#!/bin/bash

check_xdp_action=$(ip a | grep 'xdp')
if [[ -z $check_xdp_action ]]; then
  echo "Chưa kích hoạt xdp, vui lòng kích hoạt xdp"
  exit
fi

. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn triển khai ddos xdp block log:"
echo ""
lua_chon_NAME
. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

dnf install golang -y

if [[ -f /etc/systemd/system/ddos-blocker-nftables.service ]]; then
  rm -f /etc/systemd/system/ddos-blocker-nftables.service
fi

if [[ ! -f /etc/systemd/system/ddos-blocker-nftables.service ]]; then
  # 1. Biên dịch lại file C
  cd /etc/wptt/bao-mat/nftables
  rm -f xdp_blocker.o
  clang -O2 -g -target bpf -c xdp_blocker.c -o xdp_blocker.o
  # 2. Gỡ chương trình XDP cũ ra khỏi card mạng (quan trọng!)
  sudo bpftool net detach xdp dev eth0

  # 3. Tải lại chương trình XDP mới và pin map
  sudo bpftool prog load xdp_blocker.o /sys/fs/bpf/xdp_blocker_prog map pin /sys/fs/bpf/blacklist_map

  # 4. Gắn lại chương trình mới vào card mạng
  sudo bpftool net attach xdp pinned /sys/fs/bpf/xdp_blocker_prog dev eth0
  mkdir -p /usr/local/lsws/$NAME/bao-mat
  cd /usr/local/lsws/$NAME/bao-mat

  go mod init lsws-watcher
  go get github.com/cilium/ebpf
  rm -f /usr/local/lsws/$NAME/bao-mat/anti.go
  cp -f /etc/wptt/bao-mat/nftables/anti-xdp.go /usr/local/lsws/$NAME/bao-mat/anti.go
  ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')
  sed -i "/var whitelistIPs/a \"$ip\"," /usr/local/lsws/$NAME/bao-mat/anti.go
  chmod +x /usr/local/lsws/$NAME/bao-mat/anti.go
  cd /usr/local/lsws/$NAME/bao-mat && go build anti.go && chmod +x anti
  rm -f /usr/local/bin/anti
  mv /usr/local/lsws/$NAME/bao-mat/anti /usr/local/bin/
  # rm -rf /usr/local/lsws/$NAME/bao-mat
  echo '
[Unit]
Description=Go Lang Log Blocker for Litespeed
Documentation=https://your-doc-link.com # (Tùy chọn)
After=network.target nftables.service

[Service]
ExecStart=/usr/local/bin/anti

Restart=always

User=root
Group=root

RestartSec=5s

[Install]
WantedBy=multi-user.target
' >/etc/systemd/system/ddos-blocker-nftables.service
  setenforce 0
  sed -i 's/=enforcing/=disabled/g' /etc/selinux/config
  systemctl daemon-reload
  systemctl start ddos-blocker-nftables
  systemctl enable ddos-blocker-nftables
fi
