#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly status APP => status Redis"
echo "========================================================================="
echo ""
echo ""
if [[ -f /etc/redis.conf ]];then
# /usr/local/lsmcd/bin/lsmcdctrl status
systemctl status redis.service
# systemctl status lsmcd
echo "-------------------------------------------------------------------------"
echo "Hoan thanh status object cache redis"
echo "-------------------------------------------------------------------------"
echo "Tinh trang hoat dong Redis hien tai"
echo "Redis   : $(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 "
echo "-------------------------------------------------------------------------"
else
echo "Ban chua cai dat object cache Redis"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/service/wptt-status-main 1
fi

