#!/bin/bash
#find tim file được tạo và sửa đổi dưới 1640 phút (bằng 27,3 tiếng, đợi vòng cron ssl khoảng 0 giờ và 12 giờ gia hạn ssl)
if [[ $(find /etc/letsencrypt/archive -type f -mmin -1640) ]]; then
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi

