#!/bin/bash
#find tim file được tạo và sửa đổi dưới 1640 phút (bằng 27,3 tiếng, đợi vòng cron ssl khoảng 0 giờ và 12 giờ gia hạn ssl) và kiểm tra phải đáp ứng được điều kiện trong 27,3 chưa có lần nào reset -newer /usr/local/lsws/cgid -print -quit
# Tìm file SSL (.pem) được sửa đổi trong 1640 phút và mới hơn lần OLS reload cuối cùng
if [[ -n $(find /etc/letsencrypt/archive -type f -name "*.pem" -mmin -1640 -newer /usr/local/lsws/cgid -print -quit 2>/dev/null) ]]; then
    # Reload cơ chế "vừa chạy vừa thay lốp" (Zero Downtime)
	. /etc/wptt/core-functions 2>/dev/null
    wptt_smart_reload_lsws >/dev/null 2>&1
fi
