#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025

function huong_dan(){
Thiết lập cài ssl letsencrypt miễn phí bằng DNS API Cloudflare
Thay vì như bình thường bạn phải trỏ dns đúng với hệ thống thì SSL mới cài đặt được ssl letsencrypt thì bạn có thể xác thực bằng cách này
}

if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo "$ket_noi_cloudflare_dns_api_letencrypt:"
echo ""
options=(
    "Thiết lập Cloudflare API DNS"            #1
    "Xóa thiết lập Cloudflare API DNS"            #2
)
# Hàm thực thi hành động dựa trên index (cho menu Quản lý Cloudflare API DNS)
run_action() {
    local index=$1
    local script_path=""
    local script_args="98" # Tham số 98 cho các script này

    case $index in
         0) script_path="/etc/wptt/ssl/cloudflare-api-dns" ;;
         1) script_path="/etc/wptt/ssl/cloudflare-api-dns-xoa" ;;
        *) echo "Lựa chọn không hợp lệ: Index $index."; return 1 ;; # Lỗi được viết cứng do không có file ngôn ngữ
    esac

    # Kiểm tra và chạy script con
    if [[ -x "$script_path" ]]; then
        "$script_path" "$script_args"
    else
        echo "Lỗi: Không tìm thấy hoặc không thể thực thi script '$script_path'."
    fi
    # read -rp "Nhấn Enter để quay lại menu..." # Bỏ comment nếu muốn tạm dừng
}
. /etc/wptt/wptt-callback-menu-chon

