#!/bin/bash

function huong_dan(){
Tính năng SSL Lets Encrypt [sử dụng] Cloudflare API DNS là một phương pháp tự động hóa việc xin cấp và gia hạn chứng chỉ SSL miễn phí từ Lets Encrypt bằng cách sử dụng API [giao diện lập trình ứng dụng] của Cloudflare để xác thực quyền sở hữu tên miền thông qua bản ghi DNS.

Nói một cách đơn giản, thay vì phải tạo file trên web server để Lets Encrypt kiểm tra [phương pháp HTTP-01], bạn cho phép một công cụ [như Certbot, acme.sh] tự động thêm và xóa các bản ghi TXT đặc biệt trong cài đặt DNS của tên miền bạn trên Cloudflare. Lets Encrypt sẽ kiểm tra các bản ghi DNS này để xác nhận bạn là chủ sở hữu tên miền và cấp chứng chỉ.

Mục Đích Chính và Lợi Ích
 * Tự động hóa hoàn toàn: Toàn bộ quá trình từ xác thực, xin cấp đến gia hạn chứng chỉ có thể được tự động hóa hoàn toàn, kể cả với chứng chỉ wildcard.
 * Không cần thay đổi web server: Không yêu cầu web server phải truy cập được từ bên ngoài hoặc phải đặt file xác thực lên đó. Hữu ích khi web server nằm sau tường lửa chặt chẽ tường lửa chặn quốc gia hoặc webserver chưa công khai.
 * Bảo mật với API Token: Cloudflare cho phép tạo API token với quyền hạn chế [chỉ cho phép sửa đổi bản ghi DNS của một zone cụ thể], an toàn hơn so với việc dùng Global API Key.
 * Thuận tiện cho người dùng Cloudflare: Nếu bạn đã sử dụng Cloudflare làm nhà cung cấp DNS, việc này giữ mọi thứ trong cùng một hệ sinh thái.

}

echo "========================================================================="
echo "|Quản lý SSL => Quản Lý DNS API Cloudflare => Thiết lập                 |"
echo "========================================================================="

. /etc/wptt/echo-color

mkdir -p /etc/wptt/.cloudflare
function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ ! -f /etc/wptt/.cloudflare/wptt-$NAME.ini ]]; then
					selects+=("$NAME")
			fi
		done

if [[ $selects = '' ]];then
echo "Tất cả domain trên hệ thống đã được kích hoạt cloudflare api dns hết rồi"
. /etc/wptt/ssl/cloudflare-api-dns-main 1
fi

		PS3="
$(tput setab 0)-//- Nhập lựa chọn website của bạn muốn thiết lập Cloudflare DNS API [0=Thoát]:$(tput sgr0) "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Không xác định được domain"
		exit
	fi
}

echo "Lựa chọn website thiết lập Cloudflare api dns: "
    echo ""
lua_chon_NAME

path="/etc/wptt/vhost/.$NAME.conf"
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
. /etc/wptt/ssl/cloudflare-api-dns-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
. /etc/wptt/ssl/cloudflare-api-dns-main 1
    exit
fi


if [[ -f /etc/wptt/.cloudflare/wptt-$NAME.ini ]];then
echo "Xác nhận bạn đã thiết lập DNS cloudflare API"
sleep 2
. /etc/wptt/ssl/cloudflare-api-dns-main 1
exit
fi



check_dns_subdomain=$(host -t ns $NAME| grep 'has no NS record' )
if [[ $check_dns_subdomain ]];then
subdomain_to_domain=$(echo $NAME | cut -f2-5 -d '.')
check_dns=$(host -t ns $subdomain_to_domain | grep 'cloudflare')
else
check_dns=$(host -t ns $NAME | grep 'cloudflare')
fi



if [[ $check_dns = "" ]];then
echo "Xác nhận domain $NAME không sử dụng DNS cloudflare"
echo "Tính năng này để sử dụng bạn cần phải sử dụng DNS cloudflare"
sleep 3
. /etc/wptt/ssl/cloudflare-api-dns-main 1
exit
fi

echo "Mục đích tính năng này giúp cài đặt SSL letsencrypt không cần trỏ DNS về IP webserver"

read -p "Nhập Email đăng nhập đăng ký cloudflare của domain $NAME [ 0 = Thoát ]: " email_cloudflare
if [[ $email_cloudflare = "0" || $email_cloudflare = "" ]];then
. /etc/wptt/ssl/cloudflare-api-dns-main 1
exit
fi

echo "Truy cập: https://dash.cloudflare.com/profile/api-tokens => rồi ấn vào nút view màu xanh để xem API"
read -p "Nhập cloudflare Global API KEY [ 0 = Thoát ]: " KEY

if [[ $KEY = "0" || $KEY = "" ]];then
. /etc/wptt/ssl/cloudflare-api-dns-main 1
exit
fi


_runing "Thiết lập Cloudflare DNS API"
echo "Thiết lập Cloudflare DNS API website $NAME : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log
mkdir -p /etc/wptt/.cloudflare

check_install=$(ls /etc/wptt/.cloudflare | grep 'wptt')

echo "dns_cloudflare_email = $email_cloudflare
dns_cloudflare_api_key = $KEY" >> /etc/wptt/.cloudflare/wptt-$NAME.ini

chmod 700 -R /etc/wptt/.cloudflare

if [[ $check_install = "" ]];then
dnf install -y python3-cloudflare >/dev/null 2>&1
dnf install -y python3-certbot-dns-cloudflare >/dev/null 2>&1
fi


function dns_coudflare_xac_thuc_zones(){
AUTH_HEADERS=( "X-Auth-Email: $email_cloudflare" "X-Auth-Key: $KEY" )
kiem_tra_ket_noi=$(curl -X GET "https://api.cloudflare.com/client/v4/zones?name=$1" \
"${AUTH_HEADERS[@]/#/-H}" \
-H "Content-Type: application/json" \
| python3 -c "import sys,json;data=json.loads(sys.stdin.read()); print(data['result'][0]['id'] if data['result'] else '')" >/tmp/check-dns-cloudflare 2>&1)
}

if [[ $check_dns_subdomain ]];then
subdomain_to_domain=$(echo $NAME | cut -f2-5 -d '.')
dns_coudflare_xac_thuc_zones "$subdomain_to_domain"
else
dns_coudflare_xac_thuc_zones "$NAME"
fi


if [[ $(cat /tmp/check-dns-cloudflare) ]];then
_rundone "Thiết lập Cloudflare DNS API"
else
rm -f /etc/wptt/.cloudflare/wptt-$NAME.ini
_runloi "Thiết lập Cloudflare DNS API"
echoDo "Vui lòng thử lại sau"
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/ssl/cloudflare-api-dns-main 1
fi

