#!/bin/bash

echo "========================================================================="
echo "|Quản lý SSL => Quản Lý DNS API Cloudflare => Xóa thiết lập             |"
echo "========================================================================="

. /etc/wptt/echo-color

. /etc/wptt/tenmien
    echo ""
    echo ""
    echo "Lựa chọn website bạn muốn xóa thiết lập cloudflare api dns: "
    echo ""
lua_chon_NAME

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
    clear
    echoDo "Domain khong ton tai tren VPS."
    sleep 3
. /etc/wptt/ssl/cloudflare-api-dns-main 1
    exit
fi


if [[ ! -f /etc/wptt/.cloudflare/wptt-$NAME.ini ]];then
	echoDo "Bạn chưa thiết lập DNS cloudflare API"
	sleep 3
	. /etc/wptt/ssl/cloudflare-api-dns-main 1
	exit
else
	_runing "Xóa thiết lập Cloudflare API DNS"
	rm -f /etc/wptt/.cloudflare/wptt-$NAME.ini
	check_install=$(ls /etc/wptt/.cloudflare | grep 'wptt')
	if [[ $check_install = "" ]];then
		yum remove -y python2-cloudflare python2-certbot-dns-cloudflare >/dev/null 2>&1
	fi
	_runing "Xóa thiết lập Cloudflare API DNS"
fi



