#!/bin/bash

. /etc/wptt/echo-color

. /etc/wptt/tenmien
    echo ""
    echo ""
    echo "Lua chon website thiet lap cloudflare api dns: "
    echo ""
lua_chon_NAME

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
    clear
	echoDo "Domain không tồn tại trên hệ thống này"
    sleep 3
. /etc/wptt/ssl/cloudflare-api-dns-main 1
    exit
fi


if [[ -f /etc/wptt/.cloudflare/wptt-$NAME.ini ]];then
echo "Xac nhan ban da thiet lap DNS cloudflare API"
sleep 3
. /etc/wptt/ssl/cloudflare-api-dns-main 1
exit
fi



check_dns_subdomain=$(host -t ns $NAME| grep 'has no NS record' )

if [[ $check_dns_subdomain ]];then
subdomain_to_domain=$(echo $NAME | cut -f2-5 -d '.')
check_dns=$(host -t ns $subdomain_to_domain | grep 'cloudflare')
else
check_dns=$(host -t ns $NAME | grep 'cloudflare')
fi



if [[ $check_dns = "" ]];then
echo "Xác nhận domain $NAME không sử dụng DNS cloudflare"
echo "Tính năng này để sử dụng bạn cần phải sử dụng DNS cloudflare"
sleep 3
. /etc/wptt/ssl/cloudflare-api-dns-main 1
exit
fi

echo "Mục đích tính năng này giúp cài đặt SSL letsencrypt không cần trỏ DNS về IP webserver"

echo "Truy cập: https://dash.cloudflare.com/profile/api-tokens => rồi ấn vào nút view màu xanh để xem API"
read -p "Nhập cloudflare Global API KEY [ 0 = Thoát ]: " token

if [[ $token = "0" ]];then
. /etc/wptt/ssl/cloudflare-api-dns-main 1
exit
fi

read -p "Nhập Email đăng nhập cloudflare [ 0 = Thoát ]: " email_cloudflare

if [[ $email_cloudflare = "0" ]];then
. /etc/wptt/ssl/cloudflare-api-dns-main 1
exit
fi

_runing "Thiết lập Cloudflare DNS API"
mkdir -p /etc/wptt/.cloudflare

check_install=$(ls /etc/wptt/.cloudflare | grep 'wptt')

echo "dns_cloudflare_email = $email_cloudflare
dns_cloudflare_api_key = $KEY" >> /etc/wptt/.cloudflare/wptt-$NAME.ini

chmod 700 -R /etc/wptt/.cloudflare

if [[ $check_install = "" ]];then
yum install -y python2-cloudflare python2-certbot-dns-cloudflare >/dev/null 2>&1
fi

_rundone "Thiết lập Cloudflare DNS API"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/ssl/cloudflare-api-dns-main 1
fi

