#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2026

function huong_dan() {
  Tính năng Xóa SSL Lets Encrypt là quá trình gỡ bỏ một chứng chỉ SSL/TLS của Lets Encrypt đã được cài đặt cho một tên miền [website] cụ thể khỏi máy chủ web. Đồng thời, việc này thường bao gồm cả việc vô hiệu hóa cấu hình HTTPS liên quan đến chứng chỉ đó và có thể dừng tiến trình tự động gia hạn cho chứng chỉ này.

  Nói một cách đơn giản, đây là hành động gỡ bỏ ổ khóa 🔒 Lets Encrypt khỏi website của bạn, khiến website đó không còn sử dụng kết nối mã hóa HTTPS thông qua chứng chỉ Lets Encrypt đó nữa.

  Mục Đích Chính
  * Khi ngừng sử dụng website/tên miền: Nếu website không còn hoạt động, chứng chỉ SSL của nó cũng không còn cần thiết.
  * Chuyển sang loại chứng chỉ SSL khác: Khi bạn muốn sử dụng chứng chỉ từ một nhà cung cấp khác [ví dụ: chứng chỉ trả phí có xác thực tổ chức - OV, hoặc xác thực mở rộng - EV].
  * Gỡ lỗi sự cố SSL phức tạp: Trong một số trường hợp, việc xóa và cài đặt lại có thể là một bước để khắc phục sự cố.
  * Cấu hình lại máy chủ: Khi có những thay đổi lớn về cấu hình máy chủ hoặc chuyển đổi máy chủ.
  * Ngừng gia hạn tự động cho một tên miền cụ thể: Nếu bạn không muốn tên miền đó tiếp tục sử dụng HTTPS với Lets Encrypt.

  Sau khi xóa, website sẽ không còn phục vụ qua HTTPS bằng chứng chỉ Lets Encrypt đó nữa. Nếu không có chứng chỉ nào khác được cấu hình, truy cập HTTPS sẽ thất bại, và website có thể chỉ truy cập được qua HTTP [không mã hóa].
}

. /etc/wptt/.wptt.conf
[[ -z "$ngon_ngu" ]] && ngon_ngu='vi'
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/echo-color
echo -e "\n\n\n========================================================================="
echo -e "|$quan_ly_ssl => $xoa_chung_chi_ssl_letencrypt                      |"
echo -e "=========================================================================\n\n"

echo "$lua_chon_website_ban_muon $xoa_chung_chi_ssl_letencrypt: "
echo ""

function lua_chon_NAME() {
  NAME=""
  selects=()

  # Quét Vhost
  for filepath in /etc/wptt/vhost/.*.conf; do
    [[ ! -f "$filepath" || "$filepath" == *"/..conf" ]] && continue
    domain="${filepath##*/}"
    domain="${domain%.conf}"
    domain="${domain#.}"
    if [[ "$domain" == ?*.?* ]]; then
      if [[ -f "/etc/letsencrypt/live/$domain/cert.pem" || -f "/etc/letsencrypt/live/www.${domain}/cert.pem" ]]; then
        selects+=("$domain")
      fi
    fi
  done

  # Quét Domain chuyển hướng
  if [[ -d "/etc/wptt/chuyen-huong" ]]; then
    for filepath in /etc/wptt/chuyen-huong/.*.conf; do
      [[ ! -f "$filepath" || "$filepath" == *"/..conf" ]] && continue
      domain="${filepath##*/}"
      domain="${domain%.conf}"
      domain="${domain#.}"
      if [[ "$domain" == ?*.?* ]]; then
        if [[ -f "/etc/letsencrypt/live/$domain/cert.pem" || -f "/etc/letsencrypt/live/www.${domain}/cert.pem" ]]; then
          selects+=("$domain")
        fi
      fi
    done
  fi

  # Hiển thị Menu nếu có data
  if [[ ${#selects[@]} -gt 0 ]]; then
    PS3="$(tput setab 0)-//- $nhap_lua_chon_website_cua_ban [0=$exit_thoat]:$(tput sgr0) "
    select opt in "${selects[@]}"; do
      NAME=$opt
      break
    done
  else
    clear
    echoDo "Không có domain nào trước đó được cài SSL Let's Encrypt."
    echoDo "$khong_co_domain_nao_ton_tai_tren_he_thong"
    exit 1
  fi
}

lua_chon_NAME

# --- CHỐT CHẶN THOÁT HIỂM ---
[[ "$NAME" == "0" || -z "$NAME" ]] && exec /etc/wptt/wptt-ssl-main 1

CLEAN="$NAME"
. /etc/wptt/echo-color

pathcheck="/etc/wptt/vhost/.$NAME.conf"
[[ ! -f "$pathcheck" && ! -f "/etc/wptt/chuyen-huong/.$NAME.conf" ]] && {
  clear
  echoDo "$ten_mien_nay_khong_ton_tai_tren_he_thong"
  sleep 2
  exec /etc/wptt/wptt-ssl-main 1
}

check_ssl="/etc/letsencrypt/live/$NAME/cert.pem"
if [[ ! -f "$check_ssl" && ! -f "/etc/letsencrypt/live/www.${NAME}/cert.pem" ]]; then
  echoDo "Website $NAME bạn chưa cài đặt chứng chỉ SSL Let's Encrypt."
  exec /etc/wptt/wptt-ssl-main 1
fi

echo "$xac_nhan $xoa_chung_chi_ssl_letencrypt website $NAME?: "
prompt="$nhap_lua_chon_cua_ban [1-2]: "
dongy="n"
options=("$dong_y" "$khong_dong_y")
PS3="$prompt"
select opt in "${options[@]}"; do
  case "$REPLY" in
  1)
    dongy="y"
    break
    ;;
  2)
    dongy="n"
    break
    ;;
  *)
    printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
    break
    ;;
  esac
done

if [[ "$dongy" == "y" ]]; then
  UI_STRING="$xoa_chung_chi_ssl_letencrypt website $NAME"
  _runing "$UI_STRING"

  # Fix sập OLS nếu xoá SSL của Website Chính
  if [[ "$NAME" == "$Website_chinh" ]]; then
    mkdir -p "/etc/wptt-ssl-tu-ky/$NAME"
    cd "/etc/wptt-ssl-tu-ky/$NAME" || exit
    openssl req -new -newkey rsa:2048 -nodes -keyout "$NAME.key" -out "$NAME.csr" -subj "/C=VN/ST=Hanoi/L=Hanoi/O=WPTangToc OLS/OU=IT Department/CN=$NAME/emailAddress=admin@example.com" >/dev/null 2>&1
    openssl x509 -req -in "$NAME.csr" -signkey "$NAME.key" -out "cert.crt" -days 3650 >/dev/null 2>&1

    if [[ -f "/usr/local/lsws/conf/httpd_config.conf" ]]; then
      sed -i "/keyFile/d" /usr/local/lsws/conf/httpd_config.conf
      sed -i "/certFile/d" /usr/local/lsws/conf/httpd_config.conf
      sed -i "/CACertFile/d" /usr/local/lsws/conf/httpd_config.conf
      sed -i "/https/a    keyFile                \/etc\/wptt-ssl-tu-ky\/$NAME\/$NAME.key" /usr/local/lsws/conf/httpd_config.conf
      sed -i "/https/a    certFile               \/etc\/wptt-ssl-tu-ky\/$NAME\/cert.crt" /usr/local/lsws/conf/httpd_config.conf
    fi
    /usr/local/lsws/bin/lswsctrl reload >/dev/null 2>&1
  fi

  . /etc/wptt/core-functions

  # Revoke & Delete non-www
  if [[ -f "$check_ssl" ]]; then
    certbot revoke --non-interactive --agree-tos --cert-path "$check_ssl" >/dev/null 2>&1
    if wptt_kha_dung_de_xoa_xac_thuc "$CLEAN"; then
      rm -rf "/etc/letsencrypt/live/${CLEAN}"
      rm -f "/etc/letsencrypt/renewal/${CLEAN}.conf"
      rm -rf "/etc/letsencrypt/archive/${CLEAN}"
    fi
  fi

  # Revoke & Delete www
  if [[ -f "/etc/letsencrypt/live/www.${CLEAN}/cert.pem" ]]; then
    certbot revoke --non-interactive --agree-tos --cert-path "/etc/letsencrypt/live/www.${CLEAN}/cert.pem" >/dev/null 2>&1
    if wptt_kha_dung_de_xoa_xac_thuc "${CLEAN}"; then
      rm -rf "/etc/letsencrypt/live/www.${CLEAN}"
      rm -f "/etc/letsencrypt/renewal/www.${CLEAN}.conf"
      rm -rf "/etc/letsencrypt/archive/www.${CLEAN}"
    fi
  fi

  _rundone "$UI_STRING"
fi

# --- Xóa .htaccess ---
UI_STRING_HT="Xóa chuyển hướng HTTP sang HTTPS website $NAME"
_runing "$UI_STRING_HT"
path2="/usr/local/lsws/$CLEAN/html/.htaccess"

if [[ -f "$path2" ]]; then
  sed -i -e '/^#begin-chuyen-huong-http-to-https-wptangtoc-ols/,/^#end-chuyen-huong-http-to-https-wptangtoc-ols$/d' "$path2"
  sed -i -e '/^#begin-chuyen-huong-www-to-non-www-wptangtoc-ols/,/^#end-chuyen-huong-www-to-non-www-wptangtoc-ols$/d' "$path2"
  sed -i -e '/^#begin-chuyen-huong-non-www-to-www-wptangtoc-ols/,/^#end-chuyen-huong-non-www-to-www-wptangtoc-ols$/d' "$path2"
fi

/usr/local/lsws/bin/lswsctrl reload >/dev/null 2>&1
_rundone "$UI_STRING_HT"

echo "Xoá SSL free letsencrypt website $NAME: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

echo -e "\n==================================================================="
echoDone "$xoa_chung_chi_ssl_letencrypt website $CLEAN $hoan_tat             "
echo "==================================================================="

[[ ${1:-} == "98" ]] && exec /etc/wptt/wptt-ssl-main 1
