#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025

function huong_dan(){
Gia hạn chứng chỉ SSL letsencrypt thủ công. Tính năng này sẽ gia hạn xin cấp gia hạn chứng chỉ ssl letsencrypt

Ghi chú: Mặc định WPTangToc OLS có cơ chế tự động gia hạn auto vĩnh viễn rồi.
Có thể vì lý do lỗi nào đó bạn không thể gia hạn được, có thể sử dụng tính năng này
}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý SSL => Gia hạn thủ công chứng chỉ SSL FREE letsencrypt         |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/echo-color

selects=()
for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
	NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
	if [[ -f /etc/letsencrypt/live/$NAME/cert.pem ]]; then
			selects+=("$NAME")
	fi
done

if [[ $selects = '' ]];then
	echo "Tất cả domain trên hệ thống không có domain nào sử dụng SSL letsencrypt"
	. /etc/wptt/wptt-ssl-main 1
fi


echo "Bạn muốn gia hạn chứng chỉssl Free letsencrypt?: "
prompt="Nhập lựa chọn của bạn [1-2]: "
renew="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			renew="y"
			break
			;;

		2)
			renew="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


if [[ "$renew" = "y" ]]; then
	_runing "Gia hạn chứng chỉ SSL Free letsencrypt"

	echo "Gia hạn thủ công SSL free letsencrypt all: $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

	if [[ -f /etc/csf/csf.conf ]];then
		countryblicklist=`grep "CC_ALLOW_FILTER =\ " /etc/csf/csf.conf | awk 'NR==1 {print $3}' | cut -d \" -f 2`
		if [ "$countryblicklist" ]; then
			csf -x >/dev/null 2>&1
		fi
	fi


	if $(cat /etc/*release | grep -q "Ubuntu") ; then
		path_nftables_config="/etc/nftables.conf"
	else
		path_nftables_config="/etc/sysconfig/nftables.conf"
	fi

	if [[ -f $path_nftables_config ]];then
		if [[ $(cat $path_nftables_config | grep 'ipvietnam') ]];then
			systemctl stop nftables >/dev/null 2>&1
		fi
	fi

    /usr/bin/certbot renew --quiet
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

	if [[ -f /etc/csf/csf.conf ]];then
		countryblicklist=`grep "CC_ALLOW_FILTER =\ " /etc/csf/csf.conf | awk 'NR==1 {print $3}' | cut -d \" -f 2`
		if [ "$countryblicklist" ]; then
			csf -e >/dev/null 2>&1
		fi
	fi

	if [[ -f $path_nftables_config ]];then
		if [[ $(cat $path_nftables_config | grep 'ipvietnam') ]];then
			systemctl start nftables >/dev/null 2>&1
		fi
	fi

	_rundone "Gia hạn chứng chỉ SSL Free letsencrypt"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-ssl-main 1
fi


