#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2023
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý SSL => Kiểm tra chứng chỉ SSL                                  |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website bạn muốn kiếm tra chứng chỉ SSL (HTTPS):"
echo ""
lua_chon_NAME

. /etc/wptt/echo-color
. /etc/wptt/.wptt.conf

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-ssl-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-ssl-main 1
    exit
fi



echo "Đang tiến hành kiểm tra chứng chỉ SSL website $NAME"

if [[ $Website_chinh != $NAME ]];then
	ssl_web_chinh="/etc/letsencrypt/live/$Website_chinh/cert.pem"
	ssl_tra_phi_web_chinh="/usr/local/lsws/$Website_chinh/ssl/cert.crt"

	if [[ -f "$ssl_tra_phi_web_chinh" ]]; then
		ssl_web_chinh="/usr/local/lsws/$NAME/ssl/cert.crt"
	fi

	if [[ ! -f "$ssl_web_chinh" ]]; then
		echoDo "Hệ thống kiếm tra website $Website_chinh chưa được cài đặt chứng chỉ SSL nào"
		echo "Với hệ thống OpenLiteSpeed bạn phải cài SSL cho website đại diện ($Website_chinh)"
		echo "Thì các website khác mới có thể hoạt động được trên giao thức HTTPS"
		sleep 5
		. /etc/wptt/wptt-ssl-main 1
		exit
	fi
fi



checkssl=$(curl -Is https://${NAME} | head -n 1 | grep -c "200")
ssl="/etc/letsencrypt/live/$NAME/cert.pem"
ssl_tra_phi="/usr/local/lsws/$NAME/ssl/cert.pem"

if [[ -f "$ssl_tra_phi" ]]; then
	ssl="/usr/local/lsws/$NAME/ssl/cert.crt"
fi

if [[ "$checkssl" = "0" && ! -f "$ssl" ]]; then
	echoDo "Hệ thống kiếm tra website $NAME chưa được cài đặt chứng chỉ SSL nào"
	sleep 5
	. /etc/wptt/wptt-ssl-main 1
	exit
fi

if [[ "$checkssl" = "0" && -f "$ssl" ]]; then
	echo "Hệ thống kiểm tra website $NAME đã được cài đặt chứng chỉ SSL"
	echo "nhưng website $NAME không hoạt động với chứng chỉ SSL"
	echo "Vui lòng khắc phục sự cố"
	if [[ ! $(which netstat) ]];then
		yum install net-tools -y >/dev/null 2>&1
	fi
	check_open_port=$(netstat -tulpn | grep LISTEN | grep ':443')
	if [[ $check_open_port ]];then
		echo "Port 443 đang hoạt động tốt"
	else
		echo "Port 443 không hoạt động"
		echo "Hình như đã có vấn đề về tường lửa firewall (Firewall cloud) vui lòng mở cổng port 443 để sử dụng giao thức HTTPS (SSL)"
		echo "Mở tường lửa Firewall cloud hãy liên hệ với đơn vị cung cấp dịch vụ máy chủ để bạn có thể mở cổng port"

	fi
	exit
fi

echo "Xác nhận chứng chỉ SSL website $NAME đang hoạt động tốt"
echo ""
echo "Dưới đây là một số thông tin của chứng chỉ SSL hiện tại của website $NAME :"

openssl x509 -in $ssl -noout -text 

echo "Hệ thống xác nhận website $NAME đã được cài đặt thành công SSL (HTTPS)"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-ssl-main 1
fi


