#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý SSL => Cài đặt SSL Cache FREE letsencrypt                      |"
echo "========================================================================="

. /etc/wptt/echo-color

NAME=$1

if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ "$NAME" = "" ]]; then
  . /etc/wptt/tenmien
  echo ""
  echo ""
  echo "Lựa chọn website bạn muốn cài đặt chứng chỉSSL letsencrypt (HTTPS): "
  echo ""
  lua_chon_NAME
fi

if [[ $NAME = "0" || $NAME = '' ]]; then
  . /etc/wptt/wptt-ssl-main 1
fi

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" ]]; then
  clear
  echoDo "Domain không tồn tại trên VPS này."
  sleep 3
  . /etc/wptt/wptt-ssl-main 1
  exit
fi

if [[ ! -d /usr/local/lsws/$NAME/html ]]; then
  echoDo "Hệ thống không xác nhận được thư mục mã nguồn của website $NAME"
  echoDo "Thu muc ma nguon tieu chuan cua WPTangToc OLS: /usr/local/lsws/$NAME/html khong hop le"
  echoDo "Nguyen nhan dan den viec nay co the ban da thay doi cau truc thu muc hoac su dung unikey de them tien mien"
  echoDo "Vui long kiem tra lai duong dan thu muc cua ban"
  echoDo "Ho tro sua loi		: https://wptangtoc.com/lien-he/"
  exit
fi

_runing "Cài đặt chứng chỉ SSL letsencrypt cho website $NAME"

echo "Cài SSL letsencrypt no Cache website $NAME : $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

rm -f /tmp/ssl-$NAME.txt

if [[ -f "/etc/letsencrypt/live/$NAME/cert.pem" ]]; then
  echo "Bạn đã cài đặt SSL trước đó cho website $NAME rồi"
  echo "Subdomain bạn có muốn mở rộng thêm chúng chỉ SSL sử dụng cùng 1 chứng chi website $NAME"
  read -p "Bạn có muốn mở rộng chứng chỉ ssl website $NAME không ? (y/n): " renew
  if [[ "$renew" = "y" ]]; then
    . /etc/wptt/ssl/wptt-mo-rong-ssl-free $NAME
  else
    . /etc/wptt/wptt-ssl-main 1
    exit
  fi
fi

if [[ -f "/etc/letsencrypt/live/$NAME-0001/cert.pem" ]]; then
  echo "Ban da cai dat SSL cho $NAME roi"
  read -p "Ban co muon renew lai ssl khong? (y/n): " renew
  if [[ "$renew" = "y" ]]; then
    echo "Tien hanh xoa SSL cu cua ban"
    certbot revoke --cert-path /etc/letsencrypt/live/$NAME-0001/cert.pem
    rm -rf /etc/letsencrypt/live/$NAME-0001
  else
    . /etc/wptt/wptt-ssl-main 1
    exit
  fi
fi

#tu dong them subdomain multisite wordpress
if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
  check_mulsite_dang_su_dung=$(cat /usr/local/lsws/$NAME/html/wp-config.php | grep MULTISITE)
  if [[ $check_mulsite_dang_su_dung ]]; then
    sub_domain_multisite=$(wp site list --field=url --path=/usr/local/lsws/$NAME/html --allow-root 2>/dev/null | cut -f3 -d '/' | sort -u | uniq)
    echo "$sub_domain_multisite" >>/tmp/ssl-$NAME.txt
  fi
fi

#kiem tra mo rong ssl da tro ip chua
if [[ -f /tmp/ssl-$NAME.txt ]]; then
  multisite_check_dns_tro_ip_chua=($(cat /tmp/ssl-$NAME.txt))
  for multisite in ${multisite_check_dns_tro_ip_chua[@]}; do
    multisite_check_dns=$(host $multisite | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
    if [[ $multisite_check_dns != $ip ]]; then
      echo ''
      echo "domain $multisite chua tro dns ve $ip de co the cai SSL"
      sed -i "/$multisite/d" /tmp/ssl-$NAME.txt
    fi
  done
fi

echo "$NAME" >>/tmp/ssl-$NAME.txt

echo "www.$NAME" >>/tmp/ssl-$NAME.txt

# echo "Dang tien hanh cai SSL cho website $NAME..."
# list_all_ssl_thong_bao=($(cat /tmp/ssl-$NAME.txt | sort -u | sed '/^$/d' | uniq))
# for domain_ssl in ${list_all_ssl_thong_bao[@]};do
# echo "Tien hanh cai dat ssl domain: $domain_ssl"
# done

#nạp toán bộ biến tất cả subdomain và domain
list_ssl_domain_all=$(cat /tmp/ssl-$NAME.txt | sort -u | uniq | sed '/^$/d' | sed 's/^/-d /g' | tr -s '\n' ' ')

duong_dan_docroot_web=$(cat /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf | grep 'docRoot' | awk '{print $2}') #truy tìm docRoot để tương thích khi người dùng cố gắng custom đường dẫn path
# certbot certonly --non-interactive --agree-tos --register-unsafely-without-email --expand --webroot -w /usr/local/lsws/$NAME/html/ $list_ssl_domain_all >/dev/null 2>&1

certbot certonly --non-interactive --agree-tos --register-unsafely-without-email --expand --webroot -w ${duong_dan_docroot_web} $list_ssl_domain_all >/dev/null 2>&1

#setup lại vhost nếu trong trường hợp người dùng đã kích hoạt ssl trả phí trước đó để clean lại
sed -i -e '/^vhssl /,/^}$/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
echo "vhssl  {
  keyFile                 /etc/letsencrypt/live/$NAME/privkey.pem
  certFile                /etc/letsencrypt/live/$NAME/cert.pem
  certChain               0
  CACertFile              /etc/letsencrypt/live/$NAME/chain.pem
  sslProtocol             24
  renegProtection         1
  sslSessionCache         1
  sslSessionTickets       1
  enableSpdy              15
  enableQuic              1
}

" >>/usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

# tu dong chuyen thu muc www cho ve non-www nếu letsencrypt tạo thư mục www
if [[ -d /etc/letsencrypt/live/www.$NAME ]]; then
  ln -s /etc/letsencrypt/live/www.$NAME /etc/letsencrypt/live/$NAME
fi

if [[ -f /etc/letsencrypt/live/$NAME/cert.pem ]]; then
  _rundone "Cài đặt chứng chỉ SSL letsencrypt cho website $NAME"
fi

sleep 1
_runing "Tiến hành tối ưu hóa chuyển hướng HTTP sang HTTPS"
if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
  giatuanwww=$(wp option get home --path=/usr/local/lsws/$NAME/html --allow-root | grep 'www.')
  if [[ $giatuanwww ]]; then
    wp option update home "https://www.$NAME" --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 2>/dev/null
    wp option update siteurl "https://www.$NAME" --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 2>/dev/null
  else
    wp option update home "https://$NAME" --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 2>/dev/null
    wp option update siteurl "https://$NAME" --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 2>/dev/null
  fi

fi

path2="/usr/local/lsws/$NAME/html/.htaccess"

#xóa chuyển hướng http to https
#sed -i '/RewriteCond %{HTTPS} !=on/,+1d' "$path2"
sed -i -e '/^#begin-chuyen-huong-http-to-https-wptangtoc-ols/,/^#end-chuyen-huong-http-to-https-wptangtoc-ols$/d' /usr/local/lsws/$NAME/html/.htaccess
# if [[ ! -f /etc/wptt/chuyen-huong/.$NAME.conf ]];then #tương thích không thực thi lệnh này với website chuyển hướng
#xóa chuyển hướng www to non-www
sed -i -e '/^#begin-chuyen-huong-www-to-non-www-wptangtoc-ols/,/^#end-chuyen-huong-www-to-non-www-wptangtoc-ols$/d' /usr/local/lsws/$NAME/html/.htaccess
# sed -i '/RewriteCond %{HTTP_HOST} ^www/,+1d' "$path2"
#xóa chuyển hướng non-www to www
sed -i -e '/^#begin-chuyen-huong-non-www-to-www-wptangtoc-ols/,/^#end-chuyen-huong-non-www-to-www-wptangtoc-ols$/d' /usr/local/lsws/$NAME/html/.htaccess
# sed -i '/RewriteCond %{HTTP_HOST} ^'$NAME' /,+1d' "$path2"
# fi
#end xóa chuyển hướng http to https

sed -i '1 i #begin-chuyen-huong-http-to-https-wptangtoc-ols\
RewriteCond %{HTTPS} !=on\
RewriteRule ^(.*)$ https:\/\/%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]\
#end-chuyen-huong-http-to-https-wptangtoc-ols' /usr/local/lsws/"$NAME"/html/.htaccess

#chuyển hướng www to non www
sed -i '1 i #begin-chuyen-huong-www-to-non-www-wptangtoc-ols\
RewriteCond %{HTTP_HOST} ^www.'$NAME' [NC]\
RewriteRule ^(.*)$ https:\/\/'$NAME'/$1 [L,R=301,NC]\
#end-chuyen-huong-www-to-non-www-wptangtoc-ols' /usr/local/lsws/"$NAME"/html/.htaccess

_rundone "Tiến hành tối ưu hóa chuyển hướng HTTP sang HTTPS"

echo "========================================================================="
echo "Phần mềm phát triển bởi	: Gia Tuấn"
echo "========================================================================="

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
#config vhost chuyển cấu hình htaccess
. /etc/wptt/vhost/.$NAME.conf
if [[ $vhost_chuyen_htaccess ]]; then
  . /etc/wptt/wptt-vhost-chuyen-ve-htaccess $NAME >/dev/null 2>&1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-ssl-main 1
fi
