#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý SSL => Cài đặt SSL trả phí paid                                |"
echo "========================================================================="
. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color
NAME=$1
no_key=$2

if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ $NAME = "" ]];then
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website muon cai ssl tra phi (HTTPS): "
echo ""
lua_chon_NAME
fi

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-ssl-main 1
fi

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
  . /etc/wptt/wptt-ssl-main 1
    exit
fi

mkdir -p /usr/local/lsws/"$NAME"/ssl
if [[ $no_key = "" ]];then
read -p "Ban co muon tao file private key (y/n): " dongy2
fi

if [[ "$dongy2" = "y" ]];then
openssl genrsa -out /usr/local/lsws/"$NAME"/ssl/"$NAME".key 2048
openssl req -new -key /usr/local/lsws/"$NAME"/ssl/"$NAME".key -out /usr/local/lsws/"$NAME"/ssl/"$NAME".csr
echo "========================================================================="
echo "==>Copy doan key xac thuc ben nha cung cap dich vu SSL <=="
cat /usr/local/lsws/"$NAME"/ssl/"$NAME".csr
fi

if [[ "$NAME" = "$Website_chinh" ]]; then
  sed -i "/letsencrypt/d" /usr/local/lsws/conf/httpd_config.conf
  sed -i "/https/a   keyFile              \/usr\/local\/lsws\/${NAME}\/ssl\/${NAME}.key" /usr/local/lsws/conf/httpd_config.conf
  sed -i "/https/a   certFile             \/usr\/local\/lsws\/${NAME}\/ssl\/cert.crt" /usr/local/lsws/conf/httpd_config.conf
  sed -i "/https/a   CACertFile           \/usr\/local\/lsws\/${NAME}\/ssl\/ca_bundle.crt" /usr/local/lsws/conf/httpd_config.conf
fi

sed -i "/vhssl/,+15d" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf

echo "vhssl  {
  keyFile                 /usr/local/lsws/$NAME/ssl/$NAME.key
  certFile                /usr/local/lsws/$NAME/ssl/cert.crt
  certChain               0
  CACertFile              /usr/local/lsws/$NAME/ssl/ca_bundle.crt
  sslProtocol             24
  renegProtection         1
  sslSessionCache         1
  sslSessionTickets       1
  enableSpdy              15
  enableQuic              1
  enableStapling          1




}

" >>/usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf

path2="/usr/local/lsws/$NAME/html/.htaccess"
grepwww=$(grep -c 'RewriteCond %{HTTP_HOST} ^www' $path2)
grepssl=$(grep -c 'RewriteCond %{HTTPS} !=on' $path2)

if [[ "$grepssl" != "0" ]]; then
  if [[ "$grepwww" = "0" ]]; then
    sed -i '/RewriteCond %{HTTPS} !=on/,+1d' $path2
  else
    sed -i '/RewriteCond %{HTTP_HOST} ^www/,+3d' $path2
  fi
fi

checkdns=$(host $NAME | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
checkdnscname=$(host www.$NAME | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

if [[ "$checkdns" = "$checkdnscname" ]]; then
  sed -i '1 i RewriteCond %{HTTP_HOST} ^www.'$NAME' [NC]\
 RewriteRule ^(.*)$ https:\/\/'$NAME'/$1 [L,R=301,NC]\
 RewriteCond %{HTTPS} !=on\
 RewriteRule ^(.*)$ https:\/\/%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]' /usr/local/lsws/"$NAME"/html/.htaccess
else
  sed -i '1 i RewriteCond %{HTTPS} !=on\
RewriteRule ^(.*)$ https:\/\/%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]' /usr/local/lsws/"$NAME"/html/.htaccess
fi

if [[ $no_key = "" ]];then
if [[ "$dongy2" = "y" ]];then
echo "yeu cau uploads gom 2 file: cert.crt va ca_bundle.crt"
else
echo "yeu cau uploads gom 3 file: cert.crt va ca_bundle.crt va $NAME.key"
fi
echo "UPloads file ben don vi cung cap ssl cung cap cho ban vao thu muc: /usr/local/lsws/$NAME/ssl/"
echo "Vui long dat dung ten giong het nhu yeu cau tren roi uploads nhu yeu cau vao thu muc WPTangToc OLS yeu cau"
echo "Khi hoan tat uploads xong hay go lenh: wptt ssl-tra-phi $NAME"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-ssl-main 1
fi


