#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025

function huong_dan() {
  Tính năng Kiểm tra chứng chỉ SSL website là khả năng xem xét và xác minh các thông tin chi tiết của chứng chỉ SSL/TLS mà một trang web đang sử dụng để thiết lập kết nối HTTPS an toàn. Điều này giúp bạn đánh giá tính hợp lệ và độ tin cậy của kết nối đó.

  Nói một cách đơn giản, đây là cách bạn soi xem giấy phép bảo mật [chứng chỉ SSL] của một website có những thông tin gì, có còn hạn hay không, và do ai cấp.

  Mục Đích Chính
  * Xác minh danh tính website: Đảm bảo bạn đang kết nối đúng với website mình muốn, không phải trang giả mạo.
  * Kiểm tra thời hạn chứng chỉ: Xem ngày cấp và quan trọng nhất là ngày hết hạn để biết chứng chỉ có còn hiệu lực không.
  * Biết được đơn vị cấp [CA]: Xem tổ chức nào đã cấp chứng chỉ [ví dụ: Lets Encrypt, DigiCert, Sectigo].
  * Gỡ lỗi sự cố HTTPS: Khi website báo lỗi kết nối SSL [ví dụ: trình duyệt cảnh báo không an toàn], việc kiểm tra chứng chỉ giúp tìm ra nguyên nhân.
  * Đánh giá mức độ bảo mật: Xem các thông tin kỹ thuật của chứng chỉ như thuật toán chữ ký, độ dài khóa.
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

NAME=$1
if [[ $NAME = "98" ]]; then
  echo ""
  echo ""
  echo ""
  echo "========================================================================="
  echo "|Quản lý SSL => Kiểm tra chứng chỉ SSL                                  |"
  echo "========================================================================="
  NAME=""
fi

if [[ $NAME = "" ]]; then
  . /etc/wptt/tenmien-them-lua-chon-tat-ca-website
  echo ""
  echo ""
  echo "Lựa chọn website bạn muốn kiếm tra chứng chỉ SSL (HTTPS):"
  echo ""
  lua_chon_NAME
fi

if [[ $NAME = 'Tất cả website' ]]; then
  if [ "$(ls -A /etc/wptt/vhost)" ]; then
    for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
      domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      path_html="/usr/local/lsws/$domain/html"
      i=1
      if [ "$domain" != "${domain/./}" ] && [ "$domain" != '.' ]; then #điều kiện domain phải có dấu . và lỗi chỉ có only .
        if [[ -d "$path_html" ]]; then
          . /etc/wptt/ssl/wptt-kiem-tra-ssl $domain
        fi
      fi
    done
  fi

  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    . /etc/wptt/wptt-ssl-main 1
  fi
  exit
fi

. /etc/wptt/echo-color
. /etc/wptt/.wptt.conf

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-ssl-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . /etc/wptt/wptt-ssl-main 1
  exit
fi

unset ssl_xac_thuc_kha_dung
. /etc/wptt/ssl/check-ssl-cert-con-kha-dung $NAME

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color - Reset về màu mặc định

if [[ $ssl_xac_thuc_kha_dung = 'true' ]]; then
  echo -e "website $NAME chứng chỉ ssl ${GREEN} vẫn đang khả dụng ${NC}"
else
  echo -e "website $NAME chứng chỉ ssl ${RED}đang không khả dụng ${NC}"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-ssl-main 1
fi
