#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2024

. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color

NAME=$1
if [[ $NAME = '98' ]];then
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý SSL => Cài đặt tự động cài đặt ssl SSL FREE letsencrypt        |"
echo "========================================================================="
NAME=''
fi

if [[ $NAME = '' ]];then
function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ -d /usr/local/lsws/$NAME/html ]];then
				if [[ ! -f "/etc/letsencrypt/live/$NAME/cert.pem" && ! -d /usr/local/lsws/$NAME/ssl ]]; then
					if [ "$NAME" != "${NAME/./}" ]; then
						selects+=("$NAME")
					fi
				fi
			fi
		done

		if [[ $selects = '' ]];then
			echo "Tất cả website được cài ssl hết trước đó rồi"
			exit
		fi

#check tổng số website, nếu 2 website trở lên thì sẽ tự động có tính năng tất cả
		a=0
		for select in ${selects[@]};do
			a=$(expr $a + 1)
		done

		if [[ $a != 1 ]];then
			selects+=("Tat-ca-website")
		fi
PS3="
-//- Lựa chọn website bạn muốn tự động cài đặt ssl letsencrypt:  "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Không có domain nào tồn tại trên hệ thống."
	fi
}

lua_chon_NAME
fi

if [[ $NAME = 'Tat-ca-website' ]];then
	if [ "$(ls -A /etc/wptt/vhost|sort -uV)" ]; then
		for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path_html="/etc/letsencrypt/live/$domain"
			i=1
			if [[ ! -d "$path_html" ]]; then
				. /etc/wptt/ssl/cai-ssl-all-free $domain
			fi
		done
	fi
	exit
fi


if [[ $NAME = "0" || $NAME = '' ]];then
    . /etc/wptt/wptt-ssl-main 1
fi


path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" ]]; then
	clear
	echoDo "Domain không tồn tại trên VPS này."
	sleep 3
	. /etc/wptt/wptt-ssl-main 1
	exit
fi


if [[ -d /etc/letsencrypt/live/$NAME || -d /usr/local/lsws/$NAME/ssl ]];then
	echo "Đã kích hoạt ssl trước đó rồi"
	if [[ -f /etc/cron.d/cai-ssl-auto-$NAME-tu-dong.cron ]];then
		rm -f /etc/cron.d/cai-ssl-auto-$NAME-tu-dong.cron
		systemctl restart crond.service
		if $(cat /etc/*release | grep -q "Ubuntu") ; then
			NAME_CRON_ubuntu=${NAME//[.]/_}
		rm -f /etc/cron.d/cai-ssl-auto-$NAME_CRON_ubuntu-tu-dong_cron
		systemctl restart cron.service
		fi
	fi
	return 2>/dev/null; exit
fi

if [[ -f /etc/cron.d/cai-ssl-auto-$NAME-tu-dong.cron ]];then
	echo "Đã kích hoạt tự động cài ssl"
	return 2>/dev/null; exit
fi

cat >"/etc/cron.d/cai-ssl-auto-$NAME-tu-dong.cron" <<END
*/2 * * * * root /etc/wptt/ssl/crond-ssl-auto/check-tro-ip-vs-run $NAME >/dev/null 2>&1
END

if $(cat /etc/*release | grep -q "Ubuntu") ; then
	NAME_CRON_ubuntu=${NAME//[.]/_}
	ln -sf /etc/cron.d/cai-ssl-auto-$NAME-tu-dong.cron /etc/cron.d/cai-ssl-auto-${NAME_CRON_ubuntu}-tu-dong_cron
	systemctl restart cron.service
else
	systemctl restart crond.service
fi
echo "Tự động kiểm tra và tiến hành cài ssl cứ 2 phút 1 lần cho website $NAME"
