#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý SSL => Cài đặt SSL FREE letsencrypt                            |"
echo "========================================================================="

. /etc/wptt/echo-color

NAME=$1

if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ "$NAME" = "" ]]; then
    . /etc/wptt/tenmien
    echo ""
    echo ""
    echo "Lựa chọn website bạn muốn cài đặt chứng chỉSSL letsencrypt (HTTPS): "
    echo ""
    lua_chon_NAME
fi

if [[ $NAME = "0" || $NAME = '' ]];then
    . /etc/wptt/wptt-ssl-main 1
fi

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" ]]; then
    clear
    echoDo "Domain không tồn tại trên VPS này."
    sleep 3
    . /etc/wptt/wptt-ssl-main 1
    exit
fi



if [[ ! -d /usr/local/lsws/$NAME/html ]]; then
	echoDo "Hệ thống không xác nhận được thư mục mã nguồn của website $NAME"
    echoDo "Thu muc ma nguon tieu chuan cua WPTangToc OLS: /usr/local/lsws/$NAME/html khong hop le"
    echoDo "Nguyen nhan dan den viec nay co the ban da thay doi cau truc thu muc hoac su dung unikey de them tien mien"
    echoDo "Vui long kiem tra lai duong dan thu muc cua ban"
    echoDo "Ho tro sua loi		: https://wptangtoc.com/lien-he/"
    exit
fi

if [[ -f /etc/wptt/.cloudflare/wptt-$NAME.ini ]];then
echo "Tiến hành cài SSL phương pháp Cloudflare API DNS"
. /etc/wptt/ssl/wptt-caissl-cloudlflare-api-dns $NAME 98
return 2>/dev/null ; exit
fi


check_http_online=$(curl -Is http://$NAME)
if [[ $check_http_online = "" ]];then
echo "Kiểm tra website $NAME không hoạt động vì vậy không thế cài đặt được chứng chỉ SSL"
. /etc/wptt/wptt-ssl-main 1
return 2>/dev/null ; exit
fi

_runing "Cài đặt chứng chỉ SSL letsencrypt cho website $NAME"

checkdns=$(host $NAME | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
checkdns2=$(nslookup $NAME | grep Address | cut -f5 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')


ip=$(ip a | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | sed '/127.0.0.1/d' | sed '/192.168/d' | sort -u)

ip+=$(curl -s myip.directadmin.com)

# if [[ $ip = '' ]];then
# 	ip=$(curl -s myip.directadmin.com)
# 	if [[ "$ip" = "" ]]; then
# 		ip=$(curl -s ifconfig.me)
# 	fi
# fi


#xac thuc kiểm tra đã trỏ ip dns chưa
if ! [[ $(echo $ip | grep $checkdns) || $(echo $ip | grep $checkdns2) ]]; then
    checknameserver=$(host -t ns $NAME)
	_runloi "Cài đặt chứng chỉ SSL letsencrypt cho website $NAME"
	echo "Cài đặt chứng chỉSSL không thành công - thông báo lỗi"
	echo "Bạn chưa trỏ tên miền DNS $NAME về máy chủ IP: $ip mới"
	echo "Hãy trỏ DNS thì mới có thể cài được chứng chỉSSL"
	echo "Hãy trỏ DNS $checkdns thành $ip rồi quay trở lại để cài chứng chỉSSL"
    if [[ "$checkdns" = "" ]]; then
        echo "Tên miền $NAME chưa được trỏ IP. Giá trị IP của $NAME là không có giá trị nào, bạn vui lòng trỏ IP về $ip"
    fi
	echo "Tên miền $NAME đang được quản lý bởi $checknameserver bạn hãy truy cập vào để trỏ tên miền của mình về $ip"
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-ssl-main 1
	fi
return 2>/dev/null ; exit
fi

checkdnscname=$(host www.$NAME | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
checkdnscname2=$(nslookup www.$NAME | grep Address | cut -f5 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

if [[ $checkdnscname = '' ]];then
checkdnscname='172.168.0.1'
fi

if [[ $checkdnscname2 = '' ]];then
checkdnscname2='172.168.0.1'
fi

check_dev_wptangtoc=$(curl -Is http://$NAME | grep 'WPTangTocOLS')
if [[ $check_dev_wptangtoc = "" ]];then
_runloi "Cài đặt chứng chỉ SSL letsencrypt cho website $NAME"
echoDo "Bạn không thể cài đặt chứng chỉ SSL"
echoDo "Vui lòng liên hệ với tác giả Gia Tuấn để được trợ giúp"
    . /etc/wptt/wptt-ssl-main 1
return 2>/dev/null ; exit
fi


rm -f /tmp/ssl-$NAME.txt

if [[ -f "/etc/letsencrypt/live/$NAME/cert.pem" ]]; then
    echo "Bạn đã cài đặt SSL trước đó cho website $NAME rồi"
	echo "Subdomain bạn có muốn mở rộng thêm chúng chỉ SSL sử dụng cùng 1 chứng chi website $NAME"
    read -p "Bạn có muốn mở rộng chứng chỉ ssl website $NAME không ? (y/n): " renew
    if [[ "$renew" = "y" ]]; then
		. /etc/wptt/ssl/wptt-mo-rong-ssl-free $NAME
    else
    . /etc/wptt/wptt-ssl-main 1
        exit
    fi
fi

if [[ -f "/etc/letsencrypt/live/$NAME-0001/cert.pem" ]]; then
    echo "Ban da cai dat SSL cho $NAME roi"
    read -p "Ban co muon renew lai ssl khong? (y/n): " renew
    if [[ "$renew" = "y" ]]; then
        echo "Tien hanh xoa SSL cu cua ban"
        certbot revoke --cert-path /etc/letsencrypt/live/$NAME-0001/cert.pem
        rm -rf /etc/letsencrypt/live/$NAME-0001
    else
    . /etc/wptt/wptt-ssl-main 1
        exit
    fi
fi


#tu dong them subdomain multisite wordpress
if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
check_mulsite_dang_su_dung=$(cat /usr/local/lsws/$NAME/html/wp-config.php | grep MULTISITE)
if [[ $check_mulsite_dang_su_dung ]];then
	sub_domain_multisite=$(wp site list --field=url --path=/usr/local/lsws/$NAME/html --allow-root 2>/dev/null | cut -f3 -d '/' | sort -u | uniq)
	echo "$sub_domain_multisite" >> /tmp/ssl-$NAME.txt
fi
fi

#kiem tra mo rong ssl da tro ip chua
if [[ -f /tmp/ssl-$NAME.txt ]];then
	multisite_check_dns_tro_ip_chua=($(cat /tmp/ssl-$NAME.txt))
	for multisite in ${multisite_check_dns_tro_ip_chua[@]};do
		multisite_check_dns=$(host $multisite | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
		if [[ $multisite_check_dns != $ip ]];then
echo ''
echo "domain $multisite chua tro dns ve $ip de co the cai SSL"
sed -i "/$multisite/d" /tmp/ssl-$NAME.txt
		fi
	done
fi

echo "$NAME" >> /tmp/ssl-$NAME.txt

if [[ "$checkdns" = "$checkdnscname" || "$checkdns2" = "$checkdnscname2" || "$checkdns" = "$checkdnscname2" || "$checkdns2" = "$checkdnscname" ]]; then
	echo "www.$NAME" >> /tmp/ssl-$NAME.txt
fi

# echo "Dang tien hanh cai SSL cho website $NAME..."
# list_all_ssl_thong_bao=($(cat /tmp/ssl-$NAME.txt | sort -u | sed '/^$/d' | uniq))
# for domain_ssl in ${list_all_ssl_thong_bao[@]};do
# echo "Tien hanh cai dat ssl domain: $domain_ssl"
# done


#nạp toán bộ biến tất cả subdomain và domain
list_ssl_domain_all=$(cat /tmp/ssl-$NAME.txt | sort -u |uniq |sed '/^$/d' | sed 's/^/-d /g' | tr -s '\n' ' ')

#tiến hành thực thi cài đặt ssl
certbot certonly --non-interactive --agree-tos --register-unsafely-without-email --expand --webroot -w /usr/local/lsws/$NAME/html/ $list_ssl_domain_all >/dev/null 2>&1

#setup lại vhost nếu trong trường hợp người dùng đã kích hoạt ssl trả phí trước đó để clean lại
sed -i -e '/^vhssl /,/^}$/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
echo "vhssl  {
  keyFile                 /etc/letsencrypt/live/$NAME/privkey.pem
  certFile                /etc/letsencrypt/live/$NAME/cert.pem
  certChain               0
  CACertFile              /etc/letsencrypt/live/$NAME/chain.pem
  sslProtocol             24
  renegProtection         1
  sslSessionCache         1
  sslSessionTickets       1
  enableSpdy              15
  enableQuic              1
  enableStapling          1
  ocspRespMaxAge          86400
  ocspResponder           http://cert.int-x3.letsencrypt.org/
  ocspCACerts             /etc/letsencrypt/live/$NAME/chain.pem
}

" >>/usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

# tu dong chuyen thu muc www cho ve non-www nếu letsencrypt tạo thư mục www
if [[ -d /etc/letsencrypt/live/www.$NAME ]];then
ln -s /etc/letsencrypt/live/www.$NAME /etc/letsencrypt/live/$NAME
fi

checkssl2=$(curl -Is https://${NAME} | grep -c "WPTangTocOLS")
if [[ ! -f "/etc/letsencrypt/live/$NAME/cert.pem" || "$checkssl2" = "0" ]]; then
	_runloi "Cài đặt chứng chỉ SSL letsencrypt cho website $NAME"
    echoDo "Quá trình cài đặt SSL không thành công, đã xảy ra sự cố"
    if [[ -f "/etc/letsencrypt/live/$NAME/cert.pem" ]]; then
        echo "Chứng chỉ SSL của bạn đã được cài đặt, kiểm tra thực tế https://$NAME thì không hoạt động"
        . /etc/wptt/.wptt.conf
        if [[ "$Website_chinh" != "$NAME" && ! -f "/etc/letsencrypt/live/$Website_chinh/cert.pem" && ! -d "/usr/local/lsws/$Website_chinh/ssl" ]]; then
            echo "Website chính $Website_chinh chưa được cài đặt SSL"
			echo "vui lòng cài đặt SSL cho website $Website_chinh trước thì các website khác mới mới có thể sử dụng HTTPS"
        fi
    else
        echo "Chứng chỉ SSL cài đặt không thành công, bạn có thể xem nguyên nhân không cài được SSL tại đây: /var/log/letsencrypt"
    fi

		if [[ -f "/etc/letsencrypt/live/$NAME-0001/cert.pem" && ! -f "/etc/letsencrypt/live/$NAME/cert.pem" ]];then
clear
echo "Tien hanh fix loi ssl"
sed -i "s:/etc/letsencrypt/live/$NAME:/etc/letsencrypt/live/$NAME-0001:g" /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
echo "Chuyen doi cai ssl 2 lan lien tiep"
echoDone "Hoan tat kich hoat lai SSL"
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
		fi
		exit
	else
		_rundone "Cài đặt chứng chỉ SSL letsencrypt cho website $NAME"
fi
sleep 1
_runing "Tiến hành tối ưu hóa chuyển hướng HTTP sang HTTPS"
if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
    giatuanwww=$(wp option get home --path=/usr/local/lsws/$NAME/html --allow-root | grep 'www.')
    if [[ $giatuanwww ]]; then
        wp option update home "https://www.$NAME" --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 2>/dev/null
        wp option update siteurl "https://www.$NAME" --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 2>/dev/null
    else
        wp option update home "https://$NAME" --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 2>/dev/null
        wp option update siteurl "https://$NAME" --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 2>/dev/null
    fi

fi

path2="/usr/local/lsws/$NAME/html/.htaccess"

#clear chuyen huong cu
grepwww=$(grep -c 'RewriteCond %{HTTP_HOST} ^www' $path2)
grepssl=$(grep -c 'RewriteCond %{HTTPS} !=on' $path2)

if [[ "$grepssl" != "0" ]]; then
    if [[ "$grepwww" = "0" ]]; then
		#xóa chuyển hướng non www to www công nghệ cũ
        sed -i '/RewriteCond %{HTTPS} !=on/,+1d' "$path2"
    else
		#xoa chuyển hướng www to non www và ngược lại
        sed -i '/RewriteCond %{HTTP_HOST} ^www/,+3d' "$path2"
        sed -i '/RewriteCond %{HTTP_HOST} !^www/,+3d' "$path2"
    fi
fi

if [[ "$checkdns" = "$checkdnscname" || "$checkdns2" = "$checkdnscname2" || "$checkdns" = "$checkdnscname2" || "$checkdns2" = "$checkdnscname" ]]; then
    sed -i '1 i RewriteCond %{HTTP_HOST} ^www.'$NAME' [NC]\
RewriteRule ^(.*)$ https:\/\/'$NAME'/$1 [L,R=301,NC]\
RewriteCond %{HTTPS} !=on\
RewriteRule ^(.*)$ https:\/\/%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]' /usr/local/lsws/"$NAME"/html/.htaccess
else
    sed -i '1 i RewriteCond %{HTTPS} !=on\
RewriteRule ^(.*)$ https:\/\/%{HTTP_HOST}%{REQUEST_URI} [L,R=301,NE]' /usr/local/lsws/"$NAME"/html/.htaccess
fi

if [[ $giatuanwww ]]; then
if [[ "$checkdns" = "$checkdnscname" || "$checkdns2" = "$checkdnscname2" || "$checkdns" = "$checkdnscname2" || "$checkdns2" = "$checkdnscname" ]]; then

        if [[ "$grepssl" != "0" ]]; then
            if [[ "$grepwww" = "0" ]]; then
                sed -i '/RewriteCond %{HTTPS} !=on/,+1d' "$path2"
            else
                sed -i '/RewriteCond %{HTTP_HOST} ^www/,+3d' "$path2"
            fi
        fi
        sed -i '1 i RewriteCond %{HTTPS} !=on [NC]\
RewriteRule ^(.*)$ https:\/\/%{HTTP_HOST}/$1 [R=301,L]' /usr/local/lsws/"$NAME"/html/.htaccess
    fi
fi

function box_out() {
    local s=("$@") b w
    for l in "${s[@]}"; do
        ((w < ${#l})) && {
            b="$l"
            w="${#l}"
        }
    done
    tput setaf 7
    echo " -${b//?/-}-
| ${b//?/ } |"
    for l in "${s[@]}"; do
        printf '| %s%*s%s |\n' "$(tput setaf 7)" "-$w" "$l" "$(tput setaf 3)"
    done
    echo "| ${b//?/ } |
 -${b//?/-}-"
    tput sgr 0
}

if [[ "$checkdns" = "$checkdnscname" || "$checkdns2" = "$checkdnscname2" || "$checkdns" = "$checkdnscname2" || "$checkdns2" = "$checkdnscname" ]]; then
    chuyenhuongwww="Tu dong chuyen huong www.$NAME sang $NAME"
fi

_rundone "Tiến hành tối ưu hóa chuyển hướng HTTP sang HTTPS"

echo "========================================================================="
echo "Phần mềm phát triển bởi	: Gia Tuấn"
echo "========================================================================="
if [[ "$renew" = "y" ]]; then
    echo "========================================================================="
    echo "SSL cua $NAME da duoc renew"
    echo "========================================================================="
fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
#config vhost chuyển cấu hình htaccess
. /etc/wptt/vhost/.$NAME.conf
if [[ $vhost_chuyen_htaccess ]];then
. /etc/wptt/wptt-vhost-chuyen-ve-htaccess $NAME >/dev/null 2>&1
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-ssl-main 1
fi

