#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly PHP => Thay doi version php                                    |"
echo "========================================================================="
echo ""
. /etc/wptt/.wptt.conf
echo "-------------------------------------------------------------------------"
echo "Thay doi version php, phien ban php hien tai cua ban: $php_version_check"
echo "-------------------------------------------------------------------------"

echo "Ban hay lua chon phien ban PHP muon su dung [0 = Thoat]: "
prompt="Nhap vao lua chon cua ban [1-3]: "
php_version="7.4"
options=("PHP 8.0" "PHP 7.4" "PHP 7.3")
PS3="$prompt"
select opt in "${options[@]}"; do
    case "$REPLY" in
    1)
        php_version="8.0"
        break
        ;;
    2)
        php_version="7.4"
        break
        ;;

    3)
        php_version="7.3"
        break
        ;;
    $((${#options[@]} + 1)))
        printf "\nHe thong se cai dat PHP 7.4\n"
        break
        ;;
    *) wptangtoc ;;
    esac
done
clear

if [[ "$php_version" = "$php_version_check" ]]; then
    echo "Hien tai ban dang su dung phien ban php nay roi"
    exit
fi

if [[ "$php_version" = "0" || "$php_version" = "" ]]; then
    exit
fi

if [[ "$php_version" != "$php_version_check" ]]; then
    php_ver_chon=${php_version//[-._]/}

    yum install lsphp${php_ver_chon} lsphp${php_ver_chon}-json lsphp${php_ver_chon}-common lsphp${php_ver_chon}-gd lsphp${php_ver_chon}-imagick lsphp${php_ver_chon}-process lsphp${php_ver_chon}-mbstring lsphp${php_ver_chon}-mysqlnd lsphp${php_ver_chon}-xml lsphp${php_ver_chon}-opcache lsphp${php_ver_chon}-mcrypt lsphp${php_ver_chon}-pdo lsphp${php_ver_chon}-imap lsphp${php_ver_chon}-bcmath lsphp${php_ver_chon}-pecl-memcache lsphp${php_ver_chon}-pecl-memcached lsphp${php_ver_chon}-pgsql lsphp${php_ver_chon}-zip -y
    ln -sf /usr/local/lsws/lsphp${php_ver_chon}/bin/lsphp /usr/local/lsws/fcgi-bin/lsphp${php_ver_chon}
    ln -sf /usr/local/lsws/lsphp${php_ver_chon}/bin/lsphp /usr/local/lsws/fcgi-bin/lsphp5
    ln -sf /usr/local/lsws/lsphp${php_ver_chon}/bin/php /usr/bin/php
    sed -i "/opcache.memory_consumption/d" /usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini
    sed -i "/opcache.interned_strings_buffer/d" /usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini
    sed -i "/opcache.max_accelerated_files/d" /usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini
    sed -i "/opcache.revalidate_freq/d" /usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini
    sed -i "/opcache.fast_shutdown/d" /usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini
    sed -i "/opcache.enable_cli/d" /usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini
    echo 'opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.revalidate_freq=100
opcache.fast_shutdown=1
opcache.enable_cli=1' >>/usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini
    sed -i "s/expose_php = On/expose_php = off/g" /usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini
    sed -i "s/upload_max_filesize = 2M/upload_max_filesize = 8M/g" /usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini
    sed -i "s/max_execution_time = 30/max_execution_time = 120/g" /usr/local/lsws/lsphp${php_ver_chon}/etc/php.ini

    sed -i "/php_version_check/d" /etc/wptt/.wptt.conf
    echo "php_version_check=$php_version" >>/etc/wptt/.wptt.conf

    sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/httpd_config.conf

    if [ "$(ls -A /etc/wptt/vhost)" ]; then
        echo
        echo "dang cap nhat chuyen doi version php $php_version"
        echo '--------------------------------------------------'
        for entry in $(ls -A /etc/wptt/vhost); do
            domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
            path="/usr/local/lsws/$domain/html"
            i=1
            if [[ -d "$path" ]]; then
                sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/vhosts/$domain/$domain.conf
            fi
        done
        echo '--------------------------------------------------'
        echo
    fi

    /usr/local/lsws/bin/lswsctrl restart
    echo "Hoan tat viec chuyen php version $php_version"
fi
