version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "🔒 bảo mật"
      include: "scope"
# Mỗi tuần, con Robot của GitHub sẽ tự động đi kiểm tra. Nếu nó phát hiện có bản checkout hoặc gitleaks mới an toàn hơn, nó sẽ tự động dịch ngược ra mã SHA chuẩn xác nhất và tạo 1 Pull Request để xin phép bạn Merge.
