#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
RED='\033[0;31m'
NC='\033[0m'
echo -e "${RED}-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo "Cai dat WPTangToc OLS"
echo "-------------------------------------------------------------------------"
echo -e "--------------------------------------------------------------------------${NC}"

wget -q https://wptangtoc.com/share/wptangtoc-ols.zip

if [[ ! -f wptangtoc-ols.zip ]];then
echo "Cap nhat chuyen doi that bai"
exit
fi

unzip -o wptangtoc-ols.zip
cd tool-wptangtoc-ols
cd ..
\cp -rf tool-wptangtoc-ols/* /etc/wptt/
rm -f wptangtoc-ols.zip
rm -rf tool-wptangtoc-ols
rm -rf toolwptangtocols
chmod -R 740 /etc/wptt
\cp -f /etc/wptt/wptangtoc /usr/bin
rm -f /etc/wptt/wptangtoc
\cp -f /etc/wptt/wptt /usr/bin
rm -f /etc/wptt/wptt
wptangtocols_version=$(curl -s https://wptangtoc.com/share/version-wptangtoc-ols.txt?force-update)
sed -i "/version_wptangtoc_ols/d" /etc/wptt/.wptt.conf
echo "version_wptangtoc_ols=$wptangtocols_version" >>/etc/wptt/.wptt.conf
echo "$wptangtocols_version" > /tmp/wptangtoc-ols-version
rm -f ghi-de-update
RED='\033[0;31m'
NC='\033[0m'
echo -e "${RED}
     .:..........................             
      .::::::::::::::::::::::::::::..         
        ..:::::::::::::::::::::::::::::.      
                             ...:::::::::.    
                                  .:::::::.   
          .:::::::.         .       .:::::::  
         .::::::::::::::::::::..      ::::::: 
         ::::::::::::::::::::::::.     ::::::.
        .::::::::::::::::::::::::::.   .:::::.
        .::::::::::::::::::::::::::::  .:::::.
        .::::::::::::::::::::::::::.   .:::::.
         ::::::::::::::::::::::::.     ::::::.
.::::::  .:::::::::::::::::::::.      ::::::. 
          .:::::::.                 .:::::::  
       ::::::::::::.              .:::::::.   
       ......:::::::::...    ...:::::::::.    
               .:::::::::::::::::::::::.      
   ..............::::::::::::::::::..         
  .:::::::::::::................. ${NC}"
  
echo "-------------------------------------------------------------------------"
echo -e "${RED}-------------------------------------------------------------------------"
echo "Cai dat WPTangToc OLS $wptangtocols_version"
echo "-------------------------------------------------------------------------"
echo -e "--------------------------------------------------------------------------${NC}"
echo "-------------------------------------------------------------------------"
