#!/bin/bash

domain_them=$(cat /usr/local/lsws/*/html/danh-sach-website-wptangtoc-ols.txt)

if [[ $domain_them = '' ]]; then
  echo "Không xác định được danh sách"
  exit
fi
rm -f /usr/local/lsws/*/html/danh-sach-website-wptangtoc-ols.txt

domain_trung_lap=($(ls -A /etc/wptt/vhost | sed 's/^.//' | sed 's/.conf//'))

echo '--------------------------------------------------'
for NAME in ${domain_them[@]}; do
  sleep 3
  if [[ ! "${domain_trung_lap[@]}" =~ "${NAME}" ]]; then
    echo "Them domain $NAME vao WPTangToc OLS"
    . /etc/wptt/domain/wptt-themwebsite $NAME
    rm -f /usr/local/lsws/$NAME/html/index.html
    #subfolder add website
    if [[ -f /usr/local/lsws/$NAME/html/subfolder-wptt.txt ]]; then
      for thumuc in $(cat /usr/local/lsws/$NAME/html/subfolder-wptt.txt); do
        . /etc/wptt/domain/wptt-subfolder-website "$NAME" "$thumuc"
      done
    fi
  fi
done
echo '--------------------------------------------------'

clear
. /etc/wptt/.wptt.conf

for NAME in ${domain_them[@]}; do
  if [[ -f /usr/local/lsws/$NAME/html/giatuan-wptangtoc.sql ]]; then
    echo "Chuyển website $NAME"
    . /etc/wptt/vhost/.$NAME.conf
    mariadb -u "$database_admin_username" -p"$database_admin_password" -e "DROP DATABASE IF EXISTS ${DB_Name_web}"
    mariadb -u "$database_admin_username" -p"$database_admin_password" -e "CREATE DATABASE IF NOT EXISTS ${DB_Name_web}"
    mariadb -u "$database_admin_username" -p"$database_admin_password" -e "DROP USER IF EXISTS '${DB_User_web}'@'localhost'"
    mariadb -u "$database_admin_username" -p"$database_admin_password" -e "CREATE USER IF NOT EXISTS '${DB_User_web}'@'localhost' IDENTIFIED BY '${DB_Password_web}'"
    mariadb -u "$database_admin_username" -p"$database_admin_password" -e "GRANT ALL PRIVILEGES ON ${DB_Name_web}.* TO '${DB_User_web}'@'localhost' WITH GRANT OPTION"
    mariadb -u "$database_admin_username" -p"$database_admin_password" -e "FLUSH PRIVILEGES"

    mariadb -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web" --force </usr/local/lsws/$NAME/html/giatuan-wptangtoc.sql
    rm -f /usr/local/lsws/$NAME/html/giatuan-wptangtoc.sql
    . /etc/wptt/db/wptt-ket-noi $NAME >/dev/null 2>&1
    . /etc/wptt/wptt-phanquyen $NAME
  fi

  if [[ -d /usr/local/lsws/$NAME/logs ]]; then
    sed -i -e '/^errorlog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
    sed -i -e '/^accesslog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
    echo '
errorlog $VH_ROOT/logs/error.log {
useServer               1
logLevel                ERROR
rollingSize             10M
}

accesslog $VH_ROOT/logs/access.log {
useServer               0
rollingSize             10M
keepDays                30
compressArchive         1
}' >>/usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf

  fi

  if [[ -f /usr/local/lsws/$NAME/html/subfolder-wptt.txt ]]; then
    domain_all=$(find /usr/local/lsws/$NAME/html -type f -name 'wp-config.php')
    for entry in ${domain_all[@]}; do
      path=$(echo $entry | sed 's/\/wp-config.php//g')
      i=1

      #bypass website gốc
      thumuc=$(echo $path | cut -f7 -d '/')
      if [[ $thumuc = '' ]]; then
        continue
      fi

      if [[ -f "$path/wp-config.php" ]]; then
        cd $path && curl -sO https://wptangtoc.com/giatuan/wptt-import-db && bash wptt-import-db
        rm -f $path/giatuan-wptangtoc.sql
      fi
    done
    rm -f /usr/local/lsws/$NAME/html/subfolder-wptt.txt
  fi
done

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
rm -f wptt-rsync-move
rm -f ~/wptt-rsync-move
echo "Hoan tat chuyen toan bo website"
ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')
if [[ -z $ip ]]; then #bài toán nếu webserver chỉ hỗ trợ mỗi ipv6 không hỗ trợ ipv4
  ip=$(curl -sk --connect-timeout 5 --max-time 10 https://ipv6.icanhazip.com)
fi
echo "hãy trỏ ip các website về IP: $ip va tien hanh cai dat ssl de su dung"
