#!/bin/bash
. /etc/wptt/core-functions 2>/dev/null
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025
function huong_dan() {
    cat << 'EOF'
  Tính năng Gửi feedback cho tác giả trong phần mềm WPTangToc OLS là một kênh liên lạc quan trọng cho phép người dùng đóng góp ý kiến, báo lỗi, hoặc đề xuất cải tiến trực tiếp đến người đã phát triển ra công cụ đó.

  Mục đích chính của tính năng này:
  * Báo lỗi [Bug Report]: Giúp người dùng thông báo cho tác giả về bất kỳ lỗi nào họ gặp phải khi sử dụng WPTangToc OLS, kèm theo mô tả chi tiết để tác giả có thể kiểm tra và khắc phục.
  * Đề xuất tính năng mới [Feature Request]: Người dùng có thể gợi ý những chức năng mới hoặc cải tiến cho các tính năng hiện có mà họ cảm thấy sẽ hữu ích cho WPTangToc OLS.
  * Đóng góp ý kiến chung: Chia sẻ trải nghiệm sử dụng, những điểm hài lòng hoặc chưa hài lòng về công cụ.
  * Yêu cầu hỗ trợ [trong một số trường hợp]: Mặc dù kênh feedback không luôn là kênh hỗ trợ chính thức, nhưng đôi khi người dùng cũng có thể đặt câu hỏi hoặc nhờ trợ giúp qua đây.

  Để gửi feedback cho tác giả WPTangToc OLS, bạn nên tìm kiếm các thông tin liên hệ hoặc đường dẫn hỗ trợ được cung cấp trong tài liệu hướng dẫn, trong các thông báo của script khi chạy, hoặc trên các trang web/diễn đàn nơi WPTangToc OLS được giới thiệu và thảo luận [ví dụ như nhóm FaceBook cộng đồng tăng tốc WordPress, hoặc trang GitHub].
EOF
}

. /etc/wptt/.wptt.conf
if [[ -z "$ngon_ngu" ]]; then
  ngon_ngu='vi'
fi
. "/etc/wptt/lang/$ngon_ngu.sh"

echp "Email liên hệ: giatuan@wptangtoc.com
** Liên hệ trao đổi trực tiếp:** qua Zalo 0866880462 (Gia Tuấn)"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  exec /usr/bin/wptangtoc 1
fi
exit 1



