#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly SSL => Xoa tra phi paid                                        |"
echo "========================================================================="


. /wptt/wptt/.wptt.conf

. /etc/wptt/tenmien
echo ""
echo ""
echo "lua chon website muon xoa SSL tra phi (HTTPS): "
echo ""
lua_chon_NAME

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
  clear
  echo "Domain khong ton tai tren VPS."
  . /etc/wptt/wptt-ssl-main
  exit
fi

if [[ "$NAME" = "$Website_chinh" ]]; then
  sed -i "/keyFile/d" /usr/local/lsws/conf/httpd_config.conf
  sed -i "/certFile/d" /usr/local/lsws/conf/httpd_config.conf
  sed -i "/CACertFile/d" /usr/local/lsws/conf/httpd_config.conf
  sed -i "/https/a keyFile              \/etc\/letsencrypt\/live\/$NAME\/privkey.pem" /usr/local/lsws/conf/httpd_config.conf
  sed -i "/https/a certFile             \/etc\/letsencrypt\/live\/$NAME\/cert.pem" /usr/local/lsws/conf/httpd_config.conf
  sed -i "/https/a CACertFile           \/etc\/letsencrypt\/live\/$NAME\/chain.pem" /usr/local/lsws/conf/httpd_config.conf
fi

sed -i "/vhssl/,+15d" /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

echo "vhssl  {
  keyFile                 /etc/letsencrypt/live/$NAME/privkey.pem
  certFile                /etc/letsencrypt/live/$NAME/cert.pem
  certChain               0
  CACertFile              /etc/letsencrypt/live/$NAME/chain.pem
  sslProtocol             24
  renegProtection         1
  sslSessionCache         1
  sslSessionTickets       1
  enableSpdy              15
  enableQuic              1
  enableStapling          1
  ocspRespMaxAge          86400
  ocspResponder           http://cert.int-x3.letsencrypt.org/
  ocspCACerts             /etc/letsencrypt/live/$NAME/chain.pem
}

" >>/usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
rm -rf /usr/local/lsws/"$NAME"/ssl
/usr/local/lsws/bin/lswsctrl restart

path2="/usr/local/lsws/$NAME/html/.htaccess"
grepwww=$(grep -c 'RewriteCond %{HTTP_HOST} ^www' $path2)
grepssl=$(grep -c 'RewriteCond %{HTTPS} !=on' $path2)

if [[ "$grepssl" != "0" ]]; then
  if [[ "$grepwww" = "0" ]]; then
    sed -i '/RewriteCond %{HTTPS} !=on/,+1d' $path2
  else
    sed -i '/RewriteCond %{HTTP_HOST} ^www/,+3d' $path2
  fi
fi

echo "hoan tat qua trinh xoa SSL tra phi"
