#!/bin/bash

function huong_dan() {
  WPTangToc OLS có tính năng kiểm tra dung lượng mã nguồn website, thì đây là một chức năng tiện ích giúp bạn nhanh chóng xem được tổng kích thước [dung lượng đĩa] mà thư mục của một website cụ thể đang chiếm dụng trên máy chủ.

  Tính năng Kiểm tra Dung lượng Mã nguồn Website [WPTangToc OLS]
  💾 Mục đích chính:
  * Quản lý Dung lượng Đĩa: Giúp bạn theo dõi xem website nào đang chiếm nhiều không gian lưu trữ nhất trên máy chủ, đặc biệt hữu ích khi dung lượng đĩa có hạn.
  * Xác định Website Phình to: Dễ dàng tìm ra các website có dung lượng lớn bất thường, có thể do chứa nhiều file ảnh/video, file cache lớn, hoặc các file không cần thiết.
  * Hỗ trợ Dọn dẹp: Cung cấp thông tin để bạn quyết định website nào cần được dọn dẹp [xóa file rác, tối ưu ảnh, xóa cache cũ].
  * Lập kế hoạch Sao lưu/Di chuyển: Biết được dung lượng giúp bạn ước tính thời gian và không gian cần thiết cho việc sao lưu hoặc di chuyển website.

  Tóm lại: Tính năng kiểm tra dung lượng mã nguồn website trong WPTangToc OLS là một công cụ hữu ích giúp bạn giám sát và quản lý hiệu quả việc sử dụng không gian lưu trữ trên máy chủ cho từng website WordPress, hỗ trợ việc tối ưu và bảo trì hệ thống.
}

NAME=$1
if [[ $NAME = "98" ]]; then
  NAME=""
fi
if [[ -z "$NAME" ]]; then
  echo ""
  echo ""
  echo ""

  echo "========================================================================="
  echo "|Quản lý mã nguồn => Kiểm tra dung lượng mã nguồn website               |"
  echo "========================================================================="
  echo ""
  echo ""
  . /etc/wptt/tenmien-them-lua-chon-tat-ca-website
  echo ""
  echo ""
  echo "Lựa chọn website bạn muốn kiếm tra dung lượng mã nguồn: "
  echo ""
  lua_chon_NAME
fi

if [[ $NAME = 'Tất cả website' ]]; then
  if [ "$(ls -A /etc/wptt/vhost | grep -v '^\.\.conf$' | sort -uV)" ]; then
    for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
      domain=$(echo "$entry" | sed 's/^.//' | sed 's/.conf//')
      path_html="/usr/local/lsws/$domain/html"
      i=1
      if [[ -d "$path_html" ]]; then
        . /etc/wptt/ma-nguon/wptt-kiem-tra-dung-luong "$domain"
      fi
    done
  fi

  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    exec /etc/wptt/wptt-ma-nguon-main 1
  fi

  exit
fi

if [[ "$NAME" = "0" || -z "$NAME" ]]; then
  exec /etc/wptt/wptt-ma-nguon-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  exec /etc/wptt/wptt-ma-nguon-main 1
  exit
fi

kiemtra_dung_luong=''
kiemtra_dung_luong=$(du -hs /usr/local/lsws/"$NAME"/html | sed 's/\t//g' | cut -f1 -d '/')
echo "Dung lượng mã nguồn website $NAME là ${kiemtra_dung_luong}B"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  exec /etc/wptt/wptt-ma-nguon-main 1
fi
