#!/bin/bash

function huong_dan(){
Tính năng xoá mã nguồn website, thì đây là một chức năng mạnh mẽ và nguy hiểm, cho phép bạn xóa toàn bộ các tệp tin và thư mục [mã nguồn PHP, HTML, CSS, JS, hình ảnh, v.v.] của một website cụ thể khỏi máy chủ của bạn.

Tính năng Xoá Mã Nguồn Website
🎯 Mục đích sử dụng:
 * Dọn dẹp: Loại bỏ các website thử nghiệm [test/staging] hoặc dự án cũ.
 * Chuẩn bị Cài đặt lại: Xóa mã nguồn cũ trước khi cài đặt một phiên bản website mới hoàn toàn.

Tóm lại: Tính năng xóa mã nguồn website trong WPTangToc OLS là một công cụ tiện lợi để dọn dẹp máy chủ nhưng cực kỳ nguy hiểm. Hãy sử dụng nó với sự cẩn trọng tối đa và luôn đảm bảo bạn đã có bản sao lưu đầy đủ trước khi nhấn nút xóa. Luôn đọc kỹ tài liệu hoặc hỏi cộng đồng hỗ trợ của WPTangToc OLS nếu bạn không chắc chắn.
}


echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Mã nguồn => Xóa mã nguồn website                               |"
echo "========================================================================="
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website bạn muốn xóa mã nguồn: "
echo ""
lua_chon_NAME
name="$NAME"

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

echo "Xác nhận bạn muốn xóa mã nguồn website ${NAME}"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ "$dongy" = "y" ]]; then
	_runing "Xóa mã nguồn website $NAME"
    rm -rf /usr/local/lsws/"$NAME"/html/*
	_rundone "Xóa mã nguồn website $NAME"
else
    . /etc/wptt/wptt-ma-nguon-main 1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-ma-nguon-main 1
fi

