#!/bin/bash

. /etc/wptt/.wptt.conf
if [[ -z "$ngon_ngu" ]]; then
  ngon_ngu='vi'
fi
. "/etc/wptt/lang/$ngon_ngu.sh"
. /etc/wptt/echo-color
tinh_nang_ten="truy cập nhanh thư mục backup website"

echo -e "${C_CYAN}╭──────────────────────────────────────────────────────────────────────────────╮${C_RESET}"
center_text "${C_BOLD_WHITE}$quan_ly_ma_nguon ➜ $tinh_nang_ten${C_RESET}"
echo -e "${C_CYAN}╰──────────────────────────────────────────────────────────────────────────────╯${C_RESET}\n"

NAME=$1
if [[ $NAME = '98' ]]; then
  NAME=''
fi

if [[ -z "$NAME" ]];then
	. /etc/wptt/tenmien
	lua_chon_NAME "$tinh_nang_ten"
fi

. /etc/wptt/echo-color

if [[ "$NAME" = "0" || -z "$NAME" ]]; then
  exec /etc/wptt/wptt-ma-nguon-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  exec /etc/wptt/wptt-ma-nguon-main 1
  exit
fi

gowpt() {
  local target_dir="/usr/local/backup-website/$1"
  echo "==> Chuyển đến $target_dir"
	if [[ ! -d "$target_dir" ]];then
		echo "Lỗi: Không thể truy cập thư mục $target_dir" >&2
		echo "Vì thư mục backup website không tồn tại"
		return 1 # Trả về mã lỗi
	fi

  if cd "$target_dir"; then
    # Chạy lệnh ls sau khi cd thành công (tùy chọn)
    ls -al
  else
    echo "Lỗi: Không thể truy cập thư mục $target_dir" >&2
    return 1 # Trả về mã lỗi
  fi
}
gowpt "$NAME"
unset pathcheck NAME
unset -f gowpt
