#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý mã nguồn => Truy cập nhanh mã nguồn website                    |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Truy cập nhanh vào thư mục backup website: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-ma-nguon-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
	    . /etc/wptt/wptt-ma-nguon-main 1
    exit
fi

# box_out()
# {
#     title="| $1 |"
#     edge=$(echo "$title" | sed 's/./=/g')
#     echo "$edge"
#     echo "$title"
#     echo "$edge"
# }

# echo "Truy cập nhanh vào thư mục mã nguồn của website $NAME"
# echo ""
# box_out "Truy cập vào mã nguồn: cd /usr/local/lsws/$name/html"
# echo ""
# echo ""
# ls /usr/local/lsws/$name/html --color=auto
cd /usr/local/backup-website/$name

gowpt() {
  local target_dir="/usr/local/backup-website/$1"
  echo "==> Chuyển đến $target_dir"
  if cd "$target_dir"; then
    # Chạy lệnh ls sau khi cd thành công (tùy chọn)
    ls -al
  else
    echo "Lỗi: Không thể truy cập thư mục $target_dir" >&2
    return 1 # Trả về mã lỗi
  fi
}
gowpt $NAME

