#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Ma nguon => Xoa ma nguon website                               |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon ban muon xoa ma nguon: "
echo ""
lua_chon_NAME
name="$NAME"
pathttt="/etc/wptt/vhost/.$name.conf"
if [[ ! -f "$pathttt" || "$name" = "0" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    . /etc/wptt/wptt-ma-nguon-main
    exit
fi

read -p "Xac nhan ban muon xoa ma nguon website $name" dongy
if [[ "$dongy" = "y" ]]; then
    rm -rf /usr/local/lsws/"$name"/html/*
    echo ""
    echo "Da hoan tat xoa ma nguon website $name"
else
    . /etc/wptt/wptt-ma-nguon-main
fi
