#!/bin/bash

function huong_dan(){
Kích hoạt hoặc huỷ kích hoạt open_basedir để nâng cao bảo mật PHP để giảm thiểu tối đa việc 1 website bị hack, nó lấy ra website còn lại.

open_basedir là đóng phân vùng hoạt động của PHP

Mục đích chính của open_basedir:

* Tăng cường bảo mật: Đây là mục đích cốt lõi. Bằng cách giới hạn phạm vi truy cập tệp tin, open_basedir giúp ngăn chặn các script PHP [đặc biệt là khi website bị tấn công hoặc chứa mã độc] truy cập, đọc hoặc ghi vào các tệp tin nhạy cảm nằm ngoài thư mục gốc của website đó. Điều này đặc biệt hữu ích trong môi trường hosting chia sẻ, nơi nhiều website cùng hoạt động trên một máy chủ. Nếu một website bị xâm nhập, open_basedir sẽ giúp hạn chế khả năng mã độc lây lan sang các website khác hoặc truy cập vào các tệp tin hệ thống của máy chủ.
* Kiểm soát môi trường thực thi của PHP: Nó giúp quản trị viên máy chủ định rõ những khu vực nào trên hệ thống tệp mà các kịch bản PHP được phép tương tác.


Thường anh em sử dụng plugin backup như duplicator hay backupbuddy sẽ bị lỗi.. nếu bạn không sử dụng plugin thì hãy nên bật tính năng này
Ghi chú: khi bật có thể bị lỗi một số tính năng bạn vui lòng kiểm tra kỹ trước khi triển khai
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$bao_mat => $bat/$tat open_basedir                                |"
echo "========================================================================="

RED='\033[0;31m'
NC='\033[0m'
xanh='\033[0;32m'

if [ "$(ls -A /etc/wptt/vhost|sort -uV)" ]; then
  echo
  echo "Kiểm tra website kích hoạt open_basedir:"
  echo "========================================================================="
  for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
    domain=$(echo "$entry" | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/conf/vhosts/"$domain"/"$domain".conf"
    i=1
	if [[ -f "$path" ]]; then
		if [[ $(cat /usr/local/lsws/conf/vhosts/"$domain"/"$domain".conf | grep 'open_basedir') = '' ]];then
			hoatdong="Đang được tắt"
			echo -e "Hệ thống kiểm tra website $domain tính năng :${RED} $hoatdong${NC}"
		else
			hoatdong="Đang được bật"
			echo -e "Hệ thống kiểm tra website $domain tính năng :${xanh} $hoatdong${NC}"
		fi
	fi
  done
  echo "========================================================================="
  echo
fi


. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website muốn Bật/Tắt open_basedir: "
lua_chon_NAME
echo ""

. /etc/wptt/echo-color

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt/wptt-bao-mat-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
	clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
	sleep 3
	. /etc/wptt/wptt-bao-mat-main 1
	exit
fi

check_da_duoc_gan_gia_tri=$(cat /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf | grep 'shell_exec')
check_open_open_basedir=$(cat /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf | grep 'open_basedir')

# gia tri dieu kien khi đã được add phpIniOverride
if [[ $check_da_duoc_gan_gia_tri = '' ]];then
	if [[ $check_open_open_basedir ]];then
		echo "Hiện tại website $NAME đang kích hoạt tính năng open_basedir"
		read -p "Bạn có muốn tắt open_basedir không? (y/n): " dongytat
		if [[ $dongytat = 'y' ]];then
			echo "Tắt open_basedir : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log
			sed -i -e '/^phpIniOverride/,/^}$/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
			echoDone "Hoàn tất tắt open_basedir của website $NAME"
		fi
	else
		echo "Hiện tại website $NAME không kích hoạt tính năng open_basedir"
		read -p "Bạn có muốn bật open_basedir không? (y/n): " dongybat
		if [[ $dongybat = 'y' ]];then
echo "
phpIniOverride  {
php_admin_value open_basedir \"/usr/local/lsws/$NAME:/tmp:/var/run/redis:/usr/local/lsws/memcached\"
}" >> /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
			echoDone "Hoàn tất bật open_basedir của website $NAME"
		fi
	fi
fi

# gia tri dieu kien khi chua duoc add phpIniOverride
if [[ $check_da_duoc_gan_gia_tri ]];then
	if [[ $check_open_open_basedir ]];then
		echo "Hiện tại website $NAME đang kích hoạt tính năng open_basedir"
		read -p "Bạn có muốn tắt open_basedir không? (y/n): " dongytat
		if [[ $dongytat = 'y' ]];then
			sed -i '/open_basedir/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
			echoDone "Hoàn tất tắt open_basedir của website $NAME"
		fi
	else
		echo "Hiện tại website $NAME không kích hoạt tính năng open_basedir"
		read -p "Bạn có muốn bật open_basedir không? (y/n): " dongybat
		if [[ $dongybat = 'y' ]];then
			echo "Bật open_basedir : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log
			sed -i '/^phpIniOverride/a php_admin_value open_basedir "/usr/local/lsws/'$NAME':/tmp:/var/run/redis:/usr/local/lsws/memcached"' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
			echoDone "Hoàn tất bật open_basedir của website $NAME"
		fi
	fi
fi

#reboot lại hệ thống để xác nhận
if [[ $dongybat = 'y' || $dongytat = 'y' ]];then
	/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-bao-mat-main 1
fi


