#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý bảo mật => Bật/Tắt hàm nguy hiểm PHP                           |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website muốn Bật/Tắt chặn hàm nguy hiểm PHP: "
lua_chon_NAME
echo ""

. /etc/wptt/echo-color

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt/wptt-bao-mat-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
	clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
	sleep 3
	. /etc/wptt/wptt-bao-mat-main 1
	exit
fi

check_da_duoc_gan_gia_tri=$(cat /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf | grep 'open_basedir')
check_open_shell_exec=$(cat /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf | grep 'shell_exec')

# gia tri dieu kien khi đã được add phpIniOverride
if [[ $check_da_duoc_gan_gia_tri = '' ]];then
	if [[ $check_open_shell_exec ]];then
		echo "Hiện tại website $NAME đang kích hoạt tính năng chặn hàm những hàm nguy hiểm"
		read -p "Bạn có muốn tắt tính năng chặn những hàm nguy hiểm không? (y/n): " dongytat
		if [[ $dongytat = 'y' ]];then
			sed -i -e '/^phpIniOverride/,/^}$/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
			echoDone "Hoàn tất tắt chặn những hàm nguy hiểm cho website $NAME"
		fi
	else
		echo "Hiện tại website $NAME không kích hoạt tính năng chặn hàm nguy hiểm PHP"
		read -p "Bạn có muốn bật chặn những hàm nguy hiểm không? (y/n): " dongybat
		if [[ $dongybat = 'y' ]];then
echo "
phpIniOverride  {
php_admin_value disable_functions \"exec,system,passthru,shell_exec,dl,show_source,posix_kill,posix_mkfifo,posix_getpwuid,posix_setpgid,posix_setsid,posix_setuid,posix_setgid,posix_seteuid,posix_setegid,posix_uname\"
}" >> /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
			echoDone "Hoàn tất bật chặn những hàm nguy hiểm website $NAME"
		fi
	fi
fi

# gia tri dieu kien khi chua duoc add phpIniOverride
if [[ $check_da_duoc_gan_gia_tri ]];then
	if [[ $check_open_shell_exec ]];then
		echo "Hiện tại website $NAME đang kích hoạt tính năng chặn hàm nguy hiểm PHP"
		read -p "Bạn có muốn tắt chặn hàm shell_exec không? (y/n): " dongytat
		if [[ $dongytat = 'y' ]];then
			sed -i '/disable_functions/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
			echoDone "Hoàn tất tắt chặn hàm shell_exec của website $NAME"
		fi
	else
		echo "Hiện tại website $NAME không kích hoạt tính năng chặn những hàm nguy hiểm bảo mật"
		read -p "Bạn có muốn bật chặn funtions nguy hiểm không? (y/n): " dongybat
		if [[ $dongybat = 'y' ]];then
			sed -i '/^phpIniOverride/a php_admin_value disable_functions "exec,system,passthru,shell_exec,dl,show_source,posix_kill,posix_mkfifo,posix_getpwuid,posix_setpgid,posix_setsid,posix_setuid,posix_setgid,posix_seteuid,posix_setegid,posix_uname"' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
			echoDone "Hoàn tất bật chặn hàm shell_exec của website $NAME"
		fi
	fi
fi

#reboot lại hệ thống để xác nhận
if [[ $dongybat = 'y' || $dongytat = 'y' ]];then
	/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-bao-mat-main 1
fi


