#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2024
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

if [[ $1 = "" ]];then
	. /etc/wptt/wptt-header-menu
	header_menu
else
	. /etc/wptt/echo-color
	echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Quản lý CSF:"
echo ""
options=(
	"Cài đặt CSF" #0
	"Hủy thiết lập CSF" #1
	"Chặn quốc gia" #2
	"Chỉ cho phép một số quốc gia được truy cập" #3
	"Hủy bỏ chặn quốc gia" #4
	"Hủy bỏ chặn toàn bộ quốc gia chỉ được một số quốc gia cho phép" #5
	"Bật chế độ chống DDOS" #6
	"Tắt chế độ chống DDOS" #7
)

# Hàm thực thi hành động dựa trên index (cho menu Quản lý CSF)
run_action() {
    local index=$1
    local script_path=""
    local script_args="98" # Tham số 98 cho các script này

    case $index in
         0) script_path="/etc/wptt/bao-mat/csf/wptt-cai-dat-csf" ;;
         1) script_path="/etc/wptt/bao-mat/csf/wptt-huy-cai-dat-csf" ;;
         2) script_path="/etc/wptt/bao-mat/csf/chan-ip-quoc-gia" ;;
         3) script_path="/etc/wptt/bao-mat/csf/chan-ip-quoc-gia-chi-cho-phep" ;;
         4) script_path="/etc/wptt/bao-mat/csf/huy-bo-chan-ip-quoc-gia" ;;
         5) script_path="/etc/wptt/bao-mat/csf/huy-bo-chan-ip-quoc-gia-chi-cho-phep" ;;
         6) script_path="/etc/wptt/bao-mat/csf/mod-csf-chong-ddos" ;;
         7) script_path="/etc/wptt/bao-mat/csf/tat-mod-csf-chong-ddos" ;;
        *) echo "${lua_chon_khong_hop_le:-Lựa chọn không hợp lệ}: Index $index."; return 1 ;;
    esac

    # Kiểm tra và chạy script con
    if [[ -x "$script_path" ]]; then
        "$script_path" "$script_args"
    else
        echo "Lỗi: Không tìm thấy hoặc không thể thực thi script '$script_path'."
    fi
    # read -rp "Nhấn Enter để quay lại menu..." # Bỏ comment nếu muốn tạm dừng
}
. /etc/wptt/wptt-callback-menu-chon

