#!/bin/bash

. /etc/wptt/echo-color
. /etc/wptt/.wptt.conf

if [[ $mod_chong_ddos = '' ]];then
echo "Xác nhận bạn muốn sử dụng chế độ chống ddos tôi đang bị tấn công"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ $dongy = 'n' ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

_runing "Bật chế độ chống ddos tôi đang bị tấn công"
sed -i -e '/^perClientConnLimit /,/^}$/d' /usr/local/lsws/conf/httpd_config.conf
sed -i -e '/^lsrecaptcha /,/^}$/d' /usr/local/lsws/conf/httpd_config.conf

#ý nghĩa config Yêu cầu tĩnh/giây = 40, và Yêu cầu động/giây = 2 điều tiết băng thông.
#banPeriod: nếu bị quá sẽ bị khoá 600 giây (10 PHút) có thể tăng cao hơn nếu muốn
#hardLimit nếu 20 kết nối trong vòng 15 gracePeriod thì bị block 600 giây
echo 'perClientConnLimit  {
  staticReqPerSec         40
  dynReqPerSec            2
  outBandwidth            0
  inBandwidth             0
  softLimit               15
  hardLimit               20
  blockBadReq             1
  gracePeriod             15
  banPeriod               600
}' >> /usr/local/lsws/conf/httpd_config.conf

echo 'lsrecaptcha  {
  enabled                 1
  type                    1

  botWhiteList  {

  }
}' >> /usr/local/lsws/conf/httpd_config.conf
sed -i '/mod_chong_ddos/d' /etc/wptt/.wptt.conf
echo 'mod_chong_ddos=1' >> /etc/wptt/.wptt.conf
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "Bật chế độ chống ddos tôi đang bị tấn công"
echo "Khi cơn bão đã qua đi (hết bị hacker sơ múi) thì hãy tắt chế độ này để để cho website hoạt động tốt nhất"
fi



if [[ $mod_chong_ddos ]];then
echo "Xác nhận bạn muốn tắt chế độ chống ddos tôi đang bị tấn công"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ $dongy = 'n' ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

_runing "Tắt chế độ chống ddos tôi đang bị tấn công"
sed -i -e '/^perClientConnLimit /,/^}$/d' /usr/local/lsws/conf/httpd_config.conf
sed -i -e '/^lsrecaptcha /,/^}$/d' /usr/local/lsws/conf/httpd_config.conf
echo 'perClientConnLimit  {
  staticReqPerSec         0
  dynReqPerSec            0
  outBandwidth            0
  inBandwidth             0
  softLimit               100000
  hardLimit               150000
  gracePeriod             15
  banPeriod               300
}' >> /usr/local/lsws/conf/httpd_config.conf
sed -i '/mod_chong_ddos/d' /etc/wptt/.wptt.conf
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "Tắt chế độ chống ddos tôi đang bị tấn công"
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

