#!/bin/bash

function huong_dan() {
  Tính năng thiết lập kích hoạt.
  Nếu ai đó truy cập vào SSH của bạn, ngay lập tức nó sẽ thông báo qua telegram về thời gian đăng nhập, ip đăng nhập...
  Để bạn dễ dàng kiểm soát hệ thống
}

. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color
echo "========================================================================="
echo "|Bảo Mật => Cảnh báo login SSH qua telegram" |
  echo "========================================================================="
if [[ "$thong_bao_login_ssh" = "1" ]]; then
  echo "Trạng thái: thông báo login ssh đã được kích hoạt"
else
  echo "Trạng thái: thông báo login ssh chưa được kích hoạt"
fi
echo "/-----------------------------------------------------------------------/"

if [[ "$telegram_api" = "" || "$telegram_id" = "" ]]; then
  clear
  echo "Vui lòng kích hoạt Telegram trước khi để sử dụng được tính năng này."
  sleep 3
  . /etc/wptt/bao-mat/wptt-telegram
fi

if [[ "$thong_bao_login_ssh" = "1" ]]; then
  echo "Bạn đã bật cảnh bảo đăng nhập qua Telegram"
  echo "Bạn có muốn tắt cảnh bảo đăng nhập telegram? "
  prompt="Nhập lựa chọn của bạn [1-2]: "
  dongy="n"
  options=("Đồng ý" "Không đồng ý")
  PS3="$prompt"
  select opt in "${options[@]}"; do
    case "$REPLY" in
    1)
      dongy="y"
      break
      ;;

    2)
      dongy="n"
      break
      ;;

    $((${#options[@]} + 1)))
      printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
      break
      ;;
    *)
      printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
      break
      ;;
    esac
  done
  if [[ "$dongy" = "y" ]]; then
    _runing "Tắt cảnh báo login SSH telegram"
    sed -i "/thong_bao_login_ssh/d" /etc/wptt/.wptt.conf
    _rundone "Tắt cảnh báo login SSH telegram"
  fi

else

  echo "Bạn có muốn bật cảnh bảo đăng nhập qua Telegram?"
  prompt="Nhập lựa chọn của bạn [1-2]: "
  dongy="n"
  options=("Đồng ý" "Không đồng ý")
  PS3="$prompt"
  select opt in "${options[@]}"; do
    case "$REPLY" in
    1)
      dongy="y"
      break
      ;;

    2)
      dongy="n"
      break
      ;;

    $((${#options[@]} + 1)))
      printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
      break
      ;;
    *)
      printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
      break
      ;;
    esac
  done

  if [[ "$dongy" = "y" ]]; then
    _runing "Bật cảnh báo thông báo login SSH qua telegram"
    sed -i "/thong_bao_login_ssh/d" /etc/wptt/.wptt.conf
    echo "thong_bao_login_ssh=1" >>/etc/wptt/.wptt.conf
    _rundone "Bật cảnh báo thông báo login SSH qua telegram"
  fi
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-ssh-main 1
fi
