#!/bin/bash
domain_thuc_thi=$1

if [[ $2 = 'on' ]];then
cong_tac='+i'
fi

if [[ $2 = 'off' ]];then
cong_tac='-i'
fi

if [[ $2 = '' ]];then
	return 2>/dev/null;exit;
fi

if [[ -d /usr/local/lsws/"$domain_thuc_thi"/html/wp-content/themes ]];then
chattr -R $cong_tac /usr/local/lsws/"$domain_thuc_thi"/html/wp-content/themes
fi

if [[ -d /usr/local/lsws/"$domain_thuc_thi"/html/wp-content/plugins ]];then
chattr -R $cong_tac /usr/local/lsws/"$domain_thuc_thi"/html/wp-content/plugins
fi


if [[ -d /usr/local/lsws/"$domain_thuc_thi"/html/wp-admin ]];then
chattr -R $cong_tac /usr/local/lsws/"$domain_thuc_thi"/html/wp-admin
fi

if [[ -d /usr/local/lsws/"$domain_thuc_thi"/html/wp-includes ]];then
chattr -R $cong_tac /usr/local/lsws/"$domain_thuc_thi"/html/wp-includes
fi

file_all_wordpress_core=($(find /usr/local/lsws/$domain_thuc_thi/html  -maxdepth 1 -type f -name "*.php"))
for file_chattr in ${file_all_wordpress_core[@]};do
chattr $cong_tac $file_chattr
done
