#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025
RED='\033[0;31m'
NC='\033[0m'
clear

echo ""
if [ "$(ls -A /etc/wptt/vhost|sort -uV)" ]; then
    echo "========================================================================="
    echo "Danh sách domain đã được kích hoạt bảo mật 2 lớp wp-admin:"
    echo "========================================================================="
    for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
        domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
        path="/usr/local/lsws/"$domain"/passwd/.mk"
        i=1
        if [[ -f "$path" ]]; then
            checkauto="Đã kích hoạt"
        else
            checkauto="Chưa kích hoạt"
        fi
		if [[ -d /usr/local/lsws/"$domain" ]];then
        echo "Website $domain $checkauto bảo mật 2 lớp wp-admin"
		fi
    done
    echo "========================================================================="
    echo
fi

echo ""
echo ""
echo "Lựa chọn website bạn muốn xem thông tin tài khoản bảo mật 2 lớp: "
echo ""
function lua_chon_NAME() {
    NAME=""
    if [ "$(ls -At /etc/wptt/vhost)" ]; then
        selects=()
        for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
            NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
            if [[ -f /usr/local/lsws/"$NAME"/passwd/.mk ]]; then
                selects+=("$NAME")
            fi
        done
        PS3="
-//- Nhập lựa chọn website của bạn [Thoát=0]: "
        select select in ${selects[@]}; do
            NAME=$select
            index=$REPLY
            break
        done
    else
        clear
        echo "Khong co domain tren he thong cua ban."
        exit
    fi
}

lua_chon_NAME

if [[ $NAME = '' || $NAME = '0' ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

if [[ ! -f /usr/local/lsws/"$NAME"/passwd/.mk ]]; then
echo "webserver cua ban chua co domain nao duoc kich hoat bao mat 2 lop wp-admin"
exit
fi

echo -e "${RED}-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo "  	                    Xem thong tin tai khoan	"
echo "-------------------------------------------------------------------------"
echo -e "--------------------------------------------------------------------------${NC}"
echo "-------------------------------------------------------------------------"
echo ""

. /etc/wptt/vhost/."$NAME".conf

echo "-------------------------------------------------------------------------"
echo "ID dang nhap      : $id_dang_nhap_wordpress_2"
echo "Password          : $password_dang_nhap_wordpress_2"
echo "-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo ""

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

