#!/bin/bash
. /etc/wptt/.wptt.conf
NAME=$1
date="$(date "+%d-%m-%Y %H:%M")"

	function hello-giatuan() {
	text="
Cảnh báo website bị DDOS: website $1 đang bị ddos boi IP $2
Thời điểm: ${date}
	"
	url_tele="https://api.telegram.org/bot${telegram_api}/sendMessage"
	curl -s -d "chat_id=$telegram_id&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url_tele > /dev/null	
	}
	


    if [[ -d "$path" ]]; then
        hello-giatuan "$domain" "$ip"
    fi


NAME2=${NAME//[-._]/wp}
echo "========================================================================="
echo "Danh sach IP da bi chan boi Brute Force wp-admin:"
echo "========================================================================="
fail2ban-client status ddos-$NAME2 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')