#!/bin/bash

function huong_dan() {
  Kích hoạt tường lửa 8G:

  Tường lửa 8G giúp bảo vệ chống lại các mối đe dọa phổ biến:
  * Nâng cao bảo mật cho WordPress.
  * Bad Bots: Chặn các bot độc hại, trình thu thập dữ liệu rác.
  * Malicious Requests: Ngăn chặn các yêu cầu chứa mã độc, dấu hiệu tấn công.
  * SQL Injection [SQLi]: Các mẫu tấn công SQL phổ biến.
  * Cross-Site Scripting [XSS]: Các mẫu tấn công XSS.
  * Directory Traversal: Cố gắng truy cập vào các tệp hoặc thư mục không được phép.
  * Remote File Inclusion [RFI] / Local File Inclusion [LFI]: Cố gắng chèn và thực thi tệp từ xa hoặc cục bộ.
  * Spam Referrers: Chặn các referrer spam.
  Ghi chú: khi kích hoạt tường lửa 8G sẽ làm giảm một phần hiệu suất tốc độ của website
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
. /etc/wptt/echo-color
NAME=$1
if [[ $NAME = "98" ]]; then
  NAME=""
fi
if [[ $NAME = "" ]]; then
  echo ""
  echo ""
  echo ""
  echo "========================================================================="
  echo "|$bao_mat => $bat $tuong_lua 8G                                 |"
  echo "========================================================================="

  RED='\033[0;31m'
  NC='\033[0m'
  xanh='\033[0;32m'

  if [ "$(ls -A /etc/wptt/vhost | sort -uV)" ]; then
    echo
    echo "Kiểm tra website kích hoạt tường lửa 8G:"
    echo "========================================================================="
    for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
      domain=$(echo "$entry" | sed 's/^.//' | sed 's/.conf//')
      path="/usr/local/lsws/$domain/html/.htaccess"
      i=1
      if [[ -f "$path" ]]; then
        if [[ $(cat /usr/local/lsws/$domain/html/.htaccess | grep '#begin-tuong-lua-bao-mat-8g') = '' ]]; then
          hoatdong="Đang được tắt"
          tuan_7g='1'
          echo -e "Hệ thống kiểm tra website $domain :${RED} $hoatdong${NC}"
        else
          hoatdong="Đang được bật"
          echo -e "Hệ thống kiểm tra website $domain :${xanh} $hoatdong${NC}"
        fi
      fi
    done
    echo "========================================================================="
    echo
  fi

  if [[ $tuan_7g = '' ]]; then
    . /etc/wptt/echo-color
    echoDo "Tất cả website được kích hoạt tường lửa 8G hết rồi"
    check_menu_wptangtoc_active=$1
    if [[ $check_menu_wptangtoc_active = "98" ]]; then
      . /etc/wptt/wptt-bao-mat-main 1
    fi
    return 2>/dev/null
    exit
  fi

  . /etc/wptt/tenmien-them-lua-chon-tat-ca-website
  echo ""
  echo ""
  echo "$lua_chon_website_ban_muon $bat $tuong_lua 8G: "
  echo ""
  lua_chon_NAME
fi

if [[ $NAME = 'Tất cả website' ]]; then
  if [ "$(ls -A /etc/wptt/vhost | sort -uV)" ]; then
    for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
      domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      path_html="/usr/local/lsws/$domain/html"
      i=1
      if [ "$domain" != "${domain/./}" ] && [ "$domain" != '.' ]; then #điều kiện domain phải có dấu . và lỗi chỉ có only .
        if [[ -d "$path_html" ]]; then
          _runing "Thiết lập tường lửa 8G website $domain"
          if [[ $(cat /usr/local/lsws/$domain/html/.htaccess | grep '#begin-tuong-lua-bao-mat-8g') = '' ]]; then
            (/etc/wptt/bao-mat/wptt-firewall-7g $domain >/dev/null 2>&1)
          fi
          _rundone "Thiết lập tường lửa 8G website $domain"
        fi
      fi
    done
  fi

  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    . /etc/wptt/wptt-bao-mat-main 1
  fi

  exit
fi

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-bao-mat-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . /etc/wptt/wptt-bao-mat-main 1
  exit
fi

if [[ ! -f /usr/local/lsws/$NAME/html/.htaccess ]]; then
  echoDo "Không xác định được file .htaccess"
  exit
fi

echo "Thiết lập tường lửa 8G website $NAME: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

#xoa tường lửa 7g để lên tường lửa 8G
sed -i -e '/^#begin-tuong-lua-bao-mat-7g/,/^#end-tuong-lua-bao-mat-7g$/d' /usr/local/lsws/$NAME/html/.htaccess

#nguyên tắc là cho biến quy tắc phải đưa lên trên cùng của file .htaccess trên quy tắc của lịnk wordpres thì mới hoạt động
quy_tac=$(cat /etc/wptt/bao-mat/firewall.txt)
htaccess_hien_tai=$(cat /usr/local/lsws/$NAME/html/.htaccess)

#kiểm tra đã kích hoạt trước đó chưa
if [[ $(echo $htaccess_hien_tai | grep '#begin-tuong-lua-bao-mat-8g') ]]; then
  echoDo "website $NAME đã được kích hoạt tường lửa 8G trước đó rồi"
  . /etc/wptt/wptt-bao-mat-main 1
  exit
fi

echo "$quy_tac" >/usr/local/lsws/$NAME/html/.htaccess
echo "$htaccess_hien_tai" >>/usr/local/lsws/$NAME/html/.htaccess
if [[ -f /etc/wptt/vhost/.$NAME.conf ]]; then
  sed -i '/tuong_lua_7g/d' /etc/wptt/vhost/.$NAME.conf
  echo 'tuong_lua_7g=1' >>/etc/wptt/vhost/.$NAME.conf
fi

#clear htaccess chuyen vhost
vhost_chuyen_htaccess=''
. /etc/wptt/vhost/.$NAME.conf
if [[ $vhost_chuyen_htaccess ]]; then
  . /etc/wptt/wptt-htaccess-tat-chuyen-doi-vhost $NAME >/dev/null 2>&1
fi

#tuong thich tuong lua 8G voi phpmyadmin
. /etc/wptt/.wptt.conf
if [[ $Website_chinh = "$NAME" && -d /usr/local/lsws/$NAME/html/phpmyadmin ]]; then
  sed -i '/RewriteCond %{QUERY_STRING} ^(%2d|-)/i RewriteCond %{REQUEST_URI} !^/phpmyadmin/index\\.php$ [NC]' /usr/local/lsws/$NAME/html/.htaccess
fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
echoDone "Hoàn tất kích hoạt tường lửa 8G cho website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-bao-mat-main 1
fi
