#!/bin/bash
. /etc/wptt/.wptt.conf

date="$(date "+%d-%m-%Y %H:%M")"

	function hello-giatuan() {

telegram_api='6888429490:AAEZ4dYrrX4B2BZWTJ3j9wsaPvXXvTBopXc'
telegram_id='1638096630'

ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com |grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com| grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')



	text="
Cảnh báo website ngừng hoạt động: website $1 đang ngừng hoạt động
Thời điểm: ${date}
	"
	url_tele="https://api.telegram.org/bot${telegram_api}/sendMessage"
	curl -s -d "chat_id=$telegram_id&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url_tele > /dev/null	
	}
	
if [ "$(ls -A /etc/wptt/vhost|sort -uV)" ]; then
  for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
    domain=$(echo "$entry" | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" && ! -f /usr/local/lsws/conf/vhosts/"$domain"/"$omain".conf.bkwptt ]]; then
      checkssl=$(curl -Is https://"${domain}" | head -n 1 | grep -c "200")
      checkssl2=$(curl -Is http://"${domain}" | head -n 1 | grep -c "200")
      if [[ "$checkssl" = "0" && "$checkssl2" = "0" ]]; then
        hello-giatuan "$domain"
      fi
    fi

  done
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

