#!/bin/bash
. /etc/wptt/.wptt.conf
echo "/-----------------------------------------------------------------------/"
echo "Bảo mật => Hủy tính năng chống ddos website"
echo "/-----------------------------------------------------------------------/"

. /etc/wptt/echo-color
if [ "$(ls -A /etc/wptt/vhost)" ]; then
    echo "========================================================================="
    echo "Danh sách Domain đã kích hoạt chống ddos:"
    echo "========================================================================="
    for entry in $(ls -A /etc/wptt/vhost); do
        domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
        domain2=${domain//[-._]/wp}
        path="/etc/fail2ban/filter.d/ddos-$domain2.conf"
        i=1
        if [[ -f "$path" ]]; then
            checkauto="Đã kích hoạt"
        else
            checkauto="Chưa kích hoạt"
        fi
        echo "Website $domain $checkauto chống ddos"
    done
    echo "========================================================================="
    echo
fi

echo ""
echo ""
echo "Lựa chọn website bạn muốn hủy kích hoạt ddos website: "
echo ""
function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			NAME2=${NAME//[-._]/wp}
			if [[ -f /etc/fail2ban/filter.d/ddos-$NAME2.conf ]]; then
				selects+=("$NAME")
			fi
		done
		if [[ $selects = '' ]];then
			echo "Tất cả domain trên hệ thống chưa có domain nào được kích hoạt chống DDOS"
			. /etc/wptt/wptt-bao-mat-main 1
		fi

		#check tổng số website, nếu 2 website trở lên thì sẽ tự động có tính năng tất cả
		a=0
		for select in ${selects[@]};do
			a=$(expr $a + 1)
		done

		if [[ $a != 1 ]];then
			selects+=("Tat-ca-website")
		fi

        PS3="
-//- Nhập lựa chọn website của bạn [0=Thoát]: "
        select select in ${selects[@]}; do
            NAME=$select
            index=$REPLY
            break
        done
    else
        clear
        echo "Không có domain nào trên hệ thống."
        exit
    fi
}

lua_chon_NAME


if [[ $NAME = 'Tat-ca-website' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
            domain2=${domain//[-._]/wp}
            if [[ -f /etc/fail2ban/filter.d/ddos-$domain2.conf ]]; then
					_runing "Xoá thiết lập chống ddos website $domain"
					. /etc/wptt/bao-mat/wptt-canh-bao-ddos-thiet-lap-xoa $domain >/dev/null 2>&1
					_rundone "Xoá thiết lập chống ddos website $domain"
			fi
		done
	fi

	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-menu-logs 1
	fi
	exit
fi


if [[ $NAME = '' || $NAME = 0 ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi


NAME2=${NAME//[-._]/wp}
if [[ ! -f /etc/fail2ban/filter.d/ddos-$NAME2.conf ]]; then
    echo "domain $NAME chưa được kích hoạt chống DDOS"
    exit
fi

. /etc/wptt/vhost/.$NAME.conf
. /etc/wptt/echo-color
_runing "Hủy kích hoạt chống DDOS website $NAME"
if [[ $bat_log_domain = '' ]];then
sed -i -e '/^errorlog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -i -e '/^accesslog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
rm -rf /usr/local/lsws/$NAME/logs
fi

sed -i -e '/^#begin-ddos-website-'$NAME2'/,/^#end-ddos-website-'$NAME2'$/d' /etc/fail2ban/jail.local
rm -f /etc/fail2ban/filter.d/ddos-$NAME2.conf
# sed -i "/ddos-$NAME2/,+7d" /etc/fail2ban/jail.local

fail2ban-client reload
systemctl restart fail2ban
_rundone "Hủy kích hoạt chống DDOS website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

