#!/bin/bash

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Bao Mat => Tat kich hoat Modsecurity                                   |"
echo "========================================================================="
echo ""

if [[ ! -d /usr/local/lsws/modsec/owasp ]]; then
    echo "ban da chua kich hoat modsecurity"
    exit
fi

read -p "Xac nhan huy kich hoat bao mat modsecurity (y/n): " dongy
if [[ "$dongy" = "y" ]]; then
    path="/usr/local/lsws/modsec/owasp"
    rm -rf $path
    sed -i '/mod_security/,+6d' /usr/local/lsws/conf/httpd_config.conf
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
    echo "Hoan tat huy kich hoat bao mat modsecurity"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

