#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Bao Mat => unban bo chan ip                                            |"
echo "========================================================================="
echo ""
echo ""
if [ "$(ls -A /etc/wptt/vhost)" ]; then
    echo "========================================================================="
    echo "Danh sach Domain da kich hoat chong Brute Force wp-admin:"
    echo "========================================================================="
    for entry in $(ls -A /etc/wptt/vhost); do
        domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
        domain2=${domain//[-._]/wp}
        path="/etc/fail2ban/filter.d/wordpress-dangnhap-$domain2.conf"
        i=1
        if [[ -f "$path" ]]; then
            checkauto="Da kich hoat"
        else
            checkauto="Chua kich hoat"
        fi
        echo "Website $domain $checkauto chong Brute Force wp-admin"
    done
    echo "========================================================================="
    echo
fi

echo ""
echo ""
echo "lua chon website unban bo chan ip: "
echo ""
function lua_chon_NAME() {
    NAME=""
    if [ "$(ls -At /etc/wptt/vhost)" ]; then
        selects=()
        for entry in $(ls -A /etc/wptt/vhost); do
            NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
            NAME2=${NAME//[-._]/wp}
            if [[ -f /etc/fail2ban/filter.d/wordpress-dangnhap-$NAME2.conf ]]; then
                selects+=("$NAME")
            fi
        done
        PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
        select select in ${selects[@]}; do
            NAME=$select
            index=$REPLY
            break
        done
    else
        clear
        echo "Khong co domain tren he thong cua ban."
        exit
    fi
}

lua_chon_NAME

NAME2=${NAME//[-._]/wp}
read -p "Nhap ip ban muon bo chan: " ip
if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
fail2ban-client set wordpress-dangnhap-$NAME2 unbanip $ip
echo "Hoan tat mo khoa $ip"
else
echo "IP khong dung dang"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

