#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Bao Mat => Xoa phan mem Scan quet virus website                        |"
echo "========================================================================="
echo ""
echo ""

if [[ ! -f "/usr/local/maldetect/uninstall.sh" ]]; then
    echo "Ban chua cai dat phan mem diet virus va quet virus voi wptangtoc ols"
    exit
fi

bash /usr/local/maldetect/uninstall.sh
yum remove clamav-server clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd -y
. /etc/wptt/echo-color
echoDone "Hoan tat xoa phan mem diet virus"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

