#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Bao Mat => Huy kich hoat chong Brute Force wp-admin                    |"
echo "========================================================================="
echo ""
echo ""
echo ""
if [ "$(ls -A /etc/wptt/vhost)" ]; then
    echo "========================================================================="
    echo "Danh sach Domain da kich hoat chong Brute Force wp-admin:"
    echo "========================================================================="
    for entry in $(ls -A /etc/wptt/vhost); do
        domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
        domain2=${domain//[-._]/wp}
        path="/etc/fail2ban/filter.d/wordpress-dangnhap-$domain2.conf"
        i=1
        if [[ -f "$path" ]]; then
            checkauto="Da kich hoat"
        else
            checkauto="Chua kich hoat"
        fi
        echo "Website $domain $checkauto chong Brute Force wp-admin"
    done
    echo "========================================================================="
    echo
fi

echo ""
echo ""
echo "lua chon website huy kich hoat chong Brute Force wp-admin: "
echo ""
function lua_chon_NAME() {
    NAME=""
    if [ "$(ls -At /etc/wptt/vhost)" ]; then
        selects=()
        for entry in $(ls -A /etc/wptt/vhost); do
            NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
            NAME2=${NAME//[-._]/wp}
            if [[ -f /etc/fail2ban/filter.d/wordpress-dangnhap-$NAME2.conf ]]; then
                selects+=("$NAME")
            fi
        done
        PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
        select select in ${selects[@]}; do
            NAME=$select
            index=$REPLY
            break
        done
    else
        clear
        echo "Khong co domain tren he thong cua ban."
        exit
    fi
}

lua_chon_NAME

NAME2=${NAME//[-._]/wp}
if [[ ! -f /etc/fail2ban/filter.d/wordpress-dangnhap-$NAME2.conf ]]; then
    echo "Ban chua co domain nao duoc kich hoat chong Brute Force wp-admin"
    exit
fi

tuancheck=$(cat /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf | grep -c "#vi-bao-mat-wp-admin")
if [[ "$tuancheck" = "1" ]]; then
    sed -i "/#vi-bao-mat-wp-admin/,+12d" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
    rm -rf /usr/local/lsws/$NAME/logs
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi
rm -f /etc/fail2ban/filter.d/wordpress-dangnhap-$NAME2.conf
sed -i "/wordpress-dangnhap-$NAME2/,+7d" /etc/fail2ban/jail.local
fail2ban-client reload
systemctl restart fail2ban
echo "Hoan tat huy kich hoat chong Brute Force wp-admin cho website $NAME"
