#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Bảo mật => Kích hoạt tường lửa 7G                                 |"
echo "========================================================================="
NAME=$1
if [[ $NAME = "98" ]];then
NAME=""
fi


if [[ $NAME = '' ]];then
function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]];then
				if [ "$NAME" != "${NAME/./}" ]; then
					selects+=("$NAME")
				fi
			fi
		done

		if [[ $selects = '' ]];then
			echo "Không có website nào sử dụng WordPress"
			. /etc/wptt/wptt-wordpress-main 1
			exit
		fi
selects+=("Tat-ca-website")
PS3="
-//- Lựa chọn website bạn tắt thiết lập tường lửa 7G:  "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Không có domain nào tồn tại trên hệ thống."
	fi
}

lua_chon_NAME
fi



. /etc/wptt/echo-color


if [[ $NAME = 'Tat-ca-website' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path="/usr/local/lsws/$domain/html/wp-config.php"
			path_html="/usr/local/lsws/$domain/html"
			i=1
			if [[ -f "$path" ]]; then
				_runing "Thiết lập tường lửa 7G website $domain"
				if [[ $(cat /usr/local/lsws/$domain/html/.htaccess |grep '#tuong-lua-bao-mat-7g') ]];then
				. /etc/wptt/bao-mat/wptt-tat-firewall-7g $domain >/dev/null 2>&1
				fi
				_rundone "Thiết lập tường lửa 7G website $domain"
			fi
		done
	fi

	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-db-main 1
	fi

	exit
fi


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-bao-mat-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-bao-mat-main 1
    exit
fi


if [[ ! -f /usr/local/lsws/$NAME/html/.htaccess ]];then
echoDo "Không xác định được file .htaccess"
exit
fi

dem_so_dong=$(cat /etc/wptt/bao-mat/firewall.txt | wc -l)
dem_so_dong_tru_sed=$(expr $dem_so_dong - 2)

htaccess_hien_tai=$(cat /usr/local/lsws/$NAME/html/.htaccess)
#kiểm tra đã kích hoạt trước đó chưa
if ! [[ $(echo $htaccess_hien_tai | grep '#tuong-lua-bao-mat-7g') ]];then
echoDo "website $NAME chưa được kích hoạt tường lửa 7G"
. /etc/wptt/wptt-bao-mat-main 1
exit
fi

sed -i '/#tuong-lua-bao-mat-7g/,+'$dem_so_dong_tru_sed'd' /usr/local/lsws/$NAME/html/.htaccess
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

sed -i '/tuong_lua_7g/d' /etc/wptt/vhost/.$NAME.conf

echoDone "Hoàn tất hủy Kích hoạt tường lửa 7G cho website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

