#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Kiem tra toc do hook WordPress                    |"
echo "========================================================================="
. /etc/wptt-user/tenmien
echo ""
echo ""
echo "Lua chon website wordpress kiem tra hook speed: "
echo ""
lua_chon_NAME

pathcheck="/etc/wptt-user/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt-user/wptt-wordpress-main
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt-user/wptt-wordpress-main
  exit
fi


    wp package install wp-cli/profile-command --allow-root

path="/usr/local/lsws/$NAME/html"

wp profile hook --allow-root --path="$path"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-wordpress-main 1
fi
