#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Update ghi de wordpress core                      |"
echo "========================================================================="
. /etc/wptt-user/tenmien
lua_chon_NAME
path="/usr/local/lsws/$NAME/html"
echo "Dang tien hanh reinstall wordpress core cho website $NAME"
cd "$path"
wp core download --skip-content --force --allow-root --path="$path"
echo "hoan tat"
