#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Tai plugin LiteSpeed Cache                        |"
echo "========================================================================="
. /etc/wptt/tenmien
lua_chon_NAME

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

if [[ -f /etc/redis.conf ]]; then
  data_wptangtoc="wptangtoc-rs.data"
else
  data_wptangtoc="wptangtoc.data"
fi

path="/usr/local/lsws/$NAME/html"

pathcheckplugin="/usr/local/lsws/$NAME/html/wp-content/plugins/litespeed-cache"
if [[ -d "$pathcheckplugin" ]]; then
  echo "Bạn đã sử dụng kích hoạt plugin LiteSpeed cache rồi"
  echo "Bạn có muốn import tối ưu theo cách của WPTangToc cho LiteSpeed Cache không ? "
  prompt="Nhập lựa chọn của bạn [1-2]: "
  dongynhap="n"
  options=("Đồng ý" "Không đồng ý")
  PS3="$prompt"
  select opt in "${options[@]}"; do
    case "$REPLY" in
    1)
      dongynhap="y"
      break
      ;;

    2)
      dongynhap="n"
      break
      ;;

    $((${#options[@]} + 1)))
      printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
      break
      ;;
    *)
      printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
      break
      ;;
    esac
  done

  if [[ "$dongynhap" = "y" ]]; then
    echo ""
    echo "Dang toi uu theo cach cua wptangtoc"
    echo ""

    ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')

    sed -i "/WP_CACHE/d" /usr/local/lsws/"$NAME"/html/wp-config.php
    rm -rf /usr/local/lsws/"$NAME"/html/wp-content/cache
    rm -f /usr/local/lsws/"$NAME"/html/wp-content/object-cache.php

    cd "$path" && wget https://wptangtoc.com/share/$data_wptangtoc
    if [[ ! -f $path/$data_wptangtoc ]]; then
      cd "$path" && wget -q https://wptangtoc.com/share/$data_wptangtoc --no-check-certificate
    fi

    wp plugin activate litespeed-cache --allow-root --path="$path"
    wp litespeed-option import $data_wptangtoc --path="$path" --allow-root
    wp option patch update litespeed.conf.server_ip $ip --path="$path" --allow-root
    if [[ ! -f /etc/redis.conf && ! -d /usr/local/lsmcd ]]; then
      wp option patch update litespeed.conf.object 0 --path="$path" --allow-root
      rm -f /usr/local/lsws/"$NAME"/html/wp-content/object-cache.php
      wp litespeed-option set object false --path="$path" --allow-root
    fi
    rm -f $data_wptangtoc
    echo "Hoan tat qua trinh import nhap du lieu wptangtoc cho litespeed"
  fi
  exit
fi
pluginsspeed=(
  cache-enabler
  wp-rocket
  w3-total-cache
  wp-super-cache
  wp2speed
  nitropack
  wp-fastest-cache
  hummingbird-performance
  swift-performance-lite
  swift-performance-pro
  cache-enabler
  sg-cachepress
  breeze
  wp-meteor
  phastpress
  flying-press
  comet-cache
  powered-cache
  borlabs-cache
  hyper-cache
  wp-speed-of-light
  surge
  nginx-helper
)

for plugintt in ${pluginsspeed[@]}; do
  pathcheckplugin3="/usr/local/lsws/$NAME/html/wp-content/plugins/$plugintt"
  if [[ -d "$pathcheckplugin3" ]]; then
    echo "Ban da su dung plugin $plugintt wordpress thi khong nen kich hoat LScache de tranh xung dot"
    echo "Neu ban muon su dung Lscache thi hay xoa plugin $plugintt di"
    exit
  fi

done

echo "Dang tien hanh tai plugin LiteSpeed Cache cho website $NAME"

cd "$path"
rm -f /usr/local/lsws/"$NAME"/html/wp-content/object-cache.php
wp plugin install litespeed-cache --activate --allow-root --path="$path"
echo "Hoan tat tai plugin LiteSpeed cache va kich hoat"
echo "Dang toi uu theo cach cua wptangtoc"
cd "$path" && wget https://wptangtoc.com/share/$data_wptangtoc
wp litespeed-option import $data_wptangtoc --path="$path" --allow-root
rm -f $data_wptangtoc
ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')
wp option patch update litespeed.conf.server_ip $ip --path="$path" --allow-root
chown -R $User_name_vhost:$User_name_vhost /usr/local/lsws/"$NAME"/html/wp-content
cd /usr/local/lsws/"$NAME"/html/wp-content && find . -type d -exec chmod 755 {} \;
cd /usr/local/lsws/"$NAME"/html/wp-content && find . -type f -exec chmod 644 {} \;

wp rewrite flush --allow-root --path="$path"
/usr/local/lsws/bin/lswsctrl restart

echo "==================================================================="
echo "Hoan tat qua trinh tai plugin Litespeed va tu dong toi uu hoa"
echo "Cong cu phat trien boi	: Gia Tuan"
echo "Yeu Cau Ho tro		: wptangtoc.com/lien-he"
echo "Tai tro phat trien	: wptangtoc.com/donate"
echo "==================================================================="
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi
