#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Tăng mức giới hạn WordPress                       |"
echo "========================================================================="
. /etc/wptt-user/tenmien
lua_chon_NAME

. /etc/wptt-user/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt-user/wptt-wordpress-main 1
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt-user/wptt-wordpress-main 1
  exit
fi

_runing "Tăng giới hạn Ram WordPress website $NAME"
wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
sed -i "/WP_MEMORY_LIMIT/d" "$wp_config"
sed -i "/<?php/a define( 'WP_MEMORY_LIMIT', '128M' );" "$wp_config"
_rundone "Tăng giới hạn Ram WordPress website $NAME"

