#!/bin/bash
echo ""
echo ""
echo ""
echo "==================================================================================="
echo "|Quan ly WordPress => tat chinh sua giao dien code truc tiep tren wordpress admin |                               "
echo "==================================================================================="
. /etc/wptt-user/tenmien
lua_chon_NAME

. /etc/wptt/echo-color

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt-user/wptt-wordpress-main 1
  exit
fi



echo "Xác nhận kích hoạt tắt sửa code trực tiếp trên wp-admin"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


if [[ "$dongy" = "y" ]]; then

 /etc/wptt-user/echo-color
wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
if [[ ! -f $wp_config ]];then
echoDo "không xác định được file wp-config của website $NAME"
. /etc/wptt-user/wptt-wordpress-main 1
fi

_runing "Tắt sửa code trực tiếp trên wp-admin"
sed -i "/DISALLOW_FILE_EDIT/d" "$wp_config"
sed -i "/DISALLOW_FILE_MODS/d" "$wp_config"
sed -i "/<?php/a define( 'DISALLOW_FILE_EDIT', true);" "$wp_config"
sed -i "/<?php/a define( 'DISALLOW_FILE_MODS', true);" "$wp_config"
_rundone "Tắt sửa code trực tiếp trên wp-admin"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-wordpress-main 1
fi

