#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Thay đổi tiền tố database                         |"
echo "========================================================================="
. /etc/wptt-user/tenmien
lua_chon_NAME
. /etc/wptt-user/echo-color

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt-user/wptt-wordpress-main 1
  exit
fi


if [[ ! -d /root/.wp-cli/packages/vendor/iandunn/wp-cli-rename-db-prefix ]]; then
	_runing "Cài đặt WP CLI package rename database"
    wp package install iandunn/wp-cli-rename-db-prefix --allow-root
	_rundone "Cài đặt WP CLI package rename database"
fi

path="/usr/local/lsws/$NAME/html"


ramdom_db=$(
	date +%s | sha256sum | base64 | head -c 5
	echo
)


if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
check_mulsite_dang_su_dung=$(cat /usr/local/lsws/$NAME/html/wp-config.php | grep MULTISITE)
if [[ $check_mulsite_dang_su_dung ]];then
echo "Tinh nang nay hien tai khong ho tro WordPress Multisite"
exit
fi
fi

tien_to_cu=$(wp db prefix --allow-root --path=$path 2>/dev/null)
read -p "Xác nhận thay đổi tiền tố database cho website $NAME từ $tien_to_cu thành ${ramdom_db}_ (y/n): " dongyluon
if [[ "$dongyluon" = "y" ]];then
	_runing "Thay dổi tiền tố database cho website $NAME"
wp rename-db-prefix "${ramdom_db}"_ --allow-root --path="$path" >/dev/null 2>&1
tien_to_moi=$(wp db prefix --allow-root --path=$path 2>/dev/null)
if [[ $tien_to_moi != $tien_to_cu ]];then
	_rundone "Thay dổi tiền tố database cho website $NAME"
else
	_runloi "Thay dổi tiền tố database cho website $NAME"
fi


fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-wordpress-main 1
fi

