#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Toi uu database                                   |"
echo "========================================================================="
. /etc/wptt-user/tenmien
lua_chon_NAME

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt-user/wptt-wordpress-main
  exit
fi


path="/usr/local/lsws/$NAME/html"
echo "Dang tien hanh toi uu database cho website $NAME"
wp db optimize --path="$path" --allow-root
echo "hoan tat"
