#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Chuyển đổi unix socket database                   |"
echo "========================================================================="
. /etc/wptt-user/tenmien
echo ""
echo ""
echo "Lựa chọn website muốn chuyển đổi unix socket database: "
echo ""
lua_chon_NAME

. /etc/wptt-user/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt-user/wptt-wordpress-main 1
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt-user/wptt-wordpress-main 1
  exit
fi


check1=$(grep -c 'mysql.sock' /usr/local/lsws/"$NAME"/html/wp-config.php)
if [[ "$check1" = "1" ]]; then
    echo "Ban da kich hoat unix socket database truoc do"
    exit
fi

	_runing "Chuyển đổi unix stocket database"
	sed -i "/DB_HOST/s/'[^']*'/':\/var\/lib\/mysql\/mysql.sock'/2" /usr/local/lsws/"$NAME"/html/wp-config.php
	_rundone "Chuyển đổi unix stocket database"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-wordpress-main 1
fi

