#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Update va ghi den WORDPRESS(Core + Plugin + Theme)|"
echo "========================================================================="

. /etc/wptt-user/tenmien
lua_chon_NAME


pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt-user/wptt-wordpress-main
  exit
fi


path="/usr/local/lsws/$NAME/html"
wp plugin install $(wp plugin list --field=name) --force --allow-root --path="$path"
wp theme install $(wp theme list --field=name) --force= --allow-root --path="$path"
wp core download --skip-content --force --allow-root --path="$path"

echo "==================================================================="
echo "   Qua trinh cap nhat plugin va themes va wordpress da hoan tat    "
echo "==================================================================="
