#!/bin/bash
. /etc/wptt/.wptt.conf

if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_cache => $xoa_opcache                       |"
echo "========================================================================="
echo ""
echo ""

. /etc/wptt/echo-color
_runing "$don_dep OPCache Cache"
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "$don_dep OPCache Cache"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-cache-main 1
fi

