#!/bin/bash

if [[ - d /usr/local/lsmcd ]];then
echo "Ban da kich hoat lsmemcached"
exit
fi

echo "Tien hanh kich hoat lsmemcached"
yum groupinstall "Development Tools" -y
yum install autoconf automake zlib-devel openssl-devel expat-devel pcre-devel libmemcached-devel cyrus-sasl* -y
git clone https://github.com/litespeedtech/lsmcd.git
cd lsmcd
./fixtimestamp.sh
./configure CFLAGS=" -O3" CXXFLAGS=" -O3"
make
sudo make install
echo 'Repl.HeartBeatReq=30
Repl.HeartBeatRetry=3000
Repl.MaxTidPacket=2048000
Repl.GzipStream=YES
Repl.LbAddrs=127.0.0.1:12340
Repl.ListenSvrAddr=127.0.0.1:12340
REPL.DispatchAddr=127.0.0.1:5501
RepldSockPath=/tmp/repld.usock
CACHED.PRIADDR=127.0.0.1:11000

#CACHED.ADDR=127.0.0.1:11211
CACHED.ADDR=UDS:///tmp/lsmcd.sock
#default is 8, it can be bigger depending on cache data amount
Cached.Slices=8
Cached.Slice.Priority.0=100
Cached.Slice.Priority.1=100
Cached.Slice.Priority.2=100
Cached.Slice.Priority.3=100
Cached.Slice.Priority.4=100
Cached.Slice.Priority.5=100
Cached.Slice.Priority.6=100
Cached.Slice.Priority.7=100

Cached.ShmDir=/dev/shm/lsmcd
#If you change the UseSasl or DataByUser configuration options you need to remove the ShmDir folder and contents.
#Cached.UseSasl=true
#Cached.DataByUser=true
#Cached.Anonymous=false
#Cached.UserSize=1000
#Cached.HashSize=500000
#CACHED.MEMMAXSZ=0
#CACHED.NOMEMFAIL=false

##this is the global setting, no need to have per slice configuration. 
User=nobody
Group=nobody
#depends CPU core
CachedProcCnt=4
CachedSockPath=/tmp/cached.usock.
#TmpDir=/tmp/lsmcd
LogLevel=notice
#LogLevel=dbg_medium
LogFile=/tmp/lsmcd.log
' >/usr/local/lsmcd/conf/node.conf
echo '                               .:---::::::::::
                          .:-=+++++++=::::::::
                       .-++++++++++++*+=::::::
                    .-+++++++****++++++*+=::::
                  .=++++++#%@@@@@@%*+++++*+=::
                .=++++++*@@@%%%%%@@@%*+++++*+.
               -+++++++*@@%########@@%++++++= 
         .:::-+++++++++#@@#########%@@*+++++. 
      ::---:-++++++++++*@@%########@@@+++++:  
    :-----:-*+++++++++++#@@@%###%%@@@*++++-   
  .------:-++++++++++++++*#@@@@@@@%#+++++-    
 .----::::+++++++++*++++++++******++++++:     
.-:.     -++++++*++=--++++++++++++++++-       
.      :=****+*+=--:=+++++++++++++++=.        
     :*##%%%%%+-::-+*+++++++++++++=.          
    =##%%%%%#=::=++*+++++++++*++-.            
   :##%%%%%*--+*%%*+++++***++=-:              
   *#####%#+*#%%%%#*++++==--::-.              
   :=##%%%%%%%%%%##=:..-::----:               
    *#%%####%%%##*:   :------.                
   -###*+*####*=:    .-----:                  
    ..   :-::.      .---:.                    
                   .::.                       
'
echo "Hoan tat cai dat object cache LSmemcached"
systemctl start lsmcd
systemctl enable lsmcd
/usr/local/lsmcd/bin/lsmcdctrl start
systemctl restart lsws
