#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
. /etc/wptt/echo-color
NAME=$1

if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ "$NAME" = "" ]]; then
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Cache => Xoa cache 	                                          |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website ban muon xoa toan bo Cache: "
echo ""
lua_chon_NAME
fi
pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
	echoDo "Khong xac dinh duoc domain"
    clear
    . /etc/wptt/wptt-wordpress-main
return 2>/dev/null ; exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "He thong xac nhan ban chua kich hoat su dung WordPress"
  echoDo "Tinh nang nay clear cache WordPress chi ho tro website WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main
return 2>/dev/null ; exit
fi


path2="/usr/local/lsws/$NAME/html"
cd /usr/local/lsws/$NAME/html
wp cache flush --path=$path2 --allow-root 2>/dev/null
pathcheckplugin="/usr/local/lsws/$NAME/html/wp-content/plugins/litespeed-cache"
if [[ -d "$pathcheckplugin" ]]; then
	echo 'Tien hanh xoa cache LiteSpeed cache'
    wp litespeed-purge all --path=$path2 --allow-root 2>/dev/null
fi

if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/swift-performance-lite ]];then
	echo 'Tien hanh xoa cache swift preformance'
	wp sp_clear_all_cache --allow-root --path="$path2" 2>/dev/null
fi


if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/swift-performance ]];then
	echo 'Tien hanh xoa cache swift preformance'
	wp sp_clear_all_cache --allow-root --path="$path2" 2>/dev/null
fi

path_plugin_wprocket="/usr/local/lsws/$NAME/html/wp-content/plugins/wp-rocket"
if [[ -d "$path_plugin_wprocket" ]]; then
	echo 'Tien hanh xoa cache wp rocket'
	wp eval 'rocket_clean_domain();' --allow-root --path="$path2" 2>/dev/null
fi

if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/w3-total-cache ]];then
	echo 'Tien hanh xoa cache w3-total-cache'
	wp eval 'w3tc_pgcache_flush();' --allow-root --path="$path2" 2>/dev/null
fi


if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/cache-enabler ]];then
	echo 'Tien hanh xoa cache cache-enabler'
	wp eval 'Cache_Enabler::clear_total_cache();' --allow-root --path="$path2" 2>/dev/null
fi


if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/autoptimize ]];then
	echo 'Tien hanh xoa cache autoptimize'
	wp eval 'autoptimizeCache::clearall();' --allow-root --path="$path2" 2>/dev/null
fi


if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/flying-press ]];then
	echo 'Tien hanh xoa cache flying-press'
	wp eval 'Purge::purge_cached_pages();' --allow-root --path="$path2" 2>/dev/null
fi

if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/wp-optimize ]];then
	echo 'Tien hanh xoa cache wp-optimize'
	wp eval '$wpoptimize_cache_commands = new WP_Optimize_Cache_Commands(); $wpoptimize_cache_commands->purge_page_cache();' --allow-root --path="$path2" 2>/dev/null
fi

echoDone "Hoan tat qua trinh clear cache website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-cache-main 1
fi

