#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
. /etc/wptt/echo-color
NAME=$1

if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ "$NAME" = "" ]]; then
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Cache => Xóa cache 	                                          |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website bạn muốn xóa toàn bộ Cache:"
echo ""
lua_chon_NAME
fi


. /etc/wptt/echo-color

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt/wptt-cache-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
. /etc/wptt/wptt-cache-main 1
return 2>/dev/null ; exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng mã nguồn WordPress"
  echoDo "Tính năng này chỉ dành cho mã nguồn WordPress"
  sleep 3
. /etc/wptt/wptt-cache-main 1
return 2>/dev/null ; exit
fi


path2="/usr/local/lsws/$NAME/html"

plugins_active=$(wp plugin list --fields=name --status=active --path=$path2 --allow-root 2>/dev/null | sed '1d')

wp cache flush --path=$path2 --allow-root 2>/dev/null
pathcheckplugin="/usr/local/lsws/$NAME/html/wp-content/plugins/litespeed-cache"
if [[ $(echo $plugins_active | grep 'litespeed-cache') ]]; then
	echo 'Tiến hành xóa cache của LiteSpeed cache'
    wp litespeed-purge all --path=$path2 --allow-root 2>/dev/null
fi

if [[ $(echo $plugins_active | grep 'swift-performance-lite') ]];then
	echo 'Tien hanh xoa cache swift preformance'
	wp sp_clear_all_cache --allow-root --path="$path2" 2>/dev/null
fi


if [[ $(echo $plugins_active | grep 'swift-performance') ]];then
	echo 'Tiến hành xóa cache của swift preformance'
	wp sp_clear_all_cache --allow-root --path="$path2" 2>/dev/null
fi

if [[ $(echo $plugins_active | grep 'wp-rocket') ]];then
	echo 'Tiến hành xóa cache của wp rocket'
	wp eval 'rocket_clean_domain();' --allow-root --path="$path2" 2>/dev/null
fi

if [[ $(echo $plugins_active | grep 'w3-total-cache') ]];then
	echo 'Tiến hành xóa cache của w3-total-cache'
	wp eval 'w3tc_pgcache_flush();' --allow-root --path="$path2" 2>/dev/null
fi


if [[ $(echo $plugins_active | grep 'cache-enabler') ]];then
	echo 'Tiến hành xóa cache của cache-enabler'
	wp eval 'Cache_Enabler::clear_total_cache();' --allow-root --path="$path2" 2>/dev/null
fi


if [[ $(echo $plugins_active | grep 'autoptimize') ]];then
	echo 'Tiến hành xóa cache của autoptimize'
	wp eval 'autoptimizeCache::clearall();' --allow-root --path="$path2" 2>/dev/null
fi


if [[ $(echo $plugins_active | grep 'flying-press') ]];then
	echo 'Tiến hành xóa cache của flying-press'
	wp eval 'Purge::purge_cached_pages();' --allow-root --path="$path2" 2>/dev/null
fi

if [[ $(echo $plugins_active | grep 'wp-optimize') ]];then
	echo 'Tiến hành xóa cache của wp-optimize'
	wp eval '$wpoptimize_cache_commands = new WP_Optimize_Cache_Commands(); $wpoptimize_cache_commands->purge_page_cache();' --allow-root --path="$path2" 2>/dev/null
fi


if [[ $(echo $plugins_active | grep 'breeze') ]];then
	echo 'Tiến hành xóa cache của breeze'
	wp eval "do_action('breeze_clear_all_cache');" --allow-root --path="$path2" 2>/dev/null
fi


if [[ $(echo $plugins_active | grep 'wp-fastest-cache') ]];then
	echo 'Tiến hành xóa cache của wp-fastest-cache'
	wp fastest-cache clear all --allow-root --path="$path2" 2>/dev/null
fi

if [[ $(echo $plugins_active | grep 'wp-performance') ]];then
	echo 'Tiến hành xóa cache của WP Performance'
	wp wpp flush  --allow-root --path="$path2" 2>/dev/null
fi

if [[ $(echo $plugins_active | grep 'wp-super-cache') ]];then
	echo 'Tiến hành xóa cache của wp-super-cache'
	wp eval 'global $file_prefix, $supercachedir;if ( empty( $supercachedir ) && function_exists( "get_supercache_dir" ) ) {$supercachedir = get_supercache_dir();}wp_cache_clean_cache( $file_prefix );' --allow-root --path="$path2" 2>/dev/null
fi

echoDone "Hoàn tất quá trình xóa cache cho website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-cache-main 1
fi

