#!/bin/bash
if [[ -d /usr/local/lsmcd ]];then
echo "Ban chua kich hoat lsmemcached"
exit
fi

systemctl start lsmcd
systemctl enable lsmcd
/usr/local/lsmcd/bin/lsmcdctrl start
/usr/local/lsws/bin/lswsctrl restart
systemctl restart lsws

echo "Hoan tat bat LSmemcached"
