#!/bin/bash

echo "========================================================================="
echo "|Quản lý Cache => Hủy kích hoạt lsmemcached                             |"
echo "========================================================================="
if [[ ! -d /usr/local/lsmcd ]];then
echo "Bạn chưa cài đặt lsmemcached"
. /etc/wptt/wptt-cache-main 1
exit
fi
. /etc/wptt/.wptt.conf

# xóa lsphp memcached khi không có memcached
if [[ ! -f /etc/sysconfig/memcached ]];then
lsphp=($(ls /usr/local/lsws | grep 'lsphp' | sed 's/^lsphp//g'))
for phpmemcached in ${lsphp[@]};do
yum remove lsphp${phpmemcached}-pecl-memcached -y
done
fi

systemctl stop lsmcd
systemctl disable lsmcd
rm -rf /usr/local/lsmcd
rm -rf ~/lsmcd
rm -rf /dev/shm/lsmcd
rm -rf /tmp/lsmcd
rm -f /tmp/lsmcd.log


/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
systemctl restart lsws

. /etc/wptt/echo-color
echoDone "Hủy cài đặt LSmemcached thành công"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-cache-main 1
fi

