#!/bin/bash

if [[ -f /etc/redis.conf ]];then
echo "Ban da kich hoat redis"
exit
fi
        echo '[litespeed]
name=LiteSpeed Tech Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/centos/$releasever/$basearch/
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-update]
name=LiteSpeed Tech Update Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/centos/$releasever/update/$basearch/
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-edge]
name=LiteSpeed Tech Edge Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/edge/centos/$releasever/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-edge-update]
name=LiteSpeed Tech Edge Update Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/edge/centos/$releasever/update/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed
' >/etc/yum.repos.d/litespeed.repo
yum install redis -y
. /etc/wptt/.wptt.conf
php_ver_chon=${php_version_check//[-._]/}
yum install lsphp${php_ver_chon}-pecl-redis -y
        echo '[litespeed]
name=LiteSpeed Tech Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/centos/$releasever/$basearch/
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-update]
name=LiteSpeed Tech Update Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/centos/$releasever/update/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-edge]
name=LiteSpeed Tech Edge Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/edge/centos/$releasever/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-edge-update]
name=LiteSpeed Tech Edge Update Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/edge/centos/$releasever/update/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed
' >/etc/yum.repos.d/litespeed.repo

echo '                               .:---::::::::::
                          .:-=+++++++=::::::::
                       .-++++++++++++*+=::::::
                    .-+++++++****++++++*+=::::
                  .=++++++#%@@@@@@%*+++++*+=::
                .=++++++*@@@%%%%%@@@%*+++++*+.
               -+++++++*@@%########@@%++++++= 
         .:::-+++++++++#@@#########%@@*+++++. 
      ::---:-++++++++++*@@%########@@@+++++:  
    :-----:-*+++++++++++#@@@%###%%@@@*++++-   
  .------:-++++++++++++++*#@@@@@@@%#+++++-    
 .----::::+++++++++*++++++++******++++++:     
.-:.     -++++++*++=--++++++++++++++++-       
.      :=****+*+=--:=+++++++++++++++=.        
     :*##%%%%%+-::-+*+++++++++++++=.          
    =##%%%%%#=::=++*+++++++++*++-.            
   :##%%%%%*--+*%%*+++++***++=-:              
   *#####%#+*#%%%%#*++++==--::-.              
   :=##%%%%%%%%%%##=:..-::----:               
    *#%%####%%%##*:   :------.                
   -###*+*####*=:    .-----:                  
    ..   :-::.      .---:.                    
                   .::.                       
'
work_cpucore=$(ulimit -n)
cpucore=$(grep -c ^processor /proc/cpuinfo)
max_client=$(expr $work_cpucore \* $cpucore \* 2)
max_client_max=$(expr $work_cpucore \* $cpucore \* 3)
max_client_php=$(expr $work_cpucore \* $cpucore \/ 8)
tong_ram_byte=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
rong_ram_mb=$(echo "scale=0;${tong_ram_byte}/1024" | bc)
if [[ "$rong_ram_mb" = "" ]]; then
  rong_ram_mb="2048"
fi
tong_ram_mb_db=$(echo "scale=0;${rong_ram_mb}/1.4" | bc)
tong_ram_gb=$(expr ${rong_ram_mb} / 1024)
db_table_size=$(expr $tong_ram_gb \* 64 )
buffer_db=$(expr $rong_ram_mb / 5)
echo "unixsocket /tmp/redis.sock
unixsocketperm 777
maxmemory ${tong_ram_mb_db}mb
maxmemory-policy allkeys-lru" >> /etc/redis.conf
mkdir -p /var/run/redis
chmod 700 /var/lib/redis
chown redis:redis /var/run/redis
chown redis:redis /etc/redis.conf
chmod 600 /etc/redis.conf
semanage permissive -a redis_t
echo "Hoan tat cai dat object cache Redis"
            systemctl enable redis.service
            systemctl start redis.service
systemctl restart lsws
echo 'Hay dien file doan ma nay vao file wp-config.php'
echo "define('WP_REDIS_SCHEME', 'unix');
define('WP_REDIS_PATH', '/var/run/redis/redis.sock');"
