#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022

echo "========================================================================="
echo "|Quản lý Cache => Kích hoạt Redis 		                             |"
echo "========================================================================="


if [[ -f /etc/redis.conf ]];then
echo "Bạn đã cài đặt redis trước đó"
. /etc/wptt/wptt-cache-main 1
exit
fi

. /etc/wptt/echo-color

        echo '[litespeed]
name=LiteSpeed Tech Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/centos/$releasever/$basearch/
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-update]
name=LiteSpeed Tech Update Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/centos/$releasever/update/$basearch/
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-edge]
name=LiteSpeed Tech Edge Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/edge/centos/$releasever/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-edge-update]
name=LiteSpeed Tech Edge Update Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/edge/centos/$releasever/update/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed
' >/etc/yum.repos.d/litespeed.repo

_runing "Cài đặt redis"
yum install redis -y >/dev/null 2>&1
lsphp=($(ls /usr/local/lsws | grep 'lsphp' | sed 's/^lsphp//g'))
for phpredis in ${lsphp[@]};do
yum install lsphp${phpredis}-pecl-redis -y >/dev/null 2>&1
done
_runing "Cài đặt redis"


        echo '[litespeed]
name=LiteSpeed Tech Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/centos/$releasever/$basearch/
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-update]
name=LiteSpeed Tech Update Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/centos/$releasever/update/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-edge]
name=LiteSpeed Tech Edge Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/edge/centos/$releasever/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed

[litespeed-edge-update]
name=LiteSpeed Tech Edge Update Repository for CentOS $releasever - $basearch
baseurl=http://rpms.litespeedtech.com/edge/centos/$releasever/update/$basearch/
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-litespeed
' >/etc/yum.repos.d/litespeed.repo

_runing "Cấu hình redis"

echo "unixsocket /var/run/redis/redis.sock
unixsocketperm 777
maxmemory 128mb
maxmemory-policy allkeys-lru
save \"\"" >> /etc/redis.conf

sed -i 's/tcp-keepalive 300/tcp-keepalive 0/g' /etc/redis.conf
sed -i 's/rdbcompression yes/rdbcompression no/g' /etc/redis.conf
sed -i 's/rdbchecksum yes/rdbchecksum no/g' /etc/redis.conf

mkdir -p /var/run/redis
chmod 700 /var/lib/redis
chown redis:redis /var/run/redis
chown redis:redis /etc/redis.conf
chmod 600 /etc/redis.conf
systemctl enable redis.service
systemctl start redis.service
systemctl restart lsws
_rundone "Cấu hình redis"
echo "Bạn có thể sử dụng plugin LiteSpeed để quản trị object cache redis"
echo "Địa chỉHOST unix stocket: /var/run/redis/redis.sock"


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-cache-main 1
fi

