#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025

function huong_dan(){
Việc thay đổi cổng [port] mặc định [thường là 19019] của WebAdmin GUI OpenLiteSpeed là một biện pháp bảo mật hữu ích, giúp ẩn giao diện quản trị khỏi các máy quét cổng tự động và giảm thiểu nguy cơ bị tấn công.

Dưới đây là giới thiệu ngắn gọn về tính năng này:

Tại sao cần đổi cổng WebAdmin GUI?
 * Bảo mật qua việc ẩn náu [Security through obscurity]: Hầu hết các bot và kẻ tấn công tự động thường quét các cổng mặc định của những dịch vụ phổ biến. Việc đổi sang một cổng không chuẩn sẽ khiến giao diện quản trị của bạn khó bị phát hiện hơn.
 * Tránh xung đột cổng: Nếu cổng 19019 đang được sử dụng bởi một dịch vụ khác trên máy chủ của bạn, việc đổi cổng cho WebAdmin là cần thiết.
 * Tuân thủ chính sách: Một số tổ chức có chính sách yêu cầu thay đổi cổng mặc định của các dịch vụ quản trị.

Luôn nhớ sao lưu tệp cấu hình trước khi thực hiện thay đổi và đảm bảo rằng cổng bạn chọn không bị xung đột với các dịch vụ khác đang chạy trên máy chủ.
}


echo "========================================================================="
echo "|Quản lý WebGuiAdmin => Đổi Port                                        |"
echo "========================================================================="

. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color
path="/usr/local/lsws/conf/disablewebconsole"
if [[ -f $path ]]; then
    echo "Bạn đã tắt webguiadmin trước đó rồi"
    echo "không cần thiết phải đổi port webguiadmin"
    exit
fi

port_checkssh=$(cat /etc/ssh/sshd_config | grep "Port " | cut -f2 -d" ")
read -p "Nhập port Webguiadmin bạn muốn thay đổi [0=Thoát]: " port
if [[ "$port" = "0" || "$port" = "" ]]; then
    clear
    . /etc/wptt/wptt-webadmin-main 1
    exit
fi

if [[ $port = '0' || $port = '' ]];then
    . /etc/wptt/wptt-webadmin-main 1
fi

if [[ ! $port =~ ^-?[0-9]+$ ]]; then
    clear
    echo "Port không đúng định dạng, vui lòng nhập port từ 1 - 65535"
    . /etc/wptt/wptt-webadmin-main 1
fi

port_webgui_openlitespeed=$(cat /usr/local/lsws/admin/conf/admin_config.conf | grep "address" | cut -f2 -d":")

if [[ "$port" = "22" || "$port" = "$port_checkssh" || "$port" = "80" || "$port" = "443" || "$port" = "$port_webgui_openlitespeed" ]]; then
    echo "Ban vui long chon cong port khac cong port nay da duoc su dung"
    sleep 3
    . /etc/wptt/wptt-webadmin-main 1
    exit
fi

if (("$port" > 65535)); then
    echo "port ban muon chuyen > 65535 he thong khong cho phep doi"
    sleep 3
    . /etc/wptt/wptt-webadmin-main 1
    exit 
fi

_runing "Đổi port webguiadmin thành $port"


ipv6=$(curl -s --connect-timeout 5 --max-time 10 https://ipv6.icanhazip.com)
sed -i -e '/^listener adminListener/,/^}$/d' /usr/local/lsws/admin/conf/admin_config.conf
if [[ $ipv6 = '' ]];then #chỉ support only ipv4
	echo 'listener adminListener{
address               *:'$port'
secure                1
keyFile               $SERVER_ROOT/admin/conf/webadmin.key
certFile              $SERVER_ROOT/admin/conf/webadmin.crt
clientVerify          0
}' >> /usr/local/lsws/admin/conf/admin_config.conf
else #ipv6 support thêm
	echo 'listener adminListener{
address               [ANY]:'$port'
secure                1
keyFile               $SERVER_ROOT/admin/conf/webadmin.key
certFile              $SERVER_ROOT/admin/conf/webadmin.crt
clientVerify          0
}' >> /usr/local/lsws/admin/conf/admin_config.conf
fi



firewall-cmd --permanent --zone=public --add-port="$port"/tcp >/dev/null 2>&1
firewall-cmd --permanent --zone=public --remove-port=$port_webgui_openlitespeed/tcp >/dev/null 2>&1

firewall-cmd --reload >/dev/null 2>&1


#csf
if [[ -f /etc/csf/csf.conf ]];then
	if [[ $(cat /etc/csf/csf.conf | grep '^TCP_IN' | grep "$port,") = '' ]];then
		#xoa port
		sed -i -r '/^TCP_IN /s/"'$port_webgui_openlitespeed'"/""/; s/([",])'$port_webgui_openlitespeed',|,'$port_webgui_openlitespeed'([,"])/\1\2/' /etc/csf/csf.conf


		#mo port
		sed -i "s/^TCP_IN = \"/TCP_IN = \"$port,/g" /etc/csf/csf.conf

		csf -x >/dev/null 2>&1
		csf -e >/dev/null 2>&1
	fi
fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
sed -i "/port_webgui_openlitespeed=/d" /etc/wptt/.wptt.conf
echo "port_webgui_openlitespeed=$port" >>/etc/wptt/.wptt.conf


ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com |grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com| grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')

_rundone "Đổi port webguiadmin thành $port"

echo "Da doi cong port webguiadmin tu $port_webgui_openlitespeed thanh $port"
echo "-------------------------------------------------------------------------"
echo "              Luu lai thong tin ben duoi de truy cap ve sau              "
echo "-------------------------------------------------------------------------"
echo "1.	WebAdmin console port: $port                	               		  "
if [[ $ip ]];then
echo "2.	truy cập webgui OLS: http://$ip:$port            	        	 "
fi
if [[ $ipv6 ]];then
echo "2.	truy cập webgui OLS: http://[$ipv6]:$port            	        	 "
fi
echo "3.	Ten dang nhap OLS webgui:  $Ten_dang_nhap_ols_webgui                        		   "
echo "4.	Password OLS webgui:  $Password_OLS_webgui                    	        	 "
echo "5.	Moi thong tin tai khoan duoc luu tru:  /etc/wptt/.wptt.conf       	 "
echo "-------------------------------------------------------------------------"
echo ""
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
 . /etc/wptt/wptt-webadmin-main 1
fi

