#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021

. /etc/wptt/.wptt.conf
path="/usr/local/lsws/conf/disablewebconsole"
if [[ -f $path ]]; then
    echo "Ban da tat webguiadmin truoc do roi"
    echo "Khong can thiet phai doi cong port webguiadmin"
    exit
fi
port_checkssh=$(cat /etc/ssh/sshd_config | grep "Port " | cut -f2 -d" ")
read -p "Nhap port SSH ban muon thay doi [0=Thoat]: " port
if [[ "$port" = "0" || "$port" = "" ]]; then
    clear
    . /etc/wptt/wptt-webadmin-main
    exit
fi

if [[ ! $port =~ ^-?[0-9]+$ ]]; then
    clear
    echo "Port khong dung dinh dang, vui long nhap port tu 1000 - 30000"
    exit
fi

if [[ "$port" = "22" || "$port" = "$port_checkssh" || "$port" = "80" || "$port" = "443" || "$port" = "$port_webgui_openlitespeed" ]]; then
    echo "Ban vui long chon cong port khac cong port nay da duoc su dung"
    exit
fi

sed -i "/address/d" /usr/local/lsws/admin/conf/admin_config.conf
sed -i "/adminListener/a address               *:$port" /usr/local/lsws/admin/conf/admin_config.conf
firewall-cmd --permanent --zone=public --add-port="$port"/tcp
firewall-cmd --reload

echo "Da thay doi cong port webguiadmin thanh $port."
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
sed -i "/port_webgui_openlitespeed=/d" /etc/wptt/.wptt.conf
echo "port_webgui_openlitespeed=$port" >>/etc/wptt/.wptt.conf
ip=$(curl -s myip.directadmin.com)
if [[ "$ip" = "" ]]; then
    ip=$(curl -s ifconfig.me)
fi

echo "Da doi cong port webguiadmin"

echo "              Luu lai thong tin ben duoi de truy cap ve sau              "
echo "-------------------------------------------------------------------------"
echo "1.	WebAdmin console port: $port                	               		  "
echo "2.	Truy cap webgui OLS: http://$ip:$port           	        	 "
echo "3.	Ten dang nhap OLS webgui:  $Ten_dang_nhap_ols_webgui                        		   "
echo "4.	Password OLS webgui:  $Password_OLS_webgui                    	        	 "
echo "5.	Moi thong tin tai khoan duoc luu tru:  /etc/wptt/.wptt.conf       	 "
echo "-------------------------------------------------------------------------"
echo ""
