#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025

function huong_dan(){
Tính năng WebAdmin GUI [Giao diện Quản trị Web] của OpenLiteSpeed là một công cụ mạnh mẽ và thân thiện, giúp bạn dễ dàng cấu hình và quản lý máy chủ web OpenLiteSpeed mà không cần phải thao tác trực tiếp với các tệp cấu hình qua dòng lệnh.

Dưới đây là giới thiệu về tính năng kích hoạt và sử dụng WebAdmin GUI của OpenLiteSpeed:

Mục đích của WebAdmin GUI:
 * Cấu hình trực quan: Cung cấp giao diện đồ họa để bạn có thể xem và chỉnh sửa hầu hết các thiết lập của máy chủ OpenLiteSpeed, từ cài đặt cơ bản đến các tính năng nâng cao.
 * Quản lý dễ dàng: Giúp việc quản lý virtual host [các trang web chạy trên cùng máy chủ], listeners [cổng lắng nghe], module, và các thành phần khác trở nên đơn giản hơn.
 * Theo dõi thời gian thực: Cung cấp các số liệu thống kê và trạng thái máy chủ theo thời gian thực, giúp bạn giám sát hiệu suất và phát hiện sự cố.
 * Giảm thiểu lỗi: Giao diện trực quan giúp hạn chế sai sót so với việc chỉnh sửa thủ công các tệp cấu hình văn bản phức tạp.

 WebAdmin GUI là một thành phần không thể thiếu khi làm việc với OpenLiteSpeed, giúp đơn giản hóa đáng kể công việc quản trị máy chủ web, đồng thời cung cấp nhiều công cụ mạnh mẽ để theo dõi và tối ưu hóa hiệu suất.

 Ghi chú: sử dụng webguiadmin đồng nghĩa với việc một port được mở ra đồng nghĩa với việc thêm một rủi ro bảo mật.
}


. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo "========================================================================="
echo "|$quan_ly_webguiadmin => Kích hoạt                                       |"
echo "========================================================================="

. /etc/wptt/.wptt.conf
path="/usr/local/lsws/conf/disablewebconsole"
if [[ ! -f $path ]]; then
	echo "Bạn đã mở webguiadmin trước đó rồi"
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-webadmin-main 1
	fi
	exit
fi

ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com |grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com| grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')

echo "Xác nhận bạn có muốn mở openlitespeed webgui? "
prompt="Nhập lựa chọn của bạn [1-2]: "
confirm="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			confirm="y"
			break
			;;

		2)
			confirm="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


if [[ "$confirm" = "y" ]]; then
    rm -f /usr/local/lsws/conf/disablewebconsole
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi

echo "Bạn có muốn thay đổi Port webguiadmin OLS? để nâng cao bảo mật"
read -p "Nhập port webguiadmin OLS mới, bỏ qua nhấn (Enter):" port_ols

if [[ $port_ols = '0' ]];then
    echo "Bạn nhập sai dữ liệu sẽ tự động để nguyên port mặc định là cổng port 19019"
    port_ols=19019
fi

if [[ ! $port_ols =~ ^-?[0-9]+$ ]]; then
    clear
    echo "Bạn nhập sai dữ liệu sẽ tự động để nguyên port mặc định là cổng port 19019"
    port_ols=19019
fi

if [ "$port_ols" = '' ]; then
    port_ols=19019
fi


if ! [[ $port_ols =~ ^[0-9]+$ ]] || (( $port_ols < 1 || $port_ols > 65536 )); then
echo "Vui lòng đổi port dưới 65536"
    echo "Bạn nhập sai dữ liệu sẽ tự động để nguyên port mặc định là cổng port 19019"
    port_ols=19019
fi

port_ssh=$(cat /etc/ssh/sshd_config | grep "Port " | grep -o '[0-9]\+$'|| echo 22)

if [ "$port_ols" = "$port_ssh" ]; then
    echo "trùng với công port ssh của bạn $port_ssh"
    echo "Vui lòng thiết lập lại và chọn cổng port khác"
	 . /etc/wptt/wptt-webadmin-main 1
    exit
fi


#port remote database tránh trùng lặp
if $(cat /etc/*release | grep -q "Ubuntu") ; then
	duong_dan_cau_hinh_mariadb="/etc/mysql/my.cnf"
else
	duong_dan_cau_hinh_mariadb="/etc/my.cnf.d/server.cnf"
fi

port_mariadb_remote=$(cat $duong_dan_cau_hinh_mariadb | grep 'port='| grep -o '[0-9]\+$')
if [[ $port_mariadb_remote ]];then
	if [ "$port_ols" = "$port_mariadb_remote" ]; then
		echo "trùng với công port remote database của bạn $port_mariadb_remote"
		echo "Vui lòng thiết lập lại và chọn cổng port khác"
		. /etc/wptt/wptt-webadmin-main 1
		exit
	fi
fi

echo "Xác nhận port_webgui_openlitpeed la: $port_ols"

if [[ $(echo $port_ols) = '' ]];then
	port_ols='19019'
fi

#port_webgui_openlitespeed=$(cat /usr/local/lsws/admin/conf/admin_config.conf | grep "address" | grep -o '[0-9]\+$')
sed -i -e '/^listener adminListener/,/^}$/d' /usr/local/lsws/admin/conf/admin_config.conf
#sed -i "s/$port_webgui_openlitespeed/$port_ols/g" /usr/local/lsws/admin/conf/admin_config.conf
# ipv6=$(ip -6 a | grep 'inet6 ' | awk '{print $2}' | sed '/fe80::/d' | sort -u| cut -f1 -d '/'| grep -Eio '([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|:(:[0-9a-fA-F]{1,4}){1,7}|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])' | sed '/^::1$/d')


ipv4=$(curl -sf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com |grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -sf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com| grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')

if [[ $ipv4  ]];then
	echo 'listener adminListener{
address               *:'$port_ols'
secure                1
keyFile               $SERVER_ROOT/admin/conf/webadmin.key
certFile              $SERVER_ROOT/admin/conf/webadmin.crt
clientVerify          0
}' >> /usr/local/lsws/admin/conf/admin_config.conf
fi

ipv6=$(curl -s --connect-timeout 5 --max-time 10 https://ipv6.icanhazip.com)
if [[ $ipv6 && $ipv4 = '' ]];then #chỉ support only ipv6 mới thực thi
echo 'listener adminListener{
address               [ANY]:'$port_ols'
secure                1
keyFile               $SERVER_ROOT/admin/conf/webadmin.key
certFile              $SERVER_ROOT/admin/conf/webadmin.crt
clientVerify          0
}' >> /usr/local/lsws/admin/conf/admin_config.conf
fi

firewalld_service=$(systemctl status firewalld.service 2>/dev/null | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
if [[ "$firewalld_service" = "active" ]]; then
    firewall-cmd --permanent --zone=public --add-port=$port_ols/tcp
    firewall-cmd --reload
fi
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

if [[ -f /etc/csf/csf.conf ]];then
	if [[ $(cat /etc/csf/csf.conf | grep '^TCP_IN' | grep "$port_ols,") = '' ]];then
		sed -i "s/^TCP_IN = \"/TCP_IN = \"$port_ols,/g" /etc/csf/csf.conf
		csf -x >/dev/null 2>&1
		csf -e >/dev/null 2>&1
	fi
fi


#nftables openlitespeed
nftables_service=$(systemctl status nftables.service 2>/dev/null | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
if [[ "$nftables_service" = "active" ]]; then
	if $(cat /etc/*release | grep -q "Ubuntu") ; then
		path_nftables_config="/etc/nftables.conf"
	else
		path_nftables_config="/etc/sysconfig/nftables.conf"
	fi

	if [[ -f $path_nftables_config ]];then
		sed -i '/#port webguiadmin/d' $path_nftables_config
		sed -i "/chain input /a\ \ tcp dport $port_ols accept #port webguiadmin" $path_nftables_config
		systemctl restart nftables
	fi
fi

Post_Install_Regenerate_Webadmin_Console_Passwd() {
	Webadmin_Pass=$(
	head /dev/urandom | tr -dc A-Za-z0-9 | head -c 36
	echo ''
)
id_ols_admin=$(
date +%s | sha256sum | base64 | head -c 24
echo
)
Encrypt_string=$(/usr/local/lsws/admin/fcgi-bin/admin_php -q /usr/local/lsws/admin/misc/htpasswd.php "${Webadmin_Pass}")
echo "" >/usr/local/lsws/admin/conf/htpasswd
echo "$id_ols_admin:$Encrypt_string" >/usr/local/lsws/admin/conf/htpasswd
}
Post_Install_Regenerate_Webadmin_Console_Passwd

sed -i "/Password_OLS_webgui/d" /etc/wptt/.wptt.conf
sed -i "/Ten_dang_nhap_ols_webgui/d" /etc/wptt/.wptt.conf
echo "Password_OLS_webgui=$Webadmin_Pass
Ten_dang_nhap_ols_webgui=$id_ols_admin" >>/etc/wptt/.wptt.conf


sed -i "/port_webgui_openlitespeed=/d" /etc/wptt/.wptt.conf
echo "
port_webgui_openlitespeed=$port_ols" >>/etc/wptt/.wptt.conf

echo "Mở webguiadmin OLS : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

echo "              Lưu lại thông tin bên dưới để truy cập              "
echo "-------------------------------------------------------------------------"
echo "1.	WebAdmin console port: $port_ols                	               		  "

if [[ $ipv6 && $ipv4 = '' ]];then #chỉ support only ipv6 mới thực thi
echo "2.	truy cập webgui OLS: http://[$ipv6]:$port_ols            	        	 "
else
echo "2.	truy cập webgui OLS: http://${ipv4}:$port_ols            	        	 "
fi
echo "3.	Ten dang nhap OLS webgui:  $id_ols_admin                        		   "
echo "4.	Password OLS webgui:  $Webadmin_Pass                    	        	 "
echo "-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo "Bạn có thể vào menu WPTangToc OLS để xem lại tài khoản webguiadmin"
echo "-------------------------------------------------------------------------"


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
 . /etc/wptt/wptt-webadmin-main 1
fi

