#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022

echo "========================================================================="
echo "|Quản lý WebGuiAdmin => Kích hoạt                                       |"
echo "========================================================================="

. /etc/wptt/.wptt.conf
path="/usr/local/lsws/conf/disablewebconsole"
if [[ ! -f $path ]]; then
    echo "Bạn đã mở webguiadmin trước đó rồi"
    exit
fi

ip=$(curl -s myip.directadmin.com)
if [[ "$ip" = "" ]]; then
    ip=$(curl -s ifconfig.me)
fi

read -p "Xác nhận bạn có muốn mở openlitespeed webgui? (y/n): " confirm
if [[ "$confirm" = "y" ]]; then
    rm -f /usr/local/lsws/conf/disablewebconsole
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi
echo "Bạn có muốn thay đổi Port webguiadmin OLS? để nâng cao bảo mật"
read -p "Nhập port webguiadmin OLS mới, bỏ qua nhấn (Enter): " port_ols

if [[ ! $port_ols =~ ^-?[0-9]+$ ]]; then
    clear
    echo "Ban nhap sai du lieu se tu dong de nguyen port mac dinh la cong 19019"
    port_ols=19019
fi

if [ "$port_ols" = '' ]; then
    port_ols=19019
fi

if [ "$port_ols" = "$port_ssh" ]; then
    echo "trùng với công port ssh của bạn $port_ssh"
    echo "Vui lòng thiết lập lại và chọn cổng port khác"
	 . /etc/wptt/wptt-webadmin-main 1
    exit
fi

echo "Xác nhận port_webgui_openlitpeed la: $port_ols"

if [[ "$port_ols" != "19019" ]]; then
    sed -i "s/19019/$port_ols/g" /usr/local/lsws/admin/conf/admin_config.conf
    firewall-cmd --permanent --zone=public --add-port=$port_ols/tcp
    firewall-cmd --reload
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi
if [[ "$port_ols" = "19019" ]]; then
    firewall-cmd --permanent --zone=public --add-port=19019/tcp
    firewall-cmd --reload
fi

echo "
port_webgui_openlitespeed=$port_ols" >>/etc/wptt/.wptt.conf

echo "              Luu lai thong tin ben duoi de truy cap ve sau              "
echo "-------------------------------------------------------------------------"
echo "1.	WebAdmin console port: $port_ols                	               		  "
echo "2.	truy cap webgui OLS: http://$ip:$port_ols            	        	 "
echo "3.	Ten dang nhap OLS webgui:  $Ten_dang_nhap_ols_webgui                        		   "
echo "4.	Password OLS webgui:  $Password_OLS_webgui                    	        	 "
echo "5.	Moi thong tin tai khoan duoc luu tru:  /etc/wptt/.wptt.conf       	 "
echo "-------------------------------------------------------------------------"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
 . /etc/wptt/wptt-webadmin-main 1
fi

