#!/bin/bash

sed -i -e '/^geoipdb \//,/^}$/d' /usr/local/lsws/conf/httpd_config.conf
echo 'geoipdb /usr/local/lsws/GeoIP/GeoLite2-Country.mmdb {
  geoipDBName             COUNTRY_DB
}
' >>/usr/local/lsws/conf/httpd_config.conf

# rm -f /usr/share/GeoIP/GeoLite2-Country.mmdb
mkdir -p /usr/local/lsws/GeoIP
wget -P /usr/local/lsws/GeoIP https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

#<IfModule mod_rewrite.c>
#RewriteCond %{ENV:GEOIP_COUNTRY_CODE} ^(VN)$
#</ifModule>
