#!/bin/bash

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$cau_hinh_webserver => $chinh_sua Maria Database                       |"
echo "========================================================================="
echo ""
echo ""
echo "$xac_nhan $ban_muon $chinh_sua maria database ? "
prompt="$nhap_lua_chon_cua_ban [1-2]: "
dongy="n"
options=("$dong_y" "$khong_dong_y")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
			break
			;;
		*)
			printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
			break
			;;
	esac
done



if [[ "$dongy" = "y" ]]; then
. /etc/wptt/.wptt.conf
if [[ $editor_cau_hinh = "" ]];then
editor_cau_hinh="nano" 
fi
echo '                                              
                     ::::                     
                    :-::-:                    
        ..      ..::::::::::..      ..        
       :-:-:..:----::::::::---::..:-:-:       
       .:::::--:..          ..:--:::::.       
        .::::.                  :::::.        
        ::::                     .::::        
       ::::       .-=++++=-.       ::::       
      .-::       =*******##*=       ::-.      
  ..::::-.      +********:.+#=      ::::::..  
  ---:::-.     .***=-**- .=***      .-:::---  
  ..::::-.      +**=.  .=****=      ::::::..  
      .-::      .+*#*==*****=       ::-.      
       ::::       :=+***++-.       ::::       
        ::::                      ::::        
        .::::.                  :::::.        
       .:::::--:.            .:--:::::.       
       :-:-:..::--::::..:::---::..:-:-:       
        ..       ..::::::::..       ..        
                    .::::.                    
                     ::::                     
                                              
'
echo "$cong_cu_cau_hinh: $editor_cau_hinh $de $chinh_sua"
if [[ $editor_cau_hinh = "nano" ]];then
    echo "$chinh_sua $xong $nhap ctrl + o $de $luu_lai && ctrl + x $de $exit_thoat"
    echo "$hay_het_suc_can_than_trong_qua_trinh_chinh_sua MariaDB !!"
    sleep 4
fi
sleep 2

check_thay_doi=$(md5sum /etc/my.cnf.d/server.cnf |cut -f1 -d ' ' > /tmp/mariadb_cau_hinh_wptangtoc)
    $editor_cau_hinh /etc/my.cnf.d/server.cnf
	if [[ $(cat /tmp/mariadb_cau_hinh_wptangtoc) != $(md5sum /etc/my.cnf.d/server.cnf |cut -f1 -d ' ')  ]];then
	. /etc/wptt/echo-color
	_runing "$khoi_dong_lai MariaDB $de_cap_nhat_gia_tri $thay_doi"
	systemctl restart mysql
    # /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
	_rundone "$khoi_dong_lai MariaDB $de_cap_nhat_gia_tri $thay_doi"
	fi
else
    . /etc/wptt/wptt-cau-hinh-websever-main 1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-cau-hinh-websever-main 1
fi

