#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Cấu hình webserver => Cấu hình Vhost                                   |"
echo "========================================================================="

. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website bạn muốn sửa lại vhost: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-cau-hinh-websever-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-cau-hinh-websever-main 1
    exit
fi

read -p "Xác nhận bạn muốn cấu hình lại vhost website $NAME (y/n): " dongy
if [[ "$dongy" = "y" ]]; then
. /etc/wptt/.wptt.conf
if [[ $editor_cau_hinh = "" ]];then
editor_cau_hinh="nano" 
fi
echo '                                              
                     ::::                     
                    :-::-:                    
        ..      ..::::::::::..      ..        
       :-:-:..:----::::::::---::..:-:-:       
       .:::::--:..          ..:--:::::.       
        .::::.                  :::::.        
        ::::                     .::::        
       ::::       .-=++++=-.       ::::       
      .-::       =*******##*=       ::-.      
  ..::::-.      +********:.+#=      ::::::..  
  ---:::-.     .***=-**- .=***      .-:::---  
  ..::::-.      +**=.  .=****=      ::::::..  
      .-::      .+*#*==*****=       ::-.      
       ::::       :=+***++-.       ::::       
        ::::                      ::::        
        .::::.                  :::::.        
       .:::::--:.            .:--:::::.       
       :-:-:..::--::::..:::---::..:-:-:       
        ..       ..::::::::..       ..        
                    .::::.                    
                     ::::                     
                                              
'
echo "Sử dụng công cụ editor: $editor_cau_hinh để chỉnh sửa"
if [[ $editor_cau_hinh = "nano" ]];then
    echo "Chỉnh sửa xong ấn ctrl + o để lưu lại và ctrl + x để thoát ra"
    echo "Hãy cẩn thận khi chỉnh sửa lại webserver LiteSpeed !!"
    sleep 4
fi
sleep 2
    $editor_cau_hinh /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
else
    . /etc/wptt/wptt-cau-hinh-websever-main 1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-cau-hinh-websever-main 1
fi

