#!/bin/bash
# @description: Optimize LiteSpeed cho máy chủ chạy nhiều website

# 1. Tạo thư mục Backup cấu hình an toàn
TEMP_OLS_config_DIR=$(mktemp -d /etc/wptt/tmp/XXXXXX)
cp -rf /usr/local/lsws/conf/* "${TEMP_OLS_config_DIR:?}"

# 2. Tính toán tài nguyên (Dùng toán tử $(( )) của Bash nhanh hơn lệnh expr)
cpucore=$(grep -c ^processor /proc/cpuinfo)
core_tien_lsphp_child=$((cpucore * 2))
vhost_dir="/usr/local/lsws/conf/vhosts"

# 3. QUÉT VÀ BƠM CẤU HÌNH VÀO TOÀN BỘ VHOST
# Bỏ qua các file rác như ..conf
find "$vhost_dir" -type f -name "*.conf" ! -name "..conf" -print0 | while IFS= read -r -d $'\0' file; do
    
    # Kỹ thuật Sed Block: Chỉ thao tác bên trong khối extprocessor -> }
    # - Xóa sạch các dòng chứa chữ 'env' cũ
    sed -i '/extprocessor/,/}/ { /env[[:space:]]/d }' "$file"

    # - Chèn 1 khối cấu hình mới tinh vào ngay dưới dòng chữ 'priority'
    sed -i '/extprocessor/,/}/ {
        /priority[[:space:]]/a \
  env                     PHP_LSAPI_CHILDREN='"$core_tien_lsphp_child"'\
  env                     LSAPI_AVOID_FORK=0\
  env                     LSAPI_MAX_IDLE=30\
  env                     LSAPI_MAX_IDLE_CHILDREN=1\
  env                     LSAPI_MAX_PROCESS_TIME=120\
  env                     LSAPI_PGRP_MAX_IDLE=30\
  env                     LSAPI_ACCEPT_NOTIFY=1\
  env                     LSAPI_MAX_CMD_SCRIPT_PATH_LEN=200
    }' "$file"

done

# 4. CHUẨN HÓA QUYỀN SỞ HỮU (PERMISSIONS)
if grep -q "Ubuntu" /etc/*release 2>/dev/null; then
  tuong_thich_nhom_litespeed="nogroup"
else
  tuong_thich_nhom_litespeed="nobody"
fi

chown -R lsadm:"${tuong_thich_nhom_litespeed:?}" "$vhost_dir"
find "$vhost_dir" -type f -print0 | xargs -0 chmod 750

# 5. TEST CÚ PHÁP VÀ ÁP DỤNG (HOẶC KHÔI PHỤC NẾU LỖI)
if /usr/local/lsws/bin/openlitespeed -t >/dev/null 2>&1; then
  rm -rf "${TEMP_OLS_config_DIR:?}"
  echo "$(date '+%d-%m-%Y %H:%M') - OLS Auto-Tuning nhiều website Thành công!" >> /var/log/wptangtoc-ols.log
else
  echo -e "\033[1;31mLỗi cú pháp OLS! Khôi phục về cấu hình cũ...\033[0m"
  # Khôi phục an toàn
  if [[ -n "$TEMP_OLS_config_DIR" ]];then
	  rm -rf /usr/local/lsws/conf/*
	  cp -rf "${TEMP_OLS_config_DIR:?}"/* /usr/local/lsws/conf/

	  chown -R lsadm:"$tuong_thich_nhom_litespeed" /usr/local/lsws/conf
	  chmod -R 750 /usr/local/lsws/conf

	  rm -rf "${TEMP_OLS_config_DIR:?}"
  fi

  echo "$(date '+%d-%m-%Y %H:%M') - OLS Auto-Tuning thất bại, đã restore về cấu hình cũ!" >> /var/log/wptangtoc-ols.log
fi
