#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Ma nguon => Kiem tra dung luong website                        |"
echo "========================================================================="
echo ""
echo ""

. /etc/wptt/tenmien
echo ""
echo ""
echo "Truy cap nhanh vao thu muc ma nguon: "
echo ""
lua_chon_NAME
name="$NAME"
pathttt="/etc/wptt/vhost/.$name.conf"
if [[ ! -f "$pathttt" || "$name" = "0" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    . /etc/wptt/wptt-ma-nguon-main
    exit
fi

echo "Dung luong ma nguon website $name: "
echo ""
kiemtra_dung_luong=$(du -hs /usr/local/lsws/$name/html | cut -c 1-4)
echo "Dung luong ma nguon website $name la ${kiemtra_dung_luong}"
