#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao lưu & khôi phục => Thiết lập tự động sao lưu website               |"
echo "========================================================================="
echo ""
echo ""

if [[ -f $HOME/wptt/$NAME-auto-backup-user ]];then
	echo "website đã được thiết lập tự động sao lưu website trước đó rồi"
	. /etc/wptt-user/wptt-backup-restore-main 1
fi

. /etc/wptt-user/echo-color
. /etc/wptt-user/tenmien
lua_chon_NAME


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt-user/wptt-backup-restore-main 1
fi


. /etc/wptt/vhost/."$NAME".conf

echo -n "Bạn muốn tự động backup website lúc mấy giờ? [0-23]: "
read gio

if [[ ! $gio =~ ^-?[0-9]+$ ]]; then
	echo "Bạn nhập sai dữ liệu thời gian từ 0 đến 23, hệ thống sẽ tự động chọn giá trị là 1h sáng"
	gio="1"
fi

if (( "$gio" > "23" )); then
	echo "Bạn nhập sai dữ liệu thời gian từ 0 đến 23, hệ thống sẽ tự động chọn giá trị là 1h sáng"
	gio="1"
fi

if [[ "$gio" = "" ]]; then
	gio="1"
	echo "Bạn không nhập dữ liệu hệ thống sẽ tự động chọn là 1h sáng"
fi

echo "Bạn muốn tự động backup website vào thứ mấy? "
echo ""
. /etc/wptt-user/wptt-times-tuan
tuan

if [ "$thu" = "0" ] || [ "$thu" = "7" ]; then
	thu12="chủ nhật hàng tuần"
fi
if [ "$thu" = "1" ]; then
	thu12="thứ hai hàng tuần"
fi
if [ "$thu" = "2" ]; then
	thu12="thứ ba hàng tuần"
fi
if [ "$thu" = "3" ]; then
	thu12="thứ tư hàng tuần"
fi
if [ "$thu" = "4" ]; then
	thu12="thứ năm hàng tuần"
fi
if [ "$thu" = "5" ]; then
	thu12="thứ sáu hàng tuần"
fi
if [ "$thu" = "6" ]; then
	thu12="thứ bảy hàng tuần"
fi

if [ "$thu" = "*" ]; then
	thu12="hàng ngày"
fi


echo "Bạn có chắc chắn muốn tự động sao lưu website $NAME lúc $gio giờ $thu12 ?"
prompt="Nhập lựa chọn của bạn [1-2]: "
response="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			response="y"
			break
			;;

		2)
			response="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


if [[ "$response" = "y" ]]; then
	mkdir -p $HOME/wptt

	checkdathietlap=$(grep -rnw "$HOME/.config/rclone/rclone.conf" -e "wptangtoc" >>/dev/null 2>&1 && echo 1)
	if [[ $checkdathietlap ]]; then
		echo "Bạn có muốn uploads file backup tự động lên lưu trữ đám mây Google Driver không?"
		prompt="Nhập lựa chọn của bạn [1-2]: "
		uploads="n"
		options=("Đồng ý" "Không đồng ý")
		PS3="$prompt"
		select opt in "${options[@]}"; do
			case "$REPLY" in
				1)
					uploads="y"
					break
					;;

				2)
					uploads="n"
					break
					;;

				$((${#options[@]} + 1)))
					printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
					break
					;;
				*)
					printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
					break
					;;
			esac
		done


		if [[ "$uploads" = "y" ]]; then

			tuan1="1998"
			echo "Khi đã uploads lên Google Driver bạn có muốn tự động xóa file backup tại local không?"
			prompt="Nhập lựa chọn của bạn [1-2]: "
			delete="n"
			options=("Đồng ý" "Không đồng ý")
			PS3="$prompt"
			select opt in "${options[@]}"; do
				case "$REPLY" in
					1)
						delete="y"
						break
						;;

					2)
						delete="n"
						break
						;;

					$((${#options[@]} + 1)))
						printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
						break
						;;
					*)
						printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
						break
						;;
				esac
			done


			if [[ "$delete" = "y" ]]; then
				tuan2="1998"
			else
				tuan2="12345"
			fi

		fi
	fi

	cat >"$HOME/wptt/$NAME-auto-backup-user" <<END
#!/bin/bash
. /etc/wptt-user/backup-restore/wptt-saoluu $NAME $tuan1 $tuan2
END

chmod 500 $HOME/wptt/$NAME-auto-backup-user
chmod 500 $HOME/wptt

cat <(crontab -l) <(echo "0 $gio * * $thu $HOME/wptt/$NAME-auto-backup-user >/dev/null 2>&1") | crontab -

if $(cat /etc/*release | grep -q "Ubuntu") ; then
	systemctl restart cron.service
else
	systemctl restart crond.service
fi

echo "-------------------------------------------------------------------------"
echo "website $NAME sẽ được tự động sao lưu vào $gio giờ $thu12 .      "
echo "-------------------------------------------------------------------------"
echo "Duong dan luu tru thu muc backup ma nguon va database :$HOME/$NAME/backup-website  "
if [[ "$uploads" = "y" ]]; then
	echo "-------------------------------------------------------------------------"
	echo "File backup trên Google Driver sẽ tự động lưu trữ tại thư mục: wptangtoc_ols_backup/$NAME"
fi
echo "-------------------------------------------------------------------------"
echo "Nếu cần khôi phục lại website thì bạn hãy truy cập vào menu của WPTangToc OLS rồi sử dụng tính năng khôi phục website"
echo "-------------------------------------------------------------------------"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt-user/wptt-backup-restore-main 1
fi

