#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
clear
echo ""
echo ""
echo ""
echo "==================================================================================="
echo "|Sao lưu & khôi phục => Thiết lập Rclone backup lưu trữ đám mây Google Drive   	|"
echo "==================================================================================="
echo ""
echo ""

. /etc/wptt-user/echo-color
if [[ ! -d $HOME/.config ]];then
mkdir -p $HOME/.config
chmod 751 $HOME/.config
fi

check_rclone=$(which rclone)

checkdathietlap=$(grep -rnw "$HOME/.config/rclone/rclone.conf" -e "wptangtoc" >>/dev/null 2>&1 && echo 2)

if [[ $checkdathietlap ]]; then
	clear
	echo "Bạn đã cấu hình rclone trước đó rồi"
	. /etc/wptt-user/wptt-backup-restore-main 1
	exit
fi

echo "Copy https://bit.ly/3zIr4K4 sau đó paste vào trình duyệt để đã đăng nhập tài khoản google để lấy id:"
read -p "Nhập mã id của bạn [0=Thoat]: " checkid

if [[ "$checkid" = "0" ]]; then
. /etc/wptt-user/wptt-backup-restore-main 1
	clear
	exit
fi

if [[ "$checkid" = "" ]]; then
. /etc/wptt-user/wptt-backup-restore-main 1
	clear
	exit
fi

_runing "Thiết lập Google Driver"

thietlap=$(expect -c "
spawn /usr/sbin/rclone config
expect \"n\"
send \"n\r\"
expect \"name\"
send \"wptangtoc\r\"
expect \"Storage\"
send \"drive\r\"
expect \"client_id\"
send \"\r\"
expect \"client_secret\"
send \"\r\"
expect \"scope\"
send \"1\r\"
expect \"root_folder_id\"
send \"\r\"
expect \"service_account_file\"
send \"\r\"
expect \"n\"
send \"n\r\"
expect \"n\"
send \"n\r\"
expect \"verification\"
send \"$checkid\r\"
expect \"n\"
send \"n\r\"
expect \"n\"
send \"y\r\"
expect eof
")

checkdathietlapxacthuc=$(grep -rnw "$HOME/.config/rclone/rclone.conf" -e "wptangtoc" >>/dev/null 2>&1 && echo 2)
if [[ $checkdathietlapxacthuc ]]; then
	_rundone "Thiết lập Google Driver"
else
	_runloi "Thiết lập Google Driver"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-backup-restore-main 1
fi

