#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao lưu & khôi phục => Thiết lạp tự động xóa file sao luu website Google Driver      |"
echo "========================================================================="
checkactivate=$(grep -rnw "$HOME/.config/rclone/rclone.conf" -e "wptangtoc" >>/dev/null 2>&1 && echo 2)
if [[ "$checkactivate" = "2" ]]; then
    google=4
else
    echo "Bạn chưa kích hoạt rclone Google Driver"
	sleep 3
    . /etc/wptt-user/wptt-backup-restore-main 1
    exit
fi
. /etc/wptt-user/tenmien
lua_chon_NAME


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt-user/wptt-wordpress-main 1
fi


if [ -f /etc/cron.d/delete-google-driver-$NAME.cron ]; then
	echo "$NAME đã được kích hoạt tự động backup hết hạn trước đó rồi!"
	sleep 3
	. /etc/wptt-user/wptt-backup-restore-main 1
	exit
fi

. /etc/wptt-user/echo-color
read -p "Nhập số ngày của bạn muốn đặt hạn sử dụng cho file backup trên Google Drive
Ví dụ: 10 hay 60 sử dụng số nguyên dương: " ngay

if [[ ! $ngay =~ ^-?[0-9]+$ ]]; then
	clear
	echoDo "Nhập số ngày không đúng định dạng"
	sleep 4
	. /etc/wptt-user/wptt-backup-restore-main 1
	exit
fi

_runing "Thiết lập xóa file backup trên Google Driver hết hạn"
cat >"/etc/wptt-auto/$NAME-delete-backup-google-driver" <<END
#!/bin/bash
. /etc/wptt-user/backup-restore/wptt-auto-delete-google-driver-backup $NAME $ngay
END

chmod 740 /etc/wptt-auto/$NAME-delete-backup-google-driver

cat >"/etc/cron.d/delete-google-driver-$NAME.cron" <<END
0 3 * * * root /etc/wptt-auto/$NAME-delete-backup-google-driver >/dev/null 2>&1
END


if $(cat /etc/*release | grep -q "Ubuntu") ; then
	NAME_CRON_ubuntu=${NAME//[.]/_}
	ln -sf /etc/cron.d/delete-google-driver-$NAME.cron /etc/cron.d/delete-google-driver-${NAME_CRON_ubuntu}_cron
	systemctl restart cron.service
else
	systemctl restart crond.service
fi


_rundone "Thiết lập xóa file backup trên Google Driver hết hạn"
echo "========================================================================="
echo "Hoàn tất kích hoạt tự động xóa file backup hết hạn Google Driver"
echo "========================================================================="
echo "Vào lúc 3 giờ sáng hàng ngày"
echo "Hệ thống sẽ tự động xóa các file backup trong thư mục backup google driver: wptangtoc_ols_backup/$NAME file nào đã được tạo trước ngày $ngay ngày sẽ tự động xóa đi"
echo "========================================================================="


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-backup-restore-main 1
fi

