#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao lưu & khôi phục => Tải file backup từ Lưu trữ đám mây              |"
echo "========================================================================="
echo ""
echo ""

checkactivate=$(grep -rnw "$HOME/.config/rclone/rclone.conf" -e "wptangtoc" >>/dev/null 2>&1 && echo 2)
if [[ "$checkactivate" = "2" ]]; then
    google=4
else
    echo "Hệ thống của bạn chưa kích hoạt rclone lưu trữ đám mây"
    . /etc/wptt-user/wptt-backup-restore-main 1
    exit
fi

if [[ $(cat ~/.config/rclone/rclone.conf | grep 'onedrive') ]];then
		cloud_service='OneDrive'
else
		cloud_service='Google Drive'
fi

echo "========================================================================="
. /etc/wptt-user/tenmien
lua_chon_NAME


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt-user/wptt-backup-restore-main 1
fi


. /etc/wptt-user/echo-color
selects=()

if [[ "$google" = "4" ]]; then
	_runing "Đang tiến hành tải danh sách từ $cloud_service"
	x=$(rclone lsf wptangtoc:wptangtoc_ols_backup/"$NAME")
	while IFS= read -r line; do selects+=("$line"); done <<<"$x"
		if [[ $selects = '' ]];then
			_runloi "Tiến hành tải danh sách từ $cloud_service ..."
			echoDo "Không có file backup nào tồn tại."
			sleep 3
			. /etc/wptt-user/wptt-backup-restore-main 1
		fi
		_rundone "Tiến hành tải danh sách từ $cloud_service"
		echo '========================================================================='
	echo ''
	echo "Danh sách các file backup của website $NAME lưu trữ trên Google Driver"
fi
PS3="
-//- Nhập lựa chọn của bạn (1-${#selects[@]}) [0=Thoát]: "
select select in ${selects[@]}; do
    file=$select
    break
done

if [[ "$file" = "" || "$file" = '0' ]]; then
	. /etc/wptt-user/wptt-backup-restore-main 1
fi

if [[ "${file}" ]]; then

echo "Xác nhận để download File $file "
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy_taifile="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy_taifile="y"
			break
			;;

		2)
			dongy_taifile="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


    if [[ "$dongy_taifile" = 'y' ]]; then
		    echo '                
              :=*###***###*+-                 
           .+#*=:.       .:=*#*:              
          *%+.                -#%:            
        ..:                     -@+           
       -@:                       .@*:.        
      .@+                         .*****+:    
      +@                               .=#%-  
   :=*%*                                  :@* 
 :##=:                                      @+
-@=                                         =@
@*                                          =@
@=                                          %#
*@                                        .#% 
 *%=                                      *+  
  :*#*+++============================+*#+     
     .:::--@*---*@----@%---=@+---#@--:.       
     -+=:  @=    -    #*    @:   +@  :++-     
    +@-=@**#.   :+    %#   .@-   :%*#@--@=    
    .***+. ..   -@    =-    @:  ..  .+***.    
          *#+#+:*@    ::    @+:*#+#+          
          @#-%%==.   :@@:   :++%#-%%          
           -=-      =@:-@-      -=-           
                    :%**#.                    
'

_runing "Tải $file từ $cloud_service"
        rm -f /usr/local/lsws/"$NAME"/backup-website/"$file"
        rclone copy wptangtoc:wptangtoc_ols_backup/"$NAME"/"$file" /usr/local/lsws/"$NAME"/backup-website
_rundone "Tải $file từ $cloud_service"
    fi
fi
echo ""
tuancheck=$(echo "$file" | grep -c ".zip")

tuancheck2=$(echo "$file" | grep -c ".sql")

if [[ "$tuancheck" = "1" ]]; then
    echo "Bạn đã tải file ma nguon .zip roi ban co muon tai them file database .sql nữa không?"
    ggdrthem="file sql database"

fi

if [[ "$tuancheck2" = "1" ]]; then
    echo "Bạn đã tải file database .sql rồi bạn có muốn tải thêm file mã nguồn nguồn .zip nữa không?"
    ggdrthem="file zip mã nguồn"

fi

echo "Bạn có muốn tiếp tục tải thêm $ggdrthem nữa không? "
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy_taitiep="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy_taitiep="y"
			break
			;;

		2)
			dongy_taitiep="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


if [[ "$dongy_taitiep" = 'y' ]]; then
    selects=()

    if [[ "$google" = "4" ]]; then
    echo '                
              :=*###***###*+-                 
           .+#*=:.       .:=*#*:              
          *%+.                -#%:            
        ..:                     -@+           
       -@:                       .@*:.        
      .@+                         .*****+:    
      +@                               .=#%-  
   :=*%*                                  :@* 
 :##=:                                      @+
-@=                                         =@
@*                                          =@
@=                                          %#
*@                                        .#% 
 *%=                                      *+  
  :*#*+++============================+*#+     
     .:::--@*---*@----@%---=@+---#@--:.       
     -+=:  @=    -    #*    @:   +@  :++-     
    +@-=@**#.   :+    %#   .@-   :%*#@--@=    
    .***+. ..   -@    =-    @:  ..  .+***.    
          *#+#+:*@    ::    @+:*#+#+          
          @#-%%==.   :@@:   :++%#-%%          
           -=-      =@:-@-      -=-           
                    :%**#.                    
'

_runing "Tải danh sách từ $cloud_service"
x=$(rclone lsf wptangtoc:wptangtoc_ols_backup/$NAME)
while IFS= read -r line; do selects+=("$line"); done <<<"$x"
	if [[ $selects = '' ]];then
		_runloi "Tải danh sách từ $cloud_service"
		echoDo "Không có file backup nào tồn tại."
		sleep 3
		. /etc/wptt-user/wptt-backup-restore-main 1
	fi
	_rundone "Tải danh sách từ $cloud_service"
	echo '========================================================================='
	echo ''
	echo "Danh sách các file backup của website $NAME lưu trữ trên $cloud_service"

    fi
    PS3="
-//- Nhập lựa chọn của bạn (1-${#selects[@]}) [0=Thoát]: "
    select select in ${selects[@]}; do
        file2=$select
        break
    done


	if [[ "$file2" = "" || "$file2" = '0' ]]; then
		. /etc/wptt-user/wptt-backup-restore-main 1
	fi


    if [[ "${file2}" ]]; then

        echo "Xác nhận để download File $file2 "
		prompt="Nhập lựa chọn của bạn [1-2]: "
		dongy_taifile2="n"
		options=("Đồng ý" "Không đồng ý")
		PS3="$prompt"
		select opt in "${options[@]}"; do
			case "$REPLY" in
				1)
					dongy_taifile2="y"
					break
					;;

				2)
					dongy_taifile2="n"
					break
					;;

				$((${#options[@]} + 1)))
					printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
					break
					;;
				*)
					printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
					break
					;;
			esac
		done


        if [[ "$dongy_taifile2" = 'y' ]]; then
			_runing "Tải $file2 từ $cloud_service"
            rm -f /usr/local/lsws/"$NAME"/backup-website/"$file2"
            rclone copy wptangtoc:wptangtoc_ols_backup/"$NAME"/"$file2" /usr/local/lsws/"$NAME"/backup-website
			_rundone "Tải $file2 từ $cloud_service"
        fi
    fi
fi

if [[ "$dongy_taifile" = 'y' && -f /usr/local/lsws/"$NAME"/backup-website/$file ]]; then
RED='\033[1;32m'
NC='\033[0m'
echo -e "${RED}                                              
               ........               
          .......    .....            
       .:..                   .:::.   
     .:.                    .:::::::. 
    ::                    .:::::::::. 
   :.                   .::::::::::.  
  :.                  .::::::::::.    
 .:      ..:.       .::::::::::.      
 :.    .:::::::.  .::::::::::.     .: 
 :.    .:::::::::::::::::::.       .: 
 :.     .::::::::::::::::.         .: 
 .:       .::::::::::::.           :. 
  :.        .::::::::.            .:  
   :.         .::::.             .:   
    ::                          ::    
     .:.                      .:.     
       .::.                .::.       
          .......    .......          
               ........               

${NC}"
    echo "Qua trinh tai hoan tat - Thu muc luu tru tai: /usr/local/lsws/"$NAME"/backup-website/$file"
else
    echo "Qua trinh download file Backup từ $cloud_service đã xảy ra lỗi"
vang='\033[1;33m'
NC='\033[0m'
echo -e "${vang}                                              
                   .:::....                   
                 .--=+++=-::.                 
                :--*%%%%%%+::.                
               :--*%%%%%%%%*:::               
              ---#%%%%%#%%%%*:::              
            .--=#%%%#=--=#%%%#-::             
           .--=%%%%%*:-:.*%%%%#-::.           
          .--+%%%%%%*---:*%%%%%#=::.          
         :--*%%%%%%%*--::*%%%%%%#+::.         
        :--*%%%%%%%%*--::*%%%%%%%#+:::        
       ---#%%%%%%%%%*--::*%%%%%%%%#*:::       
      --=#%%%%%%%%%%*---:*%%%%%%%%%#*-::      
    .--=%%%%%%%%%%%%#--::#%%%%%%%%%%##-::     
   .--+%%%%%%%%%%%%%%#*+#%%%%%%%%%%%%##=::.   
  :--+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##=::.  
 :--*%%%%%%%%%%%%%%%#=-:-#%%%%%%%%%%%%%##+::. 
:--*%%%%%%%%%%%%%%%%#--::#%%%%%%%%%%%%%%##+::.
--=%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%###-::
:--*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##+::.
 :--=++***************++++++++++++++++++=-::. 
   .:::::::::::::::::::....................  
${NC}"
fi

if [[ "$dongy_taitiep" = "y" ]]; then
    if [[ "$dongy_taifile2" = 'y' && -f /usr/local/lsws/"$NAME"/backup-website/$file2 ]]; then
        echo "Quá trình tải hoàn tất - thư mục lưu trữ tại: /usr/local/lsws/"$NAME"/backup-website/$file2"
    else
        echo "Quá trình download file backup từ $cloud_service đã xảy ra lỗi"
vang='\033[1;33m'
NC='\033[0m'
echo -e "${vang}                                              
                   .:::....                   
                 .--=+++=-::.                 
                :--*%%%%%%+::.                
               :--*%%%%%%%%*:::               
              ---#%%%%%#%%%%*:::              
            .--=#%%%#=--=#%%%#-::             
           .--=%%%%%*:-:.*%%%%#-::.           
          .--+%%%%%%*---:*%%%%%#=::.          
         :--*%%%%%%%*--::*%%%%%%#+::.         
        :--*%%%%%%%%*--::*%%%%%%%#+:::        
       ---#%%%%%%%%%*--::*%%%%%%%%#*:::       
      --=#%%%%%%%%%%*---:*%%%%%%%%%#*-::      
    .--=%%%%%%%%%%%%#--::#%%%%%%%%%%##-::     
   .--+%%%%%%%%%%%%%%#*+#%%%%%%%%%%%%##=::.   
  :--+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##=::.  
 :--*%%%%%%%%%%%%%%%#=-:-#%%%%%%%%%%%%%##+::. 
:--*%%%%%%%%%%%%%%%%#--::#%%%%%%%%%%%%%%##+::.
--=%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%###-::
:--*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##+::.
 :--=++***************++++++++++++++++++=-::. 
   .:::::::::::::::::::....................  
${NC}"
    fi
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-backup-restore-main 1
fi

