#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
	clear
version_wptangtoc_ols=$(cat /tmp/wptangtoc-ols-version-main)
	RED='\033[0;31m'
	NC='\033[0m'
	echo -e "${RED}+-----------------------------------------------------------------------+"
	echo "|                                                                       |"
	echo "|                       WPTANGTOC OLS phiên bản: $version_wptangtoc_ols			|"
	echo "|                          Phát triển bởi: Gia Tuấn			|"
	if [[ $wptangtoc_ols_giatuan = "1" ]]; then
		echo "|                          WPTangToc OLS Premium                        |"
	fi
	if [[ $beta_wptangtoc_ols = "1" ]]; then
		echo "|                          WPTangToc OLS beta                           |"
	fi
	echo -e "+-----------------------------------------------------------------------+ ${NC}"
	echo ""
	echo ""
else
	echo ""
	. /etc/wptt-user/echo-color
	echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
	echo ""
	echo ""
	echo "WPTangToc OLS MENU chính:"
	echo ""
fi

options=(
	"Quản lý WordPress"               #1
	"Quản lý Database"                #2
	"Sao lưu & Khôi phục"             #3
	"Tải mã nguồn WordPress"          #4
	"Quản lý SSH/SFTP"                #6
	"Preload Cache"         #7
	"Quản lý logs"                    #8
	"Quản lý mã nguồn"                #9
	"Quản lý Cache"          #19
	"Gửi yêu cầu => Gia Tuấn"         #25
	"Tặng tác giả cốc bia"     #30
	"Kiểm tra tài nguyên"
	"Quản lý filemanager"
)
PS3="
Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"; do
	case $opt in
		"${options[0]}")
			"/etc/wptt-user/wptt-wordpress-main"
			;;

		"${options[1]}")
			"/etc/wptt-user/wptt-db-main"
			;;

		"${options[2]}")
			"/etc/wptt-user/wptt-backup-restore-main"
			;;

		"${options[3]}")
			"/etc/wptt-user/wptt-install-wordpress2" 99
			;;

		"${options[4]}")
			"/etc/wptt-user/wptt-ssh-main"
			;;

		"${options[5]}")
			"/etc/wptt-user/wptt-preload-cache2" 98
			;;

		"${options[6]}")
			"/etc/wptt-user/wptt-menu-logs"
			;;

		"${options[7]}")
			"/etc/wptt-user/wptt-ma-nguon-main"
			;;

		"${options[8]}")
			"/etc/wptt-user/wptt-cache-main"
			;;

		"${options[9]}")
			"/etc/wptt-user/wptt-feedback" 98
			;;

		"${options[10]}")
			"/etc/wptt-user/wptt-donate" 98
			;;

		"${options[11]}")
			"/etc/wptt-user/wptt-tai-nguyen-main" 98
			;;

		*) . /etc/wptt-user/wptt-status && ps -ef | grep 'bash' | grep '/etc/wptt\|/bin/wptangtoc-user' | grep -v grep | grep -v 'preload'| grep -v 'status' | awk '{print $2}' | xargs kill -9 >/dev/null 2>&1| echo 'Hoàn tất thoát menu WPTangToc OLS' | tr -s '\n' ' ' ;;

	esac
done
