#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt-user/wptt-header-menu
header_menu
else
	. /etc/wptt-user/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Quản lý sao lưu && Khôi phục:"
echo ""
options=(
	"Sao lưu website"                                          #1
	"Khôi phục website"                                        #2
	"Sao lưu database"                                         #3
	"Khôi phục database"                                       #4
	"Xóa file backup"                                          #5
	"Thiết lập tự động sao lưu website" #6
	"Xóa thiết lập tự động sao lưu website" #7
	"Thiết lập Backup lưu trữ Google Drive" #8
	"Xóa thiết lập Backup lưu trữ Google Drive" #9
	"Download tải file backup trên Google Drive" #10
	"Xóa file backup trên Google Drive" #11
)
PS3="
Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"; do
	case $opt in

		"${options[0]}")
			"/etc/wptt-user/backup-restore/wptt-saoluu" 98
			;;
		"${options[1]}")
			"/etc/wptt-user/backup-restore/wptt-khoiphuc" 98
			;;
		"${options[2]}")
			"/etc/wptt-user/db/wptt-saoluu-database" 97
			;;
		"${options[3]}")
			"/etc/wptt-user/db/wptt-nhapdatabase" 97
			;;

		"${options[4]}")
			"/etc/wptt-user/backup-restore/wptt-xoa-file-backup" 98
			;;

		"${options[5]}")
			"/etc/wptt-user/backup-restore/wptt-auto-backup" 98
			;;

		"${options[6]}")
			"/etc/wptt-user/backup-restore/wptt-tat-auto-backup" 98
			;;

		"${options[7]}")
			"/etc/wptt-user/backup-restore/wptt-rclone" 98
			;;

		"${options[8]}")
			"/etc/wptt-user/backup-restore/wptt-huy-rclone" 98
			;;

		"${options[9]}")
			"/etc/wptt-user/backup-restore/wptt-download-rclone" 98
			;;

		"${options[10]}")
			"/etc/wptt-user/backup-restore/wptt-xoa-file-backup-google-driver" 98
			;;

		*) wptangtoc-user 1 ;;
	esac
done
