#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt-user/wptt-header-menu
header_menu
else
	. /etc/wptt-user/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Quản lý logs:"
echo ""
options=(
    "Xem access log domain"                      #5
    "Xem access log domain có truy vấn"          #6
	"Xem eror logs domain"
	"Xóa Log"                                    #10
	"Xem tiến trình hoạt động"                   #11
)

PS3="
Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[5]}")
        "/etc/wptt-user/logs/wptt-xem-access-log-domain" 98
        ;;

    "${options[6]}")
        "/etc/wptt-user/logs/wptt-xem-access-log-domain-truy-van" 98
        ;;

    "${options[7]}")
        "/etc/wptt-user/logs/wptt-xem-error-log-domain" 98
        ;;

    "${options[10]}")
        "/etc/wptt-user/logs/wptt-xoa-logs" 98
        ;;

    "${options[11]}")
        "/etc/wptt-user/logs/wptt-xem-tien-trinh" 98
        ;;
        
    *) wptangtoc-user 1 ;;
    esac
done
