#!/bin/bash
. /etc/wptt/wptt-header-menu
header_menu
echo ""
echo ""
echo "Quan ly WordPress:"
echo ""
options=(
  "Cap nhat wordpress core"                              #3
  "Cap nhat plugins"                                     #4
  "Cap nhat themes"                                      #5
  "Cai lai reinstall wordpress core"                     #6
  "Cai lai reinstall wordpress (core + plugin + themes)" #7
  "Cap nhat wordpress all vps (core + plugin + themes)"  #8
  "Tai plugin LiteSpeed Cache"                           #10
  "Tat sua code truc tiep tren wp-admin wordpress"       #11
  "Xoa binh luan spam"                                   #12
  "Truy van va thay the co so du lieu"                   #13
  "Bat che do bao tri"                                   #14
  "Tat che do bao tri"                                   #15
  "Toi uu hoa hinh anh"                                  #16
  "Kich hoat LScache"                                    #17
  "Huy kich hoat LScache"                                #18
  "Unix stocket config database"                         #19
  "Toi uu hoa wp-cron"                                   #20
  "Tat toi uu hoa wp-cron"                               #21
  "Tang muc gioi han ram wordpress"                      #22
  "Thay doi salt cookie dang nhap"                       #23
  "Tat wp debug wordpress"                               #24
  "Bat wp debug wordpress"                               #25
  "Toi uu heartbeat api"                                 #26
  "Tat XML RPC wordpress"                                #27
  "Doi PassWord wp-admin wordpress"                      #28
  "login wp-admin magic link"                            #29
  "Xoa transient database"                               #30
  "Thay doi tien to database"                            #31
  "Toi uu ALL database"                                  #32
  "Rewrite permalink"                                    #33
  "Reset lai ve wordpress moi hoan toan"                 #34
  "Tai tao lai Thumbnail"                                #35
  "Clear cache && Preload WP Rocket"                     #36
  "Kham Suc khoe wordpress"                              #37
  "Kiem tra autoload"                                    #38
  "Cap nhat Url home va siteurl"                         #39
  "Kiem tra phien ban wordpess"                          #40
  "Kiem tra bao mat ma nguon decode base64"              #41
  "Sua chua database ALL"                                #42
  "Kiem tra toc do hook" 								 #43
  "Bat chinh sua code truc tiep WP-admin"  				 #44
  "Nhap du lieu Toi uu Plugin LiteSpeed Cache"  		#45
  "Thiet Lap WordPress Multisite"  						#46
)

PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
  case $opt in
  "${options[2]}")
    "/etc/wptt/wordpress/update-core"
    ;;
  "${options[3]}")
    "/etc/wptt/wordpress/update-plugin"
    ;;
  "${options[4]}")
    "/etc/wptt/wordpress/update-theme"
    ;;
  "${options[5]}")
    "/etc/wptt/wordpress/ghi-de-wordpress-core"
    ;;
  "${options[6]}")
    "/etc/wptt/wordpress/wptt-update-reinstall-wordpres"
    ;;
  "${options[7]}")
    "/etc/wptt/wordpress/update-full"
    ;;

  "${options[8]}")
    "/etc/wptt/wordpress/wptt-xoacache"
    ;;

  "${options[10]}")
    "/etc/wptt/wordpress/tai-plugin-litespeed-cache"
    ;;

  "${options[11]}")
    "/etc/wptt/wordpress/tat-chinh-sua-truc-tiep-admin-wordpress"
    ;;

  "${options[12]}")
    "/etc/wptt/wordpress/xoa-binh-luan-spam"
    ;;

  "${options[13]}")
    "/etc/wptt/wordpress/query-truyvan"
    ;;

  "${options[14]}")
    "/etc/wptt/wordpress/bat-baotri"
    ;;
  "${options[15]}")
    "/etc/wptt/wordpress/tat-baotri"
    ;;

  "${options[16]}")
    "/etc/wptt/wordpress/image"
    ;;

  "${options[17]}")
    "/etc/wptt/wordpress/lscache"
    ;;

  "${options[18]}")
    "/etc/wptt/wordpress/huy-lscache"
    ;;

  "${options[19]}")
    "/etc/wptt/wordpress/unix-stocket-wpconfig"
    ;;

  "${options[20]}")
    "/etc/wptt/wordpress/wp-cron-job"
    ;;

  "${options[21]}")
    "/etc/wptt/wordpress/tat-wp-cron-job"
    ;;

  "${options[22]}")
    "/etc/wptt/wordpress/tang-gioi-han-ram-wordpress"
    ;;

  "${options[23]}")
    "/etc/wptt/wordpress/thay-salt"
    ;;

  "${options[24]}")
    "/etc/wptt/wordpress/wp-debug"
    ;;

  "${options[25]}")
    "/etc/wptt/wordpress/bat-wp-debug"
    ;;

  "${options[26]}")
    "/etc/wptt/wordpress/plugin-heartbeat-wptangtoc"
    ;;

  "${options[27]}")
    "/etc/wptt/wordpress/plugin-xml-rpc-wptangtoc"
    ;;

    "${options[28]}")
    "/etc/wptt/wordpress/passwd-wp"
    ;;

    "${options[29]}")
    "/etc/wptt/wordpress/login-wpadmin-magic"
    ;;

  "${options[30]}")
    "/etc/wptt/wordpress/transient"
    ;;
  "${options[31]}")
    "/etc/wptt/wordpress/thay-doi-tien-to"
    ;;
  "${options[32]}")
    "/etc/wptt/wordpress/all-database"
    ;;
  "${options[33]}")
    "/etc/wptt/wordpress/rewrite"
    ;;
  "${options[34]}")
    "/etc/wptt/wordpress/wptt-wipe-wordpress"
    ;;
  "${options[35]}")
    "/etc/wptt/wordpress/wptt-render-thumbnail"
    ;;

  "${options[36]}")
    "/etc/wptt/wordpress/wptt-rocket"
    ;;

  "${options[37]}")
    "/etc/wptt/wordpress/kham-suc-khoe-wordpress"
    ;;

  "${options[38]}")
    "/etc/wptt/wordpress/check-autoload"
    ;;

  "${options[39]}")
    "/etc/wptt/wordpress/thay-url-option"
    ;;

  "${options[40]}")
    "/etc/wptt/wordpress/kiem-tra-version-wp"
    ;;

  "${options[41]}")
    "/etc/wptt/wordpress/check-decode-base64"
    ;;


  "${options[42]}")
    "/etc/wptt/wordpress/check-hook-speed"
    ;;

  "${options[43]}")
    "/etc/wptt/wordpress/bat-chinh-sua-truc-tiep-admin-wordpress"
    ;;
    
  "${options[44]}")
    "/etc/wptt/wordpress/nhap-du-lieu-litespeed-wptangtoc"
    ;;

  "${options[45]}")
    "/etc/wptt/wordpress/wordpress-multisite"
    ;;

  *) wptangtoc ;;
  esac
done
