#!/bin/bash
if [[ $1 = "" ]]; then
  . /etc/wptt-user/wptt-header-menu
  header_menu
else
  . /etc/wptt-user/echo-color
  echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi

echo ""
echo ""
echo "Quản lý mã nguồn:"
echo ""
options=(
  "Kiểm tra dung lượng mã nguồn website" #2
  "Xóa mã nguồn website"                 #4
)
PS3="
Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"; do
  case $opt in
  "${options[0]}")
    exec "/etc/wptt-user/ma-nguon/wptt-kiem-tra-dung-luong"
    ;;

  "${options[1]}")
    exec "/etc/wptt-user/ma-nguon/wptt-xoa-ma-nguon" 98
    ;;

  *) exec /etc/wptt-user/wptangtoc-user 1 ;;
  esac
done
