#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
function tuan() {
prompt="Nhap vao lua chon cua ban [1-7]: "
thu="1"
options=("Thu hai" "Thu ba" "Thu tu" "Thu nam" "thu sau" "thu bay" "chu nhat" "hang ngay")
PS3="$prompt"
select opt in "${options[@]}"; do

  case "$REPLY" in
  1)
    thu="1"
    break
    ;;
  2)
    thu="2"
    break
    ;;
     3)
    thu="3"
    break
    ;;
      4)
    thu="4"
    break
    ;;
      5)
    thu="5"
    break
    ;;
      6)
    thu="6"
    break
    ;;
      7)
    thu="0"
    break
    ;;

    8)
    thu="*"
    break
    ;;

  $((${#options[@]} + 1)))
    printf "\nHe thong chon thu hai\n"
    break
    ;;
  *)
    printf "Ban nhap sai, he thong chon thu hai\n"
    break
    ;;
  esac

done
}
