#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2024
clear
echo "feedback WPTangTocOLS : $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

echo -e "+-----------------------------------------------------------------------+"
echo "|                                                                       |"
echo "|                        Gửi yêu cầu đến Gia Tuấn		        |"
echo "|                                                                       |"
echo -e "+-----------------------------------------------------------------------+"
echo "                                        .                     
                                        .:---==--=:                 
                                      ::::::::::::--:.              
                                   ::::.........::::::-:            
                                 :==:..............::::::           
                                ::::..    ...........::::.          
                               :..::....   .....:.....:-.-.         
                               . .--:-:.............::.::.:         
                                :==++=-:-....:.......:::::.         
                               :=+++*++=--::... .....:::.-          
                              :++*******==-:.....:. ... ..          
                              ===+*###*****+-:==-=++-:.:.           
                              ==-:-=***#*******####%#+==            
                             .+---.:-++++==-==+*#####+=*=.          
                             =***+++=+**+==-:-=+*##%#+*#*.          
                             *#####**####**++++**##%#*+#:           
                             *******###############%###-            
                             ++==+*#%%%%#*##%%%%%#%#*+.             
                             :+=++=+***##*+*#####%#.                
                              -+--++++**##*+**####.                 
           .:-----::::.::::..:-=+==++**++=++**##*                   
        .-=++=========-------=:-*+===++********#.                   
       -=-=----------==-----:-::+******##*****##.                   
     .-------==-------===-:---::=+++*********##%-                   
   .-------==---------------:---====++++*****###=:.                 
  :--------------------------:-=+++++++*******+====                 
.---------------==---=------:..-*#******+++==-----==.               
------------------------------::-+*##**+==----=====-=-.             
------:------------------------:::-==--:.:+========--=+-            
-----::-----------------------::-+::::::..:===--=====:=+=-.         
----::---------------------------=--------:----======-:=+++=-:.  "

read -p "Xác nhận bạn muốn gửi yêu cầu đến cho mình? (y/n): " dongy
if [[ "$dongy" != "y" ]]; then
  wptangtoc-user 1
  exit
fi

read -p "Nhập nội dung gửi đến mình: " noidung

telegram_api_giatuan=$(curl -s https://wptangtoc.com/share/feedback.txt | grep "api" | cut -f2 -d "=")
telegram_id_giatuan=$(curl -s https://wptangtoc.com/share/feedback.txt | grep "id" | cut -f2 -d "=")

client_ip=$(echo $SSH_CLIENT | awk '{ print $1}')
vps_ip=$(curl -s ipv4.icanhazip.com)
if [[ "$vps_ip" = "" ]]; then
  vps_ip=$(curl -s checkip.amazonaws.com)
fi
date="$(date "+%d-%m-%Y %H:%M")"
info_ip=https://ipinfo.io/${client_ip}
text="
Thông tin yêu cầu WPTangToc OLS
-------------------------------------
Nội dung: $noidung
-------------------------------------
IP Máy trạm: *${client_ip}* - [Thông tin chi tiết](${info_ip})
IP webserver: ${vps_ip}
Thời điểm: ${date}
Số điện thoại: ${sodienthoai}
Website: $(
  for entry in $(ls -A /etc/wptt/vhost | grep -v '^\.\.conf$' | sort -uV); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
      echo "$domain ,"
    fi
  done
)
-------------------------------------
WPTangToc OLS phiên bản : $version_wptangtoc_ols
Phát triển bởi [Gia Tuấn](https://wptangtoc.com/gia-tuan)
"
url_tele="https://worker-soft-shape-e788.hoangtuan0137.workers.dev/bot${telegram_api_giatuan}/sendMessage"
curl -s -d "chat_id=$telegram_id_giatuan&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url_tele >/dev/null
clear
echo "Nội dung tin nhắn đã gửi đến Gia Tuấn (Tác giả phần mềm WPTangToc OLS)"
echo "Cảm ơn bạn đã gửi yêu cầu đến với mình"

if [[ "$telegram_api" != "" || "$telegram_id" != "" ]]; then

  text="
Cảm ơn bạn đã gửi yêu cầu cho Gia Tuấn
-------------------------------------
Nội dung của bạn: ${noidung}
Thời điểm: ${date}
-------------------------------------
Các thông tin cá nhân của mình.
Số điện thoại: 0866880462
Zalo: 0866880462
Telegram: t.me/wptangtoc
website: wptangtoc.com
FaceBook: fb.com/wptangtoc
Email: giatuan@wptangtoc.com
STK Ngân Hàng: 2222223338888 (Hoàng Gia Tuấn) - MB Bank, CN Hải Phòng
-------------------------------------
WPTangToc OLS phiên bản : $version_wptangtoc_ols
Phát triển bởi [Gia Tuấn](https://wptangtoc.com/gia-tuan)
"
  url_tele="https://worker-soft-shape-e788.hoangtuan0137.workers.dev/bot${telegram_api}/sendMessage"
  curl -s -d "chat_id=$telegram_id&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url_tele >/dev/null

fi
sleep 2

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  wptangtoc 1
fi
