#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => tang muc gioi han ram WordPress                   |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website ban muon tang muc gioi han ram WordPress: "
echo ""
lua_chon_NAME

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-menu-wordpress
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt/wptt-menu-wordpress
  exit
fi


wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
sed -i "/WP_MEMORY_LIMIT/d" "$wp_config"
sed -i "/<?php/a define( 'WP_MEMORY_LIMIT', '128M' );" "$wp_config"
echo "Da tang ram WordPress thanh cong cho website $NAME"
