#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Mã nguồn => Xóa mã nguồn website                               |"
echo "========================================================================="
. /etc/wptt-user/tenmien
lua_chon_NAME
name="$NAME"

echo "Xoá mã nguồn website $NAME : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

. /etc/wptt-user/echo-color
echo "Xác nhận bạn muốn xóa mã nguồn website ${NAME}"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ "$dongy" = "y" ]]; then
	_runing "Xóa mã nguồn website $NAME"
    rm -rf /usr/local/lsws/"$NAME"/html/*
	_rundone "Xóa mã nguồn website $NAME"
else
    . /etc/wptt-user/wptt-ma-nguon-main 1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-ma-nguon-main 1
fi

