#!/bin/bash

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/echo-color

if [[ $(which vnstat 2>/dev/null) ]];then
vnstat_check='on'
else
vnstat_check='off'
fi

if [[ $vnstat_check = 'off' ]];then
echo -e "$xac_nhan $cai tool $quan_ly_bang_thong ?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done


	if [[ "$dongy" = 'y' ]]; then
	_runing "$cai $quan_ly_bang_thong"
dnf install vnstat -y >/dev/null 2>&1
systemctl start vnstat >/dev/null 2>&1
systemctl enable vnstat >/dev/null 2>&1
	_rundone "$cai $quan_ly_bang_thong"
fi
. /etc/wptt/tai-nguyen-server/wptt-bang-thong-main 98
fi



if [[ $vnstat_check = 'on' ]];then
echo -e "$xac_nhan $tat tool $quan_ly_bang_thong ?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done


	if [[ "$dongy" = 'y' ]]; then
	_runing "$tat $quan_ly_bang_thong"
dnf remove vnstat -y >/dev/null 2>&1
systemctl stop vnstat >/dev/null 2>&1
systemctl disable vnstat >/dev/null 2>&1
	_rundone "$tat $quan_ly_bang_thong"
fi
. /etc/wptt/tai-nguyen-server/wptt-bang-thong-main
fi


. /etc/wptt/tai-nguyen-server/wptt-bang-thong-main

