#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/echo-color

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_bang_thong => Xem thông kê băng thông theo tháng              |"
echo "========================================================================="

vnstat -m


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/tai-nguyen-server/wptt-bang-thong-main 1
fi

