#!/bin/bash
. /etc/wptt/.wptt.conf
MYSQL_CONN="-u $database_admin_username -p${database_admin_password}"
TBLLIST=""
COMMA=""
SQL="SELECT CONCAT(table_schema,'.',table_name) FROM information_schema.tables WHERE"
SQL="${SQL} table_schema NOT IN ('information_schema','mysql','performance_schema')"
for DBTB in $(mysql ${MYSQL_CONN} -ANe"${SQL}"); do
    echo Toi uu hoa TABLE "${DBTB};"
    SQL="OPTIMIZE TABLE ${DBTB};"
    mysql ${MYSQL_CONN} -ANe"${SQL}"
done
echo "Hoan tat qua trinh toi uu tat ca database"
