#!/bin/bash

function huong_dan() {
  Kiểm tra mã nguồn có bị dính mã độc mã hoá base64 không?
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

tinh_nang_ten="Kiểm tra mã nguồn mã hoá Decode base64"

. /etc/wptt/echo-color
echo -e "${C_CYAN}╭───────────────────────────────────────────────────────────────────────╮${C_RESET}"
center_text "${C_BOLD_WHITE}$quan_ly_wordpress ➜ $tinh_nang_ten${C_RESET}"
echo -e "${C_CYAN}╰───────────────────────────────────────────────────────────────────────╯${C_RESET}\n"

. /etc/wptt/tenmien-only-website-by-wordpress
lua_chon_NAME "$tinh_nang_ten"

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  exec /etc/wptt/wptt-wordpress-main 1
fi

if [[ ! -d /root/.wp-cli/packages/vendor/wp-cli/doctor-command ]]; then
  wp package install git@github.com:wp-cli/doctor-command.git --allow-root
fi

path="/usr/local/lsws/$NAME/html"

echo "Đang kiểm tra mã nguồn website $NAME ..."

giatuancheck=$(wp doctor check file-eval --allow-root --path="$path" | grep -c "success")
if [[ "$giatuancheck" = "1" ]]; then
  echo "Ma nguon website $NAME cua ban khong co ma hoa decode base64"
else
  echo "Da co van de khong on voi ma nguon website $NAME cua ban"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  exec /etc/wptt/wptt-wordpress-main 1
fi
