#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
. /etc/wptt/echo-color
echo "========================================================================="
echo "|$quan_ly_wordpress => $bat / $tat $chinh_sua_code_truc_tiep_wp_admin_wordpress    |"
echo "========================================================================="

function lua_chon_NAME() {
    NAME=""
    if [ "$(ls -At /etc/wptt/vhost)" ]; then
        selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [ "$NAME" != "${NAME/./}" ]; then
				if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]];then
					#tuỳ biến thêm thông báo
					if [[ $(cat /usr/local/lsws/$NAME/html/wp-config.php | grep 'DISALLOW_FILE_EDIT' | grep 'true') ]];then
						NAME="$NAME đang bật tính năng không cho phép chỉnh sửa code trong dashboard"
					else
						NAME="$NAME đang tắt tính năng không cho phép chỉnh sửa code trong dashboard"
					fi
					selects+=("$NAME")
				fi
			fi
		done

if [[ $selects = '' ]];then
echo "Tất cả domain trên hệ thống chưa có domain nào được kích hoạt sử dụng chuyển hướng"
   . /etc/wptt/wptt-domain-main 1
fi

        PS3="
-//- $lua_chon_website_ban_muon [0=$exit_thoat]: "
        select select in "${selects[@]}"; do
            NAME=$select
            index=$REPLY
            break
        done
    else
        clear
        echo "$khong_co_domain_nao_ton_tai_tren_he_thong"
        exit
    fi
}

lua_chon_NAME


NAME=$(echo $NAME | cut -f1 -d ' ')
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi


unset da_setup_mods
if [[ $(cat /usr/local/lsws/$NAME/html/wp-config.php | grep 'DISALLOW_FILE_MODS'| grep 'true') ]];then
	da_setup_mods='1'
else
	da_setup_mods='0'
fi


if [[ $da_setup_mods = '0' ]];then
	echo "Xác nhận kích hoạt tính năng không cho phép sửa code trực tiếp trên wp-admin"
	prompt="Nhập lựa chọn của bạn [1-2]: "
	dongy="n"
	options=("Đồng ý" "Không đồng ý")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
			*)
				printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
		esac
	done



	if [[ "$dongy" = "y" ]]; then
		. /etc/wptt/echo-color
		wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
		if [[ ! -f $wp_config ]];then
			echoDo "không xác định được file wp-config của website $NAME"
			. /etc/wptt/wptt-wordpress-main 1
		fi

		_runing "$bat tính năng không cho phép sửa code trực tiếp trên wp-admin"
		sed -i "/DISALLOW_FILE_EDIT/d" "$wp_config"
		sed -i "/DISALLOW_FILE_MODS/d" "$wp_config"
		sed -i "/<?php/a define( 'DISALLOW_FILE_EDIT', true);" "$wp_config"
		sed -i "/<?php/a define( 'DISALLOW_FILE_MODS', true);" "$wp_config"
		wp eval 'opcache_reset();' --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 #xoá opcache_reset
		_rundone "$bat tính năng không cho phép sửa code trực tiếp trên wp-admin"
	fi
fi



if [[ $da_setup_mods = '1' ]];then
	echo "Xác nhận huỷ kích hoạt tính năng không cho phép sửa code trực tiếp trên wp-admin"
	prompt="Nhập lựa chọn của bạn [1-2]: "
	dongy="n"
	options=("Đồng ý" "Không đồng ý")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
			*)
				printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
		esac
	done



	if [[ "$dongy" = "y" ]]; then
		. /etc/wptt/echo-color
		wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
		if [[ ! -f $wp_config ]];then
			echoDo "không xác định được file wp-config của website $NAME"
			. /etc/wptt/wptt-wordpress-main 1
		fi

		_runing "Tắt tính năng không cho phép sửa code trực tiếp trên wp-admin"
		sed -i "/DISALLOW_FILE_EDIT/d" "$wp_config"
		sed -i "/DISALLOW_FILE_MODS/d" "$wp_config"
		wp eval 'opcache_reset();' --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 #xoá opcache_reset
		_rundone "Tắt tính năng không cho phép sửa code trực tiếp trên wp-admin"
	fi
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-wordpress-main 1
fi

