#!/bin/bash

function huong_dan() {
  Tính năng này để cài đặt lại hoặc ghi đè các file lõi [core files] của WordPress.

  Mục đích sử dụng chính [tính năng] của lệnh này:

  * Sửa chữa lỗi lõi WordPress: Nếu các file lõi của WordPress bị hỏng do cập nhật thất bại, bị nhiễm mã độc, hoặc do sửa đổi file không mong muốn, lệnh này có thể khôi phục chúng về trạng thái gốc sạch sẽ.
  * Đảm bảo tính toàn vẹn của file lõi: Giúp chắc chắn rằng các file lõi trên website của bạn hoàn toàn giống với bản phát hành chính thức từ WordPress.org.
  * Giải quyết sự cố không rõ nguyên nhân: Đôi khi, đây là một bước khắc phục sự cố khi website gặp lỗi lạ mà nghi ngờ có liên quan đến file lõi.

  Tóm lại, lệnh này cung cấp một cách mạnh mẽ để làm mới các file lõi WordPress một cách có kiểm soát, giữ lại nội dung quan trọng của bạn, và thường được dùng để sửa lỗi hoặc đảm bảo tính toàn vẹn của cài đặt WordPress.
}

. /etc/wptt/echo-color
tinh_nang_ten="Update ghi đè WordPress core"

echo -e "${C_CYAN}╭───────────────────────────────────────────────────────────────────────╮${C_RESET}"
center_text "${C_BOLD_WHITE}$quan_ly_wordpress ➜ $tinh_nang_ten${C_RESET}"
echo -e "${C_CYAN}╰───────────────────────────────────────────────────────────────────────╯${C_RESET}\n"

. /etc/wptt/echo-color
NAME=$1
if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ $NAME = "" ]]; then
  . /etc/wptt/tenmien-them-lua-chon-tat-ca-website-by-wordpress
  lua_chon_NAME "$tinh_nang_ten"
fi

if [[ $NAME = 'Tất cả website' ]]; then
  if [ "$(ls -A /etc/wptt/vhost | grep -v '^\.\.conf$' | sort -uV)" ]; then
    for entry in $(ls -A /etc/wptt/vhost | grep -v '^\.\.conf$' | sort -uV); do
      domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      path="/usr/local/lsws/$domain/html/wp-config.php"
      path_html="/usr/local/lsws/$domain/html"
      i=1
      if [ "$domain" != "${domain/./}" ] && [ "$domain" != '.' ]; then #điều kiện domain phải có dấu . và lỗi chỉ có only .
        if [[ -f "$path" ]]; then
          _rundone "Reinstall WordPress Core"
          (/etc/wptt/wordpress/ghi-de-wordpress-core $domain >/dev/null 2>&1)
          _rundone "Reinstall WordPress Core"
        fi
      fi
    done
  fi
  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    exec /etc/wptt/wordpress/wptt-update-wordpress-main 1
  fi
  exit
fi

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  exec /etc/wptt/wordpress/wptt-update-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  exec /etc/wptt/wordpress/wptt-update-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  exec /etc/wptt/wordpress/wptt-update-wordpress-main 1
  exit
fi

path="/usr/local/lsws/$NAME/html"

_runing "Reinstall WordPress Core"

. /etc/wptt/vhost/.$NAME.conf
. /etc/wptt/php/php-cli-domain-config $NAME
sudo -u "$User_name_vhost" /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp core download --skip-content --force --allow-root --path="$path"

_rundone "Reinstall WordPress Core"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  exec /etc/wptt/wordpress/wptt-update-wordpress-main 1
fi
