#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_cap_nhat_wordpress => Downguprade WordPress core               |"
echo "========================================================================="
. /etc/wptt/echo-color
NAME=$1
if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ $NAME = "" ]];then
. /etc/wptt/tenmien-only-website-by-wordpress
echo ""
echo ""
echo "$lua_chon_website_ban_muon hạ cấp WordPress core: "
echo ""
lua_chon_NAME
fi


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

unset wp_version phien_ban_core_download line selects
path="/usr/local/lsws/$NAME/html"
phien_ban_core_download=$(curl -s "https://api.wordpress.org/core/version-check/1.7/" | \
tr "}" "\n" | \
grep 'version' |\
awk 'match($0, /"version":"([^"]+)"/, arr) { print arr[1] }'|\
sort -ruV |\
while read -r line; do
  echo "$line"
done)

clear
echo "Bạn hãy lựa chọn phiên bản WordPress Core muốn sử dụng: "
while IFS= read -r line; do selects+=("$line"); done <<<"$phien_ban_core_download"
	PS3="
-//- Nhập vào lựa chọn của bạn [1-$(echo $phien_ban_core_download |wc -w)] [0=Thoát]: "
	select select in "${selects[@]}"; do
		wp_version=$select
		break
	done

	
if [[ $wp_version = '0' || $wp_version = '' ]]; then
. /etc/wptt/wordpress/wptt-update-wordpress-main 1
fi


. /etc/wptt/vhost/.$NAME.conf
if [[ $lock_down ]];then
. /etc/wptt/bao-mat/wptt-chattr-file-lock $NAME off
fi

_runing "hạ cấp WordPress Core website $NAME $phien_ban $wp_version"
. /etc/wptt/php/wptt-php-service-cli-theo-domain $NAME 
wp core download --skip-content --version=${wp_version} --force --allow-root --path=$path >/dev/null 2>&1
wp core update-db --allow-root --path=$path >/dev/null 2>&1
_rundone "hạ cấp WordPress Core website $NAME $phien_ban $wp_version"

_runing "$phan_quyen website $NAME"
chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$NAME"/html
if [[ $lock_down ]];then
	find /usr/local/lsws/"$NAME"/html -type f -print0 |xargs -0 chmod 404
	find /usr/local/lsws/"$NAME"/html -type d -print0 |xargs -0 chmod 515
	find /usr/local/lsws/"$NAME"/html/wp-content/uploads -type d -print0 |xargs -0 chmod 755
	. /etc/wptt/bao-mat/wptt-chattr-file-lock $NAME on
else
	find /usr/local/lsws/"$NAME"/html -type f -print0 |xargs -0 chmod 644
	find /usr/local/lsws/"$NAME"/html -type d -print0 |xargs -0 chmod 755
fi
_rundone "$phan_quyen website $NAME"

echo "hạ cấp Core WordPress website $NAME : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wordpress/wptt-update-wordpress-main 1
fi

