#!/bin/bash
. /etc/wptt/echo-color
tinh_nang_ten="Kiểm tra sức khoẻ WordPress"

echo -e "${C_CYAN}╭──────────────────────────────────────────────────────────────────────────────╮${C_RESET}"
center_text "${C_BOLD_WHITE}$quan_ly_wordpress ➜ $tinh_nang_ten${C_RESET}"
echo -e "${C_CYAN}╰──────────────────────────────────────────────────────────────────────────────╯${C_RESET}\n"

. /etc/wptt/tenmien-only-website-by-wordpress
lua_chon_NAME "$tinh_nang_ten"

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  exec /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  exec /etc/wptt/wptt-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main
  exit
fi

if [[ ! -d /root/.wp-cli/packages/vendor/wp-cli/doctor-command ]]; then
  wp package install git@github.com:wp-cli/doctor-command.git --allow-root
  clear
fi

path="/usr/local/lsws/$NAME/html"
. /etc/wptt/php/php-cli-domain-config $NAME
/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp doctor check --all --allow-root --path="$path"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  exec /etc/wptt/wptt-wordpress-main 1
fi
