#!/bin/bash
function huong_dan() {
  Tính năng này đăng nhập nhanh vào tài khoản dashboard WP-admin không cần biết tài khoản admin WordPress
}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Đăng nhập Login wp-admin magic link               |"
echo "========================================================================="
echo ""
echo ""
NAME=$1

if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ "$NAME" = "" ]]; then
  . /etc/wptt/tenmien
  echo ""
  echo ""
  echo "Lựa chọn website muốn đăng nhập Login wp-admin magic link: "
  echo ""
  lua_chon_NAME
fi

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi

. /etc/wptt/echo-color

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Domain khong ton tai tren VPS."
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"

  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

echo "Magic link login website $NAME: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

. /etc/wptt/php/php-cli-domain-config $NAME
path="/usr/local/lsws/$NAME/html"
pathlogin="/usr/local/lsws/$NAME/html/wp-content/plugins/dologin"

if [[ ! -d "$pathlogin" ]]; then
  _runing "Download plugin WP CLI dologin"
  /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp plugin install dologin --activate --path=$path --allow-root >/dev/null 2>&1
  . /etc/wptt/vhost/."$NAME".conf
  chown -R "$User_name_vhost":"$User_name_vhost" $pathlogin
  find $pathlogin -type d -exec chmod 755 {} \;
  find $pathlogin -type f -exec chmod 644 {} \;
  _rundone "Download plugin WP CLI dologin"
fi
clear
_runing "Tạo link đăng nhập"
tuan=$(/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp user list --role=administrator --fields=user_login --path=$path --allow-root 2>/dev/null | sed '/user_login/d' | tail -1 | sed -n '$p')
giatuandzdz=$(/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp dologin gen "$tuan" --path=$path --allow-root 2>/dev/null | cut -f2 -d '?')
if [[ "$giatuandzdz" ]]; then
  _rundone "Tạo link đăng nhập"
  echo "Truy cập vào đường dẫn link để login wp-admin: https://$NAME/wp-admin/?${giatuandzdz}"
  echo "Link login magic này chỉ có thể sử dụng một lần duy nhất"
else
  _runloi "Tạo link đăng nhập"
  echoDo "Không thiết lập được magic link login"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi
