#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Login wp-admin magic link                         |"
echo "========================================================================="
echo ""
echo ""
NAME=$1

if [[ "$NAME" = "" ]];then
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website muon Login wp-admin magic link: "
echo ""
lua_chon_NAME
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-menu-wordpress
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-config.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt/wptt-menu-wordpress
  exit
fi


        PACKAGEQUERY=$(wp package list | grep -i 'wp-cli-login-command')
        if [[ $PACKAGEQUERY = "" ]];then
	wp package install aaemnnosttv/wp-cli-login-command --allow-root
        fi
        
path="/usr/local/lsws/$NAME/html"
pathlogin="/usr/local/lsws/$NAME/html/wp-content/plugins/wp-cli-login-server"

if [[ ! -d "$pathlogin" ]]; then
wp login install --activate --path=$path --allow-root 
. /etc/wptt/vhost/."$NAME".conf
chown -R "$User_name_vhost":"$User_name_vhost" $pathlogin
find $pathlogin -type d -exec chmod 755 {} \;
find $pathlogin -type f -exec chmod 644 {} \;
fi

tuan=$(wp user list --role=administrator --fields=user_login --path=$path | sed '/user_login/d' | head -1)
giatuandzdz=$(wp login create "$tuan" --path=$path --allow-root | grep 'http')
if [[ "$giatuandzdz" ]];then
echo "Truy vao duong dan link de login wp-admin: $giatuandzdz"
echo "Khi truy cap thi url magic link nay se tu dong bi vo hieu hoa"
else
echo "khong thiet lap duoc magic link login"
fi

