#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Cache => Kich hoat LScache                                 |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website muon kich hoat LScache: "
echo ""
lua_chon_NAME
pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
. /etc/wptt/wptt-cache-main
    exit
fi

pathcheckplugin="/usr/local/lsws/$NAME/html/wp-content/plugins/litespeed-cache"
if [[ -d "$pathcheckplugin" ]]; then
    echo "ban da su dung plugin LiteSpeed cache wordpress thi da duoc kich hoat LSCache roi"
    exit
fi

pathcheckplugin2="/usr/local/lsws/$NAME/html/wp-content/plugins/wp-rocket"
if [[ -d "$pathcheckplugin2" ]]; then
    echo "ban da su dung plugin wp rocket wordpress thi khong nen kich hoat LScache de tranh xung dot"
    echo "neu ban muon su dung Lscache thi hay xoa plugin WP rocket di"
    exit
fi

pathcheckplugin3="/usr/local/lsws/$NAME/html/wp-content/plugins/w3-total-cache"
if [[ -d "$pathcheckplugin3" ]]; then
    echo "ban da su dung plugin W3 total cache wordpress thi khong nen kich hoat LScache de tranh xung dot"
    echo "neu ban muon su dung Lscache thi hay xoa plugin w3 total cache di"
    exit
fi

echo "Tot nhat ban hay len su dung plugin LiteSpeed cache WordPress de kich hoat de ban co the tuy bien duoc lscache phuc vu nhu cau tang toc hieu qua hon" 
read -p "Ban muon kich hoat LSCache bang .htaccess? (y/n): " check
if [[ "$check" = "y" ]]; then
    path="/usr/local/lsws/$NAME/html"
    echo '<IfModule LiteSpeed>
CacheEnable public /
RewriteEngine on
RewriteCond %{REQUEST_METHOD} ^(HEAD|GET)$
RewriteCond %{REQUEST_URI} !^/(wp-admin|wp-login.php|wp-cron.php)
RewriteRule .* - [E=Cache-Control:max-age=7200]
</IfModule>' >>/usr/local/lsws/$NAME/html/.htaccess

    wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
    sed -i "/WP_CACHE/d" $wp_config
    sed -i "/<?php/a define( 'WP_CACHE', true );" $wp_config
    /usr/local/lsws/bin/lswsctrl restart
fi
echo "hoan tat"



check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "99" ]];then
. /etc/wptt/wptt-cache-main 1
fi

