#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => nhap du lieu toi uu plugin LiteSpeed Cache        |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website muon nhap du lieu toi uu plugin LiteSpeed cache: "
echo ""
lua_chon_NAME

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-menu-wordpress
    exit
fi
. /etc/wptt/vhost/.$NAME.conf

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
    clear
    echo "He thong xac nhan ban chua kich hoat su dung WordPress"
    sleep 3
    . /etc/wptt/wptt-menu-wordpress
    exit
fi

if [[ -f /etc/redis.conf ]];then
data_wptangtoc="wptangtoc-rs.data"
else
data_wptangtoc="wptangtoc.data"
fi

path="/usr/local/lsws/$NAME/html"

pluginsspeed=(
	wp-rocket
	w3-total-cache
	wp-super-cache
	wp2speed
	nitropack
	wp-fastest-cache
	hummingbird-performance
	swift-performance-lite
	swift-performance-pro
	cache-enabler
	sg-cachepress
	breeze
	wp-meteor
	phastpress
	)

for plugintt in ${pluginsspeed[@]}
do
	pathcheckplugin3="/usr/local/lsws/$NAME/html/wp-content/plugins/$plugintt"
if [[ -d "$pathcheckplugin3" ]]; then
    echo "Ban da su dung plugin $plugintt wordpress thi khong nen kich hoat LScache de tranh xung dot"
    echo "Neu ban muon su dung Lscache thi hay xoa plugin $plugintt di"
    exit
fi

done

echo "Dang tien hanh tai plugin LiteSpeed Cache cho website $NAME"
pathcheckplugin="/usr/local/lsws/$NAME/html/wp-content/plugins/litespeed-cache"
if [[ ! -d "$pathcheckplugin" ]]; then
echo "Ban chua cai dat plugin LiteSpeed Cache: "
read -p "Ban co muon cai dat plugin LiteSpeed Cache Khong (y/n): " dong_y_install
if [[ $dong_y_install = "y" ]];then
wp plugin install litespeed-cache --activate --allow-root --path="$path"
chown -R $User_name_vhost:$User_name_vhost /usr/local/lsws/"$NAME"/html/wp-content
cd /usr/local/lsws/"$NAME"/html/wp-content && find . -type d -exec chmod 755 {} \;
cd /usr/local/lsws/"$NAME"/html/wp-content && find . -type f -exec chmod 644 {} \;
else
	exit
fi
fi

if [[ -d "$pathcheckplugin" ]]; then
        echo ""
        echo "Dang toi uu theo cach cua wptangtoc"
        echo ""

ip=$(curl -s myip.directadmin.com)
if [[ "$ip" = "" ]]; then
    ip=$(curl -s ifconfig.me)
fi
        sed -i "/WP_CACHE/d" /usr/local/lsws/"$NAME"/html/wp-config.php
        rm -rf /usr/local/lsws/"$NAME"/html/wp-content/cache
        rm -f /usr/local/lsws/"$NAME"/html/wp-content/object-cache.php
        cd "$path" && wget https://wptangtoc.com/share/$data_wptangtoc --no-check-certificate
        wp plugin activate litespeed-cache --allow-root --path="$path"
        wp litespeed-option import $data_wptangtoc --path="$path" --allow-root
wp option patch update litespeed.conf.server_ip $ip --path="$path" --allow-root
        rm -f $data_wptangtoc
        echo "hoan tat qua trinh import nhap du lieu wptangtoc cho litespeed"
    fi
wp rewrite flush --allow-root --path="$path"
/usr/local/lsws/bin/lswsctrl restart

echo "==================================================================="
echo "Hoan tat qua trinh tai plugin Litespeed va tu dong toi uu hoa"
echo "Cong cu phat trien boi	: Gia Tuan"
echo "Yeu Cau Ho tro		: wptangtoc.com/lien-he"
echo "Tai tro phat trien	: wptangtoc.com/donate"
echo "==================================================================="
