#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Nhập dữ liệu tối ưu plugin LiteSpeed Cache        |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website bạn muốn nhập dữ liệu tối ưu plugin LiteSpeed cache: "
echo ""
lua_chon_NAME


. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi


if [[ -f /etc/redis.conf ]];then
data_wptangtoc="wptangtoc-rs.data"
else
data_wptangtoc="wptangtoc.data"
fi

path="/usr/local/lsws/$NAME/html"

pluginsspeed=(
	cache-enabler
	wp-rocket
	w3-total-cache
	wp-super-cache
	wp2speed
	nitropack
	wp-fastest-cache
	hummingbird-performance
	swift-performance-lite
	swift-performance-pro
	cache-enabler
	sg-cachepress
	breeze
	wp-meteor
	phastpress
	flying-press
	comet-cache
	powered-cache
	borlabs-cache
	hyper-cache
	wp-speed-of-light
	surge
	nginx-helper
	)

for plugintt in ${pluginsspeed[@]}
do
	pathcheckplugin3="/usr/local/lsws/$NAME/html/wp-content/plugins/$plugintt"
if [[ -d "$pathcheckplugin3" ]]; then
    echo "Ban da su dung plugin $plugintt wordpress thi khong nen kich hoat LScache de tranh xung dot"
    echo "Neu ban muon su dung Lscache thi hay xoa plugin $plugintt di"
    exit
fi

done


pathcheckplugin="/usr/local/lsws/$NAME/html/wp-content/plugins/litespeed-cache"
if [[ ! -d "$pathcheckplugin" ]]; then
	_runing "Cài đặt plugin LiteSpeed Cache"
wp plugin install litespeed-cache --allow-root --path="$path" >/dev/null 2>&1
. /etc/wptt/vhost/."$NAME".conf && chown -R "$User_name_vhost":"$User_name_vhost" $pathcheckplugin
if [[ -d $pathcheckplugin ]];then
	_rundone "Cài đặt plugin LiteSpeed Cache"
else
	_runloi "Cài đặt plugin LiteSpeed Cache"
fi
fi

_runing "Cấu hình tối ưu theo cách khuyến nghị của wptangtoc.com (Gia Tuấn)"

if [[ -d "$pathcheckplugin" ]]; then
ip=$(curl -s myip.directadmin.com)
if [[ "$ip" = "" ]]; then
    ip=$(curl -s ifconfig.me)
fi
        sed -i "/WP_CACHE/d" /usr/local/lsws/"$NAME"/html/wp-config.php
        rm -rf /usr/local/lsws/"$NAME"/html/wp-content/cache
        rm -f /usr/local/lsws/"$NAME"/html/wp-content/object-cache.php
        cd "$path" && wget -q https://wptangtoc.com/share/$data_wptangtoc --no-check-certificate
        wp plugin activate litespeed-cache --allow-root --path="$path" >/dev/null 2>&1
        wp litespeed-option import $data_wptangtoc --path="$path" --allow-root >/dev/null 2>&1
wp option patch update litespeed.conf.server_ip $ip --path="$path" --allow-root >/dev/null 2>&1
        rm -f $data_wptangtoc
_rundone "Cấu hình tối ưu theo cách khuyến nghị của wptangtoc.com (Gia Tuấn)"
    fi
wp rewrite flush --allow-root --path="$path"
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

echo "==================================================================="
echo "Hoan tat qua trinh tai plugin Litespeed va tu dong toi uu hoa"
echo "Cong cu phat trien boi	: Gia Tuan"
echo "Yeu Cau Ho tro		: wptangtoc.com/lien-he"
echo "Tai tro phat trien	: wptangtoc.com/donate"
echo "==================================================================="
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-wordpress-main 1
fi
