#!/bin/bash

function huong_dan() {
  tính năng rewrite trong WordPress, hay còn gọi là WordPress Rewrite API và thường được biết đến qua Permalinks [Đường dẫn tĩnh], là một hệ thống mạnh mẽ cho phép WordPress chuyển đổi các URL [địa chỉ web] mặc định khó hiểu thành các URL thân thiện, dễ đọc và tốt cho SEO.

  Giải thích ngắn gọn:

  Thay vì một URL dạng:
  * http://example.com/?p=123 [khó nhớ, không thân thiện với SEO]
  WordPress có thể rewrite [viết lại] nó thành dạng:
  * http://example.com/ten-bai-viet-cua-ban/ [dễ đọc, dễ nhớ, tốt cho SEO]
  hoặc
  * http://example.com/chuyen-muc/ten-bai-viet/

  Tính năng rewrite của WordPress là một công cụ thiết yếu giúp website của bạn có các đường dẫn URL đẹp mắt, dễ hiểu, thân thiện với người dùng và đặc biệt quan trọng cho việc tối ưu hóa công cụ tìm kiếm [SEO].
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_wordpress => Rewrite permalink                                 |"
echo "========================================================================="

. /etc/wptt/echo-color
NAME=$1
if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ $NAME = "" ]]; then
  . /etc/wptt/tenmien-them-lua-chon-tat-ca-website-by-wordpress
  echo ""
  echo ""
  echo "$nhap_lua_chon_website_cua_ban rewrite permalink: "
  echo ""
  lua_chon_NAME
fi

if [[ $NAME = 'Tất cả website' ]]; then
  if [ "$(ls -A /etc/wptt/vhost)" ]; then
    for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
      domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      path="/usr/local/lsws/$domain/html/wp-config.php"
      path_html="/usr/local/lsws/$domain/html"
      i=1
      if [ "$domain" != "${domain/./}" ] && [ "$domain" != '.' ]; then #điều kiện domain phải có dấu . và lỗi chỉ có only .
        if [[ -f "$path" ]]; then
          _runing "rewrite permalink website $domain"
          (/etc/wptt/wordpress/rewrite $domain >/dev/null 2>&1)
          _rundone "rewrite permalink website $domain"
        fi
      fi
    done
  fi

  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
  fi
  exit
fi

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

path="/usr/local/lsws/$NAME/html"

_runing "Rewrite permalink cho website $NAME"
. /etc/wptt/php/php-cli-domain-config $NAME
/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp rewrite flush --path="$path" --allow-root >/dev/null 2>&1
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "Rewrite permalink cho website $NAME"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi
