#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Tai plugin LiteSpeed Cache                        |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website muon tai plugin LiteSpeed cache: "
echo ""
lua_chon_NAME

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-menu-wordpress
    exit
fi
. /etc/wptt/vhost/.$NAME.conf

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
    clear
    echo "He thong xac nhan ban chua kich hoat su dung WordPress"
    sleep 3
    . /etc/wptt/wptt-menu-wordpress
    exit
fi

path="/usr/local/lsws/$NAME/html"

pathcheckplugin="/usr/local/lsws/$NAME/html/wp-content/plugins/litespeed-cache"
if [[ -d "$pathcheckplugin" ]]; then
    echo "ban da kich hoat su dung plugin LiteSpeed cache roi"
    read -p "ban co muon import toi uu theo cach cua wptangtoc cho LiteSpeed Cache khong (y/n): " dongynhap
    if [[ "$dongynhap" = "y" ]]; then
        echo ""
        echo "Dang toi uu theo cach cua wptangtoc"
        echo ""
        sed -i "/WP_CACHE/d" /usr/local/lsws/"$NAME"/html/wp-config.php
        rm -rf /usr/local/lsws/"$NAME"/html/wp-content/cache
        rm -f /usr/local/lsws/"$NAME"/html/wp-content/object-cache.php
        cd "$path" && wget https://wptangtoc.com/share/wptangtoc.data --no-check-certificate
        wp plugin activate litespeed-cache --allow-root --path="$path"
        wp litespeed-option import wptangtoc.data --path="$path" --allow-root
        rm -f wptangtoc.data
        echo "hoan tat qua trinh import nhap du lieu wptangtoc cho litespeed"
    fi
    exit
fi
pluginsspeed=(
	wp-rocket
	w3-total-cache
	wp-super-cache
	wp2speed
	nitropack
	wp-fastest-cache
	hummingbird-performance
	swift-performance-lite
	swift-performance-pro
	cache-enabler
	sg-cachepress
	breeze
	wp-meteor
	phastpress
	)

for plugintt in ${pluginsspeed[@]}
do
	pathcheckplugin3="/usr/local/lsws/$NAME/html/wp-content/plugins/$plugintt"
if [[ -d "$pathcheckplugin3" ]]; then
    echo "Ban da su dung plugin $plugintt wordpress thi khong nen kich hoat LScache de tranh xung dot"
    echo "Neu ban muon su dung Lscache thi hay xoa plugin $plugintt di"
    exit
fi

done

echo "Dang tien hanh tai plugin LiteSpeed Cache cho website $NAME"

cd "$path"
wp plugin install litespeed-cache --activate --allow-root --version=3.6.4 --path="$path"
echo "hoan tat tai plugin LiteSpeed cache va kich hoat"
echo "dang toi uu theo cach cua wptangtoc"
cd "$path" && wget https://wptangtoc.com/share/wptangtoc.data
wp litespeed-option import wptangtoc.data --path="$path" --allow-root
rm -f wptangtoc.data
chown -R $User_name_vhost:$User_name_vhost /usr/local/lsws/"$NAME"/html/wp-content/plugins/litespeed-cache
cd /usr/local/lsws/"$NAME"/html/wp-content/plugins/litespeed-cache && find . -type d -exec chmod 755 {} \;
cd /usr/local/lsws/"$NAME"/html/wp-content/plugins/litespeed-cache && find . -type f -exec chmod 644 {} \;

wp rewrite flush --allow-root --path="$path"
/usr/local/lsws/bin/lswsctrl restart

echo "==================================================================="
echo "Hoan tat qua trinh tai plugin Litespeed va tu dong toi uu hoa"
echo "Cong cu phat trien boi	: Gia Tuan"
echo "Yeu Cau Ho tro		: wptangtoc.com/lien-he"
echo "Tai tro phat trien	: wptangtoc.com/donate"
echo "==================================================================="
