#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_wordpress => $tang_gioi_han_ram WordPress                       |"
echo "========================================================================="


. /etc/wptt/echo-color

unset ram_wordpress_giatri selects
echo "$lua_chon_website_ban_muon $tang_gioi_han_ram WordPress: "
function lua_chon_NAME() {
    NAME=""
    if [ "$(ls -At /etc/wptt/vhost)" ]; then
        selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [ "$NAME" != "${NAME/./}" ]; then
				if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]];then
					#tuỳ biến thêm thông báo
					unset ram_wordpress_giatri
					ram_wordpress_giatri=$(cat /usr/local/lsws/$NAME/html/wp-config.php | grep 'WP_MEMORY_LIMIT' | cut -d \' -f4)
					if [[ $ram_wordpress_giatri ]];then
						NAME="$NAME đang được cấu hình là ${ram_wordpress_giatri}B"
					else
						NAME="$NAME đang được cấu hình là 64MB"
					fi
					selects+=("$NAME")
				fi
			fi
		done

if [[ -z $selects ]];then
echo "Tất cả domain trên hệ thống chưa có domain đang sử dụng WordPress"
   . /etc/wptt/wptt-domain-main 1
fi

        PS3="
-//- $lua_chon_website_ban_muon [0=$exit_thoat]: "
        select select in "${selects[@]}"; do
            NAME=$select
            index=$REPLY
            break
        done
    else
        clear
        echo "$khong_co_domain_nao_ton_tai_tren_he_thong"
        exit
    fi
}

lua_chon_NAME


NAME=$(echo $NAME | cut -f1 -d ' ')

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

read -p "Nhập số dung lượng MB ram bạn muốn cấu hình (ví dụ: 256) [0=$exit_thoat]: " ram_number
if [[ $ram_number = '0' || $ram_number = '' ]]; then
	. /etc/wptt/wptt-wordpress-main 1
fi

ram_number=$(echo $ram_number | sed 's/mb//g' | sed 's/MB//g'| sed 's/M//g'| sed 's/m//g' | sed 's/ //g' | sed 's/-//g')

if [[ ! $ram_number =~ ^-?[0-9]+$ ]]; then
	echoDo "Bạn nhập sai kiểu dữ liệu vui lòng nhập số nguyên"
	. /etc/wptt/wptt-wordpress-main 1
fi


_runing "Tăng giới hạn Ram WordPress website $NAME thành ${ram_number}MB"
wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
sed -i "/WP_MEMORY_LIMIT/d" "$wp_config"
sed -i "/<?php/a define( 'WP_MEMORY_LIMIT', '${ram_number}M' );" "$wp_config"
wp eval 'opcache_reset();' --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 #xoá opcache_reset
_rundone "Tăng giới hạn Ram WordPress website $NAME thành ${ram_number}MB"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-wordpress-main 1
fi

