#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_wordpress => Tăng mức giới hạn WordPress                       |"
echo "========================================================================="


. /etc/wptt/echo-color
NAME=$1
if [[ $NAME = '98' ]];then
NAME=''
fi

if [[ $NAME = '' ]];then
. /etc/wptt/tenmien-them-lua-chon-tat-ca-website-by-wordpress
echo ""
echo ""
echo "$lua_chon_website_ban_muon rewrite permalink: "
echo ""
lua_chon_NAME
fi

if [[ $NAME = 'Tất cả website' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path="/usr/local/lsws/$domain/html/wp-load.php"
			path_html="/usr/local/lsws/$domain/html"
			i=1
			if [ "$domain" != "${domain/./}" ] && [ "$domain" != '.' ]; then #điều kiện domain phải có dấu . và lỗi chỉ có only .
				if [[ -f "$path" ]]; then
					. /etc/wptt/vhost/."$domain".conf
					_runing "Tăng Ram WordPress website $domain"
					. /etc/wptt/db/wptt-ket-noi $domain >/dev/null 2>&1
					_rundone "Tăng Ram WordPress website $domain"
				fi
			fi
		done
	fi
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-db-main 1
	fi
	exit
fi



if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

_runing "Tăng giới hạn Ram WordPress website $NAME"
wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
sed -i "/WP_MEMORY_LIMIT/d" "$wp_config"
sed -i "/<?php/a define( 'WP_MEMORY_LIMIT', '128M' );" "$wp_config"
_rundone "Tăng giới hạn Ram WordPress website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-wordpress-main 1
fi

