#!/bin/bash

function huong_dan() {
  Tắt tính năng tối ưu hóa WP-Cron là quá trình hoàn nguyên [revert] các cài đặt đã được thực hiện để tối ưu hóa WP-Cron, đưa hệ thống xử lý tác vụ theo lịch của WordPress trở về cơ chế hoạt động mặc định của nó.

  Nói một cách đơn giản, nếu trước đó bạn đã cấu hình để WP-Cron chạy hiệu quả hơn bằng cách vô hiệu hóa việc nó tự kích hoạt theo lượt truy cập và thay bằng một cron job của server, thì tắt tối ưu hóa có nghĩa là bạn quay lại cách hoạt động ban đầu: WP-Cron sẽ lại được kích hoạt mỗi khi có người dùng truy cập website.

  Mục Đích Chính Của Việc Tắt Tối Ưu Hóa
  * Đơn giản hóa [nếu không có quyền truy cập server cron]: Nếu bạn không thể thiết lập cron job ở cấp độ máy chủ [ví dụ: trên một số gói hosting rất hạn chế] hoặc thấy việc đó quá phức tạp.
  * Gỡ lỗi [Troubleshooting]: Nếu nghi ngờ rằng cron job của server được cấu hình sai hoặc đang gây ra sự cố, việc tắt tối ưu hóa [và kích hoạt lại WP-Cron mặc định] có thể là một bước chẩn đoán tạm thời.
  * Chấp nhận được với website lưu lượng rất thấp: Đối với các trang có ít hoặc không có truy cập, nơi việc các tác vụ theo lịch bị trễ một chút là chấp nhận được và gánh nặng của WP-Cron mặc định không đáng kể.
  * Xung đột hiếm gặp: Trong một số trường hợp rất hiếm, có thể có xung đột giữa cách cron job của server gọi wp-cron.php với một plugin cụ thể.

  Sau khi tắt tối ưu hóa, WordPress sẽ quay trở lại cơ chế mặc định: wp-cron.php sẽ được kích hoạt bởi các lượt truy cập vào website. Các tác vụ đã lên lịch sẽ chạy dựa trên lưu lượng truy cập này.

  Lưu ý: Việc này có thể làm tăng tải cho server trên các website có lưu lượng truy cập cao và làm giảm độ tin cậy của việc thực thi tác vụ đúng giờ trên các website có lưu lượng truy cập thấp.
}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Tắt tối ưu wp-cron                                |"
echo "========================================================================="

if [ "$(ls -A /etc/wptt/vhost | sort -uV)" ]; then
  echo "========================================================================="
  echo "Danh sách Domain đã kích hoạt tối ưu hóa wp cron:"
  echo "========================================================================="
  for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/etc/cron.d/wp-cron-job-$domain.cron"
    i=1
    if [[ -f "$path" ]]; then
      checkauto="Đã kích hoạt giá trị thiết lập là "
      checktuan=$(cat /etc/cron.d/wp-cron-job-$domain.cron | cut -f2 -d "/" | cut -f1 -d " ")
      themphut=" phút thực thi cron một lần"
    else
      checkauto="Chưa kích hoạt"
      checktuan=""
      themphut=" tối ưu hóa WP Crond"
    fi
    echo "Website $domain $checkauto$checktuan$themphut"
  done
  echo "========================================================================="
  echo
fi

function lua_chon_NAME() {
  NAME=""
  if [ "$(ls -At /etc/wptt/vhost)" ]; then
    selects=()
    for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
      NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      if [ "$NAME" != "${NAME/./}" ] && [ "$NAME" != '.' ]; then #điều kiện domain phải có dấu . và lỗi chỉ có only .
        if [[ -f /etc/cron.d/wp-cron-job-"$NAME".cron ]]; then
          selects+=("$NAME")
        fi
      fi
    done

    if [[ $selects = '' ]]; then
      echo "Tất cả domain trên hệ thống chưa có domain nào được kích hoạt tối ưu wp cron"
      . /etc/wptt/wptt-wordpress-main 1
    fi

    PS3="
-//- Nhập lựa chọn website của bạn [0=Thoát]: "
    select select in ${selects[@]}; do
      NAME=$select
      index=$REPLY
      break
    done
  else
    clear
    echo "Khong co domain duoc thiet lap toi uu wp cron."
    exit
  fi
}

echo ""
echo ""
echo "Lựa chọn website bạn muốn tắt tối ưu wp-cron: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

if [ ! -f /etc/cron.d/wp-cron-job-"$NAME".cron ]; then
  echo "$NAME chưa được kích hoạt tối ưu wp cron !"
  exit
fi

read -p "Xác nhận bạn có muốn tắt tối ưu wp cron không? (y/n): " dongy
if [[ "$dongy" = "y" ]]; then

  echo "Hủy kích hoạt tối ưu wp cron website $NAME: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log
  _runing "Hủy kích hoạt tối ưu wp cron website $NAME"
  wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
  sed -i "/DISABLE_WP_CRON/d" "$wp_config"

  . /etc/wptt/php/php-cli-domain-config $NAME
  /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp eval 'opcache_reset();' --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 #xoá opcache_reset

  rm -f /etc/cron.d/wp-cron-job-"$NAME".cron
  if $(cat /etc/*release | grep -q "Ubuntu"); then
    NAME_CRON_ubuntu=${NAME//[.]/_}
    rm -f /etc/cron.d/wp-cron-job-{$NAME_CRON_ubuntu}_cron
    systemctl restart cron
  else
    systemctl restart crond
  fi
  _rundone "Hủy kích hoạt tối ưu wp cron website $NAME"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi
