#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Tắt tối ưu wp-cron                                |"
echo "========================================================================="

if [ "$(ls -A /etc/wptt/vhost)" ]; then
	echo "========================================================================="
	echo "Danh sách Domain đã kích hoạt tối ưu hóa wp cron:"
	echo "========================================================================="
	for entry in $(ls -A /etc/wptt/vhost); do
		domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
		path="/etc/cron.d/wp-cron-job-$domain.cron"
		i=1
		if [[ -f "$path" ]]; then
			checkauto="Đã kích hoạt giá trị thiết lập là "
			checktuan=$(cat /etc/cron.d/wp-cron-job-$domain.cron | cut -f2 -d "/" | cut -f1 -d " ")
			themphut=" phút thực thi cron một lần"
		else
			checkauto="Chưa kích hoạt"
			checktuan=""
			themphut=" tối ưu hóa WP Crond"
		fi
		echo "Website $domain $checkauto$checktuan$themphut"
	done
	echo "========================================================================="
	echo
fi


function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ -f /etc/cron.d/wp-cron-job-"$NAME".cron ]]; then
				selects+=("$NAME")
			fi
		done

if [[ $selects = '' ]];then
echo "Tất cả domain trên hệ thống chưa có domain nào được kích hoạt tối ưu wp cron"
. /etc/wptt/wptt-wordpress-main 1
fi

		PS3="
-//- Nhập lựa chọn website của bạn [0=Thoát]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Khong co domain duoc thiet lap toi uu wp cron."
		exit
	fi
}

echo ""
echo ""
echo "Lựa chọn website bạn muốn tắt tối ưu wp-cron: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

if [ ! -f /etc/cron.d/wp-cron-job-"$NAME".cron ]; then
    echo "$NAME chưa được kích hoạt tối ưu wp cron !"
    exit
fi

read -p "Xác nhận bạn có muốn tắt tối ưu wp cron không? (y/n): " dongy
if [[ "$dongy" = "y" ]]; then
	_runing "Hủy kích hoạt tối ưu wp cron website $NAME"
    wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
    sed -i "/DISABLE_WP_CRON/d" "$wp_config"
    rm -f /etc/cron.d/wp-cron-job-"$NAME".cron
	_rundone "Hủy kích hoạt tối ưu wp cron website $NAME"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-wordpress-main 1
fi

