#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Tat bao mat wp-admin 2 lop                        |"
echo "========================================================================="
. /etc/wptt/.wptt.conf

if [ "$(ls -A /etc/wptt/vhost)" ]; then
    echo "========================================================================="
    echo "Danh sach Domain da kich hoat bao mat 2 lop wp-admin:"
    echo "========================================================================="
    for entry in $(ls -A /etc/wptt/vhost); do
        domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
        path="/usr/local/lsws/$domain/passwd/.mk"
        i=1
        if [[ -f "$path" ]]; then
            checkauto="Da kich hoat"
        else
            checkauto="Chua kich hoat"
        fi
        echo "Website $domain $checkauto bap mat 2 lop wp-admin"
    done
    echo "========================================================================="
    echo
fi



echo ""
echo ""
echo "Lua chon website muon tat kich hoat bao mat 2 lop wp-admin: "
echo ""
function lua_chon_NAME() {
    NAME=""
    if [ "$(ls -At /etc/wptt/vhost)" ]; then
        selects=()
        for entry in $(ls -A /etc/wptt/vhost); do
            NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
            if [[ -f /usr/local/lsws/$NAME/passwd/.mk ]]; then
                selects+=("$NAME")
            fi
        done
        PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
        select select in ${selects[@]}; do
            NAME=$select
            index=$REPLY
            break
        done
    else
        clear
        echo "Khong co domain tren he thong cua ban."
        exit
    fi
}


lua_chon_NAME

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-menu-wordpress
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt/wptt-menu-wordpress
  exit
fi

pathcheck2="/usr/local/lsws/$NAME/passwd/.mk"
if [[ ! -f "$pathcheck2" ]]; then
    echo "ban chua kich hoat bao mat 2 lop wp-admin"
    exit
fi

pathcheck2="/usr/local/lsws/$NAME/passwd/.mk"
if [[ -f "$pathcheck2" ]]; then
    read -p "Xac nhan ban co muon tat bao mat 2 lop wp-admin (y/n): " dongy
    if [[ "$dongy" = "y" ]]; then

        sed -i '/realm '${NAME}wp'/,+23d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
        rm -rf /usr/local/lsws/"$NAME"/passwd/.mk
        sed -i "/id_dang_nhap_wordpress_2/d" /etc/wptt/vhost/."$NAME".conf
        sed -i "/password_dang_nhap_wordpress_2/d" /etc/wptt/vhost/."$NAME".conf
        /usr/local/lsws/bin/lswsctrl restart
        echo "============================================================================="
        echo "da hoan huy kich hoat bao mat 2 lop wordpress admin website $NAME"
        echo "============================================================================="

    fi
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main 1
fi

