#!/bin/bash

function huong_dan() {
  Đây là tính năng thay đổi tiền tố database
  mặc định WordPress sử dụng tiền tố wp_
  tính năng này sẽ thay đổi tiền tố đó sẽ giúp nâng cao bảo mật cho WordPress hơn
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_wordpress => $thay_doi $tien_to database                         |"
echo "========================================================================="
. /etc/wptt/tenmien-only-website-by-wordpress
echo ""
echo ""
echo "$lua_chon_website_ban_muon $thay_doi $tien_to database: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉ có thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
  check_mulsite_dang_su_dung=$(cat /usr/local/lsws/$NAME/html/wp-config.php | grep MULTISITE)
  if [[ $check_mulsite_dang_su_dung ]]; then
    echo "Tính năng này không hỗ trợ website WordPress Multisite"
    . /etc/wptt/wptt-wordpress-main 1
  fi
fi

if [[ ! -d /root/.wp-cli/packages/vendor/iandunn/wp-cli-rename-db-prefix ]]; then
  _runing "Cài đặt WP CLI package rename database"
  wp package install iandunn/wp-cli-rename-db-prefix --allow-root >/dev/null 2>&1
  _rundone "Cài đặt WP CLI package rename database"
fi

. /etc/wptt/php/php-cli-domain-config $NAME

unset ramdom_db tien_to_cu dongy
ramdom_db=$(
  date +%s | sha256sum | base64 | head -c 5
  echo
)

path="/usr/local/lsws/$NAME/html"

tien_to_cu=$(/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp db prefix --allow-root --path=$path 2>/dev/null)

echo "Lưu ý: hãy backup website trước khi sử dụng tính năng này"
echo -e "$xac_nhan $thay_doi $tien_to website $NAME từ $tien_to_cu thành ${ramdom_db}_ ?"
prompt="$nhap_lua_chon_cua_ban [1-2]: "
dongy="n"
options=("$dong_y" "$khong_dong_y")
PS3="$prompt"
select opt in "${options[@]}"; do
  case "$REPLY" in
  1)
    dongy="y"
    break
    ;;

  2)
    dongy="n"
    break
    ;;

  $((${#options[@]} + 1)))
    printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
    break
    ;;
  *)
    printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
    break
    ;;
  esac
done

if [[ "$dongy" = 'y' ]]; then
  unset lock_down
  . /etc/wptt/vhost/.$NAME.conf
  if [[ $lock_down ]]; then
    chattr -i /usr/local/lsws/"$NAME"/html/wp-config.php
  fi
  path="/usr/local/lsws/$NAME/html"
  _runing "$thay_doi $tien_to website $NAME từ $tien_to_cu thành ${ramdom_db}_"
  /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp rename-db-prefix "${ramdom_db}"_ --allow-root --path=/usr/local/lsws/$NAME/html --no-confirm >/dev/null 2>&1
  /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp eval 'opcache_reset();' --path=/usr/local/lsws/$NAME/html --allow-root >/dev/null 2>&1 #xoá opcache_reset

  if [[ $(/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp db prefix --allow-root --path=$path 2>/dev/null) == "$tien_to_cu" ]]; then
    _runloi "$thay_doi $tien_to website $NAME từ $tien_to_cu thành ${ramdom_db}_"
  else
    _rundone "$thay_doi $tien_to website $NAME từ $tien_to_cu thành ${ramdom_db}_"
  fi

  echo "Thay đổi tiền tố website $NAME: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

  if [[ $lock_down ]]; then
    chattr +i /usr/local/lsws/"$NAME"/html/wp-config.php
  fi

fi

# tien_to_cu=$(wp db prefix --allow-root --path=$path 2>/dev/null)
# read -p "Xác nhận thay đổi tiền tố database cho website $NAME từ $tien_to_cu thành ${ramdom_db}_ (y/n): " dongyluon
# if [[ "$dongyluon" = "y" ]];then
# 	_runing "Thay dổi tiền tố database cho website $NAME"
# tien_to_moi=$(wp db prefix --allow-root --path=$path 2>/dev/null)
# if [[ $tien_to_moi != $tien_to_cu ]];then
# 	_rundone "Thay dổi tiền tố database cho website $NAME"
# else
# 	_runloi "Thay dổi tiền tố database cho website $NAME"
# fi
# fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi
