#!/bin/bash

function huong_dan() {
  Tối ưu hoá toàn bộ database trong hệ thống
  OPTIMIZE TABLE: Giải Pháp Tối Ưu Hóa Không Gian và Hiệu Suất Cơ Sở Dữ Liệu
  Mục đích chính của OPTIMIZE TABLE:

  * Giảm không gian lưu trữ: Sau nhiều thao tác chèn, cập nhật hoặc xóa dữ liệu, các bảng có thể bị phân mảnh hoặc chứa nhiều không gian không được sử dụng. OPTIMIZE TABLE giúp thu hồi lại không gian thừa này.
  * Cải thiện hiệu quả I/O: Bằng cách chống phân mảnh dữ liệu và chỉ mục, lệnh này giúp giảm thiểu số lượng thao tác đọc/ghi [I/O] cần thiết khi truy cập bảng, từ đó tăng tốc độ truy vấn.
  Cập nhật thống kê chỉ mục: OPTIMIZE TABLE thường cập nhật các thông tin thống kê về chỉ mục, giúp bộ tối ưu hóa truy vấn của DBMS đưa ra các kế hoạch thực thi hiệu quả hơn.
}

if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/echo-color
tinh_nang_ten="$toi_uu database"

echo -e "${C_CYAN}╭───────────────────────────────────────────────────────────────────────╮${C_RESET}"
center_text "${C_BOLD_WHITE}$quan_ly_wordpress ➜ $tinh_nang_ten${C_RESET}"
echo -e "${C_CYAN}╰───────────────────────────────────────────────────────────────────────╯${C_RESET}\n"

NAME=$1
if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ $NAME = "" ]]; then
  . /etc/wptt/tenmien-them-lua-chon-tat-ca-website-by-wordpress
  lua_chon_NAME "$tinh_nang_ten"
fi

. /etc/wptt/core-functions
if [[ "$1" == '98' ]]; then
  WPTT_IN_MENU="yes"
  WPTT_MENU_BACK="/etc/wptt/wptt-db-main 1"
fi

wptt_check_mariadb || wptt_die "MariaDB đang bị sập! Hệ thống từ chối không cho phép tối ưu database."

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  exec /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  exec /etc/wptt/wptt-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  exec /etc/wptt/wptt-wordpress-main 1
  exit
fi

echo "Tối ưu hoá database : $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log
. /etc/wptt/php/php-cli-domain-config $NAME
. /etc/wptt/vhost/.$NAME.conf

path="/usr/local/lsws/$NAME/html"
_runing "Tối ưu database cho website $NAME"
sudo -u "$User_name_vhost" /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp db optimize --path="$path" --allow-root
_rundone "Tối ưu database cho website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  exec /etc/wptt/wptt-wordpress-main 1
fi
