#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Xoa transient database                            |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website wordpress muon xoa transient database: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
    echoDo "Domain khong ton tai tren VPS."
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi


pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

path="/usr/local/lsws/$NAME/html"
echo "Dang tien hanh xoa transient database cho website $NAME"
wp transient delete --all --path="$path" --allow-root
echo "Hoan tat xoa transient wordpress"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-wordpress-main 1
fi

