#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Update themes WordPress                           |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "lua chon website wordpress muon update themes: "
echo ""
lua_chon_NAME
. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
    echoDo "Domain khong ton tai tren VPS."
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

path="/usr/local/lsws/$NAME/html"
echo "Dang tien hanh cap nhat theme cho website $NAME"
wp theme update --all --path="$path" --allow-root
wp cache flush --path="$path" --allow-root
wp rewrite flush --path="$path" --allow-root
echo "hoan tat"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-wordpress-main 1
fi

