#!/bin/bash
 . /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/echo-color
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_wordpress => $cap_nhat Plugins WordPress                      |"
echo "========================================================================="

 
NAME=$1
if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ $NAME = "" ]];then
 . /etc/wptt/tenmien-them-lua-chon-tat-ca-website-by-wordpress
 echo ""
 echo ""
 echo "$lua_chon_website_ban_muon $cap_nhat plugins: "
 echo ""
 lua_chon_NAME
fi


if [[ $NAME = 'Tất cả website' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			unset path path_html
			path="/usr/local/lsws/$domain/html/wp-config.php"
			path_html="/usr/local/lsws/$domain/html"
			i=1
			if [[ -f "$path" ]]; then
				_runing "$cap_nhat plugins website $domain"
				. /etc/wptt/wordpress/update-plugin $domain >/dev/null 2>&1
				_rundone "$cap_nhat plugins website $domain"
			fi
		done
	fi

	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-wordpress-main 1
	fi
	exit
fi


 if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

 
pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
 if [[ ! -f "$pathcheckwp" ]]; then
   clear
   echo "He thong xac nhan ban chua kich hoat su dung WordPress"
   sleep 3
   . /etc/wptt/wptt-wordpress-main 1
   exit
 fi
 
 
 path="/usr/local/lsws/$NAME/html"
_runing "$cap_nhat plugins website $domain"
 wp plugin update --all --path="$path" --allow-root >/dev/null 2>&1
 wp cache flush --path="$path" --allow-root >/dev/null 2>&1
 . /etc/wptt/wptt-phan-quyen2 $NAME >/dev/null 2>&1
 wp rewrite flush --path="$path" --allow-root >/dev/null 2>&1
 _rundone "$cap_nhat plugins website $domain"
 
 check_menu_wptangtoc_active=$1
 if [[ $check_menu_wptangtoc_active = "98" ]];then
 . /etc/wptt/wptt-wordpress-main 1
 fi
