#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/echo-color
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_cap_nhat_wordpress => $cap_nhat WordPress ALL             |"
echo "========================================================================="
echo "update tất cả core WordPress + plugin + themes cho tất cả các website tại hệ thống này?"
prompt="$nhap_lua_chon_cua_ban [1-2]: "
dongy="n"
options=("$dong_y" "$khong_dong_y")
PS3="$prompt"
select opt in "${options[@]}"; do
  case "$REPLY" in
  1)
    dongy="y"
    break
    ;;

  2)
    dongy="n"
    break
    ;;

  $((${#options[@]} + 1)))
    printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
    break
    ;;
  *)
    printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
    break
    ;;
  esac
done

if [[ "$dongy" = 'y' ]]; then
  if [ "$(ls -At /etc/wptt/vhost)" ]; then
    i=1
    for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
      NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      path="/usr/local/lsws/$NAME/html"
      if [[ -f $path/wp-load.php ]]; then
        . /etc/wptt/php/php-cli-domain-config $NAME
        echo "Đang tiến hành cập nhật cho $NAME"
        /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp plugin update --all --path="$path" --allow-root
        /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp theme update --all --path="$path" --allow-root
        /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp language core update --path="$path" --allow-root
        /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp language plugin update --all --path="$path" --allow-root
        /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp language theme update --all --path="$path" --allow-root
        /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp core update --path="$path" --allow-root
        /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp core update-db --path="$path" --allow-root
        /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp cache flush --path="$path" --allow-root
        /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp rewrite flush --path="$path" --allow-root
      fi
    done
  fi
fi
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wordpress/wptt-update-wordpress-main 1
fi
