#!/bin/bash

function huong_dan() {
  Tính năng cập nhật theme WordPress là một chức năng cho phép người dùng dễ dàng nâng cấp giao diện [theme] website của họ lên phiên bản mới nhất do nhà phát triển theme cung cấp.

  Tại sao cần cập nhật theme [lợi ích chính]:
  * Bảo mật: Đây là lý do quan trọng nhất. Các bản cập nhật theme thường xuyên vá các lỗ hổng bảo mật được phát hiện. Việc không cập nhật có thể khiến website của bạn dễ bị tấn công.
  * Thêm Tính năng Mới: Nhà phát triển thường bổ sung các tính năng, tùy chọn tùy chỉnh, hoặc cải tiến thiết kế trong các phiên bản mới, giúp website của bạn hiện đại và tiện dụng hơn.
  * Sửa lỗi [Bug Fixes]: Các phiên bản cập nhật sửa các lỗi đã biết từ phiên bản trước, giúp theme hoạt động ổn định và mượt mà hơn.
  * Đảm bảo Tương thích: Giúp theme tương thích tốt hơn với phiên bản WordPress mới nhất cũng như các plugin khác, tránh xung đột và lỗi không mong muốn.

  Tính năng cập nhật theme WordPress là một phần thiết yếu để duy trì một website an toàn, ổn định, và hiện đại. Việc thường xuyên kiểm tra và áp dụng các bản cập nhật là một thói quen tốt cho mọi chủ sở hữu website WordPress.
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/echo-color
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_cap_nhat_wordpress => $cap_nhat themes WordPress             |"
echo "========================================================================="

NAME=$1
if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ $NAME = "" ]]; then
  . /etc/wptt/tenmien-them-lua-chon-tat-ca-website-by-wordpress
  echo ""
  echo ""
  echo "$lua_chon_website_ban_muon $cap_nhat themes: "
  echo ""
  lua_chon_NAME
fi

if [[ $NAME = 'Tất cả website' ]]; then
  if [ "$(ls -A /etc/wptt/vhost | sort -uV)" ]; then
    for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
      domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      unset path path_html
      path="/usr/local/lsws/$domain/html/wp-load.php"
      path_html="/usr/local/lsws/$domain/html"
      i=1
      if [ "$domain" != "${domain/./}" ] && [ "$domain" != '.' ]; then #điều kiện domain phải có dấu . và lỗi chỉ có only .
        if [[ -f "$path" ]]; then
          _runing "$cap_nhat themes website $domain"
          (/etc/wptt/wordpress/update-theme $domain >/dev/null 2>&1)
          _rundone "$cap_nhat themes website $domain"
        fi
      fi
    done
  fi

  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
  fi
  exit
fi

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wordpress/wptt-update-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . /etc/wptt/wordpress/wptt-update-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt/wordpress/wptt-update-wordpress-main 1
  exit
fi

path="/usr/local/lsws/$NAME/html"
echo "Thông tin cập nhật plugin website $NAME"
. /etc/wptt/php/php-cli-domain-config $NAME

/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp theme list --fields=name,version,update_version --allow-root --path=$path 2>/dev/null

_runing "$cap_nhat Themes website $domain"
/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp theme update --all --path="$path" --allow-root >/dev/null 2>&1
/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp language theme update --all --path="$path" --allow-root >/dev/null 2>&1
. /etc/wptt/cache/wptt-xoacache $NAME >/dev/null 2>&1
_rundone "$cap_nhat Themes website $domain"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wordpress/wptt-update-wordpress-main 1
fi
