#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025
# @email: giatuan@wptangtoc.com

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

function huong_dan() {
  Tính năng Multisite [đa trang web] là một chức năng mạnh mẽ được tích hợp sẵn trong WordPress, cho phép bạn tạo và quản lý một mạng lưới nhiều website khác nhau từ một lần cài đặt WordPress duy nhất.

  🎯 Mục đích sử dụng phổ biến:
  * Tạo một mạng lưới blog cá nhân.
  * Các trường đại học, tổ chức cung cấp website cho các khoa, phòng ban, hoặc dự án.
  * Doanh nghiệp có nhiều chi nhánh hoặc thương hiệu con muốn có website riêng nhưng quản lý tập trung.
  * Cung cấp nền tảng cho người dùng tự tạo website [tương tự WordPress.com].

  Tính năng thiết lập multisite WordPress bạn có thể dễ dàng thiết lập multisite
  Với dạng: subdomain hoặc subfolder
}

domain=$1
chuyen_web=$2
if [[ $domain = "98" ]]; then
  domain=""
fi

if [[ "$domain" = "" ]]; then
  echo ""
  echo ""
  echo ""
  echo "========================================================================="
  echo "|$quan_ly_wordpress => Thiet lap WordPress Multisite                      |"
  echo "========================================================================="
  . /etc/wptt/tenmien
  echo ""
  echo ""
  echo "$lua_chon_website_ban_muon thiet lap WordPress multisite: "
  echo ""
  lua_chon_NAME
  domain="$NAME"
fi

path="/etc/wptt/vhost/.$domain.conf"
if [[ ! -f "$path" ]]; then
  clear
  echo "Domain khong ton tai tren VPS, vui long them website"
  echo
  return 2>/dev/null
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-config.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban khong su dung ma nguon WordPress"
  sleep 3
  if [[ $2 = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
  fi
  return 2>/dev/null
  exit
fi

. /etc/wptt/echo-color

. /etc/wptt/vhost/."$domain".conf
. /etc/wptt/.wptt.conf

kiemtra_multisite=$(cat /usr/local/lsws/$NAME/html/wp-config.php | grep SUBDOMAIN_INSTALL | cut -f1 -d')' | cut -f2 -d ',' | sed 's/ //g')

if [[ $kiemtra_multisite = 'true' ]]; then
  echo "He thong da kiem tra website WordPress $NAME dang su dung multisite subdomain"
  multisite_tuy_chon="1"
fi

if [[ $kiemtra_multisite = 'false' ]]; then
  echo "He thong da kiem tra website WordPress $NAME dang su dung multisite Sub-directory"
  multisite_tuy_chon="2"
fi

if [[ $kiemtra_multisite = "" ]]; then
  if [[ $2 ]]; then
    return 2>/dev/null
    exit
  fi
  echo "Tien Hanh thiet lap WordPress multisite cho website $NAME"
fi

if [[ $kiemtra_multisite = "" ]]; then
  echo "Ban hay lua chon thiet lap Multisite nhu the nao: "
  prompt="Nhap vao lua chon cua ban [1-3]: "
  multisite_tuy_chon="3"
  options=("Multisite Subdomain" "Multisite Sub-directory" "Khong Su dung Multisite")
  PS3="$prompt"
  select opt in "${options[@]}"; do

    case "$REPLY" in
    1)
      multisite_tuy_chon="1"
      break
      ;;
    2)
      multisite_tuy_chon="2"
      break
      ;;

    3)
      multisite_tuy_chon="3"
      break
      ;;

    $((${#options[@]} + 1)))
      printf "\nHe thong se khong cai multisite\n"
      break
      ;;
    *)
      printf "Ban nhap sai, Khong cai multisite\n"
      break
      ;;
    esac

  done

fi

if [[ $multisite_tuy_chon = "3" || $multisite_tuy_chon = "" || $multisite_tuy_chon = "0" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

# check_mulsite_dang_su_dung=$(wp site list --allow-root 2>/dev/null --path=/usr/local/lsws/$NAME/html)
# if [[ $check_mulsite_dang_su_dung ]];then
# echo "Ban da thiet lap multisite truoc do roi"
# exit
# fi

. /etc/wptt/php/php-cli-domain-config $NAME

wp_config="/usr/local/lsws/$NAME/html/wp-config.php"

if [[ $multisite_tuy_chon = "2" ]]; then
  _runing "Thiết lập WordPress Mutisite Sub-directory"
  if [[ $2 = "" ]]; then
    kich_hoat_multisite_wp=$(/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp core multisite-convert --allow-root --path=/usr/local/lsws/$NAME/html 2>/dev/null)
  fi
  clear
  check_htaccess=$(cat /usr/local/lsws/$NAME/html/.htaccess | grep 'multisite')
  if [[ $check_htaccess = "" ]]; then
    sed '1 i ### thiet lap multisite ###\
RewriteEngine On\
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]\
RewriteBase \/\
RewriteRule ^index\.php$ - [L]\

RewriteRule ^([_0-9a-zA-Z-]+\/)?wp-admin$ $1wp-admin\/ [R=301,L]\

RewriteCond %{REQUEST_FILENAME} -f [OR]\
RewriteCond %{REQUEST_FILENAME} -d\
RewriteRule ^ - [L]\
RewriteRule ^([_0-9a-zA-Z-]+\/)?(wp-(content|admin|includes).*) $2 [L]\
RewriteRule ^([_0-9a-zA-Z-]+\/)?(.*\.php)$ $2 [L]\
RewriteRule . index.php [L]' /usr/local/lsws/$NAME/html/.htaccess
  fi
  _rundone "Thiết lập WordPress Mutisite Sub-directory"
fi

if [[ $multisite_tuy_chon = "1" ]]; then
  _runing "Thiết lập WordPress Multisite sub-domain"
  if [[ $2 = "" ]]; then
    kich_hoat_multisite_wp=$(/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp core multisite-convert --subdomains --allow-root --path=/usr/local/lsws/$NAME/html >/dev/null 2>&1)
  fi
  check_sub_all=$(cat /usr/local/lsws/conf/httpd_config.conf | grep "*.$NAME")
  if [[ $check_sub_all = "" ]]; then
    sed -i "s/$NAME $NAME/&, *.$NAME/g" /usr/local/lsws/conf/httpd_config.conf
  fi

  check_htaccess=$(cat /usr/local/lsws/$NAME/html/.htaccess | grep 'multisite')
  if [[ $check_htaccess = "" ]]; then
    sed -i '1 i ### thiet lap multisite ###\
RewriteEngine On\
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]\
RewriteBase \/\
RewriteRule ^index\.php$ - [L]\

RewriteRule ^wp-admin$ wp-admin\/ [R=301,L]\

RewriteCond %{REQUEST_FILENAME} -f [OR]\
RewriteCond %{REQUEST_FILENAME} -d\
RewriteRule ^ - [L]\
RewriteRule ^(wp-(content|admin|includes).*) $1 [L]\
RewriteRule ^(.*\.php)$ $1 [L]\
RewriteRule . index.php [L]' /usr/local/lsws/$NAME/html/.htaccess
  fi
  _rundone "Thiết lập WordPress Multisite sub-domain"
  checkdns=$(host giatuandz.$NAME | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
  if [[ "$checkdns" = "" ]]; then
    checkdns=$(nslookup giatuandz.$NAME | grep Address | cut -f5 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
  fi

  if [[ $checkdns = "" ]]; then
    ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')

    echo "Vui long tro dns Wildcard DNS cua domain $NAME de co the su dung multisite sub-domain"
    echo "Tro type = A --- Name = * --- = content $ip"
  fi

fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi
