#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Thiet lap WordPress Mutisite                      |"
echo "========================================================================="
domain=$1
if [[ "$domain" = "" ]]; then
  . /etc/wptt/tenmien
  echo ""
  echo ""
  echo "Lua chon ten website thiet lap WordPress multisite: "
  echo ""
  lua_chon_NAME
  domain="$NAME"
fi

path="/etc/wptt/vhost/.$domain.conf"
if [[ ! -f "$path" ]]; then
  clear
  echo "Domain khong ton tai tren VPS, vui long them website"
  echo
  exit
fi


pathcheckwp="/usr/local/lsws/$NAME/html/wp-config.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban khong su dung ma nguon WordPress"
  sleep 3
  . /etc/wptt/wptt-menu-wordpress
  exit
fi


. /etc/wptt/vhost/."$domain".conf
. /etc/wptt/.wptt.conf


echo "Ban hay lua chon thiet lap Mutisite nhu the nao: "
prompt="Nhap vao lua chon cua ban [1-3]: "
multisite_tuy_chon="3"
options=("Mutisite Subdomain" "Mutisite Sub-directory" "Khong Su dung Mutisite")
PS3="$prompt"
select opt in "${options[@]}"; do

  case "$REPLY" in
  1)
    multisite_tuy_chon="1"
    break
    ;;
  2)
    multisite_tuy_chon="2"
    break
    ;;

  3)
    multisite_tuy_chon="3"
    break
    ;;

  $((${#options[@]} + 1)))
    printf "\nHe thong se khong cai multisite\n"
    break
    ;;
  *)
    printf "Ban nhap sai, Khong cai multisite\n"
    break
    ;;
  esac

done

if [[ $multisite_tuy_chon = "3" ]];then
  sleep 3
  . /etc/wptt/wptt-menu-wordpress
  exit
fi

# check_mulsite_dang_su_dung=$(wp site list --allow-root 2>/dev/null --path=/usr/local/lsws/$NAME/html)
# if [[ $check_mulsite_dang_su_dung ]];then
# echo "Ban da thiet lap multisite truoc do roi"
# exit
# fi

wp_config="/usr/local/lsws/$NAME/html/wp-config.php"
check=$(cat /usr/local/lsws/$NAME/html/wp-config.php | grep 'WP_ALLOW_MULTISITE')
if [[ $check = "" ]];then
echo "Tien Hanh thiet lap WordPress Mutisite"
sed -i "/WP_ALLOW_MULTISITE/d" "$wp_config"
sed -i "/<?php/a define( 'WP_ALLOW_MULTISITE', true );" "$wp_config"
fi


if [[ $multisite_tuy_chon = "3" ]];then
echo "Tien hanh thiet lap WordPress Mutisite Sub-directory"
sed -i "/WP_ALLOW_MULTISITE/d" "$wp_config"
sed -i "/MULTISITE/d" "$wp_config"
sed -i "/SUBDOMAIN_INSTALL/d" "$wp_config"
sed -i "/DOMAIN_CURRENT_SITE/d" "$wp_config"
sed -i "/PATH_CURRENT_SITE/d" "$wp_config"
sed -i "/SITE_ID_CURRENT_SITE/d" "$wp_config"
sed -i "/BLOG_ID_CURRENT_SITE/d" "$wp_config"


sed -i "/<?php/a define( 'WP_ALLOW_MULTISITE', true );" "$wp_config"
sed -i "/<?php/a define( 'MULTISITE', true );" "$wp_config"
sed -i "/<?php/a define( 'SUBDOMAIN_INSTALL', false );" "$wp_config"
sed -i "/<?php/a define( 'DOMAIN_CURRENT_SITE', '$NAME' );" "$wp_config"
sed -i "/<?php/a define( 'PATH_CURRENT_SITE', '/' );" "$wp_config"
sed -i "/<?php/a define( 'SITE_ID_CURRENT_SITE', 1 );" "$wp_config"
sed -i "/<?php/a define( 'BLOG_ID_CURRENT_SITE', 1 );" "$wp_config"

sed '1 i RewriteEngine On\
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]\
RewriteBase \/\
RewriteRule ^index\.php$ - [L]\

RewriteRule ^([_0-9a-zA-Z-]+\/)?wp-admin$ $1wp-admin\/ [R=301,L]\

RewriteCond %{REQUEST_FILENAME} -f [OR]\
RewriteCond %{REQUEST_FILENAME} -d\
RewriteRule ^ - [L]\
RewriteRule ^([_0-9a-zA-Z-]+\/)?(wp-(content|admin|includes).*) $2 [L]\
RewriteRule ^([_0-9a-zA-Z-]+\/)?(.*\.php)$ $2 [L]\
RewriteRule . index.php [L]' /usr/local/lsws/$NAME/html/.htaccess
fi


if [[ $multisite_tuy_chon = "2" ]];then
	check_sub_all=$(cat /usr/local/lsws/conf/httpd_config.conf | grep "*.$NAME" )
	if [[ $check_sub_all = "" ]];then
sed -i "s/$NAME $NAME/&, *.$NAME/g" /usr/local/lsws/conf/httpd_config.conf
	fi

echo "Tien hanh thiet lap WordPress Mutisite Sub-domain"
sed -i "/WP_ALLOW_MULTISITE/d" "$wp_config"
sed -i "/MULTISITE/d" "$wp_config"
sed -i "/SUBDOMAIN_INSTALL/d" "$wp_config"
sed -i "/DOMAIN_CURRENT_SITE/d" "$wp_config"
sed -i "/PATH_CURRENT_SITE/d" "$wp_config"
sed -i "/SITE_ID_CURRENT_SITE/d" "$wp_config"
sed -i "/BLOG_ID_CURRENT_SITE/d" "$wp_config"


sed -i "/<?php/a define( 'WP_ALLOW_MULTISITE', true );" "$wp_config"
sed -i "/<?php/a define( 'MULTISITE', true );" "$wp_config"
sed -i "/<?php/a define( 'SUBDOMAIN_INSTALL', true );" "$wp_config"
sed -i "/<?php/a define( 'DOMAIN_CURRENT_SITE', '$NAME' );" "$wp_config"
sed -i "/<?php/a define( 'PATH_CURRENT_SITE', '/' );" "$wp_config"
sed -i "/<?php/a define( 'SITE_ID_CURRENT_SITE', 1 );" "$wp_config"
sed -i "/<?php/a define( 'BLOG_ID_CURRENT_SITE', 1 );" "$wp_config"

checkdns=$(host giatuandz.$NAME | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
if [[ "$checkdns" = "" ]]; then
    checkdns=$(nslookup giatuandz.$NAME | grep Address | cut -f5 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
fi

if [[ $checkdns = "" ]];then
ip=$(curl -s myip.directadmin.com)
	if [[ "$ip" = "" ]]; then
    ip=$(curl -s ifconfig.me)
	fi
echo "Vui long tro dns Wildcard DNS cua domain $NAME de co the su dung multisite sub-domain"
echo "Tro type = A --- Name = * --- = content $ip"
fi

sed -i '1 i RewriteEngine On\
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]\
RewriteBase \/\
RewriteRule ^index\.php$ - [L]\

RewriteRule ^wp-admin$ wp-admin\/ [R=301,L]\

RewriteCond %{REQUEST_FILENAME} -f [OR]\
RewriteCond %{REQUEST_FILENAME} -d\
RewriteRule ^ - [L]\
RewriteRule ^(wp-(content|admin|includes).*) $1 [L]\
RewriteRule ^(.*\.php)$ $1 [L]\
RewriteRule . index.php [L]' /usr/local/lsws/$NAME/html/.htaccess
fi
