#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Tắt wp debug                                      |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/echo-color
NAME=$1
if [[ $NAME = "98" ]];then
NAME=""
fi
if [[ $NAME = "" ]];then
. /etc/wptt/tenmien-them-lua-chon-tat-ca-website
echo "Lựa chọn website bạn muốn tắt wp debug: "
echo ""
lua_chon_NAME
fi

. /etc/wptt/echo-color


if [[ $NAME = 'Tất cả website' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path="/usr/local/lsws/$domain/html/wp-config.php"
			path_html="/usr/local/lsws/$domain/html"
			i=1
			if [[ -f "$path" ]]; then
				_runing "Tắt wp debug website $domain"
				. /etc/wptt/wordpress/wp-debug $domain >/dev/null 2>&1
				_rundone "Tắt wp debug website $domain"
			fi
		done
	fi

	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
    . /etc/wptt/wptt-wordpress-main 1
	fi
	exit
fi


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

_runing "Thiết lập tắt WP-debug website $NAME"

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
_runloi "Thiết lập tắt WP-debug website $NAME"
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

wp_config="/usr/local/lsws/$NAME/html/wp-config.php"

if [[ $check_if ]];then
sed -i '/WP_DEBUG/,+2d' $wp_config
fi

sed -i "/WP_DEBUG/d" "$wp_config"
sed -i "/WP_DEBUG_LOG/d" "$wp_config"
sed -i "/WP_DEBUG_DISPLAY/d" "$wp_config"
sed -i "/<?php/a define( 'WP_DEBUG', false );" "$wp_config"
sed -i "/<?php/a define( 'WP_DEBUG_LOG', false );" "$wp_config"
sed -i "/<?php/a define( 'WP_DEBUG_DISPLAY', false );" "$wp_config"

if [[ -f /usr/local/lsws/$NAME/html/wp-content/debug.log ]];then
	rm -f /usr/local/lsws/$NAME/html/wp-content/debug.log
fi

_rundone "Thiết lập tắt WP-debug website $NAME"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-wordpress-main 1
fi

