#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Regenerate tai tao lai Thumbnails                 |"
echo "========================================================================="

. /etc/wptt/tenmien
echo ""
echo ""
echo "lua chon website bam muon Regenerate tai tao lai Thumbnails"
echo ""
lua_chon_NAME

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-menu-wordpress
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt/wptt-menu-wordpress
  exit
fi


prompt="Nhap vao lua chon cua ban [1-2]: "
render_thumbnail="2"
options=("Tai tao lai tat ca thumbnail" "chi tai tao thumbnail con thieu")
PS3="$prompt"
select opt in "${options[@]}"; do
    case "$REPLY" in
    1)
        render_thumbnail="1"
        break
        ;;
    2)
        render_thumbnail="2"
        break
        ;;
    $((${#options[@]} + 1)))
        printf "\nse tai tao thumbnail cai con thieu\n"
        break
        ;;
    *) wptangtoc ;;
    esac
done

path="/usr/local/lsws/$NAME/html"
if [[ "$render_thumbnail" = "1" ]]; then
    wp media regenerate --yes --path=$path --allow-root
    echo "Da hoan Regenerate tai tao thumbnail cho website $NAME"
else
    wp media regenerate --only-missing --path=$path --allow-root
    echo "Da hoan Regenerate tai tao thumbnail cho website $NAME"
fi
