#!/bin/bash

dung_luong=$1

if [[ $dung_luong = '' ]];then
read -p "Dung lượng size cache lưu vào ram (Nhập số nguyên dương): " dung_luong
fi

if [[ ! $dung_luong =~ ^-?[0-9]+$ ]]; then
echo "Nhập sai dữ liệu"
return 2>/dev/null;exit
fi

sed -i '/totalInMemCacheSize/d' /usr/local/lsws/conf/httpd_config.conf
sed -i "/maxCachedFileSize/a  	totalInMemCacheSize 	   ${dung_luong}M" /usr/local/lsws/conf/httpd_config.conf
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

