#!/bin/bash
function check_auto_chmod_chown() {
  local NAME=$1
  # local TIMESTAMP_FILE="/usr/local/lsws/$NAME/.check_chmod_chown_wptangtoc_ols_auto"
  local DOCROOT="/usr/local/lsws/$NAME/html"

  # 1. BẢO VỆ: Kiểm tra thư mục có tồn tại không trước khi find (Tránh báo lỗi rác hệ thống)
  if [[ ! -d "$DOCROOT" ]]; then
    return
  fi

  unset User_name_vhost lock_down
  . /etc/wptt/vhost/.$NAME.conf
  if [[ -n $User_name_vhost ]] && [[ -z $lock_down ]]; then                                                                                                                  #yêu cầu điều kiện có username và không dùng lockdown
    if [[ $(/usr/bin/find /usr/local/lsws/$NAME/html -maxdepth 1 ! -name "phpmyadmin" \( ! -user "$User_name_vhost" -o ! -group "$User_name_vhost" \) -print -quit) ]]; then #quét xem có phân quyền đúng thuộc sở hữu hay không và bypass phpmyadmin nó quyền nobody
      ionice -c 3 nice -n 19 /etc/wptt/wptt-phanquyen $NAME >/dev/null 2>&1
    fi
  fi
}

for filepath in /etc/wptt/vhost/.*.conf; do
  [[ ! -f "$filepath" || "$filepath" == *"/..conf" ]] && continue

  NAME="${filepath##*/}"
  NAME="${NAME%.conf}"
  NAME="${NAME#.}"

  if [[ "$NAME" == ?*.?* ]]; then
    check_auto_chmod_chown "$NAME"
  fi
done
