#!/bin/bash
  if [ "$(ls -A /etc/wptt/vhost | grep -v '^\.\.conf$' | sort -uV)" ]; then
    for entry in $(ls -A /etc/wptt/vhost | grep -v '^\.\.conf$' | sort -uV); do
      domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      path="/usr/local/lsws/$domain/html"
      i=1

      if [[ -d "$path" ]]; then
        if [[ -f /usr/local/lsws/conf/vhosts/$domain/$domain.conf ]]; then
		    sed -i '/Strict-Transport-Security/d' /usr/local/lsws/conf/vhosts/$domain/$domain.conf
            sed -i "/extraHeaders /a Strict-Transport-Security max-age=31536000; includeSubDomains; preload" /usr/local/lsws/conf/vhosts/$domain/$domain.conf #add hsts
        fi
      fi
    done
  fi
  /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
  echo 'Hoàn tất install hsts all domain'
