#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2024
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Chuyển đổi ngôn ngữ:"
echo ""
options=(
    "Tiếng Việt"                     #1
    "Tiếng Anh"                      #2
	"Tiếng Trung" #3
)
PS3="
Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"; do
    case $opt in
    "${options[0]}")
		ngon_ngu="vi"
        ;;
    "${options[1]}")
		ngon_ngu="en"
        ;;
    "${options[2]}")
		ngon_ngu="cn"
        ;;
    *) wptangtoc 1 ;;
    esac
done

sed '/ngon_ngu/d' /etc/wptt/.wptt.conf
echo "ngon_ngu=$ngon_ngu" >> /etc/wptt/.wptt.conf
echo "Hoàn tất chuyển đổi ngôn ngữ sang $ngon_ngu"
wptangtoc 1
