#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $wptangtoc_ols_giatuan ]];then
if [ "$(ls -A /etc/wptt/vhost)" ]; then
  echo
  echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
      sed -i '/X-Powered-By/d' /usr/local/lsws/conf/vhosts/$domain/$domain.conf 
	fi
  done
  echo '--------------------------------------------------'
  echo
fi
echo 'Hoàn tất'
wptt reboot-ls
fi
