#!/bin/bash
NAME=$1
if [[ -f /usr/local/lsws/$NAME/html/wp-content/clear-litespeed-wptangtoc.json ]];then


tien_trinh_pid_trung_lap_remove=$(ps -ef | grep -v grep | grep 'bash' | grep '/etc/wptt' | grep 'wptt-preload-cache.sh'| grep $NAME | awk '{print $2}' | xargs kill -9 >/dev/null 2>&1)

rm -f /usr/local/lsws/$NAME/html/wp-content/clear-litespeed-wptangtoc.json
bash /etc/wptt/wptt-preload-cache2 $NAME
fi
