#!/bin/bash

. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website search WordPress activate: "
echo ""
lua_chon_NAME
pathcheck="/etc/wptt/vhost/.$NAME.conf"

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi

if [[ ! -f /usr/bin/java ]]; then
  sudo dnf remove 'java-1.8.0-openjdk-*' -y
  dnf install java-11-openjdk-devel -y
fi

if [[ ! -f /etc/elasticsearch/elasticsearch.yml ]]; then
  echo '[elasticsearch]
name=Elasticsearch repository for 8.x packages
baseurl=https://artifacts.elastic.co/packages/8.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
' >/etc/yum.repos.d/elasticsearch.repo
  dnf install -y elasticsearch
  sudo /usr/share/elasticsearch/bin/elasticsearch-keystore remove xpack.security.transport.ssl.keystore.secure_password
  sudo /usr/share/elasticsearch/bin/elasticsearch-keystore remove xpack.security.transport.ssl.truststore.secure_password
  sudo /usr/share/elasticsearch/bin/elasticsearch-keystore remove xpack.security.http.ssl.keystore.secure_password

  echo '
xpack.security.enabled: false
network.host: 127.0.0.1
http.port: 9200
' >>/etc/elasticsearch/elasticsearch.yml
  chown -R elasticsearch:elasticsearch /var/log/elasticsearch
  # sed -i 's/-Xms1g/-Xms512m/g' /etc/elasticsearch/jvm.options
  # sed -i 's/-Xms1g/-Xms512m/g' /etc/elasticsearch/jvm.options
  # sed -i 's/-Xmx1g/-Xmx512m/g' /etc/elasticsearch/jvm.options
  sed -i '/-Xmx/d' /etc/elasticsearch/jvm.options
  echo '-Xmx512m' >>/etc/elasticsearch/jvm.options

  systemctl enable elasticsearch.service
  systemctl start elasticsearch.service

  echo "hoàn tất cài đặt elasticsearch"
fi

wp_config="/usr/local/lsws/$NAME/html/wp-config.php"

sed -i "/EP_HOST/d" "$wp_config"
sed -i "/<?php/a define( 'EP_HOST', 'http://127.0.0.1:9200' );" "$wp_config"

if [[ ! -d /usr/local/lsws/$NAME/html/wp-content/plugins/elasticpress ]]; then
  wp plugin install elasticpress --activate --path=/usr/local/lsws/$NAME/html --allow-root
  . /etc/wptt/vhost/."$NAME".conf
  chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$NAME"/html
  find /usr/local/lsws/"$NAME"/html/wp-content/plugins -type d -exec chmod 755 {} \;
  find /usr/local/lsws/"$NAME"/html/wp-content/plugins -type f -exec chmod 644 {} \;
fi

echo "Dang tien hanh index search: "
wp elasticpress index --path=/usr/local/lsws/"$NAME"/html --allow-root
