#!/bin/bash
function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//'| sed 's/_./\//g')
			if [ "$NAME" != "${NAME/./}" ]; then
				selects+=("$NAME")
			fi
		done
		PS3="
-//- Nhập lựa chọn website của bạn [0=Thoát]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
		if [[ $(echo $NAME | grep '/') ]];then
			NAME=$(echo $NAME | cut -f1 -d '/')
			subfolder=$(echo $NAME | cut f2 -d '/' | sed 's/$/\//g')
			subfolder2=$(echo $NAME | cut f2 -d '/' | sed 's/^/\//g')
		fi
	else
		clear
		echo "Không có domain nào tồn tại trên hệ thống."
		exit
	fi
}
