#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
. /etc/wptt/.wptt.conf
if [[ $1 = "" ]];then
clear
RED='\033[0;31m'
NC='\033[0m'
ols1=$(systemctl status lsws.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
mariadb1=$(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)

if [[ "$ols1" = "active" ]]; then
  ols="Hoat dong tot"
else
  echo "========================================================================="
  ols2="Webserver LiteSpeed dang bi gap su co"
  /usr/local/lsws/bin/lswsctrl restart
  echo "========================================================================="
fi

if [[ "$mariadb1" = "active" ]]; then
  mariadb="Hoat dong tot"
else
  echo "========================================================================="
  mariadb2="MariaDB Database dang bi gap su co"
  systemctl restart mariadb.service
  echo "========================================================================="
fi

echo -e "${RED}+-----------------------------------------------------------------------+"
echo "|                                                                       |"
echo "|                        WPTANGTOC OLS phien ban: $version_wptangtoc_ols			|"
echo "|                          Phat trien boi: Gia Tuan			|"
if [[ $wptangtoc_ols_giatuan = "1" ]]; then
echo "|                          WPTangToc OLS Premium                        |"
fi
if [[ $beta_wptangtoc_ols = "1" ]]; then
echo "|                          WPTangToc OLS beta                           |"
fi
echo -e "+-----------------------------------------------------------------------+ ${NC}"
echo "========================================================================="
if [[ "$ols1" = "active" && "$mariadb1" = "active" ]]; then
  hoatdong="Hoạt động tốt"
else
  hoatdong="Tình trạng máy chủ: Máy chủ đang có vấn đề, cần phải khắc phục"
  echo "$mariadb2"
  echo "$ols2"
fi
echo "Tình trạng máy chủ: $hoatdong"
echo "========================================================================="
echo ""
echo ""
else
	echo ""
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo ""
echo ""
echo "WPTangToc OLS MENU chính:"
echo ""
fi

options=(
  "Quản lý WordPress"               #1
  "Quản lý Domain"                  #2
  "Quản lý SSL"                     #3
  "Quản lý Database"                #4
  "Sao lưu & Khôi phục"             #5
  "Tải mã nguồn WordPress"          #6
  "Quản lý Service Application"     #7
  "Quản lý Mở/Khóa IP"              #8
  "Quản lý SSH/SFTP"                #9
  "Quản lý cập nhật webserver"        #10
  "Preload Cache"         #11
  "Quản lý WebGuiAdmin"             #12
  "Cấu hình Webserver"              #13
  "Quản lý PHP"                     #14
  "Quản lý logs"                    #15
  "Duplicate website"               #16
  "Quản lý mã nguồn"                #17
  "Phân quyền website"              #18
  "Quản lý Cache"          #19
  "Thông tin tài khoản webserver"   #20
  "Thông tin webserver"             #21
  "Bảo mật"                         #22
  "Cập nhật WPTangToc OLS"          #23
  "Quản lý PhpMyAdmin" #24
  "Gửi yêu cầu => Gia Tuấn"         #25
  "Quản lý swap"                    #26
  "Chuyển website về WPTangToc OLS" #27
  "Quản lý File Manager" #28
  "Quản lý tài nguyên server" #29
  "Tặng tác giả cốc bia"     #30
)
PS3="
Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"; do
  case $opt in
  "${options[0]}")
    "/etc/wptt/wptt-wordpress-main"
    ;;

  "${options[1]}")
    "/etc/wptt/wptt-domain-main"
    ;;

  "${options[2]}")
    "/etc/wptt/wptt-ssl-main"
    ;;

  "${options[3]}")
    "/etc/wptt/wptt-db-main"
    ;;

  "${options[4]}")
    "/etc/wptt/wptt-backup-restore-main"
    ;;

  "${options[5]}")
    "/etc/wptt/wptt-install-wordpress2" 99
    ;;

  "${options[6]}")
    "/etc/wptt/wptt-service-main"
    ;;

  "${options[7]}")
    "/etc/wptt/wptt-khoa-ip-main"
    ;;

  "${options[8]}")
    "/etc/wptt/wptt-ssh-main"
    ;;

  "${options[9]}")
    "/etc/wptt/wptt-update-main"
    ;;

  "${options[10]}")
    "/etc/wptt/wptt-preload-cache2" 98
    ;;

  "${options[11]}")
    "/etc/wptt/wptt-webadmin-main"
    ;;

  "${options[12]}")
    "/etc/wptt/wptt-cau-hinh-websever-main"
    ;;

  "${options[13]}")
    "/etc/wptt/wptt-php-ini-main"
    ;;
  "${options[14]}")
    "/etc/wptt/wptt-menu-logs"
    ;;

  "${options[15]}")
    "/etc/wptt/wptt-sao-chep-website" 99
    ;;

  "${options[16]}")
    "/etc/wptt/wptt-ma-nguon-main"
    ;;

  "${options[17]}")
    "/etc/wptt/wptt-phan-quyen-all" 99
    ;;

  "${options[18]}")
    "/etc/wptt/wptt-cache-main"
    ;;

  "${options[19]}")
    "/etc/wptt/wptt-kiemtra2" 98
    ;;

  "${options[20]}")
    "/etc/wptt/wptt-kiemtra" 98
    ;;

  "${options[21]}")
    "/etc/wptt/wptt-bao-mat-main"
    ;;

  "${options[22]}")
    "/etc/wptt/wptt-update" 97
    ;;

  "${options[23]}")
    "/etc/wptt/wptt-phpmyadmin-main"
    ;;

  "${options[24]}")
    "/etc/wptt/wptt-feedback" 98
    ;;

  "${options[25]}")
    "/etc/wptt/wptt-swap-main"
    ;;

  "${options[26]}")
    "/etc/wptt/wptt-chuyen-web-main"
    ;;

  "${options[27]}")
	"/etc/wptt/wptt-quan-ly-files-main"
    ;;

  "${options[28]}")
	"/etc/wptt/wptt-tai-nguyen-main" 98
    ;;

  "${options[29]}")
	"/etc/wptt/wptt-donate" 98
    ;;

  *) wptt status && ps -ef | grep 'bash' | grep '/etc/wptt\|/bin/wptangtoc' | grep -v grep | grep -v 'preload'| grep -v 'status' | awk '{print $2}' | xargs kill -9| echo 'Hoàn tất thoát menu WPTangToc OLS' | tr -s '\n' ' ' ;;
  esac
done
