#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Quan ly phpmyadmin:"
echo ""
options=(
    "Kich hoat phpmyadmin"                       #1
    "Huy kich hoat phpmyadmin"                     #2
    "Xem thong tin dang nhap phpmyadmin"            #3
    "Thay doi ID va Password dang nhap"              #4
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/phpmyadmin/wptt-mo-phpmyadmin" 98
        ;;
    "${options[1]}")
        "/etc/wptt/phpmyadmin/wptt-xoa-phpmyadmin" 98
        ;;
    "${options[2]}")
        "/etc/wptt/phpmyadmin/wptt-thongtin-phpmyadmin" 98
        ;;

    "${options[3]}")
        "/etc/wptt/phpmyadmin/wptt-phpmyadmin-doi-password" 98
        ;;

    *) wptangtoc ;;
    esac
done
