#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Giả lập:"
echo ""
options=(
    "Giả lập từ một website nào đó trong hệ thống này"                     #1
    "Giả lập từ WordPress mới trắng"                      #2
    "Chuyển website giả lập vào website chính"                      #3
)
PS3="
Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"; do
    case $opt in
    "${options[0]}")
        "/etc/wptt/gia-lap-website/gia-lap-website-co-du-lieu" 98
        ;;
    "${options[1]}")
        "/etc/wptt/gia-lap-website/gia-lap-website-wordpress-moi-hoan-toan" 98
        ;;
    "${options[2]}")
        "/etc/wptt/gia-lap-website/gia-lap-website-dua-vao-website-chinh" 98
        ;;
    *) wptangtoc 1 ;;
    esac
done
