#!/bin/bash
. /etc/wptt/.wptt.conf
echo "-------------------------------------------------------------------------"
echo "Chuyen toan bo VPS"
echo "-------------------------------------------------------------------------"
echo "Yeu cau vps moi cua ban phai cung chay he dieu hanh centos 7"
echo "ban truy cap vps moi cua ban go: yum install rsync -y"
echo "roi quay lai lam buoc tiep theo"
read -p "Xac nhan chuyen vps (y/n): " dongy
if [[ "$dongy" != "y" ]]; then
    exit
    wptangtoc
fi
if [[ "$dongy" = "y" ]]; then
    if [[ ! -f '/usr/bin/rsync' ]]; then
        yum install rsync -y
    fi
    read -p "Nhap Ip vps ban muon chuyen vao: " ip
    read -p "Nhap port ssh vps moi muon chuyen vao" portcheck
    if [[ ! $port =~ ^-?[0-9]+$ ]]; then
        portcheck="22"
    fi

    if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "yeu cau password tai khoan root vps moi cua ban"
        rsync -avpogtStlHz -e "ssh -p $portcheck " --numeric-ids --exclude=/etc/fstab --exclude=/etc/network/* --exclude=/proc/* --exclude=/tmp/* --exclude=/sys/* --exclude=/dev/* --exclude=/mnt/* --exclude=/boot/* --exclude=/root/* / root@$ip:/
        echo "Buoc tiep theo ban go cai nay vao vps moi: curl -sO https://wptangtoc.com/share/chuyen-vps && bash chuyen-vps"
        echo "nhu vay la xong roi ban cho dns vao vps moi va tan huong thanh qua nhe"
    fi
fi
