#!/bin/bash
. /etc/wptt/.wptt.conf
phpcheck222=$(php -v | grep cli | cut -c 1-10)
    php=$(php -i | grep php.ini | grep Loaded | cut -c 30-80)
    sed -i "/memory_limit/d" "$php"
    sed -i "/memory-limit/a memory_limit = 256M" "$php"

    sed -i "/max_input_time/d" "$php"
    sed -i "/max-input-time/a max_input_time = 120" "$php"

	sed -i '/opcache.memory_consumption/d' "$php"
	sed -i '/opcache.max_accelerated_files/d' "$php"
echo 'opcache.memory_consumption=256
opcache.max_accelerated_files=20000
' >> "$php"

	if [[ -f /etc/redis.conf ]];then
sed -i 's/128mb/256mb/g' /etc/redis.conf
systemctl restart redis.service
	fi
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
	echo "hoan tat cau hinh"
