#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Quản lý PhpMyAdmin:"
echo ""
options=(
	"Kích hoạt PhpMyAdmin"                       #1
	"Hủy kích hoạt PhpMyAdmin"                     #2
	"Xem thông tin đăng nhập PhpMyAdmin"            #3
	"Thay đổi ID va Password đăng nhập"              #4
	"Cập nhật PhpMyAdmin"              #5
)
PS3="
Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/phpmyadmin/wptt-mo-phpmyadmin" 98
        ;;
    "${options[1]}")
        "/etc/wptt/phpmyadmin/wptt-xoa-phpmyadmin" 98
        ;;
    "${options[2]}")
        "/etc/wptt/phpmyadmin/wptt-thongtin-phpmyadmin" 98
		;;

	"${options[3]}")
		"/etc/wptt/phpmyadmin/wptt-phpmyadmin-doi-password" 98
		;;

	"${options[4]}")
		"/etc/wptt/update/wptt-update-phpmyadmin" 97
		;;


    *) wptangtoc 1 ;;
    esac
done
