#!/bin/bash
if [ "$(ls -A /etc/wptt/vhost)" ]; then
  echo ""
  echo ""
  echo "Đang tiến hành phân quyền toàn bộ website ..."

  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
      . /etc/wptt/wptt-phan-quyen2 $domain
    fi
  done

fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
clear

function box_out()
{
  local s=("$@") b w
  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done
  tput setaf 3
  echo " -${b//?/-}-
| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 4)" "-$w" "$l" "$(tput setaf 3)"
  done
  echo "| ${b//?/ } |
 -${b//?/-}-"
  tput sgr 0
}


echo "==================================================================="
echo "Hoàn tất phân quyền tất cả website của bạn"
echo "==================================================================="
echo "Đã phân quyền các website: "

for entry in $(ls -A /etc/wptt/vhost); do
  domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
  path="/usr/local/lsws/$domain/html"
  i=1

  if [[ -d "$path" ]]; then
    box_out "Hoàn tất phân quyền website: $domain"
  fi
done

echo "==================================================================="
echo "Phần mềm phát triển bởi	: Gia Tuấn"
echo "==================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "99" ]];then
wptangtoc 1
fi

