#!/bin/bash
. /etc/wptt/wptt-header-menu
header_menu
echo ""
echo ""
echo "Quan ly SSL:"
echo ""
options=(
    "Cai dat SSL FREE Let’s Encrypt"          #1
    "Xoa SSL FREE Let’s Encrypt"              #2
    "Gia han thu cong SSL FREE Let’s Encrypt" #3
    "Thiet lap SSL Tra phi"                   #4
    "Xoa SSL Tra phi"                         #5
    "Kiem tra chung chi SSL"                  #6
    "Renew chuyen huong HTTPS"                #7
)

PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/ssl/wptt-caissl"
        ;;
    "${options[1]}")
        "/etc/wptt/ssl/wptt-xoa-ssl"
        ;;

    "${options[2]}")
        "/etc/wptt/ssl/wptt-gia-han-ssl"
        ;;

    "${options[3]}")
        "/etc/wptt/ssl/wptt-caissl-traphi"
        ;;

    "${options[4]}")
        "/etc/wptt/ssl/wptt-caissl-traphi-xoa"
        ;;

    "${options[5]}")
        "/etc/wptt/ssl/wptt-kiem-tra-ssl"
        ;;

    "${options[6]}")
        "/etc/wptt/ssl/wptt-renew-chuyen-huong"
        ;;
    *) wptangtoc ;;
    esac
done
