#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021

NAME=$1
if [[ "$NAME" != "" ]]; then
    if [ "$NAME" = "${NAME/./}" ]; then
        clear
        echo "Domain nhap khong dung dinh dang."
        exit
    fi
fi

if [[ "$NAME" = "" ]]; then
    echo "========================================================================="
    echo ""
    echo ""
    . /etc/wptt/tenmien
    echo "Lua chon website ban muon preload cache: "
    echo ""
    lua_chon_NAME

    pathcheck="/etc/wptt/vhost/.$NAME.conf"
    if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
        clear
        wptangtoc
        exit
    fi
fi
check="/usr/local/lsws/$NAME/html/.htaccess"
grep=$(grep -c LiteSpeed $check)
if [[ "$grep" = "" || "$grep" = "0" ]]; then
    echo "Ban chua kich hoat LScache tinh nay ban khong the su dung."
    echo "Ban quay lai su dung plugin LiteSpeed cache wordpress hoac kich hoat lscache trong menu cua WPTangToc OLS de co the su dung tinh nang nay."
    exit
fi

checkssl=$(curl -Is https://${NAME} | head -n 1 | grep -c "200")
checkssl2=$(curl -Is http://${NAME} | head -n 1 | grep -c "200")

if [[ "$checkssl" = "0" && "$checkssl2" = "0" ]]; then
    echo "He thong kiem tra website $NAME da ngung hoat dong."
    sleep 4
    wptangtoc
    exit
fi

if [[ "$checkssl" = "1" ]]; then
    ssl="https"
else
    ssl="http"
fi

echo "Dang tien hanh quet sitemap website $NAME"

grepmobile=$(grep -c Android $check)
grepwebp=$(grep -c "+webp" $check)

if [[ "$grepmobile" != "0" ]]; then
    echo "He thong xac nhan ban dang su dung cache mobile cho website $NAME"
fi

if [[ "$grepwebp" != "0" ]]; then
    echo "He thong xac nhan ban dang su dung dinh dang webp cho website $NAME"
fi

checksm=$(curl -Is ${ssl}://$NAME/sitemap.xml | head -n 1 | grep -c "200")
checksm2=$(curl -Is ${ssl}://$NAME/wp-sitemap.xml | head -n 1 | grep -c "200")
checksm3=$(curl -Is ${ssl}://$NAME/sitemap_index.xml | head -n 1 | grep -c "200")

if [[ "$checksm" = "0" && "$checksm2" = "0" && "$checksm3" = "0" ]]; then
    echo "khong xac dinh duoc sitemap cua $NAME"
    exit
fi

if [[ "$checksm" = "1" ]]; then
    NAME2="${ssl}://$NAME/sitemap.xml"
fi

if [[ "$checksm2" = "1" ]]; then
    NAME2="${ssl}://$NAME/wp-sitemap.xml"
fi

if [[ "$checksm3" = "1" ]]; then
    NAME2="${ssl}://$NAME/sitemap_index.xml"
fi

echo "Kiem tra sitemap hoan tat sitemap cua ban url la $NAME2"

tuan=$(ps -ef | grep "wptt-preload-cache.sh" | grep "bash" | awk '{print $2}')
if [[ "$tuan" ]];then
kill -9 $tuan
fi


if [[ "$checksm2" != "1" ]]; then
    echo "He thong se chay qua trinh nay ton kha nhieu tai nguyen..."
    bash /etc/wptt/wptt-preload-cache.sh -i 0.5 ${NAME2}
    if [[ "$grepmobile" != "0" ]]; then
        bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -m ${NAME2}
    fi
    if [[ "$grepwebp" != "0" ]]; then
        bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -w ${NAME2}
    fi
fi

if [[ "$checksm2" = "1" ]]; then
    bash /etc/wptt/wptt-preload-cache.sh -i 0.5 ${ssl}://$NAME/wp-sitemap-posts-post-1.xml && bash /etc/wptt/wptt-preload-cache.sh -i 0.5 ${ssl}://$NAME/wp-sitemap-posts-page-1.xml && bash /etc/wptt/wptt-preload-cache.sh -i 0.5 ${ssl}://$NAME/wp-sitemap-taxonomies-category-1.xml
    if [[ "$grepmobile" != "0" ]]; then
        bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -m ${ssl}://$NAME/wp-sitemap-posts-post-1.xml && bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -m ${ssl}://$NAME/wp-sitemap-posts-page-1.xml && bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -m ${ssl}://$NAME/wp-sitemap-taxonomies-category-1.xml
    fi
    if [[ "$grepwebp" != "0" ]]; then
        bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -w ${ssl}://$NAME/wp-sitemap-posts-post-1.xml && bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -w ${ssl}://$NAME/wp-sitemap-posts-page-1.xml && bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -w ${ssl}://$NAME/wp-sitemap-taxonomies-category-1.xml
    fi

    if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/woocommerce ]]; then
        bash /etc/wptt/wptt-preload-cache.sh -i 0.5 ${ssl}://$NAME/wp-sitemap-posts-product-1.xml && bash /etc/wptt/wptt-preload-cache.sh -i 0.5 ${ssl}://$NAME/wp-sitemap-taxonomies-product_cat-1.xml
        if [[ "$grepmobile" != "0" ]]; then
            bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -m ${ssl}://$NAME/wp-sitemap-posts-product-1.xml && bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -m ${ssl}://$NAME/wp-sitemap-taxonomies-product_cat-1.xml
        fi
        if [[ "$grepwebp" != "0" ]]; then
            bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -w ${ssl}://$NAME/wp-sitemap-posts-product-1.xml && bash /etc/wptt/wptt-preload-cache.sh -i 0.5 -w ${ssl}://$NAME/wp-sitemap-taxonomies-product_cat-1.xml
        fi
    fi

fi

echo "========================================================================="
echo "                      Preload cache da hoan tat	                       "
echo "========================================================================="
echo "Cong cu phat trien boi: Gia Tuan"
echo "Yeu Cau Ho tro: https://wptangtoc.com/lien-he"
echo "Tai tro phat trien: https://wptangtoc.com/donate"
