#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025
clear
function huong_dan(){
Tính năng Gửi feedback cho tác giả trong phần mềm WPTangToc OLS là một kênh liên lạc quan trọng cho phép người dùng đóng góp ý kiến, báo lỗi, hoặc đề xuất cải tiến trực tiếp đến người đã phát triển ra công cụ đó.

Mục đích chính của tính năng này:
 * Báo lỗi [Bug Report]: Giúp người dùng thông báo cho tác giả về bất kỳ lỗi nào họ gặp phải khi sử dụng WPTangToc OLS, kèm theo mô tả chi tiết để tác giả có thể kiểm tra và khắc phục.
 * Đề xuất tính năng mới [Feature Request]: Người dùng có thể gợi ý những chức năng mới hoặc cải tiến cho các tính năng hiện có mà họ cảm thấy sẽ hữu ích cho WPTangToc OLS.
 * Đóng góp ý kiến chung: Chia sẻ trải nghiệm sử dụng, những điểm hài lòng hoặc chưa hài lòng về công cụ.
 * Yêu cầu hỗ trợ [trong một số trường hợp]: Mặc dù kênh feedback không luôn là kênh hỗ trợ chính thức, nhưng đôi khi người dùng cũng có thể đặt câu hỏi hoặc nhờ trợ giúp qua đây.

Để gửi feedback cho tác giả WPTangToc OLS, bạn nên tìm kiếm các thông tin liên hệ hoặc đường dẫn hỗ trợ được cung cấp trong tài liệu hướng dẫn, trong các thông báo của script khi chạy, hoặc trên các trang web/diễn đàn nơi WPTangToc OLS được giới thiệu và thảo luận [ví dụ như nhóm FaceBook cộng đồng tăng tốc WordPress, hoặc trang GitHub].
}


. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

# echo "tính năng này không thể dùng nữa"
# exit;

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
wptangtoc 1
fi

echo -e "+-----------------------------------------------------------------------+"
echo "|                                                                       |"
echo "|                        $gui_yeu_cau_gia_tuan		        |"
echo "|                                                                       |"
echo -e "+-----------------------------------------------------------------------+"
echo "                                        .                     
                                        .:---==--=:                 
                                      ::::::::::::--:.              
                                   ::::.........::::::-:            
                                 :==:..............::::::           
                                ::::..    ...........::::.          
                               :..::....   .....:.....:-.-.         
                               . .--:-:.............::.::.:         
                                :==++=-:-....:.......:::::.         
                               :=+++*++=--::... .....:::.-          
                              :++*******==-:.....:. ... ..          
                              ===+*###*****+-:==-=++-:.:.           
                              ==-:-=***#*******####%#+==            
                             .+---.:-++++==-==+*#####+=*=.          
                             =***+++=+**+==-:-=+*##%#+*#*.          
                             *#####**####**++++**##%#*+#:           
                             *******###############%###-            
                             ++==+*#%%%%#*##%%%%%#%#*+.             
                             :+=++=+***##*+*#####%#.                
                              -+--++++**##*+**####.                 
           .:-----::::.::::..:-=+==++**++=++**##*                   
        .-=++=========-------=:-*+===++********#.                   
       -=-=----------==-----:-::+******##*****##.                   
     .-------==-------===-:---::=+++*********##%-                   
   .-------==---------------:---====++++*****###=:.                 
  :--------------------------:-=+++++++*******+====                 
.---------------==---=------:..-*#******+++==-----==.               
------------------------------::-+*##**+==----=====-=-.             
------:------------------------:::-==--:.:+========--=+-            
-----::-----------------------::-+::::::..:===--=====:=+=-.         
----::---------------------------=--------:----======-:=+++=-:.  "

. /etc/wptt/.wptt.conf
if [[ $wptangtoc_ols_giatuan = "" && $key_activate = '' ]]; then
echo "Tính năng này bản free không thể sử dụng được"
wptangtoc 1
fi

read -p "Xác nhận bạn muốn gửi báo lỗi đến cho mình? (y/n): " dongy
if [[ "$dongy" != "y" ]];then
wptangtoc 1
exit
fi


read -p "Nhập nội dung gửi đến mình: " noidung


if [[ "$so_dien_thoai" = "" ]]; then

read -p "Hãy nhập số điện thoại của bạn để mình dễ dàng liên hệ với bạn: " sodienthoai
pat="^[0-9]{10}$"
while [[ ! $sodienthoai =~ $pat ]]
    do
    echo "Đây không phải là số điện thoại"
    sleep 3
    wptangtoc 1
    exit
done
echo "so_dien_thoai=$sodienthoai" >> /etc/wptt/.wptt.conf
fi

telegram_api_giatuan=$(curl -s https://wptangtoc.com/share/feedback.txt | grep "api" | cut -f2 -d "=")
telegram_id_giatuan=$(curl -s https://wptangtoc.com/share/feedback.txt | grep "id" | cut -f2 -d "=")

client_ip=$(echo $SSH_CLIENT | awk '{ print $1}')
vps_ip=$(curl -s ipv4.icanhazip.com)
if [[ "$vps_ip" = "" ]]; then
    vps_ip=$(curl -s checkip.amazonaws.com)
fi
date="$(date "+%d-%m-%Y %H:%M")"
info_ip=https://ipinfo.io/${client_ip}
text="
Thông tin yêu cầu WPTangToc OLS
-------------------------------------
Nội dung: $noidung
-------------------------------------
IP Máy trạm: *${client_ip}* - [Thông tin chi tiết](${info_ip})
IP webserver: ${vps_ip}
Thời điểm: ${date}
Số điện thoại: ${sodienthoai}
Website: `for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
    domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
         echo "$domain ,"
    fi
  done
`
-------------------------------------
WPTangToc OLS phiên bản : $version_wptangtoc_ols
Phát triển bởi [Gia Tuấn](https://wptangtoc.com/gia-tuan)
"
url_tele="https://api.telegram.org/bot${telegram_api_giatuan}/sendMessage"
curl -s -d "chat_id=$telegram_id_giatuan&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url_tele > /dev/null
clear
echo "Nội dung tin nhắn đã gửi đến Gia Tuấn (Tác giả phần mềm WPTangToc OLS)"
echo "Cảm ơn bạn đã gửi báo lỗi đến với mình để mình cải tiến sản phẩm tốt hơn"

if [[ "$telegram_api" != "" || "$telegram_id" != "" ]]; then

text="
Cảm ơn bạn đã gửi yêu cầu cho Gia Tuấn
-------------------------------------
Nội dung của bạn: ${noidung}
Thời điểm: ${date}
-------------------------------------
Các thông tin cá nhân của mình.
Số điện thoại: 0866880462
Zalo: 0866880462
Telegram: t.me/wptangtoc
website: wptangtoc.com
FaceBook: fb.com/wptangtoc
Email: giatuan@wptangtoc.com
STK Ngân Hàng: 2222223338888 (Hoàng Gia Tuấn) - MB Bank, CN Hải Phòng
-------------------------------------
WPTangToc OLS phiên bản : $version_wptangtoc_ols
Phát triển bởi [Gia Tuấn](https://wptangtoc.com/gia-tuan)
"
url_tele="https://api.telegram.org/bot${telegram_api}/sendMessage"
curl -s -d "chat_id=$telegram_id&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url_tele > /dev/null

fi
sleep 2

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
wptangtoc 1
fi
