#!/bin/bash

function huong_dan(){
Tính năng hiện thị nhóm facebook để cùng nhau thảo luận trao đổi các vấn đề liên quan đến quản trị máy chủ, tăng tốc website

link: https://www.facebook.com/groups/wptangtoc/
}

clear
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

RED='\033[0;31m'
NC='\033[0m'

echo -e "${RED}
     .:..........................             
      .::::::::::::::::::::::::::::..         
        ..:::::::::::::::::::::::::::::.      
                             ...:::::::::.    
                                  .:::::::.   
          .:::::::.         .       .:::::::  
         .::::::::::::::::::::..      ::::::: 
         ::::::::::::::::::::::::.     ::::::.
        .::::::::::::::::::::::::::.   .:::::.
        .::::::::::::::::::::::::::::  .:::::.
        .::::::::::::::::::::::::::.   .:::::.
         ::::::::::::::::::::::::.     ::::::.
.::::::  .:::::::::::::::::::::.      ::::::. 
          .:::::::.                 .:::::::  
       ::::::::::::.              .:::::::.   
       ......:::::::::...    ...:::::::::.    
               .:::::::::::::::::::::::.      
   ..............::::::::::::::::::..         
  .:::::::::::::................. ${NC}"




  echo "CỘNG ĐỒNG TĂNG TỐC ĐỘ WORDPRESS"
  echo "link: https://www.facebook.com/groups/wptangtoc"
  echo "$noi_chia_se_trao_doi_thao_luan_cac_van_de_lien_quan"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
sleep 10
wptangtoc 1
fi

