#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021

. /etc/wptt/.wptt.conf

RED='\033[0;31m'
NC='\033[0m'

work_cpucore='1024'
cpucore=$(grep -c ^processor /proc/cpuinfo)
max_client=$(expr $work_cpucore \* $cpucore \* 2)
max_client_max=$(expr $work_cpucore \* $cpucore \* 3)
max_client_php=$(expr $work_cpucore \* $cpucore \/ 8)
tong_ram_byte=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
rong_ram_mb=$(echo "scale=0;${tong_ram_byte}/1024" | bc)
if [[ "$rong_ram_mb" = "" ]]; then
  rong_ram_mb="2048"
fi
tong_ram_mb_db=$(echo "scale=0;${rong_ram_mb}/4" | bc)

gioi_han_tien_trinh_bao_loi_503=$(expr $max_client \/ 8)

  NAME="$Website_chinh"
  USER=${NAME//[-._]/wp}
  NAMEPHP=${NAME//[-._]/}
  USERCLEAN="$USER"


echo -e "${RED}-------------------------------------------------------------------------"
echo ""
echo " 0     0 000000  0000000                         0000000 "
echo " 0  0  0 0     0    0       00    0    0   0000     0      0000    0000 "
echo " 0  0  0 0     0    0      0  0   00   0  0    0    0     0    0  0    0 "
echo " 0  0  0 000000     0     0    0  0 0  0  0         0     0    0  0 "
echo -e "${NC} 0  0  0 0          0     000000  0  0 0  0  000    0     0    0  0 "
echo " 0  0  0 0          0     0    0  0   00  0    0    0     0    0  0    0 "
echo "  00 00  0          0     0    0  0    0   0000     0      0000    0000 "
echo ""
echo "  00000   0       00000 "
echo " 0     0  0      0     0 "
echo " 0     0  0      0 "
echo -e "${RED} 0     0  0       00000 "
echo " 0     0  0            0 "
echo " 0     0  0      0     0 "
echo "  00000   000000  00000 "
echo -e "--------------------------------------------------------------------------${NC}"
echo "Cam on ban da chon WPTangToc OLS ..."
echo ""
echo "Cong cu phat trien boi Gia Tuan"

rm -f /usr/local/lsws/conf/httpd_config.conf

echo "#
# PLAIN TEXT CONFIGURATION FILE
#
#It not set, will use host name as serverName
serverName                
httpdWorkers              $cpucore
user                      nobody
group                     nobody
priority                  0
cpuAffinity               $cpucore
enableLVE                 0
inMemBufSize              60M
swappingDir               /tmp/lshttpd/swap
autoFix503                1
gracefulRestartTimeout    300
mime                      conf/mime.properties
showVersionNumber         0
adminEmails               root@localhost

errorlog logs/error.log {
  logLevel                ERROR
  debugLevel              0
  rollingSize             10M
  enableStderrLog         1
}

accesslog logs/access.log {
  rollingSize             10M
  keepDays                30
  compressArchive         0
}

indexFiles                index.html, index.php

expires  {
  enableExpires           1
  expiresByType           image/*=A7776000, text/css=A7776000, application/x-javascript=A7776000, application/javascript=A7776000, font/*=A7776000, application/x-font-ttf=A7776000
}
autoLoadHtaccess          1

tuning  {
  maxConnections          $max_client_max
  maxSSLConnections       $max_client_max
  connTimeout             300
  maxKeepAliveReq         $max_client_max
  keepAliveTimeout        10
  sndBufSize              0
  rcvBufSize              0
  maxReqURLLen            32768
  maxReqHeaderSize        65536
  maxReqBodySize          2047M
  maxDynRespHeaderSize    32768
  maxDynRespSize          2047M
  maxCachedFileSize       4096
  totalInMemCacheSize     20M
  maxMMapFileSize         256K
  totalMMapCacheSize      40M
  useSendfile             1
  fileETag                28
  enableGzipCompress      1
  compressibleTypes       default
  enableDynGzipCompress   1
  gzipCompressLevel       6
  gzipAutoUpdateStatic    1
  gzipStaticCompressLevel 6
  brStaticCompressLevel   6
  gzipMaxFileSize         10M
  gzipMinFileSize         300

  quicEnable              1
  quicShmDir              /dev/shm
}

fileAccessControl  {
  followSymbolLink        1
  checkSymbolLink         0
  requiredPermissionMask  000
  restrictedPermissionMask 000
}

perClientConnLimit  {
  staticReqPerSec         0
  dynReqPerSec            0
  outBandwidth            0
  inBandwidth             0
  softLimit               10000
  hardLimit               10000
  gracePeriod             15
  banPeriod               300
}

CGIRLimit  {
  maxCGIInstances         20
  minUID                  11
  minGID                  10
  priority                0
  CPUSoftLimit            10
  CPUHardLimit            50
  memSoftLimit            1460M
  memHardLimit            1470M
  procSoftLimit           400
  procHardLimit           450
}

accessDenyDir  {
  dir                     /
  dir                     /etc/*
  dir                     /dev/*
  dir                     conf/*
  dir                     admin/conf/*
}

accessControl  {
  allow                   ALL
}

extprocessor lsphp {
  type                    lsapi
  address                 uds://tmp/lshttpd/lsphp.sock
  maxConns                20
  env                     PHP_LSAPI_CHILDREN=20
  env                     LSAPI_AVOID_FORK=200M
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      5
  respBuffer              0
  autoStart               1
  path                    /usr/local/lsws/lsphp74/bin/lsphp
  backlog                 100
  instances               1
  memSoftLimit            ${rong_ram_mb}M
  memHardLimit            ${rong_ram_mb}M
  procSoftLimit           $gioi_han_tien_trinh_bao_loi_503
  procHardLimit           $gioi_han_tien_trinh_bao_loi_503
}

scripthandler  {
  add                     lsapi:lsphp wordpress
}

railsDefaults  {
  maxConns                1
  env                     LSAPI_MAX_IDLE=60
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      5
  respBuffer              0
  backlog                 50
  runOnStartUp            3
  extMaxIdleTime          300
  priority                3
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           500
  procHardLimit           600
}

wsgiDefaults  {
  maxConns                5
  env                     LSAPI_MAX_IDLE=60
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      5
  respBuffer              0
  backlog                 50
  runOnStartUp            3
  extMaxIdleTime          300
  priority                3
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           500
  procHardLimit           600
}

nodeDefaults  {
  maxConns                5
  env                     LSAPI_MAX_IDLE=60
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      5
  respBuffer              0
  backlog                 50
  runOnStartUp            3
  extMaxIdleTime          300
  priority                3
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           500
  procHardLimit           600
}

module cache {
  internal                1
checkPrivateCache   1
checkPublicCache    1
maxCacheObjSize     10000000
maxStaleAge         200
qsCache             1
reqCookieCache      1
respCookieCache     1
ignoreReqCacheCtrl  1
ignoreRespCacheCtrl 0

enableCache         0
expireInSeconds     3600
enablePrivateCache  0
privateExpireInSeconds 3600
  ls_enabled              1
}


listener http {
  address                 *:80
  secure                  0
  map                     $NAME $NAME
}

listener https {
  address                 *:443
  secure                  1
  keyFile                 /etc/letsencrypt/live/$NAME/privkey.pem
  certFile                /etc/letsencrypt/live/$NAME/cert.pem
  certChain               0
  CACertFile              /etc/letsencrypt/live/$NAME/chain.pem
  sslProtocol             24
  renegProtection         1
  sslSessionCache         1
  sslSessionTickets       1
  enableSpdy              15
  enableQuic              1
  map                     $NAME $NAME
}

vhTemplate centralConfigLog {
  templateFile            conf/templates/ccl.conf
  listeners               http
}

vhTemplate EasyRailsWithSuEXEC {
  templateFile            conf/templates/rails.conf
  listeners               http
}" >/usr/local/lsws/conf/httpd_config.conf

rm -rf /usr/local/lsws/conf/vhosts/$NAME
mkdir /usr/local/lsws/conf/vhosts/$NAME
touch /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
echo "docRoot                   /usr/local/lsws/$NAME/html
vhDomain                  $NAME
enableGzip                1
cgroups                   0


index  {
  useServer               0
  indexFiles              index.html index.php
  autoIndex               0
}

scripthandler  {
  add                     lsapi:$NAMEPHP php
}

accessControl  {
  allow                   *
}

lsrecaptcha  {
  enabled                 1
  type                    0
}
extprocessor $NAMEPHP {
  type                    lsapi
  address                 uds://tmp/lshttpd/$NAMEPHP.sock
  maxConns                20
  env                     PHP_LSAPI_CHILDREN=20
  env                     LSAPI_AVOID_FORK=200M
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      5
  respBuffer              0
  autoStart               1
  path                    /usr/local/lsws/lsphp74/bin/lsphp
  backlog                 100
  instances               1
  extUser                 $USER
  extGroup                $USER
  runOnStartUp            2
  priority                0
  memSoftLimit            ${rong_ram_mb}M
  memHardLimit            ${rong_ram_mb}M
  procSoftLimit           $gioi_han_tien_trinh_bao_loi_503
  procHardLimit           $gioi_han_tien_trinh_bao_loi_503
}

context / {
  location                /usr/local/lsws/$NAME/html
  allowBrowse             1
  extraHeaders            <<<END_extraHeaders
X-XSS-Protection 1;mode=block
X-Frame-Options SAMEORIGIN
Referrer-Policy strict-origin-when-cross-origin
X-Content-Type-Options nosniff
X-Powered-By WPTangTocOLS
permissions-policy accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
  END_extraHeaders


  rewrite  {

  }
  addDefaultCharset       off

  phpIniOverride  {

  }
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
/usr/local/lsws/$NAME/html/.htaccess
}

vhssl  {
  keyFile                 /etc/letsencrypt/live/$NAME/privkey.pem
  certFile                /etc/letsencrypt/live/$NAME/cert.pem
  certChain               0
  CACertFile              /etc/letsencrypt/live/$NAME/chain.pem
  sslProtocol             24
  renegProtection         1
  sslSessionCache         1
  sslSessionTickets       1
  enableSpdy              15
  enableQuic              1
  enableStapling          1
  ocspRespMaxAge          86400
  ocspResponder           http://cert.int-x3.letsencrypt.org/
  ocspCACerts             /etc/letsencrypt/live/$NAME/chain.pem
}

module cache {
checkPrivateCache   1
checkPublicCache    1
maxCacheObjSize     10000000
maxStaleAge         200
qsCache             1
reqCookieCache      1
respCookieCache     1
ignoreReqCacheCtrl  1
ignoreRespCacheCtrl 0
storagePath /usr/local/lsws/$NAME/luucache
enableCache         0
expireInSeconds     3600
enablePrivateCache  0
privateExpireInSeconds 3600
  ls_enabled              1
}" >/usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

chown -R lsadm:nobody /usr/local/lsws/conf/vhosts/$NAME
chmod -R 750 /usr/local/lsws/conf/vhosts/$NAME

phpcheck2223=$(php -v | grep cli | cut -c 4-7| sed 's/ //g')
php_ver_chon=${phpcheck2223//[-._]/}

sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/httpd_config.conf
sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -E -i "s/ lsphp${php_ver_chon}/lsphp${php_ver_chon}/g" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -i "s/ lsphp$ {php_ver_chon}/lsphp${php_ver_chon}/g" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf

sed -i "/$NAME $NAME/d" /usr/local/lsws/conf/httpd_config.conf

if [ "$(ls -A /etc/wptt/vhost)" ]; then
  echo
  echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
      sed -i "/listener http/a map 		$domain $domain" /usr/local/lsws/conf/httpd_config.conf && \cp -f /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf /usr/local/lsws/conf/vhosts/$domain/$domain.conf && sed -i "s/$NAME/$domain/g" /usr/local/lsws/conf/vhosts/$domain/$domain.conf && chown -R lsadm:nobody /usr/local/lsws/conf/vhosts/$domain && chmod -R 750 /usr/local/lsws/conf/vhosts/$domain
    fi
  done
  echo '--------------------------------------------------'
  echo
fi

for entry in $(ls -A /etc/wptt/vhost); do
  domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
  path="/usr/local/lsws/$domain/html"
  i=1

  if [[ -d "$path" ]]; then
    . /etc/wptt/vhost/.$domain.conf && sed -i "s/$USERCLEAN/$User_name_vhost/g" /usr/local/lsws/conf/vhosts/$domain/$domain.conf && NAMEPHP2=${domain//[-._]/} && sed -i "s/$NAMEPHP/$NAMEPHP2/g" /usr/local/lsws/conf/vhosts/$domain/$domain.conf
  fi
done

for entry in $(ls -A /etc/wptt/vhost); do
  domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
  path="/usr/local/lsws/$domain/html"
  i=1

  if [[ -d "$path" ]]; then
    . /etc/wptt/vhost/.$domain.conf && echo "virtualhost $domain {
  vhRoot                  /usr/local/lsws/$domain/
  configFile              /usr/local/lsws/conf/vhosts/$domain/$domain.conf
  allowSymbolLink         1
  enableScript            1
  restrained              1
  maxKeepAliveReq         $max_client
  setUIDMode              2
  user                    $User_name_vhost
  group                   $User_name_vhost
}" >>/usr/local/lsws/conf/httpd_config.conf
  fi
done

phpcheck=$(php -v |grep cli | cut -c 4-7)
php_version_server_hien_tai=${phpcheck//[-._]/}
if [ "$(ls -A /etc/wptt/vhost)" ]; then
  echo
  echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
		. /etc/wptt/vhost/.$domain.conf
		if [[ $phien_ban_php_domain = "" ]];then
			php_version_install=$(echo "$php_version_server_hien_tai")
		else
php_version_install=${phien_ban_php_domain//[-._]/}
		fi
sed -E -i "s/lsphp[0-9]+/lsphp${php_version_install}/g" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -E -i "s/ lsphp${php_version_install}/lsphp${php_version_install}/g" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -i "s/lsphp ${php_version_install}/lsphp${php_version_install}/g" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -i "s/ lsphp${php_version_install}/lsphp${php_version_install}/g" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -i "s/lsphp${php_version_install} /lsphp${php_version_install}/g" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -i "s/lsphp ${php_version_install}/lsphp${php_version_install}/g" /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
    fi
  done
  echo '--------------------------------------------------'
  echo
fi


if [ "$(ls -A /etc/wptt/vhost)" ]; then
  echo
  echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/ssl"
    i=1

    if [[ -d "$path" ]]; then
		. /etc/wptt/ssl/wptt-caissl-traphi $domain 1
    fi
  done
  echo '--------------------------------------------------'
  echo
fi


if [ "$(ls -A /etc/wptt/vhost)" ]; then
  echo
  echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    i=1
sed -i '/phien_ban_php_domain/g' /etc/wptt/vhost/.$domain.conf
  done
  echo '--------------------------------------------------'
  echo
fi


RED='\033[0;31m'
NC='\033[0m'

echo -e "${RED}-------------------------------------------------------------------------"
echo ""
echo " 0     0 000000  0000000                         0000000 "
echo " 0  0  0 0     0    0       00    0    0   0000     0      0000    0000 "
echo " 0  0  0 0     0    0      0  0   00   0  0    0    0     0    0  0    0 "
echo " 0  0  0 000000     0     0    0  0 0  0  0         0     0    0  0 "
echo -e "${NC} 0  0  0 0          0     000000  0  0 0  0  000    0     0    0  0 "
echo " 0  0  0 0          0     0    0  0   00  0    0    0     0    0  0    0 "
echo "  00 00  0          0     0    0  0    0   0000     0      0000    0000 "
echo ""
echo "  00000   0       00000 "
echo " 0     0  0      0     0 "
echo " 0     0  0      0 "
echo -e "${RED} 0     0  0       00000 "
echo " 0     0  0            0 "
echo " 0     0  0      0     0 "
echo "  00000   000000  00000 "
echo -e "--------------------------------------------------------------------------${NC}"
echo "-------------------------------------------------------------------------"
echo "Cong cu WPTangToc OLS phat trien boi: Gia Tuan"
echo "Yeu Cau Ho tro		: https://wptangtoc.com/lien-he/"
echo "Giup chung toi luon giu WPTangToc OLS co the su dung mien phi bang cach dong gop vao"
echo "Tai tro phat trien	: https://wptangtoc.com/donate/"
echo "Huong dan		: https://wptangtoc.com/wptangtoc-ols-huong-dan"
echo "-------------------------------------------------------------------------"
echo "Dang kiem tra he thong cua ban..."
sleep 1
/usr/local/lsws/bin/lswsctrl restart
