#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
. /etc/wptt/.wptt.conf
ip=$(curl -s myip.directadmin.com)
if [[ "$ip" = "" ]]; then
    ip=$(curl -s ifconfig.me)
fi
RED='\033[0;31m'
NC='\033[0m'
clear
echo -e "${RED}-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo "  	                    Xem thong tin tai khoan	"
echo "-------------------------------------------------------------------------"
echo -e "--------------------------------------------------------------------------${NC}"
echo "-------------------------------------------------------------------------"
echo "Username database : $database_admin_username"
echo "Password database : $database_admin_password"
echo "truy cap vao database     : mysql -u $database_admin_username -p$database_admin_password"
echo "-------------------------------------------------------------------------"
if [[ -f /usr/local/lsws/conf/disablewebconsole ]]; then
    echo "Hien tai webguiadmin cua ban da bi vo hieu hoa theo mac dinh"
    echo "Neu ban co nhu cau su dung webguiadmin ban co the mo trong menu wptangtoc ols"
fi

port_webgui_openlitespeed=$(cat /usr/local/lsws/admin/conf/admin_config.conf | grep "address" | cut -f2 -d":")

checkdns=$(host $Website_chinh | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
if [[ "$checkdns" = "" ]]; then
    checkdns=$(nslookup $Website_chinh | grep Address | cut -f5 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
fi

echo "Truy cap vao webguiadmin  : http://$ip:$port_webgui_openlitespeed"
echo "Tai khoan id webguiadmin  : $Ten_dang_nhap_ols_webgui "
echo "Password webguiadmin      : $Password_OLS_webgui"
echo "-------------------------------------------------------------------------"
if [[ "$user_tai_khoan_root" = "" ]]; then
    echo "truy cap vao ssh          : ssh -p $port_ssh root@$ip"
    echo "truy vao vao sftp         : sftp -oPort=$port_ssh root@$ip"
    if [[ "$checkdns" = "$ip" ]]; then
        echo "truy cap vao ssh          : ssh -p $port_ssh root@$Website_chinh"
        echo "truy vao vao sftp         : sftp -oPort=$port_ssh root@$Website_chinh"
    fi
else
    echo "truy cap vao ssh          : ssh -p $port_ssh $user_tai_khoan_root@$ip"
    echo "truy vao vao sftp         : sftp -oPort=$port_ssh $user_tai_khoan_root@$ip"
    if [[ "$checkdns" = "$ip" ]]; then
        echo "truy cap vao ssh          : ssh -p $port_ssh $user_tai_khoan_root@$Website_chinh"
        echo "truy vao vao sftp         : sftp -oPort=$port_ssh $user_tai_khoan_root@$Website_chinh"
    fi
fi
echo "-------------------------------------------------------------------------"
echo ""
echo "-------------------------------------------------------------------------"
echo "Cong cu WPTangToc OLS phat trien boi: Gia Tuan"
echo "Yeu Cau Ho tro            : https://wptangtoc.com/lien-he/"
echo "Giup chung toi luon giu WPTangToc OLS co the su dung mien phi bang cach dong gop vao"
echo "Tai tro phat trien        : https://wptangtoc.com/donate/"
echo "Huong dan                 : https://wptangtoc.com/wptangtoc-ols-huong-dan"
echo "-------------------------------------------------------------------------"
