#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Quan ly Cache:"
echo ""
options=(
	"Xoa Cache website WordPress" #1
	"Xoa ALL Cache WordPress" #2
	"Xoa Cache Redis" #3
    "Kich hoat LScache"               #4
    "Kich hoat object cache lsmemcached"                     #5
    "Tat kich hoat object cache lsmemcached"                      #6
    "Kich hoat object cache redis"                  #7
    "Tat kich hoat object cache redis"                #8
    "Kiem tra LScache"                #9
    "Tat kich hoat LScache"                #10
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/cache/wptt-xoacache" 98
        ;;
    "${options[1]}")
        "/etc/wptt/cache/xoa-cache-full" 98
        ;;
    "${options[2]}")
        "/etc/wptt/cache/wptt-xoa-cache-redis" 98
        ;;
    "${options[3]}")
        "/etc/wptt/cache/lscache" 99
        ;;
    "${options[4]}")
        "/etc/wptt/cache/wptt-kich-hoat-lsmemcaced" 98
        ;;
    "${options[5]}")
        "/etc/wptt/cache/wptt-huy-kich-hoat-lsmemcached" 98
        ;;
    "${options[6]}")
        "/etc/wptt/cache/wptt-redis-kich-hoat" 98
        ;;
    "${options[7]}")
        "/etc/wptt/cache/wptt-huy-kich-hoat-redis" 98
        ;;

	"${options[8]}")
        "/etc/wptt/domain/real-time-check-domain" 97
        ;;

	"${options[9]}")
        "/etc/wptt/cache/huy-lscache" 98
        ;;


    *) wptangtoc ;;
    esac
done
