#!/bin/bash
. /etc/wptt/wptt-header-menu
header_menu
echo ""
echo ""
echo "Quan ly SSH/SFTP:"
echo ""
options=(
    "Thay doi PassWord"            #1
    "Doi port SSH/SFTP"            #2
    "Thay doi user root"           #3
    "Khoi phuc user root"          #4
    "Thiet lap canh bao login SSH" #5
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/ssh/wptt-passwd"
        ;;
    "${options[1]}")
        "/etc/wptt/ssh/wptt-ssh-port"
        ;;

    "${options[2]}")
        "/etc/wptt/ssh/wptt-user-root-changer"
        ;;

    "${options[3]}")
        "/etc/wptt/ssh/wptt-user-root-quay"
        ;;

    "${options[4]}")
        "/etc/wptt/bao-mat/thong-bao-login-ssh"
        ;;
    *) wptangtoc ;;
    esac
done
