#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
echo "$wptangtoc_ols_dang_kiem_tra_he_thong"
clear
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
up=$(awk '{a=$1/86400;b=($1%86400)/3600;c=($1%3600)/60} {printf("%d ngày %d giờ %d phút\n",a,b,c)}' /proc/uptime)

RED='\033[0;31m'
NC='\033[0m'

echo -e "${RED}+-----------------------------------------------------------------------+"
echo "|                                                                       |"
echo "|                        WPTANGTOC OLS $phien_ban: $version_wptangtoc_ols 		|"
echo "|                          $phat_trien_boi_gia_tuan 			|"
if [[ $wptangtoc_ols_giatuan = "1" ]]; then
echo "|                          WPTangToc OLS Premium                        |"
fi
if [[ $beta_wptangtoc_ols = "1" ]]; then
echo "|                          WPTangToc OLS beta                           |"
fi
echo -e "+-----------------------------------------------------------------------+ ${NC}"

thoi_gian=$(date +'%H'|sed 's/^0//g')
if (( $thoi_gian < 10 ));then
thoi_diem='Chúc bạn có buổi sáng tuyệt vời'
elif (( $thoi_gian < 14 ));then
thoi_diem='Chúc bạn có buổi trưa tuyệt vời'
elif (( $thoi_gian < 18 ));then
thoi_diem='Chúc bạn có buổi chiều tuyệt vời'
else
thoi_diem='Chúc bạn có buổi tối tuyệt vời'
fi

if [[ $ngon_ngu = 'en' ]];then
if (( $thoi_gian < 10 ));then
thoi_diem='Good morning'
elif (( $thoi_gian < 18 ));then
thoi_diem='Good Afternoon'
else
thoi_diem='Good Evening'
fi
fi

if [[ $wptangtoc_ols_giatuan = "1" ]]; then
echo "$thoi_diem - WPTangToc OLS Premium $san_sang_phuc_vu		        "
else
echo "$thoi_diem - $chao_mung_ban_den_voi_wptangtoc_ols		        "
fi

echo "-------------------------------------------------------------------------"
echo "CPU : $(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}') | Ram : $(free -m | awk 'NR==2{printf "%s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }') | Disk: $(df -BG| awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}') "
echo "-------------------------------------------------------------------------"
ols1=$(systemctl status lsws.service 2>/dev/null | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
mariadb1=$(systemctl status mariadb.service 2>/dev/null | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)

if [[ "$ols1" = "active" ]]; then
    ols="$hoat_dong_tot"
else
    ols="Webserver LiteSpeed $dang_gap_su_co"
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
    systemctl restart lsws.service >/dev/null 2>&1
fi

if [[ "$mariadb1" = 'active' ]]; then
    mariadb="$hoat_dong_tot"
else
    mariadb="MariaDB Database $dang_gap_su_co"
    systemctl restart mariadb.service >/dev/null 2>&1
fi

echo "Webserver LiteSpeed	: $ols"
echo "MariaDB			: $mariadb"
if [[ "$ols1" = 'active' && "$mariadb1" = 'active' ]]; then
    echo "$tinh_trang_may_chu	: $hoat_dong_tot"
else
    echo "$tinh_trang_may_chu	: $may_chu_dang_gap_van_de"
    echo "$yeu_cau_ho_tro		: https://wptangtoc.com/lien-he"
fi
echo "System uptime	    	: $up"
echo '-------------------------------------------------------------------------'
echo "$tang_toc_wordpress	: https://wptangtoc.com/blog"
echo "$nha_tai_tro_chinh	: wptangtoc.com"
echo "$phat_trien_boi		: Gia Tuấn"
#echo "Khoá đào tạo nâng cao		: https://wptangtoc.com/dao-tao/"
echo '-------------------------------------------------------------------------'
echo "$nhap_lenh_phim_1_de_vao_menu_quan_tri"
echo '-------------------------------------------------------------------------'
ram_sudung=$(free | grep Mem | awk '{print $3/$2 * 100.0}' | cut -f1 -d '.')
if [[ $ram_sudung =~ ^-?[0-9]+$ ]];then
if (( "$ram_sudung" > 80 )); then
RED='\033[0;33m'
NC='\033[0m'
echo -e "${RED}==================================================================="
echo "Cảnh báo FULL Ram đang sử dụng: ${ram_sudung}%"
echo -e "=================================================================== ${NC}"
fi
fi


THRESHOLD_GB=2                     # Ngưỡng dung lượng (GB)
available_space=$(df -k / | awk 'NR==2{print $4}')  # Lấy dung lượng khả dụng (KB) của /
available_space_gb=$(echo "$available_space / 1024 / 1024" | bc) # Đổi sang GB
if (( $(echo "$available_space_gb <= $THRESHOLD_GB" | bc -l) )); then
message="*Cảnh báo:* Ổ cứng của máy chủ gần đầy chỉ còn khả dụng: *$(echo "$available_space_gb" | awk '{printf "%.2f", $1}') GB*."
RED='\033[0;33m'
NC='\033[0m'
echo -e "${RED}==================================================================="
echo "$canh_bao_fulldisk"
echo "$message" # Hoặc dùng hàm send_telegram_message nếu bạn đã định nghĩa
echo "Disk: $(df -BG | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')"
echo "$de_kiem_tra_dung_luong_o_cung_dang_su_dung: wptt disk"
echo -e "=================================================================== ${NC}"
fi

if [[ "$thong_bao_login_ssh" = "1" ]]; then
client_ip=$(echo $SSH_CLIENT | awk '{ print $1}')
vps_ip=$(curl -s myip.directadmin.com)
if [[ "$vps_ip" = "" ]]; then
    vps_ip=$(curl -s ifconfig.me)
fi


date="$(date "+%d-%m-%Y %H:%M")"
info_ip=https://ipinfo.io/${client_ip}
text="
Cảnh báo đăng nhập SSH - ${vps_ip}
-------------------------------------
IP đăng nhập: *${client_ip}* - [Thông tin chi tiết](${info_ip})
Thời điểm: ${date}
Website: `for entry in $(ls -A /etc/wptt/vhost); do
    domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
         echo "$domain ,"
    fi
  done
`
-------------------------------------
Cảm ơn bạn đã chọn WPTangToc OLS
WPTangToc OLS phiên bản : $version_wptangtoc_ols
Phát triển bởi [Gia Tuấn](https://wptangtoc.com/gia-tuan)
"
url_tele="https://api.telegram.org/bot${telegram_api}/sendMessage"
curl -s -d "chat_id=$telegram_id&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url_tele > /dev/null	
fi
