#!/bin/bash
clear
. /etc/wptt/.wptt.conf
RED='\033[0;31m'
NC='\033[0m'
ols1=$(systemctl status lsws.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
mariadb1=$(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)

if [[ "$ols1" = "active" ]]; then
    ols="Hoat dong tot"
else
    echo "========================================================================="
    ols2="Webserver LiteSpeed dang bi gap su co"
    echo "========================================================================="
fi

if [[ "$mariadb1" = "active" ]]; then
    mariadb="Hoat dong tot"
else
    echo "========================================================================="
    mariadb2="MariaDB Database dang bi gap su co"
    echo "========================================================================="
fi

echo -e "${RED}+------------------------------------------------------------------------+"
echo "|                        WPTANGTOC OLS phien ban: $version_wptangtoc_ols		 |"
echo "|                          Phat trien boi: Gia Tuan			 |"
echo -e "+------------------------------------------------------------------------+ ${NC}"
echo "========================================================================="
if [[ "$ols1" = "active" && "$mariadb1" = "active" ]]; then
    hoatdong="hoat dong tot"
else
    hoatdong="may chu dang co van de, can phai khac phuc"
    echo "$mariadb2"
    echo "$ols2"
fi
echo "Tinh trang may chu: $hoatdong"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://wptangtoc.com/wptangtoc-ols-huong-dan/"
echo "-------------------------------------------------------------------------"
echo ""
echo ""
echo "Quan ly ma nguon:"
echo ""
options=(
    "Xem nhanh vao ma nguon website"       #1
    "Kiem tra dung luong ma nguon website" #2
    "Tao shortcut alias ma nguon"          #3
    "Xoa ma nguon website"                 #4
    "Xem tong quan mat nguon"              #5
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/ma-nguon/wptt-truy-cap-nhanh"
        ;;
    "${options[1]}")
        "/etc/wptt/ma-nguon/wptt-kiem-tra-dung-luong"
        ;;

    "${options[2]}")
        "/etc/wptt/ma-nguon/wptt-cut"
        ;;

    "${options[3]}")
        "/etc/wptt/ma-nguon/wptt-xoa-ma-nguon"
        ;;
    "${options[4]}")
        "/etc/wptt/ma-nguon/wptt-xem-ma-nguon"
        ;;
    *) wptangtoc ;;
    esac
done
