#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025

function huong_dan() {
  Tính năng nhân bản website [website cloning/duplication] là một công cụ cho phép bạn tạo ra một bản sao y hệt của một website hiện có, bao gồm toàn bộ tệp tin, cơ sở dữ liệu và cấu hình.

  Mục đích: Tạo nhanh một bản sao của website để phục vụ nhiều mục đích khác nhau mà không ảnh hưởng đến website gốc đang hoạt động.

  Lợi ích:
  * Tiết kiệm thời gian và công sức: Không cần xây dựng lại website từ đầu.
  * Giảm thiểu rủi ro: An toàn thử nghiệm thay đổi trên bản sao.
  * Linh hoạt: Dễ dàng tạo nhiều phiên bản website cho các mục đích khác nhau.

  Đây là một tính năng rất hữu ích quản lý máy chủ.
}

. /etc/wptt/echo-color
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

NAME=$1
NAME2=$2

if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ $NAME = '' ]]; then
  . /etc/wptt/tenmien
  echo ""
  echo ""
  echo "Lựa chọn domain hoặc subdomain bạn muốn sao chép: "
  echo ""
  lua_chon_NAME
fi

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  wptangtoc 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  wptangtoc 1
  exit
fi

NAME_NGUON=$(echo $NAME)

NAME=$(echo $NAME | tr '[:upper:]' '[:lower:]') #chuyển viết hoa thành viết thường

if [[ $2 = '' ]]; then
  stty iutf8 #từ latin1 sang utf8, nhiều khi anh em dùng bộ gõ tiếng việt: dùng à â nó thêm \xc3 hay \xa9 ... tương thích với bộ gõ tiếng việt telex khi nhập domain
  read -p "Nhập domain hoac subdomain bạn muốn thêm và sao chép vào
    (vidu: wptangtoc.com, abc.wptangtoc.com ...) [0=Thoat]: " NAME2
fi

if [ "$NAME2" = '' ]; then
  clear
  echo "bạn chưa nhập domain."
  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    wptangtoc 1
  fi
  return 2>/dev/null
  exit

fi

if [[ "$NAME2" = "0" ]]; then
  clear
  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    wptangtoc 1
  fi
  return 2>/dev/null
  exit
fi

#chuyển domain punycode
NAME2=$(php /etc/wptt/domain/punycode.php $NAME2 2>/dev/null)
if [[ -z $NAME2 ]]; then
  clear
  echo "PHP của bạn bị lỗi không thể thêm website $NAME2"
  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    wptangtoc 1
  fi
  return 2>/dev/null
  exit
fi

#domain người dùng nhập sử dụng thêm space cách, sẽ báo không đúng định dạng
if [ $(echo $NAME2 | wc -w) -gt 1 ]; then
  clear
  . /etc/wptt/echo-color
  echoDo "domain nhập không đúng định dạng"
  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    wptangtoc 1
  fi
  return 2>/dev/null
  exit
fi

#chuyển đổi viết hoa thành chữ thường điều kiện
NAME2=$(echo $NAME2 | tr '[:upper:]' '[:lower:]')

if [ "$NAME2" = "${NAME2/./}" ]; then
  clear
  echo "Domain ten mien nhap khong dung dinh dang."
  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    wptangtoc 1
  fi
  return 2>/dev/null
  exit
fi

path2="/etc/wptt/vhost/.$NAME2.conf"
if [[ -f "$path2" ]]; then
  echo "Domain đã tồn tại trên hệ thống."
  # echo "Muốn sử dụng tính năng này vui lòng xóa domain $NAME2 của bạn đi"

  echo "Lưu ý: Việc này sẽ mất toàn bộ dữ liệu website $NAME2 trước đó"
  echo -e "$xac_nhan ghi đè website $NAME vào website $NAME2 ?: "
  prompt="$nhap_lua_chon_cua_ban [1-2]: "
  dongy="n"
  options=("$dong_y" "$khong_dong_y")
  PS3="$prompt"
  select opt in "${options[@]}"; do
    case "$REPLY" in
    1)
      dongy="y"
      break
      ;;

    2)
      dongy="n"
      break
      ;;

    $((${#options[@]} + 1)))
      printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
      break
      ;;
    *)
      printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
      break
      ;;
    esac
  done

  if [[ "$dongy" = 'y' ]]; then
    website_nhan_ban_nguon=$(echo $NAME) #luu trữ biến tránh xoá website nó đè biến rồi trả lại
    website_nhan_ban_dich=$(echo $NAME2)
    . /etc/wptt/domain/wptt-xoa-website $NAME2 'nhan-ban'

    #trả lại biến
    NAME=$(echo $website_nhan_ban_nguon)
    NAME2=$(echo $website_nhan_ban_dich)
    unset website_nhan_ban_dich website_nhan_ban_nguon
  else
    check_menu_wptangtoc_active=$1
    if [[ $check_menu_wptangtoc_active = "98" ]]; then
      wptangtoc 1
    fi
    return 2>/dev/null
    exit
  fi
fi

#kiem tra phan loai bo http:// va www
if [[ $(echo $NAME2 | grep '://') ]]; then
  NAME2=$(echo $NAME2 | cut -f3 -d '/')
fi

if [[ $(echo $NAME2 | grep '^www\.') ]]; then
  NAME2=$(echo $NAME2 | sed 's/^www.//g')
fi

USER=${NAME2//[-._]/wp}

# if  [[ $(cat /etc/passwd | cut -f1 -d ':' | grep -w $USER) ]]; then
#   clear
#   echo "User đã tồn tại trên hệ thống."
#   echo
#   wptangtoc 1
#   exit
# fi

. /etc/wptt/.wptt.conf

work_cpucore='1024'
cpucore=$(grep -c ^processor /proc/cpuinfo)
max_client=$(expr $work_cpucore \* $cpucore \* 2)
max_client_max=$(expr $work_cpucore \* $cpucore \* 3)
max_client_php=$(expr $work_cpucore \* $cpucore \/ 8)
tong_ram_byte=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
rong_ram_mb=$(echo "scale=0;${tong_ram_byte}/1024" | bc)
gioi_han_tien_trinh_bao_loi_503=$(expr $max_client \/ 8)
core_tien_lsphp_child=$(expr $cpucore \* 2)

_runing "Thêm domain $NAME2 vào hệ thống"

check_ky_tu=$(echo $USER | wc -c)
if (($check_ky_tu > 32)); then
  USER=$(echo $USER | cut -c 1-30)
fi

# useradd $USER -p -m -d /usr/local/lsws/$NAME2 >/dev/null 2>&1
useradd -p -m -d /usr/local/lsws/$NAME2 $USER >/dev/null 2>&1

if [[ $(cat /etc/passwd | cut -f1 -d ':' | grep -w $USER) = '' ]]; then
  random=$(
    date +%s | sha256sum | base64 | head -c 2
    echo
  )

  USER=${NAME2//[-._]/$random}
  USER=$(echo $USER | tr '[:upper:]' '[:lower:]')
  check_ky_tu2=$(echo $USER | wc -c)
  if (($check_ky_tu2 > 32)); then
    USER=$(echo $USER | cut -c 1-30)
  fi
  # useradd $USER -p -m -d /usr/local/lsws/$NAME2 >/dev/null 2>&1
  useradd -p -m -d /usr/local/lsws/$NAME2 $USER >/dev/null 2>&1
fi

if [[ $(cat /etc/passwd | cut -f1 -d ':' | grep -w $USER) = '' ]]; then
  _runloi "Thêm domain $NAME vào hệ thống"
  echoDo "Đã có lỗi vấn đề về hệ điều hành không thể tạo user mới"
  wptangtoc 1
  exit
fi

echo "Sao chép website $NAME sang website $NAME2: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

echo "virtualhost $NAME2 {
  vhRoot                  /usr/local/lsws/$NAME2/
  configFile              /usr/local/lsws/conf/vhosts/$NAME2/$NAME2.conf
  allowSymbolLink         1
  enableScript            1
  restrained              1
  maxKeepAliveReq         1000
  setUIDMode              2
  user                    $USER
  group                   $USER
}" >>/usr/local/lsws/conf/httpd_config.conf
sed -i "/listener http/a map 		$NAME2 $NAME2" /usr/local/lsws/conf/httpd_config.conf
mkdir /usr/local/lsws/conf/vhosts/$NAME2/
touch /usr/local/lsws/conf/vhosts/$NAME2/$NAME2.conf
NAMEPHP=${NAME2//[-._]/}
echo "docRoot                   /usr/local/lsws/$NAME2/html
vhDomain                  $NAME2
enableGzip                1
cgroups                   0


index  {
  useServer               0
  indexFiles              index.html index.php
  autoIndex               0
}

scripthandler  {
  add                     lsapi:$NAMEPHP php
}

accessControl  {
  allow                   *
}

lsrecaptcha  {
  enabled                 1
  type                    0
}

extprocessor $NAMEPHP {
  type                    lsapi
  address                 uds://tmp/lshttpd/$NAMEPHP.sock
  maxConns                $core_tien_lsphp_child
  env                     PHP_LSAPI_CHILDREN=$core_tien_lsphp_child
  env                     LSAPI_ACCEPT_NOTIFY=1
  env                     LSAPI_MAX_CMD_SCRIPT_PATH_LEN=200
  env                     LSAPI_AVOID_FORK=300M
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      5
  respBuffer              0
  autoStart               1
  path                    /usr/local/lsws/lsphp74/bin/lsphp
  backlog                 100
  instances               1
  extUser                 $USER
  extGroup                $USER
  runOnStartUp            2
  priority                0
  memSoftLimit            2048M
  memHardLimit            2048M
  procSoftLimit           300
  procHardLimit           400
}

context / {
  location                /usr/local/lsws/$NAME2/html
  allowBrowse             1
  extraHeaders            <<<END_extraHeaders
X-XSS-Protection 1;mode=block
X-Frame-Options SAMEORIGIN
Referrer-Policy strict-origin-when-cross-origin
X-Content-Type-Options nosniff
X-Powered-By WPTangTocOLS
permissions-policy accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
  END_extraHeaders


  rewrite  {

  }
  addDefaultCharset       off

  phpIniOverride  {

  }
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
/usr/local/lsws/$NAME2/html/.htaccess
}

vhssl  {
  keyFile                 /etc/wptt-ssl-tu-ky/$NAME2/$NAME2.key
  certFile                /etc/wptt-ssl-tu-ky/$NAME2/cert.crt
  certChain               0
  sslProtocol             24
  renegProtection         1
  sslSessionCache         1
  sslSessionTickets       1
  enableSpdy              15
  enableQuic              1
}


module cache {
checkPrivateCache   1
checkPublicCache    1
maxCacheObjSize     10000000
maxStaleAge         200
qsCache             1
reqCookieCache      1
respCookieCache     1
ignoreReqCacheCtrl  1
ignoreRespCacheCtrl 0
storagePath /usr/local/lsws/$NAME2/luucache
enableCache         0
expireInSeconds     3600
enablePrivateCache  0
privateExpireInSeconds 3600
  ls_enabled              1
}" >/usr/local/lsws/conf/vhosts/"$NAME2"/"$NAME2".conf

#khởi tạo ssl tự ký
mkdir -p /etc/wptt-ssl-tu-ky/$NAME2
cd /etc/wptt-ssl-tu-ky/$NAME2
openssl req -new -newkey rsa:2048 -nodes -keyout $NAME2.key -out $NAME2.csr -subj "/C=VN/ST=Hanoi/L=Hanoi/O=wptangtoc ols/OU=IT Department/CN=$NAME2/emailAddress=admin@example.com" >/dev/null 2>&1
openssl x509 -req -in $NAME2.csr -signkey $NAME2.key -out cert.crt -days 3650 >/dev/null 2>&1
#end khởi tạo ssl tự ký

#tuong thich ubuntu tuong thich nhom litespeed
if $(cat /etc/*release | grep -q "Ubuntu"); then
  tuong_thich_nhom_litespeed="nogroup"
else
  tuong_thich_nhom_litespeed="nobody"
fi

chown -R lsadm:$tuong_thich_nhom_litespeed /usr/local/lsws/conf/vhosts/"$NAME2"
chmod -R 750 /usr/local/lsws/conf/vhosts/"$NAME2"

mkdir -p /usr/local/lsws/"$NAME2"
mkdir -p /usr/local/lsws/"$NAME2"/html
mkdir -p /usr/local/lsws/"$NAME2"/backup-website
mkdir -p /usr/local/lsws/"$NAME2"/luucache
chmod 755 /usr/local/lsws/"$NAME2"/
chmod 755 /usr/local/lsws/"$NAME2"/html
chmod 700 /usr/local/lsws/"$NAME2"/backup-website

chown -R "$USER":"$USER" /usr/local/lsws/"$NAME2"/html

touch /usr/local/lsws/"$NAME2"/html/.htaccess

echo '# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress' >/usr/local/lsws/"$NAME2"/html/.htaccess

_rundone "Thêm domain $NAME2 vào hệ thống"

name_db=${NAME2//[-._]/}
ramdom_db=$(
  date +%s | sha256sum | base64 | head -c 18
  echo
)
database=${name_db}_${ramdom_db}_dbname
username=${name_db}_${ramdom_db}_username
password=$(
  date +%s | sha256sum | base64 | head -c 36
  echo
)

#toi ky tu database la 64
check_ky_tu_database_name=$(echo $database | wc -c)
if (($check_ky_tu_database_name > 60)); then
  database=$(echo $database | cut -c 1-60)
fi

#toi ky tu database la 64
check_ky_tu_user_name=$(echo $username | wc -c)
if (($check_ky_tu_user_name > 60)); then
  username=$(echo $username | cut -c 1-60)
fi
_runing "Thêm database mới cho website $NAME2"
mariadb -u "$database_admin_username" -p"$database_admin_password" --ssl-verify-server-cert=false -e "DROP DATABASE IF EXISTS ${database}"
mariadb -u "$database_admin_username" -p"$database_admin_password" --ssl-verify-server-cert=false -e "CREATE DATABASE IF NOT EXISTS ${database}"
mariadb -u "$database_admin_username" -p"$database_admin_password" --ssl-verify-server-cert=false -e "DROP USER IF EXISTS '${username}'@'localhost'"
mariadb -u "$database_admin_username" -p"$database_admin_password" --ssl-verify-server-cert=false -e "CREATE USER IF NOT EXISTS '${username}'@'localhost' IDENTIFIED BY '${password}'"
mariadb -u "$database_admin_username" -p"$database_admin_password" --ssl-verify-server-cert=false -e "GRANT ALL PRIVILEGES ON ${database}.* TO '${username}'@'localhost' WITH GRANT OPTION"
mariadb -u "$database_admin_username" -p"$database_admin_password" --ssl-verify-server-cert=false -e "FLUSH PRIVILEGES"
_rundone "Thêm database mới cho website $NAME2"

# php_ver_chon=${php_version_check//[-._]/}
# sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/vhosts/$NAME2/$NAME2.conf
_runing "Sao chép website $NAME sang website $NAME2"
. /etc/wptt/vhost/."$NAME".conf

#config phiên bản php của website gốc
if [[ $phien_ban_php_domain = '' ]]; then
  phien_ban_php_domain=$(php -v | grep cli | grep -oP 'PHP \K[0-9]+\.[0-9]+')
fi

php_ver_chon=${phien_ban_php_domain//[-._]/}

sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/vhosts/$NAME2/$NAME2.conf

mkdir -p "/usr/local/lsws/database"
file_sql=${database}.sql
duong_dan_thu_muc="/usr/local/lsws/database/$file_sql"
mariadb-dump -u "$database_admin_username" -p"$database_admin_password" "$DB_Name_web" --ssl-verify-server-cert=false >"$duong_dan_thu_muc"
mariadb -h localhost -u "$database_admin_username" -p"$database_admin_password" "$database" --ssl-verify-server-cert=false <"$duong_dan_thu_muc"
rm -f "$duong_dan_thu_muc"
duong_dan_nguon_cu="/usr/local/lsws/$NAME/html"
duong_dan_nguon_moi21="/usr/local/lsws/$NAME2"
duong_dan_nguon_moi="/usr/local/lsws/$NAME2/html"
cp -r "$duong_dan_nguon_cu" "$duong_dan_nguon_moi21"

if [[ $(lsattr /usr/local/lsws/$NAME2/html/wp-config.php | cut -f1 -d ' ' | grep 'i') ]]; then #lockdown check sử lý nếu website nguồn triển khai lockdown, tắt lockdown mã nguồn mới
  . /etc/wptt/bao-mat/wptt-chattr-file-lock $NAME2 off
  find /usr/local/lsws/"$NAME2"/html -type f -print0 | xargs -0 chmod 644
  find /usr/local/lsws/"$NAME2"/html -type d -print0 | xargs -0 chmod 755
fi

sed -i "/DB_HOST/s/'[^']*'/'localhost'/2" "/usr/local/lsws/$NAME2/html/wp-config.php"
sed -i "/DB_NAME/s/'[^']*'/'$database'/2" "/usr/local/lsws/$NAME2/html/wp-config.php"
sed -i "/DB_USER/s/'[^']*'/'$username'/2" "/usr/local/lsws/$NAME2/html/wp-config.php"
sed -i "/DB_PASSWORD/s/'[^']*'/'$password'/2" "/usr/local/lsws/$NAME2/html/wp-config.php"

cd /usr/local/lsws/"$NAME2"/html/

. /etc/wptt/php/php-cli-domain-config $NAME #sử dụng php của NAME domain gốc

#thay cache_key tránh xung đột khi dùng object cache
/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp config shuffle-salts WP_CACHE_KEY_SALT --force --path=/usr/local/lsws/$NAME2/html --allow-root >/dev/null 2>&1

for line_num in $(grep -n "define( 'WP_CACHE_KEY_SALT'" /usr/local/lsws/$NAME2/html/wp-config.php | head -n -1 | cut -d: -f1 | tac); do sed -i "${line_num}d" /usr/local/lsws/$NAME2/html/wp-config.php; done #để sửa trùng loọp nếu có WP_CACHE_KEY_SALT chỉ dữ liệu một cái WP_CACHE_KEY_SALT

if [[ $(cat /usr/local/lsws/$NAME2/html/wp-config.php | grep WP_CACHE_KEY_SALT) = '' ]]; then #chưa add WP_CACHE_KEY_SALT, thì add lại điều kiện
  sed -i "/define( 'WP_CACHE_KEY_SALT'/d" /usr/local/lsws/$NAME2/html/wp-config.php && sed -i "/^define( 'NONCE_SALT'/a define( 'WP_CACHE_KEY_SALT', '$NAME2' );" /usr/local/lsws/$NAME2/html/wp-config.php
  /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp config shuffle-salts WP_CACHE_KEY_SALT --force --path=/usr/local/lsws/$NAME2/html --allow-root >/dev/null 2>&1
  for line_num in $(grep -n "define( 'WP_CACHE_KEY_SALT'" /usr/local/lsws/$NAME2/html/wp-config.php | head -n -1 | cut -d: -f1 | tac); do sed -i "${line_num}d" /usr/local/lsws/$NAME2/html/wp-config.php; done #để sửa trùng loọp nếu có WP_CACHE_KEY_SALT chỉ dữ liệu một cái WP_CACHE_KEY_SALT
fi

/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp search-replace "//${NAME}" "//${NAME2}" --path="$duong_dan_nguon_moi" --allow-root >/dev/null 2>&1
/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp cache flush --allow-root --path="$duong_dan_nguon_moi" >/dev/null 2>&1
/usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp rewrite flush --allow-root --path="$duong_dan_nguon_moi" >/dev/null 2>&1
checkplugin="/usr/local/lsws/$NAME2/html/wp-content/plugins/litespeed-cache"
if [[ -d $checkplugin ]]; then
  /usr/local/lsws/lsphp${phien_ban_php_domain_thuc_thi}/bin/php /usr/local/bin/wp litespeed-purge all --allow-root --path="$duong_dan_nguon_moi" >/dev/null 2>&1
fi

chown -R $USER:$USER /usr/local/lsws/$NAME2/html
chown -R $USER:$USER /usr/local/lsws/$NAME2/backup-website

if [[ ! -f /usr/local/lsws/$NAME2/.bashrc ]]; then
  cp -rf /etc/skel/. /usr/local/lsws/$NAME2
fi

chown $USER:$USER /usr/local/lsws/$NAME2/.*

chmod 700 /usr/local/lsws/$NAME2/backup-website

mkdir -p /usr/local/backup-website/"$NAME2"

mkdir -p /wptangtoc-ols
mkdir -p /wptangtoc-ols/"$NAME2"
mkdir -p /wptangtoc-ols/"$NAME2"/backup-website

ln -s /usr/local/lsws/"$NAME2"/html /wptangtoc-ols/"$NAME2"
ln -s /usr/local/backup-website/"$NAME2"/ /wptangtoc-ols/"$NAME2"/backup-website

#anh xa thu muc home
ln -s /usr/local/lsws/$NAME2 /home/$NAME2

if [[ -f /usr/local/lsws/$NAME2/html/wp-content/db.php ]]; then
  rm -f /usr/local/lsws/$NAME2/html/wp-content/db.php
fi

#usermod -a -G wptangtoc-ols $USER

# khong cho login quyen tai khoan trực tiếp chỉ sử dụng để làm sử dụng php exec
usermod $USER -s /sbin/nologin

# echo '[[ $- != *i* ]] && return' >> /home/$USER/.bashrc
# echo ". /etc/wptt-user/wptt-status" >> /home/$USER/.bashrc
# echo "alias 1='wptangtoc-user'" >> /home/$USER/.bashrc
# echo "alias 11='wptangtoc-user'" >> /home/$USER/.bashrc

echo '[[ $- != *i* ]] && return' >>/usr/local/lsws/$NAME2/.bashrc
echo ". /etc/wptt-user/wptt-status" >>/usr/local/lsws/$NAME2/.bashrc
echo "alias 1='wptangtoc-user'" >>/usr/local/lsws/$NAME2/.bashrc
echo "alias 11='wptangtoc-user'" >>/usr/local/lsws/$NAME2/.bashrc

# mkdir -p /home/$USER/$NAME2
# ln -s /usr/local/lsws/$NAME2/html /home/$USER/$NAME2/public_html
# ln -s /usr/local/lsws/$NAME2/backup-website /home/$USER/$NAME2/backup-website

if [[ -f /usr/local/lsws/$NAME2/html/wp-config.php ]]; then
  sed -i "/WP_SITEURL/d" /usr/local/lsws/$NAME2/html/wp-config.php
  sed -i "/WP_HOME/d" /usr/local/lsws/$NAME2/html/wp-config.php
  if [[ -d /usr/local/lsws/$NAME2/html/wp-content/cache ]]; then
    rm -rf /usr/local/lsws/$NAME2/html/wp-content/cache
  fi
fi

#xoá chuyển hướng
sed -i -e '/^#begin-chuyen-huong-www-to-non-www-wptangtoc-ols/,/^#end-chuyen-huong-www-to-non-www-wptangtoc-ols$/d' /usr/local/lsws/$NAME2/html/.htaccess
sed -i -e '/^#begin-chuyen-huong-non-www-to-www-wptangtoc-ols/,/^#end-chuyen-huong-non-www-to-www-wptangtoc-ols$/d' /usr/local/lsws/$NAME2/html/.htaccess

hostname_custom=$(cat /usr/local/lsws/conf/vhosts/$Website_chinh/$Website_chinh.conf | grep 'X-Powered-By' | cut -f2 -d ' ' | sort -u)
if [[ $hostname_custom = '' || $hostname_custom != 'WPTangTocOLS' ]]; then
  sed -i '/X-Powered-By/d' /usr/local/lsws/conf/vhosts/$NAME2/$NAME2.conf
fi

if [[ $hostname_custom != 'WPTangTocOLS' ]]; then
  if [[ $hostname_custom ]]; then
    sed -i "/extraHeaders /a X-Powered-By $hostname_custom" /usr/local/lsws/conf/vhosts/$NAME2/$NAME2.conf #custom hostname
  fi
fi

unset hostname_custom

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

php_version=$(php -v | grep cli | grep -oP 'PHP \K[0-9]+\.[0-9]+')

touch /etc/wptt/vhost/."$NAME2".conf
echo "DB_Name_web=$database
DB_User_web=$username
DB_Password_web=$password
Duong_Dan_thu_muc_web=/usr/local/lsws/$NAME2/html
User_name_vhost=$USER
phien_ban_php_domain=$phien_ban_php_domain" >/etc/wptt/vhost/."$NAME2".conf

chown root:root /etc/wptt/vhost/.$NAME2.conf
chmod 700 /etc/wptt/vhost/.$NAME2.conf

# _runing "Xóa cache"
. /etc/wptt/cache/wptt-xoacache $NAME2 >/dev/null 2>&1
# _rundone "Xóa cache"
. /etc/wptt/wordpress/thay-salt $NAME2 >/dev/null 2>&1

#đếm số lượng website nếu lớn 5 sẽ chuyển sang mode nhiều web
if (($(ls -A /etc/wptt/vhost | wc -l) > 10)); then
  . /etc/wptt/cau-hinh/wptt-litespeed-config-cau-hinh-optimize-nhieu-web >/dev/null 2>&1
fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

#setup lại vhost nếu trong trường hợp người dùng đã kích hoạt ssl trả phí trước đó để clean lại

if [[ -f /etc/letsencrypt/live/$NAME2/cert.pem ]]; then #nếu domain cũ đã có ssl letsencrypt sẵn thì config vào luôn
  sed -i -e '/^vhssl /,/^}$/d' /usr/local/lsws/conf/vhosts/$NAME2/$NAME2.conf
  echo "vhssl  {
keyFile                 /etc/letsencrypt/live/$NAME2/privkey.pem
certFile                /etc/letsencrypt/live/$NAME2/cert.pem
certChain               0
CACertFile              /etc/letsencrypt/live/$NAME2/chain.pem
sslProtocol             24
renegProtection         1
sslSessionCache         1
sslSessionTickets       1
enableSpdy              15
enableQuic              1
}

" >>/usr/local/lsws/conf/vhosts/"$NAME2"/"$NAME2".conf
  /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi

_rundone "Sao chép website $NAME_NGUON sang website $NAME2"

echo "==================================================================="
echo "Hoàn tất sao chép $NAME_NGUON sang $NAME2               "
echo "==================================================================="
echo "==================================================================="
echo "Disk  : $(df -BG | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')                        "
echo "RAM   : $(free -m | awk 'NR==2{printf "%s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }')                         "
echo "==================================================================="
echo "Đường dẫn thư mục website: /usr/local/lsws/$NAME2/html              "
echo "==================================================================="
echo "Phần mềm phát triển bởi: Gia Tuấn"
echo "==================================================================="
checkdns=$(host $NAME2 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
if [[ "$checkdns" = "" ]]; then
  checkdns=$(nslookup $NAME2 | grep Address | cut -f5 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
fi

ip=$(curl -sf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com || curl -sf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com)

if [[ "$checkdns" != "$ip" ]]; then
  if [[ "$checkdns" = "" ]]; then
    echo "Tên miền $NAME2 chưa được trỏ IP, giá trị IP của $NAME là không có giá trị nào, bạn vui lòng trỏ IP về $ip"
  else
    echo "Hãy trỏ DNS domain $NAME2: $checkdns thành $ip để tận hưởng thành quả"
  fi
fi

. /etc/wptt/.wptt.conf
if [[ $download_api ]]; then
  if [[ -f /etc/wptt/add-one/check.sh ]]; then
    if [[ $email_check_downtime && $telegram_id ]]; then
      . /etc/wptt/add-one/check.sh $telegram_id $telegram_api $email >/dev/null 2>&1
    fi
    if [[ -z $email_check_downtime && $telegram_id ]]; then
      . /etc/wptt/add-one/check.sh $telegram_id $telegram_api >/dev/null 2>&1
    fi
    if [[ $email_check_downtime && -z $telegram_id ]]; then
      . /etc/wptt/add-one/check.sh $email_check_downtime >/dev/null 2>&1
    fi
  fi
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  wptangtoc 1
fi
