#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo "$quan_ly_update:"
echo ""
options=(
    "$update_wptangtoc_ols"                   #1
    "$cap_nhat_toan_bo_webserver"               #2
    "$cai_lai OpenLiteSpeed Webserver"          #3
    "$cap_nhat Rclone Google Drive"           #4
    "$cap_nhat WP CLI"                          #5
    "$kich_hoat_tu_dong_update_wptangtoc_ols" #6
    "$tat_kich_hoat_tu_dong_update_wptangtoc_ols"       #7
    "$kiem_tra_phien_ban_cac_service"                       #8
    "$cap_nhat PhpMyAdmin"                       #9
	"$chuyen_nhanh_wptangtoc_ols_chinh_thuc"     #10
	"$chuyen_nhanh_wptangtoc_ols_beta"           #11
)

# Hàm thực thi hành động dựa trên index (cho menu Quản lý Update)
run_action() {
    local index=$1
    local script_path=""
    local arg1="" # Tham số thứ nhất
    local arg2="" # Tham số thứ hai (nếu có)

    case $index in
         0) script_path="/etc/wptt/wptt-update";                    arg1="98" ;;
         1) script_path="/etc/wptt/update/wptt-update-he-thong";    arg1="98" ;;
         2) script_path="/etc/wptt/wptt-cai-lai";                   arg1="98" ;;
         3) script_path="/etc/wptt/update/wptt-update-rclone";      arg1="98" ;;
         4) script_path="/etc/wptt/update/wptt-wp-cli";             arg1="98" ;;
         5) script_path="/etc/wptt/update/wptt-auto-update";        arg1="98" ;;
         6) script_path="/etc/wptt/update/wptt-tat-auto-update";    arg1="98" ;;
         7) script_path="/etc/wptt/update/wptt-kiem-tra-version";   arg1="98" ;;
         8) script_path="/etc/wptt/update/wptt-update-phpmyadmin";  arg1="98" ;;
         9) script_path="/etc/wptt/wptt-update2";                   arg1="chinhthuc"; arg2="98" ;; # Tham số đặc biệt
        10) script_path="/etc/wptt/wptt-update2";                   arg1="beta";      arg2="98" ;; # Tham số đặc biệt
        *) echo "${lua_chon_khong_hop_le:-Lựa chọn không hợp lệ}: Index $index."; return 1 ;;
    esac

    # Kiểm tra và chạy script con
    if [[ -x "$script_path" ]]; then
        # Kiểm tra xem có tham số thứ hai không để gọi script cho đúng
        if [[ -n "$arg2" ]]; then
            "$script_path" "$arg1" "$arg2" # Gọi với 2 tham số theo thứ tự đã đặt
        elif [[ -n "$arg1" ]]; then
             "$script_path" "$arg1"        # Gọi với 1 tham số
        else
             "$script_path"                # Gọi không có tham số (dự phòng, không xảy ra với logic hiện tại)
        fi
    else
        echo "Lỗi: Không tìm thấy hoặc không thể thực thi script '$script_path'."
    fi
    # read -rp "Nhấn Enter để quay lại menu..." # Bỏ comment nếu muốn tạm dừng
}

. /etc/wptt/wptt-callback-menu-chon

