#!/bin/bash
. /etc/wptt/.wptt.conf

if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo "Phân quyền toàn bộ website : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

chown root:root /usr/local/lsws #cải tiên phân quyền chown root:root thư mục :/usr/local/lsws để nâng cao bảo mật

if [ "$(ls -A /etc/wptt/vhost)" ]; then
  echo ""
  echo ""
  echo "$phan_quyen $toan_bo website ..."

  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
      . /etc/wptt/wptt-phan-quyen2 $domain
    fi
  done

fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
clear

function box_out()
{
  local s=("$@") b w
  for l in "${s[@]}"; do
    ((w<${#l})) && { b="$l"; w="${#l}"; }
  done
  tput setaf 3
  echo " -${b//?/-}-
| ${b//?/ } |"
  for l in "${s[@]}"; do
    printf '| %s%*s%s |\n' "$(tput setaf 4)" "-$w" "$l" "$(tput setaf 3)"
  done
  echo "| ${b//?/ } |
 -${b//?/-}-"
  tput sgr 0
}


echo "==================================================================="
echo "$hoan_tat $phan_quyen $toan_bo website $tren_he_thong"
echo "==================================================================="
echo "$thanh_cong $phan_quyen $toan_bo website: "

for entry in $(ls -A /etc/wptt/vhost); do
  domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
  path="/usr/local/lsws/$domain/html"
  i=1

  if [[ -d "$path" ]]; then
    box_out "$hoan_tat $phan_quyen website: $domain"
  fi
done

echo "==================================================================="
echo "$phat_trien_boi_gia_tuan"
echo "==================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "99" ]];then
wptangtoc 1
fi

