#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
echo ""
echo ""
echo "$bao_mat:"
echo ""
options=(
	"$bat ModSecurity"                                                                #1
	"$tat ModSecurity"                                                            #2
	"$bat $baomat Brute Force WordPress"                                                #3
	"$tat $baomat Brute Force WordPress"                                            #4
	"$danh_sach_ip_da_bi_khoa by Brute Force WordPress"                                           #5
	"$mo_khoa_ip Brute Force WordPress"                                                     #6
	"$bat Hotlinking"                                                                 #7
	"$them_domain_vuot_qua Hotlinking"                                                      #8
	"$tat Hotlinking"                                                             #9
	"$bat $bao_mat_2_lop WordPress WP-Admin"                                                    #10
	"$tat $bao_mat_2_lop WordPress WP-Admin"                                                #11
	"$xem_thong_tin_tai_khoan_bao_mat_2_lop"                                                #12
	"$quet virus domain"                                                               #13
	"$quet virus ALL domain"                                                           #14
	"$xoa_phan_mem_diet_virus"                                                              #15
	"$thiet_lap telegram chat"                                                              #16
	"$thiet_lap $canh_bao login SSH"                                                        #17
	"$thiet_lap $canh_bao downtime website"                                                  #18
	"$bat $chong DDOS website"                                                         #19
	"$tat $chong DDOS website"                                                     #20
	"$thiet_lap $canh_bao telegram $khi_sap_het_tai_nguyen"                           #21
	"$thiet_lap_canh_bao_service_ngung_hoat_dong" #22
	"$bat $tuong_lua 8G" #23
	"$tat $tuong_lua 8G" #24
	"$bat/$tat open_basedir PHP" #25
	"$bat/$tat $ham_nguy_hiem_cua_php" #26
	"$quan_ly CSF" #27
	"$bat/$tat $che_do_phong_thu_toi_dang_bi_ddos" #28
	"$bat/$tat $chong DDOS IP" #29
	"$bat/$tat $chong bad bot" #30
	"$bat $chong xmlrpc" #31
	"$tat $chong xmlrpc" #32
	"$bat/$tat LockDown WordPress" #33
	"$bat/$tat $chong DDOS 404"
	"$bat/$tat $chong DDOS $tim_kiem"
	"$bat/$tat $chong HTTP 403 website ALL"
)

PS3="
$(tput setab 0)$nhap_lua_chon_cua_ban (1-${#options[@]}) [0=$exit_thoat]:$(tput sgr0) "
select opt in "${options[@]}"; do
    case $opt in
    "${options[0]}")
        "/etc/wptt/bao-mat/wptt-modsecurity" 98
        ;;
    "${options[1]}")
        "/etc/wptt/bao-mat/wptt-tat-modsecurity" 98
        ;;
    "${options[2]}")
        "/etc/wptt/bao-mat/wptt-admin-bao-mat" 98
        ;;
    "${options[3]}")
        "/etc/wptt/bao-mat/wptt-admin-xoa" 98
        ;;
    "${options[4]}")
        "/etc/wptt/bao-mat/wptt-admin-danh-sach-block" 98
        ;;
    "${options[5]}")
        "/etc/wptt/bao-mat/wptt-admin-mo-khoa" 98
        ;;

    "${options[6]}")
        "/etc/wptt/bao-mat/wptt-hotlinking" 98
        ;;

    "${options[7]}")
        "/etc/wptt/bao-mat/add-domain-hotlinking" 98
        ;;

    "${options[8]}")
        "/etc/wptt/bao-mat/wptt-xoa-hotlinking" 98
        ;;

    "${options[9]}")
        "/etc/wptt/wordpress/bao-mat-2lop" 98
        ;;
    "${options[10]}")
        "/etc/wptt/wordpress/tat-bao-mat-2lop" 98
        ;;

    "${options[11]}")
        "/etc/wptt/bao-mat/wptt-kiem-tra-tai-khoan-bao-mat-2lop" 98
        ;;
    "${options[12]}")
        "/etc/wptt/bao-mat/wptt-scan-virus" 98
        ;;

    "${options[13]}")
        "/etc/wptt/bao-mat/wptt-scan-virus-all-domain" 98
        ;;

    "${options[14]}")
        "/etc/wptt/bao-mat/wptt-scan-virus-xoa-phan-mem" 98
        ;;

    "${options[15]}")
        "/etc/wptt/bao-mat/wptt-telegram" 98
        ;;

    "${options[16]}")
        "/etc/wptt/bao-mat/thong-bao-login-ssh" 98
        ;;

    "${options[17]}")
        "/etc/wptt/bao-mat/wptt-canh-bao-downtime-thiet-lap" 98
        ;;

    "${options[18]}")
        "/etc/wptt/bao-mat/wptt-canh-bao-ddos-thiet-lap" 98
        ;;

    "${options[19]}")
        "/etc/wptt/bao-mat/wptt-canh-bao-ddos-thiet-lap-xoa" 98
        ;;

	"${options[20]}")
		"/etc/wptt/bao-mat/wptt-thong-bao-het-tai-nguyen-thiet-lap" 98
		;;

	"${options[21]}")
		"/etc/wptt/service/reboot-app/wptt-auto-reboot-thiet-lap" 98
		;;

	"${options[22]}")
		"/etc/wptt/bao-mat/wptt-firewall-7g" 98
		;;

	"${options[23]}")
		"/etc/wptt/bao-mat/wptt-tat-firewall-7g" 98
		;;

	"${options[24]}")
		"/etc/wptt/bao-mat/bat-tat-open-basedir" 98
		;;

	"${options[25]}")
		"/etc/wptt/bao-mat/bat-tat-ham-function-php-nguy-hiem" 98
		;;

	"${options[26]}")
		"/etc/wptt/bao-mat/csf-main" 98
		;;

	"${options[27]}")
		"/etc/wptt/bao-mat/mod-ddos-litespeed" 98
		;;

	"${options[28]}")
		"/etc/wptt/bao-mat/wptt-chong-ddos-ip-thiet-lap" 98
		;;

	"${options[29]}")
		"/etc/wptt/bao-mat/wptt-block-bad-bot" 98
		;;

	"${options[30]}")
		"/etc/wptt/bao-mat/wptt-chan-xmlrpc-block-fail2ban" 98
		;;

	"${options[31]}")
		"/etc/wptt/bao-mat/wptt-xmlrpc-xoa" 98
		;;

	"${options[32]}")
		"/etc/wptt/bao-mat/wptt-lock-down" 98
		;;

	"${options[33]}")
		"/etc/wptt/bao-mat/bao-mat-ddos-404" 98
		;;

	"${options[34]}")
		"/etc/wptt/bao-mat/ddos-search" 98
		;;

	"${options[35]}")
		"/etc/wptt/bao-mat/wptt-ddos-403-bi-pham-block-http" 98
		;;
	*) wptangtoc 1 ;;
    esac
done
