#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/tenmien
echo "Lua chon website ban muon phan quyen: "
echo ""
lua_chon_NAME

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
    clear
    wptangtoc
    exit
fi
. /etc/wptt/.wptt.conf
. /etc/wptt/vhost/."$NAME".conf
. /etc/wptt/echo-color
echo "Dang tien hanh phan quen website $NAME..."
chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$NAME"/html
find /usr/local/lsws/"$NAME"/html -type d -exec chmod 755 {} \;
find /usr/local/lsws/"$NAME"/html -type f -exec chmod 644 {} \;
chmod 444 /usr/local/lsws/"$NAME"/html/index.php
chmod 600 /usr/local/lsws/"$NAME"/html/wp-config.php

if [[ -f /usr/local/lsws/"$NAME"/html/wp-load.php ]];then
wp rewrite flush --allow-root --path=/usr/local/lsws/"$NAME"/html
fi

if [[ $id_dang_nhap_phpmyadmin && $Website_chinh = $NAME ]];then
if [[ -d /usr/local/lsws/"$NAME"/html/phpmyadmin ]];then
chown -R nobody:nobody /usr/local/lsws/"$NAME"/html/phpmyadmin
fi
fi
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
clear
echoDone "==================================================================="
echoDone "               Phan quyen website $NAME thanh cong                 "
echoDone "==================================================================="
echoDone "     Phan quyen thu muc :/usr/local/lsws/$NAME/html                "
echoDone "==================================================================="
echo "==================================================================="
echo "Cong cu phat trien boi: Gia Tuan"
echo "Yeu Cau Ho tro: wptangtoc.com/lien-he"
echo "==================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-domain-main 1
fi

