#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/echo-color
clear
RED='\033[0;31m'
NC='\033[0m'
echo "//---------------------------------------------------------------------//"
echo "$update_wptangtoc_ols"
echo "-------------------------------------------------------------------------"
echo "$kiem_tra... $phien_ban $cua $he_thong"
echo -e "$phien_ban $hien_tai_cua_ban_la: ${RED} $version_wptangtoc_ols ${NC}"
echo "..."
sleep 2
echo ".."
echo "/-----------------------------------------------------------------------/"
wptangtocols_version=$(curl -s https://wptangtoc.com/share/version-wptangtoc-ols.txt?domain-update="$Website_chinh")

if [[ $wptangtocols_version = '' ]];then
echoDo "$da_xay_ra_loi_vui_long_thu_lai_sau"
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-update-main 1
		exit
	fi

	if [[ $check_menu_wptangtoc_active = "97" ]];then
		sleep 2
		wptangtoc
		exit
	fi

	. /etc/wptt/wptt-status2
	exit	
fi


if [[ "$wptangtocols_version" = "$version_wptangtoc_ols" ]]; then
	echo "-----------------------------------------------------------------------"
	echo "###############   $ban_dang_su_dung_phien_ban_moi_nhat   ###############"
	echo "-----------------------------------------------------------------------"
	sleep 2
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-update-main 1
		exit
	fi

	if [[ $check_menu_wptangtoc_active = "97" ]];then
		sleep 2
		wptangtoc
		exit
	fi
	. /etc/wptt/wptt-status2
else
	echo -e "$xac_nhan $cap_nhat $phien_ban WPTangToc OLS ${RED}$wptangtocols_version${NC} ?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done

	if [[ "$dongy" = 'y' ]]; then
		echo "$dang_tien_hanh $cap_nhat"
		sleep 1
		cd
		rm -f wptangtoc-ols.zip
		rm -f wptangtoc-ols-user.zip
		wget -q http://wptangtoc.com/share/wptangtoc-ols-user.zip --no-check-certificate
		wget -q http://wptangtoc.com/share/wptangtoc-ols.zip --no-check-certificate

		if [[ ! -f wptangtoc-ols.zip ]];then
			if [[ $wptangtocols_version ]];then
				echo "$wptangtocols_version" > /tmp/wptangtoc-ols-version
			fi
			echoDo "$cap_nhat WPTangToc OLS $da_xay_ra_loi_vui_long_thu_lai_sau"
			check_menu_wptangtoc_active=$1
			if [[ $check_menu_wptangtoc_active = "98" ]];then
				. /etc/wptt/wptt-update-main 1
				exit
			fi

			if [[ $check_menu_wptangtoc_active = "97" ]];then
				sleep 2
				wptangtoc
				exit
			fi
			. /etc/wptt/wptt-status2
			exit
		fi

		if [[ ! -f wptangtoc-ols-user.zip ]];then
			if [[ $wptangtocols_version ]];then
				echo "$wptangtocols_version" > /tmp/wptangtoc-ols-version
			fi
			echoDo "$cap_nhat WPTangToc OLS $da_xay_ra_loi_vui_long_thu_lai_sau"
			check_menu_wptangtoc_active=$1
			if [[ $check_menu_wptangtoc_active = "98" ]];then
				. /etc/wptt/wptt-update-main 1
				exit
			fi

			if [[ $check_menu_wptangtoc_active = "97" ]];then
				sleep 2
				wptangtoc
				exit
			fi
			. /etc/wptt/wptt-status2
			exit
		fi


		unzip -oq wptangtoc-ols.zip
		\cp -rf tool-wptangtoc-ols/* /etc/wptt/
		rm -f wptangtoc-ols.zip
		rm -rf tool-wptangtoc-ols
		chmod -R 700 /etc/wptt
		chown root:wptangtoc-ols /etc/wptt
		chown root:wptangtoc-ols /etc/wptt/vhost
		chmod 750 /etc/wptt
		chmod 750 /etc/wptt/vhost
		\cp -f /etc/wptt/wptangtoc /usr/bin
		rm -f /etc/wptt/wptangtoc
		\cp -f /etc/wptt/wptt /usr/bin
		rm -f /etc/wptt/wptt


		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path="/usr/local/lsws/$domain/html"
			i=1
			if [[ -d "$path" && -f /etc/wptt/vhost/.$domain.conf ]]; then
				. /etc/wptt/vhost/.$domain.conf
				if [[ $User_name_vhost ]];then
					chown $User_name_vhost:$User_name_vhost /etc/wptt/vhost/.$domain.conf
				fi
			fi
		done


		unzip -qo wptangtoc-ols-user.zip
		cd tool-wptangtoc-ols-user
		cd ..
		\cp -rf tool-wptangtoc-ols-user/* /etc/wptt-user
		rm -f wptangtoc-ols-user.zip
		rm -rf tool-wptangtoc-ols-user
		chown -R root:wptangtoc-ols /etc/wptt-user
		chmod -R 750 /etc/wptt-user
		\cp -f /etc/wptt-user/wptangtoc-user /usr/bin
		chown root:wptangtoc-ols /usr/bin/wptangtoc-user
		chmod 750 /usr/bin/wptangtoc-user
		rm -f /etc/wptt-user/wptangtoc-user


		#child ma nguon wptangtoc

		if [[ -d /etc/wptt-child ]];then
			\cp -rf /etc/wptt-child/* /etc/wptt
		fi


		if [[ $key_activate ]];then
			wget -q https://key.wptangtoc.com/?${key_activate} --no-check-certificate -U "Activate key WPTangToc OLS" -O premium.zip
			if [[ -s premium.zip ]];then
				unzip -oq premium.zip -d /etc/wptt/add-one
				rm -f premium.zip
				chmod -R 700 /etc/wptt/add-one
			fi
		fi

		echo "$dang_tien_hanh_cap_nhat_vui_long_doi"
		sleep 2
		curl -sO https://wptangtoc.com/share/update && bash update
		rm -f update
		sed -i "/version_wptangtoc_ols/d" /etc/wptt/.wptt.conf
		echo "version_wptangtoc_ols=$wptangtocols_version" >>/etc/wptt/.wptt.conf
		echo "$wptangtocols_version" > /tmp/wptangtoc-ols-version
		echo "$version_wptangtoc_ols" > /tmp/wptangtoc-ols-version-main

		clear
		echo "/-----------------------------------------------------------------------/"
		echoDone "$cap_nhat $hoan_tat"
		echo "/-----------------------------------------------------------------------/"
		echo -e "$he_thong $cap_nhat $phien_ban WPTangToc OLS $moi_nhat:${RED} $wptangtocols_version ${NC}"
		echo "/-----------------------------------------------------------------------/"
		sleep 3
		echo "$cam_on_ban_da_lua_chon WPTANGTOC OLS."
		echo "$phat_trien_boi_gia_tuan"
		sleep 1
		check_menu_wptangtoc_active=$1
echo "Cập nhật WPTangToc OLS : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

		if [[ $check_menu_wptangtoc_active ]];then
		if [[ $check_menu_wptangtoc_active = "98" ]];then
			sleep 2
			. /etc/wptt/wptt-update-main 1
			exit
		fi

		if [[ $check_menu_wptangtoc_active = "97" ]];then
			sleep 2
			wptangtoc 1
			exit
		fi
		fi

		. /etc/wptt/wptt-status2

	fi
fi
