#!/bin/bash

function huong_dan(){
Hỗ trợ phát triển phần mềm WPTangToc OLS. rất biết ơn sự đóng góp của bạn nhằm hỗ trợ sứ mệnh của chúng tôi trong việc xây dựng một phần mềm thiết lập và quản trị webserver miễn phí mà hiệu suất tốt nhất.

Bánh mì trên bàn không phải là miễn phí, mặc dù phần mềm này miễn phí, và sẽ luôn như vậy. Mình thích phát triển phần mềm này và hỗ trợ các bạn, nhưng mình cũng cần bánh mì. Vui lòng tạo điều kiện để tôi tiếp tục nỗ lực vào phần mềm này:
}


clear

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh


RED='\033[0;31m'
NC='\033[0m'

echo -e "${RED}
     .:..........................             
      .::::::::::::::::::::::::::::..         
        ..:::::::::::::::::::::::::::::.      
                             ...:::::::::.    
                                  .:::::::.   
          .:::::::.         .       .:::::::  
         .::::::::::::::::::::..      ::::::: 
         ::::::::::::::::::::::::.     ::::::.
        .::::::::::::::::::::::::::.   .:::::.
        .::::::::::::::::::::::::::::  .:::::.
        .::::::::::::::::::::::::::.   .:::::.
         ::::::::::::::::::::::::.     ::::::.
.::::::  .:::::::::::::::::::::.      ::::::. 
          .:::::::.                 .:::::::  
       ::::::::::::.              .:::::::.   
       ......:::::::::...    ...:::::::::.    
               .:::::::::::::::::::::::.      
   ..............::::::::::::::::::..         
  .:::::::::::::................. ${NC}"


echo "$thay_mat_cong_dong_cam_on"

curl https://wptangtoc.com/donate/ 2>/dev/null| grep '<h2 class'| head -1 |sed -e 's|</b>|-|g' -e 's|<[^>]*>||g'
echo ''

curl https://wptangtoc.com/donate/ 2>/dev/null| sed -e '/<li>/,/li>/!d' | sed '/footer/d' | sed '/div/d' | sed '/wptangtoc.com/d' | sed '/class/d' | sed '/^$/d' | sed '/wptangtoc/d' | sed '/dieu-khoan-dich-vu/d' | sed '/chinh-sach-thanh-toan/d' | sed '/tel:0/d' | sed 's/<li>//g' | sed 's/<\/li>//g' | sed '/html>/d'| sed '/Vui lòng ghi: nội dung/d' | sed -e 's|</b>|-|g' -e 's|<[^>]*>||g'

echo ""
echo ""
echo "$giup_wptangtoc_ols_luon_luon_su_dung_mien_phi_tai_tro_cho_du_an"
echo "$minh_gia_tuan_rat_biet_on"
echo "$trong_viec_xay_dung_mot_phan_mem_quan_tri"
echo "======================================================="
echo "paypal: https://www.paypal.com/paypalme/wptangtoc"
echo "======================================================="
echo "Binance USDT: 0x808cb81614546e0a3a939afa486c28a4f8dc38f0"
echo "======================================================="
echo "$thong_tin_tai_khoan_ngan_hang:"
echo "Số tài khoản: 2222223338888"
echo "Chủ tài khoản: Hoàng Gia Tuấn"
echo "Ngân hàng MBBank"
echo "======================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
sleep 10
wptangtoc 1
fi

