#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/tenmien
echo "Lua chon website ban muon reset htaccess: "
echo ""
lua_chon_NAME

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
    clear
    wptangtoc
    exit
fi

echo 'Dang tien hanh htaccess website $NAME...'
echo '                                              
              .:-=++*****++=-:.               
           :=+******++++++*****+=:.           
        .-+***+-:.          .-=**++=:         
       =***+-.                  :=*++=:       
     :+**+-                       .=*++=      
     +**=                           :+++=     
      ..                             .+++=    
                                      .+++-   
    ==                               . =+++   
  :+**=                              +****+==-
 -*****=                              +***++-.
=*******+                             .*+++:  
  .***=..                              .+-    
   =***                                       
    ***+                                      
    .***+.                          .==+:     
     .+***=.                       -*++=.     
       -+***=.                  .-+*++-       
         -+***+=:.          .:=+**+=-         
           .-+******++++++*****+=-.           
               :-==+*****++=-:.               
                                              
'
. /etc/wptt/vhost/."$NAME".conf
echo '<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>' > /usr/local/lsws/"$NAME"/html/.htaccess
. /etc/wptt/ssl/wptt-renew-chuyen-huong $NAME
chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$NAME"/html
find /usr/local/lsws/"$NAME"/html -type d -exec chmod 755 {} \;
find /usr/local/lsws/"$NAME"/html -type f -exec chmod 644 {} \;
chmod 444 /usr/local/lsws/"$NAME"/html/index.php
chmod 600 /usr/local/lsws/"$NAME"/html/wp-config.php
wp rewrite flush --allow-root --path=/usr/local/lsws/"$NAME"/html
/usr/local/lsws/bin/lswsctrl restart
echo "==================================================================="
echo "               Hoan tat reset htaccess                 "
echo "==================================================================="
echo "Cong cu phat trien boi: Gia Tuan"
echo "Yeu Cau Ho tro: wptangtoc.com/lien-he"
echo "==================================================================="
