#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
echo ""
echo ""

NAME=$1
if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ $NAME = "" ]];then
echo "========================================================================="
echo "|Quản lý WordPress => Reset htaccess                                    |"
echo "========================================================================="
echo "========================================================================="
. /etc/wptt/tenmien
echo "Lựa chọn website bạn muốn reset htaccess:"
echo ""
lua_chon_NAME
fi

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
 wptangtoc 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
 wptangtoc 1
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  wptangtoc 1
  exit
fi


_runing "reset htaccess cho website $NAME"
. /etc/wptt/vhost/."$NAME".conf
echo '# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress' > /usr/local/lsws/"$NAME"/html/.htaccess
_rundone "reset htaccess cho website $NAME"

if [[ -f "/etc/letsencrypt/live/$NAME/cert.pem" || -d /usr/local/lsws/$NAME/ssl || -f "/etc/letsencrypt/live/www.$NAME/cert.pem" ]]; then
_runing "renew chuyển hướng"
. /etc/wptt/ssl/wptt-renew-chuyen-huong $NAME >/dev/null 2>&1
_rundone "renew chuyển hướng"
fi

if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/litespeed-cache ]];then
wp litespeed-option set cache-browser false --allow-root >/dev/null 2>&1 --path=/usr/local/lsws/$NAME
fi

. /etc/wptt/vhost/.$NAME.conf
. /etc/wptt/.wptt.conf

if [[ $tuong_lua_7g ]];then
. /etc/wptt/bao-mat/wptt-firewall-7g $NAME
fi

_runing "Phân quyền website $NAME"
chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$NAME"/html

if [[ $2 = '' ]];then
	. /etc/wptt/vhost/.$NAME.conf
	if [[ $lock_down ]];then
		find /usr/local/lsws/"$domain"/html -type f -print0 |xargs -0 chmod 404
		find /usr/local/lsws/"$domain"/html -type d -print0 |xargs -0 chmod 515
		find /usr/local/lsws/"$domain"/html/wp-content/uploads -type d -print0 |xargs -0 chmod 755
	else
		find /usr/local/lsws/"$domain"/html -type f -print0 |xargs -0 chmod 644
		find /usr/local/lsws/"$domain"/html -type d -print0 |xargs -0 chmod 755
	fi
fi

chmod 444 /usr/local/lsws/"$NAME"/html/index.php
chmod 600 /usr/local/lsws/"$NAME"/html/wp-config.php

if [[ $id_dang_nhap_phpmyadmin && $Website_chinh = $NAME && -d /usr/local/lsws/"$NAME"/html/phpmyadmin ]];then
chown -R nobody:nobody /usr/local/lsws/"$domain"/html/phpmyadmin
fi

_rundone "Phân quyền website $NAME"

wp rewrite flush --allow-root --path=/usr/local/lsws/"$NAME"/html >/dev/null 2>&1
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
echo "==================================================================="
echo "               Hoàn tất reset htaccess website $NAME              "
echo "==================================================================="
