#!/bin/bash
. /etc/wptt/wptt-header-menu
header_menu
echo "+-----------------------------------------------------------------------+"
echo "|Tinh trang hoat dong cac service hien tai                              |"
echo "+-----------------------------------------------------------------------+"
echo "|LiteSpeed     : $(systemctl status lshttpd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "|MariaDB       : $(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "|LSMemcached   : $(systemctl status lsmcd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "|SSH           : $(systemctl status sshd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "|Crond         : $(systemctl status crond.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "|Fail2Ban      : $(systemctl status fail2ban.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "+-----------------------------------------------------------------------+"
echo ""
echo ""
echo "Quan ly Reboot APP:"
echo ""
options=(
    "Reboot LiteSpeed Webserver"                                                            #1
    "Reboot Maria Database"                                                                #2
    "Reboot Fai2ban"                                                                       #3
    "Reboot ALL service"                                                                   #4
    "Reboot May chu"                                                                       #5
    "Reboot LSMemcached"                                                                   #6
    "Thiet lap canh bao service ngung hoat dong qua telegram va tu dong reboot service do" #7
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/reboot-app/wptt-reboot-litespeed"
        ;;
    "${options[1]}")
        "/etc/wptt/reboot-app/wptt-reboot-mariadb"
        ;;

    "${options[2]}")
        "/etc/wptt/reboot-app/wptt-reboot-fail2ban"
        ;;

    "${options[3]}")
        "/etc/wptt/reboot-app/wptt-reboot-app"
        ;;

    "${options[4]}")
        "/etc/wptt/reboot-app/wptt-reboot"
        ;;

    "${options[5]}")
        "/etc/wptt/reboot-app/wptt-reboot-lsmemcached"
        ;;

    "${options[6]}")
        "/etc/wptt/reboot-app/wptt-auto-reboot-thiet-lap"
        ;;
    *) wptangtoc ;;
    esac
done
