#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
. /etc/wptt/.wptt.conf

RED='\033[0;31m'
NC='\033[0m'

echo -e "${RED}-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo "Cai lai WPTangToc OLS"
echo "-------------------------------------------------------------------------"
echo -e "--------------------------------------------------------------------------${NC}"

wget -q https://wptangtoc.com/share/wptangtoc-ols.zip
unzip -o wptangtoc-ols.zip
cd tool-wptangtoc-ols
cd ..
\cp -rf tool-wptangtoc-ols/* /etc/wptt/
rm -f wptangtoc-ols.zip
rm -rf tool-wptangtoc-ols
rm -rf toolwptangtocols
chmod -R 744 /etc/wptt
\cp -f /etc/wptt/wptangtoc /usr/bin
rm -f /etc/wptt/wptangtoc
\cp -f /etc/wptt/wptt /usr/bin
rm -f /etc/wptt/wptt
wptangtocols_version=$(curl -s https://wptangtoc.com/share/version-wptangtoc-ols.txt)
sed -i "/version_wptangtoc_ols/d" /etc/wptt/.wptt.conf
echo "version_wptangtoc_ols=$wptangtocols_version" >>/etc/wptt/.wptt.conf
RED='\033[0;31m'
NC='\033[0m'
echo -e "${RED}
     .:..........................             
      .::::::::::::::::::::::::::::..         
        ..:::::::::::::::::::::::::::::.      
                             ...:::::::::.    
                                  .:::::::.   
          .:::::::.         .       .:::::::  
         .::::::::::::::::::::..      ::::::: 
         ::::::::::::::::::::::::.     ::::::.
        .::::::::::::::::::::::::::.   .:::::.
        .::::::::::::::::::::::::::::  .:::::.
        .::::::::::::::::::::::::::.   .:::::.
         ::::::::::::::::::::::::.     ::::::.
.::::::  .:::::::::::::::::::::.      ::::::. 
          .:::::::.                 .:::::::  
       ::::::::::::.              .:::::::.   
       ......:::::::::...    ...:::::::::.    
               .:::::::::::::::::::::::.      
   ..............::::::::::::::::::..         
  .:::::::::::::................. ${NC}"
  
echo "-------------------------------------------------------------------------"
echo -e "${RED}-------------------------------------------------------------------------"
echo "  Cai lai bo he thong thanh cong websever WPTangToc OLS $wptangtocols_version	"
echo "-------------------------------------------------------------------------"
echo -e "--------------------------------------------------------------------------${NC}"
echo "-------------------------------------------------------------------------"
echo "Cong cu WPTangToc OLS phat trien boi: Gia Tuan"
echo "Yeu Cau Ho tro		: https://wptangtoc.com/lien-he/"
echo "Giup chung toi luon giu WPTangToc OLS co the su dung mien phi bang cach dong gop vao"
echo "Tai tro phat trien	: https://wptangtoc.com/donate/"
echo "Huong dan		: https://wptangtoc.com/wptangtoc-ols-huong-dan"
echo "-------------------------------------------------------------------------"
