#!/bin/bash
. /etc/wptt/wptt-header-menu
header_menu
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://wptangtoc.com/wptangtoc-ols-huong-dan/"
echo "-------------------------------------------------------------------------"
echo ""
echo ""
echo "Quản lý fail2ban:"
echo ""
options=(
    "Khoa IP"                               #1
    "Mo Khoa IP"                            #2
    "Danh sach ip da khoa"                  #3
    "Thay doi lan nhap sai ssh bi tam khoa" #4
    "Thay doi thoi gian bi tam khoa IP"     #5
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/fail2ban/wptt-khoa-ip"
        ;;
    "${options[1]}")
        "/etc/wptt/fail2ban/wptt-mokhoaip"
        ;;

    "${options[2]}")
        "/etc/wptt/fail2ban/wptt-list"
        ;;

    "${options[3]}")
        "/etc/wptt/fail2ban/wptt-changer-login-sai"
        ;;

    "${options[4]}")
        "/etc/wptt/fail2ban/wptt-changer-times-block"
        ;;

    *) wptangtoc 1 ;;
    esac
done
