#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025
# @email: giatuan@wptangtoc.com

function huong_dan() {
  Tính năng Preload Cache [Tải trước bộ nhớ đệm] là một kỹ thuật chủ động tạo và lưu trữ các phiên bản đã được cache [lưu tạm] của các trang web [hoặc các tài nguyên khác] trước khi có bất kỳ người dùng nào thực sự truy cập vào những trang đó.

  Nói một cách đơn giản, thay vì đợi người dùng đầu tiên ghé thăm một trang để hệ thống bắt đầu tạo bản cache cho trang đó [khiến người đầu tiên có thể phải chờ lâu hơn], tính năng preload cache sẽ cho hệ thống [thường là plugin caching hoặc máy chủ] tự động đi một vòng website, chụp sẵn các trang và lưu vào bộ nhớ đệm.

  Mục Đích Chính
  * Đảm bảo khách truy cập đầu tiên cũng có trải nghiệm nhanh: Khi cache vừa được xóa hoặc hết hạn, người dùng đầu tiên thường phải chờ trang được tạo động. Preload giúp ngay cả người dùng này cũng nhận được phiên bản cache nhanh chóng.
  * Cải thiện hiệu suất cảm nhận được: Toàn bộ website có vẻ nhanh hơn một cách nhất quán vì nhiều trang hơn đã được cache sẵn sàng.
  * Nâng cao trải nghiệm người dùng: Tốc độ tải trang nhanh hơn dẫn đến trải nghiệm tốt hơn, có thể giảm tỷ lệ thoát trang.
  * Lợi ích SEO [gián tiếp]: Tốc độ website là một yếu tố xếp hạng. Việc đảm bảo nhiều người dùng [và có thể cả bot tìm kiếm] truy cập vào các trang đã được cache góp phần cải thiện các chỉ số hiệu suất.
  * Nhanh chóng xây dựng lại cache: Hữu ích để làm đầy lại bộ nhớ đệm một cách nhanh chóng sau khi cache được xóa thủ công hoặc sau khi có những thay đổi lớn trên website.

  Yêu cầu: bạn phải đang có sử dụng công nghệ Page Cache HTML [Ví dụ như lscache, flyingpress, WP Rocket, Swift...]
  Kết quả là phần lớn các trang trên website của bạn đã được cache sẵn sàng, mang lại tốc độ tải nhanh hơn cho nhiều người dùng hơn.
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

NAME=$1

if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ "$NAME" ]]; then
  if [ "$NAME" = "${NAME/./}" ]; then
    clear
    echo "$domain_nhap_khong_dung_dinh_dang"
    exit
  fi
fi

if [[ "$NAME" = "" ]]; then
  echo "========================================================================="
  echo ""
  echo ""
  . /etc/wptt/tenmien-them-lua-chon-tat-ca-website
  echo "$lua_chon_website_ban_muon preload cache: "
  echo ""
  lua_chon_NAME

  if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    wptangtoc 1
  fi
fi

if [[ $NAME = 'Tất cả website' ]]; then
  if [ "$(ls -A /etc/wptt/vhost | sort -uV)" ]; then
    for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
      domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      path_html="/usr/local/lsws/$domain/html"
      i=1
      if [ "$domain" != "${domain/./}" ] && [ "$domain" != '.' ]; then #điều kiện domain phải có dấu . và lỗi chỉ có only .
        if [[ -d "$path_html" ]]; then
          (/etc/wptt/wptt-preload-cache2 $domain)
        fi
      fi
    done
  fi

  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    . wptangtoc 1
  fi
  exit
fi

if [[ ! -f /etc/wptt/vhost/.$NAME.conf ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  . wptangtoc 1
  exit
fi

echo "Preload website $NAME : $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

if [[ $ip_domain ]]; then
  domain=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')
else
  domain=$(echo $NAME)
fi

#them -k để không check ssl, dùng -k vì nhiều khi dùng ssl tự ký thôi
checkssl=$(curl -kIs https://${domain} --connect-to "${domain}::127.0.0.1:443" --connect-to "${domain}::127.0.0.1:80" -A "WPTangToc OLS preload cache" | head -n 1 | grep -c "200")
checkssl2=$(curl -kIs http://${domain} --connect-to "${domain}::127.0.0.1:443" --connect-to "${domain}::127.0.0.1:80" -A "WPTangToc OLS preload cache" | head -n 1 | grep -c "200")
checkssl3=$(curl -kIs https://www.${domain} --connect-to "${domain}::127.0.0.1:443" --connect-to "${domain}::127.0.0.1:80" -A "WPTangToc OLS preload cache" | head -n 1 | grep -c "200")
checkssl4=$(curl -kIs http://www.${domain} --connect-to "${domain}::127.0.0.1:443" --connect-to "${domain}::127.0.0.1:80" -A "WPTangToc OLS preload cache" | head -n 1 | grep -c "200")

if [[ "$checkssl" = "0" && "$checkssl2" = "0" && "$checkssl3" = "0" && "$checkssl4" = "0" ]]; then
  echo "$he_thong $kiem_tra website $NAME $ngung_hoat_dong."
  sleep 4
  wptangtoc 1
  exit
fi

. /etc/wptt/vhost/.$NAME.conf
if [[ $vhost_chuyen_htaccess ]]; then
  check=$(cat /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf | sed -e '/^context/,/^}$/!d' | sed -e '/rewrite/,/^}$/!d')
else
  check=$(cat /usr/local/lsws/$NAME/html/.htaccess)
fi

NAME_path="$NAME"
if [[ "$checkssl3" = "1" || "$checkssl4" = "1" ]]; then
  domain=$(echo www.${domain})
fi

if [[ "$checkssl" = "1" || "$checkssl3" = "1" ]]; then
  ssl="https"
else
  ssl="http"
fi

echo "$dang_tien_hanh $quet sitemap website $NAME"

grepmobile=$(echo $check | grep -c Android)
grepwebp=$(echo $check | grep -c "+webp")

if [[ "$grepmobile" != "0" ]]; then
  echo "Hệ thống xác nhận bạn đang sử dụng cache mobile cho website $NAME"
fi

if [[ "$grepwebp" != "0" ]]; then
  echo "Hệ thống xác nhận bạn đang sử dụng công nghệ dịnh dạng webp cho website $NAME"
fi

# Các đường dẫn sitemap cần kiểm tra
# đặt wp-sitemap ở sau sitemap.xml để tương thích với plugin sitemap google
sitemap_paths=(
  "/sitemap_index.xml" #rankmath, yoast seo, seo press...
  "/sitemap.xml"       #All in One SEO Pack, The SEO Framework, Squirrly SEO...
  "/wp-sitemap.xml"    #sitemap mặc định wordpress
  "/sitemaps.xml"
)

check_sitemap() {
  local domain="$1"

  local ssl="$2"
  local path="$3"
  local full_url="${ssl}://${domain}${path}"

  # tuong thích với www preload cache
  if [[ $(echo $domain | grep '^www\.') ]]; then
    local domain=$(echo $domain | sed 's/^www.//g')
  fi

  # Sử dụng --connect-to thay vì --connect-to
  local check_http_200=$(curl -kIs "$full_url" --connect-to "${domain}::127.0.0.1:443" --connect-to "${domain}::127.0.0.1:80" -A "WPTangToc OLS preload cache" | head -n 1 | grep -c "200")

  if [[ "$check_http_200" != "0" ]]; then
    return 0 # Thành công
  else
    return 1 # Thất bại
  fi
}

found_sitemap=false

for path in "${sitemap_paths[@]}"; do
  if check_sitemap "$domain" "$ssl" "$path"; then
    found_sitemap=true
    NAME2="${ssl}://${domain}${path}"
    break # Thoát vòng lặp khi tìm thấy sitemap
  fi
done

if ! "$found_sitemap"; then
  echo "$khong_xac_dinh_duoc sitemap website $NAME"

  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    wptangtoc 1
  fi
  return 2>/dev/null
  exit
fi

#checksm=$(curl -Is ${ssl}://$domain/sitemap.xml --connect-to "$domain:80:127.0.0.1" --connect-to "$domain:443:127.0.0.1" -A "WPTangToc OLS preload cache" | head -n 1 | grep -c "200")
#checksm2=$(curl -Is ${ssl}://$domain/wp-sitemap.xml --connect-to "$domain:80:127.0.0.1" --connect-to "$domain:443:127.0.0.1" -A "WPTangToc OLS preload cache" | head -n 1 | grep -c "200")
#checksm3=$(curl -Is ${ssl}://$domain/sitemap_index.xml --connect-to "$domain:80:127.0.0.1" --connect-to "$domain:443:127.0.0.1" -A "WPTangToc OLS preload cache" | head -n 1 | grep -c "200")
#checksm4=$(curl -Is ${ssl}://$domain/sitemaps.xml --connect-to "$domain:80:127.0.0.1" --connect-to "$domain:443:127.0.0.1" -A "WPTangToc OLS preload cache" | head -n 1 | grep -c "200")

#if [[ "$checksm" = "0" && "$checksm2" = "0" && "$checksm3" = "0" && "$checksm4" = "0" ]]; then
#    echo "$khong_xac_dinh_duoc sitemap website $NAME"
#	sleep 4
#	wptangtoc 1
#	exit
#fi

##cho sitemap WordPress lên đầu, để cái dưới nó chèn biến, một số trường hợp website chạy song song 2 sitemap sẽ dùng sitemap bên thứ 3
#if [[ "$checksm2" = "1" ]]; then
#    NAME2="${ssl}://$domain/wp-sitemap.xml"
#fi

#if [[ "$checksm" = "1" ]]; then
#    NAME2="${ssl}://$domain/sitemap.xml"
#fi

#if [[ "$checksm3" = "1" ]]; then
#    NAME2="${ssl}://$domain/sitemap_index.xml"
#fi

#if [[ "$checksm4" = "1" ]]; then
#    NAME2="${ssl}://$domain/sitemaps.xml"
#fi

echo "$kiem_tra sitemap $hoan_tat sitemap website $NAME url: $NAME2"

grep=$(echo $check | grep -c LiteSpeed)
if [[ "$grep" = "0" ]]; then
  pluginsspeed=(
    cache-enabler
    fast-velocity-minify
    wp-rocket
    w3-total-cache
    wp-super-cache
    wp2speed
    nitropack
    wp-fastest-cache
    hummingbird-performance
    swift-performance-lite
    swift-performance-pro
    cache-enabler
    breeze
    wp-meteor
    phastpress
    flying-press
    simple-cache
    powered-cache
    yasakani-cache
    batcache
    sg-cachepress
  )

  for plugintt in ${pluginsspeed[@]}; do
    pathcheckplugin3="/usr/local/lsws/${NAME_path}/html/wp-content/plugins/$plugintt"
    if [[ -d "$pathcheckplugin3" ]]; then
      plugintt2=$(echo $plugintt | sed 's/-/ /g')
      echo "Xác nhận bạn đang sử dụng công nghệ cache $plugintt2"
      cong_cu="wptt-preload-cache-all.sh"
    fi
  done

  if [[ -f /usr/local/lsws/${NAME_path}/html/wp-content/plugins/wptangtoc/class/Cache.php ]]; then
    echo "Đang sử dụng WPTangToc Cache"
    cong_cu="wptt-preload-cache-all.sh"
  fi

  if [[ $cong_cu = "" ]]; then
    echo "Hệ thống xác định bạn đang chưa sử dụng công nghệ cache nào"
    sleep 4
    wptangtoc 1
    exit
  fi

else
  echo "$xac_nhan $ban_dang_su_dung công nghệ LScache"
  cong_cu="wptt-preload-cache-all.sh"
fi

tien_trinh_pid_trung_lap_remove=$(ps -ef | grep -v grep | grep 'bash' | grep '/etc/wptt' | grep 'wptt-preload-cache.sh\|wptt-preload-cache-all.sh' | grep $NAME | awk '{print $2}' | xargs kill -9 >/dev/null 2>&1)

cpu_su_dung=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}' | cut -f1 -d '.')

if [[ $cpu_su_dung ]]; then
  if (("$cpu_su_dung" > 85)); then
    RED='\033[0;33m'
    NC='\033[0m'
    echo -e "${RED}==================================================================="
    echo "Canh Bao FULL CPU đang sử dụng: ${cpu_su_dung}%"
    echo "Khong the su dung tinh nang preload cache"
    echo -e "=================================================================== ${NC}"
    exit
  fi
fi

ram_sudung=$(free | grep Mem | awk '{print $3/$2 * 100.0}' | cut -f1 -d '.')
if [[ $ram_sudung ]]; then
  if (("$ram_sudung" > 85)); then
    RED='\033[0;33m'
    NC='\033[0m'
    echo -e "${RED}==================================================================="
    echo "$canh_bao FULL Ram đang sử dụng: ${ram_sudung}%"
    echo "Khong the su dung tinh nang preload cache"
    echo -e "=================================================================== ${NC}"
    exit
  fi
fi

# if [[ "$checksm2" != "1" ]]; then
echo "Hệ thống sẽ chạy quá trình này khá tốn tài nguyên..."
if [[ "$grepmobile" != "0" ]]; then
  check_run='1'
  bash /etc/wptt/$cong_cu -i 0.5 -m -g ${NAME2}
fi
if [[ "$grepwebp" != "0" ]]; then
  check_run='1'
  bash /etc/wptt/$cong_cu -i 0.5 -w ${NAME2}
fi

if [[ $check_run = '' ]]; then
  bash /etc/wptt/$cong_cu -i 0.5 ${NAME2}
fi

# fi

# if [[ "$checksm2" = "1" ]]; then
#     bash /etc/wptt/$cong_cu -i 0.5 ${ssl}://$NAME/wp-sitemap-posts-post-1.xml && bash /etc/wptt/$cong_cu -i 0.5 ${ssl}://$NAME/wp-sitemap-posts-page-1.xml && bash /etc/wptt/$cong_cu -i 0.5 ${ssl}://$NAME/wp-sitemap-taxonomies-category-1.xml
#     if [[ "$grepmobile" != "0" ]]; then
#         bash /etc/wptt/$cong_cu -i 0.5 -m -g ${ssl}://$NAME/wp-sitemap-posts-post-1.xml && bash /etc/wptt/$cong_cu -i 0.5 -m -g ${ssl}://$NAME/wp-sitemap-posts-page-1.xml && bash /etc/wptt/$cong_cu -i 0.5 -m -g ${ssl}://$NAME/wp-sitemap-taxonomies-category-1.xml
#     fi
#     if [[ "$grepwebp" != "0" ]]; then
#         bash /etc/wptt/$cong_cu -i 0.5 -w ${ssl}://$NAME/wp-sitemap-posts-post-1.xml && bash /etc/wptt/$cong_cu -i 0.5 -w ${ssl}://$NAME/wp-sitemap-posts-page-1.xml && bash /etc/wptt/$cong_cu -i 0.5 -w ${ssl}://$NAME/wp-sitemap-taxonomies-category-1.xml
#     fi

#     if [[ -d /usr/local/lsws/$NAME/html/wp-content/plugins/woocommerce ]]; then
#         bash /etc/wptt/$cong_cu -i 0.5 ${ssl}://$NAME/wp-sitemap-posts-product-1.xml && bash /etc/wptt/$cong_cu -i 0.5 ${ssl}://$NAME/wp-sitemap-taxonomies-product_cat-1.xml
#         if [[ "$grepmobile" != "0" ]]; then
#             bash /etc/wptt/$cong_cu -i 0.5 -m ${ssl}://$NAME/wp-sitemap-posts-product-1.xml && bash /etc/wptt/$cong_cu -i 0.5 -m ${ssl}://$NAME/wp-sitemap-taxonomies-product_cat-1.xml
#         fi
#         if [[ "$grepwebp" != "0" ]]; then
#             bash /etc/wptt/$cong_cu -i 0.5 -w ${ssl}://$NAME/wp-sitemap-posts-product-1.xml && bash /etc/wptt/$cong_cu -i 0.5 -w ${ssl}://$NAME/wp-sitemap-taxonomies-product_cat-1.xml
#         fi
#     fi

# fi

echo "========================================================================="
echo "                      Preload cache $hoan_tat	                       "
echo "========================================================================="
echo "$phat_trien_boi_gia_tuan"
echo "========================================================================="
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  wptangtoc 1
fi
