#!/bin/bash
if [[ ! -f /usr/local/bin/ocp ]]; then
wget https://cdn.pmylund.com/files/tools/ocp2/linux/ocp-2.7-amd64.tar.gz
tar -zxf ocp-2.7-amd64.tar.gz
chmod +x ocp/ocp
mv ocp/ocp /usr/local/bin
rm -rf ocp
rm -f ocp-2.7-amd64.tar.gz
mv /etc/wptt/wptt-ocp /usr/local/bin/preload-ocp
\cp /etc/wptt/wptt-preload-cache3 /usr/local/bin/preload
chmod +x /usr/local/bin/preload
chmod +x /usr/local/bin/preload-ocp
fi

NAME=$1
ssl="https"
checksm=$(curl -Is ${ssl}://$NAME/sitemap.xml | head -n 1 | grep -c "200")
checksm2=$(curl -Is ${ssl}://$NAME/wp-sitemap.xml | head -n 1 | grep -c "200")
checksm3=$(curl -Is ${ssl}://$NAME/sitemap_index.xml | head -n 1 | grep -c "200")

if [[ "$checksm" = "0" && "$checksm2" = "0" && "$checksm3" = "0" ]]; then
    echo "khong xac dinh duoc sitemap cua $NAME"
    exit
fi

if [[ "$checksm" = "1" ]]; then
    NAME2="${ssl}://$NAME/sitemap.xml"
fi

if [[ "$checksm2" = "1" ]]; then
    NAME2="${ssl}://$NAME/wp-sitemap.xml"
fi

if [[ "$checksm3" = "1" ]]; then
    NAME2="${ssl}://$NAME/sitemap_index.xml"
fi

echo "hoan tat"
