#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2024
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo "$chuyen_website:"
echo ""
options=(
    "$chuyen_website_ben_ngoai_ve_wptangtoc"                       #1
	"$chuyen_tat_ca_website_wptangtoc_ve_wptangtoc_ols"
	"$chuyen_tat_ca_website_wptangtoc_ols_ve_wptangtoc_bang_rsync"
	"$chuyen_1_website_wptangtoc_ols_ve_wptangtoc_ols_bang_rsync"
)
PS3="
$(tput setab 0)$nhap_lua_chon_cua_ban (1-${#options[@]}) [0=$exit_thoat]:$(tput sgr0) "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/chuyen-web/wptt-chuyen-website"
        ;;
    "${options[1]}")
        "/etc/wptt/chuyen-web/wptt-chuyen-website-all"
        ;;
    "${options[2]}")
        "/etc/wptt/chuyen-web/rsync-move"
        ;;

    "${options[3]}")
        "/etc/wptt/chuyen-web/rsync-move-only" 98
    ;;

    *) wptangtoc 1 ;;
    esac
done
