#!/bin/bash
. /etc/wptt/wptt-header-menu
header_menu
echo ""
echo ""
echo "Quan ly Cache:"
echo ""
options=(
    "Kich hoat lsmemcached"                     #1
    "Tat kich hoat lsmemcached"                      #2
    "Bat lsmemcached"                     #1
    "Tat lsmemcached"                      #2
    "Kich hoat redis"                  #3
    "Tat kich hoat redis"                #4
    "Bat redis"                  #3
    "Tat redis"                #4
    "Kich hoat lscached"               #6
    "Kiem tra lscache"                #5
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/cache/wptt-them-database"
        ;;
    "${options[1]}")
        "/etc/wptt/cache/wptt-xoa-database"
        ;;
    "${options[2]}")
        "/etc/wptt/cache/wptt-saoluu-database"
        ;;
    "${options[3]}")
        "/etc/wptt/cache/wptt-nhapdatabase"
        ;;
    "${options[4]}")
        "/etc/wptt/cache/wptt-thongtin-db"
        ;;
    *) wptangtoc ;;
    esac
done
