#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

if [[ -f /tmp/wptangtoc-ols-version ]];then
wptangtocols_version=$(cat /tmp/wptangtoc-ols-version)
fi

if [[ $wptangtocols_version = "" ]];then
wptangtocols_version=$(curl -s https://wptangtoc.com/share/version-wptangtoc-ols.txt| head -1 | grep '\.')
if [[ $wptangtocols_version = "" ]];then
wptangtocols_version=$(curl -s https://github.com/wptangtoc/wptangtoc-ols/blob/main/version-wptangtoc-ols.txt | grep 'LC1' | cut -f2 -d '>' | sed 's:</td::g')
fi

fi

if [[ "$wptangtocols_version" != "$version_wptangtoc_ols" ]]; then
RED='\033[0;31m'
NC='\033[0m'
   echo "========================================================================="
   echo -e "$thong_bao $cap_nhat - $ban_dang_su_dung WPTANGTOC OLS $phien_ban: ${RED} $version_wptangtoc_ols ${NC}"
   echo "========================================================================="
   echo -e "$da_co_ban $cap_nhat WPTANGTOC OLS: ${RED} $wptangtocols_version ${NC}"
   echo "$nhap: 99 $hoac wptt update-wptangtoc - $de $cap_nhat."
   echo "========================================================================="
   echo "$phat_trien_boi_gia_tuan (wptangtoc.com)"
   if [[ $wptangtoc_ols_giatuan = "1" ]]; then
   echo "$cam_on_ban_da_lua_chon WPTangToc OLS Premium"
   else
   echo "$tai_tro_du_an: https://wptangtoc.com/donate/"
   fi
   echo "========================================================================="
fi
