#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Quản lý fail2ban:"
echo ""
options=(
    "Khoá IP"                               #1
    "Mở Khoá IP"                            #2
    "Danh sách ip đã bị khoá"                  #3
)
PS3="
$(tput setab 0)$nhap_lua_chon_cua_ban (1-${#options[@]}) [0=$exit_thoat]:$(tput sgr0) "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/fail2ban/wptt-khoa-ip" 98
        ;;
    "${options[1]}")
        "/etc/wptt/fail2ban/wptt-mokhoaip" 98
        ;;

    "${options[2]}")
        "/etc/wptt/fail2ban/wptt-list" 98
        ;;

    *) wptangtoc 1 ;;
    esac
done
