#!/bin/bash

. /etc/wptt/echo-color

NAME=$1
if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ "$NAME" = "" ]]; then
    . /etc/wptt/tenmien
    echo ""
    echo ""
	echo "Lựa chọn website muốn chuyển phân phối ảnh avif:"
    echo ""
    lua_chon_NAME
fi

if [[ $NAME = "0" || $NAME = '' ]];then
exit
fi

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" ]]; then
    clear
    echoDo "Domain khong ton tai tren VPS."
    exit
fi


pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  exit
fi

check_webp=$(cat /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf | grep 'avif')

if [[ $check_webp ]];then
echo 'trước đó đã kích hoạt phân phối avif'
exit
fi

_runing "thiết lập phân phối ảnh avif"
echo "
context /wp-content/uploads/ {
  location                /usr/local/lsws/$NAME/html/wp-content/uploads/
  allowBrowse             1

  rewrite  {
    enable                1
    inherit               1
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTP_ACCEPT} image/avif
  RewriteCond %{REQUEST_FILENAME} (?i)(.*)(\.jpe?g|\.png|\.webp)$
  RewriteCond %1\.avif -f
  RewriteRule (?i)(.*)(\.jpe?g|\.png|\.webp)$ %1\.avif [T=image/avif,E=EXISTING:1,L]
</IfModule>
  }
  addDefaultCharset       off

  phpIniOverride  {

  }
}
" >> /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

chown -R lsadm:nobody /usr/local/lsws/conf/vhosts/$NAME
chmod -R 750 /usr/local/lsws/conf/vhosts/$NAME
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "thiết lập phân phối ảnh avif"

