#!/bin/bash

. /etc/wptt/echo-color

NAME=$1
if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ "$NAME" = "" ]]; then
  . /etc/wptt/tenmien
  echo ""
  echo ""
  echo "Lựa chọn website muốn chuyển đổi .htaccess sang vhosts:"
  echo ""
  lua_chon_NAME
fi

if [[ $NAME = "0" || $NAME = '' ]]; then
  return 2>/dev/null
  exit
fi

path="/etc/wptt/vhost/.$NAME.conf"
path_bk="/etc/wptt/vhost_bk/.$NAME.conf"

if [[ ! -f "$path" && ! -f $path_bk ]]; then
  clear
  echoDo "Domain khong ton tai tren VPS."
  return 2>/dev/null
  exit
fi

# pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
# if [[ ! -f "$pathcheckwp" ]]; then
#   clear
#   echoDo "Hệ thống xác nhận bạn không sử dụng mã nguồn WordPress"
#   sleep 3
# return 2>/dev/null ; exit
# fi

#kiểm tra .htaccess
if [[ ! -f /usr/local/lsws/$NAME/html/.htaccess ]]; then
  echoDo "Không xác định được .htaccess của website $NAME"
  return 2>/dev/null
  exit
fi

#sed-multiline-delete-with-pattern
#tự động xác định tìm block rewrite xóa theo block {}
# sed -i '/^rewrite/{:a;N;/}$/!ba};/enable/d' /usr/local/lsws/conf/vhosts/$NAME.conf
sed -i -e '/^rewrite/,/^}$/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

#thiết lập tắt tự động chạy file .htaccess:

_runing "Thiết lập chuyển htaccess sang vhosts"
echo "
rewrite  {
  enable                  1
  autoLoadHtaccess        0
}" >>/usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

# sed -i '/^context/{:a;N;/}$/!ba};/enable/d' /usr/local/lsws/conf/vhosts/$NAME.conf

#xác định context
# context=$(cat /usr/local/lsws/conf/vhosts/$NAME.conf | sed -e '/^context/,/^}/!d')

# xóa context hiện tại:
sed -i -e '/^context \/ {/,/^}$/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

#xác định các code đã được add vào sử dụng tại .htaccess
sed -i '/^$/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf #xoá dòng rỗng
unset lenh_htaccess
lenh_htaccess=$(cat /usr/local/lsws/$NAME/html/.htaccess | sed '/^#/d' | sed '/^$/d') #đọc file htaccess, và xoá những dòng rỗng và xoá dòng bình luận đi
echo "
context / {
  location                /usr/local/lsws/$NAME/html
  allowBrowse             1
  extraHeaders            <<<END_extraHeaders
X-XSS-Protection 1;mode=block
X-Frame-Options SAMEORIGIN
Referrer-Policy strict-origin-when-cross-origin
X-Content-Type-Options nosniff
X-Powered-By WPTangTocOLS
permissions-policy accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
  END_extraHeaders


  rewrite  {
      enable                1
	  inherit               1
$lenh_htaccess
  }
  addDefaultCharset       off

  phpIniOverride  {

  }
}
" >>/usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

hostname_custom=$(cat /usr/local/lsws/conf/vhosts/$Website_chinh/$Website_chinh.conf | grep 'X-Powered-By' | cut -f2 -d ' ' | sort -u)
if [[ $hostname_custom = '' || $hostname_custom != 'WPTangTocOLS' ]]; then
  sed -i '/X-Powered-By/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
fi

if [[ $hostname_custom != 'WPTangTocOLS' ]]; then
  if [[ $hostname_custom ]]; then
    sed -i "/extraHeaders /a X-Powered-By $hostname_custom" /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf #custom hostname
  fi
fi
unset hostname_custom

#tuong thich ubuntu tuong thich nhom litespeed
if $(cat /etc/*release | grep -q "Ubuntu"); then
  tuong_thich_nhom_litespeed="nogroup"
else
  tuong_thich_nhom_litespeed="nobody"
fi

chown -R lsadm:$tuong_thich_nhom_litespeed /usr/local/lsws/conf/vhosts/$NAME
chmod -R 750 /usr/local/lsws/conf/vhosts/$NAME

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

sed -i '/^$/d' /etc/wptt/vhost/.$NAME.conf
sed -i '/vhost_chuyen_htaccess/d' /etc/wptt/vhost/.$NAME.conf
echo 'vhost_chuyen_htaccess=1' >>/etc/wptt/vhost/.$NAME.conf
_rundone "Thiết lập chuyển htaccess sang vhosts"
echo "Thiết lập chuyển htaccess sang vhosts website $NAME: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log
