#!/bin/bash
clear
. /etc/wptt/.wptt.conf
RED='\033[0;31m'
NC='\033[0m'
ols1=$(systemctl status lshttpd.service | grep 'enabled' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
mariadb1=$(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)

if [[ "$ols1" = "loaded" ]]; then
    ols="Hoat dong tot"
else
    echo "========================================================================="
    ols2="Websever LiteSpeed dang bi gap su co"
    /usr/local/lsws/bin/lswsctrl restart
    echo "========================================================================="
fi

if [[ "$mariadb1" = "active" ]]; then
    mariadb="Hoat dong tot"
else
    echo "========================================================================="
    mariadb2="MariaDB Database dang bi gap su co"
    systemctl restart mariadb.service
    echo "========================================================================="
fi

echo -e "${RED}+-----------------------------------------------------------------------+"
echo "|                        WPTANGTOC OLS phien ban: $version_wptangtoc_ols		|"
echo "|                          Phat trien boi: Gia Tuan			|"
echo -e "+-----------------------------------------------------------------------+ ${NC}"
echo "========================================================================="
if [[ "$ols1" = "loaded" && "$mariadb1" = "active" ]]; then
    hoatdong="hoat dong tot"
else
    hoatdong="may chu dang co van de, can phai khac phuc"
    echo "$mariadb2"
    echo "$ols2"
fi
echo "Tinh trang may chu: $hoatdong"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://wptangtoc.com/wptangtoc-ols-huong-dan/"
echo "-------------------------------------------------------------------------"
echo ""
echo ""
echo "Quan ly logs:"
echo ""
options=(
    "Xem error log server"                       #1
    "Xem access log server"                      #2
    "Bat ghi error/access log domain"            #3
    "Tat ghi error/access log domain"            #4
    "Xem access log domain"                      #5
    "Xem access log domain co truy van"          #6
    "Xem error log domain"                       #7
    "Real-Time Statistics Monitoring ALL domain" #8
    "Real-Time Statistics Monitoring domain"     #9
    "Xoa Log"                                    #10
    "Xem tien trinh hoat dong"                   #11
    "Kich hoat ghi logs database"                #12
    "Huy Kich hoat ghi logs database"            #13
    "Xem log database"                           #14
    "Xem log database truy van cham"             #15
)

PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in
    "${options[0]}")
        "/etc/wptt/logs/wptt-xem-log-server"
        ;;
    "${options[1]}")
        "/etc/wptt/logs/wptt-xem-access-log-server"
        ;;
    "${options[2]}")
        "/etc/wptt/logs/wptt-bat-logs-domain"
        ;;

    "${options[3]}")
        "/etc/wptt/logs/wptt-tat-logs-domain"
        ;;

    "${options[4]}")
        "/etc/wptt/logs/wptt-xem-access-log-domain"
        ;;

    "${options[5]}")
        "/etc/wptt/logs/wptt-xem-access-log-domain-truy-van"
        ;;

    "${options[6]}")
        "/etc/wptt/logs/wptt-xem-error-log-domain"
        ;;

    "${options[7]}")
        "/etc/wptt/domain/real-time-check"
        ;;

    "${options[8]}")
        "/etc/wptt/domain/real-time-check-domain"
        ;;

    "${options[9]}")
        "/etc/wptt/logs/wptt-xoa-logs"
        ;;

    "${options[10]}")
        "/etc/wptt/logs/wptt-xem-tien-trinh"
        ;;
    "${options[11]}")
        "/etc/wptt/logs/wptt-ghi-log-db"
        ;;

    "${options[12]}")
        "/etc/wptt/logs/wptt-xoa-ghi-log-db"
        ;;
        
    "${options[13]}")
        "/etc/wptt/logs/wptt-xem-log-db"
        ;;

    "${options[14]}")
        "/etc/wptt/logs/wptt-xem-log-db-truy-van-cham"
        ;;
    *) wptangtoc ;;
    esac
done
