#!/bin/bash
. /etc/wptt/wptt-header-menu
header_menu
echo ""
echo ""
echo "Quan ly domain:"
echo ""
options=(
    "Them domain && subdomain"                #1
    "Xoa domain"                              #2
    "Danh sach domain"                        #3
    "Kiem tra hoat dong cac website"          #4
    "Phan quyen Domain"                       #5
    "Chuyen huong Domain"                     #6
    "Xoa chuyen huong Domain"                 #7
    "Giam sat thong ke thoi gian thuc Domain" #8
    "Them domain && subdomain + WordPress"    #9
    "Them Parked Alias domain"                #10
    "Xoa Parked Alias domain"                 #11
    "Mo/Khoa Domain"                          #12
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/domain/wptt-themwebsite"
        ;;
    "${options[1]}")
        "/etc/wptt/domain/wptt-xoa-website"
        ;;
    "${options[2]}")
        "/etc/wptt/domain/wptt-list-domain"
        ;;

    "${options[3]}")
        "/etc/wptt/domain/wptt-kiemtra-hoat-dong"
        ;;

    "${options[4]}")
        "/etc/wptt/wptt-phanquyen"
        ;;

    "${options[5]}")
        "/etc/wptt/domain/wptt-chuyen-huong"
        ;;
        
    "${options[6]}")
        "/etc/wptt/domain/wptt-xoa-domain-chuyen-huong"
        ;;

    "${options[7]}")
        "/etc/wptt/domain/real-time-check"
        ;;

    "${options[8]}")
        "/etc/wptt/domain/wptt-themwebsite-wp"
        ;;

    "${options[9]}")
        "/etc/wptt/domain/wptt-alias-domain"
        ;;

    "${options[10]}")
        "/etc/wptt/domain/wptt-xoa-alias-domain"
        ;;

    "${options[11]}")
        "/etc/wptt/domain/wptt-khoa-domain"
        ;;

    *) wptangtoc ;;
    esac
done
