#!/bin/bash
. /etc/wptt/wptt-header-menu
header_menu
echo ""
echo ""
echo "Quan ly Cache:"
echo ""
options=(
    "Kich hoat object cache lsmemcached"                     #1
    "Tat kich hoat object cache lsmemcached"                      #2
    "Kich hoat object cache redis"                  #3
    "Tat kich hoat object cache redis"                #4
    "Kich hoat lscache"               #5
    "Kiem tra lscache"                #6
	"Xoa ALL Cache" #7
	"Xoa Cache website" #8
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/cache/wptt-kich-hoat-lsmemcaced"
        ;;
    "${options[1]}")
        "/etc/wptt/cache/wptt-huy-kich-hoat-lsmemcached"
        ;;
    "${options[2]}")
        "/etc/wptt/cache/wptt-redis-kich-hoat"
        ;;
    "${options[3]}")
        "/etc/wptt/cache/wptt-huy-kich-hoat-redis"
        ;;
    "${options[4]}")
        "/etc/wptt/wordpress/lscache"
        ;;
    "${options[5]}")
        "/etc/wptt/domain/real-time-check-domain"
        ;;
    "${options[6]}")
        "/etc/wptt/wordpress/xoa-cache-full"
        ;;
    "${options[7]}")
        "/etc/wptt/wordpress/wptt-xoacache"
        ;;
    *) wptangtoc ;;
    esac
done
