#!/bin/bash
clear
. /etc/wptt/.wptt.conf
RED='\033[0;31m'
NC='\033[0m'
ols1=$(systemctl status lsws.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
mariadb1=$(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)

if [[ "$ols1" = "active" ]]; then
    ols="Hoat dong tot"
else
    echo "========================================================================="
    ols2="Webserver LiteSpeed dang bi gap su co"
    echo "========================================================================="
fi

if [[ "$mariadb1" = "active" ]]; then
    mariadb="Hoat dong tot"
else
    echo "========================================================================="
    mariadb2="MariaDB Database dang bi gap su co"
    echo "========================================================================="
fi

echo -e "${RED}+------------------------------------------------------------------------+"
echo "|                        WPTANGTOC OLS phien ban: $version_wptangtoc_ols		 |"
echo "|                          Phat trien boi: Gia Tuan			 |"
echo -e "+------------------------------------------------------------------------+ ${NC}"
echo "========================================================================="
if [[ "$ols1" = "active" && "$mariadb1" = "active" ]]; then
    hoatdong="hoat dong tot"
else
    hoatdong="may chu dang co van de, can phai khac phuc"
    echo "$mariadb2"
    echo "$ols2"
fi
echo "Tinh trang may chu: $hoatdong"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://wptangtoc.com/wptangtoc-ols-huong-dan/"
echo "-------------------------------------------------------------------------"
echo ""
echo ""
echo "Quan ly domain:"
echo ""
options=(
    "Them domain && subdomain"                #1
    "Xoa domain"                              #2
    "Danh sach domain"                        #3
    "Kiem tra hoat dong cac website"          #4
    "Phan quyen Domain"                       #5
    "Chuyen huong Domain"                     #6
    "Xoa chuyen huong Domain"                 #7
    "Giam sat thong ke thoi gian thuc Domain" #8
    "Them domain && subdomain + WordPress"    #9
    "Them Parked Alias domain"                #10
    "Xoa Parked Alias domain"                 #11
    "Mo/Khoa Domain"                          #12
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/domain/wptt-themwebsite"
        ;;
    "${options[1]}")
        "/etc/wptt/domain/wptt-xoa-website"
        ;;
    "${options[2]}")
        "/etc/wptt/domain/wptt-list-domain"
        ;;

    "${options[3]}")
        "/etc/wptt/domain/wptt-kiemtra-hoat-dong"
        ;;

    "${options[4]}")
        "/etc/wptt/wptt-phanquyen"
        ;;

    "${options[5]}")
        "/etc/wptt/domain/wptt-chuyen-huong"
        ;;
        
    "${options[6]}")
        "/etc/wptt/domain/wptt-xoa-domain-chuyen-huong"
        ;;

    "${options[7]}")
        "/etc/wptt/domain/real-time-check"
        ;;

    "${options[8]}")
        "/etc/wptt/domain/wptt-themwebsite-wp"
        ;;

    "${options[9]}")
        "/etc/wptt/domain/wptt-alias-domain"
        ;;

    "${options[10]}")
        "/etc/wptt/domain/wptt-xoa-alias-domain"
        ;;

    "${options[11]}")
        "/etc/wptt/domain/wptt-khoa-domain"
        ;;

    *) wptangtoc ;;
    esac
done
