#!/bin/bash
. /etc/wptt/.wptt.conf
wptangtocols_version=$(curl -s --connect-timeout 60 --max-time 60 https://wptangtoc.com/share/version-wptangtoc-ols.txt?domain-update-tu-dong=$Website_chinh)
if [[ "$wptangtocols_version" != "$version_wptangtoc_ols" ]]; then

  #get checksum
  unset checksum_wptangtoc_file id_checksum id_checksum_user
  # Lấy nội dung file về
  checksum_wptangtoc_file=$(curl -s --connect-timeout 60 --max-time 60 https://wptangtoc.com/share/checksum.txt)
  if [[ $checksum_wptangtoc_file = '' ]]; then
    sleep 3
    checksum_wptangtoc_file=$(curl -skL --connect-timeout 60 --max-time 60 http://wptangtoc.com/share/checksum.txt)
  fi

  # Chuyển thành mảng (Array) - Tự động tách theo dòng
  mapfile -t checksum_array <<<"$checksum_wptangtoc_file"

  # Lấy từng giá trị:
  id_checksum="${checksum_array[0]}"      # Dòng 1
  id_checksum_user="${checksum_array[1]}" # Dòng 2

  OLD_PWD=$(pwd)
  TMP_DIR=$(mktemp -d)
  cd "$TMP_DIR" || exit

  # cd
  # rm -f wptangtoc-ols.zip #xoá file wptangtoc-ols.zip hiện hữu nếu có

  wget -q --timeout=15 --tries=3 https://wptangtoc.com/share/wptangtoc-ols.zip #download file

  if [[ $id_checksum != $(/usr/bin/md5sum wptangtoc-ols.zip | cut -f1 -d ' ' | head -1) ]]; then #xác thực nếu khác checksum sẽ báo lỗi
    rm -f wptangtoc-ols.zip                                                                      #xoá file nếu như checksum không đúng để báo lỗi không thực thi luôn
  fi

  if [[ ! -f wptangtoc-ols.zip ]]; then
    sleep 3 #nghỉ ngắt để xem máy chủ phục hồi
    wget -q --timeout=15 --tries=3 http://wptangtoc.com/share/wptangtoc-ols.zip --no-check-certificate
    if [[ $id_checksum != $(/usr/bin/md5sum wptangtoc-ols.zip | cut -f1 -d ' ' | head -1) ]]; then #xác thực nếu khác checksum sẽ báo lỗi
      rm -f wptangtoc-ols.zip                                                                      #xoá file nếu như checksum không đúng để báo lỗi không thực thi luôn
    fi
  fi

  if [[ ! -f wptangtoc-ols.zip ]]; then
    cd "$OLD_PWD" || cd /root
    rm -rf "$TMP_DIR"
    exit #thoát nếu không download được không checksum được
  fi

  #trước khi update backup để phục vụ rollback
  mkdir -p /etc/wptt/wptt-backup-system
  timedate=$(date +%Hgio_%d_%m_%Y)
  BACKUP_FILE="/etc/wptt/wptt-backup-system/wptt_backup_${timedate}_version:$version_wptangtoc_ols.zip"

  (
    cd /etc/wptt &&
      zip -r -q "$BACKUP_FILE" . \
        -x "wptt-backup-system/*" \
        -x ".wptt.conf" \
        -x "vhost/*"
  )

  # -g: Grow (Nối thêm vào file zip có sẵn)
  # -j: Junk paths (Bỏ đường dẫn /usr/bin/, chỉ lấy file trần)
  if [ -f "$BACKUP_FILE" ]; then #nối file /usr/bin/wptangtoc /usr/bin/wptt
    zip -g -j -q "$BACKUP_FILE" /usr/bin/wptangtoc /usr/bin/wptt
  fi

  ls -dt /etc/wptt/wptt-backup-system/*.zip 2>/dev/null | tail -n +11 | xargs -r rm -f #chỉ lưu tối đa 10 file mà thôi
  #end kết thúc backup wptangtoc ols để rollback

  kiem_tra_ton_tai_nhom=$(cat /etc/group | grep '^wptangtoc-ols:')

  unzip -o wptangtoc-ols.zip

  # \cp -rf tool-wptangtoc-ols/* /etc/wptt/

  if ! \cp -rf tool-wptangtoc-ols/* /etc/wptt/ 2>/dev/null; then #ệnh \cp -rf bên dưới nếu bị lỗi, lý do bất ngờ nào đó tiến trình dừng lại không hoàn tất được lệnh copy. Bộ code mới bị chép đè dang dở, bộ code cũ thì đã hỏng. phương án thực thi an toàn hơn nếu cp bị lỗi sẽ có phương án tự cứu chữa
    unzip -oq "$BACKUP_FILE" -d /etc/wptt/
    \cp -f /etc/wptt/wptangtoc /usr/bin
    rm -f /etc/wptt/wptangtoc
    \cp -f /etc/wptt/wptt /usr/bin
    rm -f /etc/wptt/wptt
    cd "$OLD_PWD" || cd /root
    rm -rf "$TMP_DIR"
    exit
  fi

  rm -f wptangtoc-ols.zip
  rm -rf tool-wptangtoc-ols

  if [[ -d /etc/wptt-child ]]; then #child update ghi đè
    \cp -rf /etc/wptt-child/* /etc/wptt
  fi

  chmod -R 700 /etc/wptt
  if [[ $kiem_tra_ton_tai_nhom ]]; then
    chown root:wptangtoc-ols /etc/wptt
    chown root:wptangtoc-ols /etc/wptt/vhost
    chmod 750 /etc/wptt
    chmod 750 /etc/wptt/vhost
  else
    chown root:root /etc/wptt
    chown root:root /etc/wptt/vhost
    chmod 700 /etc/wptt
    chmod 700 /etc/wptt/vhost
  fi

  \cp -f /etc/wptt/wptangtoc /usr/bin
  rm -f /etc/wptt/wptangtoc
  \cp -f /etc/wptt/wptt /usr/bin
  rm -f /etc/wptt/wptt

  if [[ $kiem_tra_ton_tai_nhom ]]; then
    for entry in $(ls -A /etc/wptt/vhost | grep -v '^\.\.conf$' | sort -uV); do
      domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      path="/usr/local/lsws/$domain/html"
      i=1
      if [[ -d "$path" && -f /etc/wptt/vhost/.$domain.conf ]]; then
        . /etc/wptt/vhost/.$domain.conf
        if [[ $(cat /etc/group | grep '^wptangtoc-ols:' | grep "$User_name_vhost") ]]; then #ktra username đó có khởi tạo vào nhom wptangtoc ols không, có bật tính năng login username không
          chown $User_name_vhost:$User_name_vhost /etc/wptt/vhost/.$domain.conf
        fi
      fi
    done
  fi

  sed -i "/version_wptangtoc_ols/d" /etc/wptt/.wptt.conf
  echo "version_wptangtoc_ols=$wptangtocols_version" >>/etc/wptt/.wptt.conf
  echo "$wptangtocols_version" >/tmp/wptangtoc-ols-version

  curl -sO https://wptangtoc.com/share/update --connect-timeout 60 --max-time 60
  if grep -q 'UPDATE_DONE="YES"' update; then #xác thực file update download có bảo toàn file hay không hay bị giám đoạn
    /bin/bash update
  fi
  rm -f update

  if [[ $key_activate ]]; then
    wget -q --timeout=15 --tries=3 https://key.wptangtoc.com/?${key_activate} --no-check-certificate -U "Activate key WPTangToc OLS" -O premium.zip
    if [[ -s premium.zip ]]; then
      unzip -oq premium.zip -d /etc/wptt/add-one
      rm -f premium.zip
      chmod -R 700 /etc/wptt/add-one
    fi
  fi

  cd "$OLD_PWD" || cd /root
  rm -rf "$TMP_DIR"
#hoàn tất update
fi
