#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Quản lý Database:"
echo ""
options=(
    "Thêm database"                     #1
    "Xóa database"                      #2
    "Sao lưu database"                  #3
    "Khôi phục database"                #4
    "Danh sách database"                #5
    "Tối ưu database ALL"               #6
    "Sửa chữa database ALL"             #7
    "Xóa toàn bộ dữ liệu của database"  #8
    "Thay đổi PassWord database"        #9
    "Kết nối Database với WordPress"    #10
    "Thông tin tài khoản database"      #11
    "Thay đổi phiên bản Maria Database" #12
    "Xem dung lượng database"           #13
    "Thiết lập tự động tối ưu Database" #14
    "Chuyển MYISAM sang INNODB" #15
    "Remote Database" #16
	"Sao lưu toàn bộ database" #17
	"Bật/tắt tự động auto restart mariadb" #18
	"Cài lại MariaDB" #19
)
PS3="
Nhập lựa chọn của bạn (1-${#options[@]}) [0=Thoát]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/db/wptt-them-database" 98
        ;;
    "${options[1]}")
        "/etc/wptt/db/wptt-xoa-database" 98
        ;;
    "${options[2]}")
        "/etc/wptt/db/wptt-saoluu-database" 98
        ;;
    "${options[3]}")
        "/etc/wptt/db/wptt-nhapdatabase" 98
        ;;
    "${options[4]}")
        "/etc/wptt/db/wptt-thongtin-db" 98
        ;;

    "${options[5]}")
        "/etc/wptt/wordpress/all-database" 98
        ;;

    "${options[6]}")
        "/etc/wptt/wordpress/all-database-sua-chua" 98
        ;;

    "${options[7]}")
        "/etc/wptt/db/wptt-wipe-database" 98
        ;;

    "${options[8]}")
        "/etc/wptt/db/wptt-thay-doi-passwd-database" 98
        ;;

    "${options[9]}")
        "/etc/wptt/db/wptt-ket-noi" 98
        ;;

    "${options[10]}")
        "/etc/wptt/db/wptt-thongtin-db-tk" 98
        ;;

    "${options[11]}")
        "/etc/wptt/db/wptt-thay-doi-version-database-maria" 98
        ;;

    "${options[12]}")
        "/etc/wptt/db/wptt-dung-luong-database" 98
        ;;    

    "${options[13]}")
        "/etc/wptt/db/wptt-tu-dong-hoa-toi-uu-database" 98
        ;;    

	"${options[14]}")
		"/etc/wptt/db/chuyen-myisam" 98
		;;    

	"${options[15]}")
		"/etc/wptt/db/wptt-remote-database" 98
		;;    

	"${options[16]}")
		"/etc/wptt/db/wptt-sao-luu-all-db" 98
	;;    

	"${options[17]}")
		"/etc/wptt/db/wptt-auto-restart-mysql" 98
	;;    

	"${options[18]}")
		"/etc/wptt/db/wptt-rebuild-mariadb" 98
	;;    
    *) wptangtoc 1 ;;
    esac
done
