#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo "Quan ly WordPress:"
echo ""
options=(
  "Cap nhat wordpress core"                              #0
  "Cap nhat plugins"                                     #1
  "Cap nhat themes"                                      #2
  "Cai lai reinstall wordpress core"                     #3
  "Cai lai reinstall wordpress (core + plugin + themes)" #4
  "Cap nhat wordpress all vps (core + plugin + themes)"  #5
  "Tai plugin LiteSpeed Cache"                           #6
  "Tat sua code truc tiep tren wp-admin wordpress"       #7
  "Bat chinh sua code truc tiep WP-admin"  				 #8
  "Truy van va thay the co so du lieu"                   #9
  "Bat che do bao tri"                                   #10
  "Tat che do bao tri"                                   #11
  "Toi uu hoa hinh anh"                                  #12
  "Unix stocket config database"                         #13
  "Toi uu hoa wp-cron"                                   #14
  "Tat toi uu hoa wp-cron"                               #15
  "Tang muc gioi han ram wordpress"                      #16
  "Thay doi salt cookie dang nhap"                       #17
  "Tat wp debug wordpress"                               #18
  "Bat wp debug wordpress"                               #19
  "Toi uu heartbeat api"                                 #20
  "Tat XML RPC wordpress"                                #21
  "Doi PassWord wp-admin wordpress"                      #22
  "login wp-admin magic link"                            #23
  "Xoa transient database"                               #24
  "Thay doi tien to database"                            #25
  "Rewrite permalink"                                    #26
  "Reset lai ve wordpress moi hoan toan"                 #27
  "Tai tao lai Thumbnail"                                #28
  "Kham Suc khoe wordpress"                              #29
  "Kiem tra autoload"                                    #30
  "Cap nhat Url home va siteurl"                         #31
  "Kiem tra phien ban wordpess"                          #32
  "Kiem tra bao mat ma nguon decode base64"              #33
  "Kiem tra toc do hook" 								 #34
  "Xoa binh luan spam"                                   #35
  "Nhap du lieu Toi uu Plugin LiteSpeed Cache"  		#36
  "Thiet Lap WordPress Multisite"  						#37
)

PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
  case $opt in
  "${options[0]}")
    "/etc/wptt/wordpress/update-core" 98
    ;;
  "${options[1]}")
    "/etc/wptt/wordpress/update-plugin" 98
    ;;
  "${options[2]}")
    "/etc/wptt/wordpress/update-theme" 98
    ;;
  "${options[3]}")
    "/etc/wptt/wordpress/ghi-de-wordpress-core" 98
    ;;
  "${options[4]}")
    "/etc/wptt/wordpress/wptt-update-reinstall-wordpres" 98
    ;;
  "${options[5]}")
    "/etc/wptt/wordpress/update-full" 98
    ;;

  "${options[6]}")
    "/etc/wptt/wordpress/tai-plugin-litespeed-cache" 98
    ;;

  "${options[7]}")
    "/etc/wptt/wordpress/tat-chinh-sua-truc-tiep-admin-wordpress" 98
    ;;

  "${options[8]}")
    "/etc/wptt/wordpress/bat-chinh-sua-truc-tiep-admin-wordpress" 98
    ;;

  "${options[9]}")
    "/etc/wptt/wordpress/query-truyvan" 98
    ;;

  "${options[10]}")
    "/etc/wptt/wordpress/bat-baotri" 98
    ;;
  "${options[11]}")
    "/etc/wptt/wordpress/tat-baotri" 98
    ;;

  "${options[12]}")
    "/etc/wptt/wordpress/image" 98
    ;;

  "${options[13]}")
    "/etc/wptt/wordpress/unix-stocket-wpconfig" 98
    ;;

  "${options[14]}")
    "/etc/wptt/wordpress/wp-cron-job" 98
    ;;

  "${options[15]}")
    "/etc/wptt/wordpress/tat-wp-cron-job" 98
    ;;

  "${options[16]}")
    "/etc/wptt/wordpress/tang-gioi-han-ram-wordpress" 98
    ;;

  "${options[17]}")
    "/etc/wptt/wordpress/thay-salt" 98
    ;;

  "${options[18]}")
    "/etc/wptt/wordpress/wp-debug" 98
    ;;

  "${options[19]}")
    "/etc/wptt/wordpress/bat-wp-debug" 98
    ;;

  "${options[20]}")
    "/etc/wptt/wordpress/plugin-heartbeat-wptangtoc" 98
    ;;

  "${options[21]}")
    "/etc/wptt/wordpress/plugin-xml-rpc-wptangtoc" 98
    ;;

    "${options[22]}")
    "/etc/wptt/wordpress/passwd-wp" 98
    ;;

    "${options[23]}")
    "/etc/wptt/wordpress/login-wpadmin-magic" 98
    ;;

  "${options[24]}")
    "/etc/wptt/wordpress/transient" 98
    ;;

  "${options[25]}")
    "/etc/wptt/wordpress/thay-doi-tien-to" 98
    ;;

  "${options[26]}")
    "/etc/wptt/wordpress/rewrite" 98
    ;;
  "${options[27]}")
    "/etc/wptt/wordpress/wptt-wipe-wordpress" 98
    ;;
  "${options[28]}")
    "/etc/wptt/wordpress/wptt-render-thumbnail" 98
    ;;

  "${options[29]}")
    "/etc/wptt/wordpress/kham-suc-khoe-wordpress" 98
    ;;

  "${options[30]}")
    "/etc/wptt/wordpress/check-autoload" 98
    ;;

  "${options[31]}")
    "/etc/wptt/wordpress/thay-url-option" 98
    ;;

  "${options[32]}")
    "/etc/wptt/wordpress/kiem-tra-version-wp" 98
    ;;

  "${options[33]}")
    "/etc/wptt/wordpress/check-decode-base64" 98
    ;;


  "${options[34]}")
    "/etc/wptt/wordpress/check-hook-speed" 98
    ;;

  "${options[35]}")
    "/etc/wptt/wordpress/xoa-binh-luan-spam" 98
    ;;
    
  "${options[36]}")
    "/etc/wptt/wordpress/nhap-du-lieu-litespeed-wptangtoc" 98
    ;;

  "${options[37]}")
    "/etc/wptt/wordpress/wordpress-multisite" 98
    ;;

  *) wptangtoc ;;
  esac
done
