#!/bin/bash
clear
. /etc/wptt/.wptt.conf
RED='\033[0;31m'
NC='\033[0m'
ols1=$(systemctl status lsws.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
mariadb1=$(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)

if [[ "$ols1" = "loaded" ]]; then
    ols="Hoat dong tot"
else
    echo "========================================================================="
    ols2="Webserver LiteSpeed dang bi gap su co"
    echo "========================================================================="
fi

if [[ "$mariadb1" = "active" ]]; then
    mariadb="Hoat dong tot"
else
    echo "========================================================================="
    mariadb2="MariaDB Database dang bi gap su co"
    echo "========================================================================="
fi

echo -e "${RED}+------------------------------------------------------------------------+"
echo "|                        WPTANGTOC OLS phien ban: $version_wptangtoc_ols		 |"
echo "|                          Phat trien boi: Gia Tuan			 |"
echo -e "+------------------------------------------------------------------------+ ${NC}"
echo "========================================================================="
if [[ "$ols1" = "active" && "$mariadb1" = "active" ]]; then
    hoatdong="hoat dong tot"
else
    hoatdong="may chu dang co van de, can phai khac phuc"
    echo "$mariadb2"
    echo "$ols2"
fi
echo "Tinh trang may chu: $hoatdong"
echo "-------------------------------------------------------------------------"
echo "Huong dan: https://wptangtoc.com/wptangtoc-ols-huong-dan/"
echo "-------------------------------------------------------------------------"
echo ""
echo ""
echo "Ghi chu: Danh muc nay la nang cao danh cho nguoi chuyen nghiep"
echo "Hay can than khi chinh sua"
echo ""
echo ""
echo "Cau hinh Webserver:"
echo ""
options=(
    "Cau hinh LiteSpeed"                                   #1
    "Cau hinh Vhost"                                       #2
    "Cau hinh Maria Database"                              #3
    "Cau hinh .htaccess"                                   #4
    "Cau hinh PHP.ini"                                     #5
    "Cau hinh Cron JOB"                                    #6
    "Tu dong cau hinh lai webserver khi thay doi phan cung" #7
)
PS3="
Nhap lua chon cua ban (1-${#options[@]}) [0=Thoat]: "
select opt in "${options[@]}"; do
    case $opt in

    "${options[0]}")
        "/etc/wptt/cau-hinh/wptt-sua-websever"
        ;;
    "${options[1]}")
        "/etc/wptt/cau-hinh/wptt-cau-hinh-vhost"
        ;;
    "${options[2]}")
        "/etc/wptt/cau-hinh/wptt-sua-mariadb"
        ;;

    "${options[3]}")
        "/etc/wptt/cau-hinh/wptt-cau-hinh-htaccess"
        ;;

    "${options[4]}")
        "/etc/wptt/php/wptt-sua-phpini"
        ;;

    "${options[5]}")
        "/etc/wptt/cau-hinh/wptt-cron"
        ;;

    "${options[6]}")
        "/etc/wptt/cau-hinh/wptt-cau-hinh-reset"
        ;;
    *) wptangtoc ;;
    esac
done
