#!/bin/bash
domain=$1
. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color
_runing "Phân quyền website $domain"

lock_down=''
. /etc/wptt/vhost/."$domain".conf

if [[ $User_name_vhost = '' ]];then
	return >/dev/null 2>&1; exit
fi

chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$domain"/html
chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$domain"/backup-website

if [[ -f /usr/local/lsws/"$domain"/.bashrc ]];then
	chown "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$domain"/.bashrc
	chown "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$domain"/.bash_profile
	chown "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$domain"/.bash_logout
fi


chmod 755 /usr/local/lsws/"$domain"/html
# find /usr/local/lsws/"$domain"/html -type d -exec chmod 755 {} \;
# find /usr/local/lsws/"$domain"/html -type f -exec chmod 644 {} \;

if [[ $lock_down ]];then
	find /usr/local/lsws/"$domain"/html -type f -print0 |xargs -0 chmod 404
	find /usr/local/lsws/"$domain"/html -type d -print0 |xargs -0 chmod 515
	#lockdown vẫn có thể uploads được dữ liệu wp-uploads
	if [[ -d /usr/local/lsws/"$domain"/html/wp-content/uploads ]];then
		find /usr/local/lsws/"$domain"/html/wp-content/uploads -type d -print0 |xargs -0 chmod 755
	fi

#lockdown tương thích với một số plugin cache
    if [[ -d /usr/local/lsws/"$domain"/html/wp-content/cache ]];then
	chmod 755 /usr/local/lsws/"$domain"/html/wp-content/cache
	find /usr/local/lsws/"$domain"/html/wp-content/cache -type d -print0 |xargs -0 chmod 755
	find /usr/local/lsws/"$domain"/html/wp-content/cache -type f -print0 |xargs -0 chmod 644
	chmod 755 /usr/local/lsws/"$domain"/html/wp-content
    fi

	if [[ -d /usr/local/lsws/"$domain"/html/wp-content/litespeed ]];then
		chmod 755 /usr/local/lsws/"$domain"/html/wp-content/litespeed
		find /usr/local/lsws/"$domain"/html/wp-content/litespeed -type d -print0 |xargs -0 chmod 755
		find /usr/local/lsws/"$domain"/html/wp-content/litespeed -type f -print0 |xargs -0 chmod 644
	fi

else
	find /usr/local/lsws/"$domain"/html -type f -print0 |xargs -0 chmod 644
	find /usr/local/lsws/"$domain"/html -type d -print0 |xargs -0 chmod 755
fi

if [[ -f /usr/local/lsws/"$domain"/html/index.php ]];then
chmod 444 /usr/local/lsws/"$domain"/html/index.php
fi

if [[ -f /usr/local/lsws/"$domain"/html/wp-config.php ]];then
chmod 600 /usr/local/lsws/"$domain"/html/wp-config.php
wp rewrite flush --allow-root --path=/usr/local/lsws/"$domain"/html >/dev/null 2>&1
fi

if [[ $id_dang_nhap_phpmyadmin && $Website_chinh = $domain && -d /usr/local/lsws/"$domain"/html/phpmyadmin ]];then
chown -R nobody:nobody /usr/local/lsws/"$domain"/html/phpmyadmin
fi

_rundone "Phân quyền website $domain"
echo "========================================================================="
