#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi
echo ""
echo ""
echo ""
echo ""

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

uswap=$(free -m | awk '/Swap/ {print $2}')
uswap_dang_dung=$(free -m | awk '/Swap/ {print $3}')
uswap_con_trong=$(free -m | awk '/Swap/ {print $4}')

echo "$dung_luong_swap_hien_tai: ${uswap}MB"
echo "$dung_luong_swap_dang_dung: ${uswap_dang_dung}MB"
echo "$dung_luong_swap_con_thua: ${uswap_con_trong}MB"
echo ""
echo "$quan_ly_swap:"
echo ""

options=(
    "$them swap" #1
    "$xoa swap"  #2
)

# Hàm thực thi hành động dựa trên index (cho menu Quản lý Swap)
run_action() {
    local index=$1
    local script_path=""
    local script_args="98" # Tham số 98 cho các script này

    case $index in
         0) script_path="/etc/wptt/swap/wptt-tao-swap" ;;
         1) script_path="/etc/wptt/swap/wptt-xoa-swap" ;;
        *) echo "${lua_chon_khong_hop_le:-Lựa chọn không hợp lệ}: Index $index."; return 1 ;;
    esac

    # Kiểm tra và chạy script con
    if [[ -x "$script_path" ]]; then
        "$script_path" "$script_args"
    else
        echo "Lỗi: Không tìm thấy hoặc không thể thực thi script '$script_path'."
    fi
    # read -rp "Nhấn Enter để quay lại menu..." # Bỏ comment nếu muốn tạm dừng
}
. /etc/wptt/wptt-callback-menu-chon

