#!/bin/bash
clear
function huong_dan() {
  Đây là tính năng xem real time hoạt động của litespeed webserver
}

echo ""
echo ""
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]]; then
  echo "========================================================================="
  echo "|Quan ly Cache => Real-Time Statistics Monitoring domain               |"
  echo "========================================================================="
elif [[ $check_menu_wptangtoc_active = "99" ]]; then
  echo "========================================================================="
  echo "|Quan ly Logs => Real-Time Statistics Monitoring domain               |"
  echo "========================================================================="
else
  echo "========================================================================="
  echo "|Quan ly Domain => Real-Time Statistics Monitoring domain               |"
  echo "========================================================================="
  echo ""
fi

. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website muon xem Real-Time Statistics Monitoring: "
echo ""
lua_chon_NAME

echo "========================================================================="
echo "Real-Time Statistics Monitoring domain $NAME"
echo "========================================================================="
cat /tmp/lshttpd/.rtreport* | grep $NAME
echo "========================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "99" ]]; then
  . /etc/wptt/wptt-logs-main 1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]]; then
  . /etc/wptt/wptt-cache-main 1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-domain-main 1
fi
