#!/bin/bash
clear
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Domain => Real-Time Statistics Monitoring domain               |"
echo "========================================================================="
echo ""
echo ""

. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website muon xem Real-Time Statistics Monitoring: "
echo ""
lua_chon_NAME

echo "========================================================================="
echo "Real-Time Statistics Monitoring domain $NAME"
echo "========================================================================="
cat /tmp/lshttpd/.rtreport* | grep $NAME
echo "========================================================================="

