#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Domain => Bật/Tắt đăng nhập username riêng cho website		  |"
echo "========================================================================="
echo ""
echo ""

. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website bật/tắt đăng nhập user riêng: "
lua_chon_NAME
echo ""

. /etc/wptt/echo-color


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt/wptt-domain-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
	clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
	sleep 3
	. /etc/wptt/wptt-domain-main 1
	exit
fi
. /etc/wptt/vhost/.$NAME.conf


check=$(cat /etc/passwd | grep "${User_name_vhost}:x" | grep 'nologin')

if [[ $check ]];then
	echo "Xác nhận bạn muốn khởi tạo đăng nhập username của website $NAME "
	prompt="Nhập lựa chọn của bạn [1-2]: "
	dongy="n"
	options=("Đồng ý" "Không đồng ý")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
			*)
				printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
		esac
	done

	if [[ $dongy != 'y' ]];then
		. /etc/wptt/wptt-domain-main 1
		exit
	fi

	. /etc/wptt/echo-color
	check_thay_doi=$(md5sum /etc/shadow |cut -f1 -d ' ' > /tmp/passwd_user_thay_doi)
	passwd $User_name_vhost
	if [[ $(cat /tmp/passwd_user_thay_doi) != $(md5sum /etc/shadow |cut -f1 -d ' ')  ]];then
		_rundone "Thiết lập PassWord cho username $User_name_vhost"
		usermod $User_name_vhost -s /bin/bash
		cp -rf /etc/skel/. /usr/local/lsws/$NAME
		chown $User_name_vhost:$User_name_vhost /usr/local/lsws/$NAME/.*
		sed -i '/wptangtoc/d' /usr/local/lsws/$NAME/.bashrc
		sed -i '/wptt/d' /usr/local/lsws/$NAME/.bashrc
		sed -i '/return/d' /usr/local/lsws/$NAME/.bashrc
		echo '[[ $- != *i* ]] && return' >> /usr/local/lsws/$NAME/.bashrc
		echo ". /etc/wptt-user/wptt-status" >> /usr/local/lsws/$NAME/.bashrc
		echo "alias 1='wptangtoc-user'" >> /usr/local/lsws/$NAME/.bashrc
		echo "alias 11='wptangtoc-user'" >> /usr/local/lsws/$NAME/.bashrc
	else
		_runloi "Thiết lập PassWord cho username $User_name_vhost"
		check_menu_wptangtoc_active=$1
		if [[ $check_menu_wptangtoc_active = "98" ]];then
			. /etc/wptt/wptt-domain-main 1
		fi
		exit
	fi

	/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
	clear

	echo "Tài khoản USERNAME: $User_name_vhost"
	echo "PassWord: ***************** (bạn vừa thiết lập vừa nãy)"

	port_ssh=$(cat /etc/ssh/sshd_config | grep "Port " | cut -f2 -d" ")
	ip=$(curl -s myip.directadmin.com)
	if [[ "$ip" = "" ]]; then
		ip=$(curl -s ifconfig.me)
	fi

	echo "Truy cập vào ssh          : ssh -p $port_ssh $User_name_vhost@$ip"
	echo "Truy cập vào sftp         : sftp -oPort=$port_ssh $User_name_vhost@$ip"
	echo "Để sử dụng quản trị website $NAME"
fi



if [[ $check = '' ]];then
	echo "Xác nhận bạn muốn tắt đăng nhập username của website $NAME "
	prompt="Nhập lựa chọn của bạn [1-2]: "
	dongy="n"
	options=("Đồng ý" "Không đồng ý")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
			*)
				printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
		esac
	done

	if [[ $dongy != 'y' ]];then
		. /etc/wptt/wptt-domain-main 1
		exit
	fi
	_runing "Tắt đăng nhập domain user"
	usermod $User_name_vhost -s /sbin/nologin
	_rundone "Tắt đăng nhập domain user"
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-domain-main 1
fi
