#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_domain => $thay_doi_username domain                             |"
echo "========================================================================="
echo ""
echo ""

. /etc/wptt/tenmien
echo ""
echo ""
echo "$lua_chon_website_ban_muon $thay_doi username: "
lua_chon_NAME
echo ""

. /etc/wptt/echo-color

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-domain-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
	clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
	sleep 3
    . /etc/wptt/wptt-domain-main 1
	exit
fi
. /etc/wptt/vhost/.$NAME.conf

read -p "$nhap username của website $NAME: " USER


#chuyen doi ky tu user
USER=${USER//[-._]/}

if  [[ $(cat /etc/passwd | cut -f1 -d ':' | grep -w $USER) ]]; then
  clear
  echo "$user_da_ton_tai_tren_he_thong_nay"
. /etc/wptt/wptt-domain-main 1
  exit
fi


echo "$xac_nhan $ban_muon $thay_doi username cho website $NAME "
prompt="$nhap_lua_chon_cua_ban [1-2]: "
dongy="n"
options=("$dong_y" "$khong_dong_y")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ $dongy != 'y' ]];then
. /etc/wptt/wptt-domain-main 1
exit
fi


_runing "$xoa user cũ $User_name_vhost của website $NAME"
pkill -u $User_name_vhost >/dev/null 2>&1
usermod -R wptangtoc-ols "$User_name_vhost" >/dev/null 2>&1
userdel -f "$User_name_vhost" >/dev/null 2>&1

if [[ -d /home/$User_name_vhost ]];then
rm -rf /home/$User_name_vhost
fi
_rundone "$xoa user cũ $User_name_vhost của website $NAME"

_runing "Thêm user mới $USER cho website $NAME"

check_ky_tu2=$(echo $USER | wc -c)
if (( $check_ky_tu2 > 32 ));then
	USER=$(echo $USER | cut -c 1-30)
fi

useradd -p -m -d /usr/local/lsws/$NAME $USER >/dev/null 2>&1

cp -rf /etc/skel/. /usr/local/lsws/$NAME
chown $USER:$USER /usr/local/lsws/$NAME/.*
sed -i '/wptangtoc/d' /usr/local/lsws/$NAME/.bashrc
sed -i '/wptt/d' /usr/local/lsws/$NAME/.bashrc
sed -i '/return/d' /usr/local/lsws/$NAME/.bashrc
echo '[[ $- != *i* ]] && return' >> /usr/local/lsws/$NAME/.bashrc
echo ". /etc/wptt-user/wptt-status" >> /usr/local/lsws/$NAME/.bashrc
echo "alias 1='wptangtoc-user'" >> /usr/local/lsws/$NAME/.bashrc
echo "alias 11='wptangtoc-user'" >> /usr/local/lsws/$NAME/.bashrc

if  [[ $(cat /etc/passwd | cut -f1 -d ':' | grep -w $USER) = '' ]]; then
_runloi "Thêm user mới $USER cho website $NAME"
. /etc/wptt/wptt-domain-main 1
fi

chmod 755 /usr/local/lsws/$NAME
chown $USER:$USER /usr/local/lsws/$NAME
chown -R $USER:$USER /usr/local/lsws/$NAME/html
chown -R $USER:$USER /usr/local/lsws/$NAME/backup-website
_rundone "Thêm user mới $USER cho website $NAME"

_runing "Thiết lập chuyển đổi từ User $User_name_vhost thành User $USER của website $NAME"
sed -i -e '/^virtualhost '$NAME'/,/^}$/d' /usr/local/lsws/conf/httpd_config.conf 

work_cpucore='1024'
cpucore=$(grep -c ^processor /proc/cpuinfo)
max_client=$(expr $work_cpucore \* $cpucore \* 2)

echo "virtualhost $NAME {
  vhRoot                  /usr/local/lsws/$NAME/
  configFile              /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
  allowSymbolLink         1
  enableScript            1
  restrained              1
  maxKeepAliveReq         $max_client
  setUIDMode              2
  user                    $USER
  group                   $USER
}" >>/usr/local/lsws/conf/httpd_config.conf

sed -i '/extUser/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
sed -i '/extGroup/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
sed -i "/instances/a extGroup                 $USER" /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
sed -i "/instances/a extUser                 $USER" /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

usermod -a -G wptangtoc-ols $USER

# khong cho login quyen tai khoan trực tiếp chỉ sử dụng để làm sử dụng php exec
usermod $USER -s /sbin/nologin

sed -i '/User_name_vhost/d' /etc/wptt/vhost/.$NAME.conf
echo "User_name_vhost=$USER" >> /etc/wptt/vhost/.$NAME.conf

#tao anh xa username
# mkdir -p /home/$USER/$NAME
# ln -s /usr/local/lsws/$NAME/html /home/$USER/$NAME/public_html
# ln -s /usr/local/backup-website/$NAME /home/$USER/$NAME/backup-website

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "Thiết lập chuyển đổi từ User $User_name_vhost thành User $USER của website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-domain-main 1
fi
