#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2024
function huong_dan(){
Đây là tính năng giúp tạm khoá website
Tính năng bật và tắt này là tính năng tạm khoá website, không xoá mã nguồn bất kỳ thứ gì.
chỉ đơn giản nó sẽ tạm ngừng hoạt động website hoặc bật lại nếu đã thiết lập tạm ngừng trước đó
}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Domain => Mo/Khoa domain                                       |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/tenmien
echo ""
echo ""
echo "lua chon domain ban muon alias vao: "
echo ""
lua_chon_NAME
path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
  clear
  echo "Domain khong ton tai tren VPS, vui long them website"
  echo
  exit
fi

. /etc/wptt/.wptt.conf


if [[ "$Website_chinh" = "$NAME" ]];then
echo "website chinh $NAME khong the su dung duoc tinh nang nay"
echo "website $NAME dai dien cho vps cua ban"
exit
fi
path_vhost="/usr/local/lsws/conf/vhosts/$NAME.conf"
path_da_khoa="${path_vhost}.khoa"

if [[ -f $path_da_khoa ]]; then
  read -p "Domain $NAME dang khoa, ban co muon mo khoa? (y/n): " dongy_mo

  if [[ "$dongy_mo" = "y" ]]; then
    mv $path_da_khoa $path_vhost
    /usr/local/lsws/bin/lswsctrl restart
    clear
    echo "Da mo domain $NAME"
    sleep 3
    . /etc/wptt/wptt-domain-main
  else
    . /etc/wptt/wptt-domain-main
  fi

fi

if [[ -f $path_vhost ]]; then
  read -p "Xac nhan khoa domain $NAME (y/n): " confirm

  if [[ "$confirm" = "y" ]]; then
    mv $path_vhost $path_da_khoa
    /usr/local/lsws/bin/lswsctrl restart
    clear
    echo "Da khoa thanh cong domain $NAME"
    . /etc/wptt/wptt-domain-main
  else
    . /etc/wptt/wptt-domain-main
  fi

fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-domain-main 1
fi

