#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Domain => thêm domain và cài WordPress                         |"
echo "========================================================================="
echo ""
echo ""

. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color

echo "Tính năng này đã ngừng hỗ trợ"
. /etc/wptt/wptt-domain-main 1
exit

