#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Domain => Xoa website                                          |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/tenmien
echo "lua chon website ban muon xoa: "
echo ""
lua_chon_NAME
path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    . /etc/wptt/wptt-domain-main
    exit
fi

. /etc/wptt/vhost/."$NAME".conf
. /etc/wptt/.wptt.conf

CLEAN="$NAME"
read -p "Xác nhận xóa website? (y/n): " dongy
if [[ "$dongy" = "y" ]]; then

    if [[ "$NAME" = "$Website_chinh" ]]; then
        echo ""
        echo ""
        echo "$NAME la website chinh dai dien cho websever cua ban hay lua chon ten mien khac de thay the lam website chinh:"
        echo "lua chon website chinh khac: "
        echo ""
        NAME3="$NAME"
        echo "Ghi chu: Chon 1 domain khac dang duoc kich hoat SSL"
        echo ""
        mkdir -p /etc/wptt/vhost2
        if [ "$(ls -A /etc/wptt/vhost)" ]; then
            for entry in $(ls -A /etc/wptt/vhost); do
                domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
                path="/usr/local/lsws/$domain/html"
                i=1

                if [[ -d "$path" ]]; then
                    cp -f /etc/wptt/vhost/."$domain".conf /etc/wptt/vhost2
                fi
            done
        fi

        rm -f /etc/wptt/vhost2/."$Website_chinh".conf

        function lua_chon_NAME_vhost2() {
            NAME=""
            if [ "$(ls -At /etc/wptt/vhost2)" ]; then
                selects=()
                for entry in $(ls -A /etc/wptt/vhost2); do
                    NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
                    if [ "$NAME" != "${NAME/./}" ]; then
                        selects+=("$NAME")
                    fi
                done
                PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
                select select in ${selects[@]}; do
                    NAME=$select
                    index=$REPLY
                    break
                done
            else
                clear
                echo "Khong co domain nao ton tai tren he thong cua ban."
                exit
            fi
        }
        lua_chon_NAME_vhost2
        NAMEPHU="$NAME"
        if [[ "$NAMEPHU" = "$Website_chinh" ]]; then
            echo "Thong bao loi"
            echo "Trung lap website chinh va website thay the chinh: $NAME3"
            echo ""
            echo ""
            echo "Vui long xoa lai website"
            exit
        fi
        if [[ "$NAMEPHU" = "0" || "$NAMEPHU" = "" ]]; then
            . /etc/wptt/wptt-domain-main
            exit
        fi

        sed -i "/keyFile/d" /usr/local/lsws/conf/httpd_config.conf
        sed -i "/certFile/d" /usr/local/lsws/conf/httpd_config.conf
        sed -i "/CACertFile/d" /usr/local/lsws/conf/httpd_config.conf
        sed -i "/https/a keyFile              \/etc\/letsencrypt\/live\/$NAMEPHU\/privkey.pem" /usr/local/lsws/conf/httpd_config.conf
        sed -i "/https/a certFile             \/etc\/letsencrypt\/live\/$NAMEPHU\/cert.pem" /usr/local/lsws/conf/httpd_config.conf
        sed -i "/https/a CACertFile           \/etc\/letsencrypt\/live\/$NAMEPHU\/chain.pem" /usr/local/lsws/conf/httpd_config.conf
        /usr/local/lsws/bin/lswsctrl restart
        sed -i "/$Website_chinh/d" /etc/wptt/.wptt.conf
        echo "Website_chinh=$NAMEPHU" >>/etc/wptt/.wptt.conf
        rm -rf /etc/wptt/vhost2
        if [[ $id_dang_nhap_phpmyadmin ]]; then
            cp -rf /usr/local/lsws/"$CLEAN"/html/phpmyadmin /usr/local/lsws/"$NAMEPHU"/html/
            mkdir -p /usr/local/lsws/"$NAMEPHU"/passwd
            cp -f /usr/local/lsws/"$Website_chinh"/passwd/.phpmyadmin /usr/local/lsws/"$NAMEPHU"/passwd
            chown -R nobody:nobody /usr/local/lsws/"$NAMEPHU"/passwd
            echo 'realm '${NAMEPHU}php' {
  userDB  {
    location              /usr/local/lsws/'$NAMEPHU'/passwd/.phpmyadmin
  }
}
context /phpmyadmin/ {
  location                phpmyadmin/
  allowBrowse             1
  realm                   '${NAMEPHU}php'

  accessControl  {
    allow                 ALL
  }

  rewrite  {

  }
  addDefaultCharset	  off

  phpIniOverride  {

  }
}' >>/usr/local/lsws/conf/vhosts/"$NAMEPHU"/"$NAMEPHU".conf

        fi
    fi

    rm -rf /usr/local/lsws/conf/vhosts/"$CLEAN"
    userdel "$User_name_vhost"
    rm -rf /home/$User_name_vhost
    rm -rf /wptangtoc-ols/"$CLEAN"
    rm -rf /usr/local/lsws/"$CLEAN"
    mysql -u $database_admin_username -p"$database_admin_password" -e "DROP DATABASE ${DB_Name_web}"
    mysql -u $database_admin_username -p"$database_admin_password" -e "DROP USER '${DB_User_web}'@'localhost'"
    sed -i "/$CLEAN $CLEAN/d" /usr/local/lsws/conf/httpd_config.conf
    sed -i "/$CLEAN/,+10d" /usr/local/lsws/conf/httpd_config.conf
    rm -f /etc/wptt/vhost/.$CLEAN.conf
    read -p "Xac nhan ban co muon xoa ca thu muc backup website cua website $CLEAN ? (y/n): " dongy2
    if [[ "$dongy2" = "y" ]]; then
        rm -rf /usr/local/backup-website/"$CLEAN"
        echo "Hoan tat xoa thu muc backup website $CLEAN"
    fi

    if [[ -f "/etc/letsencrypt/live/$CLEAN/cert.pem" ]]; then
        echo "Xac nhan thu hoi chung chi SSL, SSL website $CLEAN"
        certbot revoke --cert-path /etc/letsencrypt/live/$CLEAN/cert.pem
        rm -rf /etc/letsencrypt/live/"$CLEAN"
    fi

    echo "==================================================================="
    echo "           Da xoa toan bo thanh cong website $CLEAN                 "
    echo "==================================================================="

fi
