#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Domain => Thay đổi PassWord user && khởi tạo đăng nhập username|"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website muốn thay đổi khởi tạo: "
lua_chon_NAME
echo ""

. /etc/wptt/echo-color

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-domain-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
	clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
	sleep 3
    . /etc/wptt/wptt-domain-main 1
	exit
fi
. /etc/wptt/vhost/.$NAME.conf

echo "Xác nhận bạn muốn khởi tạo đăng nhập username của website $NAME "
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ $dongy != 'y' ]];then
. /etc/wptt/wptt-domain-main 1
exit
fi

passwd $User_name_vhost

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-domain-main 1
fi
