#!/bin/bash

function huong_dan() {
  Đây là tính năng giúp tạm khoá website
  Tính năng bật và tắt này là tính năng tạm khoá website, không xoá mã nguồn bất kỳ thứ gì.
  chỉ đơn giản nó sẽ tạm ngừng hoạt động website hoặc bật lại nếu đã thiết lập tạm ngừng trước đó
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_domain => $mo_khoa_domain                                    |"
echo "========================================================================="

RED='\033[0;31m'
NC='\033[0m'
xanh='\033[0;32m'

if [ "$(ls -A /etc/wptt/vhost | sort -uV)" ]; then
  echo
  echo "$kiem_tra $mo_khoa_domain:"
  echo "========================================================================="
  for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
    domain=$(echo "$entry" | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1
    if [[ -d "$path" ]]; then
      if [[ -f /usr/local/lsws/conf/vhosts/"$domain"/"$domain".conf.bkwptt ]]; then
        hoatdong="$dang_duoc_tat"
        echo -e "$he_thong $kiem_tra website $domain :${RED} $hoatdong${NC}"
      else
        hoatdong="$dang_duoc_bat"
        echo -e "$he_thong $kiem_tra website $domain :${xanh} $hoatdong${NC}"
      fi
    fi
  done
  echo "========================================================================="
  echo
fi

. /etc/wptt/tenmien
echo "$lua_chon_website_ban_muon $bat/$tat "
lua_chon_NAME
echo ""

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  . /etc/wptt/wptt-domain-main 1
  exit
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "$ten_mien_nay_khong_ton_tai_tren_he_thong"
  sleep 3
  . /etc/wptt/wptt-domain-main 1
  exit
fi

. /etc/wptt/.wptt.conf

# if [[ "$Website_chinh" = "$NAME" ]];then
# echo "website chính $NAME Không thể sử dụng tính năng này"
# echo "website $NAME là website đại diện của VPS này "
# . /etc/wptt/wptt-domain-main 1
# exit
# fi

if [[ -f /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf.bkwptt ]]; then
  read -p "$ban_co_muon $bat website $NAME (y/n): " dongybatlai

  if [[ $dongybatlai = 'y' ]]; then
    _runing "$bat website $NAME"
    mv /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf.bkwptt /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
    chown -R lsadm:nobody /usr/local/lsws/conf/vhosts/$NAME
    chmod -R 750 /usr/local/lsws/conf/vhosts/$NAME
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

    . /etc/wptt/.wptt.conf
    if [[ $download_api ]]; then
      if [[ -f /etc/wptt/add-one/check.sh ]]; then
        if [[ $email_check_downtime && $telegram_id ]]; then
          . /etc/wptt/add-one/check.sh $telegram_id $telegram_api $email >/dev/null 2>&1
        fi
        if [[ -z $email_check_downtime && $telegram_id ]]; then
          . /etc/wptt/add-one/check.sh $telegram_id $telegram_api >/dev/null 2>&1
        fi
        if [[ $email_check_downtime && -z $telegram_id ]]; then
          . /etc/wptt/add-one/check.sh $email_check_downtime >/dev/null 2>&1
        fi
      fi
    fi

    _rundone "$bat website $NAME"
  fi

else

  read -p "$ban_co_muon $tat website $NAME (y/n): " dongytat
  if [[ $dongytat = 'y' ]]; then
    _runing "$tat website $NAME"
    mv /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf.bkwptt
    /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
    _rundone "$tat website $NAME"
    echo "Mọi dữ liệu của website $NAME vẫn giữ nguyên ở đó"
    echo "Tính năng này chỉ tạm thời ngừng hoạt động của website $NAME"
    echo "Nếu bạn cần kích hoạt bật trở lại thì hãy quay trở lại sử dụng tính năng này"

    . /etc/wptt/.wptt.conf
    if [[ $download_api ]]; then
      if [[ -f /etc/wptt/add-one/check.sh ]]; then
        if [[ $email_check_downtime && $telegram_id ]]; then
          . /etc/wptt/add-one/check.sh $telegram_id $telegram_api $email >/dev/null 2>&1
        fi
        if [[ -z $email_check_downtime && $telegram_id ]]; then
          . /etc/wptt/add-one/check.sh $telegram_id $telegram_api >/dev/null 2>&1
        fi
        if [[ $email_check_downtime && -z $telegram_id ]]; then
          . /etc/wptt/add-one/check.sh $email_check_downtime >/dev/null 2>&1
        fi
      fi
    fi

  fi
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-domain-main 1
fi
