#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Domain => Xoa doamin chuyen huong website                      |"
echo "========================================================================="
echo ""
echo ""

if [[ -d /etc/wptt/chuyen-huong ]]; then
    echo "Ban chua tung kich hoat chuyen huong domain nao het"
    exit
fi

function lua_chon_NAME() {
    NAME=""
    if [ "$(ls -At /etc/wptt/chuyen-huong)" ]; then
        selects=()
        for entry in $(ls -A /etc/wptt/chuyen-huong); do
            NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
            if [ "$NAME" != "${NAME/./}" ]; then
                selects+=("$NAME")
            fi
        done
        PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
        select select in ${selects[@]}; do
            NAME=$select
            index=$REPLY
            break
        done
    else
        clear
        echo "Khong co domain nao ton tai tren he thong cua ban."
        exit
    fi
}

lua_chon_NAME

path="/etc/wptt/chuyen-huong/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
    clear
    echo "Domain chuyen huong khong ton tai tren VPS."
    echo
    . /etc/wptt/wptt-domain-main
    exit
fi

rm -rf /usr/local/lsws/conf/vhosts/"$NAME"
User_name_vhost=${NAME//[-._]/wp}
userdel "$User_name_vhost"
rm -rf /home/$User_name_vhost
rm -rf /wptangtoc-ols/"$NAME"
rm -rf /usr/local/lsws/"$NAME"
sed -i "/$NAME $NAME/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/$NAME/,+10d" /usr/local/lsws/conf/httpd_config.conf
rm -f /etc/wptt/chuyen-huong/.$NAME.conf

/usr/local/lsws/bin/lswsctrl restart

echo "Hoan tat xoa chuyen huong domain $NAME"