#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2024
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_domain => $them_domain                                        |"
echo "========================================================================="
echo ""
echo ""

#chuyển mã ký tự
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8


. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color
NAME=$1

if [[ $NAME = "98" ]];then
	NAME=""
fi

if [[ $NAME = "" ]];then
	read -p "$nhap domain $hoac subdomain $ban_muon_them 
	($vi_du: wptangtoc.com, abc.wptangtoc.com ...) [0=$exit_thoat]: " NAME
fi

if [[ "$NAME" = "0" ]]; then
	clear
	. /etc/wptt/wptt-domain-main 1
	exit
fi

if [ "$NAME" = '' ]; then
	clear
	echo "$ban_chua_nhap_ten_domain."
	. /etc/wptt/wptt-domain-main 1
	exit
fi

if [ "$NAME" = "${NAME/./}" ]; then
	clear
	. /etc/wptt/echo-color
	echoDo "$domain_nhap_khong_dung_dinh_dang"
	exit
fi

#domain người dùng nhập sử dụng thêm space cách, sẽ báo không đúng định dạng
if [ $(echo $NAME | wc -w) -gt 1 ];then
clear
. /etc/wptt/echo-color
echoDo "$domain_nhap_khong_dung_dinh_dang"
exit
fi

path="/etc/wptt/vhost/.$NAME.conf"
if ! [[ ! -f "$path" ]]; then
	clear
	. /etc/wptt/echo-color
	echoDo "$ten_mien_da_ton_tai_he_thong_nay."
	. /etc/wptt/wptt-domain-main 1
	exit
fi


#chuyển đổi viết hoa thành chữ thường điều kiện
NAME=$(echo $NAME | tr '[:upper:]' '[:lower:]')

#kiem tra phan loai bo http:// va www
if [[ $(echo $NAME | grep '://') ]];then
	NAME=$(echo $NAME | cut -f3 -d '/')
fi

if [[ $(echo $NAME | grep '^www\.') ]];then
	NAME=$(echo $NAME | sed 's/^www.//g')
fi


USER=${NAME//[-._]/wp}

# # pathuser="/home/$USER"
# if [[ $(cat /etc/passwd | cut -f1 -d ':' | grep -w $USER) ]]; then
# 	clear
# 	echo "User đã tồn tại trên hệ thống này"
# 	echo
# 	. /etc/wptt/wptt-domain-main 1
# 	exit
# fi

. /etc/wptt/.wptt.conf

work_cpucore='1024'
cpucore=$(grep -c ^processor /proc/cpuinfo)
max_client=$(expr $work_cpucore \* $cpucore \* 2)
max_client_max=$(expr $work_cpucore \* $cpucore \* 3)
max_client_php=$(expr $work_cpucore \* $cpucore \/ 8)
tong_ram_byte=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
rong_ram_mb=$(echo "scale=0;${tong_ram_byte}/1024" | bc)

gioi_han_tien_trinh_bao_loi_503=$(expr $max_client \/ 8)


#maxConns https://openlitespeed.org/kb/troubleshooting-too-many-lsphp-processes-on-da-when-using-ols/

if [[ "$rong_ram_mb" = "" ]]; then
	rong_ram_mb="2048"
fi

_runing "$them domain $NAME $vao_he_thong"

#ky tu toi da là 32 ký tự user trong linux
check_ky_tu=$(echo $USER | wc -c)
if (( $check_ky_tu > 32 ));then
	USER=$(echo $USER | cut -c 1-30)
fi

# useradd $USER -p -m -d /home/$USER >/dev/null 2>&1
useradd -p -m -d /usr/local/lsws/$NAME $USER >/dev/null 2>&1
if [[ $(cat /etc/passwd | cut -f1 -d ':' | grep -w $USER) = '' ]];then
	random=$(
	date +%s | sha256sum | base64 | head -c 2
	echo
)

USER=${NAME//[-._]/$random}
USER=$(echo $USER | tr '[:upper:]' '[:lower:]')

check_ky_tu2=$(echo $USER | wc -c)
if (( $check_ky_tu2 > 32 ));then
	USER=$(echo $USER | cut -c 1-30)
fi
useradd -p -m -d /usr/local/lsws/$NAME $USER >/dev/null 2>&1
# useradd "$USER" -p -m -d /home/"$USER" >/dev/null 2>&1
fi

#xac dinh user đã được tạo lập chưa
if [[ $(cat /etc/passwd | cut -f1 -d ':' | grep -w $USER) = '' ]];then
	_runloi "$them domain $NAME $vao_he_thong"
	echoDo "Đã có lỗi vấn đề về hệ điều hành không thể tạo user mới"
	. /etc/wptt/wptt-domain-main 1
	exit
fi

version=$(curl -s https://wptangtoc.com/share/version-wptangtoc-ols.txt?domain-them=$NAME)
echo "virtualhost $NAME {
vhRoot                  /usr/local/lsws/$NAME/
configFile              /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
allowSymbolLink         1
enableScript            1
restrained              1
maxKeepAliveReq         $max_client
setUIDMode              2
user                    $USER
group                   $USER
}" >>/usr/local/lsws/conf/httpd_config.conf
sed -i "/listener http/a map 		$NAME $NAME" /usr/local/lsws/conf/httpd_config.conf
mkdir /usr/local/lsws/conf/vhosts/"$NAME"/
touch /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf

NAMEPHP=${NAME//[-._]/}

echo "docRoot                   /usr/local/lsws/$NAME/html
vhDomain                  $NAME
enableGzip                1
cgroups                   0


index  {
useServer               0
indexFiles              index.html index.php
autoIndex               0
}

scripthandler  {
add                     lsapi:$NAMEPHP php
}

accessControl  {
allow                   *
}

lsrecaptcha  {
enabled                 1
type                    0
}

extprocessor $NAMEPHP {
type                    lsapi
address                 uds://tmp/lshttpd/$NAMEPHP.sock
maxConns                30
env                     PHP_LSAPI_CHILDREN=30
env                     LSAPI_AVOID_FORK=200M
initTimeout             60
retryTimeout            0
pcKeepAliveTimeout      5
respBuffer              0
autoStart               1
path                    /usr/local/lsws/lsphp74/bin/lsphp
backlog                 100
instances               1
extUser                 $USER
extGroup                $USER
runOnStartUp            2
priority                0
memSoftLimit            ${rong_ram_mb}M
memHardLimit            ${rong_ram_mb}M
procSoftLimit           $gioi_han_tien_trinh_bao_loi_503
procHardLimit           $gioi_han_tien_trinh_bao_loi_503
}

context / {
  location                /usr/local/lsws/$NAME/html
  allowBrowse             1
  extraHeaders            <<<END_extraHeaders
X-XSS-Protection 1;mode=block
X-Frame-Options SAMEORIGIN
Referrer-Policy strict-origin-when-cross-origin
X-Content-Type-Options nosniff
X-Powered-By WPTangTocOLS
permissions-policy accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
  END_extraHeaders


  rewrite  {
  }
  addDefaultCharset       off

  phpIniOverride  {

  }
}


rewrite  {
enable                  1
autoLoadHtaccess        1
/usr/local/lsws/$NAME/html/.htaccess
}

vhssl  {
keyFile                 /etc/letsencrypt/live/$NAME/privkey.pem
certFile                /etc/letsencrypt/live/$NAME/cert.pem
certChain               0
CACertFile              /etc/letsencrypt/live/$NAME/chain.pem
sslProtocol             24
renegProtection         1
sslSessionCache         1
sslSessionTickets       1
enableSpdy              15
enableQuic              1
enableStapling          1
ocspRespMaxAge          86400
ocspResponder           http://cert.int-x3.letsencrypt.org/
ocspCACerts             /etc/letsencrypt/live/$NAME/chain.pem
}

module cache {
checkPrivateCache   1
checkPublicCache    1
maxCacheObjSize     10000000
maxStaleAge         200
qsCache             1
reqCookieCache      1
respCookieCache     1
ignoreReqCacheCtrl  1
ignoreRespCacheCtrl 0
storagePath /usr/local/lsws/$NAME/luucache
enableCache         0
expireInSeconds     3600
enablePrivateCache  0
privateExpireInSeconds 3600
ls_enabled              1
}" >/usr/local/lsws/conf/vhosts/$NAME/$NAME.conf


#tuong thich ubuntu tuong thich nhom litespeed
if $(cat /etc/*release | grep -q "Ubuntu") ; then
tuong_thich_nhom_litespeed="nogroup"
else
tuong_thich_nhom_litespeed="nobody"
fi

chown -R lsadm:$tuong_thich_nhom_litespeed /usr/local/lsws/conf/vhosts/$NAME
chmod -R 750 /usr/local/lsws/conf/vhosts/$NAME
mkdir -p /usr/local/lsws/$NAME
mkdir -p /usr/local/lsws/$NAME/html
mkdir -p /usr/local/lsws/$NAME/luucache
mkdir -p /usr/local/lsws/$NAME/backup-website
mkdir -p /usr/local/backup-website/$NAME
chmod 755 /usr/local/lsws/$NAME
chmod 755 /usr/local/lsws/$NAME/html
chmod 700 /usr/local/backup-website/$NAME
chmod 700 /usr/local/lsws/$NAME/backup-website

if [[ $wptangtoc_ols_giatuan = "" ]]; then
	cp -f /etc/wptt/index.php /usr/local/lsws/$NAME/html
	chown $USER:$USER /usr/local/lsws/$NAME/html/index.php
fi

chown -R $USER:$USER /usr/local/lsws/$NAME/html
chown -R $USER:$USER /usr/local/lsws/$NAME/backup-website


if [[ ! -f /usr/local/lsws/"$NAME"/html/.htaccess ]];then
echo '# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress' > /usr/local/lsws/"$NAME"/html/.htaccess
fi

_rundone "$them domain $NAME $vao_he_thong"

name_db=${NAME//[-._]/}
ramdom_db=$(
date +%s | sha256sum | base64 | head -c 18
echo
)
database=${name_db}_${ramdom_db}_dbname
username=${name_db}_${ramdom_db}_username
password=$(
date +%s | sha256sum | base64 | head -c 36
echo
)

#toi ky tu database la 64
check_ky_tu_database_name=$(echo $database | wc -c)
if (( $check_ky_tu_database_name > 60 ));then
	database=$(echo $database | cut -c 1-60)
fi

#toi ky tu database la 64
check_ky_tu_user_name=$(echo $username | wc -c)
if (( $check_ky_tu_user_name > 60 ));then
	username=$(echo $username | cut -c 1-60)
fi

_runing "$them database website $NAME"
mariadb -u $database_admin_username -p"$database_admin_password" -e "DROP DATABASE IF EXISTS ${database}"
mariadb -u $database_admin_username -p"$database_admin_password" -e "CREATE DATABASE IF NOT EXISTS ${database}"
mariadb -u $database_admin_username -p"$database_admin_password" -e "DROP USER IF EXISTS '${username}'@'localhost'"
mariadb -u $database_admin_username -p"$database_admin_password" -e "CREATE USER IF NOT EXISTS '${username}'@'localhost' IDENTIFIED BY '${password}'"
mariadb -u $database_admin_username -p"$database_admin_password" -e "GRANT ALL PRIVILEGES ON ${database}.* TO '${username}'@'localhost' WITH GRANT OPTION"
mariadb -u $database_admin_username -p"$database_admin_password" -e "FLUSH PRIVILEGES"
_rundone "$them database website $NAME"

php_version=$(php -v |grep cli | cut -c 4-7| sed 's/ //g')

touch /etc/wptt/vhost/.$NAME.conf
echo "DB_Name_web=$database
DB_User_web=$username
DB_Password_web=$password
Duong_Dan_thu_muc_web=/usr/local/lsws/$NAME/html
User_name_vhost=$USER
phien_ban_php_domain=$php_version" >/etc/wptt/vhost/.$NAME.conf

chown $USER:$USER /etc/wptt/vhost/.$NAME.conf

mkdir -p /wptangtoc-ols
mkdir -p /wptangtoc-ols/$NAME
mkdir -p /wptangtoc-ols/$NAME/backup-website
ln -s /usr/local/lsws/$NAME/html /wptangtoc-ols/$NAME
ln -s /usr/local/backup-website/$NAME/ /wptangtoc-ols/$NAME/backup-website


#tao anh xa username
# mkdir -p /home/$USER/$NAME
# ln -s /usr/local/lsws/$NAME/html /home/$NAME/public_html
# ln -s /usr/local/lsws/$NAME/backup-website /home/$NAME/backup-website

ln -s /usr/local/lsws/$NAME /home/$NAME


# add group
usermod -a -G wptangtoc-ols $USER

if [[ ! -f /usr/local/lsws/$NAME/.bashrc ]];then
cp -rf /etc/skel/. /usr/local/lsws/$NAME
fi

chown $USER:$USER /usr/local/lsws/$NAME/.*

echo '[[ $- != *i* ]] && return' >> /usr/local/lsws/$NAME/.bashrc
echo ". /etc/wptt-user/wptt-status" >> /usr/local/lsws/$NAME/.bashrc
echo "alias 1='wptangtoc-user'" >> /usr/local/lsws/$NAME/.bashrc
echo "alias 11='wptangtoc-user'" >> /usr/local/lsws/$NAME/.bashrc

chown $USER:$USER /usr/local/lsws/"$NAME"/html/.htaccess

# khong cho login quyen tai khoan trực tiếp chỉ sử dụng php exec
usermod $USER -s /sbin/nologin

if [[ -f /usr/local/lsws/$NAME/html/index.html ]];then
sed -i "s/domain.com/$NAME/g" /usr/local/lsws/"$NAME"/html/index.html
chown $USER:$USER /usr/local/lsws/"$NAME"/html/index.html
chmod 644 /usr/local/lsws/"$NAME"/html/index.html
fi


php_ver_chon=${php_version_check//[-._]/}
sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

RED='\033[0;31m'
NC='\033[0m'
echo -e "${RED}
     .:..........................             
      .::::::::::::::::::::::::::::..         
        ..:::::::::::::::::::::::::::::.      
                             ...:::::::::.    
                                  .:::::::.   
          .:::::::.         .       .:::::::  
         .::::::::::::::::::::..      ::::::: 
         ::::::::::::::::::::::::.     ::::::.
        .::::::::::::::::::::::::::.   .:::::.
        .::::::::::::::::::::::::::::  .:::::.
        .::::::::::::::::::::::::::.   .:::::.
         ::::::::::::::::::::::::.     ::::::.
.::::::  .:::::::::::::::::::::.      ::::::. 
          .:::::::.                 .:::::::  
       ::::::::::::.              .:::::::.   
       ......:::::::::...    ...:::::::::.    
               .:::::::::::::::::::::::.      
   ..............::::::::::::::::::..         
  .:::::::::::::................. ${NC}"

echo "========================================================================="
echo "$cai_dat_thanh_cong                         "
echo "========================================================================="
echo "$them $thanh_cong website $NAME                   "
echo "========================================================================="
echo "========================================================================="
echo "Disk		: $(df -BG | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')                        "
echo "RAM		: $(free -m | awk 'NR==2{printf "%s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }')                         "
echo "========================================================================="
echo "DB_Name		: $database                                "
echo "DB_User		: $username                                "
echo "DB_Password	: $password				 "
echo "$duong_dan_thu_muc: /usr/local/lsws/$NAME/html              "
echo "$moi_thong_tin_tai_khoan_da_duoc_luu_tru:  /etc/wptt/vhost/.$NAME.conf    "
echo "========================================================================="
echo "$phat_trien_boi_gia_tuan"
echo "========================================================================="
checkdns=$(host $NAME | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
if [[ "$checkdns" = "" ]]; then
	checkdns=$(nslookup $NAME | grep Address | cut -f5 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
fi

ip=$(curl -s myip.directadmin.com)
if [[ "$ip" = "" ]]; then
	ip=$(curl -s ifconfig.me)
fi

if [[ "$checkdns" != "$ip" ]]; then
	if [[ "$checkdns" = "" ]]; then
		echo "$ten_mien $NAME $chua_duoc_tro_ip, $ban_vui_long_tro_ip_ve $ip"
	else
		echo "Hãy trỏ DNS domain $NAME: $checkdns thành $ip để tận hưởng thành quả"
	fi
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-domain-main 1
fi

