#!/bin/bash
echo "========================================================================="
echo "|Quản lý bảo mật => CSF => Chặn IP                                      |"
echo "========================================================================="
. /etc/wptt/echo-color

if [ ! -f /etc/csf/csf.conf ]; then
	echoDo "Bạn chưa cài đặt CSF"
	. /etc/wptt/wptt-bao-mat-main/csf-main 1
fi

read -r -p "Nhập địa chỉ IP bạn muốn Block: " ip
if ! [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
echoDo "Bạn nhập không đúng định dạng IPv4"
. /etc/wptt/wptt-bao-mat-main/csf-main 1
fi
_runing "Tiến hành Block IP $ip"
csf -d "${ip}" >/dev/null 2>&1
csf -x >/dev/null 2>&1
csf -e >/dev/null 2>&1
systemctl restart csf
systemctl restart lfd
_rundone "Tiến hành Block IP $ip"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-bao-mat-main/csf-main 1
fi




