#!/bin/bash

function huong_dan() {
  Tính năng Hủy thiết lập chặn quốc gia CSF trong WPTangToc OLS cho phép bạn gỡ bỏ hoặc vô hiệu hóa các quy tắc chặn [hoặc chỉ cho phép] truy cập từ các quốc gia cụ thể đã được cấu hình trước đó trong tường lửa ConfigServer Security &
  Firewall [CSF].

  🎯 Mục đích của việc hủy thiết lập chặn quốc gia
  * Khắc phục sự cố truy cập: Nếu việc chặn quốc gia đang vô tình ngăn cản người dùng hợp lệ hoặc các dịch vụ cần thiết truy cập vào máy chủ của bạn.
  * Thay đổi chính sách truy cập: Khi bạn không còn muốn giới hạn truy cập dựa trên vị trí địa lý nữa hoặc muốn mở rộng phạm vi truy cập cho website/dịch vụ.
  * Đơn giản hóa cấu hình tường lửa: Loại bỏ các quy tắc chặn theo quốc gia nếu chúng không còn cần thiết hoặc để giảm độ phức tạp trong quản lý CSF.
  * Thử nghiệm hoặc chuyển đổi chiến lược: Muốn tạm thời vô hiệu hóa để kiểm tra hoặc thay đổi sang một phương pháp kiểm soát truy cập khác.

  Tóm lại, tính năng Hủy thiết lập chặn quốc gia CSF trong WPTangToc OLS giúp bạn dễ dàng gỡ bỏ các rào cản truy cập dựa trên vị trí địa lý đã đặt ra trước đó trong CSF, cho phép máy chủ của bạn nhận truy cập từ mọi quốc gia [trừ khi có các quy tắc chặn IP cụ thể khác].
}

echo "========================================================================="
echo "|Quản lý bảo mật => CSF => Chặn Quốc gia                               |"
echo "========================================================================="

. /etc/wptt/echo-color
if [ ! -f /etc/csf/csf.conf ]; then
  echoDo "Bạn chưa cài đặt CSF"
  exec /etc/wptt/bao-mat/csf-main 1
fi

countryblicklist=$(grep "CC_DENY =\ " /etc/csf/csf.conf | awk 'NR==1 {print $3}' | cut -d \" -f 2)
if [ "$countryblicklist" = "" ]; then
  echo "========================================================================="
  echo "Hiện tại CSF Firewall không chặn quốc gia nào. "
  echo "-------------------------------------------------------------------------"
fi

echo "Sử dụng chức năng này để block một số quốc gia truy cập website trên server."
echo "-------------------------------------------------------------------------"
echo "Bạn cần nhập mã quốc gia gồm 2 chữ cái. Bạn có thể nhập nhiều đất nước bằng cách"
echo "-------------------------------------------------------------------------"
echo "cách sử dụng dâu phảy [,] và không có dấu cách [space] giữa các mã nước. VD: PK,CN,RU,DE "
echo "-------------------------------------------------------------------------"
echo "Để chặn quốc gia Pakistan,China,Russia,Germany."
echo "-------------------------------------------------------------------------"
echo "========================================================================="
read -rp "Nhập mã nước [0 = Thoát] [99 = Xem mã quốc gia]: " countrycode

if [[ $countrycode = '99' ]]; then
  cat /etc/wptt/bao-mat/csf/quoc-gia-ma-code-csf | sed 's/|$//g' | sed 's/|/==> /g'
  echo -n "Nhập mã nước [0 = Thoát]: "
  read countrycode
fi

if [[ $countrycode = '' || $countrycode = '0' ]]; then
  exec /etc/wptt/bao-mat/csf-main 1
fi

rm -f /tmp/wptangtoc_tmp_check_quoc_gia_block
rm -f /tmp/wptangtoc_ols_code_code_trung_nhau
rm -f /tmp/wptangtoc_ols_code_code_trung_nhau2
rm -f /tmp/wptangtoc_list_show_quoc_gia
rm -f /tmp/wptangtoc_ols_code_list_for

countrycode=$(echo "$countrycode" | tr '[a-z]' '[A-Z]')
countrycode=$(echo "$countrycode" | sed 's/\///' | sed 's/\///' | sed 's/\///')
echo "$countrycode" >/tmp/wptangtoc_tmp_check_quoc_gia_block
sed -i 's/,$//' /tmp/wptangtoc_tmp_check_quoc_gia_block

cat /tmp/wptangtoc_tmp_check_quoc_gia_block | awk -F, '{for (i=1;i<=NF;i++)print $i}' >/tmp/wptangtoc_ols_code_list_for

country_list=$(cat /tmp/wptangtoc_ols_code_list_for)

for manuoc in $country_list; do
  if [ ! ${#manuoc} == "2" ]; then
    clear
    echo "========================================================================= "
    echo "Ma nuoc $manuoc khong ton tai."
    echo "-------------------------------------------------------------------------"
    echo "Ban hay nhap lai !"
    exec /etc/wptt/bao-mat/csf-main 1
    exit
  fi

  if [ "$(grep "|${manuoc}|" /etc/wptt/bao-mat/csf/quoc-gia-ma-code-csf)" = "" ]; then
    clear
    echo "========================================================================= "
    echo "Ma nuoc $manuoc khong ton tai."
    echo "-------------------------------------------------------------------------"
    echo "Ban hay nhap lai !"
    exec /etc/wptt/bao-mat/csf-main 1
    exit
  else
    echo "$(grep "|${manuoc}|" /etc/wptt/bao-mat/csf/quoc-gia-ma-code-csf | sed "s/|${manuoc}|//")" >>/tmp/wptangtoc_list_show_quoc_gia
  fi

  echo "${manuoc}" >>/tmp/wptangtoc_ols_code_code_trung_nhau
  grep "${manuoc}" /tmp/wptangtoc_ols_code_code_trung_nhau >/tmp/wptangtoc_ols_code_code_trung_nhau2
  codetrungnhau=$(cat /tmp/wptangtoc_ols_code_code_trung_nhau2)
  if [ ! ${#codetrungnhau} = "2" ]; then
    clear
    echo "========================================================================= "
    echo "Ma nuoc $manuoc xuat hien nhieu hon 1 lan trong danh sach ban nhap."
    echo "-------------------------------------------------------------------------"
    echo "Ban hay nhap lai !"
    exec /etc/wptt/bao-mat/csf-main 1
    exit
  fi

done

sonuoc=$(cat /tmp/wptangtoc_list_show_quoc_gia | wc -l)
if [ ! "$sonuoc" = 1 ]; then
  nuoc=countries
  hoithoai1=$(echo "Danh sach cac nuoc ban muon block boi CSF Firewall:")
  hoithoai2=$(echo "Ban muon block $sonuoc nuoc trong danh sach ?")
else
  nuoc=country
  hoithoai1=$(echo "Nuoc ban muon block boi CSF Firewall:")
  hoithoai2=$(echo "Ban muon block dat nuoc nay ?")
fi
echo "========================================================================="
echo "$hoithoai1"
echo "-------------------------------------------------------------------------"
cat /tmp/wptangtoc_list_show_quoc_gia | pr -2 -t
echo "========================================================================="
echo "$hoithoai2 ?"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
  case "$REPLY" in
  1)
    dongy="y"
    break
    ;;

  2)
    dongy="n"
    break
    ;;

  $((${#options[@]} + 1)))
    printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
    break
    ;;
  *)
    printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
    break
    ;;
  esac
done

if [[ $dongy = 'y' ]]; then
  _runing "Chặn các quốc gia truy cập: $(cat /tmp/wptangtoc_tmp_check_quoc_gia_block)"
  sed -i 's/,$//' /tmp/wptangtoc_tmp_check_quoc_gia_block
  sed -i "s/.*CC_DENY\ =.*/CC_DENY = \"$(cat /tmp/wptangtoc_tmp_check_quoc_gia_block)\"/g" /etc/csf/csf.conf
  _rundone "Hoàn tất chặn các quốc gia truy cập: $(cat /tmp/wptangtoc_tmp_check_quoc_gia_block)"
  rm -f /tmp/wptangtoc_tmp_check_quoc_gia_block
  rm -f /tmp/wptangtoc_ols_code_code_trung_nhau
  rm -f /tmp/wptangtoc_ols_code_code_trung_nhau2
  rm -f /tmp/wptangtoc_list_show_quoc_gia
  rm -f /tmp/wptangtoc_ols_code_list_for

  csf -x >/dev/null 2>&1
  csf -e >/dev/null 2>&1
  systemctl restart csf
  systemctl restart lfd
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  exec /etc/wptt/bao-mat/csf-main 1
fi
