#!/bin/bash

echo "========================================================================="
echo "|Quản lý bảo mật => CSF => Chỉ cho Quốc gia truy cập                    |"
echo "========================================================================="

. /etc/wptt/echo-color
if [ ! -f /etc/csf/csf.conf ]; then
	echoDo "Bạn chưa cài đặt CSF"
	. /etc/wptt/bao-mat/csf-main 1
fi

countryblicklist=`grep "CC_ALLOW_FILTER =\ " /etc/csf/csf.conf | awk 'NR==1 {print $3}' | cut -d \" -f 2`
if [ "$countryblicklist" = "" ]; then
echo "========================================================================="
echo "Hien tai CSF Firewall khong block dat nuoc chưa được thiết lập. "
echo "-------------------------------------------------------------------------"
fi

echo "Sử dụng chức năng này để block một số quốc gia được truy cập website trên server."
echo "-------------------------------------------------------------------------" 
echo "Bạn cần nhập mã quốc gia gồm 2 chữ cái. Bạn có thể nhập nhiều đất nước bằng cách"
echo "-------------------------------------------------------------------------" 
echo "cách sử dụng dâu phảy [,] và không có dấu cách [space] giữa các mã nước. VD: PK,CN,RU,DE "
echo "-------------------------------------------------------------------------" 
echo "Để chặn quốc gia Pakistan,China,Russia,Germany."
echo "-------------------------------------------------------------------------" 
echo "========================================================================="
read -p "Nhập mã nước [0 = Thoát] [99 = Xem mã quốc gia]: " countrycode

if [[ $countrycode = '99' ]];then
cat /etc/wptt/bao-mat/csf/quoc-gia-ma-code-csf |sed 's/|$//g' | sed 's/|/==> /g'
echo -n "Nhập mã nước [0 = Thoát]: " 
read countrycode
fi


if [[ $countrycode = '' || $countrycode = '0' ]];then
. /etc/wptt/bao-mat/csf-main 1
fi

rm -f /tmp/wptangtoc_tmp_check_quoc_gia_block
rm -f /tmp/wptangtoc_ols_code_code_trung_nhau
rm -f /tmp/wptangtoc_ols_code_code_trung_nhau2
rm -f /tmp/wptangtoc_list_show_quoc_gia
rm -f /tmp/wptangtoc_ols_code_list_for


countrycode=$(echo $countrycode | tr '[a-z]' '[A-Z]')
countrycode=$(echo $countrycode | sed 's/\///' | sed 's/\///' | sed 's/\///')
echo "$countrycode" > /tmp/wptangtoc_tmp_check_quoc_gia_block
sed -i 's/,$//' /tmp/wptangtoc_tmp_check_quoc_gia_block

cat /tmp/wptangtoc_tmp_check_quoc_gia_block | awk -F, '{for (i=1;i<=NF;i++)print $i}' > /tmp/wptangtoc_ols_code_list_for

country_list=$(cat /tmp/wptangtoc_ols_code_list_for)

for manuoc in $country_list; do
 if [ ! ${#manuoc}  == "2" ]; then 
clear
echo "========================================================================= "
echo "Ma nuoc $manuoc khong ton tai."
echo "-------------------------------------------------------------------------"
echo "Ban hay nhap lai !"
. /etc/wptt/bao-mat/csf-main 1
exit
fi


if [ "$(grep "|${manuoc}|" /etc/wptt/bao-mat/csf/quoc-gia-ma-code-csf)" = "" ]; then
clear
echo "========================================================================= "
echo "Ma nuoc $manuoc khong ton tai."
echo "-------------------------------------------------------------------------"
echo "Ban hay nhap lai !"
. /etc/wptt/bao-mat/csf-main 1
exit
else
echo "$(grep "|${manuoc}|" /etc/wptt/bao-mat/csf/quoc-gia-ma-code-csf | sed "s/|${manuoc}|//")" >> /tmp/wptangtoc_list_show_quoc_gia
fi

echo "${manuoc}" >> /tmp/wptangtoc_ols_code_code_trung_nhau
grep "${manuoc}" /tmp/wptangtoc_ols_code_code_trung_nhau > /tmp/wptangtoc_ols_code_code_trung_nhau2
codetrungnhau=`cat /tmp/wptangtoc_ols_code_code_trung_nhau2`
if [ ! ${#codetrungnhau} = "2" ]; then 
clear
echo "========================================================================= "
echo "Ma nuoc $manuoc xuat hien nhieu hon 1 lan trong danh sach ban nhap."
echo "-------------------------------------------------------------------------"
echo "Ban hay nhap lai !"
. /etc/wptt/bao-mat/csf-main 1
exit
fi

done

sonuoc=`cat /tmp/wptangtoc_list_show_quoc_gia | wc -l`
if [ ! "$sonuoc" = 1 ]; then
nuoc=countries
hoithoai1=`echo "Danh sach cac nuoc được phép truy cập bởi CSF Firewall:"`
hoithoai2=`echo "Ban muon block toàn bộ các nước chỉ cho phép $sonuoc nuoc trong danh sach ?"`
else
nuoc=country
hoithoai1=`echo "Bạn muốn chặn tất cả các nước chỉ cho phép quốc gia này truy cập bởi CSF Firewall:"`
hoithoai2=`echo "Bạn muốn chặnt tất cả các quốc gia ngoại trừ quốc gia này?"`
fi
echo "========================================================================="
echo "$hoithoai1"
echo "-------------------------------------------------------------------------"
cat /tmp/wptangtoc_list_show_quoc_gia | pr -2 -t
echo "========================================================================="
echo "$hoithoai2 ?"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ $dongy = 'y' ]];then
_runing "Chặn toàn bộ quốc giá chỉ cho phép các quốc gia truy cập: $(cat /tmp/wptangtoc_tmp_check_quoc_gia_block)"
sed -i 's/,$//' /tmp/wptangtoc_tmp_check_quoc_gia_block
sed -i "s/.*CC_ALLOW_FILTER\ =.*/CC_ALLOW_FILTER = \"$(cat /tmp/wptangtoc_tmp_check_quoc_gia_block)\"/g" /etc/csf/csf.conf
_rundone "Chặn toàn bộ quốc giá chỉ cho phép các quốc gia truy cập: $(cat /tmp/wptangtoc_tmp_check_quoc_gia_block)"
rm -f /tmp/wptangtoc_tmp_check_quoc_gia_block
rm -f /tmp/wptangtoc_ols_code_code_trung_nhau
rm -f /tmp/wptangtoc_ols_code_code_trung_nhau2
rm -f /tmp/wptangtoc_list_show_quoc_gia
rm -f /tmp/wptangtoc_ols_code_list_for

csf -x >/dev/null 2>&1
csf -e >/dev/null 2>&1
systemctl restart csf
systemctl restart lfd
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/bao-mat/csf-main 1
fi

