#!/bin/bash

echo "========================================================================="
echo "|Quản lý bảo mật => CSF => Hủy bỏ Chặn Quốc gia                         |"
echo "========================================================================="

. /etc/wptt/echo-color
if [ ! -f /etc/csf/csf.conf ]; then
	echoDo "Bạn chưa cài đặt CSF"
	. /etc/wptt/bao-mat/csf-main 1
fi

countryblicklist=`grep "CC_DENY =\ " /etc/csf/csf.conf | awk 'NR==1 {print $3}' | cut -d \" -f 2`
if [ "$countryblicklist" = "" ]; then
echo "========================================================================="
echo "Hiện tại CSF Firewall chặn quốc gia chưa được thiết lập. "
echo "-------------------------------------------------------------------------"
. /etc/wptt/bao-mat/csf-main 1
fi
_runing "Tắt tính năng chặn toàn bộ quốc gia chỉ cho phép một số quốc gia được truy cập"
sed -i "s/.*CC_DENY\ =.*/CC_DENY = \"\"/g" /etc/csf/csf.conf
csf -x >/dev/null 2>&1
csf -e >/dev/null 2>&1
systemctl restart csf
systemctl restart lfd
_rundone "Tắt tính năng chặn toàn bộ quốc gia chỉ cho phép một số quốc gia được truy cập"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/bao-mat/csf-main 1
fi

