#!/bin/bash
echo "========================================================================="
echo "|Quản lý bảo mật => CSF => Chống DDOS chế độ                            |"
echo "========================================================================="
. /etc/wptt/echo-color
if [ ! -f /etc/csf/csf.conf ]; then
	echoDo "Bạn chưa cài đặt CSF"
	echoDo "Nếu bạn muốn sử dụng tính năng này vui lòng cài đặt CSF trước"
	. /etc/wptt/bao-mat/csf-main 1
fi

_runing "Thiết lập chống ddos bằng CSF"
sed -i 's/CT_LIMIT = "0"/CT_LIMIT = "150"/g' /etc/csf/csf.conf
sed -i 's/CT_EMAIL_ALERT = "1"/CT_EMAIL_ALERT = "0"/g' /etc/csf/csf.conf
sed -i 's/CT_PORTS = ""/CT_PORTS = "80,443"/g' /etc/csf/csf.conf
sed -i 's/SYNFLOOD = "0"/SYNFLOOD = "1"/g' /etc/csf/csf.conf

#smtp
if [[ $(cat /etc/csf/csf.conf | grep 'TCP_OUT' | grep '465,') = '' ]];then
sed "s/^TCP_OUT = \"/TCP_OUT = \"465,/g" /etc/csf/csf.conf
fi

csf -x >/dev/null 2>&1
csf -e >/dev/null 2>&1
systemctl restart csf
systemctl restart lfd
_rundone "Thiết lập chống ddos bằng CSF"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/bao-mat/csf-main 1
fi

