#!/bin/bash
echo "========================================================================="
echo "|Quản lý bảo mật => CSF => Chống DDOS chế độ                            |"
echo "========================================================================="
. /etc/wptt/echo-color
if [ ! -f /etc/csf/csf.conf ]; then
	echoDo "Bạn chưa cài đặt CSF"
	echoDo "Nếu bạn muốn sử dụng tính năng này vui lòng cài đặt CSF trước"
	. /etc/wptt/bao-mat/csf-main 1
fi

_runing "Thiết lập chống ddos bằng CSF"
sed -i "/^CT_LIMIT/s/\"[^\"]*\"/\"150\"/1" /etc/csf/csf.conf
sed -i "/^CT_EMAIL_ALERT/s/\"[^\"]*\"/\"0\"/1" /etc/csf/csf.conf
sed -i "/^CT_PORTS/s/\"[^\"]*\"/\"80,443\"/1" /etc/csf/csf.conf
sed -i "/^SYNFLOOD/s/\"[^\"]*\"/\"1\"/1" /etc/csf/csf.conf

#CONNLIMIT là giới hạn kết nối của từ ip: port;số lượng kết nối của ip
# config này là port 1 ip tối đa 20 kết nối, port 443 1 ip tối đa 15 kết nối
sed -i "/^CONNLIMIT/s/\"[^\"]*\"/\"80;20,443;30\"/1" /etc/csf/csf.conf


#smtp
if [[ $(cat /etc/csf/csf.conf | grep 'TCP_OUT' | grep '465,') = '' ]];then
sed "s/^TCP_OUT = \"/TCP_OUT = \"465,/g" /etc/csf/csf.conf
fi

csf -x >/dev/null 2>&1
csf -e >/dev/null 2>&1
systemctl restart csf
systemctl restart lfd
_rundone "Thiết lập chống ddos bằng CSF"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/bao-mat/csf-main 1
fi

