#!/bin/bash
echo "========================================================================="
echo "|Quản lý bảo mật => CSF => Hủy Cài Đặt                                  |"
echo "========================================================================="

if [[ ! -f /etc/csf/csf.conf ]];then
systemctl stop csf
systemctl stop lfd
systemctl disable csf
systemctl stop lfd
. /etc/csf/uninstall.sh
yum install remove perl-libwww-perl.noarch perl-Time-HiRes -y
rm -rf /etc/csf
systemctl start firewalld
systemctl enable firewalld
echo "Hoàn tất Xóa cài đặt CSF"
else
echo "Bạn chưa đã cài đặt CSF"
fi
