#!/bin/bash
echo "========================================================================="
echo "|Quản lý bảo mật => CSF => Cài Đặt                                      |"
echo "========================================================================="

if [[ ! -f /etc/csf/csf.conf ]];then
yum install perl-libwww-perl.noarch perl-Time-HiRes -y
cd /usr/src/
if [[ -f /usr/src/csf.tgz ]];then
rm -f /usr/src/csf.tgz
fi

wget https://download.configserver.com/csf.tgz --no-check-certificate
tar -xzf csf.tgz
cd csf
sh install.sh
cd /usr/local/csf/bin/
perl csftest.pl
systemctl stop firewalld
systemctl disable firewalld
systemctl mask firewalld

sed -i 's/TESTING = "1"/TESTING = "0"/g' /etc/csf/csf.conf

sed -i 's/# .googlebot.com/.googlebot.com/g' /etc/csf/csf.rignore
sed -i 's/# .crawl.yahoo.net/.crawl.yahoo.net/g' /etc/csf/csf.rignore
sed -i 's/# .search.msn.com/.search.msn.com/g' /etc/csf/csf.rignore
echo ".lscache_runner" >> /etc/csf/csf.rignore

echo "216.239.32.0/19 # Googlebot
64.233.160.0/19 # Googlebot
72.14.192.0/18 # Googlebot
209.85.128.0/17 # Googlebot
66.102.0.0/20 # Googlebot
74.125.0.0/16 # Googlebot
66.249.64.0/19 #Googlebotallow" >> /etc/csf/csf.allow

# sed -i '/TESTING = /d' /etc/csf/csf.conf
# sed -i '/while this is enable/a TESTING = "0"' /etc/csf/csf.conf
systemctl start csf
systemctl start lfd
systemctl enable csf
systemctl enable lfd
echo "Hoàn tất cài đặt CSF"
else
echo "Bạn đã cài đặt trước đó rồi"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/bao-mat/csf-main 1
fi

