#!/bin/bash
clear
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Domain => Kiem tra tinh trang hoat dong cac domain             |"
echo "========================================================================="
echo ""
echo ""

if [ "$(ls -A /etc/wptt/vhost)" ]; then
  echo
  echo "Kiem tra hoat dong website"
  echo "========================================================================="
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$(echo "$entry" | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
      checkssl=$(curl -Is https://"${domain}" | head -n 1 | grep -c "200")
      checkssl2=$(curl -Is http://"${domain}" | head -n 1 | grep -c "200")
      if [[ "$checkssl" = "0" && "$checkssl2" = "0" ]]; then
        hoatdong="Ngung hoat dong"
      else
        hoatdong="Hoat dong tot"
      fi
      echo "He thong kiem tra website $domain : $hoatdong"

    fi

  done
  echo "========================================================================="
  echo
fi
