#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Fail2ban => Khoa dia chi IP                                    |"
echo "========================================================================="
echo ""
echo ""
read -p "Nhap Ip ban muon khoa: " ip
echo "Dang tien hanh khoa IP $ip ..."
fail2ban-client set sshd banip $ip
echo "Da khoa IP $ip."
