#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_ip => $khoa_ip                                  |"
echo "========================================================================="
echo ""
echo ""
read -p "$nhap $ip_ban_muon_khoa [0=$exit_thoat]: " ip

if [[ $ip = '' || $ip = '0' ]];then
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-khoa-ip-main 1
fi
return 2>/dev/null;exit
fi

if [[ $(echo $ip |grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' = '' ]];then
echoDo "$ban_nhap_khong_dung_dinh_dang_ipv4"
. /etc/wptt/wptt-khoa-ip-main 1
exit
fi

. /etc/wptt/echo-color
_runing "$khoa_ip $ip"
#Khoá ip trên litespeed
checkip=$(cat /usr/local/lsws/conf/httpd_config.conf |grep 'deny'| grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
if [[ $(echo $checkip | grep $ip) = '' ]];then
	if [[ "$checkip" = "" ]];then
		sed -i "/accessControl/a deny			$ip" /usr/local/lsws/conf/httpd_config.conf
	else
		sed -i "s/$checkip/& ,$ip/" /usr/local/lsws/conf/httpd_config.conf
	fi
	/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi

#khoá ip trên ssh
fail2ban-client set sshd banip $ip >/dev/null 2>&1

#khoá ip bằng tường lửa
if [[ $(which csf 2>/dev/null) ]];then
csf -d $ip >/dev/null 2>&1
else
firewall-cmd --permanent --add-rich-rule="rule family='ipv4' source address=$ip reject" >/dev/null 2>&1
firewall-cmd --reload >/dev/null 2>&1
fi


echo "Khoá ip $ip: $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

_rundone "$khoa_ip $ip"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-khoa-ip-main 1
fi


