#!/bin/bash
clear
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_ip => $danh_sach_ip_da_bi_khoa                             |"
echo "========================================================================="
echo ""
echo ""

#fail2ban block
zgrep -h "Ban " /var/log/fail2ban.log* | awk '{print $NF}' | sort | uniq >/tmp/banip_list

#csf block
if [[ -f /etc/csf/csf.deny ]];then
	grep -v '^#' /etc/csf/csf.deny | awk '{print $1}' >> /tmp/banip_list
fi

#litespeed block
cat /usr/local/lsws/conf/httpd_config.conf |grep 'deny'| grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' >>/tmp/banip_list


#check tuong lua firewalld
if [[ $(systemctl status firewalld.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs) = 'active' ]];then
firewall-cmd --permanent --list-all | grep "rule family" | grep 'reject' | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' >> /tmp/banip_list
fi

list_ip=$(cat /tmp/banip_list| sed '/^$/d'| sort -u | uniq)
if [[ $list_ip = '' ]];then
	echo "Hiện tại chưa có IP nào đang bị chặn"
else
	echo $list_ip | tr ' ' "\n"
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-khoa-ip-main 1
fi

