#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Mở/khóa IP => Mở khoá IP                                       |"
echo "========================================================================="

read -p "Nhập ip bạn muốn mở khoá [Thoát = 0]: " ip

if [[ $ip = '' || $ip = '0' ]];then
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-bao-mat-main 1
	fi
	return 2>/dev/null;exit
fi

if ! [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
echoDo "Bạn nhập không đúng định dạng IPv4"
. /etc/wptt/wptt-khoa-ip-main 1
exit
fi
. /etc/wptt/echo-color
_runing "Mở khoá ip $ip"
# fail2ban-client set sshd unbanip $ip
for rules in $(fail2ban-client status | grep 'Jail list:' | cut -f2 -d ':' | tr ',' '\n' | uniq | sed 's/\t//g' |sed 's/ //g');do
fail2ban-client set "$rules" unbanip "$ip" >/dev/null 2>&1
done


if [[ $(cat /usr/local/lsws/conf/httpd_config.conf | grep "$ip") ]]; then
ip_all_block_litespeed=$(cat /usr/local/lsws/conf/httpd_config.conf |grep 'deny'| grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
if [[ $(echo $ip_all_block_litespeed| wc -l) = '1' ]];then
	sed -i '/^deny/d' /usr/local/lsws/conf/httpd_config.conf
else
	# sed -i -r '/^deny /s/"'$ip'"/""/; s/([",])'$ip',|,'$ip'([,"])/\1\2/' /usr/local/lsws/conf/httpd_config.conf
	if [[ $(echo $ip_all_block_litespeed | head -1) = "$ip"  ]];then
		#clean giá trị đầu tiên nhập vào sử dụng
		sed -i "s/$ip ,//g" /usr/local/lsws/conf/httpd_config.conf
	else
		#clean giá trị từ 2 trở đi
		sed -i "s/ ,$ip//g" /usr/local/lsws/conf/httpd_config.conf
	fi
fi
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi


_rundone "Mở khoá ip $ip"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-khoa-ip-main 1
fi
