#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021


. /etc/wptt/.wptt.conf

if [[ $id_dang_nhap_phpmyadmin = "" ]];then
echo "ban chua kich hoat phpmyadmin"
exit
fi

rm -rf /usr/local/lsws/$Website_chinh/html/phpmyadmin
rm -rf /usr/local/lsws/"$Website_chinh"/passwd/.phpmyadmin

sed -i "$id_dang_nhap_phpmyadmin/d" /etc/wptt/.wptt.conf
sed -i "$password_dang_nhap_phpmyadmin/d" /etc/wptt/.wptt.conf
sed -i '/realm/,$d' /usr/local/lsws/conf/vhosts/"$Website_chinh"/"$Website_chinh".conf

if [[ -f /usr/local/lsws/"$Website_chinh"/passwd/.mk ]];then
NAME="$Website_chinh"
  echo 'realm '$NAME' {

  userDB  {
    location              /usr/local/lsws/'$NAME'/passwd/.mk
  }
}

context exp:wp-login.php {
  location                $DOC_ROOT/$0
  allowBrowse             1
  realm                   '$NAME'

  accessControl  {
    allow                 ALL
  }

  rewrite  {

  }
  addDefaultCharset	  off

  phpIniOverride  {

  }
}' >>/usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
  /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
else
rm -rf /usr/local/lsws/"$Website_chinh"/passwd
fi

echo "Hoan tat xoa cai dat phpmyadmin"

