#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý PhpMyAdmin => Kích hoạt PhpMyAdmin                             |"
echo "========================================================================="
echo ""
. /etc/wptt/.wptt.conf

if [[ $id_dang_nhap_phpmyadmin && -d /usr/local/lsws/$Website_chinh/html/phpmyadmin ]];then
	. /etc/wptt/echo-color
	echoDo "Bạn đã kích hoạt PhpMyadmin trước đó rồi"
sleep 3
    . /etc/wptt/wptt-phpmyadmin-main 1
exit
fi

. /etc/wptt/echo-color


if [[ $(cat /usr/local/lsws/$Website_chinh/html/.htaccess | grep '#begin-tuong-lua-bao-mat-7g') ]];then
	echo "website chính $Website_chinh đang sử dụng tường lửa 7G"
	echo "Nếu bạn muốn sử dụng PhpMyadmin thì vui lòng tắt tường lửa 7G"
	echo "Khi nào sử dụng xong PhpMyadmin thì hãy bật lại tường lửa 7G cho website $Website_chinh"
    . /etc/wptt/wptt-phpmyadmin-main 1
	exit;
fi

echo '                                                .               
                                               ::               
                                               *. ::            
                                     -        +*   *:           
                                    =+       :#+   =#-          
                                   .#-      .##= : -##=         
                                   *#:      *##= =-:#*#+        
                                  -##:     +###- .#+*###*.      
                                 .##*.    +####:  *#++###*:     
                                 *##*    +####*.  *##=:=***=    
                                =###+   +#####*.  *###+  .:=:   
                               :####= :#######+   ***+*=        
                               +**++: --:::::::...-------:..    
        ::         --.  --     :.:--:-:---=--=======+==:        
  ----..==-: ---- =#*..*#+:= :=-+*+*=-+++*+-*+*+++-++-+-=:      
 :=.:=-=:.+:-=.-=-*-*+++*.*- *--*+=#-=*.-*:*--*.++-*:*-.*-      
.==--.:- :-:=--- == +=.+::*+*+==  .+--+=+:-= +:.+.+:-= -=       
:-         -:            --=-                                   
                                                                
'


phpmyadmin_version=5.2.1
_runing "Cài đặt PhpMyadmin $phpmyadmin_version"
cd /usr/local/lsws/$Website_chinh/html
wget -P /usr/local/lsws/$Website_chinh/html  https://files.phpmyadmin.net/phpMyAdmin/$phpmyadmin_version/phpMyAdmin-$phpmyadmin_version-all-languages.zip --no-check-certificate >/dev/null 2>&1
unzip -q /usr/local/lsws/$Website_chinh/html/phpMyAdmin-$phpmyadmin_version-all-languages.zip
mv /usr/local/lsws/$Website_chinh/html/phpMyAdmin-$phpmyadmin_version-all-languages /usr/local/lsws/$Website_chinh/html/phpmyadmin

if [[ ! -d /usr/local/lsws/$Website_chinh/html/phpmyadmin ]];then
_runloi "Cài đặt PhpMyadmin $phpmyadmin_version"
. /etc/wptt/wptt-phpmyadmin-main 1
fi

rm -f /usr/local/lsws/$Website_chinh/html/phpMyAdmin-$phpmyadmin_version-all-languages.zip
cp -f /usr/local/lsws/$Website_chinh/html/phpmyadmin/config.sample.inc.php /usr/local/lsws/$Website_chinh/html/phpmyadmin/config.inc.php
mkdir -p /usr/local/lsws/phpmyadmin
secret=$(openssl rand -base64 32)
echo "\$cfg['TempDir'] = '/usr/local/lsws/phpmyadmin';" >> /usr/local/lsws/$Website_chinh/html/phpmyadmin/config.inc.php
echo "\$cfg['blowfish_secret'] = '$secret';" >> /usr/local/lsws/$Website_chinh/html/phpmyadmin/config.inc.php
chown -R nobody:nobody /usr/local/lsws/phpmyadmin
chown -R nobody:nobody /usr/local/lsws/$Website_chinh/html/phpmyadmin
chmod 555 /usr/local/lsws/phpmyadmin
NAME="${Website_chinh}php"
NAME2="${Website_chinh}"
  mkdir -p /usr/local/lsws/"$NAME2"/passwd
  Post_Install_Regenerate_Webadmin_Console_Passwd() {
    if [[ "$Server_Edition" = "OLS" ]]; then
      PHP_Command="admin_php"
    else
      PHP_Command="admin_php5"
    fi

    Webadmin_Pass=$(
      head /dev/urandom | tr -dc A-Za-z0-9 | head -c 36
      echo ''
    )
    id_ols_admin=$(
      date +%s | sha256sum | base64 | head -c 24
      echo
    )
    Encrypt_string=$(/usr/local/lsws/admin/fcgi-bin/admin_php -q /usr/local/lsws/admin/misc/htpasswd.php "${Webadmin_Pass}")
    echo "" >/usr/local/lsws/"$NAME2"/passwd/.phpmyadmin
    echo "$id_ols_admin:$Encrypt_string" >/usr/local/lsws/"$NAME2"/passwd/.phpmyadmin
  }
  Post_Install_Regenerate_Webadmin_Console_Passwd


  sed -i -e '/^realm '${Website_chinh}phpphpmyadmin'/,/^}$/d' /usr/local/lsws/conf/vhosts/"$Website_chinh"/"$Website_chinh".conf
  sed -i -e '/^context \/phpmyadmin\//,/^}$/d' /usr/local/lsws/conf/vhosts/"$Website_chinh"/"$Website_chinh".conf

echo 'realm '${NAME}phpmyadmin' {
  userDB  {
    location              /usr/local/lsws/'$NAME2'/passwd/.phpmyadmin
  }
}
context /phpmyadmin/ {
  location                phpmyadmin/
  allowBrowse             1
  realm                   '${NAME}phpmyadmin'

  accessControl  {
    allow                 ALL
  }

  rewrite  {

  }
  addDefaultCharset	  off

  phpIniOverride  {
php_value upload_max_filesize 10G
php_value max_file_uploads 10000
php_value post_max_size 10G
php_value max_execution_time 10000
php_admin_value open_basedir ""
  }
}' >>/usr/local/lsws/conf/vhosts/"$NAME2"/"$NAME2".conf

sed -i "/id_dang_nhap_phpmyadmin/d" /etc/wptt/.wptt.conf
sed -i "/password_dang_nhap_phpmyadmin/d" /etc/wptt/.wptt.conf

echo "id_dang_nhap_phpmyadmin=$id_ols_admin
password_dang_nhap_phpmyadmin=$Webadmin_Pass" >>/etc/wptt/.wptt.conf
  chown nobody:nobody /usr/local/lsws/"$NAME2"/passwd/.phpmyadmin
  chmod 400 /usr/local/lsws/"$NAME2"/passwd/.phpmyadmin
  /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "Cài đặt PhpMyadmin $phpmyadmin_version"

  echo "============================================================================="
  echo "Bạn hãy lưu trữ các thông tin này để sử dụng"
  echo "============================================================================="

if [[ -f "/etc/letsencrypt/live/$NAME2/cert.pem" || -f "/etc/letsencrypt/live/$NAME2-0001/cert.pem" || -d "/usr/local/lsws/$NAME2/ssl" ]]; then
  echo "============================================================================="
echo "Truy cap		: https://$Website_chinh/phpmyadmin"
else
  echo "============================================================================="
echo "Truy cap		: http://$Website_chinh/phpmyadmin"
fi

  echo "Id dang nhap		: $id_ols_admin"
  echo "PassWord dang nhap	: $Webadmin_Pass"
  echo "============================================================================="
  
  echo "Tài khoản đăng nhập database website: "
if [ "$(ls -A /etc/wptt/vhost)" ]; then
echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1
    if [[ -d "$path" ]]; then
         . /etc/wptt/vhost/.$domain.conf && echo "Website : $domain " && echo "Username: $DB_User_web" && echo "Password: $DB_Password_web" && echo "--------------------------------------------------" && echo ""
    fi
  done
fi
  echo "============================================================================="
  echo "Bạn có thể xem các tài khoản truy cập PhpMyAdmin tại menu wptangtoc ols => Quản lý PhpMyAdmin"
   echo "============================================================================="
   echo "Hoàn tất cài đặt PhpMyAdmin"
   echo "============================================================================="
   echo "Khuyến nghị: khi sử dụng xong PhpMyAdmin thì vui lòng xóa PhpMyAdmin để nâng cao bảo mật webserver"
   echo "khi nào cần thì hãy quay trở lại kích hoạt lại PhpMyAdmin"
   echo "============================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-phpmyadmin-main 1
fi
