#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly PhpMyAdmin => Thay doi tai khoan login PhpMyAdmin              |"
echo "========================================================================="
echo ""

. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color
if [[ $id_dang_nhap_phpmyadmin = "" ]];then
echoDo "Ban chua kich hoat PhpMyAdmin"
sleep 3
    . /etc/wptt/wptt-phpmyadmin-main
exit
fi


NAME="${Website_chinh}php"
NAME2="${Website_chinh}"
  mkdir -p /usr/local/lsws/"$NAME2"/passwd
  Post_Install_Regenerate_Webadmin_Console_Passwd() {

    Webadmin_Pass=$(
      head /dev/urandom | tr -dc A-Za-z0-9 | head -c 36
      echo ''
    )
    id_ols_admin=$(
      date +%s | sha256sum | base64 | head -c 24
      echo
    )
    Encrypt_string=$(/usr/local/lsws/admin/fcgi-bin/admin_php -q /usr/local/lsws/admin/misc/htpasswd.php "${Webadmin_Pass}")
    echo "" >/usr/local/lsws/"$NAME2"/passwd/.phpmyadmin
    echo "$id_ols_admin:$Encrypt_string" >/usr/local/lsws/"$NAME2"/passwd/.phpmyadmin
    echo "tai khoan username/password da cap nhat thanh cong!"
  }
  Post_Install_Regenerate_Webadmin_Console_Passwd
  
  sed -i '/id_dang_nhap_phpmyadmin/d' /etc/wptt/.wptt.conf
  sed -i '/password_dang_nhap_phpmyadmin/d' /etc/wptt/.wptt.conf
  echo "id_dang_nhap_phpmyadmin=$id_ols_admin
password_dang_nhap_phpmyadmin=$Webadmin_Pass" >>/etc/wptt/.wptt.conf
  chown nobody:nobody /usr/local/lsws/"$NAME2"/passwd/.phpmyadmin
  chmod 400 /usr/local/lsws/"$NAME2"/passwd/.phpmyadmin
  /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
  echoDone "============================================================================="
  echoDone "Da hoan tat thay doi tai khoan dang nhap PhpMyAdmin"
  echoDone "============================================================================="
  echo "============================================================================="
  echo "Ban hay luu tru thong tin nay lai de su dung"
  echo "============================================================================="
  echo "id dang nhap : $id_ols_admin"
  echo "password dang nhap : $Webadmin_Pass"
  echo "============================================================================="
  echo "Ban co the xem lai tai khoan: /etc/wptt/.wptt.conf"
  echo "Hoac xem lai tai khoan ben trong menu wptangtoc ols hoac lenh: wptt phpmyadmin-taikhoan"
  echo "============================================================================="


  check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-phpmyadmin-main 1
fi

