#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2024

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_phpmyadmin => $xoa PhpMyAdmin                                   |"
echo "========================================================================="
echo ""

. /etc/wptt/echo-color

if [[ $id_dang_nhap_phpmyadmin = "" ]];then
echoDo "$ban_chua_kich_hoat PhpMyAdmin"
sleep 3
    . /etc/wptt/wptt-phpmyadmin-main 1
exit
fi

_runing "$xoa PhpMyadmin"
rm -rf /usr/local/lsws/$Website_chinh/html/phpmyadmin
rm -f /usr/local/lsws/"$Website_chinh"/passwd/.phpmyadmin
sed -i "/id_dang_nhap_phpmyadmin/d" /etc/wptt/.wptt.conf
sed -i "/password_dang_nhap_phpmyadmin/d" /etc/wptt/.wptt.conf
#xoa bao mat 2 lop phpmyadmin
sed -i -e '/^realm '${Website_chinh}phpphpmyadmin'/,/^}$/d' /usr/local/lsws/conf/vhosts/"$Website_chinh"/"$Website_chinh".conf
sed -i -e '/^context \/phpmyadmin\//,/^}$/d' /usr/local/lsws/conf/vhosts/"$Website_chinh"/"$Website_chinh".conf
#sed -i '/realm '${Website_chinh}php'/,+21d' /usr/local/lsws/conf/vhosts/"$Website_chinh"/"$Website_chinh".conf
rm -rf /usr/local/lsws/phpmyadmin
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "$xoa PhpMyadmin"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-phpmyadmin-main 1
fi

