#!/bin/bash
echo "========================================================================="
echo "Quản lý Swap > Xóa Swap"
echo "========================================================================="
echo ""
uswap=$(free -m | awk '/Swap/ {print $2}')
uswap_dang_dung=$(free -m | awk '/Swap/ {print $3}')
uswap_con_trong=$(free -m | awk '/Swap/ {print $4}')
echo "Dung lượng swap hiện tại: ${uswap}MB"
echo "Dung lượng swap đang dùng: ${uswap_dang_dung}MB"
echo "Dung lượng swap đang còn thừa: ${uswap_con_trong}MB"
echo ""
echo ""
. /etc/wptt/echo-color
echo "Xác nhận xóa Swap? "
prompt="Nhập lựa chọn của bạn [1-2]: "
confirm="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			confirm="y"
			break
			;;

		2)
			confirm="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


if [[ ! -f "/var/swap.1" ]]; then
echoDo "Swap chưa kích hoạt không tồn tài..."
. /etc/wptt/wptt-swap-main 1
	fi
if [[ "$confirm" = 'y' ]]; then
    if [[ -f "/var/swap.1" ]]; then
		_runing "Xóa Swap"
        swapoff -a -v >/dev/null 2>&1
        rm -rf /var/swap.1 
        sed -i '/swap.1/d' /etc/fstab 
		_rundone "Xóa Swap"
    fi
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-swap-main 1
fi

