#!/bin/bash
echo "========================================================================="
echo "Quan ly Swap > Them Swap"
echo "========================================================================="
echo ""
uswap=$(free -m | awk '/Swap/ {print $3}')
echo "Dung luong swap hien tai $uswap"
echo ""
echo ""
read -p "Nhap so dung luong MB swap ban muon them (vi du: 1024): " swap


tong_ram_byte=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
rong_ram_mb=$(echo "scale=0;${tong_ram_byte}/1024" | bc)
if [[ "$rong_ram_mb" = "" ]]; then
  rong_ram_mb="2048"
fi
tong_ram_mb_db=$(echo "scale=0;${rong_ram_mb}/1.4" | bc)

gap3swap=$(expr $rong_ram_mb \* 2)
if (( "$gap3swap" < "$swap" ));then
echo "swap khong len gap hon 2 lan ram that se anh huong tieu cuc den hieu suat"
exit
fi

read -p "Xac nhan them $swap MB? (y/n): " confirm

if [[ "$confirm" = 'y' ]]; then
	
	swapoff -a -v
	rm -rf /var/swap.1
	echo "Dang tien hanh them $swap MB swap..."
	sleep 1
/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=$swap
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

sed -i '/swap.1/d' /etc/fstab
echo '/var/swap.1 none swap defaults 0 0' >> /etc/fstab
    clear
echo "Da them $swap MB swap thanh cong."
fi
