#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025

if [[ $1 = "" ]];then
. /etc/wptt/wptt-header-menu
header_menu
else
	. /etc/wptt/echo-color
echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh


# --- Định nghĩa Menu và Hành động ---
echo ""
echo ""
echo "$quan_ly_bang_thong:" #sử dụng echo đầu và căn lề biến để sử dụng fzf search all
echo ""
options=(
		"$bat/$tat phần mềm thông kê"
		"Thống Kê Theo Thời Gian Thực"   # Index 3
		"Thống Kê Theo 5 phút"                     # Index 0
		"Thống Kê Theo Giờ"                         # Index 1
		"Thống Kê Theo Giờ (Đồ họa)" # Index 2
		"Thống Kê Theo Ngày"   # Index 3
		"Thống Kê Theo Tháng"   # Index 3
		"Thống Kê Theo Năm"   # Index 3
)

# Hàm thực thi hành động dựa trên index
run_action() {
    local index=$1
    local script_path=""
    local script_args="98" # Tham số mặc định là 98 cho hầu hết các script này

    case $index in
        0) script_path="/etc/wptt/tai-nguyen-server/bang-thong/install-tool-bang-thong-do-luong" ;;
        1) script_path="/etc/wptt/tai-nguyen-server/bang-thong/xem-bang-thong-live-realtime" ;;
        2) script_path="/etc/wptt/tai-nguyen-server/bang-thong/xem-bang-thong-5-phut" ;;
        3) script_path="/etc/wptt/tai-nguyen-server/bang-thong/xem-bang-thong-gio" ;;
        4) script_path="/etc/wptt/tai-nguyen-server/bang-thong/xem-bang-thong-gio-do-hoa" ;;
        5) script_path="/etc/wptt/tai-nguyen-server/bang-thong/xem-bang-thong-ngay" ;;
        6) script_path="/etc/wptt/tai-nguyen-server/bang-thong/xem-bang-thong-thang" ;;
        7) script_path="/etc/wptt/tai-nguyen-server/bang-thong/xem-bang-thong-nam" ;;
        *) echo "${lua_chon_khong_hop_le:-Lựa chọn không hợp lệ}: Index $index."; return 1 ;;
    esac

    # Kiểm tra và chạy script con
    if [[ -x "$script_path" ]]; then
        "$script_path" "$script_args"
    else
        echo "Lỗi: Không tìm thấy hoặc không thể thực thi script '$script_path'."
    fi
    # Sau khi chạy xong, có thể thêm "Nhấn Enter để tiếp tục" nếu muốn
    # read -rp "Nhấn Enter để quay lại menu..."
}

. /etc/wptt/wptt-callback-menu-chon


