#!/bin/bash
function huong_dan(){
Tính năng truy cập vào ứng dụng: top

top trong Linux là một công cụ dòng lệnh cung cấp một cái nhìn động, cập nhật theo thời gian thực về các tiến trình [processes] đang chạy và tình hình sử dụng tài nguyên hệ thống của bạn. 

Nói một cách đơn giản, top giống như bảng điều khiển trung tâm hiển thị trực tiếp những gì đang diễn ra bên trong máy chủ hoặc máy tính Linux của bạn, đặc biệt là những tiến trình nào đang ngốn CPU và RAM nhiều nhất.

Mục Đích Chính
 * Theo dõi hệ thống thời gian thực: Xem ngay lập tức các tiến trình đang hoạt động và tài nguyên đang được sử dụng như thế nào.
 * Xác định tiến trình nặng gánh: Nhanh chóng tìm ra các ứng dụng hoặc dịch vụ đang chiếm dụng quá nhiều CPU hoặc bộ nhớ, có thể là nguyên nhân gây chậm hệ thống.
 * Gỡ lỗi hiệu suất: Giúp chẩn đoán các vấn đề về hiệu suất, tình trạng treo hoặc phản hồi chậm của hệ thống.
 * Quản lý tiến trình cơ bản: Cho phép bạn thực hiện một số hành động như kill [dừng] một tiến trình hoặc renice [thay đổi độ ưu tiên] một cách tương tác.
 * Hiểu về tải hệ thống: Cung cấp thông tin về mức độ bận rộn của CPU và bộ nhớ.

Hướng dẫn cách xem lệnh top: https://wptangtoc.com/kiem-tra-tai-nguyen-linux-top/
}

echo "========================================================================="
echo "|Quản lý tài nguyên => kiểm tra TOP	                                 |"
echo "========================================================================="
echo "Khi muốn thoát Ấn nút: q"
sleep 2
top
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-tai-nguyen-main 1
fi
