#!/bin/bash
if [[ -d /usr/local/lsws ]];then
echo '                          .                   
                        ...                   
                      .....     ..            
                    .......   :*+.            
                  ........ .=##-              
                ....... .-+%%+.               
              ........:+#%%*::=:              
            ...... .=*%%%#-.-====:            
          .......-+#%%%#*.:========:          
        .........#%%%%%*  :-=========:        
      ..........  =#%%%%*.  .-=========:      
     ..........    -####%#-   :==========     
       ..........   .+####%+ :=========-.     
         ..........   *#####*.=======-.       
           ........ .+#####+-:=====-.         
             ..... -####+=:-=====-.           
               . :*##*=-:-=====-.             
                =##+-:-======-.               
              -##=.-=======-.                 
            .++:   ======-.                   
            ..     ====-.                     
                   ==-.                       
                   =.                         
'
. /etc/wptt/echo-color
_runing "Ngừng hoạt động LiteSpeed"
/usr/local/lsws/bin/lswsctrl stop >/dev/null 2>&1
service lsws stop >/dev/null 2>&1
_rundone "Ngừng hoạt động LiteSpeed"

echo "-------------------------------------------------------------------------"
echo "Hoàn thành stop LiteSpeed Webserver"
echo "-------------------------------------------------------------------------"
echo "Tinh trang hoat dong LiteSpeed Webserver hien tai"
echo "LiteSpeed     : $(systemctl status lshttpd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-------------------------------------------------------------------------"
else
echo "Ban chua cai dat OpenLiteSpeed"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/service/wptt-stop-main 1
fi

