#!/bin/bash

sed -i -e '/^errorlog /,/^}$/d' /usr/local/lsws/conf/httpd_config.conf
echo '
errorlog logs/error.log {
  logLevel                WARN
  debugLevel              0
  rollingSize             10M
  enableStderrLog         0
}' >>/usr/local/lsws/conf/httpd_config.conf

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
echo "Hoàn tất tăng logLevel log từ error thành WARNing"
