#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Logs => Tat ghi logs Domain                                    |"
echo "========================================================================="

echo ""
echo ""
if [ "$(ls -A /etc/wptt/vhost)" ]; then
	echo "========================================================================="
	echo "Danh sach Domain da kich hoat ghi logs:"
	echo "========================================================================="
	for entry in $(ls -A /etc/wptt/vhost); do
		domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
		path="/usr/local/lsws/$domain/logs"
		i=1
		if [[ -d "$path" ]]; then
			checkauto="Da kich hoat"
		else
			checkauto="Chua kich hoat"
		fi
		echo "Website $domain $checkauto ghi logs"
	done
	echo "========================================================================="
	echo
fi

echo ""
echo ""
echo "lua chon website ban muon bat logs: "
echo ""
function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ -d /usr/local/lsws/$NAME/logs ]]; then
				selects+=("$NAME")
			fi
		done
		PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Khong co domain nao tren he thong cua ban duoc kich hoat logs."
		exit
	fi
}

lua_chon_NAME


path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
	clear
	echo "Domain khong ton tai tren VPS."
	echo
	. /etc/wptt/wptt-menu-logs
	exit
fi

if [[ ! -d /usr/local/lsws/$NAME/logs ]]; then
  echo "Ban chua kich ghi log cho website $NAME truoc do roi"
  exit
fi

read -p "Ban co muon huy kich hoat ghi logs cho website $NAME (y/n): " dongy
if [[ "$dongy" = "y" ]]; then
sed -i '/$VH_ROOT\/error.log/,+11d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
rm -rf /usr/local/lsws/"$NAME"/logs
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
. /etc/wptt/echo-color
echoDone "Da hoat tat ngung kich hoat ghi log cho website $NAME"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-menu-logs 1
fi

