#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_logs => $xoa logs ALL	                                      |"
echo "========================================================================="
echo ""
echo ""

if $(cat /etc/*release | grep -q "Ubuntu") ; then
tuong_thich_nhom_litespeed="nogroup"
else
tuong_thich_nhom_litespeed="nobody"
fi

if [ "$(ls -A /etc/wptt/vhost|sort -uV)" ]; then
    for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
        domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
        path="/usr/local/lsws/$domain/logs"
        i=1
        if [[ -d "$path" ]]; then
			if [[ -f $path/error.log ]];then
				echo "" > $path/error.log
				chown nobody:$tuong_thich_nhom_litespeed $path/error.log
			fi
			if [[ -f $path/access.log ]];then
				echo "" > $path/access.log
				chown nobody:$tuong_thich_nhom_litespeed $path/access.log
			fi
        echo "Hoàn tất xoá logs website $domain" 
        fi
    done
fi


if [[ -f /usr/local/lsws/logs/error.log ]];then
echo "" > /usr/local/lsws/logs/error.log
chown nobody:$tuong_thich_nhom_litespeed /usr/local/lsws/logs/error.log
fi

if [[ -f /usr/local/lsws/logs/access.log ]];then
echo "" > /usr/local/lsws/logs/access.log
chown nobody:$tuong_thich_nhom_litespeed /usr/local/lsws/logs/access.log
fi



chown root:$tuong_thich_nhom_litespeed /usr/local/lsws/logs
# đều phòng nếu mất thư mục logs của server sẽ tự động tái tạo lại
if [[ ! -d /usr/local/lsws/logs ]];then
	mkdir -p /usr/local/lsws/logs
	/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
chown root:$tuong_thich_nhom_litespeed /usr/local/lsws/logs
fi

echo "" > /var/log/wptangtoc-ols.log

echo "Xoá Log ALL: $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-logs-main 1
fi

