#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025

function huong_dan(){
tính năng tắt error.log website và tắt access.log website, thì mục đích của nó là cho phép bạn ngừng việc ghi lại các tệp nhật ký truy cập [access.log] và nhật ký lỗi [error.log] của máy chủ web OpenLiteSpeed cho một website cụ thể.

Giới thiệu ngắn gọn về tính năng này:

access.log [Nhật ký truy cập]:
 * Nội dung: Ghi lại mọi yêu cầu truy cập đến website của bạn [ai truy cập, truy cập cái gì, khi nào, từ đâu, trình duyệt nào, v.v.].

Lý do có thể muốn tắt:
 * Tiết kiệm dung lượng đĩa: Trên các website có lưu lượng truy cập cực lớn, tệp access.log có thể rất lớn.
 * Giảm tải I/O [nhỏ]: Ghi log liên tục có thể gây một chút tải lên ổ đĩa.
 * Tiết kiệm một chút chi phí cpu để phải ghi log.

error.log [Nhật ký lỗi máy chủ]:
 * Nội dung: Ghi lại các lỗi mà máy chủ web OpenLiteSpeed gặp phải khi xử lý yêu cầu cho website của bạn [ví dụ: lỗi PHP không được xử lý ở tầng ứng dụng, lỗi phân quyền, lỗi cấu hình vHost, v.v.].

Lý do có thể muốn tắt [CỰC KỲ KHÔNG KHUYẾN KHÍCH]:
 * Chủ yếu là để tiết kiệm dung lượng đĩa hoặc giảm I/O trong một số trường hợp rất đặc biệt.

 Tóm lại, mặc dù có thể có tính năng tắt error.log và access.log trong một số công cụ, đây là một hành động cần cân nhắc cực kỳ kỹ lưỡng vì những ảnh hưởng tiêu cực đến khả năng khắc phục sự cố và bảo mật website của bạn.

 Nhưng bạn cũng chả bao giờ xem log thì tắt là điều hợp lý: để để tiết kiệm ổ cứng và cpu
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_logs => $tat_ghi_error_access_log_domain                                    |"
echo "========================================================================="
. /etc/wptt/echo-color
echo ""
echo ""

NAME=$1
if [[ $NAME = "98" ]];then
	NAME=""
fi

if [[ $NAME = '' ]];then
	  if [ "$(ls -A /etc/wptt/vhost /etc/wptt/chuyen-huong 2>/dev/null | awk '!/:$/ && !/^\.\.?$/' | sed '/^$/d' | sort -uV)" ]; then
    echo "========================================================================="
    echo "$danh_sach_domain đã kích hoạt ghi logs:"
    echo "========================================================================="
    for entry in $(ls -A /etc/wptt/vhost /etc/wptt/chuyen-huong 2>/dev/null | awk '!/:$/ && !/^\.\.?$/' | sed '/^$/d' | sort -uV); do
      domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
      path="/usr/local/lsws/$domain/logs"
      i=1
      if [[ -d "$path" ]]; then
        checkauto="Đã kích hoạt"
      else
        checkauto="Chưa kích hoạt"
      fi

      if [[ -f /etc/wptt/chuyen-huong/$entry ]]; then
        echo "Website $domain (đang thiết lập chuyển hướng 301) $checkauto ghi logs"
      else
        echo "Website $domain $checkauto ghi logs"
      fi

    done
    echo "========================================================================="
    echo
  fi


	echo ""
	echo ""
	echo "$lua_chon_website_ban_muon $thiet_lap $tat_ghi_error_access_log_domain:"
	echo ""
	function lua_chon_NAME() {
		NAME=""
		    if [ "$(ls -A /etc/wptt/vhost /etc/wptt/chuyen-huong 2>/dev/null | awk '!/:$/ && !/^\.\.?$/' | sed '/^$/d' | sort -uV)" ]; then

			selects=()
			      for entry in $(ls -A /etc/wptt/vhost /etc/wptt/chuyen-huong 2>/dev/null | awk '!/:$/ && !/^\.\.?$/' | sed '/^$/d' | sort -uV); do

				NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
				if [[ -d /usr/local/lsws/$NAME/logs ]]; then
					selects+=("$NAME")
				fi
			done

			if [[ $selects = '' ]];then
				echo "Tất cả website chưa có website nào kích hoạt ghi logs"
				. /etc/wptt/wptt-logs-main 1
			fi


		#check tổng số website, nếu 2 website trở lên thì sẽ tự động có tính năng tất cả
		a=0
		for select in ${selects[@]};do
			a=$(expr $a + 1)
		done

		if [[ $a != 1 ]];then
			selects+=("Tất cả website")
		fi

		PS3="
$(tput setab 0)-//- $nhap_lua_chon_website_cua_ban [0=$exit_thoat]:$(tput sgr0) "
		select select in "${selects[@]}"; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echoDo "$ten_mien_nay_khong_ton_tai_tren_he_thong"
		exit
		fi
	}

	lua_chon_NAME
fi


if [[ $NAME = 'Tất cả website' ]];then
	    if [ "$(ls -A /etc/wptt/vhost /etc/wptt/chuyen-huong 2>/dev/null | awk '!/:$/ && !/^\.\.?$/' | sed '/^$/d' | sort -uV)" ]; then

		      for entry in $(ls -A /etc/wptt/vhost /etc/wptt/chuyen-huong 2>/dev/null | awk '!/:$/ && !/^\.\.?$/' | sed '/^$/d' | sort -uV); do

			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path_logs="/usr/local/lsws/$domain/logs"
			path="/usr/local/lsws/$domain/html"
			i=1
			if [[ -d "$path" ]]; then
				if [[ -d $path_logs ]];then
					_runing "Tắt ghi Logs website $domain"
					. /etc/wptt/logs/wptt-tat-logs-domain $domain >/dev/null 2>&1
					_rundone "Tắt ghi Logs website $domain"
				fi
			fi
		done
	fi

	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-logs-main 1
	fi
	exit
fi



path="/etc/wptt/vhost/.$NAME.conf"


if [[ $NAME = '' || $NAME = '0' ]];then
	. /etc/wptt/wptt-logs-main 1
	exit
fi

if [[ ! -d /usr/local/lsws/$NAME/logs ]]; then
	echo "Bạn chưa kích hoạt ghi log cho website $NAME trước đó rồi"
	. /etc/wptt/wptt-logs-main 1
	exit
fi

echo "Tắt log website $NAME: $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

_runing "$tat_ghi_error_access_log_domain $NAME"
sed -i -e '/^errorlog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -i -e '/^accesslog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf

if [[ $NAME ]];then #kiểm tra nó phải có giá trị thì mới được xoá log tránh xoá nhầm log server
rm -rf /usr/local/lsws/"$NAME"/logs
fi

# đều phòng nếu mất thư mục logs của server sẽ tự động tái tạo lại
if [[ ! -d /usr/local/lsws/logs ]];then
	if $(cat /etc/*release | grep -q "Ubuntu") ; then
		tuong_thich_nhom_litespeed="nogroup"
	else
		tuong_thich_nhom_litespeed="nobody"
	fi
	mkdir -p /usr/local/lsws/logs
	chown root:nodoby /usr/local/lsws/logs
	/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi


if [[ -f /etc/wptt/vhost/.$NAME.conf ]]; then
  sed -i '/bat_log_domain/d' /etc/wptt/vhost/.$NAME.conf
fi

if [[ -f /etc/wptt/vhost_bk/.$NAME.conf ]]; then # đường dẫn backup khi chuyển hướng domain
  sed -i '/bat_log_domain/d' /etc/wptt/vhost_bk/.$NAME.conf
fi


/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "$tat_ghi_error_access_log_domain $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-logs-main 1
fi
