#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025

function huong_dan(){
Tính năng Tắt ghi log database cho phép người dùng cấu hình hệ quản trị cơ sở dữ liệu [MariaDB] để ngừng việc ghi lại các hoạt động, truy vấn, hoặc lỗi vào các tệp nhật ký [log files].

Các loại log database phổ biến bao gồm:
 * General Query Log: Ghi lại mọi truy vấn được gửi đến database.
 * Slow Query Log: Ghi lại các truy vấn chạy chậm hơn một ngưỡng thời gian nhất định.
 * Error Log: Ghi lại các lỗi khi khởi động, chạy, hoặc dừng database.
 * Binary Log [Binlog]: Ghi lại mọi thay đổi đối với dữ liệu [quan trọng cho sao lưu và nhân bản].

Mục đích chính của việc tắt ghi log database là:
 * Cải thiện hiệu suất [Performance]: 🚀 Việc ghi log, đặc biệt là General Query Log và Binary Log trên các hệ thống có lượng truy cập lớn, tiêu tốn tài nguyên I/O và CPU. Tắt chúng có thể giúp database chạy nhanh hơn.
 * Tiết kiệm dung lượng ổ cứng: 💾 Các tệp log, nhất là General Log và Binlog, có thể phát triển rất lớn. Tắt chúng giúp tiết kiệm không gian lưu trữ.

 Tóm lại, Tắt ghi log database là một công cụ giúp tối ưu hiệu suất và dung lượng, nhưng nó đánh đổi bằng khả năng gỡ lỗi, phục hồi và kiểm toán. Hãy hiểu rõ hậu quả trước khi sử dụng.
}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Logs => Hủy kích hoạt ghi logs database                        |"
echo "========================================================================="
echo ""
echo ""

check=$(cat /etc/my.cnf.d/server.cnf | grep -c "skip-log-bin")
if [[ "$check" = "1" ]];then
echo "Ban chua kich hoat tinh nang ghi logs database"
sleep 3
. /etc/wptt/wptt-logs-main
exit
fi

echo "Xác nhận tắt tính năng ghi logs database"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


if [[ "$dongy" = "y" ]];then
sed -i '/log-bin/d' /etc/my.cnf.d/server.cnf
sed -i '/\[mysqld\]/a skip-log-bin' /etc/my.cnf.d/server.cnf
sed -i '/slow-query-log/d' /etc/my.cnf.d/server.cnf
sed -i '/slow-query-log-file/d' /etc/my.cnf.d/server.cnf
sed -i '/long_query_time/d' /etc/my.cnf.d/server.cnf
sed -i '/general-log/d' /etc/my.cnf.d/server.cnf
sed -i '/mysql-error.log/d' /etc/my.cnf.d/server.cnf

systemctl restart mariadb.service
echo "========================================================================="
echo "Hoàn tất hủy kích hoạt ghi database"
echo "========================================================================="
else
. /etc/wptt/wptt-logs-main 1
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-logs-main 1
fi

