#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2023
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Logs => Bật ghi logs Domain                                    |"
echo "========================================================================="
. /etc/wptt/echo-color
echo ""
echo ""

NAME=$1
if [[ $NAME = "98" ]];then
	NAME=""
fi

if [[ $NAME = '' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		echo "========================================================================="
		echo "Danh sách Domain đã kích hoạt ghi logs:"
		echo "========================================================================="
		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path="/usr/local/lsws/$domain/logs"
			i=1
			if [[ -d "$path" ]]; then
				checkauto="Đã kích hoạt"
			else
				checkauto="Chưa kích hoạt"
			fi
			echo "Website $domain $checkauto ghi logs"
		done
		echo "========================================================================="
		echo
	fi

	echo ""
	echo ""
	echo "Lựa chọn website bạn muốn bật ghi logs: "
	echo ""
	function lua_chon_NAME() {
		NAME=""
		if [ "$(ls -At /etc/wptt/vhost)" ]; then
			selects=()
			for entry in $(ls -A /etc/wptt/vhost); do
				NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
				if [[ ! -d /usr/local/lsws/$NAME/logs ]]; then
					selects+=("$NAME")
				fi
			done

			if [[ $selects = '' ]];then
				echo "Tất cả website đã được kích hoạt ghi logs hết rồi"
				. /etc/wptt/wptt-menu-logs 1
			fi


		#check tổng số website, nếu 2 website trở lên thì sẽ tự động có tính năng tất cả
		a=0
		for select in ${selects[@]};do
			a=$(expr $a + 1)
		done

		if [[ $a != 1 ]];then
			selects+=("Tất cả website")
		fi

		PS3="
-//- Nhập lựa chọn website của bạn [0=Thoát]: "
		select select in "${selects[@]}"; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Khong co domain tren he thong cua ban."
		exit
		fi
	}

	lua_chon_NAME
fi


if [[ $NAME = 'Tất cả website' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path_html="/usr/local/lsws/$domain/html/logs"
			path="/usr/local/lsws/$domain/html"
			i=1
			if [[ -d "$path" ]]; then
				if [[ ! -d $path_html ]];then
					_runing "Bật Logs website $domain"
					. /etc/wptt/logs/wptt-bat-logs-domain $domain >/dev/null 2>&1
					_rundone "Bật Logs website $domain"
				fi
			fi
		done
	fi

	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-menu-logs 1
	fi
	exit
fi



path="/etc/wptt/vhost/.$NAME.conf"


if [[ $NAME = '' || $NAME = '0' ]];then
	. /etc/wptt/wptt-menu-logs 1
	exit
fi


if [[ $(cat /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf| grep 'errorlog') ]]; then
	echo "Bạn đã bật ghi log cho website $NAME trước đó rồi"
	exit
fi

_runing "Bật logs cho website $NAME"
sed -i -e '/^errorlog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -i -e '/^accesslog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
echo '
errorlog $VH_ROOT/logs/error.log {
useServer               1
logLevel                ERROR
rollingSize             10M
}

accesslog $VH_ROOT/logs/access.log {
useServer               0
rollingSize             10M
keepDays                30
compressArchive         1
}' >>/usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf

mkdir -p /usr/local/lsws/"$NAME"/logs
chown -R nobody:nobody /usr/local/lsws/"$NAME"/logs
chmod 700 /usr/local/lsws/"$NAME"/logs
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

_rundone "Bật logs cho website $NAME"

echo "Đường dẫn lưu trữ logs: /usr/local/lsws/$NAME/logs"
echo 'bat_log_domain=1' >> /etc/wptt/.$NAME.conf

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-menu-logs 1
fi

