#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025


function huong_dan(){
việc xem error log cho server litespeed thông qua wptangtoc ols thường sẽ tận dụng các công cụ sẵn có của hệ điều hành Linux.

Tính năng xem error log server trong wptangtoc ols có thể được hiểu ngắn gọn như sau:

Xác định vị trí file log: OpenLiteSpeed thường lưu error log server trong một file riêng biệt. Đường dẫn phổ biến có thể là /usr/local/lsws/logs/error.log Script wptangtoc ols có thể cung cấp một lệnh hoặc tùy chọn để nhanh chóng xác định hoặc truy cập vào file log này.

Tính năng này hỗ trợ người dùng dễ dàng hơn trong việc tìm và sử dụng các công cụ có sẵn của hệ thống để xem error log của OpenLiteSpeed cho hệ thống. Điều này giúp quản trị viên nhanh chóng kiểm tra, phát hiện lỗi, phục vụ công việc gỡ lỗi hoặc các hoạt động bất thường liên quan đến webserver.
}


. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
. /etc/wptt/echo-color

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_logs => $xem_error_log_server                                |"
echo "========================================================================="
echo ""
echo ""

if [[ ! -f /usr/local/lsws/logs/error.log ]];then
echo "ERROR server log không tồn tại"
echo "mặc định error log server phải được kích hoạt không thể tắt."
echo "Nếu bị mất file error.log server thì hệ thống systemctl lsws litespeed webserver sẽ ngừng hoạt động"
	echo -e "Bạn có muốn tái tạo lại error log server để litespeed có thể sử dụng bình thường ${NAME} ?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done

	if [[ "$dongy" = 'y' ]]; then
		_runing "Khởi tạo lại error log server"

		if $(cat /etc/*release | grep -q "Ubuntu") ; then
			tuong_thich_nhom_litespeed="nogroup"
		else
			tuong_thich_nhom_litespeed="nobody"
		fi


		mkdir -p /usr/local/lsws/logs
		chown root:$tuong_thich_nhom_litespeed /usr/local/lsws/logs

		rm -f /usr/local/lsws/logs/error.log >/dev/null 2>&1
		touch /usr/local/lsws/logs/error.log
		chown nodoby:$tuong_thich_nhom_litespeed /usr/local/lsws/logs/error.log
		/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

		_rundone "Khởi tạo lại error log server"
	fi
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-logs-main 1
	fi
	return 2>/dev/null;exit;
fi

echo "Ấn phím Q hoặc ctrl + C để thoát -- ấn enter xuống dòng đọc tiếp"
echo ""
echo "đường dẫn file lưu trữ access log: /usr/local/lsws/logs/error.log"
sleep 4
more /usr/local/lsws/logs/error.log | sort

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-logs-main 1
fi


