#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	echo "========================================================================="
	echo "|Quản lý Logs => Xem monitor system                                     |"
	echo "========================================================================="
else
	echo "========================================================================="
	echo "|Quản lý tài nguyên => Xem monitor system                               |"
	echo "========================================================================="
fi

echo ""
echo ""
check=$(which gotop)
if [[ $check = '' ]];then
	cd
	wget https://github.com/xxxserxxx/gotop/releases/download/v4.2.0/gotop_v4.2.0_linux_386.rpm
	rpm -ivh gotop_v4.2.0_linux_386.rpm
	rm -f gotop_v4.2.0_linux_386.rpm
	clear
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		echo "========================================================================="
		echo "|Quản lý Logs => Xem monitor system                                     |"
		echo "========================================================================="
	else
		echo "========================================================================="
		echo "|Quản lý tài nguyên => Xem monitor system                               |"
		echo "========================================================================="
	fi
fi
echo "Ấn phím Q hoặc ctrl + C để thoát"
sleep 4
gotop


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-logs-main 1
fi

if [[ $check_menu_wptangtoc_active = "99" ]];then
	. /etc/wptt/wptt-tai-nguyen-main 1
fi

