#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2023
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_logs => $tat_ghi_error_access_log_domain                                    |"
echo "========================================================================="
. /etc/wptt/echo-color
echo ""
echo ""

NAME=$1
if [[ $NAME = "98" ]];then
	NAME=""
fi

if [[ $NAME = '' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		echo "========================================================================="
		echo "Danh sách Domain đã kích hoạt ghi logs:"
		echo "========================================================================="
		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path="/usr/local/lsws/$domain/logs"
			i=1
			if [[ -d "$path" ]]; then
				checkauto="Đã kích hoạt"
			else
				checkauto="Chưa kích hoạt"
			fi
			echo "Website $domain $checkauto ghi logs"
		done
		echo "========================================================================="
		echo
	fi

	echo ""
	echo ""
	echo "$lua_chon_website_ban_muon $thiet_lap $tat_ghi_error_access_log_domain:"
	echo ""
	function lua_chon_NAME() {
		NAME=""
		if [ "$(ls -At /etc/wptt/vhost)" ]; then
			selects=()
			for entry in $(ls -A /etc/wptt/vhost); do
				NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
				if [[ -d /usr/local/lsws/$NAME/logs ]]; then
					selects+=("$NAME")
				fi
			done

			if [[ $selects = '' ]];then
				echo "Tất cả website chưa có website nào kích hoạt ghi logs"
				. /etc/wptt/wptt-menu-logs 1
			fi


		#check tổng số website, nếu 2 website trở lên thì sẽ tự động có tính năng tất cả
		a=0
		for select in ${selects[@]};do
			a=$(expr $a + 1)
		done

		if [[ $a != 1 ]];then
			selects+=("Tất cả website")
		fi

		PS3="
-//- $nhap_lua_chon_website_cua_ban [0=$exit_thoat]: "
		select select in "${selects[@]}"; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echoDo "$ten_mien_nay_khong_ton_tai_tren_he_thong"
		exit
		fi
	}

	lua_chon_NAME
fi


if [[ $NAME = 'Tất cả website' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path_logs="/usr/local/lsws/$domain/logs"
			path="/usr/local/lsws/$domain/html"
			i=1
			if [[ -d "$path" ]]; then
				if [[ -d $path_logs ]];then
					_runing "Tắt ghi Logs website $domain"
					. /etc/wptt/logs/wptt-tat-logs-domain $domain >/dev/null 2>&1
					_rundone "Tắt ghi Logs website $domain"
				fi
			fi
		done
	fi

	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-menu-logs 1
	fi
	exit
fi



path="/etc/wptt/vhost/.$NAME.conf"


if [[ $NAME = '' || $NAME = '0' ]];then
	. /etc/wptt/wptt-menu-logs 1
	exit
fi

if [[ ! -d /usr/local/lsws/$NAME/logs ]]; then
	echo "Bạn chưa kích hoạt ghi log cho website $NAME trước đó rồi"
	. /etc/wptt/wptt-menu-logs 1
	exit
fi

_runing "$tat_ghi_error_access_log_domain $NAME"
sed -i -e '/^errorlog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
sed -i -e '/^accesslog /,/^}$/d' /usr/local/lsws/conf/vhosts/"$NAME"/"$NAME".conf
rm -rf /usr/local/lsws/"$NAME"/logs

# đều phòng nếu mất thư mục logs của server sẽ tự động tái tạo lại
if [[ ! -d /usr/local/lsws/logs ]];then
	mkdir -p /usr/local/lsws/logs
	chown root:nodoby /usr/local/lsws/logs
fi


sed -i '/bat_log_domain/d' /etc/wptt/vhost/.$NAME.conf

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "$tat_ghi_error_access_log_domain $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-menu-logs 1
fi

