#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Logs => Xem log database truy van cham                         |"
echo "========================================================================="
echo ""
echo ""

if [[ ! -f /var/lib/mysql/mysql-slow.log ]]; then
echo "Ban chua kich hoat ghi logs database"
sleep 3
. /etc/wptt/wptt-menu-logs
exit
fi

echo "An phim Q hoac ctrl + c de thoat -- an nut enter de xuong dong doc tiep"
sleep 4
more /var/lib/mysql/mysql-slow.log | sort
. /etc/wptt/wptt-menu-logs
