#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Logs => Xem monitor system                                     |"
echo "========================================================================="
echo ""
echo ""
echo "Ấn phím Q hoặc ctrl + C để thoát"
sleep 4

check=$(which gotop)

if [[ $check = '' ]];then
https://github.com/xxxserxxx/gotop/releases/download/v4.2.0/gotop_v4.2.0_linux_386.rpm
rpm -ivh gotop_v4.2.0_linux_386.rpm
rm -f gotop_v4.2.0_linux_386.rpm
fi
gotop
. /etc/wptt/wptt-menu-logs 1

