#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Logs => Xem access log domain truy van                         |"
echo "========================================================================="
echo ""
echo ""
echo "lua chon website ban muon xem access logs co truy van: "
echo ""
function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ -d /usr/local/lsws/$NAME/logs ]]; then
				selects+=("$NAME")
			fi
		done
		PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Khong co domain tren he thong cua ban duoc kich hoat ghi logs."
		exit
	fi
}

lua_chon_NAME


path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    . /etc/wptt/wptt-menu-logs
    exit
fi

if [[ ! -d /usr/local/lsws/$NAME/logs ]]; then
    echo "Ban chua kich hoat log, tinh nang nay minh tat mac dinh de dam bao hieu suat toc do"
    echo "Neu ban co nhu cau xem log thi hay tu bat len trong phan menu cua WP Tang Toc OLS"
    exit
fi


if [[ ! -f /usr/local/lsws/"$NAME"/logs/access.log ]]; then
echo "file access.log cua website $NAME khong ton tai "
exit
fi
read -p "Nhap truy van ban muon tim kiem" truyvan

echo "duong dan luu tru logs: /usr/local/lsws/$NAME/logs"
cat /usr/local/lsws/"$NAME"/logs/access.log | grep "$truyvan"
