#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025

function huong_dan(){
việc xem error log cho một domain cụ thể thông qua wptangtoc ols thường sẽ tận dụng các công cụ sẵn có của hệ điều hành Linux.

Tính năng xem access log domain trong wptangtoc ols có thể được hiểu ngắn gọn như sau:

Xác định vị trí file log: OpenLiteSpeed thường lưu error log cho mỗi virtual host [tương ứng với mỗi domain] trong một file riêng biệt. Đường dẫn phổ biến có thể là /usr/local/lsws/domain.com/logs/error.log Script wptangtoc ols có thể cung cấp một lệnh hoặc tùy chọn để nhanh chóng xác định hoặc truy cập vào file log này.

Tính năng này hỗ trợ người dùng dễ dàng hơn trong việc tìm và sử dụng các công cụ có sẵn của hệ thống để xem error log của OpenLiteSpeed cho từng domain. Điều này giúp quản trị viên nhanh chóng kiểm tra, phát hiện lỗi, phục vụ công việc gỡ lỗi hoặc các hoạt động bất thường liên quan đến một website cụ thể.
}


. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_logs => Xem error log domain                                   |"
echo "========================================================================="
echo ""
echo ""
echo "$lua_chon_website_ban_muon xem error logs: "
echo ""
echo ""
function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ -d /usr/local/lsws/$NAME/logs ]]; then
				selects+=("$NAME")
			fi
		done
		PS3="
-//- $nhap_lua_chon_website_cua_ban [0=Thoat]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Khong co domain tren he thong cua ban duoc kich hoat ghi logs."
		exit
	fi
}

lua_chon_NAME

path="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$path" || "$NAME" = "0" ]]; then
    clear
    echo "Domain khong ton tai tren VPS."
    echo
    . /etc/wptt/wptt-logs-main
    exit
fi

if [[ ! -d /usr/local/lsws/$NAME/logs ]]; then
	echo "Ban chua kich hoat log, tinh nang nay minh tat mac dinh de dam bao hieu suat toc do"
	echo "Neu ban co nhu cau xem log thi hay tu bat len trong phan menu cua WP Tang Toc OLS"
	. /etc/wptt/wptt-logs-main 1
fi

if [[ ! -f /usr/local/lsws/"$NAME"/logs/error.log ]]; then
echo "file error.log cua website $NAME khong ton tai "
	. /etc/wptt/wptt-logs-main 1
fi

echo "Ấn phím Q hoặc ctrl + C để thoát -- ấn enter xuống dòng đọc tiếp"
sleep 4
echo "duong dan luu tru logs: /usr/local/lsws/$NAME/logs"
more /usr/local/lsws/"$NAME"/logs/error.log

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-logs-main 1
fi

