#!/bin/bash
. /etc/wptt/echo-color
read -p "Nhập địa chỉ IP server mới: " IP
if ! [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
echoDo "Bạn nhập không đúng định dạng IPv4"
exit
fi


read -p "Nhập Port SSH Server mới: " Port
# check điều kiện số tự nhiên port
if [[ ! $Port =~ ^-?[0-9]+$ ]]; then
    clear
    echoDo "Port không đúng định dạng, vui lòng nhập port là số tự nhiên"
    exit
fi

. /etc/wptt/.wptt.conf

if [ "$(ls -A /etc/wptt/vhost)" ]; then
	rm -f /tmp/domain-rsync-move
	for entry in $(ls -A /etc/wptt/vhost); do
		domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
		path="/usr/local/lsws/$domain/html"
		i=1
		if [[ -d "$path" ]]; then
			echo "/usr/local/lsws/$domain" >> /tmp/domain-rsync-move
		fi
	done
fi



list_ssl_domain_all=$(cat /tmp/domain-rsync-move | sort -u |uniq |sed '/^$/d' | sed 's/ $//g' | tr -s '\n' ' ')
if [[ $(which rsync) = '' ]];then
	yum install rsync -y
fi


#cho ip vào danh sách trắng csf khi dùng csf
check_csf=$(which csf)
if [[ $check_csf ]];then
	csf -a $IP >/dev/null 2>&1
fi

echo "Lệnh: rsync -avzh -e 'ssh -p $Port -o StrictHostKeyChecking=no' $list_ssl_domain_all root@$IP:/usr/local/lsws"
rsync -avzh -e "ssh -p $Port -o StrictHostKeyChecking=no" $list_ssl_domain_all root@$IP:/usr/local/lsws
echo "Hoàn tất move mã nguồn qua ip $IP"
