#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025

function huong_dan() {
  Tính năng này chuyển website ngoài [Cpanel,plesk,Cyperpanel, AApanel, Larpvs,HocVPs,VPSSim... hệ thống cũ có terminal là được] chuyển về wptangtoc ols

  Tính năng Quản lý Chuyển Website [Website Migration] trong WPTangToc OLS là một tập hợp các công cụ và quy trình được thiết kế để giúp bạn di chuyển website [đặc biệt là WordPress] từ một nơi này sang nơi khác một cách dễ dàng và ít lỗi hơn. 🚚💨

  Giới thiệu ngắn gọn:
  Mục đích: Đơn giản hóa quá trình chuyển website giữa các máy chủ, từ nhà cung cấp này sang nhà cung cấp khác, hoặc từ môi trường phát triển [staging] lên máy chủ chính [production] và ngược lại.

  Lợi ích:
  * Giảm thiểu lỗi thủ công: Tự động hóa nhiều bước phức tạp trong quá trình di chuyển.
  * Tiết kiệm thời gian: Tăng tốc độ di chuyển website so với việc làm thủ công hoàn toàn.
  * Đảm bảo tính toàn vẹn: Giúp di chuyển đầy đủ cả tệp tin và cơ sở dữ liệu một cách nhất quán.
  * Thuận tiện: Cung cấp một quy trình tích hợp ngay trong công cụ quản lý máy chủ quen thuộc.
  Tính năng này giúp quá trình chuyển nhà cho website của bạn trở nên mượt mà và ít căng thẳng hơn, đảm bảo website hoạt động ổn định trên môi trường mới.

}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Chuyển website về WPTangToc OLS						                  |"
echo "========================================================================="
. /etc/wptt/.wptt.conf
NAME=$1
all_for=$2

if [[ $NAME = "98" ]]; then
  NAME=""
fi

if [[ $NAME = "" ]]; then
  . /etc/wptt/tenmien
  echo ""
  echo ""
  echo "Lựa chọn website bạn muốn chuyển về: "
  echo ""
  lua_chon_NAME
fi

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
  return 2>/dev/null
  exit
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
  clear
  echoDo "Tên miền không tồn tại trên hệ thống này"
  sleep 3
  return 2>/dev/null
  exit
  exit
fi

checkdns=$(host $NAME | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
if [[ "$checkdns" = "" ]]; then
  checkdns=$(nslookup $NAME | grep Address | cut -f5 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
fi

ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')

if [[ "$checkdns" = "$ip" ]]; then
  echo "Bạn đã trỏ DNS về webserver này rồi"
  return 2>/dev/null
  exit
fi

if [[ "$checkdns" = "" ]]; then
  echo "website $NAME hiện tại không tồn tại trên hệ thống internet"
  return 2>/dev/null
  exit
fi

if [[ $all_for = "" ]]; then
  echo "Yêu cầu webserver cũ của bạn phải có hỗ trợ terminal"
  echo "Tính năng này chỉ hỗ trợ mã nguồn website WordPress"
  echo "Hướng dẫn: "
  echo "Bước 1: hãy cd đi vào thư mục mã nguồn website của bạn muốn chuyển rồi"
  echo "Bước 2: Dán paste đoạn lệnh này vào terminal webserver cũ của bạn: "
  echo "lệnh: curl -sO https://wptangtoc.com/share/wptt && bash wptt"
  echo ""
  echo "Bên webserver cũ thực thi chạy xong thì hãy quay lại về xác nhận làm bước tiếp theo"
  echo "Xác nhận đã hoàn tất chạy lệnh trên hoàn tất sao lưu dữ liệu webserver cũ và tiếp tục bước tiếp theo:"
  prompt="Nhập lựa chọn của bạn [1-2]: "
  dongy="n"
  options=("Đồng ý, tiếp tục" "Không đồng ý, quay trở về")
  PS3="$prompt"
  select opt in "${options[@]}"; do
    case "$REPLY" in
    1)
      dongy="y"
      break
      ;;

    2)
      dongy="n"
      break
      ;;

    $((${#options[@]} + 1)))
      printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
      break
      ;;
    *)
      printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
      break
      ;;
    esac
  done

fi

if [[ "$dongy" = "y" || "$all_for" = "1" ]]; then
  rm -f /usr/local/backup-website/$NAME/giatuan-wptangtoc.zip
  rm -f /usr/local/backup-website/$NAME/giatuan-wptangtoc.sql
  wget -P /usr/local/backup-website/$NAME http://$NAME/giatuan-wptangtoc.sql --no-check-certificate
  wget -P /usr/local/backup-website/$NAME http://$NAME/giatuan-wptangtoc.zip --no-check-certificate
else
  return 2>/dev/null
  exit
fi

if [[ -f /usr/local/backup-website/$NAME/giatuan-wptangtoc.zip ]]; then
  duong_dan_thu_muc="/usr/local/backup-website/$NAME/giatuan-wptangtoc.zip"
else
  echo "Chưa download được file mã nguồn"
  echo "Chuyển website không thành công"
  return 2>/dev/null
  exit
fi

if [[ -f /usr/local/backup-website/$NAME/giatuan-wptangtoc.sql ]]; then
  duong_dan_thu_muc_sql="/usr/local/backup-website/$NAME/giatuan-wptangtoc.sql"
else
  echo "Chưa download được file sql"
  echo "Chuyển website không thành công"
  return 2>/dev/null
  exit
fi

. /etc/wptt/vhost/.$NAME.conf

echo "Đang tiến hành nhập dữ liệu database website $NAME ..."
mariadb -u "$database_admin_username" -p"$database_admin_password" -e "DROP DATABASE IF EXISTS ${DB_Name_web}"
mariadb -u "$database_admin_username" -p"$database_admin_password" -e "CREATE DATABASE IF NOT EXISTS ${DB_Name_web}"
mariadb -u "$database_admin_username" -p"$database_admin_password" -e "DROP USER IF EXISTS '${DB_User_web}'@'localhost'"
mariadb -u "$database_admin_username" -p"$database_admin_password" -e "CREATE USER IF NOT EXISTS '${DB_User_web}'@'localhost' IDENTIFIED BY '${DB_Password_web}'"
mariadb -u "$database_admin_username" -p"$database_admin_password" -e "GRANT ALL PRIVILEGES ON ${DB_Name_web}.* TO '${DB_User_web}'@'localhost' WITH GRANT OPTION"
mariadb -u "$database_admin_username" -p"$database_admin_password" -e "FLUSH PRIVILEGES"
clear
mariadb -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web" --force <$duong_dan_thu_muc_sql
echo "Nhập dữ liệu database thành công"
rm -rf /usr/local/lsws/"$NAME"/html/*

if [[ "$all_for" = "" ]]; then
  echo "Đang tiến hành giải nén mã nguồn của website $NAME: "
  unzip -n "$duong_dan_thu_muc" -d /usr/local/lsws/"$NAME"/html/ -x "wptt"
else
  echo "Đang tiến hành giải nén mã nguồn của website $NAME: "
  unzip -n "$duong_dan_thu_muc" -d /usr/local/lsws/"$NAME"/html/
fi

rm -rf /usr/local/lsws/"$NAME"/luucache/*

#xoá file index.html
if [[ -f /usr/local/lsws/$NAME/html/index.html ]]; then
  rm -f /usr/local/lsws/$NAME/html/index.html
fi

chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"$NAME"/html
find /usr/local/lsws/"$NAME"/html -type d -exec chmod 755 {} \;
find /usr/local/lsws/"$NAME"/html -type f -exec chmod 644 {} \;

if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
  sed -i "/DB_HOST/s/'[^']*'/'localhost'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
  sed -i "/DB_NAME/s/'[^']*'/'$DB_Name_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
  sed -i "/DB_USER/s/'[^']*'/'$DB_User_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
  sed -i "/DB_PASSWORD/s/'[^']*'/'$DB_Password_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
  wp rewrite flush --allow-root --path=/usr/local/lsws/"$NAME"/html >/dev/null 2>&1
else
  echo "Không xác định được file wp-config.php"
  echo "Có vẻ như đậy không phải mã nguồn website WordPress"
fi
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

rm -f /usr/local/backup-website/$NAME/giatuan-wptangtoc.zip
rm -f /usr/local/backup-website/$NAME/giatuan-wptangtoc.sql

#ho tro check wordpress multisite
if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
  check_mulsite_dang_su_dung=$(cat /usr/local/lsws/$NAME/html/wp-config.php | grep MULTISITE)
  if [[ $check_mulsite_dang_su_dung ]]; then
    . /etc/wptt/wordpress/wordpress-multisite $NAME 1
  fi
fi

RED='\033[0;31m'
NC='\033[0m'
echo -e "${RED}
     .:..........................             
      .::::::::::::::::::::::::::::..         
        ..:::::::::::::::::::::::::::::.      
                             ...:::::::::.    
                                  .:::::::.   
          .:::::::.         .       .:::::::  
         .::::::::::::::::::::..      ::::::: 
         ::::::::::::::::::::::::.     ::::::.
        .::::::::::::::::::::::::::.   .:::::.
        .::::::::::::::::::::::::::::  .:::::.
        .::::::::::::::::::::::::::.   .:::::.
         ::::::::::::::::::::::::.     ::::::.
.::::::  .:::::::::::::::::::::.      ::::::. 
          .:::::::.                 .:::::::  
       ::::::::::::.              .:::::::.   
       ......:::::::::...    ...:::::::::.    
               .:::::::::::::::::::::::.      
   ..............::::::::::::::::::..         
  .:::::::::::::................. ${NC}"

echo "==================================================================="
echo "        Chuyển website $NAME về hệ thống thành công                "
echo "==================================================================="

if [[ "$all_for" = "" ]]; then
  checkdns=$(host $NAME | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
  if [[ "$checkdns" = "" ]]; then
    checkdns=$(nslookup $NAME | grep Address | cut -f5 | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
  fi

  ip=$(curl -skf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' || curl -skf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com | grep -E -o '(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)')

  if [[ "$checkdns" != "$ip" ]]; then
    if [[ "$checkdns" = "" ]]; then
      echo "Ten mien $NAME chua duoc tro IP gia tri IP cua $NAME la khong co gia tri nao, ban vui long tro IP ve $ip de tan huong thanh qua"
    else
      echo "Hay tro DNS domain $NAME: $checkdns thanh $ip va cai them SSL de tan huong thanh qua"
    fi
  fi

  echo "==================================================================="
  echo "                                                                   "
  echo "Disk : $(df -BG | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')                        "
  echo "                                                                   "
  echo "                                                                   "
  echo "Duong dan luu tru backup	: /usr/local/backup-website/$NAME         "
  echo "duong dan thu muc website	: /usr/local/lsws/$NAME/html              "
  echo "==================================================================="
  echo "Cong cu phat trien boi		: Gia Tuan"
  echo "Yeu Cau Ho tro			: https://wptangtoc.com/lien-he"
  echo "Ho tro phat trien		: https://wptangtoc.com/donate"
  echo "==================================================================="
fi
