#!/bin/bash

#file này chỉ sử dụng cho centos 7
if [[ $(which dnf 2>/dev/null) ]];then
	return 2>/dev/null; exit
fi

php_doi_so=$1
if [[ $1 ]];then
	#check kiem tra chinh xac cua doi so
	check_xac_thuc_php=$(echo $1 | grep '74\|73\|80\|81\|82\|83')
fi

if [[ $check_xac_thuc_php = '' ]];then
echo "Lựa chọn phiên bản PHP bạn muốn thêm PHP ZIP extension:"
function lua_chon_NAME() {
	LSPHP=""
	if [ "$(ls /usr/local/lsws)" ]; then
		selects=()
		for entry in $(ls /usr/local/lsws); do
			LSPHP=$(echo $entry | grep 'lsphp')
				selects+=("$LSPHP")
		done
		PS3="
-//- Nhập lựa chọn phiên bản PHP bạn muốn cài đặt [0=Thoát]: "
		select select in ${selects[@]}; do
			LSPHP=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Webserver không có bất kỳ phiên bản PHP nào tồn tại trên hệ thống của bạn."
		exit
	fi
}
lua_chon_NAME
fi


if [[ $check_xac_thuc_php ]];then
	LSPHP=$(echo lsphp${php_doi_so})
fi

. /etc/wptt/echo-color

if [[ $LSPHP = "0" || $LSPHP = '' ]];then
. /etc/wptt/wptt-php-ini-main 1
exit
fi

_runing "Cài Đặt PHP Zip extension $LSPHP"

if [[ ! -d /usr/local/lsws/${LSPHP} ]];then
_runloi "Cài Đặt PHP Zip extension $LSPHP"
echoDo "Khong xac dinh duoc dir php"
. /etc/wptt/wptt-php-ini-main 1
exit
fi

yum install $LSPHP-pear $LSPHP-devel -y >/dev/null 2>&1 --nogpgcheck 
# yum install -y https://packages.psychotic.ninja/7/plus/x86_64/RPMS/libzip-0.11.2-6.el7.psychotic.x86_64.rpm >/dev/null 2>&1
# yum install -y http://packages.psychotic.ninja/7/plus/x86_64/RPMS/libzip-devel-0.11.2-6.el7.psychotic.x86_64.rpm >/dev/null 2>&1
yum install -y https://wptangtoc.com/share/lib/libzip-0.11.2-6.el7.psychotic.x86_64.rpm >/dev/null 2>&1
yum install -y https://wptangtoc.com/share/lib/libzip-devel-0.11.2-6.el7.psychotic.x86_64.rpm >/dev/null 2>&1

/usr/local/lsws/$LSPHP/bin/pecl install zip >/dev/null 2>&1
echo "extension=zip.so" > /usr/local/lsws/$LSPHP/etc/php.d/20-zip.ini


if [[ ! -f /usr/local/lsws/$LSPHP/lib64/php/modules/zip.so ]];then
	cd /usr/local/lsws/$LSPHP/lib64/php/modules && wget https://wptangtoc.com/share/lib/zip.so
fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "Cài Đặt PHP Zip extension $LSPHP"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-php-ini-main 1
fi
