#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2023

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý PHP => Cài lại PHP 	                                          |"
echo "========================================================================="
echo ""
echo ""
echo "tính năng này đang bảo trì hoạt động chưa ổn định"
. /etc/wptt/wptt-php-ini-main 1
exit

blue='\033[1;34m'
NC='\033[0m'
echo -e "${blue}                                              
                           ...::::--------------:::...                          
                  .:--===++++===========================--:..                  
             :-=+++++++===========+++++++===========+++=======-:.              
         .-+++++=============+===+*.   *+=========+===============-:.          
      .=+*++====++++++++++++===+=*-   :#=+++++===+=+++++++++++++==+==-:        
    :+*++====+=++===========+++==*    :======+++==*+===========+++==++=-:      
   =*+===++==+=#.            .=*++             -*+*             .-*====++=.    
 .++==++======++    +=====:    -%.   -+=+=+-    =#=    +=====:    -*=+===++:   
 ++==+======+=*:   :#=+++=#:   .#    *+++=+*    *#.   -#=++++#.   .#=+=====+:  
:+===========+*    ++====+*    =-   :*=++=*:   :#+    ++====+*    =*=+=====+=  
:+=========+=*=    #++++++.   :#    ++===+*    =#-   :#++++++.   :*========+=  
 =+========+=*     :....    .=#=   .#=++=*=    **     :....    .=*=========+:  
  ==========++    .......:-+*+*:...+*=++=#:...-#=    .......:-+*+========++:   
   :==+===+=#:   =*+++++++++==++++++=====++++++#:   -#+++++++++==+=====++=.    
    .-===+=+*    *+=========++================+*    *+=========+====++=-:      
       :-==++---=*=+===++=====++++++=====++++=+*---=*=+=========+++==-:        
          :-=++++=+============================+++++========++====-:.          
              .:-=======+++=========================+++=======-:.              
                   .::--===============================--::.                   
                           ...:::-------------::::..                           
     

${NC}"
. /etc/wptt/.wptt.conf
echo "Dang tien hanh cai dat. Vui long doi..."
sleep 2

phpcheck=$(php -v | grep cli | grep -oP 'PHP \K[0-9]+\.[0-9]+')
php_ver_chon=${phpcheck//[-._]/}
if [[ "$php_ver_chon" = "" ]]; then
  echo "PHP cua ban bi loi, he thong khong the xac nhan duoc phien ban php dang su dung, vui long lua chon phien ban php ban da su dung"
  echo "Ban hay lua chon phien ban PHP muon su dung: "
  prompt="Nhap vao lua chon cua ban [1-4]: "
  php_version="7.4"
  options=("Phien ban PHP 8.1" "Phien ban PHP 8.0" "Phien ban PHP 7.4" "Phien ban PHP 7.3")
  PS3="$prompt"
  select opt in "${options[@]}"; do

    case "$REPLY" in
    1)
      php_version="8.1"
      break
      ;;

    2)
      php_version="8.0"
      break
      ;;
    3)
      php_version="7.4"
      break
      ;;

    4)
      php_version="7.3"
      break
      ;;

    $((${#options[@]} + 1)))
      printf "\nHe thong se cai dat PHP 7.4\n"
      break
      ;;
    *)
      printf "Ban nhap sai, he thong cai dat PHP 7.4\n"
      break
      ;;
    esac

  done
  php_ver_chon=${php_version//[-._]/}
  clear
fi

if [[ -f /usr/local/lsws/lsphp${php_ver_chon}/lib64/php/modules/ioncube.so ]]; then
  checkioncube="1"
fi

extensions=(
  json
  gd
  process
  mbstring
  mysqlnd
  xml
  opcache
  mcrypt
  pdo
  imap
  bcmath
  intl
)

yum remove -y lsphp${php_ver_chon}
yum install -y lsphp${php_ver_chon}

for extension in ${extensions[@]}; do
  yum remove -y lsphp${php_ver_chon}-$extension
  yum install -y lsphp${php_ver_chon}-$extension
done

#yum remove lsphp${php_ver_chon} lsphp${php_ver_chon}-json lsphp${php_ver_chon}-common lsphp${php_ver_chon}-gd lsphp${php_ver_chon}-imagick lsphp${php_ver_chon}-process lsphp${php_ver_chon}-mbstring lsphp${php_ver_chon}-mysqlnd lsphp${php_ver_chon}-xml lsphp${php_ver_chon}-opcache lsphp${php_ver_chon}-mcrypt lsphp${php_ver_chon}-pdo lsphp${php_ver_chon}-imap lsphp${php_ver_chon}-bcmath lsphp${php_ver_chon}-intl -y
##lsphp${php_ver_chon}-zip
#yum install lsphp${php_ver_chon} lsphp${php_ver_chon}-json lsphp${php_ver_chon}-common lsphp${php_ver_chon}-gd lsphp${php_ver_chon}-imagick lsphp${php_ver_chon}-process lsphp${php_ver_chon}-mbstring lsphp${php_ver_chon}-mysqlnd lsphp${php_ver_chon}-xml lsphp${php_ver_chon}-opcache lsphp${php_ver_chon}-mcrypt lsphp${php_ver_chon}-pdo lsphp${php_ver_chon}-imap lsphp${php_ver_chon}-bcmath lsphp${php_ver_chon}-pecl-memcache lsphp${php_ver_chon}-intl -y
##lsphp${php_ver_chon}-zip

if [[ "$checkioncube" = "1" ]]; then
  yum remove lsphp${php_ver_chon}-ioncube -y
  yum install lsphp${php_ver_chon}-ioncube -y --nogpgcheck
fi

if [[ -f /etc/redis.conf ]]; then
  yum remove lsphp${php_ver_chon}-pecl-redis -y
  yum install lsphp${php_ver_chon}-pecl-redis -y --nogpgcheck
fi

if [[ -d /usr/local/lsmcd ]]; then
  yum remove lsphp${php_ver_chon}-pecl-memcached -y
  yum install lsphp${php_ver_chon}-pecl-memcached -y --nogpgcheck
fi

sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/httpd_config.conf
if [ "$(ls -A /etc/wptt/vhost | sort -uV)" ]; then
  echo
  echo "dang cap nhat chuyen doi version php $php_version"
  echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1
    if [[ -d "$path" ]]; then
      sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/vhosts/$domain/$domain.conf
      sed -E -i "s/ lsphp${php_ver_chon}/lsphp${php_ver_chon}/g" /usr/local/lsws/conf/vhosts/"$domain"/"$domain".conf
      sed -i "s/lsphp ${php_ver_chon}/lsphp${php_ver_chon}/g" /usr/local/lsws/conf/vhosts/"$domain"/"$domain".conf

    fi
  done
  echo '--------------------------------------------------'
  echo
fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/httpd_config.conf

if [ "$(ls -A /etc/wptt/vhost | sort -uV)" ]; then
  echo
  echo "dang cap nhat chuyen doi version php $php_version"
  echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1
    if [[ -d "$path" ]]; then
      sed -E -i "s/lsphp[0-9]+/lsphp$php_ver_chon/g" /usr/local/lsws/conf/vhosts/$domain/$domain.conf
      sed -E -i "s/ lsphp${php_ver_chon}/lsphp${php_ver_chon}/g" /usr/local/lsws/conf/vhosts/"$domain"/"$domain".conf
    fi
  done
  echo '--------------------------------------------------'
  echo
fi
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
RED='\033[0;31m'
NC='\033[0m'
echo -e "${RED}-------------------------------------------------------------------------"
echo ""
echo " 0     0 000000  0000000                         0000000 "
echo " 0  0  0 0     0    0       00    0    0   0000     0      0000    0000 "
echo " 0  0  0 0     0    0      0  0   00   0  0    0    0     0    0  0    0 "
echo " 0  0  0 000000     0     0    0  0 0  0  0         0     0    0  0 "
echo -e "${NC} 0  0  0 0          0     000000  0  0 0  0  000    0     0    0  0 "
echo " 0  0  0 0          0     0    0  0   00  0    0    0     0    0  0    0 "
echo "  00 00  0          0     0    0  0    0   0000     0      0000    0000 "
echo ""
echo "  00000   0       00000 "
echo " 0     0  0      0     0 "
echo " 0     0  0      0 "
echo -e "${RED} 0     0  0       00000 "
echo " 0     0  0            0 "
echo " 0     0  0      0     0 "
echo "  00000   000000  00000 "
echo -e "--------------------------------------------------------------------------${NC}"
echo "-------------------------------------------------------------------------"
echo -e "${RED}-------------------------------------------------------------------------"
echo "  Cap nhat phien ban php $php_version_check cong webserver WPTangToc OLS $wptangtocols_version	"
echo "-------------------------------------------------------------------------"
echo -e "--------------------------------------------------------------------------${NC}"
echo "-------------------------------------------------------------------------"
echo "Cong cu WPTangToc OLS phat trien boi: Gia Tuan"
echo "Yeu Cau Ho tro		: https://wptangtoc.com/lien-he/"
echo "Giup chung toi luon giu WPTangToc OLS co the su dung mien phi bang cach dong gop vao"
echo "Tai tro phat trien	: https://wptangtoc.com/donate/"
echo "Huong dan		: https://wptangtoc.com/wptangtoc-ols-huong-dan"
echo "-------------------------------------------------------------------------"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-php-ini-main 1
fi
