#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly PHP => Huy kich hoat ioncube PHP                               |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/.wptt.conf
read -p "Kich hoat huy kich ioncube PHP (y/n): " dongy

if [[ "$dongy" != "y" ]]; then
    . /etc/wptt/wptt-php-ini-main
fi

php_ver_chon=${php_version_check//[-._]/}

if [[ ! -f /usr/local/lsws/lsphp${php_ver_chon}/lib64/php/modules/ioncube.so ]]; then
    echo "he thong cua ban chua duoc kich hoat ioncube php truoc do"
    exit
fi

lsphp=($(ls /usr/local/lsws | grep 'lsphp' | sed 's/^lsphp//g'))
ioncube_khong_ho_tro=(
	80
	81
	)
for phpioncube in ${lsphp[@]};do
	if [[ ! "$phpioncube" =~ "$ioncube_khong_ho_tro" ]];then
echo "Tien hanh Huy kich hoat ioncube php${phpioncube}"
        yum remove lsphp${phpioncube}-ioncube -y
	fi
done

/usr/local/lsws/bin/lswsctrl restart
clear
echo "Huy kich hoat thanh cong ioncube"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-php-ini-main 1
fi

