#!/bin/bash

function huong_dan() {
  Tính năng Cấu hình max_execution_time PHP là việc điều chỉnh một cài đặt quan trọng trong PHP để quy định thời gian tối đa [tính bằng giây] mà một đoạn mã [script] PHP được phép chạy trước khi bị máy chủ tự động dừng lại.

  Nói một cách đơn giản, đây là cách bạn đặt ra giới hạn một tác vụ PHP không được chạy quá X giây.

  Mục đích chính:

  * Ngăn chặn script chạy vô hạn: Giúp dừng các script bị lỗi [ví dụ: vòng lặp vô tận] hoặc các tác vụ tốn quá nhiều thời gian, tránh làm treo máy chủ hoặc tiêu tốn tài nguyên quá mức.
  * Quản lý tài nguyên máy chủ: Đảm bảo không có script nào chiếm dụng CPU quá lâu, ảnh hưởng đến các tác vụ khác.
  * Cho phép các tác vụ dài hơi hợp lệ: Đối với các tác vụ cần nhiều thời gian để hoàn thành [như xử lý file lớn, gửi email hàng loạt, đồng bộ dữ liệu], bạn có thể tăng giá trị này lên để script không bị dừng giữa chừng.

  Mặc định là 120 giây.
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_php => $cau_hinh_max_excution_time                         |"
echo "========================================================================="
echo ""
echo ""
echo ""
. /etc/wptt/.wptt.conf
. /etc/wptt/php/wptt-php-version-domain 1

echo "Lựa chọn phiên bản PHP bạn muốn $cau_hinh_max_excution_time:"
. /etc/wptt/php/tenmien-php

. /etc/wptt/echo-color
if [[ $LSPHP = "" || $LSPHP = "0" ]]; then
  . /etc/wptt/wptt-php-ini-main 98
fi

echo "Mọi thứ đã được mình cầu hình tối ưu hết rồi"
echo "Nếu bạn có nhu cầu thực thi dài khi đã thực thi xong thì hãy vui lòng khôi phục vụ về để đảm bảo hiệu suất và bảo mật"
# echo "chung minh cung co ho tro tinh nang khoi phuc trong menu cua WPTangToc OLS"

if $(cat /etc/*release | grep -q "Ubuntu"); then
  phien_ban_php_co_cham=$(echo $LSPHP | grep -Eo '[0-9]{1,2}' | head -1 | perl -pe 's/(\d{1})(?=(?:\d{1}){1,5}\b)/\1./g')
  max_execution_time_hientai=$(cat /usr/local/lsws/$LSPHP/etc/php/$phien_ban_php_co_cham/litespeed/php.ini | grep 'max_execution_time' | cut -f2 -d '=')
else
  max_execution_time_hientai=$(cat /usr/local/lsws/$LSPHP/etc/php.ini | grep 'max_execution_time' | cut -f2 -d '=')
fi

echo "max_execution_time hiện tại $LSPHP giá trị là ${max_execution_time_hientai} giây"
echo ""
echo ""
read -p "Nhập số thời gian max_execution_time bạn muốn thay đổi php.ini
Lưu ý: Nhập số nguyên dương [0=Thoát]: " port
if [[ "$port" = "0" || "$port" = "" ]]; then
  clear
  . /etc/wptt/wptt-php-ini-main 98
  exit
fi

# port=$(echo $port | sed 's/mb//g' | sed 's/MB//g'| sed 's/M//g'| sed 's/m//g' | sed 's/ //g' | sed 's/-//g')

if [[ ! $port =~ ^-?[0-9]+$ ]]; then
  clear
  echoDo "Nhập sai trường dữ liệu hãy nhập số tự nhiện"
  . /etc/wptt/wptt-php-ini-main 98
  exit
fi

echo "Xác nhận bạn muốn thay đổi max_execution_time thành ${port} giây"
prompt="Nhập lựa chọn của bạn [1-2]: "
check="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
  case "$REPLY" in
  1)
    check="y"
    break
    ;;

  2)
    check="n"
    break
    ;;

  $((${#options[@]} + 1)))
    printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
    break
    ;;
  *)
    printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
    break
    ;;
  esac
done

if [[ "$check" = "y" ]]; then
  # php_server=$(php -i | grep php.ini | grep Loaded | cut -c 30-80 | cut -f5 -d "/")
  . /etc/wptt/echo-color
  _runing "Cấu hình max_execution_time $LSPHP giá trị là ${port} giây"

  if $(cat /etc/*release | grep -q "Ubuntu"); then
    phien_ban_php_co_cham=$(echo $LSPHP | grep -Eo '[0-9]{1,2}' | head -1 | perl -pe 's/(\d{1})(?=(?:\d{1}){1,5}\b)/\1./g')
    duong_dan_php_ini="/usr/local/lsws/$LSPHP/etc/php/$phien_ban_php_co_cham/litespeed/php.ini"
  else
    duong_dan_php_ini="/usr/local/lsws/$LSPHP/etc/php.ini"
  fi

  php=$(echo "$duong_dan_php_ini")
  if [[ ! -f $php ]]; then
    _runloi "Cấu hình max_execution_time $LSPHP giá trị là ${port} giây"
    echo "Không xác định được file php.ini"
    . /etc/wptt/wptt-php-ini-main 1
    exit
  fi

  sed -i "/max_execution_time/d" "$php"
  sed -i "/max-execution-time/a max_execution_time = ${port}" "$php"

  /usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
  _rundone "Cấu hình max_execution_time $LSPHP giá trị là ${port} giây"

  echo "-------------------------------------------------------------------------"
  echo "Khi bạn thực thi một công việc nào đó cần nhi thời gian thực thi xong"
  echo "thì hãy khôi phục lại thành 120 để nâng cao bảo mật và ổn định hệ thống"
  echo "-------------------------------------------------------------------------"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-php-ini-main 1
fi
