#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly PHP => Khoi phuc PHP.ini                                       |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/.wptt.conf
phpcheck222=$(php -v |grep cli | cut -c 1-10)
echo "-------------------------------------------------------------------------"
echo "Khoi phuc cau hinh php.ini phien ban php ban dang su dung $phpcheck222"
echo "-------------------------------------------------------------------------"

if [[ ! -f '/etc/wptt/php.ini_bk' ]]; then
echo "ban chua chinh sua cau hinh php.ini"
exit
fi

read -p "Xac nhan ban muon khoi phuc php.ini (y/n): " check
if [[ "$check" = "y" ]]; then
php=$(php -i |grep php.ini|grep Loaded| cut -c 30-80)
\cp -f /etc/wptt/php.ini_bk $php
rm -f /etc/wptt/php.ini_bk
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
echo "-------------------------------------------------------------------------"
echo "Hoan tat qua trinh khoi phuc PHP.ini"
echo "-------------------------------------------------------------------------"
fi