#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý PHP => Hủy kích hoạt ioncube PHP                               |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/.wptt.conf
read -p "Hủy kích hoạt ioncube PHP (y/n): " dongy

if [[ "$dongy" != "y" ]]; then
    . /etc/wptt/wptt-php-ini-main 1
fi

. /etc/wptt/echo-color
php_ver_chon=${php_version_check//[-._]/}

if [[ ! -f /usr/local/lsws/lsphp${php_ver_chon}/lib64/php/modules/ioncube.so ]]; then
    echoDo "Hệ thống của bạn chưa kích hoạt ioncube php trươc đó"
    exit
fi


_runing "Hủy kích hoạt ioncube extension PHP"
lsphp=($(ls /usr/local/lsws | grep 'lsphp' | sed 's/^lsphp//g'))
ioncube_khong_ho_tro=(
	80
	81
)
for phpioncube in ${lsphp[@]};do
	if [[ ! "$phpioncube" =~ "$ioncube_khong_ho_tro" ]];then
        yum remove lsphp${phpioncube}-ioncube -y >/dev/null 2>&1
	fi
done
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "Hủy kích hoạt ioncube extension PHP"
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-php-ini-main 1
fi

