#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly PHP => Cau hinh PHP.ini                                        |"
echo "========================================================================="
echo ""
. /etc/wptt/.wptt.conf
. /etc/wptt/php/wptt-php-version-domain

echo "Lua chon phien ban php ban muon cau hinh:"
function lua_chon_NAME() {
	LSPHP=""
	if [ "$(ls /usr/local/lsws)" ]; then
		selects=()
		for entry in $(ls /usr/local/lsws); do
			LSPHP=$(echo $entry | grep 'lsphp')
				selects+=("$LSPHP")
		done
		PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
		select select in ${selects[@]}; do
			LSPHP=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "webserver khong bat ky phien ban php nao ton tai tren he thong cua ban."
		exit
	fi
}
lua_chon_NAME

echo "Moi thu minh da cau hinh toi uu het roi"
echo "Neu ban co nhu cau uploads file dung luon lon thi khi da uploads xong thi hay vui long khoi phuc ve nhu cu de dam bao hieu suat va bao mat"
echo "Chung minh cung co ho tro tinh nang khoi phuc trong menu cua WPTangToc OLS"
echo -e "Hay than can nhac thuc su ban dang lam gi ${RED} Can nhac truoc khi chinh sua file php.ini ${NC}"
read -p "Xac nhan ban muon chinh sua php.ini (y/n): " check
if [[ "$check" = "y" ]]; then
if [[ $editor_cau_hinh = "" ]];then
editor_cau_hinh="nano" 
fi
echo "Su dung cong cu editor: $editor_cau_hinh de chinh sua"
sleep 2
if [[ $editor_cau_hinh = "nano" ]];then
    echo "Ctrl + O de luu lai va ctrl + X de thoat ra, ctrl + W de tim kiem nhanh"
    sleep 3
fi
	# php_server=$(php -i | grep php.ini | grep Loaded | cut -c 30-80 | cut -f5 -d "/")
	php=$(/usr/local/lsws/$LSPHP/etc/php.ini)
	if [[ ! -f $php ]];then
		echo "khong xac dinh duoc duong dan php.ini"
exit
	fi

    $editor_cau_hinh "$php"
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
fi
