#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý start service => start Redis"
echo "========================================================================="
echo ""
echo ""
if [[ -f /etc/redis.conf ]];then
. /etc/wptt/echo-color
_runing "Khởi động redis"
systemctl start redis.service
_rundone "Khởi động redis"
echo "-------------------------------------------------------------------------"
echo "Hoàn thành khởi động object cache redis"
echo "-------------------------------------------------------------------------"
echo "Tình trạng hoạt động của Redis hiện tại"
active_hien_tai=$(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
if [[ $active_hien_tai = "active" ]];then
echo "Redis     : Hoạt động tốt"
else
echo "Redis     : Đang gặp sự cố"
fi
echo "-------------------------------------------------------------------------"
else
echo "Ban chua cai dat object cache Redis"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/service/wptt-start-main 1
fi
