#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly start APP => start ALL service                               |"
echo "========================================================================="
echo ""
echo ""
echo "Tien hanh start LiteSpeed"
/usr/local/lsws/bin/lswsctrl start >/dev/null 2>&1
echo "Hoan tat start LiteSpeed"

echo "Tien hanh start MYSQL"
systemctl start mariadb.service
echo "Hoan tat start MYSQL"

echo "Tien hanh start SSH"
systemctl start sshd.service
echo "Hoan tat start SSH"

echo "Tien hanh start Crond"
systemctl start crond.service
echo "Hoan tat start Crond"

echo "Tien hanh start fail2ban"
systemctl start fail2ban
echo "Hoan tat start fail2ban"
if [[ -d /usr/local/lsmcd ]];then
echo "Tien hanh start LSMemcached"
systemctl start lsmcd
echo "Hoan tat start LSMemcached"
fi

if [[ -f /etc/redis.conf ]];then
echo "Tien hanh start redis"
systemctl start redis.service
echo "Hoan tat start redis"
fi
sleep 3

reset

echo "+-----------------------------------------------------------------------+"
echo "|Tinh trang hoat dong cac service hien tai                              |"
echo "+-----------------------------------------------------------------------+"
echo "|LiteSpeed     : $(systemctl status lshttpd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "|MariaDB       : $(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
if [[ -d /usr/local/lsmcd ]];then
echo "|LSMemcached   : $(systemctl status lsmcd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
fi

if [[ -f /etc/redis.conf ]];then
echo "|Redis   : $(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
fi


echo "|SSH           : $(systemctl status sshd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "|Crond         : $(systemctl status crond.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "|Fail2Ban      : $(systemctl status fail2ban.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
echo "+-----------------------------------------------------------------------+"



check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/service/wptt-start-main 1
fi
