#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025

function huong_dan(){
tính năng cập nhật WP-CLI thì đây là một chức năng tiện ích giúp bạn dễ dàng nâng cấp WP-CLI [WordPress Command-Line Interface] lên phiên bản mới nhất ngay trên máy chủ của mình.

🎯 Mục đích của tính năng cập nhật WP-CLI:
 * Sử dụng Tính năng Mới: WP-CLI liên tục được phát triển. Các bản cập nhật mang đến các lệnh mới, tùy chọn mới và cải tiến hiệu suất, giúp bạn quản lý WordPress hiệu quả hơn.
 * Vá lỗi & Tăng Ổn định: Các phiên bản mới sửa các lỗi được phát hiện trong các phiên bản cũ, giúp WP-CLI hoạt động ổn định và đáng tin cậy hơn.
 * Bảo mật: Đôi khi, các bản cập nhật cũng bao gồm các bản vá bảo mật cho chính công cụ WP-CLI.
 * Đảm bảo Tương thích: Giữ cho WP-CLI tương thích tốt nhất với các phiên bản WordPress mới nhất, PHP và môi trường máy chủ.

Tóm lại: Tính năng cập nhật WP-CLI trong WPTangToc OLS là một tiện ích giúp bạn đảm bảo rằng công cụ dòng lệnh WP-CLI trên máy chủ của mình luôn là phiên bản mới nhất, giúp bạn tiếp cận các tính năng, bản vá lỗi và cải tiến bảo mật mới nhất một cách dễ dàng.
}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý cập nhật Update => Cập nhật WP-CLI                             |"
echo "========================================================================="
echo ""
echo ""

if [[ ! $(which wp) ]];then
	echo "Tiến hành cài đặt WP CLI"
	curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
	chmod +x wp-cli.phar
	mv wp-cli.phar /usr/local/bin/wp
	if [[ ! $(which wp) ]];then
		curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
		chmod +x wp-cli.phar
		mv wp-cli.phar /usr/bin/wp
	fi
	if [[ $(which wp) ]];then
		echo "Đã tiền hành cài đặt WP CLI thành công"
	else
		echo "Cài đặt WP CLI Thất bại"
	fi
	. /etc/wptt/wptt-update-main 1
fi

version=$(wp --info | grep 'WP-CLI version' | cut -f2 -d ':')
echo "Phiên bản WP CLI hiện tại của bạn là: version $version"
echo "Đang tiến hành cập nhật WP CLI vui lòng đợi..."
wp cli update
version2=$(wp --info | grep 'WP-CLI version' | cut -f2 -d ':')
if [[ "$version" = "$version2" ]]; then
	echo "Hiện tại bạn đã sử dụng phiên bản WP CLI mới nhất rồi"
else
	. /etc/wptt/echo-color
    echoDone "Cập nhật thành công WP CLI lên phiên bản $version2"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-update-main 1
fi
