#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Update => Cap nhat WP-CLI                                      |"
echo "========================================================================="
echo ""
echo ""

version=$(wp --info | grep 'WP-CLI version' | cut -f2 -d ':')
echo "Phien ban wp cli hien tai cua ban la: version: $version"
echo "Dang tien hanh cap nhat WP CLI Vui long doi..."
wp cli update
version2=$(wp --info | grep 'WP-CLI version' | cut -f2 -d ':')
if [[ "$version" = "$version2" ]]; then
    echo "Hien tai ban da su dung phien ban wp cli moi nhat roi"
else
	. /etc/wptt/echo-color
    echoDone "Cap nhat thanh cong wp cli len phien ban $version2"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-update-main 1
fi
