#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_php => $cap_nhat PHP                                         |"
echo "========================================================================="
echo ""
echo ""


. /etc/wptt/.wptt.conf
echo '                          ...::::--------------:::...                          
                  .:--===++++===========================--:..                  
             :-=+++++++===========+++++++===========+++=======-:.              
         .-+++++=============+===+*.   *+=========+===============-:.          
      .=+*++====++++++++++++===+=*-   :#=+++++===+=+++++++++++++==+==-:        
    :+*++====+=++===========+++==*    :======+++==*+===========+++==++=-:      
   =*+===++==+=#.            .=*++             -*+*             .-*====++=.    
 .++==++======++    +=====:    -%.   -+=+=+-    =#=    +=====:    -*=+===++:   
 ++==+======+=*:   :#=+++=#:   .#    *+++=+*    *#.   -#=++++#.   .#=+=====+:  
:+===========+*    ++====+*    =-   :*=++=*:   :#+    ++====+*    =*=+=====+=  
:+=========+=*=    #++++++.   :#    ++===+*    =#-   :#++++++.   :*========+=  
 =+========+=*     :....    .=#=   .#=++=*=    **     :....    .=*=========+:  
  ==========++    .......:-+*+*:...+*=++=#:...-#=    .......:-+*+========++:   
   :==+===+=#:   =*+++++++++==++++++=====++++++#:   -#+++++++++==+=====++=.    
    .-===+=+*    *+=========++================+*    *+=========+====++=-:      
       :-==++---=*=+===++=====++++++=====++++=+*---=*=+=========+++==-:        
          :-=++++=+============================+++++========++====-:.          
              .:-=======+++=========================+++=======-:.              
                   .::--===============================--::.                   
                           ...:::-------------::::..                           
'
echo "$dang_tien_hanh_cap_nhat_vui_long_doi"
yum install epel-release -y
if [[ $(which dnf 2>/dev/null) ]];then
rpm -Uvh http://rpms.litespeedtech.com/centos/litespeed-repo-1.3-1.el8.noarch.rpm
else
rpm -Uvh http://rpms.litespeedtech.com/centos/litespeed-repo-1.3-1.el7.noarch.rpm
fi

if [[ -f /usr/local/lsws/lsphp74/lib64/php/modules/ioncube.so ]]; then
    checkioncube="1"
fi

if [[ -f /usr/local/lsws/lsphp73/lib64/php/modules/ioncube.so ]]; then
    checkioncube73="1"
fi


# phpcheck=$(php -v |grep cli | cut -c 4-7)
# php_ver_chon=${phpcheck//[-._]/}


lsphp=($(ls /usr/local/lsws | grep 'lsphp' | sed 's/^lsphp//g'))
for allphp in ${lsphp[@]};do
echo "Tien hanh cap nhat PHP $allphp :"
yum update lsphp${allphp} lsphp${allphp}-json lsphp${allphp}-common lsphp${allphp}-gd lsphp${allphp}-imagick lsphp${allphp}-process lsphp${allphp}-mbstring lsphp${allphp}-mysqlnd lsphp${allphp}-xml lsphp${allphp}-opcache lsphp${allphp}-mcrypt lsphp${allphp}-pdo lsphp${allphp}-imap lsphp${allphp}-bcmath lsphp${allphp}-pecl-memcache lsphp${allphp}-pecl-memcached lsphp${allphp}-intl lsphp${allphp}-zip -y --disablerepo="*" --enablerepo="litespeed,litespeed-edge,litespeed-edge-update,litespeed-update"
echo "$cap_nhat_thanh_cong PHP $allphp"
done

if [[ "$checkioncube" = "1" ]]; then
    yum update lsphp74-ioncube -y
fi

if [[ "$checkioncube73" = "1" ]]; then
    yum update lsphp73-ioncube -y
fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
clear
lsphp=($(ls /usr/local/lsws | grep 'lsphp' | sed 's/^lsphp//g'))
for allphp in ${lsphp[@]};do
echo "$cap_nhat_thanh_cong PHP $allphp $tren_he_thong WPTangToc OLS $wptangtocols_version	"
done
echo "-------------------------------------------------------------------------"
echo "-------------------------------------------------------------------------"
echo "$phat_trien_boi_gia_tuan"
echo "-------------------------------------------------------------------------"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-update-main 1
fi

