#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Update => Tat tu dong update WPTangToc OLS                     |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien

if [[ ! -f /etc/cron.d/wptangtoc-ols.cron ]]; then
    echo "Ban chua kich hoat tu dong cap nhat wptangtoc ols"
    sleep 4
    . /etc/wptt/wptt-update-main
    exit
fi

read -p "Ban co chac muon tat tu dong kiem tra va cap nhat wptangtoc ols? [y/n] " response
if [[ "$response" = "y" ]]; then
    rm -f /etc/cron.d/wptangtoc-ols.cron
    systemctl restart crond.service
    echo "Hoan tat huy kich hoat tu dong cap nhat wptangtoc ols"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-update-main 1
fi

