#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý cập nhật => Tắt tự động update WPTangToc OLS                   |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien

if [[ ! -f /etc/cron.d/wptangtoc-ols.cron ]]; then
	echo "Bạn chưa kích hoạt tự động cập nhật WPTangToc OLS"
    sleep 4
    . /etc/wptt/wptt-update-main 1
    exit
fi

echo "Bạn có chắc muốn tắt tự động cập nhật WPTangToc OLS?"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ "$dongy" = "y" ]]; then
    rm -f /etc/cron.d/wptangtoc-ols.cron
    systemctl restart crond.service
	echo "Hoàn tất hủy kích hoạt tự động cập nhật WPTangToc OLS"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-update-main 1
fi

