#!/bin/bash

function huong_dan() {
  Rollback System: Cỗ máy thời gian cho WPTangToc OLS. Cho phép bạn quay lại phiên bản cũ ngay lập tức nếu bản cập nhật mới gặp lỗi hoặc không ưng ý.

  An tâm tuyệt đối khi cập nhật! Tính năng Rollback sẽ tự động sao lưu hệ thống trước khi nâng cấp. Bạn có thể khôi phục lại phiên bản ổn định trước đó bất cứ lúc nào chỉ với một phím bấm.
}

. /etc/wptt/echo-color
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
echo "========================================================================="
echo "|$quan_ly_update => Rollback WPTangToc OLS" |
  echo "========================================================================="

if [[ ! $(ls -A /etc/wptt/wptt-backup-system | grep '.zip$' | grep '^wptt_backup_') ]]; then
  echoDo "Không có file backup nào để rollback nào tồn tại."
  exec /etc/wptt/wptt-update-main 1
  exit
fi

echo "Lựa chọn phiên bản bạn muốn rollback WPTangToc OLS: "
selects=()
for entry in $(ls -At /etc/wptt/wptt-backup-system/ | grep '.zip$' | grep '^wptt_backup_'); do
  selects+=("$entry")
done

if [[ $selects = '' ]]; then
  echoDo "Không có file backup nào để rollback nào tồn tại."
  exec /etc/wptt/wptt-update-main 1
  exit
fi

PS3="
$(tput setab 0)-//- $nhap_lua_chon_cua_ban [0=$exit_thoat]:$(tput sgr0) "
select select in ${selects[@]}; do
  file=$select
  break
done

if [[ "$file" = "0" || "$file" = "" ]]; then
  exec /etc/wptt/wptt-update-main 1
  exit
fi

if [[ "$file" = "" ]]; then
  clear
  echoDo "Không có file backup nào để rollback nào tồn tại."
  sleep 3
  exec /etc/wptt/wptt-update-main 1
fi

duong_dan_thu_muc_backup_system="/etc/wptt/wptt-backup-system/$file"

#giải nén restore
unzip -o $duong_dan_thu_muc_backup_system -d /etc/wptt

version_wptangtoc_ols_rollback=$(echo $file | cut -f2 -d ':' | sed 's/.zip//g')

\cp -f /etc/wptt/wptangtoc /usr/bin
rm -f /etc/wptt/wptangtoc
\cp -f /etc/wptt/wptt /usr/bin
rm -f /etc/wptt/wptt
chmod -R 700 /etc/wptt

kiem_tra_ton_tai_nhom=$(cat /etc/group | grep '^wptangtoc-ols:')
if [[ $kiem_tra_ton_tai_nhom ]]; then
  chown root:wptangtoc-ols /etc/wptt
  chown root:wptangtoc-ols /etc/wptt/vhost
  chmod 750 /etc/wptt
  chmod 750 /etc/wptt/vhost
else
  chown root:root /etc/wptt
  chown root:root /etc/wptt/vhost
  chmod 700 /etc/wptt
  chmod 700 /etc/wptt/vhost
fi

echo ""

thong_bao_ma_nguon=$(echo $file | sed 's/wptt_backup_//g' | cut -f1 -d ':' | sed 's/_version//g')
chuyen_doi_thong_bao_gio=$(echo $thong_bao_ma_nguon | cut -c 1-2)
chuyen_doi_thong_bao_ngay=$(echo $thong_bao_ma_nguon | cut -f2 -d '_' | cut -c 1-2)
chuyen_doi_thong_bao_thang=$(echo $thong_bao_ma_nguon | cut -f3 -d '_' | cut -c 1-2)
chuyen_doi_thong_bao_nam=$(echo $thong_bao_ma_nguon | cut -f4 -d '_' | cut -c 1-4)

#thông file hạ cấp vào cấu hình wptt
sed -i "/version_wptangtoc_ols/d" /etc/wptt/.wptt.conf
echo "version_wptangtoc_ols=$version_wptangtoc_ols_rollback" >>/etc/wptt/.wptt.conf

echoDone "Rollback wptangtoc ols system trước khi update lúc $chuyen_doi_thong_bao_gio giờ ngày $chuyen_doi_thong_bao_ngay tháng $chuyen_doi_thong_bao_thang năm $chuyen_doi_thong_bao_nam"
_rundone "Hạ cấp wptangtoc ols về phiên bản: $version_wptangtoc_ols_rollback"
echo "rollback hệ thống phiên bản: $version_wptangtoc_ols_rollback: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  exec /etc/wptt/wptt-update-main 1
fi
