#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2023
. /etc/wptt/.wptt.conf
echo "Đang tiến hành cập nhật. Vui lòng đợi..."
yum clean all >/dev/null 2>&1
yum install epel-release -y

OUTPUT=$(cat /etc/*release)
if  echo $OUTPUT | grep -q "CentOS Linux 7" ; then
rpm -ivh http://rpms.litespeedtech.com/centos/litespeed-repo-1.3-1.el7.noarch.rpm
elif echo $OUTPUT | grep -q "AlmaLinux 8" ; then
rpm -ivh http://rpms.litespeedtech.com/centos/litespeed-repo-1.3-1.el8.noarch.rpm
else
	echo "Muốn sử dụng WPTangToc OLS vui lòng dùng hệ điều hành almalinux 8"
	rm -f wptangtoc-ols
	exit
fi


if [[ $(which dnf) = '' ]];then
yum clean all && yum update -y && yum upgrade -y
else
dnf clean all && dnf update -y && dnf upgrade -y
fi

wget -q https://wptangtoc.com/share/wptangtoc-ols.zip
unzip -o wptangtoc-ols.zip
cd tool-wptangtoc-ols
cd ..
\cp -rf tool-wptangtoc-ols/* /etc/wptt/
rm -f wptangtoc-ols.zip
rm -rf tool-wptangtoc-ols
chmod -R 740 /etc/wptt
wptangtocols_version=$(curl -s https://wptangtoc.com/share/version-wptangtoc-ols.txt?update-toan-bo-he-thong)
sed -i "/version_wptangtoc_ols/d" /etc/wptt/.wptt.conf
echo "version_wptangtoc_ols=$wptangtocols_version" >>/etc/wptt/.wptt.conf
echo "$wptangtocols_version" > /tmp/wptangtoc-ols-version
curl -sO https://wptangtoc.com/share/update && bash update
rm -f update

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1


RED='\033[0;31m'
NC='\033[0m'
echo -e "${RED}-------------------------------------------------------------------------"
echo ""
echo " 0     0 000000  0000000                         0000000 "
echo " 0  0  0 0     0    0       00    0    0   0000     0      0000    0000 "
echo " 0  0  0 0     0    0      0  0   00   0  0    0    0     0    0  0    0 "
echo " 0  0  0 000000     0     0    0  0 0  0  0         0     0    0  0 "
echo -e "${NC} 0  0  0 0          0     000000  0  0 0  0  000    0     0    0  0 "
echo " 0  0  0 0          0     0    0  0   00  0    0    0     0    0  0    0 "
echo "  00 00  0          0     0    0  0    0   0000     0      0000    0000 "
echo ""
echo "  00000   0       00000 "
echo " 0     0  0      0     0 "
echo " 0     0  0      0 "
echo -e "${RED} 0     0  0       00000 "
echo " 0     0  0            0 "
echo " 0     0  0      0     0 "
echo "  00000   000000  00000 "
echo -e "--------------------------------------------------------------------------${NC}"
echo "-------------------------------------------------------------------------"
echo -e "${RED}-------------------------------------------------------------------------"
echo "  Cap nhat toan bo he thong thanh cong webserver WPTangToc OLS $wptangtocols_version	"
echo "-------------------------------------------------------------------------"
echo -e "--------------------------------------------------------------------------${NC}"
echo "-------------------------------------------------------------------------"
echo "Cong cu WPTangToc OLS phat trien boi: Gia Tuan"
echo "Yeu Cau Ho tro		: https://wptangtoc.com/lien-he/"
echo "Giup chung toi luon giu WPTangToc OLS co the su dung mien phi bang cach dong gop vao"
echo "Tai tro phat trien	: https://wptangtoc.com/donate/"
echo "-------------------------------------------------------------------------"


echo "Bạn có muốn khởi động lại toàn bộ máy chủ không?"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ "$dongy" = "y" ]]; then
    reboot
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-update-main 1
fi

