#!/bin/bash

echo "========================================================================="
echo "|Quản lý Reboot APP => Reboot LiteSpeed"
echo "========================================================================="
wptt reboot-ls
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-reboot-main 1
fi

