#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Reboot APP => Reboot server                                    |"
echo "========================================================================="
echo ""
reboot
echo "Websever se khoi dong lai"
