#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Reboot APP => Reboot Fail2ban service                          |"
echo "========================================================================="
echo ""
systemctl restart fail2ban.service
echo "-------------------------------------------------------------------------"
echo "Hoan thanh reboot Fail2ban"
echo "-------------------------------------------------------------------------"
echo "Tinh trang hoat dong Fail2ban hien tai"
echo "Fail2ban       : $(systemctl status fail2ban.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-------------------------------------------------------------------------"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-reboot-main 1
fi

