#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
if [[ $1 = "" ]];then
	. /etc/wptt/wptt-header-menu
	header_menu
	echo "+-----------------------------------------------------------------------+"
	echo "|Tình trạng hoạt động các service hiện tại                              |"
	echo "+-----------------------------------------------------------------------+"
	echo "|LiteSpeed     : $(systemctl status lshttpd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                  |"
	echo "|MariaDB       : $(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
	if [[ -f /etc/sysconfig/memcached ]];then
		echo "|Memcached   : $(systemctl status memcached.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
	fi
	if [[ -d /usr/local/lsmcd ]];then
		echo "|LSMemcached   : $(systemctl status lsmcd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
	fi
	if [[ -f /etc/redis.conf ]];then
		echo "|Redis 		: $(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
	fi
	echo "|SSH           : $(systemctl status sshd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
	echo "|Crond         : $(systemctl status crond.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
	echo "|Fail2Ban      : $(systemctl status fail2ban.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
	echo "+-----------------------------------------------------------------------+"
else
	. /etc/wptt/echo-color
	echoDo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
fi


options=(
    "Status-LiteSpeed-Webserver"                                                           #1
    "Status-Maria-Database"                                                                #2
    "Status-Fai2ban"                                                                       #3
    "Status-ALL-service"                                                                   #4
)

if [[ -d /usr/local/lsmcd ]];then
options+=("Status-LSMemcached")
fi

if [[ -f /etc/redis.conf ]];then
options+=("Status-Redis")
fi

if [[ -f /etc/sysconfig/memcached ]];then
options+=("Status-Memcached")
fi


# for service in ${options[@]};do
# echo $service
# done

function lua_chon_NAME() {
	NAME=""
	a=0
	selects=()
		for entry in ${options[@]}; do
			selects+=("$entry")
			a=$((a+1));
		done
		PS3="
Nhập lựa chọn của bạn (1-${a}) [0=Thoát]: "
		select select in ${selects[@]}; do
			service=$select
			index=$REPLY
			break
		done
}

echo ""
echo ""
echo "Quản lý Start service:"
echo ""
lua_chon_NAME


if [[ $service = 'Status-LiteSpeed-Webserver' ]];then
. /etc/wptt/service/status-app/wptt-status-litespeed 98
fi

if [[ $service = 'Status-Maria-Database' ]];then
. /etc/wptt/service/status-app/wptt-status-mariadb 98
fi

if [[ $service = 'Status-Fai2ban' ]];then
. /etc/wptt/service/status-app/wptt-status-fail2ban 98
fi

if [[ $service = 'Status-ALL-service' ]];then
. /etc/wptt/service/status-app/wptt-status-app 98
fi

if [[ $service = 'Status-LSMemcached' ]];then
. /etc/wptt/service/status-app/wptt-status-lsmemcached 98
fi

if [[ $service = 'Status-Redis' ]];then
. /etc/wptt/service/status-app/wptt-status-redis 98
fi

if [[ $service = 'Status-Memcached' ]];then
. /etc/wptt/service/status-app/wptt-status-memcached 98
fi

if [[ $service = '' || $service = '0' || $service = * ]];then
. /etc/wptt/wptt-service-main 1
fi



