#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Reboot APP => Reboot ALL service                               |"
echo "========================================================================="
echo ""
echo ""
. /etc/wptt/echo-color
function reboot-all-wptangtoc() {
_runing "Khởi động lại LiteSpeed"
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "Khởi động lại LiteSpeed"

_runing "Khởi động lại Maria Database"
 systemctl restart mariadb.service
_rundone "Khởi động lại Maria Database"

_runing "Khởi động lại SSH"
 systemctl restart sshd.service
_rundone "Khởi động lại SSH"

_runing "Khởi động lại Crond"
 systemctl restart crond.service
_rundone "Khởi động lại Crond"

_runing "Khởi động lại fail2ban"
 systemctl restart fail2ban.service
_rundone "Khởi động lại fail2ban"

if [[ -d /usr/local/lsmcd ]];then
_runing "Khởi động lại LSMemcached"
 systemctl restart lsmcd.service
_rundone "Khởi động lại LSMemcached"
fi

if [[ -f /etc/redis.conf ]];then
_runing "Khởi động lại Redis"
 systemctl restart redis.service
_rundone "Khởi động lại Redis"
fi

if [[ -f /etc/sysconfig/memcached ]];then
_runing "Khởi động lại Memcached"
 systemctl restart memcached.service
_rundone "Khởi động lại Memcached"
fi

if [[ -f /etc/csf/csf.conf ]];then
_runing "Khởi động lại CSF"
 systemctl restart csf.service
 systemctl restart lfd.service
_rundone "Khởi động lại CSF"
fi

    echo "+-----------------------------------------------------------------------+"
    echo "|Tình trạng hoạt động các service hiện tại                              |"
    echo "+-----------------------------------------------------------------------+"
    echo "|LiteSpeed     : $(systemctl status lshttpd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                  |"
    echo "|MariaDB       : $(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
if [[ -f /etc/sysconfig/memcached ]];then
    echo "|Memcached   : $(systemctl status memcached.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
fi
if [[ -f /etc/csf/csf.conf ]];then
    echo "|CSF 		: $(systemctl status csf.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
fi

if [[ -d /usr/local/lsmcd ]];then
    echo "|LSMemcached   : $(systemctl status lsmcd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
fi
if [[ -f /etc/redis.conf ]];then
    echo "|Redis 		: $(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
fi
    echo "|SSH           : $(systemctl status sshd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
    echo "|Crond         : $(systemctl status crond.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
    echo "|Fail2Ban      : $(systemctl status fail2ban.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 |"
    echo "+-----------------------------------------------------------------------+"
}

reboot-all-wptangtoc
check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/service/wptt-reboot-main 1
fi
