#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Reboot APP => Reboot CSF"
echo "========================================================================="
echo ""
echo ""
if [[ -f /etc/csf/csf.conf ]];then
. /etc/wptt/echo-color
_runing "Khởi động lại CSF"
systemctl restart csf.service
systemctl restart lfd.service
_rundone "Khởi động lại CSF"

echo "-------------------------------------------------------------------------"
echo "Hoàn thành reboot CSF"
echo "-------------------------------------------------------------------------"
echo "Tình trạng hoạt động CSF hiện tại"
echo "CSF   : $(systemctl status csf.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 "
echo "-------------------------------------------------------------------------"
else
echo "Bạn chưa cài đặt object cache memcached"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/service/wptt-reboot-main 1
fi

