#!/bin/bash
. /etc/wptt/.wptt.conf
ols1=$(systemctl status lshttpd.service | grep 'enabled' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
mariadb1=$(systemctl status mariadb.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
	function hello-giatuan() {
ip=$(curl -s myip.directadmin.com)
if [[ "$ip" = "" ]]; then
    ip=$(curl -s ifconfig.me)
fi
date="$(date "+%d-%m-%Y %H:%M")"
	text="
Thông báo service webserver quan trọng đã có vấn đề
-----------------------
webserver: ${ip}
Nội dung: $1
Ngày: ${date}
	"
	url_tele="https://api.telegram.org/bot${telegram_api}/sendMessage"
	curl -s -d "chat_id=${telegram_id}&text=${text}&disable_web_page_preview=true&parse_mode=markdown" $url_tele > /dev/null	
	}

if [[ "$ols1" != "loaded" ]]; then
/usr/local/lsws/bin/lswsctrl restart
hello-giatuan "LiteSpeed đang có vấn đề và đã thực hiện Khởi động lại LiteSpeed"
fi
if [[ "$mariadb1" != "active" ]]; then
systemctl restart mariadb.service
hello-giatuan "MariaDB đang có vấn đề và đã thực hiện Khởi động lại MariaDB"
fi


