#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Reboot APP => Reboot Memcached"
echo "========================================================================="
echo ""
echo ""
if [[ -f /etc/sysconfig/memcached ]];then
systemctl restart memcached.service
echo "-------------------------------------------------------------------------"
echo "Hoàn thành reboot object cache memcached"
echo "-------------------------------------------------------------------------"
echo "Tình trạng hoạt động memcached hiện tại"
echo "memcached   : $(systemctl status memcached.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)                                                 "
echo "-------------------------------------------------------------------------"
else
echo "Bạn chưa cài đặt object cache memcached"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/service/wptt-reboot-main 1
fi

