#!/bin/bash
if [[ -d /usr/local/lsws ]];then
/usr/local/lsws/bin/lswsctrl restart
echo '                          .                   
                        ...                   
                      .....     ..            
                    .......   :*+.            
                  ........ .=##-              
                ....... .-+%%+.               
              ........:+#%%*::=:              
            ...... .=*%%%#-.-====:            
          .......-+#%%%#*.:========:          
        .........#%%%%%*  :-=========:        
      ..........  =#%%%%*.  .-=========:      
     ..........    -####%#-   :==========     
       ..........   .+####%+ :=========-.     
         ..........   *#####*.=======-.       
           ........ .+#####+-:=====-.         
             ..... -####+=:-=====-.           
               . :*##*=-:-=====-.             
                =##+-:-======-.               
              -##=.-=======-.                 
            .++:   ======-.                   
            ..     ====-.                     
                   ==-.                       
                   =.                         
'
echo "-------------------------------------------------------------------------"
echo "Hoan thanh reboot LiteSpeed Webserver"
echo "-------------------------------------------------------------------------"
echo "Tinh trang hoat dong LiteSpeed Webserver hien tai"
active_hien_tai=$(systemctl status lshttpd.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
if [[ $active_hien_tai = "active" ]];then
echo "LiteSpeed     : hoat dong tot"
else
echo "LiteSpeed     : Dang gap su co"
fi
echo "-------------------------------------------------------------------------"
else
echo "Ban chua cai dat OpenLiteSpeed"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-reboot-main 1
fi

