#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
. /etc/wptt-user/echo-color
NAME=$1

if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ "$NAME" = "" ]]; then
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Cache => Xóa cache 	                                          |"
echo "========================================================================="
. /etc/wptt-user/tenmien
lua_chon_NAME
fi


. /etc/wptt-user/echo-color

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  echoDo "Hệ thống xác nhận bạn không sử dụng mã nguồn WordPress"
  echoDo "Tính năng này chỉ dành cho mã nguồn WordPress"
  sleep 3
. /etc/wptt-user/wptt-cache-main 1
return >/dev/null 2>&1 ; exit
fi


path2="/usr/local/lsws/$NAME/html"

plugins_active=$(wp plugin list --fields=name --status=active --path=$path2 --allow-root 2>/dev/null | sed '1d')

echo "Xóa website $NAME:"
_runing "Xóa OpCache"
wp eval 'opcache_reset();' --path=$path2 --allow-root >/dev/null 2>&1
_rundone "Xóa OpCache"

_runing "Xóa WP object cache"
wp cache flush --path=$path2 --allow-root >/dev/null 2>&1
_rundone "Xóa WP object cache"

if [[ -f /etc/redis.conf ]];then
	if [ "$(redis-cli ping)" = "PONG" ]; then
		_runing "Xóa bộ nhớ cache Redis"
		( echo "flushall" ) | redis-cli >/dev/null 2>&1
		_rundone "Xóa bộ nhớ cache Redis"
	fi
fi

pathcheckplugin="/usr/local/lsws/$NAME/html/wp-content/plugins/litespeed-cache"
if [[ $(echo $plugins_active | grep 'litespeed-cache') ]]; then
	_runing "xóa cache LiteSpeed cache"
	wp litespeed-purge all --path=$path2 --allow-root >/dev/null 2>&1
	_rundone "xóa cache LiteSpeed cache"

	if [[ -f /usr/local/lsws/$NAME/html/wp-content/object-cache.php ]];then
		if [[ $(cat /usr/local/lsws/$NAME/html/wp-content/object-cache.php | grep 'litespeed_conf') ]];then
			if [[ -f /etc/redis.conf || -f /etc/sysconfig/memcached || -d /usr/local/lsmcd ]];then
				_runing "Xóa Object Cache"
			wp eval 'LiteSpeed\Purge::purge_all_object();' --allow-root >/dev/null 2>&1 --path=$path2
				_rundone "Xóa Object Cache"
			fi
		fi
	fi
fi

# if [[ $(echo $plugins_active | grep 'swift-performance-lite') ]];then
# 		_runing "xóa cache swift preformance"
# 	wp sp_clear_all_cache --allow-root --path="$path2" >/dev/null 2>&1
# 		_rundone "xóa cache swift preformance"
# fi


if [[ $(echo $plugins_active | grep 'swift-performance') ]];then
	_runing "xóa cache swift preformance"
	wp sp_clear_all_cache --allow-root --path="$path2" >/dev/null 2>&1
	_rundone "xóa cache swift preformance"
fi

if [[ $(echo $plugins_active | grep 'wp-rocket') ]];then
	_runing "xóa cache wp rocket"
	wp eval 'rocket_clean_domain();' --allow-root --path="$path2" >/dev/null 2>&1
	_rundone "xóa cache wp rocket"
fi

if [[ $(echo $plugins_active | grep 'w3-total-cache') ]];then
	_runing "xóa cache w3-total-cache"
	wp eval 'w3tc_pgcache_flush();' --allow-root --path="$path2" >/dev/null 2>&1
	_rundone "xóa cache w3-total-cache"
fi


if [[ $(echo $plugins_active | grep 'cache-enabler') ]];then
	_runing "xóa cache cache-enabler"
	wp eval 'Cache_Enabler::clear_total_cache();' --allow-root --path="$path2" >/dev/null 2>&1
	_rundone "xóa cache cache-enabler"
fi


if [[ $(echo $plugins_active | grep 'autoptimize') ]];then
	_runing "xóa cache autoptimize"
	wp eval 'autoptimizeCache::clearall();' --allow-root --path="$path2" >/dev/null 2>&1
	_rundone "xóa cache autoptimize"
fi


if [[ $(echo $plugins_active | grep 'flying-press') ]];then
	_runing "xóa cache Flying Press"
	wp eval 'FlyingPress\Purge::purge_cached_pages();' --allow-root --path="$path2" >/dev/null 2>&1
	_runing "xóa cache Flying Press"
fi

if [[ $(echo $plugins_active | grep 'wp-optimize') ]];then
	_runing "xóa cache wp-optimize"
	wp eval '$wpoptimize_cache_commands = new WP_Optimize_Cache_Commands(); $wpoptimize_cache_commands->purge_page_cache();' --allow-root --path="$path2" >/dev/null 2>&1
	_rundone "xóa cache wp-optimize"
fi


if [[ $(echo $plugins_active | grep 'breeze') ]];then
	_runing "xóa cache breeze"
	wp eval "do_action('breeze_clear_all_cache');" --allow-root --path="$path2" >/dev/null 2>&1
	_rundone "xóa cache breeze"
fi

if [[ $(echo $plugins_active | grep 'flyingproxy') ]];then
	_runing "xóa cache flyingproxy"
	wp eval "FlyingProxy\Purge::invalidate();" --allow-root --path="$path2" >/dev/null 2>&1
	_rundone "xóa cache flyingproxy"
fi

if [[ $(echo $plugins_active | grep 'wp-fastest-cache') ]];then
		_runing "xóa cache wp-fastest-cache"
	wp fastest-cache clear all --allow-root --path="$path2" >/dev/null 2>&1
		_rundone "xóa cache wp-fastest-cache"
fi

if [[ $(echo $plugins_active | grep 'wp-performance') ]];then
		_runing "xóa cache WP Performance"
	wp wpp flush  --allow-root --path="$path2" >/dev/null 2>&1
		_rundone "xóa cache WP Performance"
fi

if [[ $(echo $plugins_active | grep 'wp-super-cache') ]];then
	_runing "xóa cache WP Super Cache"
	wp eval 'global $file_prefix, $supercachedir;if ( empty( $supercachedir ) && function_exists( "get_supercache_dir" ) ) {$supercachedir = get_supercache_dir();}wp_cache_clean_cache( $file_prefix );' --allow-root --path="$path2" >/dev/null 2>&1
	_rundone "xóa cache WP Super Cache"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-cache-main 1
fi

