#!/bin/bash
function huong_dan() {
  Việc thay đổi cổng [port] SSH mặc định [thường là cổng 22] là một trong những biện pháp bảo mật cơ bản và hiệu quả cho máy chủ Linux.

  Dưới đây là giới thiệu ngắn gọn về tính năng này:

  Tại sao cần thay đổi cổng SSH?
  * Giảm thiểu tấn công tự động [Automated Attacks]: Rất nhiều bot và script độc hại trên internet tự động quét cổng 22 để tìm kiếm các máy chủ SSH có mật khẩu yếu hoặc lỗ hổng đã biết. Việc đổi sang một cổng khác, ít phổ biến hơn, sẽ làm giảm đáng kể số lượng các cuộc tấn công tự động này.
  * Tăng cường bảo mật qua việc ẩn náu [Security through obscurity]: Mặc dù không phải là biện pháp bảo mật duy nhất và toàn diện, việc ẩn dịch vụ SSH trên một cổng không chuẩn sẽ khiến kẻ tấn công khó khăn hơn trong việc phát hiện và nhắm mục tiêu vào máy chủ của bạn.
  * Tránh xung đột cổng [Port Conflicts]: Trong một số trường hợp hiếm, cổng 22 có thể cần thiết cho một dịch vụ khác [mặc dù điều này không phổ biến].

  Lợi ích chính:
  * Giảm đáng kể log tấn công brute-force.
  * Làm cho máy chủ của bạn ít bị chú ý hơn.

  Đây là một bước đơn giản nhưng mang lại hiệu quả bảo mật đáng kể cho máy chủ của bạn.
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo "========================================================================="
echo "|$quan_ly_ssh => $thay_doi_port_ssh" |
  echo "========================================================================="

echo "Thiết lập thay đổi port SSH : $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

# kiểm tra port ssh
port_checkssh=$(cat /etc/ssh/sshd_config | grep "Port " | grep -o '[0-9]\+$' || echo 22)

port=$1 #xác định port đối số
if [[ $port = '98' ]]; then
  port=''
fi

if [[ -z $port ]]; then
  read -p "$nhap port SSH $ban_muon $thay_doi [0=$exit_thoat]: " port
  if [[ "$port" = "0" || "$port" = "" ]]; then
    . /etc/wptt/wptt-ssh-main 1
    exit
  fi
fi

if ! [[ $port =~ ^[0-9]+$ ]] || (($port < 1 || $port > 65536)); then
  clear
  echo "Port $khong_dung_dinh_dang $so_nguyen_duong, vui lòng nhập port từ 1 đến 65536"
  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    . /etc/wptt/wptt-ssh-main 1
  fi
  return 2>/dev/null
  exit
fi

#kiểm tra trung lặp port
if [[ "$port" = "$port_checkssh" || "$port" = "80" || "$port" = "443" ]]; then
  echo "Bạn vui lòng chọn port khác cổng port này đang được sử dụng bởi LiteSpeed Webserver"
  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    . /etc/wptt/wptt-ssh-main 1
  fi
  return 2>/dev/null
  exit
fi

# kiểm tra trùng lặp port webguiadmin
if [[ ! -f /usr/local/lsws/conf/disablewebconsole ]]; then
  port_webgui_openlitespeed=$(cat /usr/local/lsws/admin/conf/admin_config.conf | grep "address" | grep -o '[0-9]\+$')
  if [[ "$port" = "$port_webgui_openlitespeed" ]]; then
    echo "Bạn vui lòng chọn port khác cổng port này openlitespeed webgui đang sử dụng"
    check_menu_wptangtoc_active=$1
    if [[ $check_menu_wptangtoc_active = "98" ]]; then
      . /etc/wptt/wptt-ssh-main 1
    fi
    return 2>/dev/null
    exit
  fi
fi

#port remote database tránh trùng lặp
if $(cat /etc/*release | grep -q "Ubuntu"); then
  duong_dan_cau_hinh_mariadb="/etc/mysql/my.cnf"
else
  duong_dan_cau_hinh_mariadb="/etc/my.cnf.d/server.cnf"
fi

port_mariadb_remote=$(cat $duong_dan_cau_hinh_mariadb | grep 'port=' | grep -o '[0-9]\+$')
if [[ $port_mariadb_remote ]]; then
  if [ "$port" = "$port_mariadb_remote" ]; then
    echo "Bạn vui lòng chọn port khác cổng port này remote database đang sử dụng"
    echo "Vui lòng thiết lập lại và chọn cổng port khác"
    . /etc/wptt/wptt-ssh-main 1
    exit
  fi
fi

echo "$xac_nhan $thay_doi port SSH $port_checkssh => $port ? "
prompt="$nhap_lua_chon_cua_ban [1-2]: "
confirm=$1
options=("$dong_y" "$khong_dong_y")

PS3="$prompt"
select opt in "${options[@]}"; do
  case "$REPLY" in
  1)
    confirm="y"
    break
    ;;

  2)
    confirm="n"
    break
    ;;

  $((${#options[@]} + 1)))
    printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
    break
    ;;
  *)
    printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
    break
    ;;
  esac
done

. /etc/wptt/echo-color
if [ "$confirm" = "y" ]; then
  _runing "$thiet_lap $tuong_lua port SSH $moi [$port]"
  sed -i "/Port/d" /etc/ssh/sshd_config
  sed -i "1 i Port $port" /etc/ssh/sshd_config
  yum -y install policycoreutils-python >/dev/null 2>&1
  semanage port -a -t ssh_port_t -p tcp $port 2>/dev/null

  firewalld_service=$(systemctl status firewalld.service 2>/dev/null | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
  if [[ "$firewalld_service" = "active" ]]; then
    firewall-cmd --permanent --zone=public --add-port=$port/tcp >/dev/null 2>&1
    firewall-cmd --permanent --zone=public --remove-port=$port_checkssh/tcp >/dev/null 2>&1
    firewall-cmd --reload >/dev/null 2>&1
  fi
  systemctl reload sshd.service
  systemctl restart sshd.service

  cat >"/etc/fail2ban/jail.d/sshd.local" <<END
[sshd]
enabled = true
port = $port
#action = firewallcmd-ipset
logpath = %(sshd_log)s
maxretry = 5
bantime = 3600
END

  fail2ban-client reload

  #csf
  if [[ -f /etc/csf/csf.conf ]]; then
    if [[ $(cat /etc/csf/csf.conf | grep '^TCP_IN' | grep "$port,") = '' ]]; then
      #xoa port ssh cũ
      sed -i -r '/^TCP_IN /s/"'$port_checkssh'"/""/; s/([",])'$port_checkssh',|,'$port_checkssh'([,"])/\1\2/' /etc/csf/csf.conf

      #mo port ssh mới
      sed -i "s/^TCP_IN = \"/TCP_IN = \"$port,/g" /etc/csf/csf.conf

      csf -x >/dev/null 2>&1
      csf -e >/dev/null 2>&1
    fi
  fi

  nftables_service=$(systemctl status nftables.service 2>/dev/null | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
  if [[ "$nftables_service" = "active" ]]; then
    if $(cat /etc/*release | grep -q "Ubuntu"); then
      path_nftables_config="/etc/nftables.conf"
    else
      path_nftables_config="/etc/sysconfig/nftables.conf"
    fi

    if [[ -f $path_nftables_config ]]; then
      sed -i '/#port ssh/d' $path_nftables_config
      sed -i "/chain input /a\ \ tcp dport $port_checkssh accept #port ssh" $path_nftables_config
      systemctl restart nftables
    fi
  fi

  fail2ban-client reload >/dev/null 2>&1
  _rundone "$thiet_lap $tuong_lua port SSH $moi [$port]"
  _runing "$thay_doi port SSH $port_checkssh => $port"
  sed -i "/port_ssh=/d" /etc/wptt/.wptt.conf
  echo "port_ssh=$port" >>/etc/wptt/.wptt.conf
  _rundone "$thay_doi port SSH $port_checkssh => $port"
else
  clear
  check_menu_wptangtoc_active=$1
  if [[ $check_menu_wptangtoc_active = "98" ]]; then
    . /etc/wptt/wptt-ssh-main 1
  fi
  return 2>/dev/null
  exit
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-ssh-main 1
fi
