#!/bin/bash

clear
echo "/-----------------------------------------------------------------------/"
echo "Thay doi SSH/sFTP Password tai khoan Root"
echo "/-----------------------------------------------------------------------/"
echo "loi khuyen: hay dat password it nhat 26 ky tu de nang cao bao mat"
passwd
echo "Hoan tat"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-ssh-main 1
fi

