#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao lưu & khôi phục => Thiết lập tự động sao lưu website Telegram      |"
echo "========================================================================="
echo ""
echo ""
if [ "$(ls -A /etc/wptt/vhost|sort -uV)" ]; then
	echo "========================================================================="
	echo "Danh sách domain đã kích hoạt tự động backup website telegram:"
	echo "========================================================================="
	for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
		domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
		path="/etc/cron.d/backup$domain-telegram.cron"
		i=1
		if [[ -f "$path" ]]; then
			checkauto="Đã kích hoạt tự động lúc "
			checkauto1=$(cat /etc/cron.d/backup$domain-telegram.cron | cut -f2 -d " ")
			checkauto2=$(cat /etc/cron.d/backup$domain-telegram.cron | cut -f5 -d " ")
			tinhnang="Backup xong uploads lên telegram xoá file ở local"
			if [ "$checkauto2" = "0" ] || [ "$checkauto2" = "7" ]; then
				thu123=" giờ chủ nhật hàng tuần"
			fi
			if [ "$checkauto2" = "1" ]; then
				thu123=" giờ thứ hai hàng tuần"
			fi
			if [ "$checkauto2" = "2" ]; then
				thu123=" giờ thứ ba hàng tuần"
			fi
			if [ "$checkauto2" = "3" ]; then
				thu123=" giờ thứ tư hàng tuần"
			fi
			if [ "$checkauto2" = "4" ]; then
				thu123=" giờ thứ năm hàng tuần"
			fi
			if [ "$checkauto2" = "5" ]; then
				thu123=" giờ thứ sáu hàng tuần"
			fi
			if [ "$checkauto2" = "6" ]; then
				thu123=" giờ thứ bảy hàng tuần"
			fi

			if [ "$checkauto2" = "*" ]; then
				thu123=" giờ hàng ngày"
			fi

		else

			checkauto="Chưa được kích hoạt"
			checkauto1=""
			checkauto2=""
			thu123=" tự động sao lưu backup website"
			tinhnang=""
		fi
		echo "Website $domain $checkauto$checkauto1$thu123 $tinhnang"
	done
	echo "========================================================================="
	echo
fi

. /etc/wptt/.wptt.conf

function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ -f /etc/cron.d/backup$NAME-telegram.cron ]]; then
				selects+=("$NAME")
			fi
		done

if [[ $selects = '' ]];then
echo "Tất cả domain trên hệ thống chưa có domain nào được kích hoạt sao lưu backup website tự động"
. /etc/wptt/wptt-add-one-main 1
fi

		PS3="
-//- Nhập lựa chọn website của bạn [0=Thoát]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Không xác định được domain nào."
		exit
	fi
}

echo ""
echo ""
echo "Lựa chọn website bạn muốn huỷ thiết lập tự động backup sao lưu website uploads lên telegram: "
echo ""
lua_chon_NAME


. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt/wptt-add-one-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
	. /etc/wptt/wptt-add-one-main 1
    exit
fi


if [ -f /etc/cron.d/backup"$NAME"-telegram.cron ]; then
	_runing "Tắt tự động sao lưu website $NAME uploads lên telegram"
	rm -f /etc/cron.d/backup"$NAME"-telegram.cron
	rm -f /etc/wptt-auto/$NAME-auto-backup-telegram
	if $(cat /etc/*release | grep -q "Ubuntu") ; then
		NAME_CRON_ubuntu=${NAME//[.]/_}
		rm -f /etc/cron.d/backup${NAME_CRON_ubuntu}-telegram_cron
		systemctl restart cron.service
	else
		systemctl restart crond.service
	fi

	echo "Tắt tự động sao lưu website $NAME uploads lên telegram: $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

	_rundone "Tắt tự động sao lưu website $NAME uploads lên telegram"
else
	echo "Bạn chưa kích hoạt tự động sao lưu tự động"
	. /etc/wptt/wptt-add-one-main 1
fi



check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-add-one-main 1
fi


