#!/bin/bash

function huong_dan(){
Tính năng thông báo sắp hết hạn SSL là một công cụ tự động giám sát và cảnh báo cho bạn khi chứng chỉ SSL/TLS của website sắp hết hiệu lực.

Giới thiệu ngắn gọn:
Mục đích: Đảm bảo website luôn được bảo vệ bởi HTTPS, tránh gián đoạn truy cập, mất lòng tin từ người dùng và các cảnh báo bảo mật từ trình duyệt do SSL hết hạn.
Cách hoạt động: Hệ thống sẽ định kỳ kiểm tra ngày hết hạn của chứng chỉ SSL được cài đặt trên tên miền của bạn.

Cảnh báo sớm: Khi chứng chỉ sắp đến ngày hết hạn [ví dụ: còn 30 ngày, 14 ngày, 7 ngày], hệ thống sẽ tự động gửi thông báo cho bạn qua các kênh như:
Thông báo trong ứng dụng telegram

Lợi ích: Giúp bạn chủ động gia hạn hoặc thay thế chứng chỉ SSL kịp thời, duy trì tính bảo mật và uy tín cho website.
}


. /etc/wptt/echo-color
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

if [[ ! -f /etc/wptt/add-one/check-ssl-han-su-dung.sh ]];then
	echo "Tính năng này là tính năng Premium bạn phải mua Active key mới có thể sử dụng được"
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-add-one-main 1
	fi
	exit;
fi
if [[ "$telegram_api" = "" || "$telegram_id" = "" ]]; then
	clear
	echo "Vui lòng vào quản lý Telegram để cài đặt trước khi sử dụng tính năng này."
	sleep 3
	. /etc/wptt/bao-mat/wptt-telegram 1998
fi
if [[ ! -f /etc/cron.d/check-ssl-han-su-dung-wptangtoc.crond ]];then
	echo -e "$xac_nhan bật check hạn SSL?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done

	if [[ "$dongy" = 'y' ]]; then
		_runing "Thiết lập cảnh báo sắp hết hạn SSL cho các website"
		. /etc/wptt/.wptt.conf

cat >"/etc/cron.d/check-ssl-han-su-dung-wptangtoc.crond" <<END
0 8 * * * root /bin/bash /etc/wptt/add-one/check-ssl-han-su-dung.sh >/dev/null 2>&1
END

		if $(cat /etc/*release | grep -q "Ubuntu") ; then
					   ln -sf /etc/cron.d/check-ssl-han-su-dung-wptangtoc.crond /etc/cron.d/check-ssl-han-su-dung-wptangtoc_crond
					   systemctl restart cron.service
				   else
					   systemctl restart crond.service
		fi

		_rundone "Thiết lập cảnh báo sắp hết hạn SSL cho các website"
		echo "Tính năng này sẽ kiểm tra từng website"
		echo "Sẽ kiểm tra mỗi ngày, nếu website nào SSL hạn sử dụng còn dưới 7 ngày sẽ thông báo"
	fi
else
	echo -e "$xac_nhan huỷ check hạn ssl ?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done

	if [[ "$dongy" = 'y' ]]; then
			_runing "Huỷ Thiết lập cảnh báo hết hạn SSL website"
			rm -f /etc/cron.d/check-ssl-han-su-dung-wptangtoc.crond

		if $(cat /etc/*release | grep -q "Ubuntu") ; then
				   rm -f /etc/cron.d/check-ssl-han-su-dung-wptangtoc_crond
					   systemctl restart cron.service
				   else
					   systemctl restart crond.service
		fi

			_rundone "Huỷ Thiết lập cảnh báo hết hạn SSL website"
	fi
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-add-one-main 1
fi


