#!/bin/bash
. /etc/wptt/echo-color
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

if [[ ! -f /etc/wptt/add-one/check.sh ]];then
	echo "Tính năng này là tính năng Premium bạn phải mua Active key mới có thể sử dụng được"
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-add-one-main 1
	fi
	exit;
fi
if [[ "$telegram_api" = "" || "$telegram_id" = "" ]]; then
	clear
	echo "Vui lòng vào quản lý Telegram để cài đặt trước khi sử dụng tính năng này."
	sleep 3
	. /etc/wptt/bao-mat/wptt-telegram 1998
fi
if [[ $download_api = '' ]];then
	echo -e "$xac_nhan bật check Downtime API WPTangToc OLS ?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done

	if [[ "$dongy" = 'y' ]]; then
		_runing "Thiết lập cảnh báo downtime website"
		. /etc/wptt/add-one/check.sh $telegram_id $telegram_api >/dev/null 2>&1
		sed -i '/download_api/d' /etc/wptt/.wptt.conf
		echo "download_api=1" >> /etc/wptt/.wptt.conf
		_rundone "Thiết lập cảnh báo downtime website"
		echo "Tính năng này sẽ sử dụng API của WPTangToc OLS sẽ kiểm tra 1 phút / 1 lần website"
		echo "Nếu có sự kiện Downtime sẽ thống báo với bạn qua telegram"
	fi
else
	echo -e "$xac_nhan huỷ check Downtime API WPTangToc OLS ?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done

	if [[ "$dongy" = 'y' ]]; then
			_runing "Huỷ Thiết lập cảnh báo downtime website"
		sed -i '/download_api/d' /etc/wptt/.wptt.conf
		. /etc/wptt/add-one/huy-checkdowntime.sh >/dev/null 2>&1
			_rundone "Huỷ Thiết lập cảnh báo downtime website"
	fi
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-add-one-main 1
fi

