#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Database => Xem thong tin tai khoan database                   |"
echo "========================================================================="
echo ""
echo ""
if [ "$(ls -A /etc/wptt/vhost)" ]; then
echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1
    if [[ -d "$path" ]]; then
         . /etc/wptt/vhost/.$domain.conf && echo "website: $domain" && echo "Database Name: $DB_Name_web" && echo "Username database: $DB_User_web" && echo "Password database: $DB_Password_web" && echo "--------------------------------------------------" && echo ""
    fi
  done
fi