#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly WordPress => Chuyen doi database myisam to innodb              |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website muon chuyen myisam to innodb: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color
pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-wordpress-main
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "He thong xac nhan ban chua kich hoat su dung WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main
  exit
fi


cd /usr/local/lsws/"$NAME"/html
WPTABLES=($(wp db query "SHOW TABLE STATUS WHERE Engine = 'MyISAM'" --allow-root --silent --skip-column-names | awk '{ print $1}'))
for WPTABLE in ${WPTABLES[@]}; do
    echo "Dang chuyen ${WPTABLE} sang InnoDB"
    wp db query "ALTER TABLE ${WPTABLE} ENGINE=InnoDB" --allow-root --path=/usr/local/lsws/"$NAME"/html
    echo "Da chuyen xong ${WPTABLE} sang InnoDB"
done

echo "Hoan tat qua trinh chuyen doi cho website $NAME tu Myisam sang InnoDB"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-db-main 1
fi

