#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý WordPress => Chuyển đổi database innodb to MyISAM              |"
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website muốn chuyển innodb to MyISAM: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-wordpress-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-wordpress-main 1
    exit
fi

pathcheckwp="/usr/local/lsws/$NAME/html/wp-load.php"
if [[ ! -f "$pathcheckwp" ]]; then
  clear
  echoDo "Hệ thống xác nhận bạn không sử dụng WordPress"
  echoDo "Tính năng này chỉcó thể hoạt động trên WordPress"
  sleep 3
  . /etc/wptt/wptt-wordpress-main 1
  exit
fi



_runing "Chuyển InnoDB sang MyISAM cho website $NAME"
cd /usr/local/lsws/"$NAME"/html
WPTABLES=($(wp db query "SHOW TABLE STATUS WHERE Engine = 'InnoDB'" --allow-root --silent --skip-column-names 2>/dev/null | awk '{ print $1}'))
for WPTABLE in ${WPTABLES[@]}; do
    wp db query "ALTER TABLE ${WPTABLE} ENGINE=MyISAM" --allow-root --path=/usr/local/lsws/"$NAME"/html 2>/dev/null
done
_rundone "Chuyển InnoDB sang MyISAM cho website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-db-main 1
fi

