#!/bin/bash
exit
db_root_password=$(
  date +%s | sha256sum | base64 | head -c 32
  echo
)

mysql <<EOF
use mysql;
FLUSH PRIVILEGES;
DROP USER IF EXISTS 'wordpressadmin'@'localhost';
CREATE USER IF NOT EXISTS 'wordpressadmin'@'localhost' IDENTIFIED BY '$db_root_password';
GRANT ALL PRIVILEGES ON *.* TO 'wordpressadmin'@'localhost' WITH GRANT OPTION;
DROP USER IF EXISTS 'root'@'localhost';
FLUSH PRIVILEGES;
EOF

database_admin_password=$db_root_password
database_admin_username='wordpressadmin'

sed -i 'database_admin_password' /etc/wptt/.wptt.conf
echo "database_admin_password=$db_root_password" >>/etc/wptt/.wptt.conf

TEMP_CNF_ROOT=$(mktemp)
chmod 600 "$TEMP_CNF_ROOT" # Chỉ root mới đọc được
cat >"$TEMP_CNF_ROOT" <<EOF
[client]
user=${database_admin_username}
password=${database_admin_password}
host=localhost
max_allowed_packet=1G
default-character-set=utf8mb4

[mysqldump]
quick
quote-names
max_allowed_packet=1G
EOF

. /etc/wptt/echo-color
if [ "$(ls -A /etc/wptt/vhost | grep -v '^\.\.conf$' | sort -uV)" ]; then
  for entry in $(ls -A /etc/wptt/vhost | sort -uV); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path_html="/usr/local/lsws/$domain/html"
    i=1
    if [[ -d "$path_html" ]]; then
      _runing "Thiết lập lại user db $domain"
      . /etc/wptt/vhost/.$domain.conf
      mariadb --defaults-extra-file="$TEMP_CNF_ROOT" -e "DROP USER IF EXISTS '${DB_User_web}'@'localhost'"
      mariadb --defaults-extra-file="$TEMP_CNF_ROOT" -e "CREATE USER IF NOT EXISTS '${DB_User_web}'@'localhost' IDENTIFIED BY '${DB_Password_web}'"
      mariadb --defaults-extra-file="$TEMP_CNF_ROOT" -e "GRANT ALL PRIVILEGES ON ${DB_Name_web}.* TO '${DB_User_web}'@'localhost' WITH GRANT OPTION"
      mariadb --defaults-extra-file="$TEMP_CNF_ROOT" -e "FLUSH PRIVILEGES"
      _rundone "Thiết lập lại user db $domain"
    fi
  done
fi

rm -rf $TEMP_CNF_ROOT
