#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Database => Kết nối database với WordPress (wp-config.php)     |"
echo "========================================================================="
. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color

NAME=$1
if [[ $NAME = '98' ]];then
NAME=''
fi

if [[ $NAME = '' ]];then
. /etc/wptt/tenmien-them-lua-chon-tat-ca-website-by-wordpress
echo ""
echo ""
echo "$nhap_lua_chon_website_cua_ban Kết nối database với WordPress (wp-config.php): "
echo ""
lua_chon_NAME
fi

if [[ $NAME = 'Tất cả website' ]];then
	if [ "$(ls -A /etc/wptt/vhost)" ]; then
		for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path="/usr/local/lsws/$domain/html/wp-config.php"
			path_html="/usr/local/lsws/$domain/html"
			i=1
			if [[ -f "$path" ]]; then
				. /etc/wptt/vhost/."$domain".conf
				_runing "Thiết lập kết nối database với WordPress website $domain"
				. /etc/wptt/db/wptt-ket-noi $domain >/dev/null 2>&1
				_rundone "Thiết lập kết nối database với WordPress website $domain"
			fi
		done
	fi
	/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-db-main 1
	fi
	exit
fi

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
   	. /etc/wptt/wptt-db-main 1
fi

if [[ ! -f /etc/wptt/vhost/."$NAME".conf ]];then
   	. /etc/wptt/wptt-db-main 1
fi

. /etc/wptt/vhost/."$NAME".conf

_runing "Thiết lập kết nối database với WordPress"
if [[ ! -f "/usr/local/lsws/$NAME/html/wp-config.php" ]]; then
	_runloi "Thiết lập kết nối database với WordPress"
	echo "Không xác định được file wp-config.php"
	echo "Vui lòng kiểm tra lại mã nguồn của bạn"
	exit
fi

wp_config_php_path="/usr/local/lsws/$NAME/html/wp-config.php"

if [[ $lock_down ]];then
	chattr -i $wp_config_php_path
fi

sed -i "/DB_NAME/s/\"/'/g" "$wp_config_php_path"
sed -i "/DB_HOST/s/\"/'/g" "$wp_config_php_path"
sed -i "/DB_USER/s/\"/'/g" "$wp_config_php_path"
sed -i "/DB_PASSWORD/s/\"/'/g" "$wp_config_php_path"

sed -i "/DB_HOST/s/'[^']*'/'localhost'/2" "$wp_config_php_path"
sed -i "/DB_NAME/s/'[^']*'/'$DB_Name_web'/2" "$wp_config_php_path"
sed -i "/DB_USER/s/'[^']*'/'$DB_User_web'/2" "$wp_config_php_path"
sed -i "/DB_PASSWORD/s/'[^']*'/'$DB_Password_web'/2" "$wp_config_php_path"

#kết nối subfolder
if [[ -d /etc/wptt/$NAME-wptt ]];then
	for entry in $(ls -A /etc/wptt/$NAME-wptt); do
		subfolder=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
		. /etc/wptt/$NAME-wptt/.${subfolder}.conf
		subfolder_path=$(echo $entry | sed 's/^.//' | sed 's/.conf//'| sed 's/__/ /g' | cut -f2 -d ' ')
		wp_config_php_path="/usr/local/lsws/$NAME/html/$subfolder_path/wp-config.php"
		if [[ -f $wp_config_php_path ]];then
			sed -i "/DB_NAME/s/\"/'/g" "$wp_config_php_path"
			sed -i "/DB_HOST/s/\"/'/g" "$wp_config_php_path"
			sed -i "/DB_USER/s/\"/'/g" "$wp_config_php_path"
			sed -i "/DB_PASSWORD/s/\"/'/g" "$wp_config_php_path"

			sed -i "/DB_HOST/s/'[^']*'/'localhost'/2" "$wp_config_php_path"
			sed -i "/DB_NAME/s/'[^']*'/'$DB_Name_web'/2" "$wp_config_php_path"
			sed -i "/DB_USER/s/'[^']*'/'$DB_User_web'/2" "$wp_config_php_path"
			sed -i "/DB_PASSWORD/s/'[^']*'/'$DB_Password_web'/2" "$wp_config_php_path"
		fi
	done

	co_ket_noi_subfolder=1
fi

wp rewrite flush --allow-root --path=/usr/local/lsws/"$NAME"/html >/dev/null 2>&1

if [[ $lock_down ]];then
	chattr +i $wp_config_php_path
fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1

_rundone "Thiết lập kết nối database với WordPress"

echo "========================================================================="
echo "Database của website	: $NAME"
if [[ $co_ket_noi_subfolder = ''  ]];then
echo "Database NAME		: $DB_Name_web"
echo "USER NAME			: $DB_User_web"
echo "DB PASSWORD 		: $DB_Password_web"
fi
echo "========================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-db-main 1
fi

