#!/bin/bash
. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_database => $bat_tat_tu_dong_auto_restart_mariadb  			  |"
echo "========================================================================="
echo "/-----------------------------------------------------------------------/"
if [[ -f /etc/cron.d/auto-restart-mariadb.cron ]]; then
	echo "Trạng thái: đã được kích hoạt"
else
	echo "Trạng thái: chưa được kích hoạt"
fi
echo "/-----------------------------------------------------------------------/"


. /etc/wptt/echo-color

if [[ -f /etc/cron.d/auto-restart-mariadb.cron ]]; then
	echo "Bạn có muốn tắt tự động restart?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done

	if [[ "$dongy" = "y" ]]; then
		_runing "Tắt auto restart MariaDB"
		echo "Tắt tự động auto restart mariadb khi sập serivce : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log
		rm -f /etc/cron.d/auto-restart-mariadb.cron
		if $(cat /etc/*release | grep -q "Ubuntu") ; then
			rm -f /etc/cron.d/auto-restart-mariadb_cron
			systemctl restart cron.service
		else
			systemctl restart crond.service
		fi

		_rundone "Tắt auto restart MariaDB"
	fi
else
	echo "Bạn có muốn bật tự động restart?: "
	prompt="$nhap_lua_chon_cua_ban [1-2]: "
	dongy="n"
	options=("$dong_y" "$khong_dong_y")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				dongy="y"
				break
				;;

			2)
				dongy="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\n$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
			*)
				printf "$ban_nhap_sai_he_thong_se_chon_khong_dong_y\n"
				break
				;;
		esac
	done

	if [[ "$dongy" = "y" ]]; then
echo "Bật tự động auto restart mariadb khi sập serivce : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log
_runing "Bật auto restart MariaDB"
cat >"/etc/cron.d/auto-restart-mariadb.cron" <<END
*/5 * * * * root /etc/wptt/db/restart-auto-mariadb.sh >/dev/null 2>&1
END
if $(cat /etc/*release | grep -q "Ubuntu") ; then
	ln -sf /etc/cron.d/auto-restart-mariadb.cron /etc/cron.d/auto-restart-mariadb_cron
	systemctl restart cron.service
else
	systemctl restart crond.service
fi

echo "-------------------------------------------------------------------------"
echo "Hoàn tất kích hoạt tự động auto restart MariaDB0"
echo "Hệ thống sẽ tự động kiểm tra cứ 5 phút 1 lần, nếu MariaDB bị sập sẽ tự động restart"
echo "-------------------------------------------------------------------------"
_rundone "Bật auto restart MariaDB"
	fi
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-db-main 1
fi

