#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2022

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Database => Đổi PassWord Database                              |"
echo "========================================================================="

. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
echo ""
echo ""
echo "Nhập tên website bạn muốn thay đổi PassWord Database: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-db-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-db-main 1
    exit
fi


. /etc/wptt/vhost/.$NAME.conf

# userdb=$(echo $DB_User_web)

if [ "$DB_User_web" = "$database_admin_username" ]; then
    clear
    echo "Tài khoản ROOT database không thể đổi Password."
    sleep 4
    . /etc/wptt/wptt-db-main 1
    exit
fi


password=$(
  date +%s | sha256sum | base64 | head -c 36
  echo
)

read -p "Xác nhận thay đổi PassWord Database? (y/n): " dongy
if [[ "$dongy" = "y" ]]; then
    echo "PassWord của bạn tự động là $password"
    echo "Đang tiến hành thay đổi password database cho website $NAME..."
    mysql -u "$database_admin_username" -p"$database_admin_password" -e "SET PASSWORD FOR '$DB_User_web'@'localhost' = PASSWORD('${password}')"

	# if ! [[ $(cat /etc/my.cnf.d/server.cnf | grep '#bind-address') ]];then
    # mysql -u "$database_admin_username" -p"$database_admin_password" -e "SET PASSWORD FOR '$DB_User_web'@'%' = PASSWORD('${password}')"
	# fi

	check_remote=$(mysql -u "$database_admin_username" -p"$database_admin_password" -e "SHOW GRANTS FOR '$DB_User_web'@'%';" 2>/dev/null)
	if [[ $check_remote ]];then
    mysql -u "$database_admin_username" -p"$database_admin_password" -e "SET PASSWORD FOR '$DB_User_web'@'%' = PASSWORD('${password}')"
	fi


	mysql -u "$database_admin_username" -p"$database_admin_password" -e "FLUSH PRIVILEGES"

    sed -i "/DB_Password_web/d" /etc/wptt/vhost/."$NAME".conf
    echo "DB_Password_web=$password" >>/etc/wptt/vhost/."$NAME".conf
systemctl restart mariadb.service >/dev/null 2>&1
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
    echo "==================================================================="
    echo "Thay đổi Password Database thành công"
    checkplugin="/usr/local/lsws/$NAME/html/wp-config.php"
    if [[ -f "$checkplugin" ]]; then
        sed -i "/DB_PASSWORD/s/'[^']*'/'$password'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
        echo "Đã tự động config chuyển đổi password database mới cho file wp-config.php cho website $NAME"
    else
        echo "Xác nhận chưa thể config Password database vào file wp-config.php cho website $NAME"
    fi
    echo "==================================================================="
    echo "database_name           : $DB_Name_web"
    echo "database_user           : $DB_User_web"
    echo "database_password       : $password"
    echo "==================================================================="
    echo "Cong cu phat trien boi	: Gia Tuan"
    echo "Yeu Cau Ho tro		: wptangtoc.com/lien-he"
    echo "Tai tro phat trien	: wptangtoc.com/donate"
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-db-main 1
fi

