#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025


function huong_dan(){
Tính năng Thay đổi password database là quá trình cập nhật mật khẩu cho một tài khoản người dùng [username] cụ thể đã được tạo để truy cập và tương tác với cơ sở dữ liệu [database] trên máy chủ MariaDB.

Nói một cách đơn giản, đây là cách bạn đổi chìa khóa và ổ khoá cho một người gác cổng [user] của kho chứa dữ liệu [database] của bạn.

Mục Đích Chính
* Tăng cường bảo mật [quan trọng nhất]:
* Thay đổi mật khẩu định kỳ là một thói quen tốt.
* Cần đổi ngay nếu nghi ngờ mật khẩu cũ đã bị lộ.
* Khi nhân viên/người quản lý cũ nghỉ việc: Đổi mật khẩu của user mà họ sử dụng.
* Sau khi thiết lập ban đầu: Đặt một mật khẩu mạnh hơn cho user sau khi tạo.
* Tuân thủ chính sách mật khẩu: Đảm bảo mật khẩu đủ mạnh và phức tạp theo quy định.

}


echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Database => Đổi PassWord Database                              |"
echo "========================================================================="

. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
echo ""
echo ""
echo "Nhập tên website bạn muốn thay đổi PassWord Database: "
echo ""
lua_chon_NAME

. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-db-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-db-main 1
    exit
fi


. /etc/wptt/vhost/.$NAME.conf

# userdb=$(echo $DB_User_web)

if [ "$DB_User_web" = "$database_admin_username" ]; then
    clear
    echo "Tài khoản ROOT database không thể đổi Password."
    sleep 4
    . /etc/wptt/wptt-db-main 1
    exit
fi

echo "Thay đổi password Database website $NAME : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

password=$(
  date +%s | sha256sum | base64 | head -c 36
  echo
)

read -p "Xác nhận thay đổi PassWord Database? (y/n): " dongy
if [[ "$dongy" = "y" ]]; then
    echo "PassWord của bạn tự động là $password"
    echo "Đang tiến hành thay đổi password database cho website $NAME..."
    mariadb -u "$database_admin_username" -p"$database_admin_password" -e "SET PASSWORD FOR '$DB_User_web'@'localhost' = PASSWORD('${password}')"

	# if ! [[ $(cat /etc/my.cnf.d/server.cnf | grep '#bind-address') ]];then
    # mariadb -u "$database_admin_username" -p"$database_admin_password" -e "SET PASSWORD FOR '$DB_User_web'@'%' = PASSWORD('${password}')"
	# fi

	check_remote=$(mariadb -u "$database_admin_username" -p"$database_admin_password" -e "SHOW GRANTS FOR '$DB_User_web'@'%';" 2>/dev/null)
	if [[ $check_remote ]];then
    mariadb -u "$database_admin_username" -p"$database_admin_password" -e "SET PASSWORD FOR '$DB_User_web'@'%' = PASSWORD('${password}')"
	fi


	mariadb -u "$database_admin_username" -p"$database_admin_password" -e "FLUSH PRIVILEGES"

    sed -i "/DB_Password_web/d" /etc/wptt/vhost/."$NAME".conf
    echo "DB_Password_web=$password" >>/etc/wptt/vhost/."$NAME".conf
systemctl restart mariadb.service >/dev/null 2>&1
/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
    echo "==================================================================="
    echo "Thay đổi Password Database thành công"
    checkplugin="/usr/local/lsws/$NAME/html/wp-config.php"
    if [[ -f "$checkplugin" ]]; then
        sed -i "/DB_PASSWORD/s/'[^']*'/'$password'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
        echo "Đã tự động config chuyển đổi password database mới cho file wp-config.php cho website $NAME"
    else
        echo "Xác nhận chưa thể config Password database vào file wp-config.php cho website $NAME"
    fi
    echo "==================================================================="
    echo "database_name           : $DB_Name_web"
    echo "database_user           : $DB_User_web"
    echo "database_password       : $password"
    echo "==================================================================="
    echo "Cong cu phat trien boi	: Gia Tuan"
    echo "Yeu Cau Ho tro		: wptangtoc.com/lien-he"
    echo "Tai tro phat trien	: wptangtoc.com/donate"
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-db-main 1
fi

