#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]];then
echo "========================================================================="
echo "|Quản lý sao lưu và khôi phục => Khôi phục Database                                   |"
echo "========================================================================="
else
echo "========================================================================="
echo "|Quản lý Database => Khôi phục Database                                   |"
echo "========================================================================="
fi

. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
. /etc/wptt/echo-color

echo ""
echo ""
echo "Lựa chọn website bạn muốn khôi phục database:"
echo ""
lua_chon_NAME

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt/wptt-db-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
	. /etc/wptt/wptt-db-main 1
    exit
fi

echo "========================================================================="
echo "Hướng dẫn: Bạn hãy uploads database vào thư mục /usr/local/backup-website/$NAME"
echo "========================================================================="

if [[ $sql_gz = '' ]];then

if [ ! $(ls -A /usr/local/backup-website/$NAME | grep ".sql$") ]; then
	clear
	echoDo "Không có file backup database (dinh dang .sql) nào tồn tại."
	echoDo "Vui lòng uploads file backup database dinh dang .sql của bạn vào: /usr/local/backup-website/$NAME/"
	echo
fi


b=1
for entry in $(ls -At /usr/local/backup-website/$NAME | grep ".sql$"); do
b=$((b+1));
done
echo "========================================================================="
echo "So luong file backup Database cua website $NAME: $((b-1))"
echo "========================================================================="


selects=()
for entry in $(ls -At /usr/local/backup-website/$NAME | grep ".sql$"); do
	selects+=("$entry")
done

PS3="
-//- Nhap lua chon cua ban [0=Thoat]: "
select select in ${selects[@]}; do
	file=$select
	break
done
fi

if [[ $sql_gz ]];then
if [ ! $(ls -A /usr/local/backup-website/$NAME | grep ".sql.gz$") ]; then
	clear
	echoDo "Không có file backup database (dinh dang .sql.gz) nào tồn tại."
	echoDo "Vui lòng uploads file backup database dinh dang .sql.gz của bạn vào: /usr/local/backup-website/$NAME/"
	echo
fi


b=1
for entry in $(ls -At /usr/local/backup-website/$NAME | grep ".sql.gz$"); do
b=$((b+1));
done
echo "========================================================================="
echo "So luong file backup Database cua website $NAME: $((b-1))"
echo "========================================================================="


selects=()
for entry in $(ls -At /usr/local/backup-website/$NAME | grep ".sql.gz$"); do
	selects+=("$entry")
done

PS3="
-//- Nhap lua chon cua ban [0=Thoat]: "
select select in ${selects[@]}; do
	file=$select
	break
done
fi


if [[ "$file" = "0" ]]; then
	clear
	. /etc/wptt/wptt-db-main 1
	exit
fi

if [[ $sql_gz ]];then
if [[ "$file" = "" ]]; then
	clear
	echoDo "Khong co file backup database nao ton tai trong thu muc /usr/local/backup-website/$NAME"
	echo "Ban hay upload database .sql.gz vao thu muc /usr/local/backup-website/$NAME"
	sleep 3
	. /etc/wptt/wptt-db-main 1
fi
fi

if [[ $sql_gz = '' ]];then
if [[ "$file" = "" ]]; then
	clear
	echoDo "Khong co file backup database nao ton tai trong thu muc /usr/local/backup-website/$NAME"
	echo "Ban hay upload database .sql vao thu muc /usr/local/backup-website/$NAME"
	sleep 3
	. /etc/wptt/wptt-db-main 1
fi
fi


duong_dan_thu_muc="/usr/local/backup-website/$NAME/$file"


check_file_error=$(du -c $duong_dan_thu_muc | awk '{print $1}' | sed '1d')
if (( $check_file_error < 10 ));then
echo "$file bi loi khong the su dung de khoi phuc database"
echo "Vui long lua chon file database backup khac"
exit
fi

. /etc/wptt/vhost/."$NAME".conf
read -p "Bạn có muốn nhập $file vào database website $NAME? (y/n): " dongy

if [[ "$dongy" = "y" ]]; then
	_runing "Làm sạch toàn bộ dữ liệu database của $NAME"
	mysql -u "$database_admin_username" -p"$database_admin_password" -e "DROP DATABASE $DB_Name_web"
	mysql -u "$database_admin_username" -p"$database_admin_password" -e "CREATE DATABASE IF NOT EXISTS $DB_Name_web"
	_rundone "Làm sạch toàn bộ dữ liệu database của $NAME"

	if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
		sed -i "/DB_HOST/s/'[^']*'/'localhost'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
		sed -i "/DB_NAME/s/'[^']*'/'$DB_Name_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
		sed -i "/DB_USER/s/'[^']*'/'$DB_User_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
		sed -i "/DB_PASSWORD/s/'[^']*'/'$DB_Password_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
	fi
else
	. /etc/wptt/wptt-db-main
	exit
fi

_runing "Khôi phục database website $NAME"
if [[ $sql_gz = '' ]];then
mysql -u "$database_admin_username" -p"$database_admin_password" "$DB_Name_web" <$duong_dan_thu_muc
fi

if [[ $sql_gz ]];then
zcat $duong_dan_thu_muc | mysql -u "$database_admin_username" -p"$database_admin_password" "$DB_Name_web"
fi

_rundone "Khôi phục database website $NAME"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-db-main 1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]];then
. /etc/wptt/wptt-backup-restore-main 1
fi
