#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2026

. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
echo ""
echo ""
echo "Nhập tên website bạn muốn tái tạo tài khoản database: "
echo ""
lua_chon_NAME

. /etc/wptt/vhost/."$NAME".conf

selects=()
for entry in $(find /var/lib/mysql -maxdepth 1 -type d | sed 's#/var/lib/mysql/##g' | sed '/^test$/d' | sed '/^mysql$/d' | sed '/^performance_schema$/d' | sed '/\//d'); do
  selects+=("$entry")
done

PS3="
-//- Nhập lựa chọn database của bạn [0=Thoát]: "
select select in "${selects[@]}"; do
  database=$select
  break
done

password_database_root=$(wptt_giai_ma "$database_admin_password" 2>/dev/null)
[[ -z "$password_database_root" ]] && password_database_root="$database_admin_password" #không mã hoá trả tuơng thích nguợc

TEMP_CNF_ROOT=$(mktemp -p "/etc/wptt/tmp" wptt_db_XXXXXX.cnf)
chmod 600 "$TEMP_CNF_ROOT"
cat >"$TEMP_CNF_ROOT" <<EOF
[client]
user=${database_admin_username}
password=${password_database_root}
host=localhost
max_allowed_packet=1G
default-character-set=utf8mb4

[mysqldump]
quick
quote-names
max_allowed_packet=1G
EOF

trap "rm -f $TEMP_CNF_ROOT" EXIT

password_database_website_giai_ma=$(wptt_giai_ma "$DB_Password_web" 2>/dev/null)
[[ -z "$password_database_website_giai_ma" ]] && password_database_website_giai_ma="$DB_Password_web"

mariadb --defaults-extra-file="$TEMP_CNF_ROOT" -e "DROP USER IF EXISTS '${DB_User_web}'@'localhost'"
mariadb --defaults-extra-file="$TEMP_CNF_ROOT" -e "CREATE USER IF NOT EXISTS '${DB_User_web}'@'localhost' IDENTIFIED BY '${password_database_website_giai_ma}'"
mariadb --defaults-extra-file="$TEMP_CNF_ROOT" -e "GRANT ALL PRIVILEGES ON ${database}.* TO '${DB_User_web}'@'localhost' WITH GRANT OPTION"
mariadb --defaults-extra-file="$TEMP_CNF_ROOT" -e "FLUSH PRIVILEGES"

rm -rf "$TEMP_CNF_ROOT"

sed -i '/DB_Name_web/d' /etc/wptt/vhost/."$NAME".conf
echo "DB_Name_web=$database" >>/etc/wptt/vhost/."$NAME".conf

if [[ -f "/usr/local/lsws/$NAME/html/wp-config.php" ]]; then
  wp config set DB_HOST 'localhost' --type=constant --allow-root --path="/usr/local/lsws/$NAME/html" --quiet

  # Cấu hình DB Name
  wp config set DB_NAME "$database" --type=constant --allow-root --path="/usr/local/lsws/$NAME/html" --quiet

  # Cấu hình DB User
  wp config set DB_USER "$DB_User_web" --type=constant --allow-root --path="/usr/local/lsws/$NAME/html" --quiet

  # Cấu hình DB Password
  wp config set DB_PASSWORD "$DB_Password_web" --type=constant --allow-root --path="/usr/local/lsws/$NAME/html" --quiet
fi

echo "Hoàn tất gắn lại quyền $database cho user $DB_User_web cho website $NAME"
