#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Database => Bật Remote Database                                |"
echo "========================================================================="
. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
. /etc/wptt/echo-color

echo ""
echo ""
echo "Lựa chọn website muốn Remote Database: "
echo ""
lua_chon_NAME

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt/wptt-db-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
	clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
	sleep 3
	. /etc/wptt/wptt-db-main 1
	exit
fi

. /etc/wptt/vhost/.$NAME.conf

check_remote=$(mysql -u "$database_admin_username" -p"$database_admin_password" -e "SHOW GRANTS FOR '$DB_User_web'@'%';" 2>/dev/null)
if [[ $check_remote ]];then
	read -p "website $NAME đã được kích hoạt remote database bạn có muốn tắt (y/n): " tatremote
	if [[ $tatremote = 'y' ]];then
		_runing "Tắt kích hoạt Remote Database website $NAME"
		mysql -u "$database_admin_username" -p"$database_admin_password" -e "DROP USER IF EXISTS '${DB_User_web}'@'%'"
		mysql -u "$database_admin_username" -p"$database_admin_password" -e "FLUSH PRIVILEGES"

		if [[ -f /tmp/remote_wptangtoc_ols ]];then
		rm -f /tmp/remote_wptangtoc_ols
		fi

		for entry in $(ls -A /etc/wptt/vhost); do
			domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			path="/usr/local/lsws/$domain/html"
			i=1

			if [[ -d "$path" ]]; then
				. /etc/wptt/vhost/.$domain.conf
				if [[ $DB_User_web ]];then
				mysql -u "$database_admin_username" -p"$database_admin_password" -e "SHOW GRANTS FOR '$DB_User_web'@'%';" 2>/dev/null 1>>/tmp/remote_wptangtoc_ols
				fi
			fi
		done

		check_con_dung_website_khac=$(cat /tmp/remote_wptangtoc_ols)
		if [[ $check_con_dung_website_khac = '' ]];then
			sed -i "s/bind-address/#bind-address/g" /etc/my.cnf.d/server.cnf
			sed -i '/port=/d' /etc/my.cnf.d/server.cnf
			firewall-cmd --permanent --zone=public --remove-port=18188/tcp >/dev/null 2>&1
			firewall-cmd --reload >/dev/null 2>&1
			systemctl restart mysql.service >/dev/null 2>&1
			sed -i 's/18188/3306/g' /etc/fail2ban/jail.local
			systemctl restart fail2ban.service
		fi
		_rundone "Tắt kích hoạt Remote Database website $NAME"
	fi
	check_menu_wptangtoc_active=$1
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-db-main 1
	fi
	exit
fi

read -p "Bạn có muốn kích hoạt remote database website $NAME (y/n): " kichhoatremote

if [[ $kichhoatremote = 'y' ]];then
	_runing "Kích hoạt Remote Database website $NAME"
	sed -i "s/#bind-address/bind-address/g" /etc/my.cnf.d/server.cnf
	sed -i '/port=/d' /etc/my.cnf.d/server.cnf
	echo 'port=18188' >> /etc/my.cnf.d/server.cnf
	firewall-cmd --permanent --zone=public --add-port=18188/tcp >/dev/null 2>&1
	firewall-cmd --reload >/dev/null 2>&1
	systemctl restart mysql.service >/dev/null 2>&1
	sed -i 's/3306/18188/g' /etc/fail2ban/jail.local
	systemctl restart fail2ban.service

	mysql -u "$database_admin_username" -p"$database_admin_password" -e "CREATE USER IF NOT EXISTS '$DB_User_web'@'%' IDENTIFIED BY '$DB_Password_web'"
	mysql -u "$database_admin_username" -p"$database_admin_password" -e "GRANT ALL PRIVILEGES ON $DB_Name_web.* TO '$DB_User_web'@'%' WITH GRANT OPTION"
	mysql -u "$database_admin_username" -p"$database_admin_password" -e "FLUSH PRIVILEGES"

	ip=$(curl -s myip.directadmin.com)
	if [[ "$ip" = "" ]]; then
		ip=$(curl -s ifconfig.me)
	fi
	_rundone "Kích hoạt Remote Database website $NAME"
	echo "Thông tin tài khoản database website $NAME"
	echo "-------------------------------------------------------------------------"
	echo "1.  Database Name 		: $DB_Name_web"
	echo "2.  UserName 			: $DB_User_web"
	echo "3.  PassWord 			: $DB_Password_web"
	echo "4.  IP 				: $ip"
	echo "5.  Port 			: 18188"
	echo "-------------------------------------------------------------------------"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-db-main 1
fi

