#!/bin/bash

function huong_dan(){
Tính năng Rebuild MariaDB [Xây dựng lại MariaDB] thường đề cập đến các hành động nhằm sửa chữa, tối ưu hóa, hoặc khôi phục lại trạng thái hoạt động tốt cho cơ sở dữ liệu MariaDB, đặc biệt khi nó gặp sự cố, lỗi, hoặc hiệu suất bị suy giảm.

Nói một cách đơn giản, đây là việc làm mới hoặc sửa chữa một phần hoặc toàn bộ cơ sở dữ liệu MariaDB để nó chạy trơn tru và chính xác trở lại.

Lưu ý: Luôn nhớ sao lưu dữ liệu trước khi thực hiện các thao tác rebuild quan trọng.
}


. /etc/wptt/.wptt.conf
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quản lý Database => Thay đổi phiên bản Maria database                  |"
echo "========================================================================="
echo ""
#tang kha nang check chinh xac
checkmaria=$(mysqld --version | grep mysqld | cut -f4 -d " " |  grep '^1'| cut -f1-2 -d '.')
echo "========================================================================="
echo "|Phiên bản Maria Database hiện tại bạn đang sử dụng là $checkmaria      |"
echo "========================================================================="


echo "Xác nhân bạn có muốn rebuild máy chủ mariadb không?:"
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ $dongy = 'n' ]];then
	if [[ $check_menu_wptangtoc_active = "98" ]];then
		. /etc/wptt/wptt-db-main 1
	fi
	return 2>/dev/null;exit
fi


. /etc/wptt/echo-color
_runing "rebuild mariadb $checkmaria"
systemctl stop mariadb.service

if $(cat /etc/*release | grep -q "Ubuntu") ; then
yum remove mariadb-* -y
yum install mariadb-server mariadb-client -y
else
yum remove MariaDB-* -y
yum install MariaDB-server MariaDB-client -y
fi


work_cpucore='1024'
cpucore=$(grep -c ^processor /proc/cpuinfo)
max_client=$(expr $work_cpucore \* $cpucore \* 2)
max_client_max=$(expr $work_cpucore \* $cpucore \* 3)
max_client_php=$(expr $work_cpucore \* $cpucore \/ 8)
tong_ram_byte=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
rong_ram_mb=$(echo "scale=0;${tong_ram_byte}/1024" | bc)
if [[ "$rong_ram_mb" = "" ]]; then
  rong_ram_mb="2048"
fi
tong_ram_mb_db=$(echo "scale=0;${rong_ram_mb}/4" | bc)
max_conect_db=$(expr $max_client / 8 )
tong_ram_gb=$(expr ${rong_ram_mb} / 1024)
db_table_size=$(expr $tong_ram_gb \* 64 )
buffer_db=$(expr $rong_ram_mb / 6)

max_connections=$(expr 64 \* ${tong_ram_gb})

#cau hinh query cache set up optimize
if (( $cpucore > 2 ));then
query_cache_type=0
query_cache_size=0
else
query_cache_type=1
query_cache_size='50M'
fi

if [[ $query_cache_type = '' ]];then
query_cache_type=0
query_cache_size=0
fi



if $(cat /etc/*release | grep -q "Ubuntu") ; then
duong_dan_cau_hinh_mariadb="/etc/mysql/my.cnf"
else
duong_dan_cau_hinh_mariadb="/etc/my.cnf.d/server.cnf"
fi

if $(cat /etc/*release | grep -q "Ubuntu") ; then
	echo '[mysqld]' >> $duong_dan_cau_hinh_mariadb
fi

echo "key_buffer_size = ${buffer_db}M
table_cache = 2000
innodb_buffer_pool_size = ${tong_ram_mb_db}M
max_connections = $max_connections
query_cache_type = $query_cache_type
query_cache_limit = 2M
query_cache_min_res_unit = 2k
query_cache_size = $query_cache_size
tmp_table_size = ${db_table_size}M
max_heap_table_size = ${db_table_size}M
thread_cache_size = 81
max_allowed_packet = 64M
wait_timeout=60" >>$duong_dan_cau_hinh_mariadb
sed -i '/\[mysqld\]/a skip-log-bin' $duong_dan_cau_hinh_mariadb

systemctl start mariadb.service
systemctl enable mariadb.service
echoDone "rebuild mariadb $checkmaria"
echo "Rebuild mariadb: $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-db-main 1
fi

