#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Database => Sao luu Database                                   |"
echo "========================================================================="

. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
. /etc/wptt/echo-color
echo ""
echo ""
echo "Nhap ten website muon sao luu database: "
echo ""
lua_chon_NAME
. /etc/wptt/vhost/."$NAME".conf
pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-db-main
    exit
fi

mkdir -p "/usr/local/backup-website/$NAME"
echo "Dang tien thanh xuat database cua website $NAME..."
timedate=$(date +%Hgio\_%d\_%m\_%Y)
mysqldump -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web" >/usr/local/backup-website/$NAME/$NAME$timedate.sql

if [[ ! -f /usr/local/backup-website/$NAME/$NAME$timedate.sql ]];then
echo "========================================================================="
echoDo "Sao luu database khong thanh cong."
echo "========================================================================="
fi


check_file_error=$(du -c /usr/local/backup-website/$NAME/$NAME$timedate.sql | awk '{print $1}' | sed '1d')
if (( $check_file_error < 10 ));then
echo "========================================================================="
echoDo "Sao luu database khong thanh cong."
echo "========================================================================="
rm -f /usr/local/backup-website/$NAME/$NAME$timedate.sql
return 2>/dev/null ; exit
fi

clear
echo "========================================================================="
echoDone "Hoan thanh qua trinh sao luu backup database."
echo "$NAME$timedate.sql database cua ban nam o thu muc: /usr/local/backup-website/$NAME"
echo "========================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-db-main 1
fi

