#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Database => Khoi phuc Database                                 |"
echo "========================================================================="
. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website muon khoi phuc Database: "
echo ""
lua_chon_NAME
pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
	clear
	. /etc/wptt/wptt-db-main
	exit
fi

echo "/-----------------------------------------------------------------------/"
echo "Huong dan: Ban hay upload database .sql vao thu muc /usr/local/backup-website/$NAME"
echo "/-----------------------------------------------------------------------/"


if [ ! $(ls -A /usr/local/backup-website/$NAME/ | grep ".sql$") ]; then
	clear
	echo "Không có file backup database (dinh dang .sql) nào tồn tại."
	echo "Vui lòng uploads file backup database dinh dang .sql của bạn vào: /usr/local/backup-website/$NAME/"
	echo
fi


b=1
for entry in $(ls -At /usr/local/backup-website/$NAME | grep ".sql$"); do
b=$((b+1));
done
echo "========================================================================="
echo "So luong file backup Database cua website $NAME: $((b-1))"
echo "========================================================================="


selects=()
for entry in $(ls -A /usr/local/backup-website/$NAME | grep ".sql$"); do
	selects+=("$entry")
done

PS3="
-//- Nhap lua chon cua ban [0=Thoat]: "
select select in ${selects[@]}; do
	file=$select
	break
done

if [[ "$file" = "0" ]]; then
	clear
	. /etc/wptt/wptt-db-main
	exit
fi

if [[ "$file" = "" ]]; then
	clear
	echo "Khong co file backup database nao ton tai trong thu muc /usr/local/backup-website/$NAME"
	echo "Ban hay upload database .sql"
	sleep 3
	exit
fi

duong_dan_thu_muc="/usr/local/backup-website/$NAME/$file"
. /etc/wptt/vhost/."$NAME".conf
read -p "Ban co muon nhap $file vao database website $NAME? (y/n): " dongy

if [[ "$dongy" = "y" ]]; then
	echo "Dang xoa du lieu cu cua database cua website $NAME (database: $DB_Name_web)"
	mysql -u "$database_admin_username" -p"$database_admin_password" -e "DROP DATABASE $DB_Name_web"
	mysql -u "$database_admin_username" -p"$database_admin_password" -e "CREATE DATABASE IF NOT EXISTS $DB_Name_web"

	if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
		sed -i "/DB_HOST/s/'[^']*'/'localhost'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
		sed -i "/DB_NAME/s/'[^']*'/'$DB_Name_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
		sed -i "/DB_USER/s/'[^']*'/'$DB_User_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
		sed -i "/DB_PASSWORD/s/'[^']*'/'$DB_Password_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
	fi
else
	. /etc/wptt/wptt-db-main
	exit
fi

sleep 3
echo "Dang tien hanh nhap du lieu database"
echo ""
echo "Vui long doi..."
echo ""
mysql -h localhost -u "$database_admin_username" -p"$database_admin_password" "$DB_Name_web" <$duong_dan_thu_muc
clear
echo "Hoan thanh khoi phuc nhap du lieu database cho website $NAME ($DB_Name_web)"
echo "hoan tat qua trinh nhap du lieu database"
