#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Quan ly Database => Sao luu Database                                   |"
echo "========================================================================="

. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
echo ""
echo ""
echo "Nhap ten website muon sao luu database: "
echo ""
lua_chon_NAME
. /etc/wptt/vhost/."$NAME".conf
pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-db-main
    exit
fi

mkdir -p "/usr/local/backup-website/$NAME"
echo "Dang tien thanh xuat database cua website $NAME..."
timedate=$(date +%Hgio\_%d\_%m\_%Y)
mysqldump -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web" >/usr/local/backup-website/$NAME/$NAME$timedate.sql
clear
echo "Hoan thanh qua trinh sao luu backup database."
echo "$NAME$timedate.sql database cua ban nam o thu muc: /usr/local/backup-website/$NAME"
