#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao luu & khoi phuc => Sao luu tat cac website                         |"
echo "========================================================================="
echo ""
echo ""
pathcheck_full="/usr/local/backup-website"
before_optimize_full=$(du -hs $pathcheck_full)

echo "Backup sao luu toan bo website tren websever"

if [ "$(ls -A /etc/wptt/vhost)" ]; then
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1

    if [[ -d "$path" ]]; then
      . /etc/wptt/backup-restore/wptt-saoluu "$domain"
    fi
  done
fi
clear
echo "==================================================================="
echo "Hoan tat backup tat ca website cua ban"
echo "==================================================================="
echo "Da backup cac website: "

for entry in $(ls -A /etc/wptt/vhost); do
  domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
  path="/usr/local/lsws/$domain/html"
  i=1

  if [[ -d "$path" ]]; then
    echo "Hoan tat backup website: $domain"
  fi
done
echo "==================================================================="
echo "Dung luong thu muc truoc khi backup	: $before_optimize_full"
echo "Dung luong thu muc sau khi backup	: $(du -hs $pathcheck_full)"
echo "==================================================================="
disk=$(mount|grep ' / '|cut -d' ' -f 1)
disk_kha_dung=$(df -T -h | grep $disk | awk -F ' ' '{print $5}' | tr -d 'a-zA-G')
het_disk="2"
if [[ "$disk_kha_dung" < "$het_disk" ]];then
RED='\033[0;33m'
NC='\033[0m'
echo -e "${RED}==================================================================="
echo "Canh bao FULLDISK khi disk con duoi: 2GB"
echo "Disk: $(df -h | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')"
echo -e "=================================================================== ${NC}"
fi
echo "Cong cu phat trien boi	: Gia Tuan"
echo "Yeu Cau Ho tro		: https://wptangtoc.com/lien-he"
echo "Ho tro phat trien	: https://wptangtoc.com/donate"
echo "==================================================================="
