#!/bin/bash

function huong_dan(){
Tính năng Xóa kích hoạt File Manager [Trình quản lý tệp/tập tin] thường có nghĩa là một quản trị viên máy chủ vô hiệu hóa hoặc thu hồi quyền truy cập vào công cụ File Manager dựa trên web đối với một website cụ thể.

Nói một cách đơn giản, nếu trước đó người dùng có thể sử dụng File Manager để quản lý tệp tin website qua trình duyệt, thì sau khi xóa kích hoạt, họ sẽ không còn truy cập được vào công cụ này nữa.

Mục Đích Chính [Thường Từ Phía Quản Trị Viên]
 * Tăng cường bảo mật: Nếu một tài khoản người dùng bị nghi ngờ xâm phạm, việc vô hiệu hóa File Manager có thể là một biện pháp tạm thời để ngăn chặn các hành vi sửa đổi tệp tin trái phép.
 * Giới hạn quyền của người dùng: Trong một số trường hợp, quản trị viên có thể muốn hạn chế người dùng truy cập trực tiếp vào hệ thống tệp để tránh những thay đổi không mong muốn hoặc sai sót. Người dùng có thể được yêu cầu sử dụng các phương thức khác như FTP/SFTP.
 * Tuân thủ chính sách: Áp dụng các chính sách bảo mật hoặc giới hạn của gói dịch vụ.
 * Gỡ lỗi [hiếm khi]: Nếu có nghi ngờ bản thân công cụ File Manager gây ra sự cố.

Sau khi xóa kích hoạt, người dùng sẽ cần sử dụng các phương thức khác [nếu được phép và đã cấu hình] như  SFTP để quản lý tệp tin website của họ.
}


. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]];then
	ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|$quan_ly_file_manager => $tat File Manager                 |"
echo "========================================================================="

. /etc/wptt/echo-color
function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [ "$NAME" != "${NAME/./}" ] && [ "$NAME" != '.' ]; then #điều kiện domain phải có dấu . và lỗi chỉ có only .
				if [[ -d /usr/local/lsws/"$NAME"/html/quan-ly-files ]]; then
					selects+=("$NAME")
				fi
			fi
		done

		if [[ $selects = '' ]];then
			echo "Tất cả domain trên hệ thống chưa có domain nào được kích hoạt sử dụng File Manager"
			. /etc/wptt/wptt-quan-ly-files-main 1
		fi

		PS3="
-//- Nhập lựa chọn website của bạn [0=Thoát]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Tất cả domain trên hệ thống đều chưa được kích hoạt sử dụng File Manager"
		exit
		exit
	fi
}

echo ""
echo ""
echo "Lựa chọn website muốn hủy kích hoạt trình quản lý files: "
echo ""
lua_chon_NAME

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-quan-ly-files-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-quan-ly-files-main 1
    exit
fi

if [[ ! -d /usr/local/lsws/$NAME/html/quan-ly-files ]];then
echo "Bạn chưa kích hoạt trình quản lý files"
. /etc/wptt/wptt-quan-ly-files-main 1
fi

_runing "Hủy kích hoạt FileManager cho website $NAME"

sed -i -e '/^realm '${NAME}files'/,/^}$/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf
sed -i -e '/^context \/quan-ly-files\//,/^}$/d' /usr/local/lsws/conf/vhosts/$NAME/$NAME.conf

rm -rf /usr/local/lsws/$NAME/html/quan-ly-files
rm -f /usr/local/lsws/$NAME/passwd/.files

rm -f /usr/local/lsws/"$NAME"/passwd/.password-giatuan.json
rm -f /usr/local/lsws/"$NAME"/passwd/.user-giatuan.json


sed -i '/password_dang_nhap_quan_ly_file_cap_2/d' /etc/wptt/vhost/.$NAME.conf
sed -i '/id_dang_nhap_quan_ly_file_cap_2/d' /etc/wptt/vhost/.$NAME.conf
sed -i '/id_quan_ly_files/d' /etc/wptt/vhost/.$NAME.conf
sed -i '/password_quan_ly_file/d' /etc/wptt/vhost/.$NAME.conf

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
_rundone "Hủy kích hoạt FileManager cho website $NAME"

echo "Huỷ Kích hoạt filemanager website $NAME : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-quan-ly-files-main 1
fi

