#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]];then
echo "========================================================================="
echo "|Quản lý sao lưu và khôi phục => Sao lưu Database                       |"
echo "========================================================================="
else
echo "========================================================================="
echo "|Quản lý Database => Sao lưu Database                                   |"
echo "========================================================================="
fi

. /etc/wptt-user/tenmien
. /etc/wptt-user/echo-color
lua_chon_NAME
. /etc/wptt/vhost/."$NAME".conf


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt-user/wptt-db-main 1
fi


_runing "Sao lưu database của website $NAME"
timedate=$(date +%Hgio\_%d\_%m\_%Y)

#sao luư database bản .sql bình thường
if [[ $sql_gz = '' ]];then
mysqldump -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web" >/usr/local/lsws/$NAME/backup-website/$NAME$timedate.sql
fi

# sao lưu database định dạng gzip có nén được config
if [[ $sql_gz ]];then
mysqldump -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web" | gzip >/usr/local/lsws/$NAME/backup-website/$NAME$timedate.sql.gz
fi


if [[ ! -f /usr/local/lsws/$NAME/backup-website/$NAME$timedate.sql && ! -f /usr/local/lsws/$NAME/backup-website/$NAME$timedate.sql.gz ]];then
_runloi "Sao lưu database của website $NAME"
fi

if [[ $sql_gz = '' ]];then
	check_file_error=$(du -c /usr/local/lsws/$NAME/backup-website/$NAME$timedate.sql | awk '{print $1}' | sed '1d')
	if (( $check_file_error < 10 ));then
		_runloi "Sao lưu database của website $NAME"
		rm -f /usr/local/lsws/$NAME/backup-website/$NAME$timedate.sql
		return 2>/dev/null ; exit
	fi
fi


if [[ $sql_gz ]];then
	check_file_error=$(du -c /usr/local/lsws/$NAME/backup-website/$NAME$timedate.sql.gz | awk '{print $1}' | sed '1d')
	if (( $check_file_error < 10 ));then
		_runloi "Sao lưu database của website $NAME"
		rm -f /usr/local/lsws/$NAME/backup-website/$NAME$timedate.sql.gz
		return 2>/dev/null ; exit
	fi
fi

_rundone "Sao lưu database của website $NAME"
if [[ $sql_gz = '' ]];then
echo "$NAME$timedate.sql database của bạn nằm trong thư mục: /usr/local/lsws/backup-website"
fi

if [[ $sql_gz ]];then
echo "$NAME$timedate.sql.gz database của bạn nằm trong thư mục: /usr/local/lsws/backup-website"
fi
echo "========================================================================="


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt-user/wptt-db-main 1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]];then
. /etc/wptt-user/wptt-backup-restore-main 1
fi

