#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]];then
	echo "========================================================================="
	echo "|Quản lý sao lưu và khôi phục => Khôi phục Database                     |"
	echo "========================================================================="
else
	echo "========================================================================="
	echo "|Quản lý Database => Khôi phục Database                                 |"
	echo "========================================================================="
fi

. /etc/wptt-user/tenmien
. /etc/wptt-user/echo-color
lua_chon_NAME

if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt-user/wptt-db-main 1
fi

echo "========================================================================="
echo "Hướng dẫn: Bạn hãy uploads database vào thư mục /usr/local/lsws/$NAME/backup-website"
echo "========================================================================="

if [[ $sql_gz = '' ]];then

	if [ ! $(ls -A /usr/local/lsws/$NAME/backup-website | grep ".sql$") ]; then
		clear
		echoDo "Không có file backup database (dinh dang .sql) nào tồn tại."
		echoDo "Vui lòng uploads file backup database dinh dang .sql của bạn vào: /usr/local/lsws/$NAME/backup-website/"
		echo
	fi


	b=1
	for entry in $(ls -At /usr/local/lsws/$NAME/backup-website | grep ".sql$"); do
		b=$((b+1));
	done
	echo "========================================================================="
	echo "Số lượng file backup Database của website $NAME: $((b-1))"
	echo "========================================================================="


	selects=()
	for entry in $(ls -At /usr/local/lsws/$NAME/backup-website | grep ".sql$"); do
		selects+=("$entry")
	done

	PS3="
-//- Nhập lựa chọn của bạn [0=Thoát]: "
	select select in ${selects[@]}; do
		file=$select
		break
	done
fi

if [[ $sql_gz ]];then
	if [ ! $(ls -A /usr/local/lsws/$NAME/backup-website | grep ".sql.gz$") ]; then
		clear
		echoDo "Không có file backup database (dinh dang .sql.gz) nào tồn tại."
		echoDo "Vui lòng uploads file backup database định dạng .sql.gz của bạn vào: /usr/local/lsws/$NAME/backup-website/"
		echo
	fi


	b=1
	for entry in $(ls -At /usr/local/lsws/$NAME/backup-website | grep ".sql.gz$"); do
		b=$((b+1));
	done
	echo "========================================================================="
	echo "So luong file backup Database cua website $NAME: $((b-1))"
	echo "========================================================================="


	selects=()
	for entry in $(ls -At /usr/local/lsws/$NAME/backup-website | grep ".sql.gz$"); do
		selects+=("$entry")
	done

	PS3="
	-//- Nhập lựa chọn của bạn [0=Thoát]: "
	select select in ${selects[@]}; do
		file=$select
		break
	done
fi


if [[ "$file" = "0" ]]; then
	clear
	. /etc/wptt-user/wptt-db-main 1
	exit
fi

if [[ $sql_gz ]];then
	if [[ "$file" = "" ]]; then
		clear
		echoDo "Không có file backup database nào tồn tại trong thư mục /usr/local/lsws/$NAME/backup-website"
		echo "Bạn hãy upload database .sql.gz vào thư mục /usr/local/lsws/$NAME/backup-website"
		sleep 3
		. /etc/wptt-user/wptt-db-main 1
	fi
fi

if [[ $sql_gz = '' ]];then
	if [[ "$file" = "" ]]; then
		clear
		echoDo "Không có file backup database nào tồn tại trong thư mục /usr/local/lsws/$NAME/backup-website"
		echo "Bạn hãy upload database .sql vào thư mục /usr/local/lsws/$NAME/backup-website"
		sleep 3
		. /etc/wptt-user/wptt-db-main 1
	fi
fi


duong_dan_thu_muc="/usr/local/lsws/$NAME/backup-website/$file"

check_file_error=$(du -c $duong_dan_thu_muc | awk '{print $1}' | sed '1d')
if (( $check_file_error < 10 ));then
	echo "$file bi loi khong the su dung de khoi phuc database"
	echo "Vui long lua chon file database backup khac"
	exit
fi

. /etc/wptt/vhost/."$NAME".conf


echo "Xác nhận bạn có muốn nhập $file vào database website $NAME? "
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


if [[ "$dongy" = "y" ]]; then
	_runing "Làm sạch toàn bộ dữ liệu database của $NAME"
mysql -u "$DB_User_web" -p"$DB_Password_web" -e "DROP DATABASE IF EXISTS ${DB_Name_web}"
mysql -u "$DB_User_web" -p"$DB_Password_web" -e "CREATE DATABASE IF NOT EXISTS ${DB_Name_web}"
	_rundone "Làm sạch toàn bộ dữ liệu database của $NAME"

	if [[ -f /usr/local/lsws/$NAME/html/wp-config.php ]]; then
		sed -i "/DB_HOST/s/'[^']*'/'localhost'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
		sed -i "/DB_NAME/s/'[^']*'/'$DB_Name_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
		sed -i "/DB_USER/s/'[^']*'/'$DB_User_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
		sed -i "/DB_PASSWORD/s/'[^']*'/'$DB_Password_web'/2" "/usr/local/lsws/$NAME/html/wp-config.php"
	fi
else
	. /etc/wptt-user/wptt-db-main 1
	exit
fi

_runing "Khôi phục database website $NAME"
if [[ $sql_gz = '' ]];then
	mysql -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web" <$duong_dan_thu_muc
fi

if [[ $sql_gz ]];then
	zcat $duong_dan_thu_muc | mysql -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web"
fi

_rundone "Khôi phục database website $NAME"
clear

thong_bao_sql=$(echo $duong_dan_thu_muc | cut -f6 -d '/' | grep "$NAME" | sed "s/$NAME//g" | cut -f1 -d '.')
echo "==================================================================="
echoDone "Khôi phục database website $NAME thành công             "
if [[ $thong_bao_sql ]];then
	chuyen_doi_thong_bao_gio=$( echo $thong_bao_sql | cut -c 1-2)
	chuyen_doi_thong_bao_ngay=$( echo $thong_bao_sql | cut -f2 -d '_' | cut -c 1-2)
	chuyen_doi_thong_bao_thang=$( echo $thong_bao_sql | cut -f3 -d '_' | cut -c 1-2)
	chuyen_doi_thong_bao_nam=$( echo $thong_bao_sql | cut -f4 -d '_' | cut -c 1-4)
	if [[ $chuyen_doi_thong_bao_gio && $chuyen_doi_thong_bao_ngay && $chuyen_doi_thong_bao_thang && $chuyen_doi_thong_bao_nam ]];then
		echoDone "Khôi phục về lúc $chuyen_doi_thong_bao_gio giờ ngày $chuyen_doi_thong_bao_ngay tháng $chuyen_doi_thong_bao_thang năm $chuyen_doi_thong_bao_nam"
	fi
fi
echo "==================================================================="


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt-user/wptt-db-main 1
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "97" ]];then
	. /etc/wptt-user/wptt-backup-restore-main 1
fi
