#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Cau hinh webserver => Cau hinh cron job                                |"
echo "========================================================================="


read -p "Xac nhan ban muon cau hinh cron job (y/n): " dongy
if [[ "$dongy" = "y" ]]; then
    echo "Chinh sua xong an ctrl + o de luu lai va ctrl + x de thoat ra"
    sleep 4
export VISUAL=nano; crontab -e
else
    . /etc/wptt/wptt-cau-hinh-websever-main
fi
