#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Cau hinh webserver => Cap nhat lai config khi da thay doi phan cung    |"
echo "========================================================================="

read -p "xac nhan cap nhat lai config khi da thay doi phan cung" dongy
if [[ "$dongy" != "y" ]]; then
    clear
    . /etc/wptt/wptt-cau-hinh-websever-main
    exit
fi

work_cpucore=$(ulimit -n)
cpucore=$(grep -c ^processor /proc/cpuinfo)
max_client=$(expr $work_cpucore \* $cpucore \* 2)
max_client_max=$(expr $work_cpucore \* $cpucore \* 3)
max_client_php=$(expr $work_cpucore \* $cpucore \/ 8)
tong_ram_byte=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
rong_ram_mb=$(echo "scale=0;${tong_ram_byte}/1024" | bc)
if [[ "$rong_ram_mb" = "" ]]; then
    rong_ram_mb="2048"
fi
tong_ram_mb_db=$(echo "scale=0;${rong_ram_mb}/1.4" | bc)


sed -i "/httpdWorkers/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/serverName/a httpdWorkers                  $cpucore" /usr/local/lsws/conf/httpd_config.conf

sed -i "/cpuAffinity/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/inMemBufSize/a cpuAffinity                  $cpucore" /usr/local/lsws/conf/httpd_config.conf

sed -i "/maxConnections/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/maxSSLConnections/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/maxKeepAliveReq/d" /usr/local/lsws/conf/httpd_config.conf

sed -i "/connTimeout/a maxConnections                   $max_client_max" /usr/local/lsws/conf/httpd_config.conf
sed -i "/connTimeout/a maxSSLConnections                $max_client_max" /usr/local/lsws/conf/httpd_config.conf
sed -i "/connTimeout/a maxKeepAliveReq                  $max_client_max" /usr/local/lsws/conf/httpd_config.conf

sed -i "/maxConns/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/extprocessor/a maxConns                  $max_client_php" /usr/local/lsws/conf/httpd_config.conf

sed -i "/PHP_LSAPI_CHILDREN/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/extprocessor/a env                  PHP_LSAPI_CHILDREN=$max_client_php" /usr/local/lsws/conf/httpd_config.conf


sed -i "/memSoftLimit/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/memHardLimit/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/procSoftLimit/d" /usr/local/lsws/conf/httpd_config.conf
sed -i "/procHardLimit/d" /usr/local/lsws/conf/httpd_config.conf


sed -i '/extprocessor/a memSoftLimit            '${rong_ram_mb}'M\
memHardLimit            '${rong_ram_mb}'M\
procSoftLimit           '$max_client'\
procHardLimit           '$max_client'' /usr/local/lsws/conf/httpd_config.conf


sed -i '/railsDefaults/a memSoftLimit            '${rong_ram_mb}'M\
memHardLimit            '${rong_ram_mb}'M\
procSoftLimit           '$max_client'\
procHardLimit           '$max_client'' /usr/local/lsws/conf/httpd_config.con


sed -i '/wsgiDefaults/a memSoftLimit            '${rong_ram_mb}'M\
memHardLimit            '${rong_ram_mb}'M\
procSoftLimit           '$max_client'\
procHardLimit           '$max_client'' /usr/local/lsws/conf/httpd_config.con


sed -i '/nodeDefaults/a memSoftLimit            '${rong_ram_mb}'M\
memHardLimit            '${rong_ram_mb}'M\
procSoftLimit           '$max_client'\
procHardLimit           '$max_client'' /usr/local/lsws/conf/httpd_config.con

if [ "$(ls -A /etc/wptt/vhost)" ]; then
echo '--------------------------------------------------'
  for entry in $(ls -A /etc/wptt/vhost); do
    domain=$( echo $entry | sed 's/^.//' | sed 's/.conf//')
    path="/usr/local/lsws/$domain/html"
    i=1
    if [[ -d "$path" ]]; then
         sed -i "/memSoftLimit/,+3d" /usr/local/lsws/conf/vhosts/$domain/$domain.conf && sed -i '/extprocessor/a memSoftLimit            '${rong_ram_mb}'M\
memHardLimit            '${rong_ram_mb}'M\
procSoftLimit           '$max_client'\
procHardLimit           '$max_client'' /usr/local/lsws/conf/vhosts/$domain/$domain.conf
    fi
  done
fi
/usr/local/lsws/bin/lswsctrl restart

sed -i "/innodb_buffer_pool_size/d" /etc/my.cnf.d/server.cnf
sed -i "/max_connections/d" /etc/my.cnf.d/server.cnf

echo "innodb_buffer_pool_size= ${tong_ram_mb_db}M
max_connections = $max_client" >> /etc/my.cnf.d/server.cnf

systemctl restart mariadb.service

echo "Hoan tat thiet lap lai config"