#!/bin/bash

function huong_dan() {
  Giả lập một website WordPress trắng hoàn toàn là việc tạo ra một bản cài đặt WordPress gốc, sạch sẽ, và cung cấp một tên miền miễn phí dành cho bạn, trên máy chủ của bạn. Điều này rất hữu ích cho việc phát triển, kiểm thử, học tập và chuẩn bị cho một dự án website mới một cách an toàn và hiệu quả.
}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Giả lập => Giả lập website WordPress mới hoàn toàn                     |"
echo "========================================================================="

. /etc/wptt/echo-color
. /etc/wptt/.wptt.conf

NAME=$(echo $Website_chinh)
domain_phuc_vu="wptangtoc-ols.com"

ten_ngau_nhien=$(
  date +%s | sha256sum | base64 | head -c 4
  echo
)
ten_mien_random=${Website_chinh//[-._]/$ten_ngau_nhien}
subdomain_ten_mien=$(echo $ten_mien_random | tr '[:upper:]' '[:lower:]')

_runing "Cấu hình domain giả lập ${subdomain_ten_mien}.${domain_phuc_vu}"
ip=$(curl -sf --connect-timeout 5 --max-time 10 https://ipv4.icanhazip.com || curl -sf --connect-timeout 5 --max-time 10 https://checkip.amazonaws.com)

# bash /etc/wptt/gia-lap-website/cf-dns.sh -d $domain_phuc_vu -n $subdomain_ten_mien -t A -c $ip -p 0 -l 1 -x n 2>/tmp/dns-cloudflare.log 1>/tmp/dns-cloudflare.log

# if [[ -f /tmp/dns-cloudflare.log ]];then
# 	check_loi=$(cat /tmp/dns-cloudflare.log | grep 'ERROR:')
# 	if [[ $check_loi ]];then
# 		_runloi "Cấu hình domain giả lập ${subdomain_ten_mien}.${domain_phuc_vu}"
# 		echo "Vui lòng thử lại sau"
# 		. /etc/wptt/wptt-gia-lap-main 1
# 	fi
# fi

. /etc/wptt/gia-lap-website/cloudflare-dns "${subdomain_ten_mien}" "$ip"

echo "Gỉa lập website ${subdomain_ten_mien}.${domain_phuc_vu} mới trắng: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

_rundone "Cấu hình domain giả lập ${subdomain_ten_mien}.${domain_phuc_vu}"

_runing "Tạo lập domain ${subdomain_ten_mien}.${domain_phuc_vu}"
. /etc/wptt/domain/wptt-themwebsite "${subdomain_ten_mien}.${domain_phuc_vu}" >/dev/null 2>&1
_rundone "Tạo lập domain ${subdomain_ten_mien}.${domain_phuc_vu}"

cd /usr/local/lsws/"${subdomain_ten_mien}.${domain_phuc_vu}"/html/
rm -rf /usr/local/lsws/"${subdomain_ten_mien}.${domain_phuc_vu}"/html/*
_runing "Download mã nguồn WordPress"
wget -q http://wordpress.org/latest.tar.gz
_rundone "Download mã nguồn WordPress"
_rundone "Giải nén mã nguồn WordPress"
tar -zxf latest.tar.gz
mv wordpress/* /usr/local/lsws/"${subdomain_ten_mien}.${domain_phuc_vu}"/html && rm -rf wordpress && rm -f latest.tar.gz
_rundone "Giải nén mã nguồn WordPress"

_runing "Cài Đặt WordPress ${subdomain_ten_mien}.${domain_phuc_vu}"

. /etc/wptt/vhost/.${subdomain_ten_mien}.${domain_phuc_vu}.conf
tien_to_db=$(
  date +%s | sha256sum | base64 | head -c 6
  echo
)
wp core config --dbname="$DB_Name_web" --dbuser="$DB_User_web" --dbpass="$DB_Password_web" --dbhost=localhost --dbprefix="${tien_to_db}"_ --allow-root --extra-php >/dev/null 2>&1 <<PHP
define( 'WP_DEBUG_LOG', false );
define( 'WP_DEBUG_DISPLAY', false );
PHP

idusername=$(
  date +%s | sha256sum | base64 | head -c 18
  echo
)
SiteTitle="WPTangToc OLS"
sleep 1
mypassword=$(
  date +%s | sha256sum | base64 | head -c 36
  echo
)
emailwp=$(echo admin@${subdomain_ten_mien}.${domain_phuc_vu})

wp core install --url=http://"${subdomain_ten_mien}.${domain_phuc_vu}" --title="$SiteTitle" --admin_user="$idusername" --admin_password="$mypassword" --admin_email="$emailwp" --allow-root >/dev/null 2>&1
wp language core install vi --path=/usr/local/lsws/"${subdomain_ten_mien}.${domain_phuc_vu}"/html --activate --allow-root >/dev/null 2>&1
wp option update timezone_string "Asia/Ho_Chi_Minh" --path=/usr/local/lsws/"${subdomain_ten_mien}.${domain_phuc_vu}"/html --allow-root >/dev/null 2>&1
wp rewrite structure '/%postname%/' --path=/usr/local/lsws/"${subdomain_ten_mien}.${domain_phuc_vu}"/html --allow-root >/dev/null 2>&1
_rundone "Cài Đặt WordPress ${subdomain_ten_mien}.${domain_phuc_vu}"

wp option set blog_public 0 --allow-root --path=/usr/local/lsws/${subdomain_ten_mien}.${domain_phuc_vu}/html >/dev/null 2>&1

if [[ -f /usr/local/lsws/${subdomain_ten_mien}.${domain_phuc_vu}/html/robots.txt ]]; then
  cp -f /usr/local/lsws/${subdomain_ten_mien}.${domain_phuc_vu}/html/robots.txt /tmp/${subdomain_ten_mien}.${domain_phuc_vu}-robots.txt
fi

_runing "Phần quyền website ${subdomain_ten_mien}.${domain_phuc_vu}"
chown -R "$User_name_vhost":"$User_name_vhost" /usr/local/lsws/"${subdomain_ten_mien}.${domain_phuc_vu}"/html
_rundone "Phần quyền website ${subdomain_ten_mien}.${domain_phuc_vu}"

a=0
while [[ $check_dns = '' ]]; do
  _runing "Xác thực dns domain ${subdomain_ten_mien}.${domain_phuc_vu}"
  check_dns=$(host ${subdomain_ten_mien}.${domain_phuc_vu} | grep -Eo -m 1 '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
  a=$(expr $a + 1)
  echo $a >/tmp/dem-check_dns-wptangtoc-ols
  sleep 3

  if [[ $(cat /tmp/dem-check_dns-wptangtoc-ols) = '15' ]]; then
    . /etc/wptt/gia-lap-website/cloudflare-dns "${subdomain_ten_mien}" "$ip"
    clear
  fi

  if [[ $(cat /tmp/dem-check_dns-wptangtoc-ols) = '30' ]]; then
    . /etc/wptt/domain/wptt-xoa-website "${subdomain_ten_mien}.${domain_phuc_vu}" >/dev/null 2>&1
    _runloi "Xác thực dns domain ${subdomain_ten_mien}.${domain_phuc_vu}"
    echoDo "Chưa thể khởi tạo website giả lập vui lòng thử lại sau"
    . /etc/wptt/wptt-gia-lap-main 1
  fi
done

_rundone "Xác thực dns domain ${subdomain_ten_mien}.${domain_phuc_vu}"

_runing "Kiểm tra website giả lập"
# checkssl=$(curl -Is http://${NAME} | grep -c "WPTangTocOLS")
unset http_status
http_status=$(curl -o /dev/null -s -w "%{http_code}\n" http://${NAME})

if [ "$http_status" -ne 200 ] && [ "$http_status" -ne 301 ]; then # kiểm tra http không tồn tại không trả về 301 hoặc 200, dns giả lập thất bại
  . /etc/wptt/domain/wptt-xoa-website "${subdomain_ten_mien}.${domain_phuc_vu}" >/dev/null 2>&1
  _runloi "Kiểm tra website giả lập"
  . /etc/wptt/wptt-gia-lap-main 1
else
  sed -i '/extraHeaders /a X-Robots-Tag noindex' /usr/local/lsws/conf/vhosts/"${subdomain_ten_mien}.${domain_phuc_vu}"/"${subdomain_ten_mien}.${domain_phuc_vu}".conf
fi
_runing "Kiểm tra website giả lập"

if [[ ! -f "/etc/letsencrypt/live/$Website_chinh/cert.pem" && ! -d "/usr/local/lsws/$Website_chinh/ssl" ]]; then
  echo "Website chính $Website_chinh chưa được cài đặt SSL"
  echo "vui lòng cài đặt SSL cho website $Website_chinh trước thì các website khác mới có thể sử dụng HTTPS"
  tuan='1'
else
  _runing "Cài đặt SSL cho website giả lập"
  wptt ssl ${subdomain_ten_mien}.${domain_phuc_vu} >/dev/null 2>&1
  _rundone "Cài đặt SSL cho website giả lập"
fi

/usr/local/lsws/bin/lswsctrl restart >/dev/null 2>&1
echo "domain_gia_lap=1" >>/etc/wptt/vhost/.${subdomain_ten_mien}.${domain_phuc_vu}.conf
echo "==================================================================="
echo "Hoàn tất giả lập website ${subdomain_ten_mien}.${domain_phuc_vu}"
echo "==================================================================="
if [[ $tuan = '1' ]]; then
  echo "Truy cập: http://${subdomain_ten_mien}.${domain_phuc_vu}"
  echo "Truy cập wp-admin: http://${subdomain_ten_mien}.${domain_phuc_vu}/wp-admin/"
else
  echo "Truy cập: https://${subdomain_ten_mien}.${domain_phuc_vu}"
  echo "Truy cập wp-admin: https://${subdomain_ten_mien}.${domain_phuc_vu}/wp-admin/"
fi
echo "User đăng nhập: $idusername"
echo "PassWord Đăng nhập: $mypassword"
echo "==================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-gia-lap-main 1
fi
