#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025

function huong_dan() {
  WPTangToc OLS nay cho phép bạn lựa chọn giữa 3 định dạng nén mã nguồn khi sao lưu, giúp tối ưu hóa giữa hiệu suất, tính toàn vẹn và sự tiện lợi.

  1. ZIP [.zip]: Lựa chọn Tương Thích Tối Đa
  File .zip có thể mở được trên mọi máy tính [Windows, macOS] mà không cần cài đặt thêm phần mềm.
  Khuyên dùng: Khi mục đích chính là tải file backup về máy tính cá nhân [đặc biệt là Windows] hoặc chia sẻ cho người dùng không chuyên.

  2. ZSTD [.tar.zst]: Lựa chọn Hiệu Suất Tối Đa
  Nén và giải nén cực nhanh, tốn ít CPU và thường tạo ra file backup có dung lượng nhỏ nhất.
  Khuyên dùng: Cho các tác vụ tự động trên máy chủ khi tốc độ là ưu tiên tuyệt đối, giúp giảm tải cho server và tiết kiệm thời gian.

  3. TAR.GZ [.tar.gz]: Lựa chọn Tiêu Chuẩn Vàng
  Cân bằng giữa tỉ lệ nén tốt và tính tương thích cao trên mọi môi trường máy chủ [Linux, macOS].
  Khuyên dùng: Làm định dạng mặc định cho hầu hết nhu cầu sao lưu. Đảm bảo tính toàn vẹn và dễ dàng phục hồi website nhất.

  Mặc định thiết lập là: .zip
}

. /etc/wptt/.wptt.conf
if [[ $ngon_ngu = '' ]]; then
  ngon_ngu='vi'
fi
. /etc/wptt/lang/$ngon_ngu.sh

. /etc/wptt/.wptt.conf
. /etc/wptt/echo-color
unset dinh_dang_nen_ma_nguon
prompt="$nhap_lua_chon_cua_ban [1-3] [0=$exit_thoat] : "
options=(".zip" ".tar.zst" ".tar.gz")
PS3="$prompt"
select opt in "${options[@]}"; do
  case "$REPLY" in
  1)
    dinh_dang_nen_ma_nguon="no"
    break
    ;;

  2)
    dinh_dang_nen_ma_nguon="1"
    break
    ;;

  3)
    dinh_dang_nen_ma_nguon="2"
    break
    ;;
  $((${#options[@]} + 1)))
    printf "hệ thống sẽ thoát\n"
    break
    ;;
  *)
    printf "hệ thống sẽ thoát\n"
    break
    ;;
  esac
done

if [[ $dinh_dang_nen_ma_nguon = '' || $dinh_dang_nen_ma_nguon = '0' ]]; then
  . /etc/wptt/wptt-backup-restore-main 1
fi

if [[ $dinh_dang_nen_ma_nguon = '1' ]]; then
  print_dinh_dang_db='.tar.zst'
  if [[ $(which zstd 2>/dev/null) = '' ]]; then # cai zstd
    dnf install zstd -y
  fi

  check_thu_vien_tar=$(which tar)
  if [[ $check_thu_vien_tar = '' ]]; then
    dnf install tar -y >/dev/null 2>&1
  fi

elif [[ $dinh_dang_nen_ma_nguon = '2' ]]; then
  check_thu_vien=$(which pigz)
  check_thu_vien_tar=$(which tar)
  check_thu_vien_gzip=$(which gzip)

  if [[ $check_thu_vien = '' ]]; then
    dnf install pigz -y >/dev/null 2>&1
  fi

  if [[ $check_thu_vien_tar = '' ]]; then
    dnf install tar -y >/dev/null 2>&1
  fi

  if [[ $check_thu_vien_gzip = '' ]]; then
    dnf install gzip -y >/dev/null 2>&1
  fi

  print_dinh_dang_db='.tar.gz'
else
  print_dinh_dang_db='.zip'
fi

_runing "config chuyển định dạng sao lưu mã nguồn sang $print_dinh_dang_db"

sed -i '/dinh_dang_nen_ma_nguon/d' /etc/wptt/.wptt.conf
if [[ $dinh_dang_nen_ma_nguon != 'no' ]]; then
  echo "dinh_dang_nen_ma_nguon=$dinh_dang_nen_ma_nguon" >>/etc/wptt/.wptt.conf
fi

echo "config chuyển định dạng sao lưu mã nguồn $print_dinh_dang_db: $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log

_rundone "config chuyển định dạng sao lưu mã nguồn sang $print_dinh_dang_db"

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]]; then
  . /etc/wptt/wptt-backup-restore-main 1
fi
