#!/bin/bash
#
#
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2021
echo ""
echo ""
echo ""
echo "======================================================================================"
echo "|Sao luu & khoi phuc => Huy kich tu dong xoa file Sao luu website Google Driver      |"
echo "======================================================================================"
checkactivate=$(grep -rnw '/root/.config/rclone/rclone.conf' -e "wptangtoc" >>/dev/null 2>&1 && echo 2)
if [[ "$checkactivate" = "2" ]]; then
    google=4
else
    echo "Ban chua kich hoat rclone Google Driver"
	sleep 3
    . /etc/wptt/wptt-backup-restore-main
    exit
fi
. /etc/wptt/.wptt.conf
echo ""
echo ""
if [ "$(ls -A /etc/wptt/vhost)" ]; then
	echo "=================================================================================="
	echo "Danh sach Domain da kich hoat tu dong xoa file backup het han tren Google Driver:"
	echo "=================================================================================="
	for entry in $(ls -A /etc/wptt/vhost); do
		domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
		path="/etc/cron.d/delete-google-driver-$domain.cron"
		i=1
		if [[ -f "$path" ]]; then
			checkauto="Da kich hoat gia tri thiet lap la "
			checktuan0=$(cat /etc/wptt-auto/$domain-delete-backup-google-driver | grep "delete" |awk '{print $4}'| sed "s/d//g")
			themphut=" ngay"
		else
			checkauto="Chua kich hoat"
checktuan0=""
			themphut=""
		fi
		echo "Website $domain $checkauto$checktuan0$themphut tu dong xoa file backup het han tren Google Driver"
	done
	echo "========================================================================="
	echo
fi

function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ -f /etc/cron.d/delete-google-driver-$NAME.cron ]]; then
				selects+=("$NAME")
			fi
		done
		PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Khong co domain duoc thiet lap tu dong xoa backup tu dong google driver truoc do tai tren he thong cua ban."
		exit
	fi
}

echo ""
echo ""
echo "Lua chon website ban muon tat tu dong xoa file backup sao luu het han tren Google Driver: "
echo ""
lua_chon_NAME

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
	clear
	. /etc/wptt/wptt-backup-restore-main
	exit
fi

rm -f /etc/cron.d/delete-google-driver-$NAME.cron
rm -f /etc/wptt-auto/$NAME-delete-backup-google-driver

systemctl restart crond.service
echo "========================================================================================"
echo "Hoan tat huy kich hoat tu dong xoa file backup het han Google Driver website $NAME"
echo "========================================================================================"

