#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao luu & khoi phuc => Chuyen ZIP					                  |"
echo "========================================================================="
. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website chuyen file zip: "
echo ""
lua_chon_NAME

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
	clear
	. /etc/wptt/wptt-backup-restore-main
	exit
fi

echo "/-----------------------------------------------------------------------/"
echo "chuyen file trong thu muc: /usr/local/backup-website/$NAME"
echo "/-----------------------------------------------------------------------/"

selects=()
for entry in $(ls -A /usr/local/backup-website/$NAME | grep ".zip"); do
	selects+=("$entry")
done

PS3="
-//- Nhap lua chon cua ban [0=Thoat]: "
select select in ${selects[@]}; do
	file=$select
	break
done
pathcheck="/usr/local/backup-website/$NAME"
before_delete=$(du -hs "$pathcheck")

if [[ "$file" = "" ]]; then
	clear
	echo "Khong co file nao ton tai trong thu muc /usr/local/backup-website/$NAME"
	exit
	sleep 3
fi

duong_dan_thu_muc="/usr/local/backup-website/$NAME/$file"

echo "Dang chuyen file"
cp -f $duong_dan_thu_muc /usr/local/lsws/$NAME/html/giatuan-wptangtoc.zip

if [[ -f "/usr/local/lsws/$NAME/html/giatuan-wptangtoc.zip" ]]; then
echo "Hoan tat chuyen file"
echo "/usr/local/lsws/$NAME/html/giatuan-wptangtoc.zip"
echo "$NAME"
else
echo "Chuyen file khong thanh cong"
fi
disk=$(mount|grep ' / '|cut -d' ' -f 1)
disk_kha_dung=$(df -T -h | grep $disk | awk -F ' ' '{print $5}' | tr -d 'a-zA-G')
het_disk="2"
if (( "$disk_kha_dung" < "$het_disk" ));then
RED='\033[0;33m'
NC='\033[0m'
echo -e "${RED}==================================================================="
echo "Canh bao FULLDISK khi disk con duoi: 2GB"
echo "Disk: $(df -h | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')"
echo -e "=================================================================== ${NC}"
fi