#!/bin/bash
clear
echo ""
echo ""
echo ""
echo "==================================================================================="
echo "|Sao luu & khoi phuc => Thiet lap Rclone backup luu tru dam may Google Driver 	|"
echo "==================================================================================="
echo ""
echo ""

duong_dan_rclone="/root/.config/rclone/rclone.conf"
if [[ ! -f $duong_dan_rclone ]]; then
	echo "Dang tien hanh cai dat Rclone Google Driver..."
	echo '               .::------------:--                
               -==-------------=##+               
              -====-----------+####*.             
            .=======---------+######*.            
           .=========-------*#########:           
          .============----*###########-          
         :==============--*#############-         
        :===============-+###############=        
       -===============:  =###############+       
      -===============:    =###############+      
     -===============:      -###############*.    
   .================.        :###############*.   
  .================.          :################:  
 .===============-.            .*###############: 
:===============-                +###############-
----------------:................:+***************
:--------------==================================:
 :------------==================================: 
  .----------==================================:  
   .-------===================================:   
    .-----===================================.    
      :--===================================.     
       .-================================-:       
'
	sleep 3
	curl https://rclone.org/install.sh | sudo bash
fi

checkdathietlap=$(grep -rnw '/root/.config/rclone/rclone.conf' -e "wptangtoc" >>/dev/null 2>&1 && echo 2)
if [[ $checkdathietlap ]]; then
	clear
	echo "Ban da cau hinh rclone roi"
	exit
fi

checktool="/usr/bin/expect"
if [[ ! -f $checktool ]]; then
	yum install expect -y
fi

echo "Copy https://bit.ly/3zIr4K4 sau do Paste vao trinh duyet de lay checkid:"
read -p "Nhap ma checkid cua ban [0=Thoat]: " checkid
echo "Dang tien hanh cau hinh..."

if [[ "$checkid" = "0" ]]; then
	clear
	exit
fi

if [[ "$checkid" = "" ]]; then
	clear
	exit
fi

thietlap=$(expect -c "
spawn rclone config
expect \"n\"
send \"n\r\"
expect \"name\"
send \"wptangtoc\r\"
expect \"Storage\"
send \"drive\r\"
expect \"client_id\"
send \"\r\"
expect \"client_secret\"
send \"\r\"
expect \"scope\"
send \"1\r\"
expect \"root_folder_id\"
send \"\r\"
expect \"service_account_file\"
send \"\r\"
expect \"n\"
send \"n\r\"
expect \"n\"
send \"n\r\"
expect \"verification\"
send \"$checkid\r\"
expect \"n\"
send \"n\r\"
expect \"n\"
send \"y\r\"
expect eof
")

checkdathietlapxacthuc=$(grep -rnw '/root/.config/rclone/rclone.conf' -e "wptangtoc" >>/dev/null 2>&1 && echo 2)
if [[ $checkdathietlapxacthuc ]]; then
	echo "==================================================================================="
	echo "Thiet lap Google Driver hoan tat"
	echo "==================================================================================="

else
	echo "==================================================================================="
	echo "Thiet lap Google Driver khong thanh cong"
	echo "==================================================================================="
fi
