#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2025

function huong_dan(){
Tính năng xóa file backup thủ công đơn giản là việc bạn tự tay lựa chọn và xóa các tệp tin hoặc thư mục sao lưu [backup] không còn cần thiết nữa.

Khi nào cần dùng:

* Khi bạn cần giải phóng dung lượng lưu trữ ngay lập tức.
* Khi bạn biết chắc chắn một bản sao lưu cụ thể không còn giá trị hoặc bị lỗi.
* Để dọn dẹp đột xuất ngoài lịch trình tự động.

Lưu ý quan trọng: Việc xóa thủ công cần cẩn trọng để tránh vô tình xóa nhầm những bản sao lưu quan trọng mà bạn có thể cần đến sau này.
}

echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao lưu & khôi phục => Xóa file sao luu Backup		                  |"
echo "========================================================================="
. /etc/wptt/.wptt.conf
. /etc/wptt/tenmien
. /etc/wptt/echo-color
echo ""
echo ""
echo "Lựa chọn website bạn muốn xóa file sao lưu Backup: "
echo ""
lua_chon_NAME


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt/wptt-backup-restore-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
	. /etc/wptt/wptt-backup-restore-main 1
    exit
fi

if [ ! "$(ls -A /usr/local/backup-website/$NAME)" ]; then
    clear
    echoDo "Không có file backup nào tồn tại."
	sleep 3
	. /etc/wptt/wptt-backup-restore-main 1
	exit
fi

echo "========================================================================="
echo "Xóa file backup trong thư mục: /usr/local/backup-website/$NAME"
echo "========================================================================="

a=1
for entry in $(ls -At /usr/local/backup-website/$NAME); do
a=$((a+1));
done

if [[ $sql_gz ]];then
b=1
for entry in $(ls -At /usr/local/backup-website/$NAME | grep '.sql.gz$'); do
b=$((b+1));
done
fi

if [[ $sql_gz = '' ]];then
b=1
for entry in $(ls -At /usr/local/backup-website/$NAME | grep '.sql$'); do
b=$((b+1));
done
fi

c=1
for entry in $(ls -At /usr/local/backup-website/$NAME | grep '.zip$'); do
c=$((c+1));
done

echo "========================================================================="
echo "Số lượng file Database: $((b-1))"
echo "Số lượng file Zip mã nguồn: $((c-1))"
echo "Tổng files: $((a-1))"
echo "========================================================================="

a="y"
while [[ $a = "y" ]]
do

selects=()
for entry in $(ls -At /usr/local/backup-website/$NAME); do
	selects+=("$entry")
done

PS3="
-//- Nhập lựa chọn của bạn [0=Thoát]: "
select select in ${selects[@]}; do
	file=$select
	break
done
pathcheck="/usr/local/backup-website/$NAME"
before_delete=$(du -hs "$pathcheck"|sed 's/\t//g'| cut -f1 -d '/')

if [[ "$file" = "" || "$file" = '0' ]]; then
	. /etc/wptt/wptt-backup-restore-main 1
fi

duong_dan_thu_muc="/usr/local/backup-website/$NAME/$file"

if [[ ! -f "$duong_dan_thu_muc" ]];then
	echoDo "Không có file nào tồn tại trong thư mục: /usr/local/backup-website/$NAME"
	. /etc/wptt/wptt-backup-restore-main 1
fi

echo "Bạn có muốn xóa file backup $file không? "
prompt="Nhập lựa chọn của bạn [1-2]: "
dongy="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			dongy="y"
			break
			;;

		2)
			dongy="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done

if [[ "$dongy" = "y" ]]; then
	rm -f $duong_dan_thu_muc
	echo "Xoá file backup website $NAME ($duong_dan_thu_muc): $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log
	echoDone "Xóa file $file backup của website $NAME thành công"
	echo "==================================================================="
	echo "Dung luong thu muc truoc khi xoa	: ${before_delete}B"
	echo "Dung luong thu muc sau khi xoa		: $(du -hs $pathcheck| sed 's/\t//g'| cut -f1 -d '/')B"
	echo "==================================================================="
fi

if [[ $dongy = 'n' ]];then
. /etc/wptt/wptt-backup-restore-main 1
fi

if [[ $(ls /usr/local/backup-website/$NAME | grep ".zip$\|.sql$\|.sql.gz$") ]] ;then
echo "Bạn có muốn tiếp tục xóa file backup nữa không?: "
prompt="Nhập lựa chọn của bạn [1-2]: "
a="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			a="y"
			break
			;;

		2)
			a="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done
else
	a='n'
fi

done

disk=$(mount|grep ' / '|cut -d' ' -f 1)
disk_kha_dung=$(df -T -h | grep $disk | awk -F ' ' '{print $5}' | tr -d 'a-zA-G')
het_disk="2"

if [[ $(echo $disk_kha_dung | grep '.') ]];then
	if [[ $(echo $disk_kha_dung | wc -c) = 4 ]];then
		disk_kha_dung=$(echo $disk_kha_dung | tr -d '.')
		het_disk="20"
	fi
fi


if [[ $(echo $disk_kha_dung | grep '.') ]];then
	if [[ $(echo $disk_kha_dung | wc -c) = 5 ]];then
		disk_kha_dung=$(echo $disk_kha_dung | tr -d '.')
		het_disk="200"
	fi
fi


if [[ $disk_kha_dung ]];then
	if (( "$disk_kha_dung" < "$het_disk" ));then
		RED='\033[0;33m'
		NC='\033[0m'
		echo -e "${RED}==================================================================="
		echo 'Cảnh báo FULLDISK khi disk ổ cứng còn dưới: 2GB'
		echo "Disk: $(df -h | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')"
		echo "Để kiểm tra dung lượng ổ cứng đang được sử dụng như thế nào - Gõ lệnh: wptt disk"
		echo -e "=================================================================== ${NC}"
	fi
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-backup-restore-main 1
fi

