#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao lưu & khôi phục => Sao lưu website                                 |"
echo "========================================================================="
. /etc/wptt/echo-color
NAME=$1
ggdriver=$2
ggdriver2=$3

if [[ $NAME = "98" ]];then
NAME=""
fi

if [[ "$NAME" = "" ]]; then
    . /etc/wptt/tenmien
    echo ""
    echo ""
    echo "Lựa chọn website bạn muốn sao lưu backup: "
    echo ""
    lua_chon_NAME

	if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
		. /etc/wptt/wptt-backup-restore-main 1
	fi

	pathcheck="/etc/wptt/vhost/.$NAME.conf"
	if [[ ! -f "$pathcheck" ]]; then
		clear
		echoDo "Tên miền không tồn tại trên hệ thống này"
		sleep 3
		. /etc/wptt/wptt-backup-restore-main 1
		exit
	fi
fi

pathcheck="/usr/local/backup-website/$NAME"
before_optimize=$(du -hs $pathcheck | sed 's/\t//g'| cut -f1 -d '/')
times=$(date +%Hgio\_%d\_%m\_%Y)
. /etc/wptt/.wptt.conf
. /etc/wptt/vhost/."$NAME".conf
cd /usr/local/lsws/"$NAME"/html

_runing "Sao lưu database website $NAME"

if [[ $sql_gz = '' ]];then
mysqldump -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web" >/usr/local/backup-website/$NAME/$NAME$times.sql
fi


if [[ $sql_gz ]];then
mysqldump -u "$DB_User_web" -p"$DB_Password_web" "$DB_Name_web" | gzip >/usr/local/backup-website/$NAME/$NAME$times.sql.gz
fi


if [[ $sql_gz = '' ]];then
check_file_error_database=$(du -c /usr/local/backup-website/$NAME/$NAME$times.sql | awk '{print $1}' | sed '1d')
if (( $check_file_error_database < 10 ));then
tuanxacnhandb="0"
_runloi "Sao lưu database website $NAME"
echo "========================================================================="
echo "Sao lưu backup database không thành công."
echo "========================================================================="
rm -f /usr/local/backup-website/$NAME/$NAME$times.sql
fi
fi


if [[ $sql_gz ]];then
check_file_error_database=$(du -c /usr/local/backup-website/$NAME/$NAME$times.sql.gz | awk '{print $1}' | sed '1d')
if (( $check_file_error_database < 10 ));then
tuanxacnhandb="0"
_runloi "Sao lưu database website $NAME"
echo "========================================================================="
echo "Sao lưu backup database không thành công."
echo "========================================================================="
rm -f /usr/local/backup-website/$NAME/$NAME$times.sql.gz
fi
fi


if [[ -f /usr/local/backup-website/$NAME/$NAME$times.sql || -f /usr/local/backup-website/$NAME/$NAME$times.sql.gz ]];then
_rundone "Sao lưu database website $NAME"
tuanxacnhandb="1"
else
_runloi "Sao lưu database website $NAME"
fi


_runing "Sao lưu mã nguồn website $NAME"
echo ''
cd /usr/local/lsws/"$NAME"/html && zip -r /usr/local/backup-website/$NAME/$NAME$times.zip * -x "wp-content/ai1wm-backups/*" -x "wp-content/cache/*" -x "wp-content/updraft/*" -x "wp-content/ai1wm-backups/*" -x "error_log" -x "wp-content/debug.log" -x "wp-content/uploads/backupbuddy_backups/*" -x "wp-content/backups-dup-pro/*" -x "wp-content/backups-dup-lite/*"

if [[ -f /usr/local/backup-website/$NAME/$NAME$times.zip ]];then
_rundone "Sao lưu mã nguồn website $NAME"
tuanxacnhan="1"
else
_runloi "Sao lưu mã nguồn website $NAME"
fi

checkdathietlap=$(grep -rnw '/root/.config/rclone/rclone.conf' -e "wptangtoc" >>/dev/null 2>&1 && echo 1)
if [[ $checkdathietlap ]]; then
    if [[ "$ggdriver" != "1998" ]]; then
		if [[ $(cat ~/.config/rclone/rclone.conf | grep 'onedrive') ]];then
			echo "Bạn có muốn uploads file backup lên lưu trữ đám mây OneDriver không?"
		else
			echo "Bạn có muốn uploads file backup lên lưu trữ đám mây Google Driver không?"
		fi
		prompt="Nhập lựa chọn của bạn [1-2]: "
		uploads="n"
		options=("Đồng ý" "Không đồng ý")
		PS3="$prompt"
		select opt in "${options[@]}"; do
			case "$REPLY" in
				1)
					uploads="y"
					break
					;;

				2)
					uploads="n"
					break
					;;

				$((${#options[@]} + 1)))
					printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
					break
					;;
				*)
					printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
					break
					;;
			esac
		done
    fi
    if [[ "$uploads" = "y" || "$ggdriver" = "1998" ]]; then

			if [[ $(cat ~/.config/rclone/rclone.conf | grep 'onedrive') ]];then
		_runing "Uploads file backup lên OneDrive"
			else
		_runing "Uploads file backup lên Google Drive"
			fi

        truoc_khi=$(rclone size wptangtoc:wptangtoc_ols_backup)
		rclone copy /usr/local/backup-website/"$NAME"/$NAME$times.zip wptangtoc:wptangtoc_ols_backup/$NAME
		if [[ $sql_gz = '' ]];then
			rclone copy /usr/local/backup-website/"$NAME"/$NAME$times.sql wptangtoc:wptangtoc_ols_backup/$NAME
		fi

		if [[ $sql_gz ]];then
			rclone copy /usr/local/backup-website/"$NAME"/$NAME$times.sql.gz wptangtoc:wptangtoc_ols_backup/$NAME
		fi

		if [[ $(cat ~/.config/rclone/rclone.conf | grep 'onedrive') ]];then
			_rundone "Uploads file backup lên OneDrive"
		else
			_rundone "Uploads file backup lên Google Drive"
		fi

        if ! [[ "$ggdriver2" = "1998" || "$ggdriver2" = "12345" ]]; then

			echo "Bạn có muốn xóa file backup tại local khi đã được lưu trữ đám mây Google Driver không?"
			prompt="Nhập lựa chọn của bạn [1-2]: "
			clearfile="n"
			options=("Đồng ý" "Không đồng ý")
			PS3="$prompt"
			select opt in "${options[@]}"; do
				case "$REPLY" in
					1)
						clearfile="y"
						break
						;;

					2)
						clearfile="n"
						break
						;;

					$((${#options[@]} + 1)))
						printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
						break
						;;
					*)
						printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
						break
						;;
				esac
			done


		fi
		if [[ "$clearfile" = "y" || "$ggdriver2" = "1998" ]]; then
			_runing "Xóa file backup tại local"
			rm -f /usr/local/backup-website/"$NAME"/$NAME$times.zip
			if [[ $sql_gz = '' ]];then
				rm -f /usr/local/backup-website/"$NAME"/$NAME$times.sql
			fi
			if [[ $sql_gz ]];then
				rm -f /usr/local/backup-website/"$NAME"/$NAME$times.sql.gz
			fi
			_rundone "Xóa file backup tại local"
		fi

	fi
fi

clear
if [[ "$tuanxacnhandb" = "1" && "$tuanxacnhan" = "1" ]];then

echo "==================================================================="
echo "BackUp website $NAME thành công                 "
echo "==================================================================="
echo "Disk : $(df -BG | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')                        "
echo "Đường dẫn thư mục lưu trữ backup	: /usr/local/backup-website/$NAME         "
echo "Đường dẫn thư mục website	: /usr/local/lsws/$NAME/html              "
echo "==================================================================="
echo "Dung lượng thư mục trước khi backup	: $before_optimize"
echo "Dung lượng thư mục sau khi backup	: $(du -hs $pathcheck|sed 's/\t//g'| cut -f1 -d '/')"
else
echo "==================================================================="
echo "BackUp website $NAME thất bại                 "
echo "==================================================================="
fi

# disk=$(mount|grep ' / '|cut -d' ' -f 1)

disk=$(df -BG| awk '$NF=="/"{printf "%d/%d\n", $3,$2,$5}') 
disk_dang_dung=$(echo $disk | cut -f1 -d '/')
disk_tong=$(echo $disk | cut -f2 -d '/'| cut -f1 -d ' ')
disk_kha_dung=$(expr $disk_tong - $disk_dang_dung)

# disk_kha_dung=$(df -T -h | grep $disk | awk -F ' ' '{print $5}' | tr -d 'a-zA-G' | sed "s:\.:,:g")

het_disk="2"
if [[ $disk_kha_dung =~ ^-?[0-9]+$ ]];then
if (( "$disk_kha_dung" < "$het_disk" ));then
RED='\033[0;33m'
NC='\033[0m'
echo -e "${RED}==================================================================="
echo "Cảnh báo FULLDISK khi disk còn dưới: 2GB"
echo "Disk: $(df -BG | awk '$NF=="/"{printf "%d/%dGB (%s)\n", $3,$2,$5}')"
echo "Để kiểm tra dung lượng ổ cứng đang được sử dụng như thế nào - gõ lệnh: wptt disk"
echo -e "=================================================================== ${NC}"
fi
fi


echo "==================================================================="
if [[ "$uploads" = "y" ]]; then
	#check onedrive hay google drive
	if [[ $(cat ~/.config/rclone/rclone.conf | grep 'onedrive') ]];then
		echo "==================================================================="
		echo "Dung lượng OneDrive của bạn		: $(rclone size wptangtoc:| grep 'size' | cut -f2 -d ':' | cut -f1 -d '(')"
		echo "==================================================================="
	else
		echo "==================================================================="
		echo "Dung lượng Google Drive của bạn		: $(rclone size wptangtoc:| grep 'size' | cut -f2 -d ':' | cut -f1 -d '(')"
		echo "==================================================================="
	fi
fi
echo "==================================================================="
echo "Phần mềm phát triển bởi	: Gia Tuấn"
echo "==================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-backup-restore-main 1
fi

