#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao luu & khoi phuc => Tai file backup tu Google Driver                |"
echo "========================================================================="
echo ""
echo ""

checkactivate=$(grep -rnw '/root/.config/rclone/rclone.conf' -e "wptangtoc" >>/dev/null 2>&1 && echo 2)
if [[ "$checkactivate" = "2" ]]; then
    google=4
else
    echo "ban chua kich hoat rclone google driver"
    . /etc/wptt/wptt-backup-restore-main
    exit
fi
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lua chon website ban muon tai file tu luu tru dam may Google Driver : "
echo ""
lua_chon_NAME
pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-backup-restore-main
    exit
fi

selects=()

if [[ "$google" = "4" ]]; then
    echo "Dang Tai danh sach tu Google Driver..."
    x=$(rclone lsf wptangtoc:wptangtoc_ols_backup/"$NAME")
    while IFS= read -r line; do selects+=("$line"); done <<<"$x"
fi
PS3="
-//- Nhap lua chon cua ban [0=Thoat]: "
select select in ${selects[@]}; do
    file=$select
    break
done

if [[ "${file}" ]]; then

    read -p "Xac nhan de download File (y/n): " dongy_taifile

    if [[ "$dongy_taifile" = 'y' ]]; then
    echo '               .::------------:--                
               -==-------------=##+               
              -====-----------+####*.             
            .=======---------+######*.            
           .=========-------*#########:           
          .============----*###########-          
         :==============--*#############-         
        :===============-+###############=        
       -===============:  =###############+       
      -===============:    =###############+      
     -===============:      -###############*.    
   .================.        :###############*.   
  .================.          :################:  
 .===============-.            .*###############: 
:===============-                +###############-
----------------:................:+***************
:--------------==================================:
 :------------==================================: 
  .----------==================================:  
   .-------===================================:   
    .-----===================================.    
      :--===================================.     
       .-================================-:       
'
        echo "Dang tien hanh qua trinh tai file $file tu Gooogle Driver..."
        rm -f /usr/local/backup-website/"$NAME"/"$file"
        rclone copy wptangtoc:wptangtoc_ols_backup/"$NAME"/"$file" /usr/local/backup-website/"$NAME"
        echo "Qua trinh tai $file ve hoan tat"
    fi
fi
echo ""
tuancheck=$(echo "$file" | grep -c ".zip")
tuancheck2=$(echo "$file" | grep -c ".sql")

if [[ "$tuancheck" = "1" ]]; then
    echo "Ban da tai file ma nguon .zip roi ban co muon tai them file database .sql nua khong?"
    ggdrthem="file sql database"

fi

if [[ "$tuancheck2" = "1" ]]; then
    echo "Ban da tai file database .sql roi ban co muon tai them file ma nguon .zip nua khong?"
    ggdrthem="file zip ma nguon"

fi

read -p "Ban co muon tiep tuc tai them $ggdrthem nua khong (y/n): " dongy_taitiep
if [[ "$dongy_taitiep" = 'y' ]]; then
    selects=()

    if [[ "$google" = "4" ]]; then
    echo '               .::------------:--                
               -==-------------=##+               
              -====-----------+####*.             
            .=======---------+######*.            
           .=========-------*#########:           
          .============----*###########-          
         :==============--*#############-         
        :===============-+###############=        
       -===============:  =###############+       
      -===============:    =###############+      
     -===============:      -###############*.    
   .================.        :###############*.   
  .================.          :################:  
 .===============-.            .*###############: 
:===============-                +###############-
----------------:................:+***************
:--------------==================================:
 :------------==================================: 
  .----------==================================:  
   .-------===================================:   
    .-----===================================.    
      :--===================================.     
       .-================================-:       
'
        echo "Dang tai danh sach tu Google Driver..."
        x=$(rclone lsf wptangtoc:wptangtoc_ols_backup/$NAME)
        while IFS= read -r line; do selects+=("$line"); done <<<"$x"
    fi
    PS3="
-//- Nhap lua chon cua ban [0=Thoat]: "
    select select in ${selects[@]}; do
        file2=$select
        break
    done

    if [[ "${file2}" ]]; then

        read -p "Xac nhan de download File (y/n): " dongy_taifile2
        if [[ "$dongy_taifile2" = 'y' ]]; then
            echo "Dang tien hanh qua trinh tai file $file2 tu Gooogle Driver..."
            rm -f /usr/local/backup-website/"$NAME"/"$file2"
            rclone copy wptangtoc:wptangtoc_ols_backup/"$NAME"/"$file2" /usr/local/backup-website/"$NAME"
        fi
    fi
fi

if [[ "$dongy_taifile" = 'y' && -f /usr/local/backup-website/$NAME/$file ]]; then
    echo "Qua trinh tai hoan tat - Thu muc luu tru tai: /usr/local/backup-website/$NAME/$file"
else
    echo "Qua trinh download file Backup tu Google Driver da xay ra loi"
    echo '                                              
                   .:::....                   
                 .--=+++=-::.                 
                :--*%%%%%%+::.                
               :--*%%%%%%%%*:::               
              ---#%%%%%#%%%%*:::              
            .--=#%%%#=--=#%%%#-::             
           .--=%%%%%*:-:.*%%%%#-::.           
          .--+%%%%%%*---:*%%%%%#=::.          
         :--*%%%%%%%*--::*%%%%%%#+::.         
        :--*%%%%%%%%*--::*%%%%%%%#+:::        
       ---#%%%%%%%%%*--::*%%%%%%%%#*:::       
      --=#%%%%%%%%%%*---:*%%%%%%%%%#*-::      
    .--=%%%%%%%%%%%%#--::#%%%%%%%%%%##-::     
   .--+%%%%%%%%%%%%%%#*+#%%%%%%%%%%%%##=::.   
  :--+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##=::.  
 :--*%%%%%%%%%%%%%%%#=-:-#%%%%%%%%%%%%%##+::. 
:--*%%%%%%%%%%%%%%%%#--::#%%%%%%%%%%%%%%##+::.
--=%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%###-::
:--*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##+::.
 :--=++***************++++++++++++++++++=-::. 
   .:::::::::::::::::::....................   
                                              
'
fi

if [[ "$dongy_taitiep" = "y" ]]; then
    if [[ "$dongy_taifile2" = 'y' && -f /usr/local/backup-website/$NAME/$file2 ]]; then
        echo "Qua trinh tai hoan tat - Thu muc luu tru tai: /usr/local/backup-website/$NAME/$file2"
    else
        echo "Qua trinh download file backup tu Google Driver da xay ra loi"
        echo '                                              
                   .:::....                   
                 .--=+++=-::.                 
                :--*%%%%%%+::.                
               :--*%%%%%%%%*:::               
              ---#%%%%%#%%%%*:::              
            .--=#%%%#=--=#%%%#-::             
           .--=%%%%%*:-:.*%%%%#-::.           
          .--+%%%%%%*---:*%%%%%#=::.          
         :--*%%%%%%%*--::*%%%%%%#+::.         
        :--*%%%%%%%%*--::*%%%%%%%#+:::        
       ---#%%%%%%%%%*--::*%%%%%%%%#*:::       
      --=#%%%%%%%%%%*---:*%%%%%%%%%#*-::      
    .--=%%%%%%%%%%%%#--::#%%%%%%%%%%##-::     
   .--+%%%%%%%%%%%%%%#*+#%%%%%%%%%%%%##=::.   
  :--+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##=::.  
 :--*%%%%%%%%%%%%%%%#=-:-#%%%%%%%%%%%%%##+::. 
:--*%%%%%%%%%%%%%%%%#--::#%%%%%%%%%%%%%%##+::.
--=%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%###-::
:--*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##+::.
 :--=++***************++++++++++++++++++=-::. 
   .:::::::::::::::::::....................   
                                              
'
    fi
fi
