#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @email: giatuan@wptangtoc.com
# @since: 2022
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao lưu & khôi phục => Thiết lập tự động sao lưu database               |"
echo "========================================================================="
echo ""
echo ""
if [ "$(ls -A /etc/wptt/vhost)" ]; then
	echo "========================================================================="
	echo "Danh sách domain đã kích hoạt tự động backup database:"
	echo "========================================================================="
	for entry in $(ls -A /etc/wptt/vhost); do
		domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
		path="/etc/cron.d/backup-database$domain.cron"
		i=1
		if [[ -f "$path" ]]; then
			checkauto="Đã kích hoạt tự động lúc "
			checkauto1=$(cat /etc/cron.d/backup-database$domain.cron | cut -f2 -d " ")
			checkauto2=$(cat /etc/cron.d/backup-database$domain.cron | cut -f5 -d " ")
			kiemtra_doi_so=$(grep -c "1998" /etc/wptt-auto/$domain-auto-backup-database)
			if [[ "$kiemtra_doi_so" = "0" ]]; then
				tinhnang=""
			fi

			if [[ "$kiemtra_doi_so" = "1" ]]; then
				tinhnang="| backup xong uploads lên Gooole Driver"
			fi

			if [[ "$kiemtra_doi_so" = "2" ]]; then
				tinhnang="| backup xong uploads lên Gooole Driver và xóa luôn file backup tại local"
			fi

			if [ "$checkauto2" = "0" ] || [ "$checkauto2" = "7" ]; then
				thu123=" giờ chủ nhật hàng tuần"
			fi
			if [ "$checkauto2" = "1" ]; then
				thu123=" giờ thứ hai hàng tuần"
			fi
			if [ "$checkauto2" = "2" ]; then
				thu123=" giờ thứ ba hàng tuần"
			fi
			if [ "$checkauto2" = "3" ]; then
				thu123=" giờ thứ tư hàng tuần"
			fi
			if [ "$checkauto2" = "4" ]; then
				thu123=" giờ thứ năm hàng tuần"
			fi
			if [ "$checkauto2" = "5" ]; then
				thu123=" giờ thứ sáu hàng tuần"
			fi
			if [ "$checkauto2" = "6" ]; then
				thu123=" giờ thứ bảy hàng tuần"
			fi

			if [ "$checkauto2" = "*" ]; then
				thu123=" giờ hàng ngày"
			fi

		else

			checkauto="Chưa được kích hoạt"
			checkauto1=""
			checkauto2=""
			thu123=" tự động sao lưu backup database"
			tinhnang=""
		fi
		echo "Website $domain $checkauto$checkauto1$thu123 $tinhnang"
	done
	echo "========================================================================="
	echo
fi

. /etc/wptt/.wptt.conf

function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ ! -f /etc/cron.d/backup-database$NAME.cron ]]; then
				selects+=("$NAME")
			fi
		done

if [[ $selects = '' ]];then
echo "Tất cả domain trên hệ thống đã được kích hoạt sao lưu backup database tự động hết rồi"
. /etc/wptt/wptt-backup-restore-main 1
fi

		PS3="
-//- Nhập lựa chọn website của bạn [0=Thoát]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Không xác định được domain nào."
		exit
	fi
}

echo ""
echo ""
echo "Lựa chọn website bạn muốn thiết lập tự động backup sao lưu database: "
echo ""
lua_chon_NAME


. /etc/wptt/echo-color
if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
	. /etc/wptt/wptt-backup-restore-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
	. /etc/wptt/wptt-backup-restore-main 1
    exit
fi


if [ -f /etc/cron.d/backup-database$NAME.cron ]; then
	echoDo "website $NAME đã được kích hoạt tự động sao lưu backup trước đó rồi!"
	sleep 3
	. /etc/wptt/wptt-backup-restore-main 1
	exit
fi

. /etc/wptt/vhost/."$NAME".conf

echo -n "Bạn muốn tự động backup website lúc mấy giờ? [0-23]: "
read gio

if [[ ! $gio =~ ^-?[0-9]+$ ]]; then
	echo "Bạn nhập sai dữ liệu thời gian từ 0 đến 23, hệ thống sẽ tự động chọn giá trị là 1h sáng"
	gio="1"
fi

if (( "$gio" > "23" )); then
	echo "Bạn nhập sai dữ liệu thời gian từ 0 đến 23, hệ thống sẽ tự động chọn giá trị là 1h sáng"
	gio="1"
fi

if [[ "$gio" = "" ]]; then
	gio="1"
	echo "Bạn không nhập dữ liệu hệ thống sẽ tự động chọn là 1h sáng"
fi

echo "Bạn muốn tự động backup website vào thứ mấy? "
echo ""
. /etc/wptt/wptt-times-tuan
tuan

if [ "$thu" = "0" ] || [ "$thu" = "7" ]; then
	thu12="chủ nhật hàng tuần"
fi
if [ "$thu" = "1" ]; then
	thu12="thứ hai hàng tuần"
fi
if [ "$thu" = "2" ]; then
	thu12="thứ ba hàng tuần"
fi
if [ "$thu" = "3" ]; then
	thu12="thứ tư hàng tuần"
fi
if [ "$thu" = "4" ]; then
	thu12="thứ năm hàng tuần"
fi
if [ "$thu" = "5" ]; then
	thu12="thứ sáu hàng tuần"
fi
if [ "$thu" = "6" ]; then
	thu12="thứ bảy hàng tuần"
fi

if [ "$thu" = "*" ]; then
	thu12="hàng ngày"
fi

echo "Bạn có chắc chắn muốn tự động sao lưu database $NAME lúc $gio giờ $thu12 ?"

prompt="Nhập lựa chọn của bạn [1-2]: "
response="n"
options=("Đồng ý" "Không đồng ý")
PS3="$prompt"
select opt in "${options[@]}"; do
	case "$REPLY" in
		1)
			response="y"
			break
			;;

		2)
			response="n"
			break
			;;

		$((${#options[@]} + 1)))
			printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
		*)
			printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
			break
			;;
	esac
done


if [[ "$response" = "y" ]]; then
	mkdir -p /etc/wptt-auto
	mkdir -p /usr/local/backup-website/"$NAME"

	checkdathietlap=$(grep -rnw '/root/.config/rclone/rclone.conf' -e "wptangtoc" >>/dev/null 2>&1 && echo 1)
	if [[ $checkdathietlap ]]; then
		echo "Bạn có muốn uploads file backup tự động lên lưu trữ đám mây Google Driver không?"
		prompt="Nhập lựa chọn của bạn [1-2]: "
		uploads="n"
		options=("Đồng ý" "Không đồng ý")
		PS3="$prompt"
		select opt in "${options[@]}"; do
			case "$REPLY" in
				1)
					uploads="y"
					break
					;;

				2)
					uploads="n"
					break
					;;

				$((${#options[@]} + 1)))
					printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
					break
					;;
				*)
					printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
					break
					;;
			esac
		done


		if [[ "$uploads" = "y" ]]; then

			tuan1="1998"
			echo "Khi đã uploads lên Google Driver bạn có muốn tự động xóa file backup tại local không?"
			prompt="Nhập lựa chọn của bạn [1-2]: "
			delete="n"
			options=("Đồng ý" "Không đồng ý")
			PS3="$prompt"
			select opt in "${options[@]}"; do
				case "$REPLY" in
					1)
						delete="y"
						break
						;;

					2)
						delete="n"
						break
						;;

					$((${#options[@]} + 1)))
						printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
						break
						;;
					*)
						printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
						break
						;;
				esac
			done


			if [[ "$delete" = "y" ]]; then
				tuan2="1998"
			else
				tuan2="12345"
			fi

		fi
	fi
	cat >"/etc/wptt-auto/$NAME-auto-backup-database" <<END
#!/bin/bash
. /etc/wptt/db/wptt-saoluu-database $NAME $tuan1 $tuan2
END
	chmod 740 /etc/wptt-auto/$NAME-auto-backup-database

	cat >"/etc/cron.d/backup-database$NAME.cron" <<END
0 $gio * * $thu root /etc/wptt-auto/$NAME-auto-backup-database >/dev/null 2>&1
END

	systemctl restart crond.service

	echo "-------------------------------------------------------------------------"
	echo "website $NAME sẽ được tự động sao lưu database vào $gio giờ $thu12 .      "
	echo "-------------------------------------------------------------------------"
	echo "Duong dan luu tru thu muc backup database :/usr/local/backup-website/$NAME   "
	if [[ "$uploads" = "y" ]]; then
		echo "-------------------------------------------------------------------------"
		echo "File backup trên Google Driver sẽ tự động lưu trữ tại thư mục: wptangtoc_ols_backup/$NAME"
	fi
	echo "-------------------------------------------------------------------------"
	echo "Nếu cần khôi phục lại website thì bạn hãy truy cập vào menu của WPTangToc OLS rồi sử dụng tính năng khôi phục website"
	echo "-------------------------------------------------------------------------"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-backup-restore-main 1
fi

