#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao lưu & khôi phục => Tải file backup từ Google Driver                |"
echo "========================================================================="
echo ""
echo ""

checkactivate=$(grep -rnw '/root/.config/rclone/rclone.conf' -e "wptangtoc" >>/dev/null 2>&1 && echo 2)
if [[ "$checkactivate" = "2" ]]; then
    google=4
else
    echo "Hệ thống của bạn chưa kích hoạt rclone Google Driver"
    . /etc/wptt/wptt-backup-restore-main
    exit
fi
echo "========================================================================="
. /etc/wptt/tenmien
echo ""
echo ""
echo "Lựa chọn website bạn muốn tải file từ lưu trữ đám mây Google Driver : "
echo ""
lua_chon_NAME


if [[ "$NAME" = "0" || "$NAME" = "" ]]; then
    . /etc/wptt/wptt-backup-restore-main 1
fi

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" ]]; then
    clear
	echoDo "Tên miền không tồn tại trên hệ thống này"
    sleep 3
    . /etc/wptt/wptt-backup-restore-main 1
    exit
fi

. /etc/wptt/echo-color
selects=()

if [[ "$google" = "4" ]]; then
    echo "Đang tiến hành tải danh sách từ Google Driver..."
    x=$(rclone lsf wptangtoc:wptangtoc_ols_backup/"$NAME")
    while IFS= read -r line; do selects+=("$line"); done <<<"$x"
fi
PS3="
-//- Nhap lua chon cua ban [0=Thoat]: "
select select in ${selects[@]}; do
    file=$select
    break
done

if [[ "${file}" ]]; then

    read -p "Xác nhận để download File (y/n): " dongy_taifile

    if [[ "$dongy_taifile" = 'y' ]]; then
    echo '               .::------------:--                
               -==-------------=##+               
              -====-----------+####*.             
            .=======---------+######*.            
           .=========-------*#########:           
          .============----*###########-          
         :==============--*#############-         
        :===============-+###############=        
       -===============:  =###############+       
      -===============:    =###############+      
     -===============:      -###############*.    
   .================.        :###############*.   
  .================.          :################:  
 .===============-.            .*###############: 
:===============-                +###############-
----------------:................:+***************
:--------------==================================:
 :------------==================================: 
  .----------==================================:  
   .-------===================================:   
    .-----===================================.    
      :--===================================.     
       .-================================-:       
'
_runing "Tải $file từ Google Driver"
        rm -f /usr/local/backup-website/"$NAME"/"$file"
        rclone copy wptangtoc:wptangtoc_ols_backup/"$NAME"/"$file" /usr/local/backup-website/"$NAME"
_rundone "Tải $file từ Google Driver"
    fi
fi
echo ""
tuancheck=$(echo "$file" | grep -c ".zip")

. /etc/wptt/.wptt.conf
tuancheck2=$(echo "$file" | grep -c ".sql")

if [[ "$tuancheck" = "1" ]]; then
    echo "Bạn đã tải file ma nguon .zip roi ban co muon tai them file database .sql nữa không?"
    ggdrthem="file sql database"

fi

if [[ "$tuancheck2" = "1" ]]; then
    echo "Bạn đã tải file database .sql rồi bạn có muốn tải thêm file mã nguồn nguồn .zip nữa không?"
    ggdrthem="file zip mã nguồn"

fi

read -p "Bạn có muốn tiếp tục tải thêm $ggdrthem nữa không (y/n): " dongy_taitiep
if [[ "$dongy_taitiep" = 'y' ]]; then
    selects=()

    if [[ "$google" = "4" ]]; then
    echo '               .::------------:--                
               -==-------------=##+               
              -====-----------+####*.             
            .=======---------+######*.            
           .=========-------*#########:           
          .============----*###########-          
         :==============--*#############-         
        :===============-+###############=        
       -===============:  =###############+       
      -===============:    =###############+      
     -===============:      -###############*.    
   .================.        :###############*.   
  .================.          :################:  
 .===============-.            .*###############: 
:===============-                +###############-
----------------:................:+***************
:--------------==================================:
 :------------==================================: 
  .----------==================================:  
   .-------===================================:   
    .-----===================================.    
      :--===================================.     
       .-================================-:       
'
        echo "Đang tiến hành tải danh sách từ Google Driver..."
        x=$(rclone lsf wptangtoc:wptangtoc_ols_backup/$NAME)
        while IFS= read -r line; do selects+=("$line"); done <<<"$x"
    fi
    PS3="
-//- Nhập lựa chọn của bạn [0=Thoát]: "
    select select in ${selects[@]}; do
        file2=$select
        break
    done

    if [[ "${file2}" ]]; then

        read -p "Xác nhận để download File (y/n): " dongy_taifile2
        if [[ "$dongy_taifile2" = 'y' ]]; then
			_runing "Tải $file2 từ Google Driver"
            rm -f /usr/local/backup-website/"$NAME"/"$file2"
            rclone copy wptangtoc:wptangtoc_ols_backup/"$NAME"/"$file2" /usr/local/backup-website/"$NAME"
			_rundone "Tải $file2 từ Google Driver"
        fi
    fi
fi

if [[ "$dongy_taifile" = 'y' && -f /usr/local/backup-website/$NAME/$file ]]; then
RED='\033[1;32m'
NC='\033[0m'
echo -e "${RED}                                              
               ........               
          .......    .....            
       .:..                   .:::.   
     .:.                    .:::::::. 
    ::                    .:::::::::. 
   :.                   .::::::::::.  
  :.                  .::::::::::.    
 .:      ..:.       .::::::::::.      
 :.    .:::::::.  .::::::::::.     .: 
 :.    .:::::::::::::::::::.       .: 
 :.     .::::::::::::::::.         .: 
 .:       .::::::::::::.           :. 
  :.        .::::::::.            .:  
   :.         .::::.             .:   
    ::                          ::    
     .:.                      .:.     
       .::.                .::.       
          .......    .......          
               ........               

${NC}"
    echo "Qua trinh tai hoan tat - Thu muc luu tru tai: /usr/local/backup-website/$NAME/$file"
else
    echo "Qua trinh download file Backup tu Google Driver da xay ra loi"
vang='\033[1;33m'
NC='\033[0m'
echo -e "${vang}                                              
                   .:::....                   
                 .--=+++=-::.                 
                :--*%%%%%%+::.                
               :--*%%%%%%%%*:::               
              ---#%%%%%#%%%%*:::              
            .--=#%%%#=--=#%%%#-::             
           .--=%%%%%*:-:.*%%%%#-::.           
          .--+%%%%%%*---:*%%%%%#=::.          
         :--*%%%%%%%*--::*%%%%%%#+::.         
        :--*%%%%%%%%*--::*%%%%%%%#+:::        
       ---#%%%%%%%%%*--::*%%%%%%%%#*:::       
      --=#%%%%%%%%%%*---:*%%%%%%%%%#*-::      
    .--=%%%%%%%%%%%%#--::#%%%%%%%%%%##-::     
   .--+%%%%%%%%%%%%%%#*+#%%%%%%%%%%%%##=::.   
  :--+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##=::.  
 :--*%%%%%%%%%%%%%%%#=-:-#%%%%%%%%%%%%%##+::. 
:--*%%%%%%%%%%%%%%%%#--::#%%%%%%%%%%%%%%##+::.
--=%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%###-::
:--*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##+::.
 :--=++***************++++++++++++++++++=-::. 
   .:::::::::::::::::::....................  
${NC}"
fi

if [[ "$dongy_taitiep" = "y" ]]; then
    if [[ "$dongy_taifile2" = 'y' && -f /usr/local/backup-website/$NAME/$file2 ]]; then
        echo "Quá trình tải hoàn tất - thư mục lưu trữ tại: /usr/local/backup-website/$NAME/$file2"
    else
        echo "Quá trình download file backup từ Google Driver đã xảy ra lỗi"
vang='\033[1;33m'
NC='\033[0m'
echo -e "${vang}                                              
                   .:::....                   
                 .--=+++=-::.                 
                :--*%%%%%%+::.                
               :--*%%%%%%%%*:::               
              ---#%%%%%#%%%%*:::              
            .--=#%%%#=--=#%%%#-::             
           .--=%%%%%*:-:.*%%%%#-::.           
          .--+%%%%%%*---:*%%%%%#=::.          
         :--*%%%%%%%*--::*%%%%%%#+::.         
        :--*%%%%%%%%*--::*%%%%%%%#+:::        
       ---#%%%%%%%%%*--::*%%%%%%%%#*:::       
      --=#%%%%%%%%%%*---:*%%%%%%%%%#*-::      
    .--=%%%%%%%%%%%%#--::#%%%%%%%%%%##-::     
   .--+%%%%%%%%%%%%%%#*+#%%%%%%%%%%%%##=::.   
  :--+%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##=::.  
 :--*%%%%%%%%%%%%%%%#=-:-#%%%%%%%%%%%%%##+::. 
:--*%%%%%%%%%%%%%%%%#--::#%%%%%%%%%%%%%%##+::.
--=%%%%%%%%%%%%%%%%%%%##%%%%%%%%%%%%%%%%###-::
:--*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%##+::.
 :--=++***************++++++++++++++++++=-::. 
   .:::::::::::::::::::....................  
${NC}"
    fi
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-backup-restore-main 1
fi

