#!/bin/bash
echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao luu & khoi phuc => Tat thiet lap tu dong xoa File Sao luu website  |"
echo "========================================================================="


function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ -f /etc/cron.d/delete$NAME.cron ]]; then
				selects+=("$NAME")
			fi
		done
		PS3="
-//- Nhap lua chon website cua ban [0=Thoat]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Khong co domain duoc thiet lap tu dong xoa file backup truoc do tai tren he thong cua ban."
		exit
	fi
}

echo ""
echo ""
echo "Lua chon website ban muon tat tu dong file backup sao luu het han: "
echo ""
lua_chon_NAME

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
    clear
    . /etc/wptt/wptt-backup-restore-main
    exit
fi

if [ -f /etc/cron.d/delete$NAME.cron ]; then
    rm -f /etc/cron.d/delete$NAME.cron
	rm -f /etc/wptt-auto/$NAME-delete-backup
    systemctl restart crond.service
    echo "Ngung tu dong xoa file sao luu backup het han website $NAME thanh cong!"
else
    echo "Ban chua kich hoat sao luu backup tu dong"
    exit
fi


check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-backup-restore-main 1
fi

