#!/bin/bash
clear
echo ""
echo ""
echo ""
echo "==================================================================================="
echo "|Sao lưu & khôi phục => Hủy thiết lập Rclone backup lữu trữ đám mây               |"
echo "==================================================================================="
echo ""
echo ""
. /etc/wptt/echo-color
if [[ ! -d ~/.config/rclone ]];then
	echo "Bạn chưa thiết lập rclone lưu trữ lưu trữ đám mây"
	sleep 3
	. /etc/wptt/wptt-backup-restore-main 1
	exit
fi

checkdathietlap=$(grep -rnw '/root/.config/rclone/rclone.conf' -e "wptangtoc" >>/dev/null 2>&1 && echo 1)
if [[ $checkdathietlap ]]; then
	if [[ $(cat ~/.config/rclone/rclone.conf | grep 'onedrive') ]];then
		echo "Xác nhận xóa đăng ký OneDrive Rclone không?"
	else
		echo "Xác nhận xóa đăng ký Google Drive Rclone không?"
	fi
	prompt="Nhập lựa chọn của bạn [1-2]: "
	xacnhan="n"
	options=("Đồng ý" "Không đồng ý")
	PS3="$prompt"
	select opt in "${options[@]}"; do
		case "$REPLY" in
			1)
				xacnhan="y"
				break
				;;

			2)
				xacnhan="n"
				break
				;;

			$((${#options[@]} + 1)))
				printf "\nBạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
			*)
				printf "Bạn nhập sai hệ thống sẽ chọn là không đồng ý\n"
				break
				;;
		esac
	done


	if [[ $xacnhan = 'y' ]];then
		if [[ $(cat ~/.config/rclone/rclone.conf | grep 'onedrive') ]];then
			_runing "Hủy đăng ký OneDrive rclone"
		else
			_runing "Hủy đăng ký Google Driver rclone"
		fi
		rm -rf ~/.config/rclone
		if [[ $(cat ~/.config/rclone/rclone.conf | grep 'onedrive') ]];then
			_rundone "Hủy đăng ký OneDrive rclone"
		else
			_rundone "Hủy đăng ký Google Driver rclone"
		fi
	fi
else
	echo "Bạn chưa thiết lập rclone backup lưu trữ đám mây"
fi

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
	. /etc/wptt/wptt-backup-restore-main 1
fi

