#!/bin/bash
# @author: Gia Tuấn
# @website: https://wptangtoc.com
# @since: 2025

function huong_dan(){
Tính năng tự động xóa file backup hết hạn là một chức năng cho phép hệ thống tự động loại bỏ các bản sao lưu website cũ hoặc không còn cần thiết sau một khoảng thời gian nhất định hoặc khi chúng đã đạt đến [tuổi thọ] được định sẵn.

Nói đơn giản, bạn thiết lập quy tắc [ví dụ: chỉ giữ lại các bản sao lưu trong 30 ngày gần nhất]. Khi một bản sao lưu vượt quá giới hạn này, hệ thống sẽ tự động xóa nó đi.

Lợi ích chính:

* Tiết kiệm dung lượng lưu trữ: Ngăn chặn việc các bản sao lưu cũ tích tụ và chiếm hết không gian đĩa.
* Quản lý bản sao lưu hiệu quả: Giữ cho kho lưu trữ backup gọn gàng, dễ tìm kiếm khi cần.
* Tối ưu chi phí: Giảm chi phí lưu trữ, đặc biệt khi sử dụng các dịch vụ lưu trữ đám mây tính theo dung lượng.
=> Đây là một tính năng rất hữu ích và thường có trong các phần mềm sao lưu chuyên nghiệp,
}


echo ""
echo ""
echo ""
echo "========================================================================="
echo "|Sao lưu và khôi phục=> Thiết lập tự động xóa file Sao lưu website      |"
echo "========================================================================="
. /etc/wptt/.wptt.conf
echo ""
echo ""
if [ "$(ls -A /etc/wptt/vhost|sort -uV)" ]; then
	echo "========================================================================="
	echo "Danh sách domain đã kích hoạt tự động xóa file file backup hết hạn:"
	echo "========================================================================="
	for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
		domain=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
		path="/etc/cron.d/delete$domain.cron"
		i=1
		if [[ -f "$path" ]]; then
			checkauto="Đã kích hoạt giá trị thiết lập là "
			checktuan0=$(cat /etc/wptt-auto/$domain-delete-backup | grep "backup" |cut -f6 -d " " | sed 's/+//g')
			checktuan=$(expr $checktuan0 / 60 / 24 )
			themphut=" ngày"
		else
			checkauto="Chưa kích hoạt"
			checktuan=""
			themphut=""
		fi
		echo "Website $domain $checkauto$checktuan$themphut tự động xóa file backup hết hạn"
	done
	echo "========================================================================="
	echo
fi

function lua_chon_NAME() {
	NAME=""
	if [ "$(ls -At /etc/wptt/vhost)" ]; then
		selects=()
		for entry in $(ls -A /etc/wptt/vhost|sort -uV); do
			NAME=$(echo $entry | sed 's/^.//' | sed 's/.conf//')
			if [[ ! -f /etc/cron.d/delete$NAME.cron ]]; then
				selects+=("$NAME")
			fi
		done

if [[ $selects = '' ]];then
echo "Tất cả domain trên hệ thống đã được kích hoạt xóa file backup tự động hết rồi"
. /etc/wptt/wptt-backup-restore-main 1
fi


		PS3="
-//- Nhập lựa chọn website của bạn [0=Thoát]: "
		select select in ${selects[@]}; do
			NAME=$select
			index=$REPLY
			break
		done
	else
		clear
		echo "Khong co domain duoc thiet lap tu dong backup truoc do tai tren he thong cua ban."
		exit
	fi
}

echo ""
echo ""
echo "Lựa chọn website bạn muốn tự động file backup sao lưu hết hạn: "
echo ""
lua_chon_NAME

pathcheck="/etc/wptt/vhost/.$NAME.conf"
if [[ ! -f "$pathcheck" || "$NAME" = "0" ]]; then
	clear
	. /etc/wptt/wptt-backup-restore-main 1
	exit
fi

if [ -f /etc/cron.d/delete$NAME.cron ]; then
	echo "$NAME da kich hoat tu dong xoa backup het han truoc roi!"
	sleep 3
	. /etc/wptt/wptt-backup-restore-main 1
	exit
fi

. /etc/wptt/echo-color
read -p "Nhập số ngày bạn quy định là file backup hết hạn sử dụng
ví dụ: 10 hay 60 la số nguyên dương: " ngay

if [[ ! $ngay =~ ^-?[0-9]+$ ]]; then
	clear
	echo "So phut khong dung dinh dang"
	. /etc/wptt/wptt-backup-restore-main 1
	exit
fi

_runing "Thiết lập xóa file backup hết hạn website $NAME" 
phut=$(expr $ngay \* 60 \* 24)

cat >"/etc/wptt-auto/$NAME-delete-backup" <<END
#!/bin/bash
find /usr/local/backup-website/$NAME -type f -mmin +$phut -delete 2>/dev/null
END
chmod 740 /etc/wptt-auto/$NAME-delete-backup

cat >"/etc/cron.d/delete$NAME.cron" <<END
0 2 * * * root /etc/wptt-auto/$NAME-delete-backup >/dev/null 2>&1
END


if $(cat /etc/*release | grep -q "Ubuntu") ; then
	NAME_CRON_ubuntu=${NAME//[.]/_}
	ln -sf /etc/cron.d/delete$NAME.cron /etc/cron.d/delete${NAME_CRON_ubuntu}_cron
	systemctl restart cron.service
else
	systemctl restart crond.service
fi

_rundone "Thiết lập xóa file backup hết hạn website $NAME" 

echo "Thiết lập tự động xoá file backup website $NAME: $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log

echo "========================================================================="
echo "cứ vào lúc 2 giờ sáng hàng ngày"
echo "hệ thống sẽ tự động xóa file backup trong thư mục /usr/local/backup-website/$NAME file nào đã được tạo trước $ngay ngày sẽ tự động xóa"
echo "========================================================================="

check_menu_wptangtoc_active=$1
if [[ $check_menu_wptangtoc_active = "98" ]];then
. /etc/wptt/wptt-backup-restore-main 1
fi

