name: WPTangToc OLS CI/CD & Security

# Kích hoạt Robot khi sếp đẩy code lên nhánh main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # -------------------------------------------------------------
  # ROBOT 1: QUÉT CÚ PHÁP BASH (SHELLCHECK)
  # -------------------------------------------------------------
  shellcheck:
    name: Quét lỗi cú pháp Bash
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Tải mã nguồn về máy ảo GitHub
        uses: actions/checkout@v4

      - name: 🔍 Chạy ShellCheck toàn bộ dự án
        uses: ludeeus/action-shellcheck@master
        env:
          # Bịt mắt ShellCheck với 3 mã lỗi kinh điển do include file, trên hệ thống github không thể include thư mục /etc/wptt như linux đuợc
          SHELLCHECK_OPTS: "-e SC1091 -e SC1090 -e SC2154"
        continue-on-error: true
        with:
          scandir: './'

  # -------------------------------------------------------------
  # ROBOT 2: QUÉT BẢO MẬT & LỘ LỌT API KEY (GITLEAKS)
  # -------------------------------------------------------------
  security-scan:
    name: Quét rò rỉ Mật khẩu/API Key
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Tải mã nguồn về máy ảo GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Tải toàn bộ lịch sử commit để quét sâu

      - name: 🛡️ Chạy quét Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
